### ISSUE TITLE
Accessing cookie information

### ISSUE THREAD

**Issue by chrismelikian** [graphql-java/graphql-java#1000]
Hi,

If we have a secured GraphQL API which uses a JWT token inside a cookie, how would we access that from our code, specifically a GraphQLQueryResolver implementation? Are we really needing the browser JS to extract the JWT token and put it in the GraphQL query? I hope there's a better way.

Thanks, Chris.

**Comment by bbakerman** [comment]
use the "context" object that is set up on the ExecutionInput.
     
     InventedContext ctx = InventedContext.newCtx().setJwt(jwtTokenFromCookie()).build();
     ExecutionInput.newExecutionInput().query(queryText).context(ctx).build

**Comment by bbakerman** [comment]
I am going to close this issue because graphql-java does not deal with HTTP on purpose and instead this is an issue for another library
