### ISSUE TITLE
Default data fetcher should fetch from fields

### ISSUE THREAD

**Issue by mattwigway** [graphql-java/graphql-java#101]
The default data fetcher (PropertyDataFetcher) first checks if an object is a map, and, if so returns the appropriate value. If not, it looks for a getter for the value. FieldDataFetcher will fetch data directly from a field. It would be nice if these were combined in the default fetcher, so data will be fetched from a Map, getter, or field, whichever is present.

**Comment by mattwigway** [comment]
Thanks @tuukka!

**Comment by danielkwinsor** [comment]
Done
