### ISSUE TITLE
Expose schema directives in introspection

### ISSUE THREAD

**Issue by escitalopram** [graphql-java/graphql-java#1017]
As currently implemented (at least as of 7.0), it is possible to put directives on type definitions as well as on field definitions. This is really handy for placing hints for DataFetchers into the schema file and it works flawlessly.

I would also like to pass on this extra information to the client. However, it seems that as per spec, these directives are not exposed in the introspection feature.

I wonder what the position of the development team would be on extending the introspection code to support that, despite it being not specified by Facebook. I'm currently considering to code it myself and contribute it.

**Comment by bbakerman** [comment]
The main contributors are currently both on extended vacation...we will get
back to you in a few weeks

**Comment by bbakerman** [comment]
So introspection shows the schema types and it could show directives (non spec)

But what are the user cases that graphql clients can do knowing that a back end type as a @foo directive on it.

They cant know what foo does to the schema def.  Its already too late since the directives are applied in behaviour terms.

So I am trying to get insight in what a client could do if it KNEW that a @foo was on field X?

Also note - there are changes coming in 9.0 that allows you to wire in behaviour in once place to ALL directives on all fields say.

**Comment by escitalopram** [comment]
I'm using a GraphQL server which dynamically extracts its type definitions from a CMS (in order to be able to read from and write to it). I put directives on fields, that inform the data fetchers how to access the data in the actual CMS.

The data the CMS provides for its types are quite comprehensive, e.g. it would also contain labels to use for the UI of the client application, which I would like to be able to pass on to the GraphQL client, so that I only need to maintain my types in the CMS and everything down to the GraphQL client application doesn't need to be touched when CMS types are added/changed.

My client already has to use introspection to list the types and fields, and it would seem bad design to me, if I had to use an additional mechanism (and query) to obtain the rest of the (CMS-)type information, when directives are already there.

**Comment by bbakerman** [comment]
OK I can see your use case better.  IN some ways you need "extra metadata" to be carried with a type and see "directives" as a way to provide that.

I am not adverse to a PR that added Introspection metadata to the types.

The trick would be to "distunguish" it from "standard" meta data in some way via naming say.  I consumer should be able to "know" that they are getting non standard introspection and hence distunguish it from the "standard / any graphql server implementation" type data

**Comment by escitalopram** [comment]
Ok, thank you. Due to our project planning here, I guess it will take at least a month until I can come up with an actual pull request.

**Comment by bbakerman** [comment]
I have re-opened this - its a valid feature request

**Comment by kaqqao** [comment]
There's an issue tracking the exact same request in the spec: https://github.com/facebook/graphql/issues/300

There were also some discussions on how to distinguish the introspectable meta vs the current _private_ meta.

**Comment by yarinvak** [comment]
Is it going to be implemented soon?

**Comment by bbakerman** [comment]
Soon?  No - not soon.  Not never.. but its not actively planned yet

**Comment by yarinvak** [comment]
I think that this feature could be very helpful. Exposing metadata on the schema can be very useful - for example, if we wish to create a separate service which validates queries sent to a graphql service, and we wish to restrict inputs. With directives, we will be able to expose the input validation restrictions through the graphql schema (and the service will be able to be updated with the validation restrictions by sending an introspection query to the graphql service).
I don't see any reason to not expose directives in the introspection query as the schema is pretty much public and the goal of the introspection query is to provide a way to understand and query the schema. Directives are inherentic part of the schema and I don't see any reason why to not expose it.

If I would like to PR this issue, it could be accepted by you? Or do you have any suggestion how to expose a service metadata without extending the introspection?

**Comment by kaqqao** [comment]
The problem with implementing stuff while the spec is still under discussion is that it may easily end up conflicting with the spec in the future... And then unpleasant breaking changes become inevitable.

Also it is very much not safe to simply expose the directives blindly. They're often used to control access and visibility, and exposing that is game over.

**Comment by andimarek** [comment]
we will want to address this, but as @kaqqao pointed out it is not covered by the spec. Not sure yet what/how we gonna do.

**Comment by bhabegger** [comment]
Any news here ? I'm interested :)

**Comment by bbakerman** [comment]
See https://github.com/graphql-java/graphql-java/pull/2221

**Comment by hinsxd** [comment]
@kaqqao Hi there, how did you eventually solve your problem? We are in a similar situation that we need to mark a certain field in an InputObject to indicate that it is the ID of another entity, so that we can render the correct Select menu for that entity. But scalar can carry too little info and we cant use InputObjectType for that field. Please give me a hand if you have solved that problem. Thanks!
