### ISSUE TITLE
Concurrent execution of queries

### ISSUE THREAD

**Issue by dgruntz** [graphql-java/graphql-java#1019]
I have just executed the following query:

```
query {
  p1: getProduct(productId: 1) {
    id
  }
  p2: getProduct(productId: 2) {
    id
  }
}
```
However, the two queries were executed sequentially by the same thread. Should such queries not be executed concurrently? I have printed entry and exit in my method (and added a `Thread.sleep(10000)` in the implementing method):

```
>> getProductById(1) 17:54:14 Thread[qtp331122245-17,5,main]
<< getProductById 17:54:24 Thread[qtp331122245-17,5,main]
>> getProductById(2) 17:54:24 Thread[qtp331122245-17,5,main]
<< getProductById 17:54:34 Thread[qtp331122245-17,5,main]
```

**Comment by bbakerman** [comment]
If the DataFetchers are multi threaded then it will be asych other wise
it's single threaded

We have avoided opinionated multi threading because it makes for bad
library design....however you can make you DataFetchers use threads...
