### ISSUE TITLE
GraphQLError in Kotlin is cause an Accidental Override

### ISSUE THREAD

**Issue by vagostep** [graphql-java/graphql-java#1022]
When i try to create a custom exception that implements GraphQLError cause an Accidental Override in the getMessage error in Kotlin

It's cause because the interface GraphQLError have a method called getMessage(), and the class Throwable also have the same method. 

So, the custom exceptions need extends of Throwable and implements GraphQLError and this cause a compiler error "Accidental Override"

**Comment by bbakerman** [comment]
Can you explain more about accidental override rules in Kotlin?    I am not
familiar with the language restorations and how we are not playing ball
correctly

**Comment by vagostep** [comment]
@bbakerman In Kotlin, the class [Throwable](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-throwable/index.html) has a member called "message". Kotlin automaticaly create a setter and getter with this name (getMessage and setMessage). So, this method cause the accidental override with the abstract method in the interface GraphQLError getMessage() when i extends of Throwable and implements GraphQLError. 

Here was the same problem notify by another user: https://stackoverflow.com/questions/48698699/accidental-override-the-following-declarations-have-the-same-jvm-signature-wh

**Comment by bbakerman** [comment]
I have asked colleagues at Atlassian about this problem.

The consensus was that this is a challenge even in native Kotlin

```
interface GraphQLError {
	fun getMessage(): String
}

class FeatureFlagFetchException(s: String?) : RuntimeException(s), GraphQLError
```

Their suggestion as a work around was to declare a .java file that represents the custom exception

**Comment by vagostep** [comment]
@bbakerman Great. It would not have even occurred to me to use Java-Kotlin interoperability in this case. I will implement it

**Comment by Arcnor** [comment]
For anybody else stumbling upon this problem, the related Kotlin issue is https://youtrack.jetbrains.com/issue/KT-6653

**Comment by ryandanielspmc** [comment]
Based on the links that @Arcnor provided, there is a solution there that worked for me. Below is my implementation of that solution.
```kotlin
class CustomException(@JvmField override val message: String) : RuntimeException(message), GraphQLError  {

    override fun getMessage(): String? = super.message

    override fun getLocations(): MutableList<SourceLocation> = mutableListOf()

    override fun getErrorType(): ErrorClassification = CustomErrorClassification()
}

class CustomErrorClassification : ErrorClassification
```

**Comment by binkoni** [comment]
> Based on the links that @Arcnor provided, there is a solution there that worked for me. Below is my implementation of that solution.
> 
> ```kotlin
> class CustomException(@JvmField override val message: String) : RuntimeException(message), GraphQLError  {
> 
>     override fun getMessage(): String? = super.message
> 
>     override fun getLocations(): MutableList<SourceLocation> = mutableListOf()
> 
>     override fun getErrorType(): ErrorClassification = CustomErrorClassification()
> }
> 
> class CustomErrorClassification : ErrorClassification
> ```

This solution is not working anymore in Kotlin 1.6
```console
@JvmField cannot be applied to a property that overrides some other property
```

**Comment by bbakerman** [comment]
See https://github.com/graphql-java/graphql-java/issues/1022#issuecomment-386857203

**Comment by bonobonohu** [comment]
> See [#1022 (comment)](https://github.com/graphql-java/graphql-java/issues/1022#issuecomment-386857203)

"Their suggestion as a work around was to declare a .java file that represents the custom exception"
- haha, i came to this same conclusion as well only a few minutes ago. 😉 
only... only in this case you won't have a "pure" Kotlin application - whatever the meaning of this. 🤷‍♂️

**Comment by bbakerman** [comment]
> only in this case you won't have a "pure" Kotlin application
Think of it as a pure JVM application however ;)

**Comment by bonobonohu** [comment]
hey guys, i've just ran into this page accidently now:
https://kotlinlang.org/docs/java-to-kotlin-interop.html#handling-signature-clashes-with-jvmname
i'm not sure, since i did not cope with this since then, but... could we utilize this to get rid of this issue?
```@get:JvmName("message")``` maybe?
will get into context/try it out soon and keep you updated (or delete this comment, if it turns out i'm on the wrong track).

**Comment by ArisPoz** [comment]
So the only workaround to this issue is to create a Java class with the custom exception?

**Comment by chuck-park** [comment]
make custom exception class extends the class extends RuntimeException and implement GraphQLError.
[It](https://betterprogramming.pub/error-handling-with-graphql-spring-boot-and-kotlin-ed55f9da4221) said "because a Kotlin class can’t extend RuntimeException and implement GraphQLError at the same time."

**Comment by Satook** [comment]
There is a useable class already in GraphQL-Java. `GraphqlErrorException`

Was added to address this ticket: https://github.com/graphql-java/graphql-java/pull/1743

The file is here: https://github.com/graphql-java/graphql-java/blob/18.x/src/main/java/graphql/GraphqlErrorException.java
It was added in v14 and is still there now for Kotlin compat.
