### ISSUE TITLE
Relay SimpleListConnection accepts the data only in constructor

### ISSUE THREAD

**Issue by timony** [graphql-java/graphql-java#104]
The constructor SimpleListConnection(List<?>) is the only way how to setup the fetcher's data. Since the data field on the SLC is private, there is no way how to alter the result list with the attributes that come from the DataFetchingEnvironment that comes as parameter of the get method.

There should be a way how to use the relay support with the attributes of the field..

or this is the way to do it?:
```java
public Object get(DataFetchingEnvironment env) { 
  String regex = (String) environment.getArguments().get("regex"); 
  List<SomeObject> result = SomeService.getData(regex); 
  return new SimpleListConnection(result).get(env); 
}
```

Still thinking if this req is not beyond the GraphQL scope since it is not CRUD..

What you think?

**Comment by bbakerman** [comment]
Your example of delegating to the .get() method is how you do it
