### ISSUE TITLE
What are you thoughts on validation?

### ISSUE THREAD

**Issue by exbe** [graphql-java/graphql-java#1041]
Current design doesn't allow to natively validate variables against schema as well easily fix issues highlighted in #865.

I think this can be fixed with different design, which would enabled parser hooks to access graphql schema.

Any thoughts?

**Comment by bbakerman** [comment]
The parser doesn't need to hook into validation.  Its job is to built an AST tree that is syntactically correct and allow that to be validated and then executed.

By parser do you mean AST node traversal?  

You say `natively validate variables`.  What does native mean?   There is a prejudicial implication there that its currently "non native"  but I dont know what you mean by native?

We have fairly extensive validation in place (as define by the graphql spec).  So I am wondering what the exact problem definition is that we need to fix by new code designs?

**Comment by exbe** [comment]
I can use arguments to narrow result. It is possible to use any valid type. 
```
query HeroNameAndFriends {
  hero(episode: "JEDI") {
    name
    friends {
      name
    }
  }
}
```
Existing validation works fine, since input is a part of AST.

However, if I use variables like in the following
```
query HeroNameAndFriends($episode: Episode) {
  hero(episode: $episode) {
    name
    friends {
      name
    }
  }
}
```  
with `{
  "episode": "JEDI"
}`, what is the expectation? 

Variables are not part of AST, only few validation rules are getting invoked (like NoUnusedVariables).  VariableReference is the only type, which appears in AST for variables and this makes sense, since variables are passed down through another codepath which bypasses validation. As in result, it is not getting validated against type system in any way.

The library responds differently for semantically same arguments values, where the only difference is the way one use it (inline vs variables).

This is critical for mutations:
```
mutation CreateReviewForEpisode($ep: Episode!, $review: ReviewInput!) {
  createReview(episode: $ep, review: $review) {
    stars
    commentary
  }
}
``` 
with `{
  "ep": "JEDI",
  "review": {
    "stars": "XXXXX",
    "commentary": false
  }
}`
would call data fetcher with bogus data.  If I change this query to provide inline input, it would raise validation errors.

My expectations is that validation should happen regardless of input method (inline vs variables).
Does this make sense?

**Comment by bbakerman** [comment]
I am not convinced we need to change the parser code to implement query validation.

We already have a post parse validation step that takes the AST and variables map and check preconditions to ensure it is valid.  

This code was based on the reference JS implementation and the spec.  We have gone through several iterations of it over the last 2 years to get it as correct as possible.

And while nothing is perfect, it has served us really well.  So I am hesitant to "change the parsing" and move the same validation rules into that, since it really already is in place.
