### ISSUE TITLE
Match new spec for non-null attributes with default values

### ISSUE THREAD

**Issue by filipncs** [graphql-java/graphql-java#1046]
The spec was recently changed to clarify what to do with non-null attributes with default values:
https://github.com/facebook/graphql/pull/418

I've added a PR to illustrate how we don't live up to the new spec:
https://github.com/graphql-java/graphql-java/pull/1045

Thoughts? I think it should be a fairly simple fix for this case, but maybe this would cause other problems?

Note that this was a specific issue I ran into with trying to use the new spec, there could easily be other issues that should be fixed.

**Comment by bbakerman** [comment]
Thanks for reporting.  I will look at the PR and comment there.

For the record there was a LOT of angst about defaulting null values in the new spec.  A lot!
