### ISSUE TITLE
Why DataFetchingEnvironment.getRoot always null?

### ISSUE THREAD

**Issue by FutureElement** [graphql-java/graphql-java#1057]
this is my schema
```
type User{
    id: Long
    name: String
    age: Int
    birthday: String
    height: Float
    weight: Float
    married: Boolean
    description: String
    group: Group
}

type Group {
    id: Long
    name: String
    users: [User]
    description: String
    test: Test
}

type Test {
    id: String
}
```
I want get User`s id， but when i use getRoot in the DataFetcher, the result is null
```
public class TestDataFetcher implements DataFetcher {

    @Override
    public Object get(DataFetchingEnvironment environment) {
        Object o = environment.getRoot();
        System.out.println("root = [" + o + "]");
        return new Test();
    }
}
```
only can getSource to get the parent object ? can`t get root?

**Comment by bbakerman** [comment]
You need to use ExecutionInput to specify it

```
        HashMap<String,Object> variablesMap = new HashMap<>();
        variablesMap.put("var1","value1");
        
        ExecutionInput executionInput = ExecutionInput.newExecutionInput()
                .query('{ yourquery { name } }')
                .variables(variablesMap)
                .context(new SomeContextObject())
                .root(new SomeRootThing())
                .build();
```

The roor is fixed for the life of the query.  It also is the seed for the `environment.getSource()`

Each object returned then becomes the new `environment.getSource()` as you descend the query.

The context is also an object of your choosing.  Its a helper for you in every data fetcher for "context"

**Comment by bbakerman** [comment]
generally a data fetcher wont access the root but rather its a way to "seed" the object tree.

So assuming you have a query like

     {
       user(id : 123) {   # at this point you have a fetcher that returns a User object
           name
           group {  # at this point the User object is the source and your looking for groups in the DF
              name
              test {  # at this point the group object is the source and you are looking for a Test object in the DF
                  id
              }
       }
    }

**Comment by andimarek** [comment]
closing it, because the question was answered, please reopen @FutureElement if something is still unclear
