### ISSUE TITLE
Declaration of empty types wit empty body fails

### ISSUE THREAD

**Issue by tipok** [graphql-java/graphql-java#1059]
Issue #903 introduced empty types, but if the type is declared with an empty body, parsing will fail. 
Once changed the `+` with `*`, in this line, the parser is able to parse it correctly.

https://github.com/graphql-java/graphql-java/blob/06ee733dd535e7fcfc4f9c5b1eb5429b4b245eb0/src/main/antlr/GraphqlSDL.g4#L51

Example:

```GraphQL
type MyType {

}
```

**Comment by andimarek** [comment]
thanks @tipok for reporting it ... would you be interested in creating a PR for that? 
It should consist of the changed grammar and at least one unit test which ensures that it works expected. (Under assumption this change doesn't have any other side-effects)

**Comment by bbakerman** [comment]
Actually from the new and soon to be official spec we have this requirement.

> An Object type must define one or more fields.

So while I agree it would be nicer for the document to "parse" and get validation errors later, be aware that `type MyType {}` is invalid and wont be allowed later.

What is not clear in the spec is whether you are allowed to have an empty type and then "extend type" it so it does have fields.

**Comment by tipok** [comment]
@bbakerman in my case this is totally fine, i'm just using the parser here and failing during validation is totally fine
