### ISSUE TITLE
Anything to cache the static Queries, to save query parsing over repeated queries?

### ISSUE THREAD

**Issue by themanojshukla** [graphql-java/graphql-java#1060]
I don't know if we have anything to cache the static queries??

To static query, I mean, the queries which maybe frequent, and non-changing structure.
For example, say, clients dashboard is something that always shows data about all the posts he has written and first 5 comments on each post.
So, the query could be..

     Query AuthorDashboardQuery{
        author(id: $UserId){
            firstName
            lastName
                posts{
                id
                title
                comments(first: 5){
                    id
                    commentValue
                    user{
                        id
                        firstName
                        lastName
                    } 
                }
            }
        }
     }

Now, assume, this query is gonna be fired by all the users as soon as they login/visit dashboard.
Just the value for `$UserId` would be changing.. but making it as input variable, we can have the same query eligible to be cached, and while running, we can provide the input `$UserId`.

So, now once if this query has been parsed by the parser it's parsed output is never going to be changed. And if we could cache them, we can reduce the parsing/traversal time for graph (as it's already damn high for Breadth-First-Search trees). 

I don't know if there is something similar to this already in `GraphQL-Java` implementation or not?
Or If it is good idea or not?

**Comment by andimarek** [comment]
Please have a look here: http://graphql-java.readthedocs.io/en/latest/execution.html#query-caching

**Comment by bbakerman** [comment]
Yeah as linked to above you can do exactly what you want with graphql-java via `PreparsedDocumentProvider`

Some people in the wild are trying an even more aggressive technique on the client and server where they have a protocol for dispatching a query via a hash. 

The client creates a #hash of the query text and sends it up.  If the server has seen it, then it gets that query from its cache and executes it. So 1 HTTP request and very little layload on the way up.

If the server hasnt seen it, it responds with a 3xx and the client sends the full query.  The server then saves that query and the calculated hash.

This requires complete co-origination between the client and server and is custom.  Its not defined in spec.  But it does save a lot of bandwidth depending on usage and frequency.

To do the above you would need to build the client/server behaviours yourself.

**Comment by themanojshukla** [comment]
Thanks @andimarek for the link, and @bbakerman for detailed description. Thank you so much. That meets my concern, so closing this request.!!
