### ISSUE TITLE
RuntimeException classification

### ISSUE THREAD

**Issue by tinnou** [graphql-java/graphql-java#1063]
## Context:
Errors in graphql-java are split up into two groups.
1. GraphQLError (formatted according to the spec and is presented as part of the errors block in the response)
2. RuntimeException (Pure java exception to denote an irrecoverable error where the execution could either not start or no longer proceed)

Since RuntimeExceptions are bubbled up back to the caller of graphql-java it is important for the exception to be classified so they can be acted upon.

## Problem:
The current exception hierarchy doesn’t allow graphql-java users to effectively make the difference between logical groupings of errors.

In order to define what these logical groupings are, we must first identify the types of users interacting with the library (directly or indirectly). I identified three types:
1. the **client developer** who writes and executes GraphQL queries against the application.
2. the **API developer** who defines the GraphQL schema, writes the data fetcher logic, invents custom scalars, wires type resolvers, and wraps graphql-java into a working application.
3.  the **graphql-java maintainer** is the developer who builds and maintains the library.

Naturally, when an error happens, the API developer should be able to easily tell who is effectively responsible for the error.
For example, if the schema doesn’t provide the mandatory query field, the API developer would be responsible. If a GraphQL query is syntactically incorrect, the client developer would be responsible.

Today, the API developer has to keep track of all the possible exceptions thrown by GraphQLJava if he/she wants to be able to classify them into one of three categories (internal error, API backend error, or client error). Further more, there is no guarantee the list will remain the same in the future.

## Proposal
Consequently, a proposal would be to map the top of the exception tree (with **GraphQLException** at the top) to the 3 kind of errors:
 * a GraphQL request validation error (client error)  - **GraphQLQueryException**
 * a schema error, a data fetching error or a data complete error (API  backend error) - **GraphQLInstanceException**
 * an internal error from the graphql-java library (internal error)  - all other runtime exceptions and other GraphQLException

I put together a tree of the various exceptions that can be thrown from the library using UML: 
[Current exception hierarchy Image .pdf](https://github.com/tinnou/graphql-java/blob/exception-hierarchy/ExceptionTree.pdf)
[Current exception hierarchy UML, can be opened in Intellij](https://github.com/tinnou/graphql-java/blob/exception-hierarchy/ExceptionTree.uml)

I then changed the code to reflect the proposal, leading to the following UML diagram:
[Exception hierarchy Proposal Image .pdf](https://github.com/tinnou/graphql-java/blob/exception-hierarchy/ExceptionTreeProposal.pdf)
[Exception hierarchy Proposal UML, can be opened in Intellij](https://github.com/tinnou/graphql-java/blob/exception-hierarchy/ExceptionTreeProposal.uml)

**GraphQLException** is still at the top but is now broken down into three groups, **[GraphQLInstanceException](https://github.com/tinnou/graphql-java/blob/exception-hierarchy/src/main/java/graphql/GraphQLInstanceException.java#L11)**, **[GraphQLQueryException](https://github.com/tinnou/graphql-java/blob/exception-hierarchy/src/main/java/graphql/GraphQLQueryException.java#L11)**, and all other internal exceptions such as **[AssertInternalException](https://github.com/tinnou/graphql-java/blob/exception-hierarchy/src/main/java/graphql/AssertInternalException.java#L5)** which reflects unexpected library errors.

As a side note, **AssertException** needed to be broken down into **AssertInternalException** and **AssertException** because it is used for both [library errors](https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/Assert.java#L25) and [API developer errors](https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/Assert.java#L53) (and maybe client errors?).

I will attach the initial PR shortly.

**Comment by dondonz** [comment]
Closing this old issue, as the PR accompanying it was closed. Might be restarted in the future
