### ISSUE TITLE
every development version is published to maven central

### ISSUE THREAD

**Issue by andimarek** [graphql-java/graphql-java#1067]
Every development version is now published to maven central (with the new version pattern: "time#git-hash"),

we should update the docs accordingly 

cc  @bbakerman @tinnou

**Comment by andimarek** [comment]
I had to change the version to <date-githash> (replace # with -) to make it work with the automatic maven central sync.
Is that an issue @tinnou ?

**Comment by tinnou** [comment]
Shouldn't be a problem, I'll confirm tomorrow.
By the way, I'm already seeing some versions in Bintray already https://bintray.com/andimarek/graphql-java/graphql-java/2018-06-04T05-35-18-e5b324e and Maven seems to have a couple of versions too http://search.maven.org/#artifactdetails%7Ccom.graphql-java%7Cgraphql-java%7C2018-06-04T04-37-12%7Cjar (without the hash though), I presume you were most likely testing it. Also, Maven Repository package propagation can be slow. 

In all, a big thank you for adding maven sync for development versions!

**Comment by andimarek** [comment]
yes it is already working. :-)

**Comment by bbakerman** [comment]
Done

**Comment by mateusz-bajorek** [comment]
Ping!
Looking at https://mvnrepository.com/artifact/com.graphql-java/graphql-java - it seams like you are still publishing the nightlies over to mvn central. The normal releases are there (i.e. 11.0 etc.) but development builds as well (2019.01...). It would be good if you could publish those to a snapshot repository rather than release one.
What do you think?

**Comment by andimarek** [comment]
@mateusz-bajorek why is that problem for you? We publish the dev builds on purpose to maven central with real versions numbers so that people can actually use them if they need/want early releases.

**Comment by mateusz-bajorek** [comment]
Sure, here is my reasoning:
- there is noise in the maven repository page, you need to scroll around 7 screens down to find the actual latest release (I always tend to look at maven repo page first, before the github releases)
- you can push dev builds to a snapshot maven repository and it only requires the devs who want to use them to include reference to the snapshots repo like described here https://maven.apache.org/guides/mini/guide-multiple-repositories.html 

That way: people who want to use those builds still have no issue in doing so, and it's clear they are not full releases. I think this is the industry standard to follow such process.

**Comment by andimarek** [comment]
I understand the first point, but it should not be such a big burden imho. I would expect that you have to look up the release notes  anyway on github if you want to upgrade.  
Also please follow our twitter account https://twitter.com/graphql_java if you wanna be informed about new releases. 

The problem with publishing to other repos than maven central is that some organizations don't allow easy access to them. So adding another repo is often not really an option in bigger enterprises.
