### ISSUE TITLE
PreparsedDocumentEntry is not serializable for caching 

### ISSUE THREAD

**Issue by arian** [graphql-java/graphql-java#1071]
I hit this exception when trying to use `preparsedDocumentProvider`.

```
[INFO] [talledLocalContainer] javax.cache.CacheException: Unexpected error making a copy of entry graphql.execution.preparsed.PreparsedDocumentEntry@85840b0
[INFO] [talledLocalContainer]   at org.infinispan.jcache.embedded.functions.Invoke.copy(Invoke.java:88) ~[infinispan-jcache-9.2.3.Final.jar:9.2.3.Final]
[INFO] [talledLocalContainer]   at org.infinispan.jcache.embedded.functions.Invoke.lambda$apply$1(Invoke.java:53) ~[infinispan-jcache-9.2.3.Final.jar:9.2.3.Final]
[INFO] [talledLocalContainer]   at org.infinispan.jcache.embedded.functions.MutableEntryWrapper.exists(MutableEntryWrapper.java:36) ~[infinispan-jcache-9.2.3.Final.jar:9.2.3.Final]
[INFO] [talledLocalContainer]   at org.springframework.cache.jcache.JCacheCache$ValueLoaderEntryProcessor.process(JCacheCache.java:120) ~[spring-context-support-5.0.6.RELEASE.jar:5.0.6.RELEASE]
....
```

It's because we use infinispan through the jcache api. By default it uses *[store by value][]* where the infinispan implementation tries to serialize the value. 

That way you could also use a replicated cache for the parsed queries. However for this use-case it'd probably be slower and better to use a local cache only. In that case you can store the entries by reference, so in the jcache configuration use `configuration.setStoreByValue(false)`. After setting that configuration caching works because the `PreparsedDocumentEntry` won't be serialized.  (Perhaps defining an [infinispan externalizer][] would work too, but actually not necessary for a local-only cache).

[store by value]: https://static.javadoc.io/javax.cache/cache-api/1.0.0/javax/cache/configuration/Configuration.html#isStoreByValue()
[infinispan externalizer]: http://infinispan.org/docs/9.2.x/user_guide/user_guide.html#user_defined_externalizers

**Comment by bbakerman** [comment]
I am guess you would like the PreparsedDocumentEntry to be serialisable.  Its the inner `Document` that is the challenge.  Its the AST tree of a parsed query (built via ANTLR)

Can you give us a pseudo code example of how your are expecting to jcache the objects in your `graphql.execution.preparsed.PreparsedDocumentProvider`

**Comment by bbakerman** [comment]
The errors and Nodes are now Serialisable
