### ISSUE TITLE
Exception handling differs in `AsyncExecutionStrategy` and `AsyncSerialExecutionStrategy`

### ISSUE THREAD

**Issue by alexgenco** [graphql-java/graphql-java#1072]
We found some surprising differences between the `AsyncExecutionStrategy` and the `AsyncSerialExecutionStrategy` with regards to handling `AbortExecutionExceptions` thrown from custom instrumentations.

In the former, if you throw an `AbortExecutionException` in `beginFetchField` with a list of `GraphQLError`s, the errors correctly get added to the response errors object. However if you do the same using the `AsyncSerialExecutionStrategy`, the errors aren't added to the response. The former case seems to enter [this `catch`](https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/GraphQL.java#L478-L484), whereas the latter doesn't.

Is there a way to consolidate the behavior so we can get the same error messages regardless of the strategy? (we're using async for queries and async-serial for mutations).

Thanks!

**Comment by bbakerman** [comment]
Yes they should nominally behave the same and you are using them right (for queries and mutations say).  

Feel free to create a unit test showing this problem and perhaps even a PR to fix it.

We will look at this issue when we get a chance otherwise.

**Comment by andimarek** [comment]
This is fixed with #1083
