### ISSUE TITLE
Relay Modern support

### ISSUE THREAD

**Issue by oeil** [graphql-java/graphql-java#1093]
Hello guys, is there any plans for supporting "Relay Modern" out-of-the box? Thanks - great work with the lib BTW.

**Comment by bbakerman** [comment]
@oeil - as far as I can tell, we do support Relay Modern - last time I checked the server side implementation hadn't changed shape when they brought out Relay Modern.

But I haven't it super closely so if can list whats different (on the server) then we would consider implementing it

**Comment by andimarek** [comment]
I tried to find a definitive answer if the server side spec changed, but I could not find it. But the server side spec seemed to be unchanged, so we should assume for now that the relay support is also good for Modern.

**Comment by bbakerman** [comment]
I looked into this.  Our Relay helpers for connections and so on work with Relay Modern.

I am going to close this issue
