### ISSUE TITLE
Mutations and DataLoader dispatch problem

### ISSUE THREAD

**Issue by arlampin** [graphql-java/graphql-java#1099]
I ran into DataLoader dispatching issues when trying to execute a GraphQL mutation that returns an object that has DataLoader backed fields. I couldn't find any way to trigger DataLoader dispatch manually in the correct place to work around the problem.

Consider (simplified) schema
```graphql
type Company {
  id: ID!
  projects: [Project!]!
}
type Project {
  id: ID!
}
type Mutation {
  addCompany: Company
}
type Query {
  companies: [Company!]!
}
```
and the following query:
```graphql
mutation { addCompany { name projects { name }}}
```

If using default execution strategies (Async & AsyncSerial), the query never returns, instead it gets stuck fetching `company.projects`. The underlying DataLoader for `.projects` is never dispatched.

Executing the data fetching part alone works:
```graphql
query {companies { name projects { name }}}
```
Also, switching both query and mutation strategies to either AsyncExecutionStrategy or AsyncSerialExecutionStrategy works. It's just the (default) combination of Async and AsyncSerial that doesn't.

I've created https://gist.github.com/arlampin/06afeebb7b748c6cca90e7f8729b186b to demonstrate the problem.

**Comment by bbakerman** [comment]
We have looked into this issue and we now know what is causing it.

We missed the fact that mutations will be default using the AsyncSerialExecutionStrategy and that the dispatch calls for that are not being made at the right time (as they are in serial).

We haven't yet worked out the best way to fix this but are working on it.

Thanks for reporting it.

**Comment by bbakerman** [comment]
The initial fix here is to disable data loader batching on mutations.  This will ensure that they queries work even if they are not as efficient as they can be.

The secondary and more proper fix involves working out how we can "transfer" from the spec required AsyncSerialExecutionStrategy to the non serial AsyncExecutionStrategy and keep the field reference counting correct.

The PR merged above is the first fix to get it work.  More will follow later

**Comment by Zache** [comment]
Is there any progress made on the secondary and proper fix for this issue?
