### ISSUE TITLE
dataFetcher on type?

### ISSUE THREAD

**Issue by skwakman** [graphql-java/graphql-java#11]
Hi!

I've been trying out your graphql java implementation and I found that it's not possible to add a datafetcher on the type level.  

Although I don't think it's part of the spec (it doesn't seem to define how to define datafetcher-like functionality), the [javascript reference implementation](https://github.com/graphql/graphql-js) supports .resolve() on both fields and types. Perhaps something to add in a next version?

**Comment by skwakman** [comment]
ah crap, I'm wrong about the graphQL javascript library supporting .resolve() on type level. Like the java counterpart, we need to create a root-level type to implement this.

Still though, it might be a handy addition?

**Comment by andimarek** [comment]
Hi,

I'm not sure I understand your proposal: You want a DataFetcher on a Type? I don't know if this makes sense ... could you give an example?

Thanks

**Comment by testower** [comment]
I believe what you are referring to is the "resolve" on fields on types. Any field can have a resolve or dataFetcher on it, in both the javascript reference implementation and in this particular java implementation. Whether that dataFetcher is on a field directly on the GraphQLObject given to the schema builder, or a sub-type, doesn't make a difference. It's still given on a field, not on a type.

**Comment by skwakman** [comment]
I was thinking of being able to define a datafetcher at the type level. 

Using the current API, setting a datafetcher would look like this:
```
 GraphQLObjectType shoe = newObject()
      .name("Shoe")
      .fields(Lists.newArrayList(
        newFieldDefinition()
          .name("id")
          .type(new GraphQLNonNull(GraphQLString))
          .build()
      )).build();

GraphQLObjectType rootQuery = newObject()
      .name("root")
      .field(newFieldDefinition()
          .name(shoe.getName())
          .type(shoe)
          .dataFetcher(shoeFetcher)
          .build()
      ).build();
```
In this example I have a service somewhere which can retrieve shoes. Defining how to fetch this shoe, requires me to add this to the query object as part of a field. 
However it might be handy if I can do this from within the Shoe type, for example:
```
GraphQLObjectType shoe = newObject()
      .name("Shoe")
      .fields(Lists.newArrayList(
        newFieldDefinition()
          .name("id")
          .type(new GraphQLNonNull(GraphQLString))
          .build()
      ))
  .dataFetcher(shoeFetcher)
  .build();
```
One advantage of this that I can define how shoes are retrieved at one place, even if the type is used in more than one query object. 

My first post was created in the false assumption that the Javascript library supports this as well, but it doesn't. It's not much of a problem really, as using field level datafetchers it's still possible to create the same end-result. 

So mainly a brain-barf on my side. Perhaps it's better to keep feature-parity with the reference implementation to avoid any confusion.

**Comment by andimarek** [comment]
Ok ... I think I understand your proposal.

The problem with this change is, it might confuse more than it helps (Just my impression) 
Thats because it's a little bit against the idea, that you just describe a type with `newObject()...` and not where this data comes from. This you have todo on a concrete field.

So I would like wait for more feedback on this one: If more people wants this, I will add it.

But thanks for taking your time to report it and make it clear with your last comment,
Andi

**Comment by pli2014** [comment]
hi andimarek
when I integrated your code, I got an performance issue. for example, I searched a list data from server, which every snippet data need to be fetched again. 
{
 searchNewsList(status:0){
  data:{
       titile
      userId
      userFace
   }
}
}
userFace value need to be fetched again.  this is a N+1 issue.

Even though you designed a  strategy for data fetching.  I wanted a batch strategy, how does it work?

**Comment by andimarek** [comment]
@pli2014 Hi,

there is no batching strategy yet. But we have a PR, which is not merged yet. Maybe you could have a look at it and give some feedback if it would help you:
#49

**Comment by pli2014** [comment]
got it, it is very useful, I had integrated it in our product. breadth-first search or depth-first search, which do you like? 
BTW, I change your code to implement another feature that pass parent data to variable, I think it should be a common feature. 

For Example as below:
query user {
    userList{
       name
       userId
       friends(userId:$userId){
         name
       }
    }
       
}

generally, parent userId should be passed to friends selectionset, because userList data source is search result,and 
friends data source is another data fetching, but this variable depended $userId variable individually.

**Comment by andimarek** [comment]
@pli2014 The batching feature is now available in the latest dev build.

**Comment by pli2014** [comment]
@andimarek 
good job,  I have integrated this feature, it is very nice for me. expecting advance features.

**Comment by yrashk** [comment]
@pli2014 @andimarek 

Considering #49 is in, can we close this issue?
