### ISSUE TITLE
Argument's default value is invalid when containing backslash characters

### ISSUE THREAD

**Issue by EnilPajic** [graphql-java/graphql-java#1105]
Hi, 

I'm using `graphql-java` version `8.0`. Trying to make GraphQL query with arguments that have default values. Everything works fine, except this one particular case I need: when default value contains backslashes, quotes etc.

I'm using `graphql-spqr` to generate my schema, but nevertheless, problem exists also while schema is generated "manually". I'll provide MVCE bellow.

```java
final GraphQLSchema graphQLSchema = GraphQLSchema.newSchema()
    .query(GraphQLObjectType.newObject()
        .name("TestQuery")
        .field(GraphQLFieldDefinition.newFieldDefinition()
            .name("TestField")
            .type(Scalars.GraphQLString)
            .argument(GraphQLArgument.newArgument()
                .name("TestArgument")
                .type(Scalars.GraphQLString)
                .defaultValue("{\"operator\":\"eq\", \"operands\": []}") //<--- PROBLEM
                .build())
            .build()))
    .build();
```
This produces an `InvalidSyntaxError`: _**SchemaProblem{errors=[InvalidSyntaxError{ message=Invalid Syntax ,locations=[SourceLocation{line=6, column=50}]}]}**_ with warnings:
```
line 6:48 token recognition error at: '\'
line 6:49 token recognition error at: '\'
```

The generates schema is ill-formed:
```graphql
schema {
  query: TestQuery
}

type TestQuery {
  TestField(TestArgument: String = "{\\"operator\\":\\"eq\\", \\"operands\\": []}"): String
}
```

_(Note: the same schema is generated via `graphql-spqr` but only a warning is issued)_

IMHO, string `"{\"operator\":\"eq\", \"operands\": []}"` is perfectly valid, it is escaped properly etc. Actually, it is a serialized value of a valid JSON object.

I've managed to trace the function that does this transformation. It's called `jsonStringify` (reference: `graphql.language.AstValueHelper#jsonStringify`, [see link on master](https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/language/AstValueHelper.java#L162)) which looks like this:

```java
private static String jsonStringify(String stringValue) {
  stringValue = stringValue.replace("\"", "\\\"");
  stringValue = stringValue.replace("\\", "\\\\");
  stringValue = stringValue.replace("/", "\\/");
  stringValue = stringValue.replace("\f", "\\f");
  stringValue = stringValue.replace("\n", "\\n");
  stringValue = stringValue.replace("\r", "\\r");
  stringValue = stringValue.replace("\t", "\\t");
  return stringValue;
}
```

I don't know is this fully intentional, or I'm missing something, but first line replaces `"` with `\"`, and the second line replaces that newly inserted `\`with `\\`, thus producing `\\"` (and `\\"operator\\"` is the result).

I'd like to know is this is a bug, and if not, is there a workaround? I know I can set default value to e.g. `null` and then resolve that `null` in every GraphQL resolver (wiring), but is there a clearer way?

Maaaaybe related (but I'm not sure, because this was resolved in 2017, in 7.0 version, and it seems it is not the problem I'm facing): #863.

Thank you in advance!
Enil.

**Comment by bbakerman** [comment]
Thanks for the detailed bug.  We will investigate this.

**Comment by bbakerman** [comment]
I have a fix for this bug.  We will target a 9.x stable release

**Comment by EnilPajic** [comment]
Thank you very much for bug fix, I appreciate it! 

Suggestion: maaaybe, for performance, [`StringBuilder#new(int)`](https://docs.oracle.com/javase/7/docs/api/java/lang/StringBuilder.html#StringBuilder(int)) should be used when creating `StringBuilder` instance, and very good estimation is the `stringValue` parameter's size: `StringBuilder sb = new StringBuilder(stringValue.size());`

I'll close the issue now.
