### ISSUE TITLE
ChainedInstrumentation not finishing

### ISSUE THREAD

**Issue by kclaes** [graphql-java/graphql-java#1110]
Upgrading from 7.0 to 9.0.

I've been using a `ChainedInstrumentation` that chains `MaxQueryComplexityInstrumentation`, `DataLoaderDispatcherInstrumentation` and `TracingInstrumentation`. This worked well in 7.0.

Now, having updated the dependencies to 9.0 for graphql-java, 5.0.1 for graphql-servlet and 4.2.0 for graphql-spring-boot, a query that has to invoke more than one resolver sequentially, does not return.

I've narrowed it down to the following `Instrumentation` not working:
`return new ChainedInstrumentation(Arrays.asList(new DataLoaderDispatcherInstrumentation(...)))`
And the following does work:
`return new DataLoaderDispatcherInstrumentation(...)`

The queries that fail are hierarchical with resolvers, so for instance:
`{ entity(id=1) { property } }`,
will work if the property is fetched by a resolver without a batchloader, but will fail if the resolver for property also uses a batchloader (it simply does not get invoked/triggered).

Any pointers or things I can try?

**Comment by kclaes** [comment]
Confirmed fixed in 2018-07-04T08-09-58-795c232

**Comment by andimarek** [comment]
@kclaes thanks for confirming: it is released in 9.1 (released yersterday)
