### ISSUE TITLE
Consider semver-style third-level version releases for bugfixes

### ISSUE THREAD

**Issue by ind1go** [graphql-java/graphql-java#1114]
My company (and I suspect many others) have rules whereby open source projects need re-review, code scanning, etc, for major and minor version bumps, but don't need re-review for micro version bumps, i.e:

- 9.0 to 9.1 requires new review
- 9.0 to 9.0.1 wouldn't require new review

Would you consider adopting the 'standard' [semver](https://semver.org/) style whereby if it's purely a bugfix release, as 9.1 was, you just bump the micro- or third-level version rather than the minor- or second-level version?

Thanks for the consideration.

**Comment by bbakerman** [comment]
We are maintaining a stable branch now
