### ISSUE TITLE
Nullability shapes in fragments

### ISSUE THREAD

**Issue by freben** [graphql-java/graphql-java#1115]
Hey,

It seems like there's a regression in 9.1, compared to 9.0. For queries that use fragments, I now get the validation error `Validation error of type FieldsConflict: componentInfoLocationUrl: fields have different nullability shapes @ 'services'`.

This is an excerpt of the query:

```
query ($id: String!) {
  services(ids: [$id]) {
    componentInfoLocationUrl
    ...ComponentInformation
  }
}

fragment ComponentInformation on Component {
  componentInfoLocationUrl
}
```

from the schema:

```
type Query {
  services(ids: [String!]): [Component!]
}

type Component {
  componentInfoLocationUrl: String!
}
```

Again, this worked in 9.0, but broke in 9.1.

**Comment by freben** [comment]
If I remove the exclamation mark (`componentInfoLocationUrl: String`), it works.

**Comment by andimarek** [comment]
thanks a lot for reporting:

could you please try this build: "2018-07-13T04-59-30-f72244a". This should contain a fix for it.

**Comment by freben** [comment]
Confirmed working. That's great, thanks! Talk about quick turnaround.

**Comment by andimarek** [comment]
Version 9.2 is now released
