### ISSUE TITLE
commit message should be more meaningful  

### ISSUE THREAD

**Issue by hepin1989** [graphql-java/graphql-java#1121]
![image](https://user-images.githubusercontent.com/501740/42676397-9f628e7c-86aa-11e8-88a5-a146964f56cd.png)

like this kind is not very good:)

**Comment by andimarek** [comment]
I am sorry, but this is not a constructive way to improve the project: please open a new issue where you specify what exactly you would like to see in commit messages and why you wanna see it: how would it help you? 
Screenshots of this way especially is not helpful and just blame people (me or others).
Thanks
