### ISSUE TITLE
Add simple custom error handling

### ISSUE THREAD

**Issue by arcuri82** [graphql-java/graphql-java#1123]
Hi,
  trying to report custom error messages to my API users, but I am having some problems. I have read the documentation at [https://graphql-java.readthedocs.io/en/latest/execution.html](https://graphql-java.readthedocs.io/en/latest/execution.html), but I find it a bit cumbersome.

Business case: a user sends in a query that is correct for GraphQL (valid syntax), but then fails due to constrains (e.g., validation when data is saved to a database). It is a user error (what in a HTTP with REST would be a 4xx status code).

Ideally, I would like to just throw an exception with an error message, and have such error message be part of the `errors` field in the GraphQL response. And for such a basic case, I would like to use something already existing in `graphql-java`, and not having to write custom classes.

I looked at `graphql-java` API, and tried to use `graphql.servlet.GenericGraphQLError` which seemed doing exactly what I wanted. Unfortunately, it does not extend `RuntimeException`.

I hence copied&pasted that class, and made it extends `RuntimeException`. This worked, but, unfortunately, it has a MAJOR issue: the stacktrace is part of the response.

Ideally, I would like to just do a `throw X(msg)` where the message is shown to user with no stacktrace, and X is already part of `graphql-java` API. A possible name for X could be `GenericUserInputValidationGraphQLError`.

Related issues: #209 and #1063 
 
Or is there already a solution for it, and I missed it?

**Comment by bbakerman** [comment]
Take a look at `graphql.execution.DataFetcherResult`  It allows you to return a data result (which can be a value or null) and also errors at the same time.  You return it from your data fetcher

You can then write a little bit of helper code to turn exceptions into graphql errors.

Also there is a `ExecutionResult#toSpecification` that will remove all extra attributes from graphql errors such as stack traces.
