### ISSUE TITLE
GraphQLSchema.Builder forgets additionalTypes and additionalDirectives

### ISSUE THREAD

**Issue by samkline** [graphql-java/graphql-java#1127]
Hi, I wanted to raise what I suspect is unintentional behavior in GraphQLSchema.Builder.

The builder locally maintains a set of `additionalTypes` and `additionalDirectives`, but if you build using the `build(additionalTypes)` or `build(additionalTypes, additionalDirectives)` methods, then the builder's types and directives do not get applied, only the values passed in as arguments are included. 

For example, if you use the `build(additionalTypes)` method, there are no directives included in the returned schema, even if you just called `additionalDirectives(...)`.

I see two potential alternatives:
1. Eliminate the overloaded `build` methods and provide a single method with no args.
1. Change the `build(additionalTypes, additionalDirectives)` implementation to take the union of the passed-in values and the Builder's values.

I'm in favor of option 1 since it avoids all ambiguity, but would also be happy to submit a pull request for option 2 or another alternative if you'd like.

**Comment by bbakerman** [comment]
Seems fair - this would be a breaking change on those that call the overloaded method but its cleaner

**Comment by bbakerman** [comment]
See #1145
