### ISSUE TITLE
Move ResolvedGlobalId and related helper methods out Relay to util

### ISSUE THREAD

**Issue by marceloverdijk** [graphql-java/graphql-java#1128]
The `ResolvedGlobalId` and `toGlobalId` + `fromGlobalId` are not only useful when using Relay.
It's a good GraphQL to use global unique opaque id's.

My proposal is to move the `ResolvedGlobalId` and related helper methods in `Relay` to shared util package - or something like that - so it can be used without the `Relay` class itself. Now I'm creating my own `ResolvedGlobalId` which is a copy of the one in `graphql.relay.Relay`.

**Comment by bbakerman** [comment]
The idea of a "type + id" is a very much a realy thing where its need for the `node(id : $someId)` pattern so I think we will leave this under the relay name space

**Comment by marceloverdijk** [comment]
I always thought that Graphql was also recommending opaque id (not necessary "type + id" though).
But reading the spec again I cannot find it, even the examples use readable (simple numeric) id's.. so yes better to keep it in the relay name space.
