### ISSUE TITLE
Allow a data fetcher to navigate up the field parent structure

### ISSUE THREAD

**Issue by bbakerman** [graphql-java/graphql-java#1132]
Today you can go down the field hierarchy but not upwards

For example

```
{
    grandparentfield {
          parentfield {
               childfield {
          }
}
```

today in the `parentfield` data fetcher you can see the child field but you can see the grandparentfield easliy

We should add this

**Comment by semaphore3000** [comment]
Yes, this would be awesome.

For the moment I´m misusing the Context-Object to pass fields from grandparents to grandchildren.
