### ISSUE TITLE
Can graphql-java be run on jdk 6,7 or any jdk lower than 8?  

### ISSUE THREAD

**Issue by themanojshukla** [graphql-java/graphql-java#1134]
Today, I was doing some source code R & D on Spring Framework for properties file loaders, and suddenly I started looking into the source code of `graphql-java` .... I found in it's source code, that `graphql-java` heavily uses **lambdas** and **streams** released in **Java 8**, that arose a question in my mind that how can we run graphql-java on jdks lower than 8?? 

I couldn't find it on documentation too.. if any please provide me some links. 

Thanks

**Comment by tinnou** [comment]
GraphQL-java requires java 8 or above. For projects built with gradle you
can find the minimum version in the build.gradle file.

This targetCompatibility = 1.8

**Comment by bbakerman** [comment]
Yup we stayed on java 6 for a very long time but maybe a year ago we decide to move to Java 8.

We wont be adding any support for older JDKS sorry.


Version | Release date | End of Public Updates
-- | -- | --
Java SE 6 | December 2006 | April 2013
Java SE 7 | July 2011 | April 2015
Java SE 8 (LTS) | March 2014 | January 2019 (commercial) December 2020 (non-commercial)

**Comment by themanojshukla** [comment]
Thanks for the detailed information !!
