### ISSUE TITLE
Cannot replace the query due to problem with GraphQLSchema.newSchema(existingSchema)

### ISSUE THREAD

**Issue by asfernandes** [graphql-java/graphql-java#1135]
In a Spring Boot application, I want that spring boot does its magic and I then want to change (add fields) the query in a graphQLSchema bean.

If use `GraphQLSchema.newSchema(existingSchema)` or `GraphQLSchema.transform` and replace the query, the old query is in the builder `additionalTypes`, and we cannot remove items from this list.

I had to use:

```java
		Set<GraphQLType> schemaAdditionalTypes = schema.getAdditionalTypes();
		schemaAdditionalTypes.remove(query);
		schemaAdditionalTypes.add(newQuery);

		GraphQLSchema.Builder schemaBuilder = new GraphQLSchema.Builder()
			.query(newQuery)
			.mutation(schema.getMutationType())
			.subscription(schema.getSubscriptionType())
			.fieldVisibility(schema.getFieldVisibility())
			.additionalDirectives(schema.getDirectives().stream().collect(Collectors.toSet()))
			.additionalTypes(schemaAdditionalTypes);
```

Note also that directives in a place is a `List` and in another place is a `Set`.

**Comment by bbakerman** [comment]
I think I know the roughly the problem around the builder keeping the old additional types but can you make up an more concrete example to use as a unit test so we fix exactly the problem

**Comment by bbakerman** [comment]
See #1145
