### ISSUE TITLE
No validation of request variables

### ISSUE THREAD

**Issue by mrdon-atlassian** [graphql-java/graphql-java#1139]
When a request contains variables that aren't used, it should result in validation errors.  However, it seems graphql-java only validates the query document, not the request variables. 
For example, this doesn't trigger any validation errors:

``
{"operationName":"SpaceIDQuerysaa","query":"query SpaceIDQuerysaa($spaceKey: String) {space(key: $spaceKey)\n{ id\n __typename }}","variables":{"keyddd":"ISO"}}
``
But with another GraphQL implementation, the result is:
``
{
  "data": null,
  "errors": [
    {
      "message": "Variable $var is declared by foo but not used",
      "locations": [
        {
          "line": 6,
          "column": 1
        }
      ]
    }
  ]
}
``

**Comment by mrdon-atlassian** [comment]
PR https://github.com/graphql-java/graphql-java/pull/1142

**Comment by bbakerman** [comment]
What is the other other graphql implementation that gives that error.

On the PR i makde the case that this is NOT covered by graphql specfication
