### ISSUE TITLE
Int type value in enum type

### ISSUE THREAD

**Issue by zhewang2** [graphql-java/graphql-java#1149]
I was trying to create an enum type with Int value in GraphQL schema but failed. I might miss something in the doc. Anyone has any idea about how to implement Int value in the enum type like below?

enum IntValue {
  1
  2
  3
}

**Comment by bbakerman** [comment]
Can you explain more about how it failed?

Enums are meant to be a constrained list of string like values eg

```
enum Episode {
  NEWHOPE
  EMPIRE
  JEDI
}
```
We can map them to Java Enums under the covers and hence get ordinal support say.

You example above should be the strings "1" and "2" and "3" say

**Comment by bbakerman** [comment]
Closing this since I havent heard anything more back
