### ISSUE TITLE
graphql.execution.ExecutionStrategy#unboxPossibleDataFetcherResult is not protected

### ISSUE THREAD

**Issue by stoyandekov7** [graphql-java/graphql-java#1151]
`graphql.execution.ExecutionStrategy#unboxPossibleDataFetcherResult` is package private making it unusable from subclasses of `ExecutionStrategy`.

Furthermore it cannot be Overridden (preserving behaviour) as it is using package private class `AbsoluteGraphQLError` due to the same issue.

**Comment by bbakerman** [comment]
A PR would help address this issue
