### ISSUE TITLE
AsyncDataFetcher with DataLoader Causes Error

### ISSUE THREAD

**Issue by brockgibson** [graphql-java/graphql-java#1152]
When wrapping a DataFetcher that utilizes a DataLoader for its return, the graphql execution produces a null result. Looks to be a result of chained CompletableFuture returns...

This may be expected behavior, and maybe the use case isn't terribly compelling (async data fetcher with async load), but wanted to raise the issue nonetheless.

**Comment by bbakerman** [comment]
@brockgibson  - can you explain in more detail your code, perhaps attach some psudeo code showing the problem or  a unit test demonstrating it.

**Comment by bbakerman** [comment]
Ahh are you using `AsyncDataFetcher` with a call to DataLoader?

if you are - invert the relationship.  Stop using `AsyncDataFetcher` but rather in the DataLoader batch function you can make that an async call.

You are right that the chain of Async calls confuses things (or worse never returns) and you are not gaining any more concurrency by having async calls over async calls.

**Comment by brockgibson** [comment]
Thanks @bbakerman. I am indeed using the ```AsyncDataFetcher```.

As a little background, my team was previously using the ```ExecutorServiceExecutionStrategy``` to parallelize execution of resolvers. We have since been migrating to ```AsyncExecutionStrategy```. As an approach to enabling "backwards compatibility" with regard to fetcher behavior, I looked into creating an ```Instrumentation``` that instrumented ```DataFetcher```s by wrapping them in ```AsyncDataFetcher```s, which caused the issue described above.

We will instead be doing as you mention above to not combine the two.
