### ISSUE TITLE
SchemaGenerator does not allow to set additional Types

### ISSUE THREAD

**Issue by josh00007777** [graphql-java/graphql-java#1154]
To explain I will take an example, this is my schema -

schema {
    query: Query
}

type Query {
    allLinks(filter: LinkFilter, skip: Int = 0, first: Int = 0): [Link]
}

type Link {
    id: ID!
    url: String!
    description: String
    postedBy: Employee
}

interface Employee {
    id: ID!
    name: String!
}

type User implements Employee {
    id: ID!
    name: String!
    email: String
    password: String
}

input LinkFilter {
    description_contains: String
    url_contains: String
}

This is how I generate the GraphQL schema - 

    	TypeDefinitionRegistry typeRegistry = schemaParser.parse(schemaFile);
    	RuntimeWiring runtimeWiring = RuntimeWiring.newRuntimeWiring()
        		.type("Query", typeWiring  -> typeWiring
        			.dataFetcher("allLinks", new LinkFetcher()))
        		.type("Link", typeWiring  -> typeWiring
            			.dataFetcher("postedBy", new UserFetcher()))
        		
        		.type("Employee", typeWiring  -> typeWiring
                        .typeResolver(new TypeResolver() {
							@Override
							public GraphQLObjectType getType(TypeResolutionEnvironment env) {
								return (GraphQLObjectType)env.getSchema().getType("User");
							}
						}))
        		.build();
		GraphQLSchema graphQLSchema = schemaGenerator.makeExecutableSchema(typeRegistry, runtimeWiring);

When I run the query on this schema, it complains that type "User" is unknown. If there is a way to provide additional types to SchemaGenerator then the additional types can be taken care during schema generation itself. It can have a new method "makeExecutableSchema()" with additional parameter something like -

List<Type> additionalTypeNames = new ArrayList<Type>();
additionalTypeNames.add(new TypeName("User"));
GraphQLSchema graphQLSchema = schemaGenerator.makeExecutableSchema(typeRegistry, runtimeWiring, additionalTypeNames);

The private method can be updated to make use of additional types - 
schemaGenerator.makeExecutableSchemaImpl(buildCtx) {
....
....

//just before calling build() on schemaBuilder
     Set<GraphQLType> additionalTypes = null;
     if(!buildCtx.getAdditionalTypeNames().isEmpty()) {
        	additionalTypes = new HashSet<>();
        	for(Typet : buildCtx.getAdditionalTypeNames()) {
        		additionalTypes.add(buildOutputType(buildCtx, t));
        	}
        	return schemaBuilder.build(additionalTypes);
        } else {
        	return schemaBuilder.build();
        }
}

**Comment by bbakerman** [comment]
We will look into this.  The current code does PUT in types that are not directly referenced by other types but perhaps there is a edge case bug.

**Comment by bbakerman** [comment]
I wrote the following test on the 9.x stable branch

```
        def spec = """
            schema {
                query: Query
            }

            type Query {
                allLinks(filter: LinkFilter, skip: Int = 0, first: Int = 0): [Link]
            }
            
            type Link {
                id: ID!
                url: String!
                description: String
                postedBy: Employee
            }
            
            interface Employee {
                id: ID!
                name: String!
            }
            
            type User implements Employee {
                id: ID!
                name: String!
                email: String
                password: String
            }
            
            input LinkFilter {
                description_contains: String
                url_contains: String
            }
        """

        def schema = schema(spec, TestUtil.mockRuntimeWiring)

        expect:
        schema != null
        GraphQLObjectType userType = schema.getType("User") as GraphQLObjectType
        userType != null

        userType.getInterfaces().get(0).getName() == "Employee"
```

and it passes as expected.   It was part of `graphql.schema.idl.SchemaGeneratorTest`

It detects the extra "User" type that is not directly referenced by other types and adds it correctly as an additional type.

Can you confirm what graphql-java version you are working on.  I think this has been working like this for a while since we already have a test for this exact scenario

` def "builds additional types not referenced from schema top level"() `

Can you please confirm since I amp tempted to close this issue as working as expected

**Comment by josh00007777** [comment]
Thanks for looking into it. I have tested in latest branch and It is working as expected. Thanks again.
