### ISSUE TITLE
Skip Directive not correct

### ISSUE THREAD

**Issue by kristofdepypere** [graphql-java/graphql-java#116]
in Directives#SkipDirective the skip directive is defined with name "skip" and also with argument "skip". However validation and parsing of directive info expects "if" as argument. This seems to contradict each other.

**Comment by dev-rkoshlyak** [comment]
look like include did not work as well:(

**Comment by dev-rkoshlyak** [comment]
workaround: 
Look like if i need to use directive, I have to use add argument to field "if" on which i want to use directive .argument(newArgument().name("if").type(GraphQLBoolean).build())

**Comment by Globegitter** [comment]
Yep we are running into this as well now and neither `field @include(if: false)` nor `field @skip(if: false)` does work but @dev-rkoshlyak workaround seems to do the trick for now.

**Comment by danielkwinsor** [comment]
This will be addressed in #148

**Comment by okorz001** [comment]
This issue should be closed now

**Comment by andimarek** [comment]
closing because resolved
