### ISSUE TITLE
Discussion: Multi directives

### ISSUE THREAD

**Issue by Me1kaa** [graphql-java/graphql-java#1167]
Right now graphql-java force uniqueness of directives on one field, type, etc. I was wandering in the graphql specification and assumed that there is no such restriction in the specification. So, that's an implement specific thing, can it be changed and is it needed? 

How can it be used(the example of our team): 
We implemented directive chaining, so, directives create a chain of dataFetchers

Right now we can't use it as in the example below(because of uniqueness): 
```
type Dog {
     id: String @Map(action: "rawId -> rawId + 10000") @Map(action: "newId -> 'Dog's id is ' + newId")
}
```
Instead of that, we should use hack(looks like hack with tuples in Scala lang), we define some number of common directives with different names and that chain becomes:
```
type Dog {
     id: String @Map1(action: "rawId -> rawId + 10000") @Map2(action: "newId -> 'Dog's id is ' + newId")
}
```
And I'm not asking you to implement this, I can try implement it myself and create PR ;)

**Comment by bbakerman** [comment]
http://facebook.github.io/graphql/draft/#sec-Validation.Directives

```
Directives Are Unique Per Location
Formal Specification

For every location in the document for which Directives can apply:
Let directives be the set of Directives which apply to location.
For each directive in directives:
Let directiveName be the name of directive.
Let namedDirectives be the set of all Directives named directiveName in directives.
namedDirectives must be a set of one.
Explanatory Text

Directives are used to describe some metadata or behavioral change on the definition they apply to. When more than one directive of the same name is used, the expected metadata or behavior becomes ambiguous, therefore only one of each directive is allowed per location.

For example, the following query will not pass validation because @skip has been used twice for the same field:

query ($foo: Boolean = true, $bar: Boolean = false) {
  field @skip(if: $foo) @skip(if: $bar)
}


```

Its pretty clear they should be unique per location.  Thats why we did it
