### ISSUE TITLE
Consider adding a `containsSelection(String fieldGlobPattern)` to DataFetchingEnvironment

### ISSUE THREAD

**Issue by marceloverdijk** [graphql-java/graphql-java#1172]
Similar as `DataFetchingEnvironment.containsArgument(String name)` to check if the env contains an argument.

Maybe `containsSelection` is not the best name though. Maybe `containsSelectionField` is better?

This would make it shorter to check if a child field is selected.
Instead of `environment.getSelectionSet().contains("nationality/name")` we could do `environment.containsSelection("nationality/name")`.

**Comment by marceloverdijk** [comment]
@bbakerman if you like the idea I can make a PR.

**Comment by bbakerman** [comment]
I am tempted but I am going to say no.

I appreciate that is a nice short cut however the reason I am against it are as follows

* it adds to the already large surface area of DataFetchingEnvironment
* it hides the other functionality that is in DataSelectionSet
* it breaks the encapsulation of duties, where two classes do the same thing (via proxy calls)

I am tempted to make it easier but I dont think its enough code value in other regards

**Comment by marceloverdijk** [comment]
OK no problem. Using `environment.getSelectionSet().contains(..)` is not that long.
