### ISSUE TITLE
Deprecate ExecutorServiceExecutionStrategy

### ISSUE THREAD

**Issue by bbakerman** [graphql-java/graphql-java#1173]
`ExecutorServiceExecutionStrategy` does not offer enough value now that we have CompleteableFuture based graphql-java.

It was useful in the past to be automatically async however now each field can be async by simply choosing to use `CompleteableFuture.supplyAsync` as a return value.

ESES does not work with data loader and cant be made to work with it.

I think we should deprecate it and only supply the 2 well known ES implementations

**Comment by hepin1989** [comment]
that's a good way to go .

**Comment by hanbingjiao** [comment]
@bbakerman If we deprecate ExecutorServiceExecutionStrategy, how could we handle two API queries parallel?
Such as the following the request:

query QueryType($id1: String!, $id2: String!) {
 a1: getData(id: $id1) {
    resultCode
    data {
      abc
    }
  }
  a2: getData(id: $id2) {
    resultCode
    data {
      abc
    }
  }
}

**Comment by bbakerman** [comment]
> If we deprecate ExecutorServiceExecutionStrategy, how could we handle two API queries parallel?

The new versions of Graphql use CompletableFuture results and they combine them.

So imagine we have two data fetchers (psudeo code in lambda syntax)

    DataFetcher firstCall = env -> CompleteableFuture.supplyAsync(() -> serviceLayer.makeCall1(env));

    DataFetcher secondCall = env -> CompletableFuture.supplyAsync(() -> serviceLayer.makeCall2(env));


Each of these fetches is now and async call and CompletableFuture will delegate them to a standard ForkJoin scheduler in Java.   You can use your own scheduler if you want.  They WILL happen in parallel and be combined by graphql java

 In essence we no longer need the old ExecutorServiceExecutionStrategy which did the same thing but was invented in Java before CompletableFuture

**Comment by perkins4j2** [comment]
> > If we deprecate ExecutorServiceExecutionStrategy, how could we handle two API queries parallel?
> 
> The new versions of Graphql use CompletableFuture results and they combine them.
> 
> So imagine we have two data fetchers (psudeo code in lambda syntax)
> 
> ```
> DataFetcher firstCall = env -> CompleteableFuture.supplyAsync(() -> serviceLayer.makeCall1(env));
> 
> DataFetcher secondCall = env -> CompletableFuture.supplyAsync(() -> serviceLayer.makeCall2(env));
> ```
> 
> Each of these fetches is now and async call and CompletableFuture will delegate them to a standard ForkJoin scheduler in Java. You can use your own scheduler if you want. They WILL happen in parallel and be combined by graphql java
> 
> In essence we no longer need the old ExecutorServiceExecutionStrategy which did the same thing but was invented in Java before CompletableFuture

hi，But I still want to use parallel and my ExecutorService。

reason：
1，ExecutorService has monitor online。
2，ForkJoin‘s performance maybe not very well。

So， If I use AsyncExecutionStrategy,how can use my ExecutorService?

THS
