### ISSUE TITLE
Recursive GraphQLTypeReference resolution

### ISSUE THREAD

**Issue by yrashk** [graphql-java/graphql-java#118]
I am wondering if type reference resolution should go deeper beyond one level.

Right now, according to my best understanding of https://github.com/andimarek/graphql-java/blob/master/src/main/java/graphql/schema/SchemaUtil.java#L149-L155, for every object's field, it will do a type resolution. However, if that resolved type itself contains further type references, they won't be processed. Is this intentional or should it be improved? Happy to work on a PR if you think this should be improved.

**Comment by danielkwinsor** [comment]
Just hit this too, here's a test case that reproduces the issue.

It affects queries not just on the object, but on the __schema too.


```
    @Test
    public void testRecursionByHand() throws Exception {
        logger.debug("testRecursionByHand");
        GraphQLOutputType recursiveClass = GraphQLObjectType.newObject()
                .name("RecursiveClass")
                .field(newFieldDefinition()
                        .type(Scalars.GraphQLString)
                        .name("recursionLevel")
                        .build())
                .field(newFieldDefinition()
                        .type(new GraphQLTypeReference("RecursiveClass"))
                        .name("recursive")
                        .build())
                .build();
        GraphQLObjectType queryType = newObject()
                .name("testQuery")
                .field(newFieldDefinition()
                        .type((GraphQLOutputType) recursiveClass)
                        .name("testObj")
                        .staticValue(new RecursiveClass(2))
                        .build())
                .build();
        GraphQLSchema recursiveTestSchema = GraphQLSchema.newSchema()
                .query(queryType)
                .build();
        
        String query = ""
        + "query testSchema {"
        + "  __schema {"
        + "    types {"
        + "      name"
        + "      fields {"
        + "        name"
        + "        type {"
        + "          name"
        + "        }"
        + "      }"
        + "    }"
        + "  }"
        + "}";

        String queryString = 
        "{"
        + "  testObj {"
        + "    recursionLevel"
        + "    recursive {"
        + "      recursionLevel"
        + "    recursive {"
        + "      recursionLevel"
        + "    recursive {"
        + "      recursionLevel"
        + "    recursive {"
        + "      recursionLevel"
        + "    }"
        + "    }"
        + "    }"
        + "    }"
        + "  }"
        + "}";
        
        try {
            new GraphQL(recursiveTestSchema).execute(query);
        }
        catch (Exception e) {
            logger.error("Caught exception", e);
            throw e;
        }
        ExecutionResult queryResult = new GraphQL(recursiveTestSchema).execute(query);
        assertThat(queryResult.getErrors(), is(empty()));
```

```
public class RecursiveClass {
    public RecursiveClass() {
        
    }
    
    public RecursiveClass(int recursionLevel) {
        this.recursionLevel = String.valueOf(recursionLevel);
        if (recursionLevel > 0 && recursionLevel < 10) {
            recursive = new RecursiveClass(recursionLevel - 1);
        }
    }

    public String getRecursionLevel() {
        return recursionLevel;
    }
    public RecursiveClass getRecursive() {
        return recursive;
    }

    public String recursionLevel;
    public RecursiveClass recursive = null;
```

**Comment by andimarek** [comment]
In the resolved schema there should no TypeReference left. If this is not the case, it's definitely a bug.

**Comment by yrashk** [comment]
@andimarek the way I see the code I referenced above, the resolution only goes one level deep and stops there.

**Comment by andimarek** [comment]
@yrashk I don't think we need to go "deeper" if we visit every type (at least that was the idea)

**Comment by yrashk** [comment]
It looks like we have three independent cases where we experience unresolved type references. Not sure what's the ultimate cause, but I'll try to put more effort in figuring it out.

**Comment by alexkrebiehl** [comment]
Please try out the fix and let me know what you think.  This also fixed an issue with fragments not being resolved.

The issue was that each `GraphQLObjectType` that had a field that referenced another `GraphQLObjectType` was pointing to a different instance of that model type.  For example, `x.y`'s reference to `y` was pointing to a different instance of `y` than `z.y`'s reference to `y`.  Only one instance of `y` would have its type references resolved.  Unless you were pointing to that instance, you wouldn't see the updated model.

The problem was fixed by making sure each `GraphQLObjectType` reference was pointing to the same instance of `GraphQLObjectType` from the `typeMap`.

**Comment by danielkwinsor** [comment]
I confirm that my test cases pass with this fix.

**Comment by hanmu** [comment]
@andimarek  in the  danielkwinsor's example.we use the QL below to query for a recursive data :

```
String queryString = 
        "{"
        + "  testObj {"
        + "    recursionLevel"
        + "    recursive {"
        + "      recursionLevel"
        + "    recursive {"
        + "      recursionLevel"
        + "    recursive {"
        + "      recursionLevel"
        + "    recursive {"
        + "      recursionLevel"
        + "    }"
        + "    }"
        + "    }"
        + "    }"
        + "  }"
        + "}";
```

My question is  if recursionLevel is a dynamic value, how can i write the QL to request for a full recursive data?

**Comment by ceronman** [comment]
I can confirm that after applying this PR, the issue described in #193 disappeared completely.

**Comment by dminkovsky** [comment]
#123 was merged a few days ago. @yrashk Do you think that takes care of this issue?

**Comment by yrashk** [comment]
@dminkovsky yes, looks like the issue was resolved: https://github.com/graphql-java/graphql-java-annotations/commit/42ee9db7fd22b3106d9887d6b594ab299f9a00d5
