### ISSUE TITLE
allow reference input type

### ISSUE THREAD

**Issue by tbo-axelor** [graphql-java/graphql-java#1185]
i m try to return type but all Sacalrtype is working fine but try to return foreign type like

```
public GraphQLInputType getInputAttributeType(Attribute<?, ?> attribute) {
    	if (attribute.getPersistentAttributeType() == Attribute.PersistentAttributeType.ONE_TO_MANY || attribute.getPersistentAttributeType() == Attribute.PersistentAttributeType.MANY_TO_MANY) {
            EntityType<?> foreignType = (EntityType<?>) ((PluralAttribute<?, ?, ?>) attribute).getElementType();
            return new GraphQLList(new GraphQLTypeReference(foreignType.getName()));
        } else if (attribute.getPersistentAttributeType() == Attribute.PersistentAttributeType.MANY_TO_ONE || attribute.getPersistentAttributeType() == Attribute.PersistentAttributeType.ONE_TO_ONE) {
        	EntityType<?> foreignType = (EntityType<?>) ((SingularAttribute<?, ?>) attribute).getType();
            return new GraphQLTypeReference(foreignType.getName());
        } 
    	
    	final String declaringType = attribute.getDeclaringType().getJavaType().getName(); // fully qualified name of the entity class
        final String declaringMember = attribute.getJavaMember().getName(); // field name in the entity class

        throw new UnsupportedOperationException(
                "Attribute could not be mapped to GraphQL: field '" + declaringMember + "' of entity class '" + declaringType + "'");
    }
```
    
so it give error like java.lang.ClassCastException: graphql.schema.GraphQLObjectType cannot be cast to graphql.schema.GraphQLInputType

**Comment by tinnou** [comment]
Would you be able to post a stack trace and put together a small unit test that compiles? Otherwise it will be hard to help.

That said, my feeling here is you might already have registered on your schema the `Address` type as an output object type and you're trying to register a field on an input type of type `Address`. However, remember [per the spec](https://facebook.github.io/graphql/draft/#sec-Input-Objects) that all fields on a input type must be input types, scalars or enums. i.e you can't use a field of object type on an input type.

GraphQL specification - Input Objects:
> A GraphQL Input Object defines a set of input fields; the input fields are either scalars, enums, or other input objects.

**Comment by bbakerman** [comment]
Even if he has misconfigured his schema but putting an GraphqlObjectType  in play we still need to double check that graphql-java does indeed allow circular Input objects, which in java are only possible via a TypeRef style indirection layer (unlike JS)

See https://github.com/facebook/graphql/issues/189 and https://github.com/graphql/graphql-js/pull/1359

I think we should double check that you can in fact do the following in graphql-java

     input Something {
           name : String
           otherThing : Something
     }

**Comment by bbakerman** [comment]
Ok I have double check that GraphqlTypeReferences can be used with input object types and yes they can.  I proved it with the above self referential type.

I suspect the original report has a mix of output object types in his input objects types which is not allowed in graphql
