### ISSUE TITLE
Fix depth of TypeRef in Introspection Query

### ISSUE THREAD

**Issue by mstachniuk** [graphql-java/graphql-java#1186]
In Introspection Query a depth of `TypeRef` should be bigger. In GraphiQL it's deeper [introspectionQueries.js](https://github.com/graphql/graphiql/blob/master/src/utility/introspectionQueries.js)
depth = 7, in graphql-java it's only depth = 3 (number of `ofType` occurrences). The query will fail for Schema like this:

```
  type GeoPolygon {
    coordinates: [[[[Float]]]]!
  }
```

Found this example here: https://github.com/dbsystel/1BahnQL/blob/develop/schema.js#L371-L374 (Please don't ask me why it's so designed - I have no idea).

My sugesstions is to increase depth to 5 or 7 like in GraphiQL. WDYT?

**Comment by bbakerman** [comment]
Sounds fair enough to be honest

**Comment by bbakerman** [comment]
Made a PR for this.  Thanks for reporting this with code references and making it so easy to fix.
