### ISSUE TITLE
How to add implementation for custom directives created via GraphQLDirective class?

### ISSUE THREAD

**Issue by sujivisva** [graphql-java/graphql-java#1201]
For example, I have created a custom directive called "uppercase" using the below statements.

GraphQLDirective upperCaseDirective = GraphQLDirective.newDirective()
                        .name("uppercase")
                        .description("Directs the executor to uppercase this field")
                        .validLocations(FRAGMENT_SPREAD, INLINE_FRAGMENT, FIELD)
                        .build();

How can I add actual logic of UPPER CASING to this "upperCaseDirective" object?

**Comment by bbakerman** [comment]
You can create your own directives not by hand by using DSL directives and Directive wiring

We wrote a document on this but it seems to have missed in the page tree.  We are fixing that now.

So to address this issue right now, here is the document repeat in this issue



# Adding Behaviour

Schema Definition Language (SDL) allows you to define your graphql types in a declarative manner without using code. However you still need to wire in all the logic that backs those types and their fields.

Schema directives allow you to do this. You can place directives on SDL elements and then write the backing logic once and have it apply in many places.

This idea of “writing it once” is the key concept here. There is only code place where logic needs to be written and it is then applied to all the places in the SDL that have a named directive.

This is a more powerful model than wiring in 10-100s of data fetchers like you might with the conventional runtime wiring.

For example imagine you have a type like the following

```
type Employee
    id : ID
    name : String!
    startDate : String!
    salary : Float
}
```

Publishing salary information to every one who can see this employee’s name might not be want you want. Rather you want some sort of access control to be in place such that if your role is that of a manager, you can see salaries, otherwise you get no data back.

Directives can help you declare this more easily. Our declaration above would become something like the following:

```
directive @auth(role : String!) on FIELD_DEFINITION

type Employee
    id : ID
    name : String!
    startDate : String!
    salary : Float @auth(role : "manager")
}
```

So we have said that only people who have the role manager are authorised to see this field. We can now use this directive on ANY field that needs manager role authorisation.

```
directive @auth(role : String!) on FIELD_DEFINITION

type Employee
    id : ID
    name : String!
    startDate : String!
    salary : Float @auth(role : "manager")
}

type Department {
    id : ID
    name : String
    yearlyOperatingBudget : Float @auth(role : "manager")
    monthlyMarketingBudget : Float @auth(role : "manager")
}
```

We now need to wire in the code that can handle any field with this @auth directive. We use graphql.schema.idl.SchemaDirectiveWiring to do this.

```
class AuthorisationDirective implements SchemaDirectiveWiring {

    @Override
    public GraphQLFieldDefinition onField(SchemaDirectiveWiringEnvironment<GraphQLFieldDefinition> schemaDirectiveWiringEnv) {
        String targetAuthRole = (String) schemaDirectiveWiringEnv.getDirective().getArgument("role").getValue();

        GraphQLFieldDefinition field = schemaDirectiveWiringEnv.getElement();
        //
        // build a data fetcher that first checks authorisation roles before then calling the original data fetcher
        //
        DataFetcher originalDataFetcher = field.getDataFetcher();
        DataFetcher authDataFetcher = new DataFetcher() {
            @Override
            public Object get(DataFetchingEnvironment dataFetchingEnvironment) {
                Map<String, Object> contextMap = dataFetchingEnvironment.getContext();
                AuthorisationCtx authContext = (AuthorisationCtx) contextMap.get("authContext");

                if (authContext.hasRole(targetAuthRole)) {
                    return originalDataFetcher.get(dataFetchingEnvironment);
                } else {
                    return null;
                }
            }
        };
        //
        // now change the field definition to have the new authorising data fetcher
        return field.transform(builder -> builder.dataFetcher(authDataFetcher));
    }
}

//
// we wire this into the runtime by directive name
//
RuntimeWiring.newRuntimeWiring()
        .directive("auth", new AuthorisationDirective())
        .build();
```

This has modified the GraphQLFieldDefinition so that its original data fetcher will ONLY be called if the current authorisation context has the manager role. Exactly what mechanisms you use for authorisation is up to you. You could use Spring Security for example say, graphql-java doesnt really care.

You would provide this authorisation checker into the execution “context” object of the graphql input so it can then be accessed later in the DataFetchingEnvironment.

```
AuthorisationCtx authCtx = AuthorisationCtx.obtain();

ExecutionInput executionInput = ExecutionInput.newExecutionInput()
        .query(query)
        .context(authCtx)
        .build();
```

# Declaring Directives

In order to use a directive in SDL, the graphql specification requires that you MUST declare its shape before using it. Our @auth directive example above needs to be declared like so before use.

```
# This is a directive declaration
directive @auth(role : String!) on FIELD_DEFINITION

type Employee
    id : ID

    # and this is a usage of that declared directive
    salary : Float @auth(role : "manager")
}
```

The one exception to this is the @deprecated directive which is implicitly declared for you as follows :

```
directive @deprecated(  reason: String = "No longer supported") on FIELD_DEFINITION | ENUM_VALUE
```

The valid SDL directive locations are as follows :

```
SCHEMA,
SCALAR,
OBJECT,
FIELD_DEFINITION,
ARGUMENT_DEFINITION,
INTERFACE,
UNION,
ENUM,
ENUM_VALUE,
INPUT_OBJECT,
INPUT_FIELD_DEFINITION
```

Directives are commonly applied to fields definitions but as you can see there are a number of places they can be applied.

# Another Example - Date Formatting

Date formatting is a cross cutting concern that we should only have to write once and apply it in many areas.

The following demonstrates an example schema directive that can apply date formatting to fields that are LocaleDate objects.

Whats great in this example is that it adds an extra format argument to each field that it is applied to. So the clients can opt into what ever date formatting you provide per request.

```
directive @dateFormat on FIELD_DEFINITION

type Query {
    dateField : String @dateFormat
}
```

Then our runtime code could be :

```
public static class DateFormatting implements SchemaDirectiveWiring {
    @Override
    public GraphQLFieldDefinition onField(SchemaDirectiveWiringEnvironment<GraphQLFieldDefinition> environment) {
        GraphQLFieldDefinition field = environment.getElement();
        //
        // DataFetcherFactories.wrapDataFetcher is a helper to wrap data fetchers so that CompletionStage is handled correctly
        // along with POJOs
        //
        DataFetcher dataFetcher = DataFetcherFactories.wrapDataFetcher(field.getDataFetcher(), ((dataFetchingEnvironment, value) -> {
            DateTimeFormatter dateTimeFormatter = buildFormatter(dataFetchingEnvironment.getArgument("format"));
            if (value instanceof LocalDateTime) {
                return dateTimeFormatter.format((LocalDateTime) value);
            }
            return value;
        }));

        //
        // This will extend the field by adding a new "format" argument to it for the date formatting
        // which allows clients to opt into that as well as wrapping the base data fetcher so it
        // performs the formatting over top of the base values.
        //
        return field.transform(builder -> builder
                .argument(GraphQLArgument
                        .newArgument()
                        .name("format")
                        .type(Scalars.GraphQLString)
                        .defaultValue("dd-MM-YYYY")
                )
                .dataFetcher(dataFetcher)
        );
    }

    private DateTimeFormatter buildFormatter(String format) {
        String dtFormat = format != null ? format : "dd-MM-YYYY";
        return DateTimeFormatter.ofPattern(dtFormat);
    }
}

static GraphQLSchema buildSchema() {

    String sdlSpec = "" +
            "type Query {\n" +
            "    dateField : String @dateFormat \n" +
            "}";

    TypeDefinitionRegistry registry = new SchemaParser().parse(sdlSpec);

    RuntimeWiring runtimeWiring = RuntimeWiring.newRuntimeWiring()
            .directive("dateFormat", new DateFormatting())
            .build();

    return new SchemaGenerator().makeExecutableSchema(registry, runtimeWiring);
}

public static void main(String[] args) {
    GraphQLSchema schema = buildSchema();
    GraphQL graphql = GraphQL.newGraphQL(schema).build();

    Map<String, Object> root = new HashMap<>();
    root.put("dateField", LocalDateTime.of(1969, 10, 8, 0, 0));

    String query = "" +
            "query {\n" +
            "    default : dateField \n" +
            "    usa : dateField(format : \"MM-dd-YYYY\") \n" +
            "}";

    ExecutionInput executionInput = ExecutionInput.newExecutionInput()
            .root(root)
            .query(query)
            .build();

    ExecutionResult executionResult = graphql.execute(executionInput);
    Map<String, Object> data = executionResult.getData();

    // data['default'] == '08-10-1969'
    // data['usa'] == '10-08-1969'
}
```

Notice the SDL definition did not have a format argument yet once the directive wiring is applied, it is added to the field definition and hence clients can begin to use it.

Please note that graphql-java does not ship with this implementation. It is merely provided here as an example of what you could add yourself.

# Chaining Behaviour

The directives are applied in the order they are encountered. For example imagine directives that changed the case of a field value.

```
directive @uppercase on FIELD_DEFINITION
directive @lowercase on FIELD_DEFINITION
directive @mixedcase on FIELD_DEFINITION
directive @reversed on FIELD_DEFINITION

type Query {
    lowerCaseValue : String @uppercase
    upperCaseValue : String @lowercase
    mixedCaseValue : String @mixedcase

    #
    # directives are applied in order hence this will be lower, then upper, then mixed then reversed
    #
    allTogetherNow : String @lowercase @uppercase @mixedcase @reversed
}
```

When the above was executed each directive would be applied one on top of the other. Each directive implementation should be careful to preserve the previous data fetcher to retain behaviour (unless of course you mean to throw it away)

**Comment by bbakerman** [comment]
Fixed : https://graphql-java.readthedocs.io/en/latest/sdldirectives.html

**Comment by sujivisva** [comment]
Hi,

Thanks a lot for your reply.

Whatever you have explained is a directive which needs to be declared in the SDL and needs to be applied on the respective fields. I understand the authorization concept.

But in my case, I just want to declare the directive and implementation in a programmatic way and leave the choice of where to apply the directives, to the client who makes the query call. 

"So I just need QUERY DIRECTIVES"

For an example as I mentioned in my original question, UPPERCASING of fields can be done using custom directive. Client can decide on where to apply the UPPERCASING directives. 

And also, I am using GraphQL SPQR framework for schema-less approach in which I have found a way to hook GraphQLDirective objects to the GraphQLSchemaGenerator class. It doesn't support adding directives via RuntimeWiring like you mentioned.

 RuntimeWiring runtimeWiring = RuntimeWiring.newRuntimeWiring()
            .directive("dateFormat", new DateFormatting())
            .build();

And moreover, I found bit confused of GraphQLDirective class. Could you please let me know what is the purpose of this class? I am able to define a custom directive using this class like below.

GraphQLDirective upperCaseDirective = GraphQLDirective.newDirective()
.name("uppercase")
.description("Directs the executor to uppercase this field")
.validLocations(FRAGMENT_SPREAD, INLINE_FRAGMENT, FIELD)
.build();

But I am unable to find a way to hook the implementation logic to this GraphQLDirective object. I tried my best to explore the graphql-java framework to find out where exactly, the implementation for @include & @skip directives are hooked but I couldn't. I have seen those directives are just declared in graphql.schema.GraphQLDirective.Directives class

public static final GraphQLDirective IncludeDirective = GraphQLDirective.newDirective().......
public static final GraphQLDirective SkipDirective = GraphQLDirective.newDirective().......

**But I couldn't find where exactly the logic for include & skip directives are implemented. So this is my actual question. If I DECLARE a custom directive using GraphQLDirective class, how can I DEFINE the same (Add IMPLEMENTATION to the custom directive object)?**

**Comment by kdlan** [comment]
query directive may implement by Instrumentation

```
public class DirectiveInstrumentation extends SimpleInstrumentation {
    @Override
    public DataFetcher<?> instrumentDataFetcher(DataFetcher<?> dataFetcher,
            InstrumentationFieldFetchParameters parameters) {
        List<Directive> list = parameters.getEnvironment().getField().getDirectives();
        if (!list.isEmpty()) {
            return new DirectiveDataFetcher(dataFetcher);
        }
        return super.instrumentDataFetcher(dataFetcher, parameters);
    }
}
```

and define a new DirectiveDataFetcher to implement your `UPPERCASING` implmenttion.

I just found it is  a possible way to implements it and can not give a example now

**Comment by gipeshka** [comment]
@sujivisva regarding your question on `skip` and `include` directives, apparently they are implemented in [ConditionalNodes](https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/execution/ConditionalNodes.java) and are used in [QueryTraversal](https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/analysis/QueryTraversal.java#L46), see eg [line 224](https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/analysis/QueryTraversal.java#L224) with `shouldInclude`

**Comment by AnkitaBasu** [comment]
@kdlan  i have used the above example in a Spring boot application which uses the graphql starter

		<dependency>
		    <groupId>com.graphql-java</groupId>
		    <artifactId>graphql-java</artifactId>
		    <version>11.0</version>
		</dependency>
		<dependency>
		    <groupId>com.graphql-java</groupId>
		    <artifactId>graphql-java-tools</artifactId>
		    <version>5.2.3</version>
		</dependency>
		<dependency>
		    <groupId>com.graphql-java</groupId>
		    <artifactId>graphql-java-servlet</artifactId>
		    <version>6.1.2</version>
		</dependency>
		<dependency>
			<groupId>com.graphql-java</groupId>
			<artifactId>graphql-spring-boot-starter</artifactId>
			<version>5.0.2</version>
		</dependency>
		<dependency>
			<groupId>com.graphql-java</groupId>
			<artifactId>graphiql-spring-boot-starter</artifactId>
			<version>5.0.2</version>
		</dependency>

However the directive is not getting applied to the fields, i tried to put it in debug mode and noticed that the control never goes to the Directive class. How do i register it? is it expected to register it self automatically in spring boot ?

Thanks

**Comment by emcanavesio-meli** [comment]
Hi,

I want to use the `deprecated` directive over a query filter.
How can I do this?

Thanks

**Comment by bbakerman** [comment]
IIt your data fetcher you need change (in your case on sn: String @auth(role : "manager"))

We have lots of test for schema directive wiring.  Are you saying there is a bug.

I dont have a lot to go on here.  I think you would need to raise a seperate bug if you have found a  problem - such a bug would need reproduction steps to help us.

**Comment by forbreak** [comment]
@sujivisva  Hi! I want to know how you dealt with it in the end, I still haven't found it. How to deal with the directive created programmatically?

**Comment by tianlongJ** [comment]
> You can create your own directives not by hand by using DSL directives and Directive wiring
> 
> We wrote a document on this but it seems to have missed in the page tree. We are fixing that now.
> 
> So to address this issue right now, here is the document repeat in this issue
> 
> # Adding Behaviour
> Schema Definition Language (SDL) allows you to define your graphql types in a declarative manner without using code. However you still need to wire in all the logic that backs those types and their fields.
> 
> Schema directives allow you to do this. You can place directives on SDL elements and then write the backing logic once and have it apply in many places.
> 
> This idea of “writing it once” is the key concept here. There is only code place where logic needs to be written and it is then applied to all the places in the SDL that have a named directive.
> 
> This is a more powerful model than wiring in 10-100s of data fetchers like you might with the conventional runtime wiring.
> 
> For example imagine you have a type like the following
> 
> ```
> type Employee
>     id : ID
>     name : String!
>     startDate : String!
>     salary : Float
> }
> ```
> 
> Publishing salary information to every one who can see this employee’s name might not be want you want. Rather you want some sort of access control to be in place such that if your role is that of a manager, you can see salaries, otherwise you get no data back.
> 
> Directives can help you declare this more easily. Our declaration above would become something like the following:
> 
> ```
> directive @auth(role : String!) on FIELD_DEFINITION
> 
> type Employee
>     id : ID
>     name : String!
>     startDate : String!
>     salary : Float @auth(role : "manager")
> }
> ```
> 
> So we have said that only people who have the role manager are authorised to see this field. We can now use this directive on ANY field that needs manager role authorisation.
> 
> ```
> directive @auth(role : String!) on FIELD_DEFINITION
> 
> type Employee
>     id : ID
>     name : String!
>     startDate : String!
>     salary : Float @auth(role : "manager")
> }
> 
> type Department {
>     id : ID
>     name : String
>     yearlyOperatingBudget : Float @auth(role : "manager")
>     monthlyMarketingBudget : Float @auth(role : "manager")
> }
> ```
> 
> We now need to wire in the code that can handle any field with this @auth directive. We use graphql.schema.idl.SchemaDirectiveWiring to do this.
> 
> ```
> class AuthorisationDirective implements SchemaDirectiveWiring {
> 
>     @Override
>     public GraphQLFieldDefinition onField(SchemaDirectiveWiringEnvironment<GraphQLFieldDefinition> schemaDirectiveWiringEnv) {
>         String targetAuthRole = (String) schemaDirectiveWiringEnv.getDirective().getArgument("role").getValue();
> 
>         GraphQLFieldDefinition field = schemaDirectiveWiringEnv.getElement();
>         //
>         // build a data fetcher that first checks authorisation roles before then calling the original data fetcher
>         //
>         DataFetcher originalDataFetcher = field.getDataFetcher();
>         DataFetcher authDataFetcher = new DataFetcher() {
>             @Override
>             public Object get(DataFetchingEnvironment dataFetchingEnvironment) {
>                 Map<String, Object> contextMap = dataFetchingEnvironment.getContext();
>                 AuthorisationCtx authContext = (AuthorisationCtx) contextMap.get("authContext");
> 
>                 if (authContext.hasRole(targetAuthRole)) {
>                     return originalDataFetcher.get(dataFetchingEnvironment);
>                 } else {
>                     return null;
>                 }
>             }
>         };
>         //
>         // now change the field definition to have the new authorising data fetcher
>         return field.transform(builder -> builder.dataFetcher(authDataFetcher));
>     }
> }
> 
> //
> // we wire this into the runtime by directive name
> //
> RuntimeWiring.newRuntimeWiring()
>         .directive("auth", new AuthorisationDirective())
>         .build();
> ```
> 
> This has modified the GraphQLFieldDefinition so that its original data fetcher will ONLY be called if the current authorisation context has the manager role. Exactly what mechanisms you use for authorisation is up to you. You could use Spring Security for example say, graphql-java doesnt really care.
> 
> You would provide this authorisation checker into the execution “context” object of the graphql input so it can then be accessed later in the DataFetchingEnvironment.
> 
> ```
> AuthorisationCtx authCtx = AuthorisationCtx.obtain();
> 
> ExecutionInput executionInput = ExecutionInput.newExecutionInput()
>         .query(query)
>         .context(authCtx)
>         .build();
> ```
> 
> # Declaring Directives
> In order to use a directive in SDL, the graphql specification requires that you MUST declare its shape before using it. Our @auth directive example above needs to be declared like so before use.
> 
> ```
> # This is a directive declaration
> directive @auth(role : String!) on FIELD_DEFINITION
> 
> type Employee
>     id : ID
> 
>     # and this is a usage of that declared directive
>     salary : Float @auth(role : "manager")
> }
> ```
> 
> The one exception to this is the @deprecated directive which is implicitly declared for you as follows :
> 
> ```
> directive @deprecated(  reason: String = "No longer supported") on FIELD_DEFINITION | ENUM_VALUE
> ```
> 
> The valid SDL directive locations are as follows :
> 
> ```
> SCHEMA,
> SCALAR,
> OBJECT,
> FIELD_DEFINITION,
> ARGUMENT_DEFINITION,
> INTERFACE,
> UNION,
> ENUM,
> ENUM_VALUE,
> INPUT_OBJECT,
> INPUT_FIELD_DEFINITION
> ```
> 
> Directives are commonly applied to fields definitions but as you can see there are a number of places they can be applied.
> 
> # Another Example - Date Formatting
> Date formatting is a cross cutting concern that we should only have to write once and apply it in many areas.
> 
> The following demonstrates an example schema directive that can apply date formatting to fields that are LocaleDate objects.
> 
> Whats great in this example is that it adds an extra format argument to each field that it is applied to. So the clients can opt into what ever date formatting you provide per request.
> 
> ```
> directive @dateFormat on FIELD_DEFINITION
> 
> type Query {
>     dateField : String @dateFormat
> }
> ```
> 
> Then our runtime code could be :
> 
> ```
> public static class DateFormatting implements SchemaDirectiveWiring {
>     @Override
>     public GraphQLFieldDefinition onField(SchemaDirectiveWiringEnvironment<GraphQLFieldDefinition> environment) {
>         GraphQLFieldDefinition field = environment.getElement();
>         //
>         // DataFetcherFactories.wrapDataFetcher is a helper to wrap data fetchers so that CompletionStage is handled correctly
>         // along with POJOs
>         //
>         DataFetcher dataFetcher = DataFetcherFactories.wrapDataFetcher(field.getDataFetcher(), ((dataFetchingEnvironment, value) -> {
>             DateTimeFormatter dateTimeFormatter = buildFormatter(dataFetchingEnvironment.getArgument("format"));
>             if (value instanceof LocalDateTime) {
>                 return dateTimeFormatter.format((LocalDateTime) value);
>             }
>             return value;
>         }));
> 
>         //
>         // This will extend the field by adding a new "format" argument to it for the date formatting
>         // which allows clients to opt into that as well as wrapping the base data fetcher so it
>         // performs the formatting over top of the base values.
>         //
>         return field.transform(builder -> builder
>                 .argument(GraphQLArgument
>                         .newArgument()
>                         .name("format")
>                         .type(Scalars.GraphQLString)
>                         .defaultValue("dd-MM-YYYY")
>                 )
>                 .dataFetcher(dataFetcher)
>         );
>     }
> 
>     private DateTimeFormatter buildFormatter(String format) {
>         String dtFormat = format != null ? format : "dd-MM-YYYY";
>         return DateTimeFormatter.ofPattern(dtFormat);
>     }
> }
> 
> static GraphQLSchema buildSchema() {
> 
>     String sdlSpec = "" +
>             "type Query {\n" +
>             "    dateField : String @dateFormat \n" +
>             "}";
> 
>     TypeDefinitionRegistry registry = new SchemaParser().parse(sdlSpec);
> 
>     RuntimeWiring runtimeWiring = RuntimeWiring.newRuntimeWiring()
>             .directive("dateFormat", new DateFormatting())
>             .build();
> 
>     return new SchemaGenerator().makeExecutableSchema(registry, runtimeWiring);
> }
> 
> public static void main(String[] args) {
>     GraphQLSchema schema = buildSchema();
>     GraphQL graphql = GraphQL.newGraphQL(schema).build();
> 
>     Map<String, Object> root = new HashMap<>();
>     root.put("dateField", LocalDateTime.of(1969, 10, 8, 0, 0));
> 
>     String query = "" +
>             "query {\n" +
>             "    default : dateField \n" +
>             "    usa : dateField(format : \"MM-dd-YYYY\") \n" +
>             "}";
> 
>     ExecutionInput executionInput = ExecutionInput.newExecutionInput()
>             .root(root)
>             .query(query)
>             .build();
> 
>     ExecutionResult executionResult = graphql.execute(executionInput);
>     Map<String, Object> data = executionResult.getData();
> 
>     // data['default'] == '08-10-1969'
>     // data['usa'] == '10-08-1969'
> }
> ```
> 
> Notice the SDL definition did not have a format argument yet once the directive wiring is applied, it is added to the field definition and hence clients can begin to use it.
> 
> Please note that graphql-java does not ship with this implementation. It is merely provided here as an example of what you could add yourself.
> 
> # Chaining Behaviour
> The directives are applied in the order they are encountered. For example imagine directives that changed the case of a field value.
> 
> ```
> directive @uppercase on FIELD_DEFINITION
> directive @lowercase on FIELD_DEFINITION
> directive @mixedcase on FIELD_DEFINITION
> directive @reversed on FIELD_DEFINITION
> 
> type Query {
>     lowerCaseValue : String @uppercase
>     upperCaseValue : String @lowercase
>     mixedCaseValue : String @mixedcase
> 
>     #
>     # directives are applied in order hence this will be lower, then upper, then mixed then reversed
>     #
>     allTogetherNow : String @lowercase @uppercase @mixedcase @reversed
> }
> ```
> 
> When the above was executed each directive would be applied one on top of the other. Each directive implementation should be careful to preserve the previous data fetcher to retain behaviour (unless of course you mean to throw it away)

In version 14.0, all implementation classes of SchemaDirectiveWiring have no effect, directive annotations do not take effect, and debug is entered inside the implementation class only when the project is just started, not during runtime, and the processing of field return values ​​in the implementation class does not take effect
