### ISSUE TITLE
Type collection and reference replacement does not descend into directive arguments

### ISSUE THREAD

**Issue by kaqqao** [graphql-java/graphql-java#1208]
Seems like neither `GraphQLTypeCollectingVisitor` nor `GraphQLTypeResolvingVisitor` visit directive arguments at all.
As a result, a type that is used in directive arguments only does not become a part of the schema i.e. `schema.getTypeMap()` will not contain it.
Neither will a type reference used in a directive argument get replaced.

Here's a quick example:

```java
GraphQLSchema schema = GraphQLSchema.newSchema()
                .query(GraphQLObjectType.newObject()
                        .name("Query")
                        .field(GraphQLFieldDefinition.newFieldDefinition()
                                .name("test")
                                .type(Scalars.GraphQLString)
                                .argument(GraphQLArgument.newArgument()
                                        .name("in")
                                        //Gets replaced as expected
                                        .type(new GraphQLTypeReference("String"))
                                )
                                .dataFetcher(env -> "test")
                                .withDirective(GraphQLDirective.newDirective()
                                        .name("auth")
                                        .argument(GraphQLArgument.newArgument()
                                                .name("role")
                                                //Does *not* get replaced
                                                .type(new GraphQLTypeReference("String"))
                                                .value("Admin")
                                        )
                                )
                        )
                )
                .build();
```

**Comment by kaqqao** [comment]
I now realize that `GraphQLDirective` isn't even a part of the `GraphQLType` hierarchy, so it's never traversed... Does this mean type collection/reference replacement isn't even _supposed_ to work on directives?

**Comment by bbakerman** [comment]
>  Does this mean type collection/reference replacement isn't even supposed to work on directives, or are they sort of "second class citizens" on purpose?

It's not on purpose but the directives were definitely built out later in the project lifecycle.

I can see now how it needs to be a GraphqlType in order to be visited by Traverser code.

@andimarek - what are you thoughts on this.

GraphQLDirective can be made a GraphQLType in the same way that GraphQLFieldDefinition is a type and yet is not really a type in the true sense.

**Comment by andimarek** [comment]
After looking into it I see that this is more of a broader problem:

\I am not happy that `GraphQLFieldDefinition` is also a `GraphQLType`. I think that is missing the point. `GraphQLType` is misused here as a kind of a `GraphqlSchemaNode`. `GraphQLFieldDefinition` is not the only problem. For example `GraphQLNonNull` is also not really a `GraphQLType`: It doesn't  have name. It should just be a `GraphQLSchemaNode`.
