### ISSUE TITLE
[Question] Graphql DataFetcher with json

### ISSUE THREAD

**Issue by lyuanx** [graphql-java/graphql-java#1217]
Hi,
I've tried using DataFetcher response json:
```
GraphQLFieldDefinition.newFieldDefinition()......dataFetcher(new DataFetcher() {
        public JsonObject get(DataFetchingEnvironment dataFetchingEnvironment) {
                   // remote HTTP response json data like : {person: {name: "", age: 20}}
                   return JsonObject.mapTo(data);
       }
}).build();

// it does't work
graphql.execute("{xxxxx {person {name, age}}}").getData();
```

other way :
```
GraphQLFieldDefinition.newFieldDefinition()......dataFetcher(new DataFetcher() {
        public Object get(DataFetchingEnvironment dataFetchingEnvironment) {
                   // return java bean object
                   return new Person();
       }
}).build();

// it work
graphql.execute("{xxxxx {person {name, age}}}").getData();
```

how can I use DataFetcher response json data ?

**Comment by bbakerman** [comment]
graphql-java does not deal with JSON at all.  You need to use another library like Jackson or GSON to turn the data into a JSON representation.

```
   ExecutionResult executionResult = graphql.execute(...);
   ObjectMapper jacksonMapper = new ObjectMapper();
   jackonMapper.writeValue(new File("target/data.json"), executionResult);
```

This is done on purpose so that consumers are free to produce JSON as they see fit AND also graphql could also be used to server other wire protocols like YAML or XML if you chose.

**Comment by lyuanx** [comment]
Hi,
You don't understand what I mean.
I mean that graphql.execute(....) return data is not null if DataFetcher return java bean
graphql.execute(...) return data is null if DataFetcher return json data
(java bean and json data has the same datastruct)
!!! now I wanna DataFetcher reutrn json data but does't work
can you resolve it, thank you very much

**Comment by bbakerman** [comment]
graphql does not do "pass through JSON" per say

so in your code here

     // remote HTTP response json data like : {person: {name: "", age: 20}}
     return JsonObject.mapTo(data);

what is the `data` element.  If its a java Map, then leave it as one since graphql-java understands maps can treat them as first class data elements.  It does not understand JsonObject what ever that is.
