### ISSUE TITLE
DataFetcher Error -[ExecutionStrategy]: can't fetch fields 

### ISSUE THREAD

**Issue by vro101** [graphql-java/graphql-java#1219]
Hi all,

My first post on this forum concerns fetching fields using a datafetcher more specifically it’s an exception that stems from a executionstrategy.fetch field. Iv’e looked all over online for a possible solution to this specific problem, however none of the posted answers address this specific issue. In this post I am wondering if I am required to change my GraphQL SDL formatted schema and write it programmatically to be able fetch field values from the schema to ultimately execute the query. 
Errors log:

INFO  [2018-09-10 15:38:24,496] org.eclipse.jetty.server.handler.ContextHandler: Started i.d.j.MutableServletContextHandler@361cd35c{/,null,AVAILABLE}
INFO  [2018-09-10 15:38:24,506] org.eclipse.jetty.server.AbstractConnector: Started application@7c011174{HTTP/1.1,[http/1.1]}{0.0.0.0:9000}
INFO  [2018-09-10 15:38:24,506] org.eclipse.jetty.server.AbstractConnector: Started admin@794366a5{HTTP/1.1,[http/1.1]}{0.0.0.0:8081}
INFO  [2018-09-10 15:38:24,507] org.eclipse.jetty.server.Server: Started @3186ms

IN SINGLE CUSTOMER DATAFETCHER
WARN  [2018-09-10 15:38:50,143] graphql.execution.SimpleDataFetcherExceptionHandler: Exception while fetching data (/customer) : null
! java.lang.NullPointerException: null
! at co.vertabiz.api.customer.SingleCustomerDataFetcher.get(SingleCustomerDataFetcher.java:22)
! at co.vertabiz.api.customer.SingleCustomerDataFetcher.get(SingleCustomerDataFetcher.java:8)
! at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:258)
! at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:199)
! at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:70)
! at graphql.execution.Execution.executeOperation(Execution.java:158)
! at graphql.execution.Execution.execute(Execution.java:100)
! at graphql.GraphQL.execute(GraphQL.java:554)
! at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:496)
! at graphql.GraphQL.executeAsync(GraphQL.java:470)
! at graphql.GraphQL.execute(GraphQL.java:401)
! at graphql.servlet.GraphQLQueryInvoker.query(GraphQLQueryInvoker.java:92)
! at graphql.servlet.GraphQLQueryInvoker.query(GraphQLQueryInvoker.java:88)
! at graphql.servlet.GraphQLQueryInvoker.query(GraphQLQueryInvoker.java:39)
! at graphql.servlet.AbstractGraphQLHttpServlet.query(AbstractGraphQLHttpServlet.java:265)
! at graphql.servlet.AbstractGraphQLHttpServlet.lambda$new$0(AbstractGraphQLHttpServlet.java:87)
! at graphql.servlet.AbstractGraphQLHttpServlet.doRequest(AbstractGraphQLHttpServlet.java:236)
! at graphql.servlet.AbstractGraphQLHttpServlet.doRequestAsync(AbstractGraphQLHttpServlet.java:227)
! at graphql.servlet.AbstractGraphQLHttpServlet.doGet(AbstractGraphQLHttpServlet.java:252)
! at javax.servlet.http.HttpServlet.service(HttpServlet.java:686)
! at javax.servlet.http.HttpServlet.service(HttpServlet.java:791)
! at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:49)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)
! at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:35)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:45)
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:39)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
! at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
! at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
! at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1317)
! at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
! at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
! at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
! at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1219)
! at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
! at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:239)
! at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:52)
! at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:724)
! at io.dropwizard.jetty.BiDiGzipHandler.handle(BiDiGzipHandler.java:67)
! at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:56)
! at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169)
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
! at org.eclipse.jetty.server.Server.handle(Server.java:531)
! at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
! at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
! at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
! at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
! at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
! at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)
! at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)
! at java.lang.Thread.run(Thread.java:748)
ERROR [2018-09-10 15:38:50,160] graphql.servlet.DefaultGraphQLErrorHandler: Error executing query (ExceptionWhileDataFetching): Exception while fetching data (/customer) : null

So... from my understanding I think this null pointer exception error stems from the execution.ExecutionStrategy.fetchField call to the parent class which I listed as the SDL example listed below. 

schema {
    query: Query
}

type Query {
    customer (id: String) : Customer

}

type Customer {
      firstName: String
}

I noticed that most GraphQL documentation out there creates the schema using the GraphQL SDL format so I did it the same. But after attempting to debug this error I am starting to think twice about writing it programmatically. 

The reasoning why is because I noticed that the GET http request gets called but is than interrupted by the data fetcher error. To prove this iv’e set print statements in the QueryResource class

 that prints QueryParamater which does not get called since the runtime exception occurs before.

I’m starting to think something is wrong with my schema and that I might possibly need to write it programmatically since this “fetchField” error is language very similar to the syntax when you write schemas programmatically.

Query Resource (GET request) class:

@Path("/graphql")
@Produces(MediaType.TEXT_PLAIN)

public class QueryResource {
	
	ExecutionResult executionResult;
	private GraphQL graphql;
	
	/*GETS HTTP REQUEST FROM SERVER
	 *retrieves and stores paramaterized value 
	 */
	
	@GET
	public List<Customer> runQuery(@QueryParam("query") String query) {
		//http://localhost:9000/graphql?query={customer(id:%221%22){firstName}}

		System.out.println("Query: " + query); //never executes
		executionResult = graphql.execute(query); //never executes
		List<GraphQLError> errors = executionResult.getErrors();
        		Object data = executionResult.getData();
        		System.out.println("DATA IS: " + data);
        	return (List<Customer>) data;
    }
	
	}

Given these circumstances I was wondering if anyone on here has an idea how to solve the graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:258). The data fetcher looks like this at the moment however i’m never able to getArgument(“id) since the run time error occurs before.  

public class SingleCustomerDataFetcher implements DataFetcher<Customer> {

	/*
	 * calls customer repository and retrieves data by customer id 
	 */
	
	private CustomerRepository customerRepository;

	@Override
	public Customer get(DataFetchingEnvironment environment) {
		System.out.println("IN SINGLE CUSTOMER DATAFETCHER");
		String id = environment.getArgument("id"); //never executes
		return customerRepository.findCustomer(id); //never executes

	}
}

I truly appreciate your insight. Happy Coding :)
Thanks,
Alvaro

**Comment by andimarek** [comment]
@vro101 Can you post the full source code for SingleCustomerDataFetcher with the correct line numbers matching the Stacktrace?

thanks

**Comment by andimarek** [comment]
@vro101 see my last comment. If this is not an issue anymore, please close it. Thanks

**Comment by stiyyagura** [comment]
@vro101 was this resolved if yes how did you resolved?
