### ISSUE TITLE
TypeResolver often needs more input to resolve (Relay Node) type

### ISSUE THREAD

**Issue by kaqqao** [graphql-java/graphql-java#122]
**NOTE:** My original example was tragically bad, so I've completely replaced it. As a result, the comments discussing my original example will not make sense. I apologize for that. The gist of the issue is still the same though.

An example of the problem is when resolving a type for a GraphQL interface. The only information available to the `TypeResolver` is the resulting Java object itself, from which the resolver is supposed to deduce the corresponding GraphQL type. This forces the implementor to manually maintain a map of `GraphQLObjectType`s (as the schema object isn't (easily) reachable) and, more importantly, **if the resulting object is an instance of a generic class, this decision is impossible without further information**.

Suppose the following:

```
interface Repository { ... } 
 
class InMemoryRepository<T> implements Repository { ... }
```

`InMemoryRepository<Order>` might map to e.g. `InMemoryRepository_Order` GraphQL type (that has a `containedItem` field of type `Order`), while `InMemoryRepository<Product>` might map to `InMemoryRepository_Product` GraphQL type (that has a `containedItem` field of type `Product`), both implementing `Repository`:

```
type InMemoryRepository_Order implements Repository {
  containedItem: Order
}

type InMemoryRepository_Product implements Repository {
  containedItem: Product
}
```

When `TypeResolver` receives an instance of `InMemoryRepository`, there's no way to decide the GraphQL type: as it may be `InMemoryRepository_Order` or `InMemoryRepository_Product`.

If `TypeResolver` were to receive more information, it may be able to deduce the type. E.g. if it had access to the `Field` object, it could get the Java type of the field e.g. `InMemoryRepository<Order>` and it may deduce the corresponding type should be `InMemoryRepository_Order`. (It's possible to store the mapped Java type into `Field`'s GraphQL type, as demonstrated by _graphql-java-annotations_ [here](https://github.com/graphql-java/graphql-java-annotations/blob/master/src/main/java/graphql/annotations/GraphQLObjectTypeWrapper.java#L31)). With some advanced type analysis, even subtypes can be dealt with, e.g. if the runtime type of the resulting object wasn't `InMemoryRepository` but some subtype of it. I use this type of advanced analysis in my project (link below).

For example, in [graphql-java-annotations](https://github.com/graphql-java/graphql-java-annotations/blob/master/src/main/java/graphql/annotations/GraphQLObjectBackedByClass.java#L18) and [schemagen-graphql](https://github.com/bpatters/schemagen-graphql/blob/master/src/main/java/com/bretpatterson/schemagen/graphql/impl/GraphQLObjectMapper.java#L741) this exact strategy could be used for a much richer type resolution logic (a `Type` could be used instead of just a `Class` and combined with the runtime type of the resulting object).
In general, this change is especially of value to the maintainers of libraries that rely on GraphQL-Java (and we fortunately have a few of those now, [mine](https://github.com/leangen/GraphQL-SPQR) included), because when developing a library as opposed the final project, the Java types can not be known ahead of time, so strategies like inspecting the runtime type of `containedItem` in the example above e.g. `repo.getContainedItem().getClass()` are impossible.

The change I propose to allow such advanced type resolution logic is providing `TypeResolver` most of the data available to `DataFetchingEnvironment` (this object is called `TypeResolutionEnvironment` in [my PR](https://github.com/graphql-java/graphql-java/pull/343/files#diff-e23cffe7fe924557fcea3c3e038c2617)) instead of just the resulting object. You can see this in use in my project: https://github.com/leangen/graphql-spqr/blob/master/src/main/java/io/leangen/graphql/generator/HintedTypeResolver.java#L44 

It can be argued that this is an edge case, but that would imply usage of generics with this library in general is an edge case. I firmly believe that the fact we're dealing with a _Java_ implementation of the GraphQL spec means it needs to deeply support _Java_ idioms.

**Comment by okorz001** [comment]
instanceof?

**Comment by kaqqao** [comment]
Ha, with the way I worded the example, you're right! I now realize just how terrible job I've done trying to explain my problem. In my attempts to simplify the explanation of the situation I'm facing, I completely butchered the example. Sorry for that. I've made at attempt at fixing it. It's still somewhat vague, but I really hope it does a better job than the previous version.

**Comment by okorz001** [comment]
Is the id not in the returned User object?

**Comment by kaqqao** [comment]
Well, think of Relay global ID required by the Node spec. An ID is in the User return object, but it's no longer prefixed. The prefix was used only ti satisfy Relay Node query, and to know what object type is being queried for.
So the result would contain ID "1234" but not "act-1234".

**Comment by ntkoopman** [comment]
Why would it have a different type if the actual class is the same?

Anyway, instead of using a User object directly, you could wrap it inside a TypedUser object that contained the the User object and the correct type.

**Comment by kaqqao** [comment]
There's really nothing saying Java and GraphQL types need to match 1:1. They have very different type systems and different mappings can easily be needed. As for the TypedUser class, that's exactly what I'm doing now, but the TypedUser class has to be generated dynamically, at runtime, as the lib I'm working on has to work with types unknown ahead of time. This is both limiting (as it requires default constructor to always exist) and needlessly complicated and expensive. That's why I'm proposing to simply forward DataFetchingEnvironment to the TypeResolver. Solves exciting edge cases, and if the current TypeResolver constructor signature is retained, breaks nothing.

**Comment by DomKM** [comment]
I am also running into this issue. @kaqqao's suggestion that the `DataFetchingEnvironment` be made available to `TypeResolver` would solve it perfectly. This is also the approach that Apollo's [`graphql-tools`](http://dev.apollodata.com/tools/graphql-tools/resolvers.html#Unions-and-interfaces) uses for their type resolver signature.

**Comment by dminkovsky** [comment]
@DomKM yes we're trying to figure out an approach for this, for the next breaking release.

**Comment by kaqqao** [comment]
I've just tried removing the dependency on our forked version of graphql-java in out project and realized it's more painful than expected as `TypeResolver` doesn't even give access to the schema. And since `TypeResolver`s are instantiated before the schema is even built, it means there's no way to even provide the schema through constructor... which either means mutability/synchronization issues with adding the schema later or manually maintaining a schema-like registry of GraphQL types. And both are rather awful :(
I really hope the next release will bring some resolution.

**Comment by bbakerman** [comment]
is this related to #205 ?

**Comment by kaqqao** [comment]
I answered in #205. In short, yes, I believe solving this one may solve or at least alleviate #205 as well.
