### ISSUE TITLE
how to handle response

### ISSUE THREAD

**Issue by tbo-axelor** [graphql-java/graphql-java#1223]
i want to handle response
for example:

1) query { contact { id,name } }
query 1 return list of contact
response : { data: { contact: [ {id: 1,name: "john"},{id: 2,name: "smith"} ] } }

but i want in response data and pageInfo object like {
{ data: { contact: [ {id: 1,name: "john"},{id: 2,name: "smith"} ] } , pageInfo: { total: 2} }

so how to handle response ??

**Comment by bbakerman** [comment]
If you need pageInfo data in your returned data then you MUST have it in the query and you MUST have it in your underlying schema.

    query { 
        contact { id,name } 
        pageInfo { total }
     }

in graphql, the data you get back is ALWAYS described by the query
