### ISSUE TITLE
All top level fields do not get batch dispatched in an aliased query with multiple top level fields.

### ISSUE THREAD

**Issue by ashu-walmart** [graphql-java/graphql-java#1224]
Is it correct to always set the expected strategy calls for the first level to 1? My test scenario has multiple aliased graphql queries are in a single request. As described here:https://graphql.org/learn/queries/#aliases.  should level 1 expected strategy calls be incremented then? Or am I understanding the code incorrectly.

https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/execution/instrumentation/dataloader/FieldLevelTrackingApproach.java#L48

**Comment by andimarek** [comment]
Hi @ashu-walmart, 

This line you linked sets the strategy calls for level 1 to 1: even if you have multiple toplevel fields you only have one strategy execute call.

Do you have a failing test-case to describe your problem better?

Thanks,
Andi

**Comment by ashu-walmart** [comment]
Thanks for the response @andimarek. I will create a test case for this and see if I can reproduce the error. In the application I am working on, the batched data loader seems to have inconsistencies in batching requests for the top level aliased fields. The test in my application has 3 top level fields but only two get batched together in the first dispatch and the third one is a seperate dispatch.

**Comment by ashu-walmart** [comment]
https://gist.github.com/ashu-walmart/8f8c40b6fdd649d03db95b5b5cb78437. Here is the failing test case I created. Is the test and expectation is correct?

**Comment by bbakerman** [comment]
I am guessing it is failing on the expected "batch" calls and not the expected data?

I would expect that test to pass on the number of batch calls for optimal efficienciency

**Comment by andimarek** [comment]
closing, because it was answered https://github.com/graphql-java/graphql-java/pull/1235#issuecomment-425697777
