### ISSUE TITLE
Wrong error message "queryStrategy must be non null"

### ISSUE THREAD

**Issue by Ricki-BumbleDev** [graphql-java/graphql-java#1227]
https://github.com/graphql-java/graphql-java/blob/e45bea82274ae5853eed4aa33e8706c88368abe3/src/main/java/graphql/GraphQL.java#L254

It should say `graphQLSchema must be non null` instead of `queryStrategy must be non null` here.

**Comment by bbakerman** [comment]
Thanks for reporting this.

Could you help us out and make a PR here please
