### ISSUE TITLE
Ability to get parsed directive argument values inside a DataFetcher

### ISSUE THREAD

**Issue by kaqqao** [graphql-java/graphql-java#1228]
Given a query such as:

```graphql
{
    books(author: "John Doe") @cache(enabled = true) {
        isbn
        title
    }
}
```
where `@cache` is a custom directive, I'd expect to be able to get the value (`true`) of the `enabled` argument in a fashion similar to how I can get the value of `author`.

Currently, it's only possible to get the non-parsed value:

```java
Value cacheEnabled = dataFetchingEnvironment
                            .getField()
                            .getDirective("cache")
                            .getArgument("enabled")
                            .getValue()
```
For a scalar value (like here), it's not too hard to get the parsed value from `Value`, but it also means taking variables into account. Gets significantly more complicated for object values.

The only way to parse the values is by using `ValuesResolver` which is internal API.

So I propose an extension to the `DataFetchingEnvironment`, e.g. `DataFetchingEnvironment#getDirectiveArguments(String)` that would return the parsed values exactly the same `DataFetchingEnvironment#getArguments` does:

```java
Map<String, Object> cacheEnabled = dataFetchingEnvironment.getDirectiveArguments("cache");

//or

Optional<Boolean> cacheEnabled = dataFetchingEnvironment
                            .getDirectiveArgument("cache", "enabled");
```

**Comment by bbakerman** [comment]
@kaqqao - this will help any efforts in regard to https://github.com/graphql-java/graphql-java/issues/1211 - eg better input validation.

**Comment by dondonz** [comment]
Closing this old issue as PRs have been merged
