### ISSUE TITLE
mapped property

### ISSUE THREAD

**Issue by tbo-axelor** [graphql-java/graphql-java#1231]
is it possible to mapped propperty 
for example::: { contact { id,name } this query is working fine.
but i am creating new schema like { contact { fields {id,name } } } then how to mapped field defination means field.id or field.name

**Comment by andimarek** [comment]
Hi @tbo-axelor,

please provide more informations, I don't know what you mean.

Thanks

**Comment by bbakerman** [comment]
{ 
         contact { 
             id,name 
         }     
    }

In SDL your original query probably matched a a schema like

```
    type Query {
          contact : Contact
     }

    type Contact {
          id : ID
          name
     }

```

So to have a query like

```
   { 
       contact { 
           fields { 
                id,name 
            } 
        } 
     }
```

You would need a schema like

```
    type Query {
          contact : Contact
     }

     type Contact {
         fields : Fields
     }
    
    type Fields {
          id : ID
          name
     }

```

Extra levels are extra types in the schema

**Comment by bbakerman** [comment]
Closing this issue
