### ISSUE TITLE
DataFetcher javadoc should mention returning a DataFetcherResult

### ISSUE THREAD

**Issue by osi** [graphql-java/graphql-java#1236]
As mentioned at https://graphql-java.readthedocs.io/en/latest/execution.html#returning-data-and-errors , the javadoc for `DataFetcher` should mention the ability to return a `DataFetcherResult`

**Comment by andimarek** [comment]
thanks @osi,

can you create a PR for that? That would be really create. Thanks!

**Comment by osi** [comment]
aye will do

-- 
(peter.royal|osi)@pobox.com - http://fotap.org/~osi
