### ISSUE TITLE
Request scoped DataLoader: confusing dependencies

### ISSUE THREAD

**Issue by mattes3** [graphql-java/graphql-java#1237]
Hi,

I'm upgrading from graphql-java 6.0 to 10.0. I want to get rid of BatchedExecutionStrategy and therefore, I am trying to use DataLoaders. But: The dependencies really confuse me:

- The RuntimeWiring knows the DataFetcher(s).
- Each DataFetcher knows a DataLoader.
- A DataLoader knows a BatchedDataLoader.

DataLoaders should be *per request*. However, if a DataFetcher knows the DataLoader, the DataFetcher has to be per-request, too. But: This can't be true because RuntimeWiring is not per-request but it is static, because GraphQLSchema should be static. (at least the docs page at https://graphql-java.readthedocs.io/en/latest/batching.html says so).

This is a contradiction:
1. RuntimeWiring must be per-request because it depends on per-request DataFetchers.
1. RuntimeWiring must be static because the static GraphQLSchema depends on RuntimeWiring.

I don't get it. Which object should really have which scope?

Can somebody help me with this so that I can really upgrade to V10.0?

Thanks a lot...
Matthias

**Comment by mattes3** [comment]
Oh, I just found the answer: https://github.com/graphql-java/graphql-java-http-example/blob/master/src/main/java/com/graphql/example/http/StarWarsWiring.java

The DataLoader registry is in the Context object which allows keeping the DataLoaders per-request.

**Comment by andimarek** [comment]
would you mind creating a PR for docs to improve the documentation? That would be really awesome ... thanks a lot

**Comment by bbakerman** [comment]
The challenge is that for most people DataLoaders should be per request, but for some it does not matter so its not possible to  have a one strategy fits all.  I agree we can do a better job of documenting this

**Comment by mattes3** [comment]
I will write something in the docs and send you a PR.

**Comment by mattes3** [comment]
PR #1241 is ready.
