### ISSUE TITLE
Simple Query for recursive types

### ISSUE THREAD

**Issue by ryber** [graphql-java/graphql-java#1242]
Hello,
  I have a recursive data structure that represents an organizational hierarchy. at it's most simple the POJO for this looks like:

```java
class Org {
    String id;
    Set<Org> children;
}

```
I gave this modeled in GraphQL just fine but I've found there is no way to query it without explicitly asking for each layer:

```javascript
org {
	id, 
	children {
		id,
		children {
			id,
			children {
				id
				children {
					id
				}
			}
		}
	}
}
```

The possible depth of one of these hierarchies is unknown (although in reality it is most likely less than 10 (10 being crazy town).

I would like people using the API to NOT have to make such an ugly query. It doesn't seem like the standard supports this (see https://github.com/facebook/graphql/issues/91#issuecomment-206743676) but I was hoping maybe in the Java framework there was some way around this.

My only other option would be to define this particular query as just returning JSON, which eliminates all the other advantages of using GraphQL to begin with.

**Comment by bbakerman** [comment]
Sorry but this is a design goal of the graphql specification.  graphql has a design goal which is that in order to retrieve a data element, you need to ask for that data element.

Contrast this to say REST where you ask for a resource BUT not which data elements.  And hence the size and shape of the response is a server concern and not a strict contract.

> My only other option would be to define this particular query as just returning JSON, which eliminates all the other advantages of using GraphQL to begin with.

This is the point.  Graphql is not arbitary JSON blobs but rather JSON responses that represent the query.

**Comment by ryber** [comment]
> Sorry but this is a design goal of the graphql specification. graphql has a design goal which is that in order to retrieve a data element, you need to ask for that data element.

There is no reason the specification can't allow for that in this case by allowing me to say "this fragment, recursively, up to a depth of x" or allow the implementation to define x. It's a huge flaw IMO. Not supporting these kinds of data structures well doesn't mean they don't exist or that GraphQL can't be a great platform to support them.
