### ISSUE TITLE
DataFetchingEnvironment Arguments are null on Resolvers

### ISSUE THREAD

**Issue by senzzzi** [graphql-java/graphql-java#1245]
When I set an argument like dataFetchingEnvironment.getArguments.put("foo", "bar") and try to get this arguments on a GraphQLResolver function that receives the DataFetchingEnvironment, the arguments are empty. I am not sure, but I think this was working in a previous version. I already opened an issue similar to this one on graphql spring boot repo but it was pointed out that it was probably an issue with this library. For queries, my workaround was to use the attributes on HttpServletRequest but for subscriptions I can't do that. Is there anyway for me to set a global variable using subscriptions? Is it OK to use "variables" map inside of ExecutionContext or it exists for other purposes?

**Comment by bbakerman** [comment]
Also `dataFetchingEnvironment.getArguments.put("foo", "bar"`) is no an allowed function

We use a copy of the arguments and give that to you.  Pretty standard immutable stuff.

if you Must have a mutable store then create your own context object that allows that

for example

```
       Object  get(DataFetcherEnvironment dfe) {
      
           MyContext myContext = dfe.getContext();
  
           myContext.put("foo","bar")
           ....
```

You can then read it later

**Comment by bbakerman** [comment]
As for global context, thats what the ExecutionInput context is for

See

https://github.com/graphql-java/graphql-java-http-example/blob/master/src/main/java/com/graphql/example/http/HttpMain.java#L108

**Comment by senzzzi** [comment]
@bbakerman that did the trick, thanks a lot for help! This was not an issue at all.

**Comment by andimarek** [comment]
closing according to the last comment.
