### ISSUE TITLE
Pass custom data to DataFetcher

### ISSUE THREAD

**Issue by joshstrange** [graphql-java/graphql-java#1248]
I have a data fetcher that is acting in a way like a proxy. It get's a request and fires off 2 more requests into our system (not into GraphQl but our Akka system). When some of our code fires off a message to another part of our code we include things like who the source of the request was (the userId) and the permissions they have (so we can gate things). The problem is by the time I get to my DataFetcher I have no idea who is responsible for the request so I can't attach their info to be fired back off into our system.

The dumbed down example of this is just I have have a String I have at time of calling .execute on a query and I need access to that String inside my DataFetcher. Is this possible?

**Comment by bbakerman** [comment]
Have a look at ExecutionInput and the "context" parameter.

This gets passed down on the call and is available in ALL DataFetchingEnvironments

https://github.com/graphql-java/graphql-java-http-example/blob/master/src/main/java/com/graphql/example/http/HttpMain.java#L108

**Comment by joshstrange** [comment]
Thank you @bbakerman! You have been extremely helpful in answering all my questions and I'd like to thank you for the time and effort you put into this library, it's a godsend!
