### ISSUE TITLE
DataFetcher requires runtime object

### ISSUE THREAD

**Issue by sra-013** [graphql-java/graphql-java#1250]
My application takes a person's account details at runtime and uses those to fetch details about the person. How to create a dynamic data fetcher? Can runtime wiring be built at compile time?

**Comment by bbakerman** [comment]
All this can be done.

I suggest you first read the documentation

https://graphql-java.readthedocs.io/en/latest/

and perhaps look at a sample app

https://github.com/graphql-java/graphql-java-http-example

The code behind a data fetcher is the dynamic bit of graphql

**Comment by sra-013** [comment]
According to my understanding, if I want to fetch data based on the current user credentials, I'll have to use the getContext() method of the DataFetchingEnvironment. However, I am unable to figure out how to actually call the method and initialize the context.

**Comment by sra-013** [comment]
"Some people use a dependency framework that injects context into data fetchers automatically and hence don’t need to use this." I am using Spring so according to the above statement, I would not have to inject context explicitly. How do I go about it in that case?

**Comment by bbakerman** [comment]
Again have a look at the code in https://github.com/graphql-java/graphql-java-http-example

It has all you need
