### ISSUE TITLE
Reviving the BatchedExecutionStrategy through DataLoaders?

### ISSUE THREAD

**Issue by sp00m** [graphql-java/graphql-java#1256]
I quite heavily relied on `graphql-java-tools` and the `BatchedExecutionStrategy` for a project I'm working on, so I got a bit worried when I saw it deprecated (although I fully get the point and I would have done the same, #noblame).

Firstly: why got `graphql-java-tools` moved out of https://github.com/graphql-java to https://github.com/graphql-java-kickstart/graphql-java-tools? I couldn't find any explanation on both repos. What consequence does this have?

Secondly, I've been thinking of a way to allow `BatchLoader` to actually provide more than "simple keys", but instead the sources and the arguments to mimic the way the `BatchedExecutionStrategy` used to work, and I think I've found a possible solution.

I've written a fairly small tool to test it and I would really appreciate getting feedbacks frown this community: https://github.com/sp00m/graphql-gom. Although it's still work in progress, I've tried to document it well so that you fully get the idea.

Put simply, these three issues made me start implementing it:
- https://github.com/graphql-java/graphql-java/issues/963
- https://github.com/graphql-java-kickstart/graphql-java-tools/issues/58
- https://github.com/graphql-java/java-dataloader/issues/26

Excerpt of the README:

> You know how `BatchLoader`s are supposed to take only _keys_ to allow fetching the corresponding values from your data source? For example:
> 
> ```java
> BatchLoader<Integer, Article> articleBatchLoader = new BatchLoader<Integer, Article>() {
>     
>     @Override
>     public CompletionStage<List<Article>> load(List<Integer> keys) {
>         return articleService.getArticles(keys);
>     }
>     
> };
> ```
> 
> Well, what GOM does, is basically "enhancing" those keys by passing instances of `DataLoaderKey` instead (internal class):
> 
> ```java
> class DataLoaderKey {
>     
>     // the source, got via DataFetchingEnvironment#getSource
>     private Object source;
>     
>     // the arguments, got via DataFetchingEnvironment#getArguments
>     private Object arguments;
>     
>     // the context, got via DataFetchingEnvironment#getContext
>     private Object context;
>     
> }
> ```
> 
> This trick then allows a `BatchLoader` to "group the keys by arguments", and thus call _your resolvers_ as many times as there are distinct arguments, but each time will all the sources.

What do you think of such a solution? Is it viable? Do you see any issues of using `DataLoader` with "enhanced keys"?

**Comment by sp00m** [comment]
Thanks for your answer, I get your point about caching, but I'm not too sure it's an issue in the way I've been trying to use `BatchLoader`s.

Say with the example of `Blog 1..n Article 1..n Comment`, correct me if I'm wrong, but I think the original idea of `BatchLoader`s is to have three of them in this case:

- one BlogBatchLoader, called by Article#blog
- one ArticleBatchLoader, called by both Blog#articles and Comment#Article
- one CommentBatchLoader, called by Article#comment

In such an implementation, I can see how the key I proposed could be an issue, especially for the ArticleBatchLoader as it can be called by both Blog#articles and Comment#article.

The way I've tried to use `BatchLoader`s though, isn't "one by entity" but "one by source-target relation", so you would have:

- one for Article#blog
- one for Blog#articles
- one for Comment#Article
- one for CommentBatchLoader

In this case, I don't see caching as an issue (but actually a great addition), as I can't find a case where calling `Comment#Article` twice with the same `Comment` source should give a different result (note that I'm talking about per-query cache). What do you think? Or did I misunderstood anything?

---

I saw this `BatchLoaderWithContext` indeed, but to be honest, I'm not too sure how this could work. For example with the following query:

```
query {
  blogs {
    articlesWithFooInTitle: articles(whereTitleContains: "foo") {
      title
    }
    articlesWithBarInTitle: articles(whereTitleContains: "bar") {
      title
    }
  }
}
```

How would you make the underlying `ArticleBatchLoader`s trigger only the two following queries (pseudo code):

- `select from article where blog in (:theSourceBlogs) and title like 'foo'`
- `select from article where blog in (:theSourceBlogs) and title like 'bar'`

?

Thanks for your time!

**Comment by sp00m** [comment]
Well actually, the best would be to know how one would implement the resolution of such a schema with `BatchLoaderWithContext`s (not the proper implementation of course, but a high overview of the architecture would be great): https://github.com/sp00m/graphql-gom/blob/master/src/test/resources/graphql/gom/example/example.graphql.

**Comment by bbakerman** [comment]
You have outlined some pretty good examples and I am not 100% sure just yet how to respond

Let me talk to my colleagues about what you have presented and let me get back to you

**Comment by sp00m** [comment]
Really appreciate this, thanks for your time 🥇

**Comment by doxavore** [comment]
To be clear, the [v10 documentation for batching](https://www.graphql-java.com/documentation/v10/batching/) suggests using the deprecated `BatchLoader`, and as of today, we're not aware of a way to get the `WHERE id in (1, 2, 4)` functionality using non-deprecated features? I haven't seen anything else to suggest how one might do this without custom `List<Long>`-style loaders that won't respect the cache.

**Comment by bbakerman** [comment]
@doxavore - the documentation suggests using `BatchLoader` functions - but they are not deprecated.  

The come from the java-dataloader library which is howe we think people should do batching, that also follows spec.

Each DataLoader has a "batch loader function" like this

```
BatchLoader<Long, User> userBatchLoader = new BatchLoader<Long, User>() {
            @Override
            public CompletionStage<List<User>> load(List<Long> userIds) {
                return CompletableFuture.supplyAsync(() -> {
                    return userManager.loadUsersById(userIds);
                });
            }
        };
       DataLoader<Long, User> userLoader = DataLoader.newDataLoader(userBatchLoader);

```

It gives you all the batched ids in one call.  You can then use that to put it into SQL say.

Can you outline your use case more clearly about how you dont think you can achieve your aims using DataLoader (+their associated BatchLoader function)

**Comment by bbakerman** [comment]
@sp00m 

I had a go at trying to implement the example above using DataLoader

The code is in Groovy in Spock unit testing format

https://gist.github.com/bbakerman/2304079e0c87fb198fc348cdb26edf2b

The "keys" here when we call dataLoader.load(key) are in fact the blogId + textToSearchFor.  The reason for this is that is the unique dimension being searched for. 

So given data

```
    def blogData = [
            new Blog(id: 1, name: "Java", purpose: "Java stuff"),
            new Blog(id: 2, name: "Reactive", purpose: "Rx stuff")
    ]

    def articleData = [
            new Article(id: 101, blogId: 1, title: "Changes in the LTR policy of the JDK"),
            new Article(id: 102, blogId: 1, title: "CPU impact of the JVM Memory Model"),

            new Article(id: 200, blogId: 2, title: "So you want to use less CPU"),
            new Article(id: 201, blogId: 2, title: "Why reactive systems use less CPU")
    ]
```

and a query of

```
        query {
          blogs {
            id
            name
            articlesWithCPUInTitle: articles(whereTitleContains: "CPU") {
                blogId
                title
            }
            articlesWithReactiveInTitle: articles(whereTitleContains: "reactive") {
                blogId
                title
            }
          }
        }
```

it returns a result of

```
[blogs:
   [[id:1, name:Java, 
              articlesWithCPUInTitle:[[blogId:1, title:CPU impact of the JVM Memory Model]], 
              articlesWithReactiveInTitle:[]], 
   [id:2, name:Reactive, 
               articlesWithCPUInTitle:[[blogId:2, title:So you want to use less CPU], [blogId:2, title:Why reactive systems use less CPU]], 
                articlesWithReactiveInTitle:[[blogId:2, title:Why reactive systems use less CPU]]]]]
```

This only calls the BatchLoader function once for all blog instances (2) and for each sub field (2 x 2)

**Comment by bbakerman** [comment]
ps.  I didnt use Foo/Bar but "CPU / Reactive" as search terms

**Comment by sp00m** [comment]
That's brilliant, many thanks for your time again!

So we've basically ended up with the same approach if I understand correctly: having a custom type for the `BatchLoader` keys, that holds both the source id and the arguments (which is basically what I've implemented in [graphql-gom](https://github.com/sp00m/graphql-gom)).

> The reason for this is that is the unique dimension being searched for.

Nice wording, that's basically it yeah. Caching will still operate for an identical "sourceId+ searchText" pair, which does make sense with this schema.

Thanks again, I just wanted to make sure this was the correct approach. Feel free to close this ticket, unless you have things to add?

🙏

**Comment by sp00m** [comment]
PS: I'm pretty sure other devs could be interested by this snippet of yours BTW. Maybe it deserves a link in graphql-java's docs?

**Comment by bbakerman** [comment]
I agree this could be made into a tutorial or documentation example
