### ISSUE TITLE
A printer?

### ISSUE THREAD

**Issue by dminkovsky** [graphql-java/graphql-java#126]
Hi,

I didn't see a printer in the repository anywhere, something like https://github.com/graphql/graphql-js/blob/master/src/language/printer.js.

So I wrote one: https://gist.github.com/dminkovsky/b5efd2df4a13c6c89a01c5c49fbdffc8#file-graphqlprinter-java

I haven't fully tested this. But the AST I've needed to print has printed correctly. Thought maybe to contribute. Are there other plans for a printer?

Regarding the implementation/style, the way it is now, it could use some double dispatch with `Node`. But the big switch works. Also, I considered/attempted/aborted writing a reducing<String> visitor as in LB's JS implementation, but the approach I took was just much simpler for me.

**Comment by yrashk** [comment]
I think this would be a very valuable addition as it helps figuring out what went wrong with the design of the schema much faster than reading a JSON representation of the introspection query result.

**Comment by danielkwinsor** [comment]
For printing, I set a jackson mapper to indent and let it do the work on the json introspection:
```
    public static ObjectMapper mapper = new ObjectMapper().enable(SerializationFeature.INDENT_OUTPUT);
    public static String prettyPrint(Map<String, Object> resultMap) {
        try {
            return mapper.writeValueAsString(resultMap);
        }
        catch (JsonProcessingException e) {
            e.printStackTrace();
            return resultMap.toString();
        }
    }
```
Looks like
```
{
  "testObj" : {
    "strings" : [ "asdf", "2", "test" ],
    "ints" : [ 0 ],
    "objects" : [ {
      "objName" : "name",
```

How is the output of your printer different from the json introspection result?  Can you show an example output?

**Comment by dminkovsky** [comment]
@danielkwinsor this printer is for printing GraphQL AST Java Objects (graphql.language) into a GraphQL string. The use case for me is to manipulate input GraphQL AST and then print it back out into GraphQL string as a request to an upstream service.

**Comment by dminkovsky** [comment]
@yrashk this is actually not a schema printer. This is an AST node printer. A schema printer is needed, too though, for the purpose you mention. Should also be pretty simple, but with tests.

**Comment by dminkovsky** [comment]
Closing this for now. Can revisit with pull request.

**Comment by dminkovsky** [comment]
Re-opening because we definitely want a printer. Just want it to be tested and on a PR.

**Comment by aschrijver** [comment]
@dminkovsky Your gist would be best. The `ObjectMapper` approach would be opinionated, leading to a Jackson dependency, just _one_ of the popular Json parsers around.
While I am using Jackson myself in most of my projects, you would probably be forcing this on, say 50 to 60% (just guessing) of developers using other json libraries.

**Comment by dminkovsky** [comment]
I'm still bit confused regarding the mentions of JSON and specifically Jackson here. This printer produces GraphQL Documents from AST nodes. Is JSON relevant to this?

**Comment by aschrijver** [comment]
I just reacted on @danielkwinsor code snippet which used Jackson `ObjectMapper`. Json has not much to do with it except Jackson started originally as a json library (can now handle many formats)

**Comment by zhbrass** [comment]
I modified the gist by @dminkovsky to use pre-Java 8 features. Feel free to use.
https://gist.github.com/zhbrass/1fd7fbabad852a323740682065708b1b

**Comment by bbakerman** [comment]
The PR here now adds a pretty printer for reverse decompiling a schema

https://github.com/graphql-java/graphql-java/pull/386

**Comment by dminkovsky** [comment]
Makes sense to close this then!

**Comment by RusticFlare** [comment]
_(Because I still had to go looking for this)_

You can print by using the **`SchemaPrinter`** class.

```java
SchemaPrinter schemaPrinter = new SchemaPrinter();
schemaPrinter.print(schema);
```
