### ISSUE TITLE
Investigate what it would take to add File upload support to graphql-java

### ISSUE THREAD

**Issue by bbakerman** [graphql-java/graphql-java#1261]
See https://github.com/jaydenseric/graphql-multipart-request-spec

and an implementation : https://github.com/jaydenseric/graphql-multipart-request-spec

Note: This is not specified by the graphql spec

**Comment by osi** [comment]
Nothing is required. It's been implemented at https://github.com/graphql-java-kickstart/graphql-java-servlet/pull/102 .. the payload transformation happens before entering the execution engine.

**Comment by andimarek** [comment]
@bbakerman 12.0 or later? thx

**Comment by bbakerman** [comment]
Looking into it - it is not a graphql-java engine thing.

It consists of standard types + the ability to take say MultiPart message objects as input to a scalar "File".

I feel like this is a extended-scalars thing or best left to a code layer that deals with HTTP

**Comment by mcbain** [comment]
I cannot get it running. What should the schema look like?

```
type Mutation {
  singleUpload(file: Upload!): Boolean!
}
```

What is `Upload` supposed to be? I tried already input, scalar, none worked.

https://github.com/jaydenseric/graphql-multipart-request-spec
 
```curl localhost:8080/graphql   -F operations='{ "query": "mutation ($file: Upload!) { singleUpload(file: $file)  }", "variables": { "file": nulmap='{ "0": ["variables.file"] }'   -F 0=@pom.xml```

**Comment by mxmlnglt** [comment]
> figured it out
> 
> ```
>  @Bean
>   GraphQLScalarType upload() {
>     return graphql.servlet.ApolloScalars.Upload;
>   }
> ```

Hello, where are you supposed to add this? I'm using an extra GraphQL-related layer, i.e. the GraphQL Java Tools library to read & build the schema (from GraphQL DSL)?

**Comment by ntf** [comment]
In case someone from search result looking for how to add upload support to `graphql-java` without adding even more dependencies, 

you may refer to my solution in this gist: 
https://gist.github.com/ntf/c08fed23dc5cba2a4375a7317e14c013

**Comment by gclsgithub** [comment]
@mcbain 
How do you test the upload method?
I user [org.apache.http.client.HttpClient] to test the upload method(singleUpload).but it always failed.
can you tell me the right client in springboot to test upload method.

**Comment by gclsgithub** [comment]
@mcbain 
How do you test the upload method?
I user [org.apache.http.client.HttpClient] to test the upload method(singleUpload).but it always failed.
can you tell me the right client by springboot to test upload method.

**Comment by bambrozio** [comment]
Hi, please: what dependency do I have to add to my gradle list in order to have `ApolloScalars.Upload`?
