### ISSUE TITLE
Schema Parsing

### ISSUE THREAD

**Issue by sra-013** [graphql-java/graphql-java#1262]
Can a fragment be defined only for types that have only atomic data inside them, i.e. no lists, etc.?

**Comment by bbakerman** [comment]
No... a fragment can be defined for any type.

Have  a look at http://graphql.org/learn/

**Comment by bbakerman** [comment]
```
fragment comparisonFields on Character {
  name
  appearsIn
  friends {
    name
  }
}
```

In this example friends is a list AND a compund object type

**Comment by sra-013** [comment]
Thanks!
