### ISSUE TITLE
GraphQL-Java ignores duplicate fields

### ISSUE THREAD

**Issue by fforw** [graphql-java/graphql-java#1266]
I have a test case that tests the error condition of duplicate field definitions which can arise from a miuse of our API. In 8.0 the test throws a project specific exception based on graphl-java throwing a `graphql.AssertException: Duplicated definition for field 'sourceFour' in type 'TargetFour'`.

In 10.0 the assert doesn't happen. I cut the problem down to  this test case

```java
import graphql.AssertException;
import graphql.Scalars;
import graphql.schema.GraphQLFieldDefinition;
import graphql.schema.GraphQLObjectType;
import graphql.schema.GraphQLSchema;
import org.junit.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class GraphQLRegression
{
    private final static Logger log = LoggerFactory.getLogger(GraphQLRegression.class);


    @Test(expected = AssertException.class)
    public void testDoubleDeclaration()
    {
        final GraphQLSchema.Builder builder = GraphQLSchema.newSchema();

        final GraphQLObjectType.Builder objectBuilder = GraphQLObjectType.newObject()
            .name("TargetFour")
            .field(
                GraphQLFieldDefinition.newFieldDefinition()
                .name("sourceFour")
                .type(Scalars.GraphQLString)
            )
            .field(
                GraphQLFieldDefinition.newFieldDefinition()
                .name("sourceFour")
                .type(Scalars.GraphQLString)
            );

        builder.query(
            GraphQLObjectType.newObject()
                .name("QueryType")
            .build()
        );
        builder.mutation(
            GraphQLObjectType.newObject()
                .name("MutationType")
            .build()
        );

        builder.additionalType(objectBuilder.build());


        log.info("SCHEMA: {}", builder.build());
    }
}

```

**Comment by bbakerman** [comment]
The reason it does not assert is that the builder (that you used) now uses a map internally and will cause fields to be keyed by name

```
        public Builder field(GraphQLFieldDefinition fieldDefinition) {
            assertNotNull(fieldDefinition, "fieldDefinition can't be null");
            this.fields.put(fieldDefinition.getName(), fieldDefinition);
            return this;
        }
```

By the time the constructor runs there is no duplicate.  It has the last field definition.  However in the past we didnt have builders and you could call the constructor directly and hence get it wrong.

There is no regression here.  The code is just improved

**Comment by bbakerman** [comment]
But thanks for reporting it

**Comment by fforw** [comment]
Improved? It ignores a duplicate definition!

**Comment by fforw** [comment]
Did I miss the documentation of this behavior? If not it seems that is something that should be documented clearly.

**Comment by bbakerman** [comment]
We could improve the java doc on this I agree

**Comment by alamothe** [comment]
Sorry to comment on an old issue, but this is really problematic. 

Where should the validation happen then if we are using the builder?

**Comment by bbakerman** [comment]
We are not going to fix this.  For the same reason as mentioned above.  

The builder has `map` put semantics and has since 2018

You are the caller of the builder  - if you want to stop yourself putting the same field twice into the same builder by name - add custom code to yourself.

**Comment by alamothe** [comment]
Builders are the only way provided by the library to construct the schema. So effectively, this library does not perform validation if two fields with the same name exist in the schema. And isn't this validation required to be performed by the GraphQL spec?

By extension, builders could be silently dropping this or that (we don't know) and by the time they call the constructor, the validation passes, but the user is not aware of the problem. 

I don't have a magic idea to fix it, but it seems to me a design flaw with the library. At least an alternative to the builder (plain constructor, which does the validation) should be provided.

**Comment by bbakerman** [comment]
> Builders are the only way provided by the library to construct the schema.

Thats not true - we have SDL as well .  In fact this is probably the most powerful way to build schema.

> So effectively, this library does not perform validation if two fields with the same name exist in the schema.

Thats simply not true.  We have a difference of opinion on when is the right time to perform validation

Imagine this simplified Java example

```
Map<String,String> map = new HashMap<>();
map.put("key1", "val1");
map.put("key1", "val2");
```

now HashMaps can only contain one value per key.  Has Java failed to enforce this constraint?  It already had a key with a value and it allows another one?

Our builders have embraced map semantics BECAUSE in a type system where the name if unique - map semantic works a treat.

> but it seems to me a design flaw with the library.

It's not a flaw - it's a feature - we wanted map semantics because it's idiomatically Java like.

Se above for the `transform` case where we also want  map semantics

**Comment by alamothe** [comment]
What is SDL? 

You insisting that lack of validation is a feature, just because of the way you implemented it, does not make it a feature. From the user perspective, the library does not perform the check.

**Comment by bbakerman** [comment]
SDL is Schema Definition Language

```
type Query {
  fieldF : Foo 
}

type Foo {
  fiedBar : String
}
```

SDL can be used to declare types - it will always be complete and duplicate fields will be detected.

> From the user perspective, the library does not perform the check.

I posit that what you sar saying "from your point of view perspective, the library does not perform the check."

I have given you our code design position and how we want map semantics on field creation at the lower GraphqlXXX schea element level.

I have also explained you you and others that we won't be changing it.
