### ISSUE TITLE
Unions too strict on field type checking?

### ISSUE THREAD

**Issue by ind1go** [graphql-java/graphql-java#1281]
This is a question regarding interpretation of the spec - I'm wondering if there is a bug in union support. I've not compared to the reference implementation, I've just been looking at the spec.

Consider [this test](https://github.com/graphql-java/graphql-java/blob/master/src/test/groovy/graphql/validation/rules/OverlappingFieldsCanBeMergedTest.groovy#L116) and the following tests. They ensure that when a union type is used with two or more types containing a field of the same name, that field must be exactly the same in terms of type and nullability. So this, for example, is invalid:

```graphql
boxUnion {
    ...on IntBox {
        scalar
    }
    ...on StringBox {
        scalar
    }
}
```
returning the error `Validation error of type FieldsConflict: scalar: they return differing types Int and String @ 'boxUnion'`.

I can't see anywhere in the spec that says this form of checking is required - and indeed, it seems like the point of unions is to provide a space for very different types to be injected, which might also involve differing types. Consider the example of the GitHub search API, for example - the responses you get back from searching for a text term might be commits, users, repositories, and so on, all with different fields and there might be fields that overlap but have different types between the two.

Is it possible that this checking is unnecessary?

**Comment by bbakerman** [comment]
Of hand without doing any deep investigation I do recall us tightening the fields in fragments being of different types.   Its possible what is intended for interfaces should not apply to unions.

But as I said I have not looked into this in detail.

Let us look at the spec and also the reference implementation.

Thanks for reporting this

**Comment by bbakerman** [comment]
Have a look at https://facebook.github.io/graphql/June2018/#sec-Field-Selection-Merging

> Explanatory Text

> If multiple field selections with the same response names are encountered during execution, the field and arguments to execute and the resulting value should be unambiguous. Therefore any two field selections which might both be encountered for the same object are only valid if they are equivalent.

> During execution, the simultaneous execution of fields with the same response name is accomplished by MergeSelectionSets() and CollectFields().

> For simple hand‐written GraphQL, this rule is obviously a clear developer error, however nested fragments can make this difficult to detect manually.

I suspect that this is part of the answer here

Looking at this reference implementation is pretty much has this tests (which @andimarek  ported way back in 2015 originally)

**Comment by andimarek** [comment]
closing this issue now ... @ind1go please reopen if it is unclear or you wanna add something ... thanks
