### ISSUE TITLE
PropertyDataFetcher gets private fields by default

### ISSUE THREAD

**Issue by piotrblasiak** [graphql-java/graphql-java#1284]
This came as a huge surprise to me. If there is no explicit data fetcher set for a property, the PropertyDataFetcher which seems to be the default one fetches private fields. Is this really the way it should be and is there any way to change this so that private fields are protected by default?

**Comment by bbakerman** [comment]
PropertyDataFetcher is the default fetcher if no other is specified over it.

It will try to get field values (using the field name as the property name) first by public getter method, next by setAcceissible access on methods and then public field and finally by setAccessible field.

This means is just works out of the box at the expense of deeply following Javabeans specs on getters.  We took inspiration from GSON in this regard (which does something similar)

But if you dont like it then you can use your own property fetchers that implement the rules you would like to see.

We currently dont have a global mechanism to change the behaviour of PropertyFetcher

**Comment by piotrblasiak** [comment]
Ok, thanks for adding the change to PropertyDataFetcher - but by making the default that it will fetch private fields and no way of changing the default for the whole thing this opens up for some nasty bugs.
I am using class-level access control annotations on my domain objects, which I think is quite common. If I forget to create an explicit getter or have a getter with parameters then the PropertyDataFetcher will simply bypass the access control check without me noticing it. I really think that people expect private class members to not be accessible by graphql by default.
I know GSON does this as well, but I think in that case it´s also quite nasty and even if some people like it there is probably a large number of people that don´t expect this to be the default.
I would greatly appreciate it if you could turn it off by default by providing some data fetcher factory or something.

**Comment by bbakerman** [comment]
>  I really think that people expect private class members to not be accessible by graphql by default.

We have two choices
 1. by open by default but make it possible to be closed
 2. be closed by default but make it possible to be open

We have chose the first one.  There are pros and cons on what approach any library should take.

We do have a data fetcher factory mechanism for wiring in default fetchers however.

Have a look at `graphql.schema.idl.WiringFactory` and its parent class `graphql.schema.idl.RuntimeWiring` about how you can use them to inject a default fetcher

`graphql.schema.idl.WiringFactory#getDefaultDataFetcher`

**Comment by bbakerman** [comment]
I am going to close this issue as its now possible to make the property fetcher only get public fields
