### ISSUE TITLE
Can't serialize value (status) : Invalid input for Enum 'Status'. Unknown value 'pendingPayment

### ISSUE THREAD

**Issue by Maclaon** [graphql-java/graphql-java#1291]
how should i set annotation of enum field of a class?

**Comment by andimarek** [comment]
can you please give us more details about what are you trying to do?
Thanks!

**Comment by Maclaon** [comment]
sorry, my mistake, i posted wrong place for my issue, it should be on [graphql-spqr](https://github.com/leangen/graphql-spqr)
