### ISSUE TITLE
Interests in a BinaryTreeTypeRegistry in upstream lib

### ISSUE THREAD

**Issue by zcourts** [graphql-java/graphql-java#1293]
Hello all,
This issue is to get an idea of whether there's any interest in a binary tree style type registry in the upstream graphql-java.
We've created this as a result of how we do what others commonly call "schema stitching". 

**Some background**
We allow third party developers to define schemas for the apps they submit to our platform. We also allow a developer to `depend` on existing app's schemas. Dev 1 published Schema1 and Dev 2 can depend on Schema1 in their new Schema2 inheriting all the types and functions in it.

Until now we've been taking the two independent type registries and copying everything from both and merging into a new schema. This has proven to be a bit fragile and as graphql-java is tending towards immutable definitions everywhere it's becoming tricky to do everything we were doing before.

**The proposal**
As a result we're currently working on what amounts to a binary tree (sort of) type registry.
The registry itself stores all the SDL types the current graphql-java `TypeDefinitionRegistry` stores and in addition also stores two references to other `TypeDefintionRegistry` objects (optionally).

This is a left-biased binary tree hierarchical type registry i.e.
When an operation is performed, it first operates on the current instance (hence why I said sort of a binary tree because if first checks current instance followed by LHS then RHS), if the current instance cannot fulfil the operation

1. The left-hand side parent registry has the same operation attempted. If the the direct parent is also a
{@link BinaryTreeTypeRegistry} then it will attempt the operation and then on its parents (both left and right parents if any), this will repeat until no parents are found.
2. If the left hand side fails, the right-hand side is attempted and it in turn attempts to use all its parents until none are found
3. Finally, if neither this node in the tree or any of its parents can fulfil the operation, it will fail.
The method of failure depends on the operation but is generally an exception or an empty {@link Optional}.

As I was doing the initial work on this it occurred to me that it may generally be useful outside of our use case so I'm creating this issue to see if there's any interest in having a PR for it to be merged in upstream.

**Comment by bbakerman** [comment]
We would be interesting in what you might be thinking.

I guess some of our design principles we use on graphql-java are as follows.  So the closer to them that this might be the better it would be to get accepted

* We prefer closer to zero dependencies.  Dont bring in guava, apache-commons, spring-xxx, y or z however much some StringUtils method might be useful.  Less dependencies makes graphql-java more applicable to everyone

* We prefer staying out of the HTTP stack.  We are the low level engine of running graphql queries.  Other concerns such as JSON and HTTP are handled better by other layers

* We prefer simple code to clever code.  It should be readable with well named methods.  Clever nested streams and lambas are not our thing

* We prefer general to specific.  So the code should be generally applicable to use cases, not highly specific to just some use cases, even if it takes more setup.


Based on what I read above it might be quite exciting to have a "type registry" system that defaults to multiple participants (as long as it can still work ok for the general case of "read sdl, build type registry, wire schema" like it does today

So please consider a PR to show what you are thinking.  we often use strawman PRs that are not tested or even compile as a mechanism to show your working.

**Comment by zcourts** [comment]
That's good to hear! I actually did a quick prototype before I flew (conference for the week). The implementation is beyond rough, but is functional.

Copy and pasted the impl here https://gist.github.com/zcourts/2a2dc316310b7344794ddef64c6ca690#file-binarytreetyperegistry-java-L226

Line 226 linked is the biggest atrocity of the impl.
It demonstrates the point though and does work.
