### ISSUE TITLE
Boolean fields *must* be accessed using an isX method

### ISSUE THREAD

**Issue by sazzer** [graphql-java/graphql-java#130]
If you have a DataFetcher that returns an object instance for the data, and the object uses "getX" fields for accessing booleans then this causes the values to not be discovered and so null is returned instead.

As a concrete example of this, the Kotlin Language generates getters for properties automatically, but always in the form "getX". This is allowed by the Java Beans specification (Section 8.3.2), but fails here. I can imagine it might be the case with other places that API model objects are generated instead of hand-written.

**Comment by sazzer** [comment]
The problem is in PropertyDataFetcher.getPropertyViaGetter(). Updating it to support both isX and getX fields looks simple enough, so I might have a go if I get enough spare time.

**Comment by danielkwinsor** [comment]
I like PropertyDataFetcher the way it is, but alternative behavior can be subclassed.  The reason I like it as is: consider isClass and getClass.  Or consider isAnything and getAnything where the return types are different, or what is not expected.  This could be worse than getting null values.

With that said, I've already subclassed these fetchers in my own code and suggest the same here.

**Comment by sazzer** [comment]
If you have both an isXxx and a getXxx method for the same name but with
different return types, you're not a valid Java bean according to the spec.
It's acceptable to have both but they should reflect the same field and
therefore have the same value.

If the PropertyDataFetcher is to be used purely for beans this means this
is a non issue. If it's to be used for any arbitrary class then your right
it causes problems...

**Comment by ayhanap** [comment]
I also had problem with Boolean property accessors generated with [Lombok](https://github.com/rzwitserloot/lombok) and IDEA. The convention suggests `is` prefix for primitive `boolean` getters, so I think supporting `get` prefix for `Boolean` getters should bring no harm.

Aggree @sazzer for classes having both `isXxx `and `getXxx`. Even that is the case supplied a pull request #164 prioritizing `is` over `get` prefix for Boolean properties.

**Comment by markphilpot** [comment]
Closing this since we merged the fix [here](https://github.com/graphql-java/graphql-java/issues/164).
