### ISSUE TITLE
Requested Addition to Documentation (Programmatic Schemas)

### ISSUE THREAD

**Issue by dupski** [graphql-java/graphql-java#1301]
I'd like to submit a PR for the below, but I'm not sure where your docs repo is?

The [Creating a schema](https://www.graphql-java.com/documentation/master/schema/) doc has a section on "Creating a schema programmatically" however it does not give the detail on how to get the final `GraphQLSchema` from the programmatically-generated types.

I eventually figured out the you just need to instantiate a GraphQLSchema and pass the root Query type as the first parameter (but not before spending an hour unsuccessfully fiddling with `TypeDefinitionRegistry.add()` ) :P

Please can something like the following detail be added to the "Creating a schema programmatically" documentation section:

## Making a programmatically-generated schema executable

For programmatically-generated schemas, there is no need to use the `SchemaGenerator`, you can just instantiate a `GraphQLSchema` object directly, and pass in your root `Query` (and `Mutation`) `GraphQLObjectType` objects.

```java
GraphQLObjectType queryType = newObject()
            .name("QueryType")
            .field(newFieldDefinition()
                    .name("hello")
                    .type(GraphQLString)
                    .dataFetcher(new StaticDataFetcher("world!"))
            .build();

GraphQLSchema schema = new GraphQLSchema(queryType);

// Make the schema executable
GraphQL executor = GraphQL.newGraphQL(graphQLSchema).build()
ExecutionResult executionResult = executor.execute("{hello}");
```

**Comment by bbakerman** [comment]
The website repo is here : https://github.com/graphql-java/graphql-java-page

This directory has the latest (unrelesed) doco https://github.com/graphql-java/graphql-java-page/tree/master/content/documentation/master

**Comment by dupski** [comment]
Cool cheers. I shall sort out a PR :)
