### ISSUE TITLE
java.lang.NoClassDefFoundError: graphql/schema/DataFetcher

### ISSUE THREAD

**Issue by khteh** [graphql-java/graphql-java#1303]
I follow https://www.graphql-java.com/documentation/master/getting-started/ and bump into this error:

`Error: Unable to initialize main class com.mycompany.app.App
Caused by: java.lang.NoClassDefFoundError: graphql/schema/DataFetcher`

**Comment by bbakerman** [comment]
java.lang.NoClassDefFoundError are typically caused by an earlier exception where the class gets poisoned and cant be loaded for some reason.

Without more exceptions and information its impossible to tell you what is going on.

**Comment by khteh** [comment]
How can I debug this? I am new to java. I tried using jdb and it just exited without any stack trace:
`C:\Projects\Java\GraphQL\HelloWorld>jdb target\HelloWorld-1.0.jar
Initializing jdb ...
> trace
Command 'trace' is not valid until the VM is started with the 'run' command
> run
run target\HelloWorld-1.0.jar
Set uncaught java.lang.Throwable
Set deferred uncaught java.lang.Throwable
>
VM Started: Error: Could not find or load main class target\HelloWorld-1.0.jar
Caused by: java.lang.ClassNotFoundException: target\HelloWorld-1.0.jar

The application exited`

**Comment by khteh** [comment]
I use Sprint Tool Suite 4 and this is what I see at the console window:

`SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
{hello=Hello World!!!}`

**Comment by bbakerman** [comment]
Sorry but we cant really help you write a java program via issues on the graphql-java project.  Its just too wide a field to say "how do I write a Java program"

I recommend you get yourself a copy of a great IDE like Intellij IDEA or Eclipse and read a bunch of beginner tutorials.

**Comment by bhaskey** [comment]
I started reading the graphql-java tutorial and faced the same error. I haven't found it out where, but it seems this is because it is SL4J is required somewhere graphql-java, and it has to be in the classpath.

Adding sl4j in classpath, solved this for me.

```json
dependencies {
    implementation 'org.slf4j:slf4j-simple:2.0.0-alpha7'
}
```
