### ISSUE TITLE
MaxQueryComplexityInstrumentation usage

### ISSUE THREAD

**Issue by mudlee** [graphql-java/graphql-java#1304]
Hi. I'd like to reject queries if its complexity is greater than X. where I'd like to define field complexity with directives. I found that extending my query from MaxQueryComplexityInstrumentation, and providing a FieldComplexityCalculator in the constructor is the way(?) from the validation side.
If I return a fix number, such as 10 from that calculator, it works correctly.

However, I tried to define a custom directive in the schema, but in the FieldComplexityCalculator, the directives property for the field is empty. 

Notes: I use graphql-java-tools, graphql-spring-boot-starter

Thanks.

**Comment by bbakerman** [comment]
I am not sure how graphql-java-tools works and hence how it allows you to insert your instrumentations not how it reacts to "abort query" exception that MaxQueryComplexityInstrumentation throws.

It sounds like the abstractions over graphql-java are not helping you in this case.

**Comment by bbakerman** [comment]
I am going to close this as it seems a graphql-java-tools issue
