### ISSUE TITLE
No method for releasing Objects acquired by a DataFetcher or RootObjectBuilders

### ISSUE THREAD

**Issue by juergen-albert** [graphql-java/graphql-java#1305]
As far as I'm able to read the API, I can't find any possibility to released resources I have used during the processing of a call. If not the Datafetcher would be a good place to add a release Method. Especially in more dynamic environments it is necessary, because I need to release e.g. services or transactions after I used them.

**Comment by bbakerman** [comment]
The data fetcher is the place where code to get values for individual fields should be placed.

However if you have transactions / resources that need to span multiple fields (or the whole query) then your should look at using a custom `graphql.execution.instrumentation.Instrumentation` that knows the boundaries of your resources.

The `graphql.execution.instrumentation.Instrumentation` will be called back progressively as each stage (and field) is processed.

**Comment by bbakerman** [comment]
I am going to close this -  you are free to wrap your data fetchers via Instrumentation and we are unlikelt to create specific `release` lifecycle methods in the core library
