### ISSUE TITLE
How to register filter specially for cors filter specially OPTIONS request 

### ISSUE THREAD

**Issue by abhinav-jain09** [graphql-java/graphql-java#1307]
Hi Team,

I am using spring cloud function (inside spring boot )with Azure and GraphQL . Since graphql does not support the OPTIONS method need to write from my own as an filter . I have created the java file as following but it is not working. not sure if I need to do extra configuration
 ```
@Configuration
public class CorsConfig {
    @Bean
    public FilterRegistrationBean corsFilter() {
        UrlBasedCorsConfigurationSource source = new UrlBasedCorsConfigurationSource();
        CorsConfiguration config = new CorsConfiguration();
        config.setAllowCredentials(true);
        config.addAllowedOrigin("*");
        config.addAllowedHeader("*");
        config.addAllowedMethod("*");
        source.registerCorsConfiguration("/**", config);
        FilterRegistrationBean bean = new FilterRegistrationBean(new CorsFilter(source));
        bean.setOrder(0);
        return bean;
    }
}

```

I also set the grapQL properties in the Application.properties like as follows 
```
graphql.servlet.mapping =  /graphql/**
graphql.servlet.enabled = true
graphql.servlet.corsEnabled = true
```
still it does not work 
I am not sure what else I have to do inroder to respond to the OPTIONS request

**Comment by bbakerman** [comment]
Sorry I think you have the wrong project.  graphql-java is the base library that does query execution.

I think you want the https://github.com/graphql-java-kickstart/graphql-java-servlet project
