### ISSUE TITLE
Introspection query returns types in arbitrary order

### ISSUE THREAD

**Issue by arlampin** [graphql-java/graphql-java#1314]
We store the generated GraphQL schema JSON in our Git repo, as it is consumed by various tools. We have noticed that re-generating the JSON results in different output even when there are no changes in our actual schema. I'm not sure if graphql-java is meant to support deterministic schema JSON generation, but there seem to be lots of LinkedHashMaps/Sets internally, and I can't think of any other reason for them.

I noticed that at least GraphQLSchema.Builder stores additionalTypes in plain HashSet, while GraphQLSchema itself stores them in LinkedHashSet. Also, GraphQLTypeCollectingVisitor uses plain HashMap, which means GraphQLSchema's typeMap is also a HashMap.

**Comment by bbakerman** [comment]
I agree with you that a stable introspection system is a win.  I have started some PRs to try and address this.

The graphql spec says nothing about a stable order when a type is asked for its fields (althought query results must be stable) and graphql-js itself just uses Object js map behavior which is also not stable.

However in terms of debuggability and predictability a stable order is important.  Out SchemaPrinter already does name sorting for stability reasons.  I think the graphql types themselves should give out elements in a stable manner

**Comment by bbakerman** [comment]
The next version will have stable sort order of fields and types
