### ISSUE TITLE
Indicate schema compatibility or implement introspection query

### ISSUE THREAD

**Issue by aschrijver** [graphql-java/graphql-java#132]
It seems like the introspection query for my version of `graphql` does not match the one that is implemented in `graphql-java`. I am using graphql v0.5.0 and it has a `__schema.directives.locations` key that is not recognized.
I think it would help if the project stated the graphql version it is compatible with, so I can copy the introspection query from the correct lib.

With regards to the discussion in #109 : As the implementation is bound to a specific version of the GraphQL spec, it wouldn't be such bad idea to have some introspection query support in the project (e.g. to generate a schema for clients to use)

**Comment by danielkwinsor** [comment]
I am not familiar with graphql-js or what version this project exactly mimics.  You can try the introspection query from graphiql, which I know works.

Our __Directive definitely does not have locations as laid out at http://facebook.github.io/graphql/#sec-The-__Directive-Type but instead we have boolean `onOperation onFragment onField`.  I believe you can introspect the __Direction type itself, can you try that?

**Comment by danielkwinsor** [comment]
Yeah, I can't remember what version of graphiql I was using, but it generated basically the same query as the previous history at https://github.com/graphql/graphql-js/commits/master/src/utilities/introspectionQuery.js

We are compatible with the query from before [[RFC] Proposed change to directive location introspection](https://github.com/graphql/graphql-js/commit/e89c19d2ce584f924c2e0e472a61bb805ce260d4)

**Comment by aschrijver** [comment]
Yes, thanks. I created some code similar to graphql-js and would like to do a pull request.
But first I have to install a JDK 6 (Using Oracle JDK8 myself) and have Gradle use this one too.

Note that in JDK 8 the code does NOT compile by default because the Javadoc in the antlr-generated classes contains empty `<p/>` tags which is no longer allowed. Leads to 100 errors right now.
Maybe this can be changed in the code generation.

**Comment by aschrijver** [comment]
I create a separate issue for the javadoc part. See #134

**Comment by aschrijver** [comment]
Issue can be closed. Introspection query is present in codebase.

**Comment by dminkovsky** [comment]
Cool, thanks.

By the way, thanks to this issue/commit, I made this Maven plugin that helps accelerate iterating with Relay: https://github.com/dminkovsky/babel-relay-maven-plugin. If you use Maven and Relay, you'll find it useful?

**Comment by aschrijver** [comment]
That's a coincidence. I am using Gradle and was just working on something similar.
Nice project. I will star it anyway.

I don't have a very clean gradle way. At build time I invoke tools jar that creates the schema.json
Looking into aggregating multiple schema's into one (one schema per microservice).
The hacky way is to just aggregate the generated json's.
