### ISSUE TITLE
Adding SchemaDirective with SpringBoot starter

### ISSUE THREAD

**Issue by AnkitaBasu** [graphql-java/graphql-java#1338]
i have tried to implement a custom SchemaDirective in a  Spring boot application which uses the graphql starter and GraphQLQueryResolver and have not written any separate DataFetchers

public class AuthorisationDirective implements SchemaDirectiveWiring {

    @Override
    public GraphQLFieldDefinition onField(SchemaDirectiveWiringEnvironment<GraphQLFieldDefinition> schemaDirectiveWiringEnv) {
        String targetAuthRole = (String) schemaDirectiveWiringEnv.getDirective().getArgument("role").getValue();

        GraphQLFieldDefinition field = schemaDirectiveWiringEnv.getElement();
        //
        // build a data fetcher that first checks authorisation roles before then calling the original data fetcher
        //
        DataFetcher originalDataFetcher = field.getDataFetcher();
        DataFetcher authDataFetcher = new DataFetcher() {
            @Override
            public Object get(DataFetchingEnvironment dataFetchingEnvironment) throws Exception {
                Map<String, Object> contextMap = dataFetchingEnvironment.getContext();
                //AuthorisationCtx authContext = (AuthorisationCtx) contextMap.get("authContext");

                if ("dev".equals(targetAuthRole)) {
                    return originalDataFetcher.get(dataFetchingEnvironment);
                } else {
                    return "Un-Authorized";
                }
            }
        };
        //
        // now change the field definition to have the new authorising data fetcher
        return field.transform(builder -> builder.dataFetcher(authDataFetcher));
    }
}

		<dependency>
		    <groupId>com.graphql-java</groupId>
		    <artifactId>graphql-java</artifactId>
		    <version>11.0</version>
		</dependency>
		<dependency>
		    <groupId>com.graphql-java</groupId>
		    <artifactId>graphql-java-tools</artifactId>
		    <version>5.2.3</version>
		</dependency>
		<dependency>
		    <groupId>com.graphql-java</groupId>
		    <artifactId>graphql-java-servlet</artifactId>
		    <version>6.1.2</version>
		</dependency>
		<dependency>
			<groupId>com.graphql-java</groupId>
			<artifactId>graphql-spring-boot-starter</artifactId>
			<version>5.0.2</version>
		</dependency>
		<dependency>
			<groupId>com.graphql-java</groupId>
			<artifactId>graphiql-spring-boot-starter</artifactId>
			<version>5.0.2</version>
		</dependency>

However the directive is not getting applied to the fields, i tried to put it in debug mode and noticed that the control never goes to the Directive class. How do i register it? is it expected to register it self automatically in spring boot ?

Also below is how i used it in .graphqls file <snippet>

directive @auth(role : String!) on FIELD_DEFINITION
type Customer {
	ccid : String
	firstName: String
	lastName: String @auth(role : "manager")
	birthDate: String
	phone: [Phone]
	email: [Email]
	address: [Address]
	account: [Account]
	primaryAccountCreationDate: String
	autoPayEnrollList: [AutoPayEnrollMain]
	dependent: [Dependent]
}

type Query {
    searchCustomer(data:String!,start:Int,rows:Int) : [Customer]
}
Thanks

**Comment by andimarek** [comment]
I am sorry @AnkitaBasu that we didn't answer you when you created the ticket. I am closing it now, because I assume it is not relevant anymore. If not true, please open it again.
