### ISSUE TITLE
Javadoc does not compile with JDK 8

### ISSUE THREAD

**Issue by aschrijver** [graphql-java/graphql-java#134]
Note that in JDK 8 the code does NOT compile by default because the Javadoc in the antlr-generated classes contains empty <p/> tags which is no longer allowed.
This regardless of 6.0 compatibility settings in `build.gradle` and leads to about 100 compilation errors right now.
Maybe this can be changed in the code generation, so a build is possible without first switching JVM and Gradle JVM settings.

**Comment by aschrijver** [comment]
PS It might be helpful if the README included explanation on how the ANTLR classes where generated. AFAICS this is not part of the project now, or I've missed it.

**Comment by danielkwinsor** [comment]
There is a plugin to auto fix javadoc, I'll see about fixing that.

**Comment by aschrijver** [comment]
Fixed with #141 .  Thanks!
Closing.
