### ISSUE TITLE
Partial updates 

### ISSUE THREAD

**Issue by raderio** [graphql-java/graphql-java#1343]
Is it possible to add support for partial updates like in https://medium.com/workflowgen/graphql-mutations-partial-updates-implementation-bff586bda989

The main idea is that in JavaScript are value like `undefined`.
So, you can check if a parameter was not provided and do not update the field in database.

**Comment by raderio** [comment]
May be is it possible to achieve by adding a wrapper class like `Undefined<T>`, it is something like `Optional<T>`, so it or has value(nullable or non nullable value) or is not defined

**Comment by bbakerman** [comment]
You can already do most of this in graphql-java today.

Imagine you have a type system like this

```
            input PersonInput {
                firstName : String
                lastName : String = "defaultedLastName" 
            }
            
            type Mutation {
                updatePerson(lastName : String, firstName : String, personInput : PersonInput) : String
            }
```

When the data fetcher for `updatePerson` it is given a `DataFetchingEnvironment`.  You can today ask 2 questions

     boolean containsArg = dfe.containsArgument("firstName")
     Object firstNameValue = dfe.getArgument("firstName")

If a field argument is NOT specified then there will be NO entries in the map for that key.

I agree that `DataFetchingEnvironment` should have a `getArgumentOpt` to returns an `Optional` to better codify this in one call.

But in the mean time you can do that yourself.

You can then decide in your data fetcher how to "apply" arguments to the underlying data storage. eg if the `lastName` is missing then dont make  a call to set it.

**Comment by bbakerman** [comment]
Not this also works on complex input types eg `PersonInput` above

if `firstName` is not set into the structure, then the resultant runtime map object that represents "personInput" argument will be missing.

The following update the graphql spec covers this

https://github.com/facebook/graphql/pull/418/files

**Comment by raderio** [comment]
Cool, thanks.

>I agree that DataFetchingEnvironment should have a getArgumentOpt to returns an Optional to better codify this in one call.

+1

**Comment by AllirionX** [comment]
I am late to the party, but I implemented this with graphql-java-kickstart and it can be adapted to graphql-java: https://github.com/graphql-java-kickstart/graphql-java-tools/issues/141#issuecomment-560938020

**Comment by antch** [comment]
@raderio I'm a bit confused here -- you gave a +1 and closed the issue as completed but I don't see any support for `Optional`. Am I missing something?
