### ISSUE TITLE
Java 6 compatible, but build needs at least JDK 7 to succeed

### ISSUE THREAD

**Issue by aschrijver** [graphql-java/graphql-java#135]
Although the code is Java 6 compatible it does not compile on a JDK 6 installation due to some generics issues where e.g.:
```
boolean includeDeprecated = environment.getArgument("includeDeprecated");
```

Leads to:
```
graphql-java/src/main/java/graphql/introspection/Introspection.java:175: type parameters of <T>T cannot be determined; no unique maximal instance exists for type variable T with upper bounds boolean,java.lang.Object
```

Personally I prefer using a current JDK, i.e. Java 8 right now (see also: https://groups.google.com/forum/#!topic/graphql-java/iCCN2T1RgyI ), but if it is 6, then it should compile on 6 or there should be a mention in the README on the JDK to use.

(PS Found this while dealing with #134 )

**Comment by danielkwinsor** [comment]
Try the workaround in #124

**Comment by aschrijver** [comment]
You mean workaround = use JDK 7? Yes, I found that too. Sorry I didn't see #124 before.
To fix these issues IMHO the project should provide a bit more clarity:

1. It should compile on the JDK it is compatible with 
- And preferably on newer JDK's as well without modification
- If this is not the case the build requirements should be mentioned in the README
2. There should be a clear choice on minimum compatibility
- Now it is JDK 6, but there is an open question about it on the [forum](https://groups.google.com/forum/#!topic/graphql-java/iCCN2T1RgyI)

On 2. I prefer a JDK that is not end-of-life and lacks the new language features that have become the norm in modern Java development, but that's personal :).

**Comment by andimarek** [comment]
Thanks for your feedback.

You are right: While we state graphql-java is written in Java 6 and we try to support it, the current CI task doesn't  compile with 6, but rather 7. We need not fix that or be more clear how we support Java 6.

I also updated the old forum question that the PR was merged.

**Comment by aschrijver** [comment]
Thanks!

**Comment by okorz001** [comment]
Personally, I think it is rather difficult to support Java 6 without automated builds in a Java 6 environment. Without automated builds, you are relying on manual detection of Java 6 incompatibilities.

**Comment by andimarek** [comment]
@okorz001 It is automatically build with jdk7, but with source and target set to 6. It is not perfect, but when it successfully builds you can use with Java6, unless we have used some jdk7 library function, which didn't exist in 6.

**Comment by andimarek** [comment]
I created a PR to ensure that graphql-java is java 6 compatible: #145

**Comment by danielkwinsor** [comment]
Please check #146, which makes a JDK6u65 ./gradlew clean build work.
I don't understand the docker build `java:8` well enough, but my understanding of #145 is that this uses JDK8's javac and links to JRE6 runtime library (rt.jar or whatevs) along with source and target 6.

I use http://mojo.codehaus.org/animal-sniffer-maven-plugin/ at work to detect JRE6/JRE8 problems in our 6->8 transition.  Just FYI only.

**Comment by aschrijver** [comment]
HI @andimarek @danielkwinsor ,

I tried #146 both with OpenJDK (1.6.0_38) and Oracle JDK (1.6.0_45) and compiles without problem. So together with #145 everything should work well, even with TravisCI, I guess.

**Comment by andimarek** [comment]
Hi @aschrijver: I am closing this Issue, because it seems there is nothing left to. Thanks.

**Comment by aschrijver** [comment]
Yep. I agree. I am bit quiet these days...taking some time off the deck :wink:
