### ISSUE TITLE
How to read implement Authorization using Graphql with spring-boot? 

### ISSUE THREAD

**Issue by suneelkumar45** [graphql-java/graphql-java#1359]
HI

I need examples to implement the graphql authorization. basically, In my project trying to Implement the Authentication and Authorization of the service calls. I have  service invokation defined in QueryResolver and MutationResolver. before invoking any of the service calls i want to read the token passed in Header and validate for each and every service invocation.  In documentation and from few blogs explained to use context using DataFetchEnvironment but  unclear with the approach. need help !!

Thanks,
Suneel Kumar

**Comment by ieugen** [comment]
Look at graphql-servlet and graphql spring boot. This library does not know HTTP.

**Comment by andimarek** [comment]
closing because it doesn't concern this library: please open this issue in the appropriate lib on top of GraphQL Java (depending on what you are using) thanks
