### ISSUE TITLE
Enumerations that get populated with a Java Enum don't work correctly

### ISSUE THREAD

**Issue by sazzer** [graphql-java/graphql-java#137]
I have defined a GraphQLEnumType to use in my schema, with a set of values generated from a Java Enumeration. As far as the schema definition goes this seems to work fine. 

However, if I actually return a payload that contains the Java Enum as the value instead of the String name then the response I get out is actually null.

This appears to be because in GraphQLEnumType.getNameByValue(), it iterates over the list of possible values (Which must be Strings) and does a .equals() on it to compare to the provided value. This can only ever pass if the response object is also a String.

It would be very useful if it would detect that an enum was returned instead and get the name of it first.

**Comment by sazzer** [comment]
Fixing this is probably as simple as changing the method to read: (Note I wrote this here and haven't tested it)
```
    private Object getNameByValue(Object value) {
        Object valueToUse = value;
        if (value instanceof Enum) {
            valueToUse = ((Enum)value).name();
        }
        for (GraphQLEnumValueDefinition valueDefinition : valueDefinitionMap.values()) {
            if (valueToUse.equals(valueDefinition.getValue())) return valueDefinition.getName();
        }
        return null;
    }
```

**Comment by danielkwinsor** [comment]
Can you please show your GraphQLEnumValueDefinitions?  From my reading of the code, the definition has a value of type Object, so you can insert Planets.EARTH as value.  When your DF returns Planets.EARTH that should .equal().

**Comment by sazzer** [comment]
Ah - Somehow I'd missed that there was a version of GraphQLEnumType that
takes an Object as the value. I've been using just the single-param
version. I'll give that a go and see what happens :)

**Comment by sazzer** [comment]
I've just tried it with the method that you've mentioned, and it turns out that it works fine. Sorry about that :(
