### ISSUE TITLE
Allow "." in operation name

### ISSUE THREAD

**Issue by raderio** [graphql-java/graphql-java#1372]
At the moment we can name our operation by a name only /[_A-Za-z][_0-9A-Za-z]*/.
Is it possible to allow also the dot "." ?

So, before
```
query usersList {hello}
```
after 
```
query users.list {hello}
```
this will allow to generate a documentation like
https://api.slack.com/methods
https://vk.com/dev/methods

**Comment by dimdimych** [comment]
The specification does not allow it
https://facebook.github.io/graphql/June2018/#Name

**Comment by andimarek** [comment]
Hi,

as @dimdimych pointed out this is not allowed according to the spec and we are following the spec in general.

thanks
