### ISSUE TITLE
Add introspecation query to codebase?

### ISSUE THREAD

**Issue by aschrijver** [graphql-java/graphql-java#138]
This issue is related to #132 
Would it be an idea to have the introspection query that is compatible with graphql-java somewhere at hand in the code, like e.g. in https://gist.github.com/aschrijver/c985c48cb0bc3952c3a89b7286f0ee21 ? 

I am not proposing full support for creating a `schema.json` as others have proposed earlier, its just about the correct query to use (though schema creation could be added to the tests).

**Comment by dminkovsky** [comment]
Yeah I think this also should be added to the codebase. If you PR that would probably speed this up. Otherwise I'll get to it too.

**Comment by aschrijver** [comment]
I'll PR this one, thanks!
