### ISSUE TITLE
Generic type Object

### ISSUE THREAD

**Issue by khteh** [graphql-java/graphql-java#1396]
I am trying to port a legacy RESTful api server implementation to GraphQL and there are some controller / service functions which accepts Object as a property of input parameter. I would like to find out how to translate generic type Object to GraphQL schema type? Thanks.

**Comment by bbakerman** [comment]
Have a read of https://www.graphql-java.com/documentation/v11/data-mapping/

In essence on input you will get map objects and on output you can use maps or plain old java objects OR have your own custom data fetcher for a field
