### ISSUE TITLE
Result size validation

### ISSUE THREAD

**Issue by rrva** [graphql-java/graphql-java#1397]
To prevent runaway queries with a too large result size, some interesting research is presented here:

http://blog.liu.se/olafhartig/2018/08/08/lightweight-summary-of-our-paper-semantics-and-complexity-of-graphql/

Especially it contains a technique to reject queries with a too large result set before even executing the query. 

here is a reference implementation:

https://github.com/LiUGraphQL/graphql-result-size

Is any similar work planned for graphql-java? This would be a great feature mitigating some of the issues with runaway queries, where graphql endpoints are exposed without an explicit whitelisting of known good queries.

**Comment by andimarek** [comment]
Unfortunately there is no way in general to calculate the result size of a query before the execution.

the paper and the implementation makes some assumption we can't do:  we don't know what data is actually returned from each `DataFetcher` (Resolver) so we can't calculate the overall size before.

**Comment by andimarek** [comment]
Hi @hartig, I would be interested in the idea. If you wanna have some feedback or help in implementing it, you can reach me at twitter https://twitter.com/andimarek,

**Comment by zcourts** [comment]
We can also help with an implementation as we've already got work planned to implement our own as part of our Q1 roadmap. You can reach me at courtney dot robinson at hypi dot io or twitter/com/zcourts

**Comment by hartig** [comment]
I have followed up via email.

**Comment by andimarek** [comment]
closing this issue because nothing todo atm ... thanks @rrva for bringing it up
