### ISSUE TITLE
Add simple way to disable @defer support

### ISSUE THREAD

**Issue by tbroyer** [graphql-java/graphql-java#1399]
It doesn't appear like there's any (simple) way to disable `@defer` support. `@defer` support when writing a GraphQL server needs special treatment to send the deferred paths to the client, and in the event that this is not put in place in the code that uses GraphQL-Java, it should be possible to (easily) disable `@defer` support at the engine level (by ignoring `@defer` in queries, or failing to validate them).

For now, I can think of only one way to implement this, which is by writing my own instrumentation to either rewrite the `Document` and/or `OperationDefinition` to remove `@defer` in `instrumentExecutionContext`, or to reject `@defer` usage altogether in `beginValidation` (for that case, it might also be possible to make sure the `GraphQLSchema` does not contain the `Directives.DeferDirective`; when using `SchemaGenerator`, this requires duplicating the built schema to remove the directive).

Such instrumentations (or any other way of disabling `@defer`) should IMO be provided _out of the box_ by GraphQL-Java. WDYT?

**Comment by tbroyer** [comment]
FYI, I currently disable `@defer` support using this snippet:
```java
 private static GraphQLSchema removeDeferSupport(GraphQLSchema schema) {
   return GraphQLSchema.newSchema(schema)
       .clearDirectives()
       .additionalDirectives(without(schema.getDirectives(), Directives.DeferDirective))
       .build();
 }

 private static <T> Set<T> without(Collection<T> collection, T withoutValue) {
   return collection.stream().filter(d -> d != withoutValue).collect(toSet());
 }
```
and this causes an error to be returned early (at validation time):
```json
{
  "errors": [
    {
      "message": "Validation error of type UnknownDirective: Unknown directive defer @ 'echo'",
      "locations": [
        {
          "line": 1,
          "column": 27
        }
      ]
    }
  ]
}
```

Better than nothing :wink:

**Comment by bbakerman** [comment]
> yes, I think we should make defer support disabled by default or make it possible to enable it. @bbakerman thoughts?

The reason we have @defer on by default was to make it as widely available as possible.

As @tbroyer pointed out you need to remove iot from the list of standard directives.   We could add a  helper  method to the builder like `builder.removeDirective("directiveName")` to help.

**Comment by jimkyndemeyer** [comment]
I second disabling this by default.

The directive locations and arguments on the built-in `@defer` directive conflicts with the Relay Modern directive: https://github.com/facebook/relay/blob/76fef685f70a5aa09cd180ce0f2ef6b6d3f4f7e8/packages/relay-test-utils/testschema.graphql#L11-L14

An alternative solution would be to let any user schema declared directives take precedence or replace the built-in ones. Right now declaring a Relay defer directive appends it to the end of a linked hash set. The validation always looks up the built-in version as a consequence.

**Comment by bbakerman** [comment]
`@defer` is not longer on by default in master (which will be released in 13.0 at some stage)

**Comment by dinhani** [comment]
Since it is now disabled by default, what is the appropriate way to enable it again?

**Comment by dinhani** [comment]
After finding [this example](https://github.com/graphql-java/graphql-java/blob/0fec4be9fd3974adef781352e0840e3bd01b9401/src/test/groovy/readme/DeferredExamples.java), the following line enabled it again.

`schema.transform(builder -> builder.additionalDirective(Directives.DeferDirective));`
