### ISSUE TITLE
Stale cache data in Data Loaders when executing GraphQL Subscriptions 

### ISSUE THREAD

**Issue by haizz** [graphql-java/graphql-java#1401]
Scenario:

1. Start execution of GraphQL Subscription -> DataLoader gets created.
2. Emit first subscription result -> data written to DataLoader cache.
3. Update data in DB.
4. Emit second subscription result -> DataLoader is still the same, has same old cache from step 2 with invalid old data.

Not sure if this is a bug or missing documentation on how to reset all caches of all DataLoaders between single subscription events. But we are having this issue in production right now causing major confusion. Any workarounds would be very appreciated, thanks!

**Comment by bbakerman** [comment]
There are 2 hard things in computing.

- Naming things
- Cache invalidation
- and off by one errors

If you are using data loader as a cache and you update the backing object, then just like any caching system you must invalidate the cache entry by key.

There is a method for this : `org.dataloader.DataLoader#clear` and one for all keys `org.dataloader.DataLoader#clearAll`.  

You can disable caching in DataLoader via `org.dataloader.DataLoaderOptions#setCachingEnabled`

**Comment by haizz** [comment]
Thanks! Yeah, I actually did put `clearAll` call in the `Subscriber` of `Publisher<ExecutionResult>`:

```kotlin
dataLoaderRegistry.dataLoaders.forEach { dl ->
    dl.clearAll()
}
```

I'm wondering though, shouldn't this cleanup be performed by the library automatically when executing GraphQL Subscriptions?

**Comment by bbakerman** [comment]
> I'm wondering though, shouldn't this cleanup be performed by the library automatically when executing GraphQL Subscription

No because only the specific implementation can know its own caching policies.
