### ISSUE TITLE
Allow providing custom default value for missing key in MappedBatchLoader result

### ISSUE THREAD

**Issue by vojtapol** [graphql-java/graphql-java#1403]
MappedBatchLoader is a great addition to the data loading architecture. Sadly, we can't use it in many cases. Frequently we data load lists like so:

```
type Parent {
  id: String!
  children: [Child!]!  # lazy-loaded via data loader, can not be null
}
```

When data loading `children` the return type of the mapped batch loading function is `Map<String, List<Child>>`. When a key is not present in the map, `DataLoaderHelper::invokeMapBatchLoader` substitutes `null`.  However, in this case outlined above it should instead substitute an empty list.

I propose adding an additional data loader option that would let us set this default value to an arbitrary value. Another solution that might suffice would be the helper first testing whether the `loadResult` is a `Collection` and if so, substituting an empty collection by default.

**Comment by bbakerman** [comment]
Its your batch loading code that is returning the map given the set of keys

    public interface MappedBatchLoader<K, V> {
         CompletionStage<Map<K, V>> load(Set<K> keys);
     }

So if you want empty list values - then put them in in that loader

The problem with a default value is that DataLoaderOptions has not concept of the type `V` that dataloader returns.  I mean we could cast it I guess.




Also this issue would be better over in the https://github.com/graphql-java/java-dataloader/issues project

I made https://github.com/graphql-java/java-dataloader/issues/40 for this

**Comment by bbakerman** [comment]
I am going to close this issue here and follow up in the dataloader project
