### ISSUE TITLE
incompatible version 11.0 to 2019-01-22T01-01-11-41d67d7

### ISSUE THREAD

**Issue by qzucas** [graphql-java/graphql-java#1407]
I use maven which to manage my project.

graphql dependency like this:
    <dependency>
      <groupId>com.graphql-java</groupId>
      <artifactId>graphql-java</artifactId>
      <version>2019-01-22T01-01-11-41d67d7</version>
    </dependency>

before this, I use the version 11.0, my project can run normally.

today, I want to use GraphQLFieldsContainer to write some schemadirectivewiring, so I update the version 2019-01-22T01-01-11-41d67d7, my project cann't run.

Error information here:
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
ERROR 8168 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************
Description:
An attempt was made to call the method graphql.language.OperationTypeDefinition.getType()Lgraphql/language/Type; but it does not exist. Its class, graphql.language.OperationTypeDefinition, is available from the following locations:

    jar:file:/../../../graphql-java/graphql-java/2019-01-22T01-01-11-41d67d7/graphql-java-2019-01-22T01-01-11-41d67d7.jar!/graphql/language/OperationTypeDefinition.class

It was loaded from the following location:
    file:/E:/maven/repository/com/graphql-java/graphql-java/2019-01-22T01-01-11-41d67d7/graphql-java-2019-01-22T01-01-11-41d67d7.jar

Action:

Correct the classpath of your application so that it contains a single, compatible version of graphql.language.OperationTypeDefinition

who can help me resolve the question of incompatible version?

**Comment by qzucas** [comment]
in version 11.0
 the OperationTypeDefinition's code is:
private final Type type;

    @Internal
    protected OperationTypeDefinition(String name, Type type, SourceLocation sourceLocation, List<Comment> comments) {
        super(sourceLocation, comments);
        this.name = name;
        this.type = type;
    }
public Type getType() {
        return type;
    }

but in version 2019-01-22T01-01-11-41d67d7, the code is 
private final TypeName typeName;

    public static final String CHILD_TYPE_NAME = "typeName";

    @Internal
    protected OperationTypeDefinition(String name, TypeName typeName, SourceLocation sourceLocation, List<Comment> comments, IgnoredChars ignoredChars) {
        super(sourceLocation, comments, ignoredChars);
        this.name = name;
        this.typeName = typeName;
    }

    public TypeName getTypeName() {
        return typeName;
    }

in version 2019-01-22T01-01-11-41d67d7

i don't find where use this OperationTypeDefinition.getType()

**Comment by andimarek** [comment]
@qzucas that is correct: 11.0 is the latest release. all the versions with a date and hash in it are development builds. 

So please be aware that you trying out an unreleased version. Is that what you wanted?

**Comment by qzucas** [comment]
@andimarek thanks for your reply.  
I know the version is unreleased. It's normally that the daily version goes wrong. But I want to use the new function of new version about directives in my project.
When will be the version 12.0  released?  I look forward to that this problem will be solved soon and 12.0 will be released.
thank you

**Comment by andimarek** [comment]
@qzucas I am sorry, I can't give you a release date for 12.0 at the moment.

**Comment by thorntonrp** [comment]
I created issue https://github.com/graphql-java/graphql-java/issues/1439 which describes how the development build versions are creating confusion about release versions.

**Comment by andimarek** [comment]
@qzucas version 12.0 is now released

**Comment by qzucas** [comment]
@andimarek thank you very much. I have used version 12.0 and very well.
