### ISSUE TITLE
How to find out the root cause of "Invalid schema provided"?

### ISSUE THREAD

**Issue by khteh** [graphql-java/graphql-java#1414]
How to find out the root cause of "Invalid schema provided"? I have many *.graphqls. Some of them just have data type IDL without any query and mutation definition.

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'schemaParser' defined in class path resource [com/oembedler/moon/graphql/boot/GraphQLJavaToolsAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.coxautodev.graphql.tools.SchemaParser]: Factory method 'schemaParser' threw exception; nested exception is com.coxautodev.graphql.tools.InvalidSchemaError: Invalid schema provided (org.antlr.v4.runtime.InputMismatchException) at: [@313,1904:1904='[',<11>,120:12]

**Comment by bbakerman** [comment]
You will want to ask in the https://github.com/graphql-java-kickstart/graphql-java-tools project.

InputMismatchException usually means you are missing a token (eg opening and closing braces)

But how graphql-tools is combining files I have no insight on... hence ask there

**Comment by andimarek** [comment]
closing it because it concerns another project
