### ISSUE TITLE
Logging sensitive data

### ISSUE THREAD

**Issue by chih-chen** [graphql-java/graphql-java#1417]
Hi guys! 

I'm having problems with logs. I have some sensitive data that I can't log, but they are logged at [this](https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/GraphQL.java#L594) place when the execution fails. I saw some people asking for logs, so I don't know how to handle this issue. Is it possible to not log the variables? 

Thanks a lot!

**Comment by bbakerman** [comment]
private static final Logger log = LoggerFactory.getLogger(GraphQL.class);

Just turn off logging for `graphql.GraphQL` in your logging config

**Comment by chih-chen** [comment]
@bbakerman Thanks for point out this solution, I really forgot about it.
