### ISSUE TITLE
Possible to override build-in scalar coercion

### ISSUE THREAD

**Issue by arlampin** [graphql-java/graphql-java#1420]
Is it possible to override type coercion for build-in GraphQL types? 

Our use case is that we internally use for example Java's OffsetDateTime as return value, but need to customize its serialized format. In GraphQL schema these fields are represented as GraphQL Strings. We would like to avoid creating a custom Scalar type just for this purpose, and the plain `toString()` as used by `Scalars.GraphQLString` is not valid for our purposes.

In practice we would like to override the GraphQLString's Coercing impl. with one that checks the argument type.

**Comment by bbakerman** [comment]
There is no way to override the standard Scalars.  The whole point of standard scalars is standard naming and behavior

You want "date time" behavior but you don't want a "DateTime" scalar?  I think you are doing it wrong.

For example I am sure you have a mix of real "String" fields and "DataTime String" fields so how would you know which was which?  Who would a caller know other than by field naming convention?  eg `thisIsADateTime : String` is the only way to know that its not a String but a"DataTime String"?


I urge you to consider using https://github.com/graphql-java/graphql-java-extended-scalars and custom scalars.

**Comment by arlampin** [comment]
OffsetDateTime was just a single example, there are plenty of other use cases where one might want to overwrite serialization without creating a distinct scalar. `Object.toString()`'s method contract doesn't require it to return particularly usable output, it's meant as development and debugging aid.

This isn't limited to GraphQL String type either. For example, we have a class `ID<T>` mapping to GraphQL ID type in the schema. `toString` returns e.g. `Project:123` for debugging purposes, but in GraphQL output that value is base64 encoded using custom DataFetcher.

**Comment by bbakerman** [comment]
You cant override the standard scalars and I dont think we would ever allow it.

DataFetchers per field are the "code callback" that are injectable.  They are the standard way to change result objects.

If the higher level objects you return cant be made into Strings easily then you need to so that it in the top level data fetcher OR put a data fetcher onto your String fields and have them create the String object from the appropriate place

```
     query {
            topLevel {                      # data fetcher gets specialField into String shape
                    specialField           # or a specific data fetcher here that knows how to get it in to String shape

```

Have a look at `graphql.schema.idl.WiringFactory` that will allow you to KNOW what fields you are retriveving and hence put special data fetchers in place

**Comment by bbakerman** [comment]
I am going to close this issue because we will not allow scalar co-ercing overrides

**Comment by timzaak** [comment]
If build-in scalar can be override, then this is may more easily  ported for other jvm languages, like Scala. 
Optional=>Scala Option
List => scala Seq
and so on.
