### ISSUE TITLE
Add support for customising the shape of the error response from a GraphQLError

### ISSUE THREAD

**Issue by bmorganatlas** [graphql-java/graphql-java#1426]
This bug was logged after some discussion in https://spectrum.chat/graphql-java/general/add-the-ability-to-more-deeply-customise-the-error-fields-produced~61e9549e-cc88-474d-a460-5cf1f448f5e8

I'm using graphql-java 11 and what I want to be able to produce is an error block with additional top level field called 'statusCode' in addition to the standard error shape, it would look like this:
```
  "errors": [
    {
      "message": "Name for character with ID 1002 could not be fetched.",
      "statusCode": 404,
      "locations": [ { "line": 6, "column": 7 } ],
      "path": [ "hero", "heroFriends", 1, "name" ]
    }
  ],
```
The current extension handling comes out in the extensions object, something like this:
```
  "errors": [
    {
      "message": "Name for character with ID 1002 could not be fetched.",
      "extensions": {
        "status": "400",
        "foo": "bah"
      }
      "locations": [ { "line": 6, "column": 7 } ],
      "path": [ "hero", "heroFriends", 1, "name" ]
    }
  ],
```
I thought I could work around this by overriding `GraphQLError#toSpecification` to produce the output in the shape I want but this gets wrapped in a `AbsoluteGraphQLError` in `graphql.execution.ExecutionStrategy#unboxPossibleDataFetcherResult` and effectively overwritten:
```
    Object unboxPossibleDataFetcherResult(ExecutionContext executionContext,
                                          ExecutionStrategyParameters parameters,
                                          Object result) {
        if (result instanceof DataFetcherResult) {
            //noinspection unchecked
            DataFetcherResult<?> dataFetcherResult = (DataFetcherResult) result;
            dataFetcherResult.getErrors().stream()
                    .map(relError -> new AbsoluteGraphQLError(parameters, relError))
                    .forEach(executionContext::addError);
            return dataFetcherResult.getData();
        } else {
            return result;
        }
    }
```
I note that in master this has been reworked to handle 'relative' errors so it won't wrap in certain cases based on a flag in the `DataFetcherResult` but this doesn't seem like the right solution for this case.

I could a few potential ways to tackle this:

**Spread the values from `extensions` onto the root of the generated specification.** 
This seems undesirable because it would break the current api contract. We would also need to resolve potential for conflicts between the fields, i.e. what do we do when someone has an extension field `message`

**Use reflection / a flag to determine is `toSpecification` has been overridden and use it if it is defined**
We could use reflection or a new boolean `implementsSpecification` to determine if the `toSpecification` is provided by the implementor and if so wrap the existing `GraphQLError` and delegate `toSpecification` calls to it when unboxing.
This seems like an ugly solution , if we use a flag we bloat the interface if we use reflection it would be an ugly solution.

Perhaps there is another approach that we could take that I haven't seen.

**Comment by bbakerman** [comment]
According to the graphql spec

https://facebook.github.io/graphql/June2018/#sec-Errors

> GraphQL services may provide an additional entry to errors with key extensions. This entry, if set, must have a map as its value. This entry is reserved for implementors to add additional information to errors however they see fit, and there are no additional restrictions on its contents.

```
{
  "errors": [
    {
      "message": "Name for character with ID 1002 could not be fetched.",
      "locations": [ { "line": 6, "column": 7 } ],
      "path": [ "hero", "heroFriends", 1, "name" ],
      "extensions": {
        "code": "CAN_NOT_FETCH_BY_ID",
        "timestamp": "Fri Feb 9 14:33:09 UTC 2018"
      }
    }
  ]
}
```

It then says how it failed to mention that top level fields are not allowed.  Since they failed at that they now discourage it not ban it

> GraphQL services should not provide any additional entries to the error format since they could conflict with additional entries that may be added in future versions of this specification.

> Note : Previous versions of this spec did not describe the extensions entry for error formatting. While non‐specified entries are not violations, they are still discouraged.

```
{
  "errors": [
    {
      "message": "Name for character with ID 1002 could not be fetched.",
      "locations": [ { "line": 6, "column": 7 } ],
      "path": [ "hero", "heroFriends", 1, "name" ],
      "code": "CAN_NOT_FETCH_BY_ID",
      "timestamp": "Fri Feb 9 14:33:09 UTC 2018"
    }
  ]
}
```

As such I think graphql-java will follow that advice and allow "extensions" fields in errors.   We already do this

So now that the AbsoluteGraphqlError bug is fixed (by default) you can place "extended errors" into the extensions area and it will be carried over during a `toSpecification` call

If you absolutely MUST have a top level field then you are requires to write your own "error post processing" code yourself (a bit like toSpecification but with your own attribute understanding) before you put the ExecutionResult into a JSON stack


(On a side note - we recognize that the AbsoluteGraphqlError pattern is kinda broken - we don't recommend that any one use it.   We turned it off by default in graphql java 12 but for backwards compatibility reasons we did not remove it.  We may remove it in the future)

**Comment by bbakerman** [comment]
See #1495 for ever more options on customising the error output (in terms of error classification)

**Comment by bbakerman** [comment]
I am going to close this as we believe "extensions" is the way to extend graphql errors since its spec compliant
