### ISSUE TITLE
JAR dependencies

### ISSUE THREAD

**Issue by snandesh** [graphql-java/graphql-java#1430]
Can anyone list the jar dependencies for this project?
I only got antlr4-runtime. Need all of them.

**Comment by andimarek** [comment]
you can see the dependencies in the build gradle file: https://github.com/graphql-java/graphql-java/blob/master/build.gradle#L52 

Right now we have:
```
  compile 'org.antlr:antlr4-runtime:4.7.2'
    compile 'org.slf4j:slf4j-api:' + slf4jVersion
    compile 'com.graphql-java:java-dataloader:2.1.1'
    compile 'org.reactivestreams:reactive-streams:' + reactiveStreamsVersion
    antlr "org.antlr:antlr4:4.7.2"
```
