### ISSUE TITLE
Change order of fields inside Response

### ISSUE THREAD

**Issue by Sparow199** [graphql-java/graphql-java#1432]
Previous editions suggested that a data property be contained in a result before errors, however this has been reversed for easier human debugging.

[Facebook GraphQL merged PR](https://github.com/facebook/graphql/pull/384)

**Comment by bbakerman** [comment]
Yeah - fair enough.  

We could change this in the ExecutionResult object.

Of course the JSON production might not respect that but the Java API could try to follow the guidance
