### ISSUE TITLE
Support printing directives in the output

### ISSUE THREAD

**Issue by smyrick** [graphql-java/graphql-java#1434]
**Describe the bug**
Directives are not part of the SDL from the schema printer. According to the GraphQL spec we should have a string like so: https://facebook.github.io/graphql/draft/#sec-Type-System.Directives

This will allow us to parse the schema with other libraries that require it be present

```graphql
directive @example on FIELD
```

**To Reproduce**
```groovy
    def simpleIdlWithDirective() {
        return """
            directive @example on FIELD_DEFINITION
            
            type Query {
                fieldA : String @example
            }
        """
    }

    def "directives are printed as top level types when the includeDirectives flag is set"() {
        given:
        def registry = new SchemaParser().parse(simpleIdlWithDirective())
        def runtimeWiring = newRuntimeWiring().build()
        def options = SchemaGenerator.Options.defaultOptions().enforceSchemaDirectives(true)
        def schema = new SchemaGenerator().makeExecutableSchema(options, registry, runtimeWiring)

        when:
        def resultWithNoDirectives = new SchemaPrinter(defaultOptions().includeDirectives(false)).print(schema)

        then:
        resultWithNoDirectives == '''type Query {
  fieldA : String
}
'''

        when:
        def resultWithDirectives = new SchemaPrinter(defaultOptions().includeDirectives(true)).print(schema)

        then:
        resultWithDirectives == '''directive @example on FIELD_DEFINITION
            
type Query {
  fieldA : String @example
}
'''
    }
```

**Comment by bbakerman** [comment]
Thanks for reporting this.  The printing of directive definitions was completely missed in the SchemaPrinter

**Comment by lancethomps** [comment]
any chance this can be released as v12.1?

**Comment by bbakerman** [comment]
On my phone.. So un checked answer...

But I thought there is a print option that includes directives


It might not be on by default


As for 12.1.... The stable branch is 9.x.  It would be in 13.0 or 9.x

**Comment by lancethomps** [comment]
There is, but as this issue mentions, it does not actually print the directive definition itself (only the directive annotation on some portion of the schema).

I've gone through the upgrade to 12.0 so I definitely do not want to go back to 9.x because of a bug in 12.0 - what is the problem with releasing a 12.x version?

**Comment by dkuc84** [comment]
@bbakerman - just wondering any reason why you are filtering out the common directives (i.e. `skip`,
`include`, `defer` and `deprecated`)?
