### ISSUE TITLE
Newline character followed by single character followed by a space

### ISSUE THREAD

**Issue by jschwartz73** [graphql-java/graphql-java#1438]
GraphQL Java v11.0

**Describe the bug**
I found an issue with multiline text in a mutation.  Whenever there is a multiline text using the \n character, followed by a single standard character, followed by a space, the resulting data parsed is missing the single standard character.

For example: 
```
"""Line 1\n2 Line number\nThird line"""
```

will parse as:
```
Line 1
 Line number
Third line
```

I followed the code through the debugger, and I believe the error is in this line:

`graphql.parser.Parser`
Line  48: 
`Document doc = antlrToLanguage.createDocument(documentContext)`

I do not understand ANTLR enough to troubleshoot past this point.

**To Reproduce**
```
mutation{upsertDoc(multilineField: """Line 1\n2 Line number\nThird line"""){multilineField}}
```

Results 
```
Line 1
 Line number
Third line
```
I found a workaround which is to use `\r` instead of `\n`.

Any help would be greatly appreciated

**Comment by bbakerman** [comment]
Thanks for reporting this.  We will look into it.

**Comment by bbakerman** [comment]
I was able to reproduce this bug

In groovy format like this

```
    def "1438 - slash-n is incorrectly parsed"() {
        given:
        def input = '''
            mutation{fld(arg: """L1\nL 2\nL 3"""){innerField}}
        '''
        when:
        Document document = new Parser().parseDocument(input)
        Field firstField = (document.definitions[0] as OperationDefinition).selectionSet.selections[0] as Field
        def argumentValue = firstField.getArguments().get(0).getValue()

        then:
        argumentValue instanceof StringValue
        def value = ((StringValue) argumentValue).value
        value == 'L1\nl 2\nL 3'
    }
```
It does seem to be something to do with \n pairing of some sort because the string '''L1\nl 2\nL3` actually works as expected.

Anyway I will try to get to the bottom of what is happening here.

**Comment by bbakerman** [comment]
Hmm it looks like the code problem is in `graphql.parser.StringValueParsing#removeIndentation`
and how it tries to follow the graphqlspec on how to indent multiline triple quoted strings

https://github.com/facebook/graphql/pull/327/files#diff-fe406b08746616e2f5f00909488cce66R758

We will need to review this code

**Comment by bbakerman** [comment]
Thanks for reporting this

This has been fixed and now follows the graphql spec on triple quote indenting more thoroughly

**Comment by jschwartz73** [comment]
Thank you!
