### ISSUE TITLE
Development builds create wrong release version in maven-metadata.xml

### ISSUE THREAD

**Issue by thorntonrp** [graphql-java/graphql-java#1439]
Many tools, including command-line maven and http://search.maven.org, query the maven-metadata.xml file to determine the latest release version. My organization uses an automated process as part of our build to query maven-metadata.xml to update our managed dependency versions. However, the graphql-java daily development builds break Maven release semantics for maven-metadata.xml. See http://repo1.maven.org/maven2/com/graphql-java/graphql-java/maven-metadata.xml

```xml
<metadata>
  <groupId>com.graphql-java</groupId>
  <artifactId>graphql-java</artifactId>
  <versioning>
    <latest>2019-02-28T01-17-35-b2cc1c2</latest>
    <release>2019-02-28T01-17-35-b2cc1c2</release>
    ...
  </versioning>
</metadata>
```

Please note that the `<release>` value is not accurate. This makes it very difficult for us to determine in any automated fashion when a new release is available.

**Comment by andimarek** [comment]
I am sorry that this approach doesn't work for your automatic tooling, but we decided to publish the dev versions via maven (as "real" releases) to make them as accessible as possible and to allow people  to depend on them if they really want.

I recommend you follow us on [twitter](https://twitter.com/graphql_java) or [spectrum](https://spectrum.chat/graphql-java) or use the [Github Notifications for releases](https://help.github.com/en/articles/watching-and-unwatching-releases-for-a-repository)
