### ISSUE TITLE
'skip' and 'include' directives no longer supported on fragment definitons (April 2016 spec)

### ISSUE THREAD

**Issue by aschrijver** [graphql-java/graphql-java#144]
With the recent support for `directive.locations` (see #136 ) the project _almost_ complies [to latest graphql spec of April 2016](https://github.com/facebook/graphql/releases/tag/April2016).

But skip and include directives are no longer supported on fragment definitions. See: https://github.com/facebook/graphql/commit/1c38e6ac16de82a2a28487c8f193d673e39a1e33

However changing these would break backwards-compatibility (decision).
See: https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/Directives.java

Note, there may be more incompatibilities with latest spec, but this is the only remaining change that is breaking.

**Comment by danielkwinsor** [comment]
This will be addressed in #148

**Comment by aschrijver** [comment]
#148 merged. Closing
