### ISSUE TITLE
Problems in relay.connectionType

### ISSUE THREAD

**Issue by jadedevin13** [graphql-java/graphql-java#1441]
**Describe the bug**
Using relay.connectionType(.. in more than one edge causes _No provided type may have a name which conflicts with any built in types (including Scalar and Introspection types). You have redefined the type 'PageInfo' from being a 'GraphQLObjectType' to a 'GraphQLObjectType'_

Since the connection type is not using a GraphQLTypeReference, it's creating a new PageInfoType when it tries to traverse the schema.

**Comment by kaqqao** [comment]
This is a breaking change, so it really should have been documented with the release...
