### ISSUE TITLE
For completely invalid schema's as well, it takes too much time to report the error

### ISSUE THREAD

**Issue by josh00007777** [graphql-java/graphql-java#1444]
I am parsing a graphql schema like this -

TypeDefinitionRegistry typeDefinitionRegistry typeDefinitionRegistry = new SchemaParser().parse(graphQLSchemaString);

In my case the schema file is selected in UI, and the server gets the content of the file. Now if user select a completely invalid file (like pdf) and if the file is too big(suppose 2gb), then the whole system hangs.

It is not only PDF or other formats, if a big text file with invalid content is selected then also this issue happens.

The expectation is that if the 'graphQLSchemaString' is completely invalid or as soon as we find the first invalid syntax, further parsing should be aborted.

**To Reproduce**
To reproduce this issue I am using a big PDF file, I am reading the PDF file and then the content is passed to SchemaParser.

TypeDefinitionRegistry typeDefinitionRegistry typeDefinitionRegistry = new SchemaParser().parse(graphQLSchemaString);

I am using 9.4 version of graphql java.

**Comment by andimarek** [comment]
can you share what you mean with too long?

**Comment by bbakerman** [comment]
We will not be fixing this in the base graphql-java.  

This use case (internet submitted schemas) deserves it own custom "sensibility check code" to be done by your application.

We make an assumption that the schemas provided are graphql schemas and may have a few problems.  

We don't optimise for detection of  binary data.  If we did, it would be code we would have to maintain over time and it would not be used by 95% of all library consumers.

I urge you to develop your own "sanity code" before you submit it to the schema parser.

**Comment by josh00007777** [comment]
Ok, Thanks for explaining. I am closing the issue.
