### ISSUE TITLE
No validation error for invalid schema

### ISSUE THREAD

**Issue by josh00007777** [graphql-java/graphql-java#1447]
**Describe the bug**
I am using this schema:

type Query {
  allUsers: [User!]!
}

type User {
  name: String!
  age: Int!
}
{
  allUsers {
    . addressDetails
  }
}

fragment addressDetails on User {
  name
  street
  zipcode
  city
}

You can see that there is some text in this which is invalid (fragment section) but still I am able to import it(i.e. Schema parser doesnt throw any error).

**To Reproduce**
Use the above schema and parse it like this:

new SchemaParser().parse(graphQLSchemaString);

no errors on parsing.

Using 9.4 version

**Comment by bbakerman** [comment]
Interesting .. I know why this is happening.  The graphql Document is inclusive of "query" aspects and "sdl type definition" aspects

https://facebook.github.io/graphql/June2018/#sec-Appendix-Grammar-Summary.Document

So the SchemaParser is parsing all of the Document but then only collects the known "SDL" types

So the underlying document parser is correct - however we can argue that `SchemaParser` should only accept "SDL related" elements

**Comment by bbakerman** [comment]
This is now fixed on master.

It with report an error if non SDL elements are present
