### ISSUE TITLE
Getting error for valid Double value

### ISSUE THREAD

**Issue by josh00007777** [graphql-java/graphql-java#1448]
**Describe the bug**
For below schema --

type Employee {
    sal: Float   
}
type Query {
   getEmployee(sal:Float): Employee
}

When this query is passed, Invalid Syntax error is raised --

{
  getEmployee (sal:1.7976931348155E+308){
    sal
  }
}

If I remove + from "sal" value then it is working, as per java 1.7976931348155E+308 is valid double value.

**Comment by andimarek** [comment]
merged the PR ... thanks
