### ISSUE TITLE
[Feature Request] Support for @stream directive

### ISSUE THREAD

**Issue by jadedevin13** [graphql-java/graphql-java#1453]
Relay supports [@stream](https://github.com/facebook/relay/blob/76fef685f70a5aa09cd180ce0f2ef6b6d3f4f7e8/packages/relay-test-utils/testschema.graphql#L16) directive

**Comment by bbakerman** [comment]
What does it do?  You can put it in a query field but then what happens?

We would need a much better explanation to consider it.  We would also like to see other possible implementations (for interoperability of clients - eg a web client could have the same behavior on graphql-java as it could on some other engine say)

**Comment by jadedevin13** [comment]
I understand. It's in [apollo server's roadpmap](https://github.com/apollographql/apollo-server/blob/4fe53f3c127d488044addd2dffea1ff3c4e145cd/ROADMAP.md#support-for-defer-live-and-stream). 

> `@stream` is similar to `@defer`, except that processing can continue right away, and the streamed part of the result can begin sending right away.

Closing this for now.
