### ISSUE TITLE
Internationalization of graphql-java error messages

### ISSUE THREAD

**Issue by gh157006136** [graphql-java/graphql-java#1465]
Is there an error message corresponding to the Chinese version?

**Comment by bbakerman** [comment]
We dont have i18n messages in graphql - which is a pity to be honest

**Comment by bbakerman** [comment]
See #1473

**Comment by dondonz** [comment]
To resurrect an old thread, i18n error messages are almost done!

Validation error messages have been added, with parser and coercing messages awaiting review https://github.com/graphql-java/graphql-java/pull/2921 https://github.com/graphql-java/graphql-java/pull/2912

We'd love to include more languages, especially 中文! Please help us by opening a PR
