### ISSUE TITLE
Optional Query Validation

### ISSUE THREAD

**Issue by MdSarfarazKhan** [graphql-java/graphql-java#1479]
We have a very high latency system with a large schema and queries. I'm building  a query registration system ,so in short on production only pre registered query will run . Thus guaranteeing all the queries are validated earlier.
So I would like to skip the query validation on production to save some Milli sec. On some other framework(Sangria- scala lib) I found it very easy to skip it but in java it seems it's mandatory.

`
graphql.GraphQL#parseAndValidate
graphql.GraphQL#validate
graphql.validation.Validator
`

Is there any way we can skip the validation?

**Comment by MdSarfarazKhan** [comment]
I have created a pull request with the solution
 https://github.com/graphql-java/graphql-java/pull/1480

**Comment by bbakerman** [comment]
>  I'm building a query registration system ,so in short on production only pre registered query will run .

Check out `graphql.execution.preparsed.PreparsedDocumentProvider` which given query text you can give back a Document.  There is a function you can call given to you that does the standard parse and validate

You could use the `Parser` to get a document say and not call the function and hence skip vaildation

Or you could parse and validate the first time and then "cache" the result for all subsequent requests and hence amortize that over all the requests.  (One time penalty)
