### ISSUE TITLE
Create Schema Definition from Introspection Result is ignoring Custom Scalar from Server

### ISSUE THREAD

**Issue by soniachan** [graphql-java/graphql-java#1481]
Hi guys,

I am trying to use graphql-java to send graphql queries to prisma graphql server. However, it fails to create GraphQLSchema with the introspection results from prisma grpahql server due to the 'DateTime'

**Introspection**
```
query IntrospectionQuery {
  __schema {
    queryType {
      name
    }
    mutationType {
      name
    }
    subscriptionType {
      name
    }
    types {
      ...FullType
    }
    directives {
      name
      description
      locations
      args {
        ...InputValue
      }
    }
  }
}

fragment FullType on __Type {
  kind
  name
  description
  fields(includeDeprecated: true) {
    name
    description
    args {
      ...InputValue
    }
    type {
      ...TypeRef
    }
    isDeprecated
    deprecationReason
  }
  inputFields {
    ...InputValue
  }
  interfaces {
    ...TypeRef
  }
  enumValues(includeDeprecated: true) {
    name
    description
    isDeprecated
    deprecationReason
  }
  possibleTypes {
    ...TypeRef
  }
}

fragment InputValue on __InputValue {
  name
  description
  type {
    ...TypeRef
  }
  defaultValue
}

fragment TypeRef on __Type {
  kind
  name
  ofType {
    kind
    name
    ofType {
      kind
      name
      ofType {
        kind
        name
        ofType {
          kind
          name
          ofType {
            kind
            name
            ofType {
              kind
              name
              ofType {
                kind
                name
              }
            }
          }
        }
      }
    }
  }
}

```

**Introspection Result**
```
{
  "data": {
    "__schema": {
      "queryType": {
        "name": "Query"
      },
      "mutationType": {
        "name": "Mutation"
      },
      "subscriptionType": {
        "name": "Subscription"
      },
      "types": [
        {
          "kind": "SCALAR",
          "name": "DateTime",
          "description": "",
          "fields": null,
          "inputFields": null,
          "interfaces": null,
          "enumValues": null,
          "possibleTypes": null
        },
        ...
      ],
      "directives": [
        ...
      ]
    }
  }
}
```

**Create Schema Definition from Introspection Result**
``` 
Document schema = new IntrospectionResultToSchema().createSchemaDefinition((Map<String, Object>) introspectionResult.get("data"));
String printedSchema = new SchemaPrinter().print(schema);
Reader schemaProvider = new StringReader(printedSchema);
SchemaParser parser = new SchemaParser();
SchemaGenerator schemaGenerator = new SchemaGenerator();
TypeDefinitionRegistry typeRegistry = parser.parse(schemaProvider);
GraphQLSchema schema = schemaGenerator.makeExecutableSchema(typeRegistry, RuntimeWiring.newRuntimeWiring().build());
```

**Error** 

> The input value type 'DateTime' is not present when resolving type 'UserWhereInput' [@1107:1], There is no type resolver defined for interface / union 'Node' type

Does anyone have any idea or tries to implement this?

**Comment by soniachan** [comment]
Also tried adding DateTime as custom scalar field but it is throwing the same error
Reference: https://github.com/howtographql/graphql-java/blob/master/src/main/java/com/howtographql/hackernews/Scalars.java

**Comment by bbakerman** [comment]
Sounds like a possible big in the IntrospectionResultToSchema() code.

Would you be able to supply a simplified test case we can help to track this down with.  For example the full Json for the schema or a simplied test case

**Comment by yshrsmz** [comment]
Hi, I've encountered the same error with GitHub's API.

Here's a schema.json file and introspection query.
https://gist.github.com/yshrsmz/d7de070f3bb5202aea73de89708bdc8d

For DateTime Scalar I used [graphql-java/graphql-java-extended-scalars](https://github.com/graphql-java/graphql-java-extended-scalars)

**Comment by mbell-gresham** [comment]
Also looking in to this, wondering if its related to the fact that:

`new SchemaPrinter().print(schema)`

calls `UnExecutableSchemaGenerator.makeUnExecutableSchema(registry)`

**Comment by complanboy2** [comment]
Observation is thatthe SchemaPrinter misses the custom type information from the SDL it generates. 
And also the empty type information it generate is not accepted by the parser. It may fill in a void information for empty types, so that parser will have no issues.

**Comment by kotrao** [comment]
Is this problem solved? I am having similar issue with JSON custom scalar type. Can you please share how you solved it?

**Comment by IceBlizz6** [comment]
Suspect that i'm having the same problem.
GraphQL introspection query gives information about scalar types.
But SchemaPrinter().print(GraphQLSchema) output does not give any scalars.
Even though it references Long and LocalDateTime types, they have no "scalar Long" definition.

**Comment by IceBlizz6** [comment]
Nevermind, figured out the solution.
SchemaPrinter(SchemaPrinter.Options.defaultOptions().includeScalarTypes(true))
Looks like SchemaPrinter does not print custom scalars by default.
