### ISSUE TITLE
Version 12 not available in Maven repo

### ISSUE THREAD

**Issue by zenios** [graphql-java/graphql-java#1484]
Maven repos last stable version is v11 after from there on only daily releases with the date appended to the name

![Screenshot from 2019-04-02 08-56-37](https://user-images.githubusercontent.com/89569/55379310-546b9b80-5525-11e9-88f0-98f825e187b2.png)

**Comment by andimarek** [comment]
not sure about this specific view, but version 12.0 is available: https://repo1.maven.org/maven2/com/graphql-java/graphql-java/12.0/

**Comment by andimarek** [comment]
See also: https://mvnrepository.com/artifact/com.graphql-java/graphql-java/12.0
