### ISSUE TITLE
BatchedExecutionStrategy returns fields in arbitrary order

### ISSUE THREAD

**Issue by arlampin** [graphql-java/graphql-java#150]
It seems BatchedExecutionStrategy uses Java HashMap internally, and as such field ordering is not consistent.

The problem happens in [graphql.execution.batched.GraphQLExecutionResultContainer](https://github.com/graphql-java/graphql-java/blob/5803af910e408d7cc106960be8fccf55b27df66b/src/main/java/graphql/execution/batched/GraphQLExecutionResultContainer.java#L17) line 17. I believe this is a mistake and it should instead use LinkedHashMap, as other parts of graphql-java do.

**Comment by andimarek** [comment]
Hi,

maybe you can create a PR for that change? That would be great.

Thanks

**Comment by arlampin** [comment]
Sure. Created #151 that fixes the issue.

**Comment by arlampin** [comment]
#151 was merged, closing
