### ISSUE TITLE
Make a LTS statement about 9.x in our read me and doc site

### ISSUE THREAD

**Issue by bbakerman** [graphql-java/graphql-java#1501]
Reminder to ourselves to put a note about 9.x being the current LTS support version

**Comment by Archcry** [comment]
I think the fact that graphql 9 is a LTS release is pretty clear when reading the [article](https://www.graphql-java.com/blog/breaking-changes-and-lts/). What I would like to know is what the period for support for this LTS is. The community was asked about this last october but since then there has been no official statement on the period of support on graphql 9 LTS. Would be nice to still get this.

**Comment by Archcry** [comment]
An official statement about this would be nice.

**Comment by andimarek** [comment]
@Archcry I will quote @bbakerman here:

We cant give you a definitive date on how long the 9.x LTS will be there. The backing project is not a company, its a group of individuals and hence given a proper LTS commitment with dates is a big ask.

We can only give you more vague indications.

9.x came out in June 2018 and at a vague guess I think it would likely still be LTS support in June 2019.

Taken from spectrum: https://spectrum.chat/graphql-java/general/9-x-is-our-current-lts-version-how-often-are-you-updating~196ab67d-2770-4f3f-b1b3-b056ecb3a2e1

**Comment by Archcry** [comment]
So it's not a LTS?

**Comment by andimarek** [comment]
@Archcry it is a LTS because we back port bugfixes to 9.x, while we don't do it to 10,11, ... We just can't tell you exactly how long we continue do do it as @bbakerman explained.

**Comment by Archcry** [comment]
Well, June 2019 isn't to far away, that's next month. So if the vague guess is anything to go by we now have about a month or so to upgrade to version 12. That's what I call suddenly. I mean no disrespect but the current definition used for LTS doesn't feel like something people using Graphql can rely on.

**Comment by andimarek** [comment]
As @bbakerman explained: this open source project is not run by a company. We are doing our best with the time and resources we have at our disposal. I understand that a more definite statement would be better, but we don't want to promise anything we can't uphold.

**Comment by Archcry** [comment]
I understand, I do think it would be a good idea to think about the value you're actually adding by having a LTS release though. I do understand that you are maintaining the project in your free time and that making commitments isn't desirable but being vague about a LTS period isn't going to help either. Perhaps it would be better not to have a LTS release at all if you cannot make the commitment on a certain period.
