### ISSUE TITLE
SchemaDiff inner class Options methods have confusing signatures

### ISSUE THREAD

**Issue by grrttedwards** [graphql-java/graphql-java#1502]
Version `11.0`

The `SchemaDiff.Options` inner class does not provide an obvious way to enable the `enforceDirectives` flag. The full definition:
```
    /**
     * Options for controlling the diffing process
     */
    public static class Options {

        final boolean enforceDirectives;

        Options(boolean enforceDirectives) {
            this.enforceDirectives = enforceDirectives;
        }

        public Options enforceDirectives() {
            return new Options(true);
        }

        public static Options defaultOptions() {
            return new Options(false);
        }

    }
```

The only way to create an instance of `Options` with the flag enabled is to chain the calls `Options.defaultOptions().enforceDirectives()`, which is rather confusing. This whole class seems to have a strange design, with one protected constructor, one public method, and one public static method.

**Comment by bbakerman** [comment]
> `Options.defaultOptions().enforceDirectives()`, which is rather confusing. 

So the alternative is a builder pattern like

`Options.newOptions().enforceDirectives().build()`

It looks a lot like what we have.  I will take this as a comment on code style rather than a bug or design problem

**Comment by lwilli** [comment]
I also was confused on how to get an `Options` with `enforceDirectives = true` until I stumbled across this issue.
