### ISSUE TITLE
Keep DataFetcher support

### ISSUE THREAD

**Issue by siderakis** [graphql-java/graphql-java#1505]
Can we keep DataFetcher on GraphQLFieldDefinition?

Is there a solid reason to migrate away from this pattern?

Rejoiner.io makes heavy use of DataFetcher are we don’t see a easy/intuitive path for migrating away from it.

**Comment by bbakerman** [comment]
The main design reason we are moving to GraphqlCodeRegistry is it allows us to have "comparable" type objects eg. `someObjectType.equals(someOtherObjectType)`

Also separating the definition of a field and how your fetch it at runtime allows for better design in our opinion.

> Rejoiner.io makes heavy use of DataFetcher are we don’t see a easy/intuitive path for migrating away from it.

Can you tell us more on what you MUST hang everything off `GraphQLFieldDefinition`?  

I would have thought that as you generate "generate field definitions" from java code you can place to generated DataFetcher into code registry at the same time?

**Comment by siderakis** [comment]
An issue we faced when looking at using GraphqlCodeRegistry was trying to merge multiple GraphqlCodeRegistry instances.  As a workaround we'll keep a list of DataFetchers and their metadata in a custom wrapper object and add them to a single GraphqlCodeRegistry at the last step of building the schema. Or use a [GraphQLFieldDefinition wrapper](https://github.com/google/rejoiner/blob/master/rejoiner/src/main/java/com/google/api/graphql/rejoiner/FieldDefinition.java) that also contains the DataFetcher and parent type name. I think with these wrapper objects it shouldn't be difficult for us to migrate. Having something like `GraphqlCodeRegistry.combine()` would help out.

```
public static GraphqlCodeRegistry combine(Collection<GraphqlCodeRegistry> GraphqlCodeRegistryCollection){
 // combine all private fields and return a new instance of GraphqlCodeRegistry
}
```

In general I think this change (separating the schema definition from the resolvers) is introducing some of the issues as outlined here https://www.prisma.io/blog/the-problems-of-schema-first-graphql-development-x1mn4cb0tyl3

Anyway, this library has matured a lot over the past years, thanks for the great work!

**Comment by Togrias** [comment]
The reference implementation graphql.js is using the original pattern. It helps consolidate all the code related to one object in one place.

**Comment by excitement-engineer** [comment]
@Togrias I agree with your point. It makes the code a lot more manageable when the type and the resolver are contained in one place. I would also upvote keeping support for the DataFetcher API as it currently stands.

**Comment by siderakis** [comment]
Reopening since others had questions.

It would be useful to know if these are going to be removed or not. If not can we remove the deprecated annotations?

**Comment by bbakerman** [comment]
> It would be useful to know if these are going to be removed or not. If not can we remove the deprecated annotations?

We plan to remove them.  Hence we put @deprecation Java annotations on them to signal that intent.   We will not be removing the annotations.

**Comment by Togrias** [comment]
Will the API of the Relay helper library also be changed? Right now it uses the deprecated methods typeResolver and dataFetcher.

**Comment by siderakis** [comment]
What would it take in terms of community feedback for you to reconsider the decision?

**Comment by kliakos** [comment]
+1 for keeping the DataFetcher on GraphQLFieldDefinition.

Why can't we have both the registry and the original pattern?

**Comment by bbakerman** [comment]
We are not going to do this in graphql-java

**Comment by kliakos** [comment]
Is there an example of a large open-source codebase that is using a code-first GraphQL schema building approach? I am wondering how can the approach with the `GraphQLCodeRegistry` be maintainable when you have at least a few thousand GraphQL fields.

**Comment by cristatus** [comment]
While the reference implementation `graphql-js` still allows resolver with field definition (and there is no intention to remove it), I am really surprised why `graphql-java` made it deprecated. We are stuck with older version just because of this change. We have a very large object graph that we found very difficult to migrate.
