### ISSUE TITLE
A null variables map causes NPE during coercion

### ISSUE THREAD

**Issue by grrttedwards** [graphql-java/graphql-java#1506]
**Describe the bug**
Version `11.0`
During execution of a query which includes a variable, but no variables map in the request, a NullPointerException occurs during coercion of the variable values.

This is worked around by explicitly initializing the variables map to an instance of an empty map, but I'm curious if this should be handled at the GraphQL server level? This is related to #1142, which was rejected for a slightly different reason.

The default behavior of Spring in particular when using Jackson defaults is to leave the variables map null on the request DTO if it was not specified in the request.

When a request is made with a variable and without the variable value map, the following occurs:
```
java.lang.NullPointerException: null
	at graphql.execution.ValuesResolver.coerceArgumentValues(ValuesResolver.java:77)
	at graphql.execution.Execution.execute(Execution.java:71)
	at graphql.GraphQL.execute(GraphQL.java:573)
	at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:515)
	at graphql.GraphQL.executeAsync(GraphQL.java:489)
	at graphql.GraphQL.execute(GraphQL.java:420)
```

**To Reproduce**
Either create a small test server or start any server you have around with a schema
1. Start a server with a simple schema like `type Query { foo(a: Int): Int }`
1. Send a request JSON like 
    ```
    { 
      "query": "query TestMissingVariable($variable: Int) { foo(a: $variable) }",
      "operationName": "TestMissingVariable"
    }
    ```
    with no variables map 
1. See exception occurs

**Comment by bbakerman** [comment]
Yeah defaulting the variable map if its null would make sense to avoid NPEs.

**Comment by andimarek** [comment]
thanks for reporting. the original code path is not valid anymore, but via #1596 we are making now sure variables map can never be null. closing this issue now
