### ISSUE TITLE
Cache control extension usage/directive

### ISSUE THREAD

**Issue by jmccaull** [graphql-java/graphql-java#1507]
I am looking into replacing a custom implementation of Apollo Cache controls with the one recently implemented here. I see the infrastructure for the cache controls, but has anyone done anything like the directive yet? is this the right place for it? I can do a quick pr if appropriate.

**Comment by bbakerman** [comment]
>but has anyone done anything like the directive yet? 

I am not sure what the "directive" is?  Is there a well known schema directive out there that indicates "caching" for a field?

**Comment by jmccaull** [comment]
Apollo utilizes a @cacheControl(maxAge: Int, scope: Scope) directive in schemas to define what fields get hints: https://github.com/apollographql/apollo-server/tree/master/packages/apollo-cache-control
I guess a refinement of my question is, if Apollo style cache controls are supported, does it make sense to provide the directive as well? would something like the spring boot kickstart or java graphql tools be a better place for this? To me it seems similar to the tracing instrumentation and makes sense to include here. I'll find time shortly to work up a PR

**Comment by williamkwao** [comment]
@jmccaull I can pick this up if you haven't started working on it

**Comment by andimarek** [comment]
@jmccaull I don't think graphql java is the right place to offer non standard solutions like that. You are right that we did that before (kind of) by supporting the tracing format. 
But the experience  shows that supporting something that relies on non spec conforming implementations is a risky thing todo.

I would think this kind of instrumentation/directive belongs into an extra library.
