### ISSUE TITLE
how get data from database to construct SimpleListConnection 

### ISSUE THREAD

**Issue by LongylG** [graphql-java/graphql-java#1510]
recently,i begin to use graphql,when i was want to get pagination parameter,i notice that relay
can do this.but i find and read a lot of document,i was at a loss about how to get data,SimpleListConnection is different with DataFetcher,DataFetcher can get arguments and do query method to get data from database,SimpleListConnection only accept List<T>.there is someone can give me an example,think a lot!

**Comment by bbakerman** [comment]
Relay is a specification for pagination : 

https://facebook.github.io/relay/docs/en/graphql-server-specification.html
https://facebook.github.io/relay/graphql/connections.htm

You need to create "types" that match the relay shape as proscribed by the Relay spec.

Then as you say you need to create a data fetcher that returns a `source' object that fits this shape

```
{
ships(first: 1) {
      edges {
        node {
          name
        }
      }
    }
}
```
So in the example above, the ships data fetcher needs to return a object that can be examined by the `edges` and `node` fields etc

We have given you a "list" backed implementation as a starter in graphql-java.  It assumes it has the complete set of data in a list (which is can paginate itself ) which in the real world is not that useful

However you can implement your own `graphql.relay.Connection` implementation say via `graphql.relay.DefaultConnection`

You would read data from the database, paginated according to the field replay "arguments" ie. `first`/`after` or `last`/`before`

https://facebook.github.io/relay/graphql/connections.htm#sec-Forward-pagination-arguments

And then create `Edge` data from it place it into the `graphql.relay.DefaultConnection`

I have some exploratory code that does this with a local database

https://github.com/bbakerman/graphql-java-examples/tree/master/src/main/java/com/graphql/example/proxy/relay

https://github.com/bbakerman/graphql-java-examples/blob/master/src/main/java/com/graphql/example/proxy/IceAndFireDataFetchers.java#L152

That example was reading data from a "paged" http service (fire and ice) and turning it into Relay data.  


FYI : the Spectrum chat room is a better place to ask these questions

https://spectrum.chat/graphql-java

**Comment by LongylG** [comment]
@bbakerman,thank a lot for you reply,and i was learned a lot from above example and document ,i got a idea to pagination, below is my code:
 public static <T> Connection<T> getConnection(DataFetchingEnvironment env, List<T> data) {

        SimpleListConnection simpleListConnection = new SimpleListConnection(data);
        return simpleListConnection.get(env);
    }
is it correct?

**Comment by bbakerman** [comment]
Perhaps - I cant see enough of your code.  The trick with connections is you need the `last/first` arguments from the DataFetcherEnvironment so you can "page your data".  SimpleListConnection works as long as you are happy that 100% of the possible data can be in memory at one time

To be more efficient you will need your own Connection that also takes the pagination arguments.

**Comment by greenled** [comment]
@bbakerman do you have any plans to add another Connection implementation backed by something else than a List, something more flexible? If that's the case I would like to share my own implementation, inspired by the `SimpleListConnection` and the [ForwardOnlyFixedPagedDataSet](https://github.com/bbakerman/graphql-java-examples/blob/master/src/main/java/com/graphql/example/proxy/relay/ForwardOnlyFixedPagedDataSet.java) in your example. It accepts four functions and a String prefix for the cursors in the constructor:

- One for geting a List<T> of *forward* paginated results
- One for geting a List<T> of *backward* paginated results
- One for transforming an Object (instance of T) into a String identifier to build the cursors
- One for transforming a String identifier back into an Object (instance of T)

This is how the constructor looks like:

```java
public OutsourcedConnection(
    String prefix,
    Function<T, String> objectToIdentifier,
    Function<String, T> identifierToObject,
    BiFunction<T, Integer, List<T>> getResultsPageForward,
    BiFunction<T, Integer, List<T>> getResultsPageBackward
)
```

As the way it fetches the data is up to the functions provided, it allows to **efficiently** use relay pagination with a relational database. I think it's generic enough to be used with an http service or any other data source with support for pagination. Should I make a PR with further details?
