### ISSUE TITLE
GraphQL Java limit condition

### ISSUE THREAD

**Issue by raj206** [graphql-java/graphql-java#1511]
`Background`:

Using GraphQL Java with Kotlin in a SpringBoot app.

`Problem`:

I am trying to add a limit condition on a certain type which would go somewhat like this:

`user.graphqls`:
```
type Author {
  id: ID!
  books: [Book]
}
getAuthor(id: ID!): Author
```
Now, I only want to get 1 book and not all the books.

`Kotlin Data Classes`:
```
data class Book(id: Int, name: String)
data class Author(id: Int, books: List<Book>)
```
`Kotlin Query Resolver`
```
class AuthorResolver(): GraphQLResolver {
    fun getAuthor(id: Int): Author {
      val b1 = Book(1, "b1")
      val b2 = Book(2, "b2")
      val b3 = Book(3, "b3")
      val a1 = Author(1, arrayListOf(b1, b2, b3))
      return Author
    }
}
```
Note: I am obviously not using Ints for IDs so please don't answer with security concerns etc. This is just an oversimplified example for a much more complex problem.

Query I want:
```
query GetAuthor{
  getAuthor(id: 1) {
    books (limit: 1) {
      id,
      name
    }
  }
}
```
The (limit: 1) throws an error and I would like to fetch only one Book. How can I do that?

**Comment by bbakerman** [comment]
I notice you are using `GraphQLResolver` which is not a base graphql-java feature

I think it comes from another project based on graphql-java 

https://github.com/graphql-java-kickstart/graphql-java-tools



FYI : the Spectrum chat room is a better place to ask these questions

https://spectrum.chat/graphql-java

**Comment by andimarek** [comment]
closing it because we didn't get any new information, please reopen again @raj206 if you have new infos
