### ISSUE TITLE
InlineFragment not implementing DirectivesContainer

### ISSUE THREAD

**Issue by dirkkolb** [graphql-java/graphql-java#1514]
I am just wondering why InlingeFragment is not implementing the DirectivesContainer interface. Obviously, all methods of DirectivesContainer are implemented.

**Comment by bbakerman** [comment]
The challenge is that `public interface DirectivesContainer<T extends DirectivesContainer> extends NamedNode<T> `

and name node has a name - aka getName() which InlineFragment does not

Now exactly what DirectivesContainer has to be a named node is a little lost on me in review and hence perhaps that is the oversight.  That is is there a place where DirectivesContainer has to be a NamedNode say??

I think we would change DirectivesContainer to not be a NamedNode and hence be able to apply it to InlineFragment

**Comment by realityforge** [comment]
I believe this issue can be closed as the associated PR has been merged
