### ISSUE TITLE
`SchemaDirectiveWiringEnvironment#getCodeRegistry` is null

### ISSUE THREAD

**Issue by alexgenco** [graphql-java/graphql-java#1515]
**Describe the bug**

We're trying to upgrade to from 11.0 to 12.0 and the upgrade has broken one of our directive wirings. It seems like the `SchemaDirectiveWiringEnvironment` passed to `onField` has a null `getCodeRegistry()` on all fields we've used the directive on.

We are also updating from graphql-java-tools 5.4.1 to 5.6.0.

**To Reproduce**

```java
public class FooDirective implements SchemaDirectiveWiring {
  @Override
  public GraphQLFieldDefinition onField(SchemaDirectiveWiringEnvironment<GraphQLFieldDefinition> env) {
    Objects.requireNonNull(env.getCodeRegistry());
    return env.getFieldDefinition();
  }
}

public class QueryResolver implements GraphQLQueryResolver {
  public String field() {
    return "foo";
  }
}

public static void main(String[] args) {
  GraphQLSchema schema = SchemaParser.newParser()
    .directive("foo", new FooDirective())
    .schemaString("type Query { field: String @foo }")
    .resolvers(new QueryResolver())
    .build()
    .makeExecutableSchema(); // Throws NPE
}
```

We've been following the documentation here https://www.graphql-java.com/documentation/v12/sdl-directives/

Thanks!

**Comment by bbakerman** [comment]
I think you might have an interplay problem between graphql-java the base library and graphql-java-tools which is an abstraction layer on top of graphql-java

https://github.com/graphql-java-kickstart/graphql-java-tools

I double checked and we have a series of integration tests that prove the codeRegistry is non null

The reproduction code above is not graphql-java code.  I think it might be that whatever library it is (and I am guessing at graphql-java-tools) has a version interplay problem with the latest graphql-java 12.0

**Comment by alexgenco** [comment]
Thanks @bbakerman I'll open up an issue over there as well

**Comment by alexgenco** [comment]
No need: https://github.com/graphql-java-kickstart/graphql-java-tools/issues/268

**Comment by alexgenco** [comment]
This appears to be fixed now 🎉
