### ISSUE TITLE
Error reporting not helpful for large project structures

### ISSUE THREAD

**Issue by raj206** [graphql-java/graphql-java#1520]
`Basic problem`:
When GraphQL throws errors, it lists the line number which is calculated by going through the files in alphabetical order. 
`Example`: 
There was an error in my `b.graphqls` file at line 19 but as it is the second file (after `a.graphqls` which has 55 lines of code), the error showed that there is a problem with line 74.
For small projects which have a single schema file, this might seem like the appropriate way of doing things but with about a 100+ types and countless queries, this does not make sense. 
`Questions`:
Is there a better way in which errors can be reported? 
Or is there a better project structure that would support this ideology? (I have one file for queries, one for mutations and multiple files for different types)

**Comment by bbakerman** [comment]
For SDL have a look at `graphql.parser.MultiSourceReader`.  Its is designed for exactly the situation you are talking about.  That is it allows you to create a virtual document from many parts.

However for queries, `graphql.ExecutionInput` only takes a String and hence there is no "sourceName" associated with a Query.  We would have to change it significantly to be `Reader` based.  Its possible but not as urgent as in SDL definitions

I cant recall off hand if `graphql.parser.MultiSourceReader` was released in 12.0 or is coming in 13.0

**Comment by andimarek** [comment]
@raj206 closing this issue now as 13.0 is released. Please open it again if the problem was not solved.
