### ISSUE TITLE
Parse errors in SDL field definitions when using keywords as field names

### ISSUE THREAD

**Issue by jimkyndemeyer** [graphql-java/graphql-java#1523]
**Describe the bug**
Given the following SDL:

```graphql
type Foo {
  true: String
  false: String
  on: String
  null: String
}
```

The parser throws a parse error even though these names are allowed as field names in the GraphQL grammar: https://graphql.github.io/graphql-spec/June2018/#FieldDefinition

I see there's already an attempt at handling this for other keywords in https://github.com/graphql-java/graphql-java/blob/fccc0c754eea96c6b89024349f359d2e563e6691/src/main/antlr/GraphqlCommon.g4#L31

**To Reproduce**
New up the GraphQL Parser and parse the example above:

```java
import graphql.parser.Parser;
new Parser().parseDocument(exampleSDLAsString);
```
Observe that the parser throws errors even though the above is valid according to the grammar.

Related issue: https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/issues/239

**Comment by andimarek** [comment]
thanks for reporting: is should be fixed with #1599
