### ISSUE TITLE
AbsoluteGraphQLError ignores execution path

### ISSUE THREAD

**Issue by jmccaull** [graphql-java/graphql-java#1527]
Using the DataFetcherResult builder along with the GraphqlErrorBuilder, if the path of the error in the builder is not set to an empty collection explicitly the execution path is ignored in the optional logic within AbsoluteGraphQLError and null is returned. Looking at the tests, I can't tell if this is intentional though it seems like a bug to me. This could be fixed in the builder but I think it is more appropriate to handle within AbsoluteGraphQLError. Is there a reason this should ever return null? if not I've done a quick pr to correct. 
https://github.com/graphql-java/graphql-java/pull/1526

**Comment by andimarek** [comment]
We are planning to get rid of `AbsoluteGraphQLError` totally and to support it function differently.
