### ISSUE TITLE
Upload file via mutation support

### ISSUE THREAD

**Issue by dev-rkoshlyak** [graphql-java/graphql-java#153]
I don't think it is possible now.
I know there are support from js side for uploading files via mutations.
But i see no support for it from java side.

**Comment by Jimexist** [comment]
I think you just need to implement `DataFetcher` and then get the `File` or `FileInputStream` from the context/environment. There is very little to be done this library.

**Comment by kaqqao** [comment]
Yup, what JS examples do is just set the entire request object as the root context. You can do the exact same thing. Then your fetcher can get the file from the request body. Nothing for the spec implementation itself to do.

**Comment by andimarek** [comment]
closing because as mentioned it is out of scope for this library to hande file uploads

**Comment by 0x6e6562** [comment]
@andimarek Not sure how helpful it is to suggest something from a different platform, but in the [Absinthe](https://github.com/absinthe-graphql/absinthe) GraphQL server library, you can get a handle on Elixir equivalent of a Java `ServletRequest` - they call it `%Plug.Upload{}` in the standard library, but the abstraction would be isomorphic in Java:

```elixir
mutation do
  field :upload_file, :string do
    arg :payload, non_null(:upload)
    arg :metadata, :upload
    resolve fn args, _ ->
      args.payload # this is a `%Plug.Upload{}` struct.
      {:ok, "success"}
    end
  end
end
```

As previous posters have said, it is possible to craft this from the library as is, so strictly speaking this is not necessary. But it would be nice from a documentation perspective.

**Comment by andimarek** [comment]
@0x6e6562 always happy to improve the documentation. Could you create a PR to document it? that would be great!

**Comment by 0x6e6562** [comment]
@andimarek I would gladly raise a PR to help other people with this issue, but for various different reasons, I decided to abandon file uploads via `graphql-java`, so I didn't put the time in to figure out how to wire this into a programmatic field definition. I just made the point about the upload support because I had used it on a different project (using a different graphql server package).

**Comment by loganvolkers** [comment]
If someone is looking to implement this, here is a proposed spec that uses multipart upload: https://github.com/jaydenseric/graphql-multipart-request-spec
