### ISSUE TITLE
Support for query variables

### ISSUE THREAD

**Issue by iancw** [graphql-java/graphql-java#154]
It looks like express-graphql and graphql-ruby accept queries with query and variables in separate structures.  For example, here is a query generated by the express-graphql client library.

```json
{
   "query":"query AppHomeRoute($uuid_0:String!) {
         account(uuid:$uuid_0) { 
               ...
         }
     }",
   "variables":{"uuid_0":"88888888-4444-4444-4444-121212121212"}
}
```
Here are a couple articles discussing variables:
 * http://rmosolgo.github.io/blog/2016/03/03/using-graphql-without-relay/
 * https://medium.com/the-graphqlhub/graphql-tour-variables-58c6abd10f56#.3lumjqvbm 

It doesn't look like the graphql-java server accepts query variables like this currently.  It seems like this would be a nice feature to have, so you can use graphql-java servers with the relay-starter-kit.

**Comment by danielkwinsor** [comment]
The GraphQL object accepts variables aka arguments
public ExecutionResult execute(String requestString, Object context, Map<String, Object> arguments)`
You can set context to null in this case.

**Comment by iancw** [comment]
I've expanded the provided example for a bit more context.  When I put a variable named `uuid_0` in the arguments map, I still get `ValidationError: Validation error of type UndefinedVariable: Undefined variable uuid_0` during validation.  I also attempted `$uuid_0` with same result.

When I provide the values statically, the framework automatically puts them into the arguments map.  For example, this works.

```
query  {
    account(uuid:"88888888-4444-4444-4444-121212121212") {
        ...
    }
}
```

And `uuid` shows up as a key in the `arguments` map.  It looks like the Graphql grammar the parser is based on understands variables (https://github.com/antlr/grammars-v4/blob/master/graphql/GraphQL.g4), but there is no grammar for specifying the values of said variables.  They appear instead to be passed as part of a JSON request alongside the GraphQL query by react / express-graphql and graphql-ruby (as described above).

I see no mechanism to set them in graphql-java currently.  I could easily write a wrapper in my service to parse JSON response and stick the variable definitions somewhere.  There doesn't appear to be a place though.  If I'm corrected, I'll happily submit a PR to the README that documents how to do this.

**Comment by iancw** [comment]
So I just found your TODO MVC example, and see that you do in fact use variables as described above (https://github.com/graphql-java/todomvc-relay-java/blob/master/src/main/java/todomvc/GraphQLController.java#L33-L34). And also it seems to be working fine for me now.  Maybe I just needed to clean & rebuild or something. Working on a PR to update README as promised.

**Comment by iancw** [comment]
I submitted a PR to README to document how variables are supported.   Not sure when / if that will merge, so I'm just closing this issue. I have my graphql-Java server working with relay following advice from @danielkwinsor.  Thanks!

**Comment by devtomk** [comment]
Are variables really supported? Maybe I am missing something, but the following code always results in an error "Validation error of type UndefinedVariable: Undefined variable personId"


    String query = "query { person(id: $personId) { id, name } }";
    Map<String, Object> variables = new HashMap<>();
    variables.put("personId", "42");

    ExecutionInput input = ExecutionInput.newExecutionInput().
        query(query).
        variables(variables).
        build();
    ExecutionResult result = graphQL.execute(input);

The following works without problems:

    String query = "query { person(id: \"42\") { id, name } }";
    ExecutionInput input = ExecutionInput.newExecutionInput().
        query(query).
        build();
    ExecutionResult result = graphQL.execute(input);


I am using graphql-java 4.0

**Comment by SebastianWjertzoch** [comment]
I have the exact same problem with version 4.1.

**Comment by andimarek** [comment]
@devtomk @SebastianWjertzoch variables are fully supported ... your query is wrong.

you have to declare each variable with type for example:
```graphql
query nameOfTheQuery($nameOfTheVariable: Int) { 
  foo(someArgument: nameOfTheVariable) 
} 
```

**Comment by SebastianWjertzoch** [comment]
We both use the ExecutionInput. So type declaration is not part of the query.

Like this
String query = "query { person(id: \"42\") { id, name } }";
ExecutionInput input = ExecutionInput.newExecutionInput().
    query(query).
    build();
ExecutionResult result = graphQL.execute(input);

**Comment by andimarek** [comment]
@SebastianWjertzoch as mentioned above:  you have to declare the variable. 

you query is 
```graphql
query { person(id: $personId) { id, name } }
```
but it is missing the declaration of the variable. It should like this:
```graphql
query myQuery($personId: Int) { person(id: $personId) { id, name } }
```

I hope this helps

**Comment by SebastianWjertzoch** [comment]
Ok. So i have to build an special query for every kind of request. I was confused because this: 
query { person(id: \"42\") { id, name } } 
works fine without special queries.

**Comment by andimarek** [comment]
well ... if you wanna use a variable you have to declare the variable. 

the query you mention works fine, because you don't use a variable, hence you don't have to declare it.
