### ISSUE TITLE
QueryResolver ParentType name for Wrapped Types

### ISSUE THREAD

**Issue by vgupta88** [graphql-java/graphql-java#1548]
While QueryTraversal helped us get a list of all query fields in a ${type}.${name} fashion we hit a roadblock where the parent type is a list/wrappedType. For Wrapped types we get the getParentType() as [${type}] but getParentType().getName() comes as null which should have been ${type} where as for other non-wrapped types it works fine.
Can anyone suggest a way to work around this?

**Comment by bbakerman** [comment]
Use `graphql.schema.GraphQLTypeUtil` to unwrap types completely and get their name
