### ISSUE TITLE
Move errorType to extensions

### ISSUE THREAD

**Issue by aeb-sia** [graphql-java/graphql-java#1549]
The spec used to not specify how to handle extra data on errors, but it does not and it actually [discourages](https://graphql.github.io/graphql-spec/June2018/#example-9008d) adding other toplevel field to the errors entry.

Instead it recommends putting all that under extensions. I know this is a breaking change but it seems to be future proof way.

**Comment by bbakerman** [comment]
We have a PR for exactly this

https://github.com/graphql-java/graphql-java/pull/1495

**Comment by realityforge** [comment]
I believe this issue can be closed as the associated PR has been merged
