### ISSUE TITLE
Should `SchemaDirectiveWiringEnvironmentImpl` be package private?

### ISSUE THREAD

**Issue by rharriso** [graphql-java/graphql-java#1552]
One of the constructor parameters is `SchemaGeneratorDirectiveHelper.Parameters` is internal to the package private class `SchemaGeneratorDirectiveHelper`

**Comment by bbakerman** [comment]
We tend to use public classes in graphql0-java BUT annotate them with `@PublicApi` or`@Internal`

```
@Internal
public class SchemaDirectiveWiringEnvironmentImpl<T extends GraphQLDirectiveContainer> implements SchemaDirectiveWiringEnvironment<T> {

```

so really its an internal class and is not intended to be used by consumers

**Comment by rharriso** [comment]
Is there an advantage to public vs default package private?

I’ve used that when I wanted to test internals.

**Comment by bbakerman** [comment]
> Is there an advantage to public vs default package private?

Its a trade off.  default level access is more restrictive so one could argue to use the least access as possible.

However that is also a barrier to code re-use AND flexibility in a library.

So we go for flexiable (public) BUT use annotations to warn people of possible instability

**Comment by rharriso** [comment]
The trade off and choice makes sense. 

However should `SchemaGeneratorDirectiveHelper` then be public as well? It is also annotated as `@Internal` and one of it's internal classes, `Parameters`, is used as a argument type on a public class.

Thanks for you time.
