### ISSUE TITLE
When I have more than one RuntimeWiring in my project, how do I finally combine them

### ISSUE THREAD

**Issue by szjzszjz** [graphql-java/graphql-java#1553]
BookProvider :All the methods for Book
 public static RuntimeWiring buildRuntimeWiring(BookDataFetcher bookDataFetcher) {
        return RuntimeWiring.newRuntimeWiring()
                .type(newTypeWiring("Query").dataFetcher("books", bookDataFetcher.books()))
                .type(newTypeWiring("Query").dataFetcher("bookById", bookDataFetcher.bookById()))
                .type(newTypeWiring("Query").dataFetcher("bookByPageCountAndId", bookDataFetcher.bookByPageCountAndId()))
                .type(newTypeWiring("Query").dataFetcher("booksPaging", bookDataFetcher.booksPaging()))
                .type(newTypeWiring("Query").dataFetcher("booksPagingByPageCount", bookDataFetcher.booksPagingByPageCount()))
                .type(newTypeWiring("Query").dataFetcher("booksLikeByName", bookDataFetcher.booksLikeByName()))
                .type(newTypeWiring("Mutation").dataFetcher("modifyBook", bookDataFetcher.modifyBook()))
                .type(newTypeWiring("Mutation").dataFetcher("createBook", bookDataFetcher.createBook()))
                .type(newTypeWiring("Mutation").dataFetcher("deleteBook", bookDataFetcher.deleteBook()))
                .type(newTypeWiring("Book").dataFetcher("author", bookDataFetcher.author()))
                .build();
    }

UserProvider :All the methods for User
public static RuntimeWiring buildRuntimeWiring(UserDataFetcher userDataFetcher){
        return RuntimeWiring.newRuntimeWiring()
                .type(newTypeWiring("Query").dataFetcher("save",userDataFetcher.save()))
                .type(newTypeWiring("Query").dataFetcher("login",userDataFetcher.login()))
                .type(newTypeWiring("Query").dataFetcher("userById",userDataFetcher.userById()))
                .type(newTypeWiring("Query").dataFetcher("userByGender",userDataFetcher.userByGender()))
                .build();

    }

Finally, you want to generate a graphqlSchema, but makeExecutableSchema(typeRegistry, userWiring); Only one RuntimeWiring is allowed, what should I do?
        GraphQLSchema graphQLSchema1= schemaGenerator1.makeExecutableSchema(typeRegistry,  userWiring);

**Comment by bbakerman** [comment]
Sorry we dont not provide a mechanism to combine runtime wirings.  Its not a use case we have put any effort into

You could create a "master" runtime wiring that delegated to a set of wirings (resolving clashes yourself) 

Or you could have each of those "build" methods take a RuntimeWiring.Builder and have them work on a common mutable builder

**Comment by bbakerman** [comment]
BTW its not a bad idea that we could have a Runtime combining mechanism.  Its just not something that we have built.  The challenge on that of course would be resolving clashes.  eg how to combine each when they have each have a WiringFactory say.

**Comment by szjzszjz** [comment]
thanks a lot！My problem has been solved.

**Comment by shwetasynoverge** [comment]
How did you resolve it

**Comment by nikki003** [comment]
> thanks a lot！My problem has been solved.
Can you please tell how did you solve it. I m trying out the same thing that you tried
