### ISSUE TITLE
Multiple fragments with the same name should be an error

### ISSUE THREAD

**Issue by realityforge** [graphql-java/graphql-java#1557]
Fragment names should be unique within a document according to [Section 5.5.1.1](https://graphql.github.io/graphql-spec/draft/#sec-Fragment-Name-Uniqueness) of the specification but `graphql-java` does not generate an error when this this occurs.

i.e. The following does not generate a validation error but should
```graphql
...

fragment NameParts on Event {
  name
}

fragment NameParts on Event {
  name
  type {
    name
  }
}

...
```

**Comment by bbakerman** [comment]
Thanks for reporting.  Since you have fixed it on your branch, a PR back into the main library would help others.

(Its open source after all)

**Comment by andimarek** [comment]
This will be addressed by this PR: https://github.com/graphql-java/graphql-java/pull/1607
