### ISSUE TITLE
Support for Apollo's GraphQL Federation

### ISSUE THREAD

**Issue by arlampin** [graphql-java/graphql-java#1565]
Apollo has open-sourced their Apollo Federation spec and JS implementation

blog post: https://blog.apollographql.com/apollo-federation-f260cf525d21
spec: https://www.apollographql.com/docs/apollo-server/federation/federation-spec/

It would be nice to have graphql-java support the federation spec so that services written using graphql-java could be used as a part of a federated schema.

**Comment by andimarek** [comment]
Hi,

I think support for Apollo Federation would be an additional library on top of GraphQL Java, therefore we will not implement directly in this project.

Of course if some features are missing in GraphQL Java to implement it we would be open for PRs/changes to make it happen.

**Comment by bbakerman** [comment]
One thing listed as missing is `extend type XXX {...}` support in the schema printer

Todate we collapse `extend type` objects as schema build time and hence there is no evidence of their existence at schema print time (eg when we print a GraphQLObjectType )

**Comment by bbortt** [comment]
Hi all!

I'm very interested in this as well. Sadly, I don't know much about the background of this project. For example, would the same separation of "Federation" and "Graphql-Server" as in the [apollo-implementation](https://github.com/apollographql/federation-demo/blob/master/gateway.js) be possible and make sense? E.g. does graphql-java also have some kind of `executor` and would this be customizable?
Then we should definitely create a new project which "stitches" the schema and creates this `executor`.
Anyways I think we have to adapt the existing graphql-java to allow "unchecked" foreign entities (e.g. no present Java object) for sure. Respectively support the new syntax occasionally.

What do you guys think?

BR, Timon

**Comment by arlampin** [comment]
I just realized that Apollo seems to already have a Java impl. available at https://github.com/apollographql/federation-jvm build on top of graphql-java. I haven't actually tested it and I haven't seen any references to it, but it seems to be exactly what I had in mind.

**Comment by bbortt** [comment]
@arlampin nice one, didn't know that. sadly it seems just to cover the service party not the gateway :( I'd love to combine it with the cloud gateway. however, it's a start, at least.

**Comment by mcohen75** [comment]
I have a couple of PRs open to the federation-jvm project that gets the project into a basic working state. More work is necessary. So far the team has not been highly responsive to my questions and PRs. @bbakerman is the team here open to the possibility of a community contributed federation project?

**Comment by andimarek** [comment]
closing this issue, because there is no direct action at the moment.

Please contribute to the https://github.com/apollographql/federation-jvm project if you are interested in java federation support.

@mcohen75 not sure what you mean with "community contributed". If you mean projects under the GraphQL Java org, then the answer in general is no: we only allow projects inside the org we are ourself fully committed in maintaining.

**Comment by mcohen75** [comment]
Thanks for following up Andreas. Yes I meant under the GraphQL Java org.
