### ISSUE TITLE
Schema parser doesn't throw errors anymore

### ISSUE THREAD

**Issue by jexp** [graphql-java/graphql-java#1574]
**Describe the bug**
I'm upgrading graphql-java in a library from version 5 to 12 and my last failing tests are expected schema parser errors.

The old version used to fail with an (antlr) exception. The new version silently returns a broken document. But something outputs an error to the console:

```
line 3:7 token recognition error at: '/'

java.lang.AssertionError: Should fail parsing: 

Document{definitions=[ObjectTypeDefinition{name='Foo', implements=[], directives=[], fieldDefinitions=[]}, OperationDefinition{name='null', operation=QUERY, variableDefinitions=[], directives=[], selectionSet=SelectionSet{selections=[Field{name='name', alias='null', arguments=[], directives=[], selectionSet=null}, Field{name='String', alias='null', arguments=[], directives=[], selectionSet=null}]}}]}
```

Could be related to: https://github.com/graphql-java/graphql-java/pull/1348

**To Reproduce**
Please provide a code example or even better a test to reproduce the bug.

```
    @Test
    fun parseIDLError2() {
        val input = """
type Foo {
  name / String
}
"""
        try {
            val doc = Parser().parseDocument(input)
            fail("Should fail parsing: ${doc}")
        } catch(e: Exception) {
            assertEquals("Error parsing IDL expected ':' got '/' line 3 column 7",e.message)
        }
    }

```

**Comment by andimarek** [comment]
I could reproduce the exception in version 5, but not in 13.0 ... it may have todo with the newer antlr version we are using.

**Comment by andimarek** [comment]
we actually never really handled pure syntax errors: #1601 fixes that.

Thanks for reporting @jexp
