### ISSUE TITLE
Update v13 Query Caching documentation

### ISSUE THREAD

**Issue by marceloverdijk** [graphql-java/graphql-java#1575]
The [v13 Query Caching](https://www.graphql-java.com/documentation/v13/execution/) documentation is out of date and should be updated.

**Comment by Sparow199** [comment]
I'm interested to do this.

**Comment by Sparow199** [comment]
Take a look at this working [example](https://gist.github.com/Sparow199/ad81ab4407c6c13e37004dd696775a4a), if you validate it, i'll make a PR to documentation project.

**Comment by ahhhkah** [comment]
Hey @Sparow199 

I think, reinitializing the cache inside the getDocument-Function, makes caching useless.

My solution would be something like this:
```
Cache<String, PreparsedDocumentEntry> cache = Caffeine.newBuilder().maximumSize(10_000).build();

GraphQL graphQL = GraphQL.newGraphQL(StarWarsSchema.starWarsSchema)
            .preparsedDocumentProvider((executionInput, computeFunction) -> cache.get(executionInput.getQuery(), val -> computeFunction.apply(executionInput)))
            .build();
```

Or if you prefer a class: https://gist.github.com/ahhhkah/91c6d20c82ea24cbb327fc086830e5aa

I also created a pull request: https://github.com/graphql-java/graphql-java-page/pull/28

**Comment by Sparow199** [comment]
Thanks for your feedback, I'm agree with you. In my production code, I
inject the bean with Cache so I haven't this issue.

**Comment by marceloverdijk** [comment]
Thx for this.

PS: It looks complex for a simple cache lookup as it was before (`.preparsedDocumentProvider(cache::get)`).
Maybe the GraphQL api itself could provide some easier way here.
