### ISSUE TITLE
Unicode characters not supported in graphql descriptions

### ISSUE THREAD

**Issue by rsmckinney** [graphql-java/graphql-java#1577]
**Describe the bug**
Unicode characters such as emoji are not supported in graphql descriptions.

**To Reproduce**
Excerpt from the github graphql schema:
```graphql
"""
Emojis that can be attached to Issues, Pull Requests and Comments.
"""
enum ReactionContent {
  """
  Represents the 😕 emoji.
  """
  CONFUSED
. . .
}
```
The above emoji character is in the triple-quote comment, but the graphql antlr parser chokes on it.  This blows up parsing of the schema, rendering it useless.

**Comment by bbakerman** [comment]
I seem to recall some other work some one did a while back regarding emojii and other more Unicode characters.

I will try to dig up what happened there.  

It feels like something we should fix (in the ANTLR parser) but I cant help shaking this nagging feeling that there was more to it.

**Comment by bbakerman** [comment]
So the PR I was thinking of is https://github.com/graphql-java/graphql-java/pull/464/files

Again off hand I cant remember why I had to use surrogate pairs on input.  I would need to do more investigation of the spec.  I seem to recall something about that but perhaps I am wrong.

**Comment by bbakerman** [comment]
https://graphql.github.io/graphql-spec/June2018/#CommentChar

> A comment can contain any Unicode code point except LineTerminator so a comment always consists of all code points starting with the # character up to but not including the line terminator.

Seems pretty clear that it should be allowed

**Comment by rsmckinney** [comment]
In my view I'd be inclined to put a low priority on this, however the schema in question is the GitHub schema which is a pretty high profile.  Since Manifold uses graphql schemas as a virtual type domain, the schema has to at least parse in order for Manifold to make use of it. ([Manifold](https://github.com/manifold-systems/manifold) is a new framework for Java I am working with)

**Comment by bbakerman** [comment]
One work around might be to preparse the SDL and replace certain unicode characters with their \uxxxx replacements first, which I think will parse right now

**Comment by andimarek** [comment]
After reviewing the spec and what we do it is actually correct that emojis are not supported. (See https://github.com/graphql/graphql-spec/issues/214)

This emoji is outside of the range of supported characters for the description, but they are allowed for comments.

@rsmckinney can you point us to the position where github uses an emoji in a description? thanks

**Comment by andimarek** [comment]
@rsmckinney never mind, I found that you actually referenced a snipped from the github API. 👍 

Just as clarification: comments are different from the triple quote strings you are used. This is called "description". Comments allow all unicode chars, but descriptions don't.

**Comment by andimarek** [comment]
@bbakerman I am inclined to change to allow full unicode characters, even if it is outside of the spec. What do you think?
