### ISSUE TITLE
Support additional Optional like types from other packages ( guava, vavr, etc )

### ISSUE THREAD

**Issue by sean-brandt** [graphql-java/graphql-java#1581]
**Describe the bug**
Recent changes moved unboxing of possible optionals to a package scoped class and static method with no 'hook' for extension or overriding.

**To Reproduce**
Attempt to support another optional type other than java's Optional

It's possible to support extension without needing to use either reflection or adding third party dependencies. PR to address this is inbound.

**Comment by andimarek** [comment]
closing, because we now support custom unboxers.
