### ISSUE TITLE
Invalid queries are logged in clear text

### ISSUE THREAD

**Issue by pfstrack** [graphql-java/graphql-java#1585]
**Describe the bug**

Invalid queries are logged in clear text:

https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/GraphQL.java#L560

```
if (!errors.isEmpty()) {
    log.warn("Query failed to validate : '{}'", query);
    return new PreparsedDocumentEntry(errors);
}
```

This is a potential issue, because query may contain information that should not be logged (e.g. passwords, SSN, etc.). The query text should probably not be logged here.

**Comment by bbakerman** [comment]
I empathize with this problem.  At my company Atlassian, we have strong policies around never logging private information.

However many companies do not or do not have private information.  And a library that "just" works in that case if more powerful for them in debugging.

I think the best way to fix this is to create "well named" loggers for the private information.

That was you can use logging config to turn the private loggers to OFF

**Comment by pfstrack** [comment]
I would agree with custom loggers for better control of (potentially) sensitive logging. But the default behavior should be not to log. Or you should have some sort of prod vs. non-prod behavior.

The simple work around it to suppress the logging (which I’ve done). But imagine if there were a relational database whose default behavior was to dump all malformed queries to a log file. People would rightfully complain it’s a potential security hole.

The default message should be “query did not validate, turn on debug mode for more information” or something to that effect.

Granted, it’s not as bad as it could be, because only the query is logged, not the parameters, so well-behaved clients using parametrized queries are not at risk.

Anyway, it’s not a pressing issue for me because, as I’ve said, I just suppressed those particular log statements. But I tend to be paranoid about security risks and thought I should bring it to your attention :)

**Comment by bbakerman** [comment]
We will use a pattern like this

```
[main] WARN graphql.GraphQL_NotPrivacySafe - Query failed to validate : '
             fragment StoryDetail on Story {
                id
                text @defer
              }
              query {
                newsFeed {
                  stories {
                    text # @defer is missing
                    
                    # fragment
                    ...StoryDetail
                    
                    ## inline fragment
                    ... on Story {
                        id
                        text @defer 
                    }
                  }
                }
              }        
          '
```

people can then turn off `graphql.xxx.yyy_NotPrivacySafe` while stilling getting other logs

This strikes a balance between open by default and able to be locked down by those who want to.

**Comment by pfstrack** [comment]
Thank you. That’s definitely an improvement.

**Comment by pfstrack** [comment]
Sorry @bbakerman I had another thought. I think the pattern for your NotPrivacySafe logging should be: “NotPrivacySafe.%s” rather than “%s_NotPrivacySafe”.

Hierarchical logging means it’s easy to filter logs based on keys at the beginning of the logging name, but hard to do so at the end. The way it’s set up now, you will need a separate suppression for each class, and if the class names change or a new class gets a NotPrivacySafe log, the logging configuration will need to be updated.

If you make NotPrivacySafe the prefix, you can easily suppress all of them in a single config:

```<logger name="NotPrivacySafe" level="OFF"/>```

**Comment by bbakerman** [comment]
Good thinking

**Comment by bbakerman** [comment]
This has been done
