### ISSUE TITLE
In Execution#executeOperation()  ,which executionStrategy will be used to execute the request should get from ExecutionContext input parameter 

### ISSUE THREAD

**Issue by drupalspring** [graphql-java/graphql-java#1591]
In `Execution#executeOperation()` , I think which  `ExecutionStrategy` will be used should be get from the `ExecutionContext` input parameter rather than get from the internal `ExecutionStrategy` property . I am referring to the following codes in `Execution#executeOperation()`:

```
          ExecutionStrategy executionStrategy;
            if (operation == OperationDefinition.Operation.MUTATION) {
                executionStrategy = mutationStrategy;
            } else if (operation == SUBSCRIPTION) {
                executionStrategy = subscriptionStrategy;
            } else {
                executionStrategy = queryStrategy;
            }
            log.debug("Executing '{}' query operation: '{}' using '{}' execution strategy", executionContext.getExecutionId(), operation, executionStrategy.getClass().getName());
            result = executionStrategy.execute(executionContext, parameters);
```

I am thinking is it much more better to do in the following ways ?

```
  ExecutionStrategy executionStrategy;
            if (operation == OperationDefinition.Operation.MUTATION) {
                executionStrategy = executionContext.getMutationStrategy();
            } else if (operation == SUBSCRIPTION) {
                executionStrategy = executionContext.getSubscriptionStrategy();
            } else {
                executionStrategy = executionContext.getQueryStrategy();
            }
    result = executionStrategy.execute(executionContext, parameters);
```

So , it allows the use-case that if i change the `executionStrategy` in the `instrumentExecutionContext` which is just executed before `Execution#executeOperation()` , the changed executionStrategy can still take effect.

Also refer to https://spectrum.chat/graphql-java/general/logic-in-execution-executeoperation~4f3734a4-55fb-40c8-b766-3eb41d08aa15

**Comment by bbakerman** [comment]
I agree with this.  Would you care to present a PR to help us get this in place

**Comment by bbakerman** [comment]
Fixed
