### ISSUE TITLE
Add more documentation around Subscription implementation

### ISSUE THREAD

**Issue by kambojsourbh** [graphql-java/graphql-java#1593]
Hello

I recently worked on adding Subscription support in our java stack. I started with the documentation that is available on [graphql-java doc](https://www.graphql-java.com/documentation/v12/subscriptions/). From an understanding and starting point of view,   I found this doc is a good start but when I went into more deeper into this problem, I have to do a lot of research on many things which I think can be added into this subscription doc. 

- Bi-directional communication - We need a bi-directional communication for continuous message transfer between client and server. The documentation says 

> "graphql-java only produces a stream of results. It does not concern itself with sending these over the network on things like web sockets and so on.

Even though its not a concern but I see there are js  libraries e.g. [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws) which provides rich support for this bi-directional communication. 
It will be good if we can add more details on what are the some of the available option you can look for e.g. spring websockets(depends on spring DI), [Java API for websocket](https://docs.oracle.com/javaee/7/tutorial/websocket.htm), SSE (Server send events), HTTP2.0, AWS websocket etc.
There is one more thing which is more related to websockets are like how all sessions will be managed and how unsubscribe operation will close those session. 

- Pub-sub mechanism - When we need to scale subscription, we need a pub-sub system which can distribute message to different servers and can act like a single source of truth. There are couple of libraries for js like as mentioned [here](https://github.com/apollographql/graphql-subscriptions#pubsub-implementations) but currently I don't know if there is any for graphql-java. 
We should mention about this pub-sub requirement in the Subscription documentation. And also, it takes lot of efforts in determining which pub-sub technology(e.g. Redis, Kafka, EventBus etc) you should use so maybe some pointers around this as well will help developers. 

- Reactive-stream available implementation- graphql-java uses reactive streams to implement subscription. but reactive-streams are just interfaces/APIs and you need one particular implementation  of reactive stream. There are couple of implementation available for reactive stream like RxJava, Reactor, Akka streams etc and I also faced difficulty in getting comparison about these different implementations of reactive stream.  I think this can also go into the subscription doc. 

- What are different ways to trigger subscription? - Based on my experience, I found multiple ways to trigger a particular subscription. (Trigger I mean source streams for subscription).

1. We can create a new query from subscription request and with any updates through mutation, we can execute that query. (I have not tried this approach).
2. Mutation are used for updates so their data can also act as a source stream for Subscriptions
3. PubSub can also receive data from some external system(maybe some update API) which can also act as a trigger mechanism. 

- Integration with GraphQL IDEs(GraphiQL & Playground) - GraphQL IDEs are very good ways of testing the GraphQL APIs. But when it comes to subscription, there are some work required at these IDEs level as well as at server end. 

At the IDEs, we need to integrate it with [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws) as given [here](https://github.com/apollographql/subscriptions-transport-ws#use-it-with-graphiql). This will enable these IDEs to send subscription request using websocket connection. 

At server end, we need to configure the server so that it can handle all lifecycle types of subscription requests. [These are the protocols](https://github.com/apollographql/subscriptions-transport-ws#use-it-with-graphiql) which server has to handle to support subscription.  e.g. GQL_CONNECTION_INIT is sent from client for initialisation of connection and server will respond with GQL_CONNECTION_ACK or GQL_CONNECTION_ERROR based on whether the connection is established or not. 

These are some of the pointers which I experienced during the subscription implementation phase and I believe there are other people which would have faced some of these pointers or going to face. so I see this as an opportunity of adding these in the documentation. 

Thanks
Sourbh Kamboj

**Comment by kambojsourbh** [comment]
Hello GraphQL community, I would like to know your thoughts on improving documentation as mentioned in above subscription implementation pointers. I know it can also go into one blog but I have searched so many blogs to find small small things so that's why I am in the favour of having a single source of truth. Let me know your thoughts.

**Comment by brockgibson** [comment]
I'm all for more documentation and sharing experiences to make future development efforts simpler.

**Comment by bbakerman** [comment]
One of the design goals of graphql-java is to be a graphql engine only.  This means it can be used in the widest possible way.  We are used in servers, in embedded mobile clients, as Intellij graphql editor implementations....all because we aim for near zero dependencies and are not opinionated about result encoding and transport

Which is WHY we called this out.  We know you need to do more things and bidirectional communications is tricky - however we deliberately avoid this so that you can use whatever you like.

We also have not documented all these concerns because we just don't have the bandwidth.  Please feel free to create content out there that others can learn from.  We can even linked to it from out docs

**Comment by dondonz** [comment]
We always appreciate more documentation, feel free to open a PR https://github.com/graphql-java/graphql-java-page/pulls
