### ISSUE TITLE
if you throw an AbortExecutionException in an instrumentation then that kills the instrumentation chain

### ISSUE THREAD

**Issue by bbakerman** [graphql-java/graphql-java#1597]
Say in a beginExecute call you throw a new AbortExecutionExection

Today no more sensible Instrumentation calls will be made.  For example

`graphql.execution.instrumentation.Instrumentation#instrumentExecutionResult`

instead it short cuts out  and a standard result is returned.

But this means that "enhanced" results will not be produced.

eg in our Atlassian work we "enhance" all results with request ids etc and they wont get a chance to be set.

**Comment by andimarek** [comment]
@bbakerman this is probably related to https://github.com/graphql-java/graphql-java/issues/460
