### ISSUE TITLE
missing @deprecated directive when manually building GraphQLSchema

### ISSUE THREAD

**Issue by dkuc84** [graphql-java/graphql-java#1598]
**Describe the bug**
`@deprecated` directive is not available in the GraphQLSchema generated through the corresponding builder using `GraphQLSchema.newSchema()`. 

There are two problems:
* `GraphQLSchema.Builder` only adds `@skip` and `@include` directives [[link](https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/schema/GraphQLSchema.java#L291)]. As far as I can tell `@deprecated` directive is only added from `SchemaGenerator#makeExecutableSchema` [[link](https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/schema/idl/SchemaGenerator.java#L265)] that is dependent on loading the GraphQLSchema from a file.
* Adding deprecation reason to a field definition/enum value does not add `@deprecated` directive

**To Reproduce**
Please provide a code example or even better a test to reproduce the bug.

```groovy
def "deprecated directive test"() {
    given:
    def schemaBuilder = GraphQLSchema.newSchema()
    def deprecatedField = GraphQLFieldDefinition.newFieldDefinition()
            .name("deprecatedField")
            .deprecate("Custom deprecated message")
            .staticValue(123)
            .type(Scalars.GraphQLInt)

    def queryBuilder = GraphQLObjectType.newObject()
            .name("Query")
            .field(deprecatedField.build())

    schemaBuilder.query(queryBuilder.build())
    def schema = schemaBuilder.build()

    when:
    def result = new SchemaPrinter(defaultOptions().includeDirectives(true)).print(schema)

    then:
    result == '''type Query {
  deprecatedField: Int @deprecated(reason : "Custom deprecated message")
}
'''
}
```

**Comment by bbakerman** [comment]
The reason for the missing @deprecated directive is that it was "magic" in the graphql specification from the start.  

graphql-java copied the reference implementation with `type.deprecate("Custom deprecated message")`  

The assumption is that a graphql server implementation always handles an implicit @deprecated directive even if its not declared in SDL.

I say this only to explain where we came from (eg mentioned in spec - not required to be a directive) and not what we will or wont do in printing

> GraphQLSchema.Builder only adds @skip and @include directives [link]. As far as I can tell @deprecated directive is only added from SchemaGenerator#makeExecutableSchema [link] that is dependent on loading the GraphQLSchema from a file.

Remember there are SDL directives and query directives (ones that go on fields and arguments).  

The reason GraphQLSchema.Builder  only magically adds @skip and @include  is that they are query directives (not SDL ones) and hence @deprecated is not needed at query execution time

> Adding deprecation reason to a field definition/enum value does not add @deprecated directive

Yeah we could "synthesize" a directive from the setting of this boolean flag I guess.  Again this was done via magic code from very early times based on what grpaphql-js does.

**Comment by dkuc84** [comment]
Thanks for the details. Indeed `@deprecated` always seemed "special" compared to other directives (i.e. explicit deprecation reason fields). 

Since there is a different behavior depending on whether you load schema from a file vs manually constructing it I'd assume you would like to keep it consistent. Our "fix" was to explicitly add the `@deprecated` directive when processing deprecation reason ([[link](https://github.com/ExpediaDotCom/graphql-kotlin/blob/master/src/main/kotlin/com/expedia/graphql/generator/types/FunctionBuilder.kt#L38)].
