### ISSUE TITLE
Invalid cache handling since #1483

### ISSUE THREAD

**Issue by dirkkolb** [graphql-java/graphql-java#1606]
I was wondering why my cache was filled up with elements but without any hit. I debugged the implementation and realized that the complete ExecutionInput with its randomized Id and variables is stored in the cache. If this is true, it is obvious that there is no hit. The hashCode() method of ExecutionInput considers all elements of the object resulting always in different hash values even if the query is identical.

Before #1483, only the query was stored in the cache.

**Comment by bbakerman** [comment]
You are not required to store the ExecutionInput object but rather use to to generate  a "cache key" that suits your needs.  Previously just the query text was provided but it became clear that some people needed more "data" to make a caching decision, so we provided the whole ExecutionInput in later versions.

As you noted this is not a great cache key.  You need to invent your own.  It might be just `execitionInput.getQuery()` or it might be more complex.

**Comment by bbakerman** [comment]
I am going to close this issue.  It was a breaking change in what is sent but one should only put attributes into a cache that one knows is cacheable.
