### ISSUE TITLE
graphql-java fails to resolve static (nested) classes as in JAXB

### ISSUE THREAD

**Issue by pverdoorn** [graphql-java/graphql-java#1611]
I'm trying to map a JAXB model,  the result of a call to a soap service,  to a GraphQL model.
Unfortunately this fails when a nested property resides in an inner static class.  Is this a familiar problem?  Am i doing something wrong?

**Comment by bbakerman** [comment]
I cant say its a familair problem, its not been reported that I know of

The most basic fetcher in graphql-java is PropertyFetcher - which will look at an object and try to find values by field name.

eg if the field is called `name` it will try to do the following

* if the object is a map then it does map.get('name')
* otherwise it tries POJO getters (getName()) etc.. via reflection

I am not sure of the structure of your POJO types.  Could you give an example?

**Comment by pverdoorn** [comment]
Hi Brian, 

Thanks for your response.  I will try to summarize.  

I’m dealing with set of classed generated by JAXB. They look like this

Public Class A{
	….
	 public List<ClassA.ClassB> getClassB()	

	private static final Class B	{
	…
	public List<ClassA.ClassB.ClassC> getClassC()   
	}

	private static final Class C	{
	…etc…. 
	}
} 

The error I get is the following:  
ClassA.ClassB.ClassC  cannot be mapped to a GraphQL type!  Since GraphQL-Java deals with erased types at runtime, only non-parameterized classes can represent a GraphQL type.  This allows for reverse-lookup by java class in interfaces and union types.

My guess is that this means that GraphQl can’t deal with nested classes like this.

**Comment by bbakerman** [comment]
> ClassA.ClassB.ClassC cannot be mapped to a GraphQL type! Since GraphQL-Java deals with erased types at runtime, only non-parameterized classes can represent a GraphQL type. This allows for reverse-lookup by java class in interfaces and union types.

I dont think this error message is being generated by any graphql-java code.

It might be in some graphql-java wrapper library say but its not graphql-java

**Comment by lqc** [comment]
@pverdoorn I seen this type of error when using graphql-java-tools (e.g. graphql-java-kickstart/graphql-java-tools#114), but generic support was reworked there some time ago and this error message is not even in the code base now. You should try upgrading.

**Comment by bbakerman** [comment]
I am going to close this as not a graphql-java problem
