### ISSUE TITLE
Cache the query complexities to optimize complexity calculation

### ISSUE THREAD

**Issue by prabhatcraz** [graphql-java/graphql-java#1621]
graphq-java could retain query complexity calculations in memory.

Advantages:
- In general, same queries would be sent to the server over and over again and it would be waste of resources to do such calculation for high pressure systems.
- It would also enable rejecting queries which are too big to process, even before resolution starts, again benefitting the hight pressure systems.

Additional options:
- User should be able enable and disable caching while instantiating the `MaxQueryComplexityInstrumentation` class.
- Key of the cache could be hash of the query string. (Not sure if this the best way)
- User should be able to put a max limit on cache size. cache eviction policy could also be a parameter.

**Comment by bbakerman** [comment]
graphql-java has a simple call back mechanism to cache queries.

`graphql.execution.preparsed.PreparsedDocumentProvider`

We don't have a way to cache query complexity and I would be wary of building one.   Caching is alm osty always a code base very specific thing.  Its very hard to produce library code that can cache smartly.

I think you would be better to create your own QueryComplexity instrumentation that had all the caching / cache invalidation specifics that suit your app.

**Comment by prabhatcraz** [comment]
Thanks for the reply, just one more thought before we close this. For most of the application, scale of queries is well within a reasonable size and creating an in-memory cache would help a lot. Caching could be an optional feature :)

**Comment by andimarek** [comment]
closing this now: @prabhatcraz you are right, that an in memory cache as optional feature would be helpful. The general challenge we have is: 
1. we can't add external dependencies for having a cache (like guava or caffeine)
2. adding any new feature means we need to support it
