### ISSUE TITLE
SchemaPrinter includes all the arguments even if some of them has no value set

### ISSUE THREAD

**Issue by saponniah** [graphql-java/graphql-java#1623]
**Describe the bug**
[SchemaPrinter](https://github.com/graphql-java/graphql-java/blob/2e1e9897030f61a6e9a2c2eba358fd87da1d20d0/src/main/java/graphql/schema/idl/SchemaPrinter.java) while printing the directives, prints just the argument name if an argument value is not provided for that argument.

**To Reproduce**
For example, let's say there is a directive defined like this with two arguments - a required argument `namespace` and an optional argument `name`,

`directive @schema(namespace: String!, name: String) on OBJECT`

Let's say on a generated OBJECT type we only specify the value for argument `namespace` and in that case, the `SchemaPrinter` should not include the argument `name` while printing the schema. But this is how it looks like in the printed schema,

`
type Person @schema(namespace: "foo", name) {
  ...
}
`

**Comment by bbakerman** [comment]
Yup feels like a bug.  We are always happy to accept PRs to help fix problems

**Comment by vickeyyeh** [comment]
@bbakerman, SchemaPrinterComparatorsTest.groovy is expecting the directive arguments with no values like this:

interface TypeA @a(a, bb) @bb(a, bb) {
  a(a: Int, bb: Int): String @a(a, bb) @bb(a, bb)
  bb(a: Int, bb: Int): String @a(a, bb) @bb(a, bb)
}

All the tests with directive are written this way. Are these tests wrong?

**Comment by bbakerman** [comment]
Yes they are invalid

**Comment by bbakerman** [comment]
Fixed
