### ISSUE TITLE
String scalar coercion seems wrong

### ISSUE THREAD

**Issue by fforw** [graphql-java/graphql-java#1627]
As the code currently is (https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/Scalars.java#L181-L188), String scalar values are just silently converted with toString() if they're not Strings, which seems wrong in both directions.
For `serialize` it should always be a String and it not being a String seems like an illegal internal state.

Even worse for `parseValue`, graphql-java just accepts erroneous data. A number is a number, a String is a String etc pp.

**Comment by fforw** [comment]
Not to mention that a toString conversion is of course only correct for a limited number of scalar value types. For other types you might just get a "MyType@4o7c0ffe".

**Comment by bbakerman** [comment]
We could tighten this.

The reference graphql-js code base does this

```
function serializeString(rawValue: mixed): string {
  const value = serializeObject(rawValue);

  // Serialize string, boolean and number values to a string, but do not
  // attempt to coerce object, function, symbol, or other types as strings.
  if (typeof value === 'string') {
    return value;
  }
  if (typeof value === 'boolean') {
    return value ? 'true' : 'false';
  }
  if (isFinite(value)) {
    return value.toString();
  }
  throw new TypeError(`String cannot represent value: ${inspect(rawValue)}`);
}
```

That is booleans, finite numbers and strings and nothing else

The coerce is even more strict

```
function coerceString(value: mixed): string {
  if (typeof value !== 'string') {
    throw new TypeError(
      `String cannot represent a non string value: ${inspect(value)}`,
    );
  }
  return value;
}
```

That is strings only.

I like the idea that we tighten this up (this is very old code) and follow the reference implementation in spirit.

The drawback would be we might break any one relying on loose behavior.  eg StringBuffers would magically work today

@andimarek - thoughts on tightening this up to graphql-js inspired levels

**Comment by arlampin** [comment]
graphql-js's inline comment is actually wrong, it also serializes various object types by calling `serializeObject` first, namely those that have `valueOf` or `toJSON` functions.

**Comment by bbakerman** [comment]
Thanks @arlampin - your right.

So the reference implementation takes just about ANY object in JS terms and calls a sort of `toString` on it and then that's the value.

So I am loathe to say the graphql-java MUST only accept Strings and nothing else.
