### ISSUE TITLE
Local context is not inherited to grandchildren DataFetchers

### ISSUE THREAD

**Issue by michael-fl** [graphql-java/graphql-java#1635]
When returning a local context from a resolver (DataFetcher) using

```
DataFetcherResult.newResult().data(result).localContext(context);
```

that local context is forwarded to the resolvers of the *direct* child fields - fine!

However, the context is not forwarded to any resolvers of fields nested deeper below. To do so, one has to wrap it explicitly again and again using above's pattern in all the child resolvers.

I'm not sure if this is a bug or a missing feature. However, in my opinion this makes the local context almost useless. When setting a context information, it should be available for all the fields of the remaining sub-tree.

I'd like to request this behavior as a feature.

**Comment by bbakerman** [comment]
Its a bug if thats the case.  It is meant to be passed down to grand children and so on if not set.

Looking at the code it intends to do this

```
            Object localContext = dataFetcherResult.getLocalContext();
            if (localContext == null) {
                // if the field returns nothing then they get the context of their parent field
                localContext = parameters.getLocalContext();
            }
```

But I cant find a test that explicitly tests this (passing across field levels) to prove this.

So definitely a bug

**Comment by JaidenAshmore** [comment]
Hey @michael-fl could you confirm that the scenario that you are describing is represented by this test that I just created? https://github.com/graphql-java/graphql-java/pull/1646

The test is passing so I am wondering if I have misinterpreted the problem you are having.

**Comment by bbakerman** [comment]
@michael-fl - We are going to close this issue as we are pretty sure it works,

if you have more evidence that we can re-open it
