### ISSUE TITLE
RxJava on DataFetcher

### ISSUE THREAD

**Issue by evilmonster18** [graphql-java/graphql-java#1636]
Hi everyone, I have been experimenting with GraphQL Java and know that it currently supports asynchronous execution of `DataFetcher` through both Java's `Future` and `CompletionStage`. I also tried to use RxJava's `Single` and `Observable`, but without success. Can you tell me if these are currently supported? What about Reactor's `Mono` and `Flux`?

**Comment by bbakerman** [comment]
> ava and know that it currently supports asynchronous execution of DataFetcher through both Java's Future and CompletionStage

Actually its ONLY via CompletionStage - you cant return a future from a data fetcher - graphql-java will not understand it


As for RXJava / WebFlux support - we dont have native support for understanding RxJava / WebFlux apis.  

However both libraries offer a `toCompleteableFuture()` kinda of API

https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Mono.html#toFuture--

That is you convert the reattive value into a CompleteFuture.  Its asynchronous and keeps the same runtime semantics as you want in a reactive system.

We run a series of WebFlux based graphql-java system here at my employer Atlassian.  It works fine in async terms

One thing you WILL lose however is magic things like SubscriberContext.

https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Mono.html#subscriberContext--

SubscriberContext requires all code stay inside a Mono chain (they use Mono hooks to propogate the context) and hence the toFuture call breaks that.

graphql-java has a "context" object to hold such things but you need to code that in - you wont get Mono magic

**Comment by bbakerman** [comment]
Closed as answered
