### ISSUE TITLE
graphql.validation.Validator does not validate that fields in an Operation exist

### ISSUE THREAD

**Issue by realityforge** [graphql-java/graphql-java#1642]
The following schema and document are not flagged as invalid by `graphql.validation.Validator` when they should be.

Schema:

```graphql
schema {query: Query}
type Query {
  person: Person
}
type Person {name: String}
```

Document: 
```graphql
mutation personQuery {
  person {
    name
  }
}
```

It should generate an error with code similar to:

```java
String message = String.format( "Field '%s' of type '%s' is undefined", field.getName(), topLevelFieldName );
errors.add( new ValidationError( ValidationErrorType.FieldUndefined, field.getSourceLocation(), message ) );
```

which would produce an error like:

> Validation error of type FieldUndefined: Field 'person' of type 'Mutation' is undefined

It looks like only minor changes to the Rules would be required to support this.

**Comment by simeonleatherland** [comment]
Hey Hey! Thanks for submitting an issue, I reproduced this and received this `Schema is not configured for mutations.` as expected. Could you provide some more details on what you are receiving on your end when you try the mutation?

**Comment by andimarek** [comment]
Hi @realityforge ... closing this issue now: please reopen it if this is still a problem.

**Comment by realityforge** [comment]
Finally got back to this to test and all fixed in v14. Thanks!

**Comment by andimarek** [comment]
thanks for confirming @realityforge
