### ISSUE TITLE
Relay: mutationWithClientMutationId

### ISSUE THREAD

**Issue by dminkovsky** [graphql-java/graphql-java#165]
I just made my own implementation of `Relay#mutationWithClientMutationId()` before noticing that the method exists in this package. My implementation is identical with one exception. Shouldn't [line 190](https://github.com/graphql-java/graphql-java/blob/2ab1b6a3c28bca930715c245499dacaee44bf22a/src/main/java/graphql/relay/Relay.java#L190), which is currently 

```
.dataFetcher(dataFetcher)
```

instead wrap the user-provided `DataFetcher` and place the `clientMutationId` from input into the result? Like so:

```
.dataFetcher(env -> {
    Map<String, Object> data = (Map<String, Object>) dataFetcher.get(env);
    data.put("clientMutationId", ((Map<String, Object>) env.getArguments().get("input")).get("clientMutationId"));
    return data;
})
```

Without this, how does this field makes its way from input to output and get resolved downstream? Granted, I haven't tried the current implementation but I don't know how it would work...

**Comment by ntkoopman** [comment]
You would implement this in every dataFetcher you pass to mutationWithClientMutationId or create a subclass. Your code will fail if the dataFetcher returns something other than a Map.

**Comment by dminkovsky** [comment]
@ntkoopman yeah you're right:

> Your code will fail if the dataFetcher returns something other than a Map.

That is unacceptable. Will close this.
