### ISSUE TITLE
CompleteableFuture that completes exceptionally with a custom exception which implements GraphQLError is not becoming an graphql error

### ISSUE THREAD

**Issue by bbakerman** [graphql-java/graphql-java#1652]
From spectrum : https://spectrum.chat/graphql-java/general/graphql-java-13-0-unable-to-get-extensions-from-async-data-fetcher-exceptions~f0752fa2-aa88-49ee-98ac-a56f1c2b64fa

Hi - i am using graphql-java 13.0 and one of my async data fetchers returns a CompletableFuture which is completed exceptionally with a custom exception which implements GraphQLError and extends RuntimeException.
eg:- preProcessRequest function in below data fetcher throws the above custom exception

```
   @Override
    public CompletionStage<T> get(final DataFetchingEnvironment environment) {
        return CompletableFuture.completedFuture(null)
                .thenCompose(v -> preProcessRequest(environment))
                .thenCompose(v -> executeRequest(environment))
                .exceptionally(throwable -> {
                    LOG.info("GraphQL Query failed {}", throwable);
                    final Throwable t = ThrowableUtils.unwrapIfExecutionOrCompletionException(throwable);
                    throw ThrowableUtils.ensureRuntime(t);
                });
    }
```

However, i am unable to get extensions from the error.
When executing this code in ExecutionStrategy.java:

```
return fetchedValue
                .handle((result, exception) -> {
                    fetchCtx.onCompleted(result, exception);
                    if (exception != null) {
                        handleFetchingException(executionContext, parameters, environment, exception);
                        return null;
                    } else {
                        return result;
                    }
                })
                .thenApply(result -> unboxPossibleDataFetcherResult(executionContext, parameters, result));
```

the exception object is of type CompletionException instead of the underlying GraphQLError and hence error extensions are null. This used to work with v12.0 and i am unsure if i changed something or the version upgrade broke it. Is this a known issue?

**Comment by oliemansm** [comment]
This seems to happen for all exceptions thrown like this, not just the ones implementing `GraphQLError`. See also failing test in this sample project: https://github.com/oefimov/graphql-java-servlet-250. Any idea when this issue is going to be addressed?

**Comment by roschlau** [comment]
We just stumbled over this problem in 2021 - a little disheartening to see that there's basically no reaction to this at all. We've built ourselves a little custom error handler that checks any exception thrown by a data fetcher if it's a CompletionException and unwraps its cause if it is, so extensions from our custom GraphqlError classes are properly passed on.

I'd probably be able to draft a PR for this integrating the unwrapping logic into the library, but I have not idea if that is actually generally applicable solution or if there are pitfalls that make it unsuitable for being the default behavior, so would like some input on this from the maintainers, if possible.

**Comment by bbakerman** [comment]
> We just stumbled over this problem in 2021 - a little disheartening to see that there's basically no reaction to this at all so far...

We can look into this but guilting us into it is probably  not the way to do it.

A PR is worth a 1000 guilt trips

**Comment by bbakerman** [comment]
(Or maybe a guilt trip does work)

**Comment by roschlau** [comment]
@bbakerman Sorry, you're right that wasn't a professional comment, I apologize for that!
I commented here first and didn't start with a PR because I wasn't really sure if just generally unwrapping CompletionExceptions was the right way to go, or if there were other concerns at play. Would you rather have a seen a PR in that case nonetheless, to discuss on the proposed changes directly?

I very much appreciate what you're doing here, and appreciate the work to fix this issue. The linked PR looks exactly like what I was thinking about!
