### ISSUE TITLE
BatchLoader.load(keys) function receives duplicate keys when caching is disabled

### ISSUE THREAD

**Issue by josh00007777** [graphql-java/graphql-java#1656]
Hi,

I am using dataloader in my application to load the data, there is single dataloader "personLoader" which loads data for Person object for this schema:

Schema:

```
type Query{
 listPersons:[Person]
}
type Person{
 name:String
 id:String
 bestFriend:Person
 friends:[Person]
}
```

In my application :
1. There is a resolver "listPersonsResolver" for Query operation field "listPersons". This invoke personLoader.loadMany([1,2,3,4,5])
2. A resolver "bestFriendResolver" to resolve Person/bestFriend field. This invoke personLoader.load(bestFriendId)
3. A resolver "friendsResolver" to resolve Person/friends field. This invoke personLoader.loadMany([friendsID])

I am facing 2 issues :
Issue 1 -- When batching(batchSize = -1) and caching both are enabled and I execute the query (attached), the batch loader gets called to load data for Persons = [1,2,3,4,5] twise, once for the root field(listPersons) and once for the child fields (all other fields) with ids =[1,2,3,4,5] . As I have enabled the caching and using same dataloader to load the Person's data so my expectation is that once the loader is invokded for root field "listPersons" and it has loaded all 5 Persons, so the second call should not be there to load (child data) the Persons=[1,2,3,4,5] again (because these are already loaded).

Issue 2 --  When batching(batchSize = -1) is enabled, but caching is disabled and I execute the query (attached), There will multiple calls to batch loader to load the Persons data again and again (as caching is disabled to it is expected), but in my case I am getting duplicate keys as input to BatchLoader.load(keys) function, in one case the input to this function is [1,2,4,2,3,1..] total 19 keys in input, with many duplicate entries. The batchloader should get unique keys to load the data.

I am using :
		'graphql-java:9.4.0',
		'java-dataloader:2.0.2'

Query: 

```
{
  listPersons {
    name
    bestFriend {
      name
      bestFriend {
        name
         bestFriend {
          name
        }
        friends {
          name
          bestFriend {
            name
            bestFriend {
              name
               bestFriend {
                name
              }
              friends {
                name
              }
            }
          }
        }
      }
    }
  }
}
```

Data :

```
users : [
	{id: "1", name: "user1", bestFriend : {id: "2"}, friends:[{id: "2"}, {id: "3"}, {id: "4"}, {id: "5"}]}
	{id: "2", name: "user2", bestFriend : {id: "3"}, friends:[{id: "3"}, {id: "4"}, {id: "5"}, {id: "1"}]}
	{id: "3", name: "user3", bestFriend : {id: "4"}, friends:[{id: "4"}, {id: "5"}, {id: "1"}, {id: "2"}]}
	{id: "4", name: "user4", bestFriend : {id: "5"}, friends:[{id: "5"}, {id: "1"}, {id: "2"}, {id: "3"}]}
	{id: "5", name: "user5", bestFriend : {id: "1"}, friends:[{id: "1"}, {id: "2"}, {id: "3"}, {id: "4"}]}
]
```

**Comment by bbakerman** [comment]
Let me address Issue 2 first-

The basic DataLoader is a list and not a set.  Therefore it you load 1,2,3,1,2 as a series of loads and there is no caching, it presents a value for each load call


```
   @Test
    public void example() {
        List<Collection<Integer>> loadCalls = new ArrayList<>();
        DataLoaderOptions options = DataLoaderOptions.newOptions().setCachingEnabled(false);
        DataLoader<Integer, Integer> identityLoader = idLoader(options, loadCalls);

        identityLoader.load(1);
        identityLoader.load(2);
        identityLoader.load(3);
        identityLoader.load(1);
        identityLoader.load(2);

        identityLoader.dispatch();

        System.out.println("This is what happens");
        System.out.println(loadCalls);
    }

```

produces

```
This is what happens
[[1, 2, 3, 1, 2]]
```

As for Issue 1 : 

>As I have enabled the caching and using same dataloader to load the Person's data so my expectation is that once the loader is invokded for root field "listPersons" and it has loaded all 5 Persons, so the second call should not be there to load (child data) the Persons=[1,2,3,4,5] again (because these are already loaded).

This would be my expectation as well.  In fact we have extensive tests for this in

https://github.com/graphql-java/java-dataloader

So I am pretty confident it works.

What are your keys and do they have proper hashCode / equals?  Do you have a custom cache for example??

**Comment by josh00007777** [comment]
Thanks for explaining Issue-2(actually not issue, but I was expecting diff behaviour), I will take care internally to handle duplicate keys.

For Issue - 1, I dont have any custom cache, it is using internal cache from graphql-java, The key implements equals() & hashcode(), otherwise batchloader would have been invoked multiple times to load the data for keys [1,2,3,4,5], but it is getting invoked only twice.

**Comment by bbakerman** [comment]
I am really confident in data loader working properly.  But of course no code is 100% perfecy

I think we need a failing unit test showing Issue 1) not working and calling things twice
