### ISSUE TITLE
Make PropertyDataFetcher more reusable

### ISSUE THREAD

**Issue by Thisen** [graphql-java/graphql-java#1663]
I want to propose a non-breaking change to `PropertyDataFetcher` to make it more reusable, if you need custom logic to get the correct environment source.

I suggest adding a `getSource()` method for fetching the source:

```java
protected Object getSource(DataFetchingEnvironment environment) {
    return environment.getSource();
}
```

Which is used by `get()` like such:

```java
public T get(DataFetchingEnvironment environment) {
        Object source = getSource(environment);
        if (source == null) {
            return null;
        }
        ... // the rest
}
```
Now the consumer would be able to extend `PropertyDataFetcher` and write custom logic for retrieving the correct source.

What do you think? 😁

**Comment by andimarek** [comment]
Hi @Thisen ..... can you give us a bit more background?
`PropertyDataFetcher` was not intended to be subclassed. What is your use case for doing it? If you need a custom PropertyDataFetcher you can instantiate one and use it.

**Comment by Thisen** [comment]
My use case is a dynamic API, where the getters for the fields of an object type is behind a common interface.

Example:

```
Plugin Plugin = environment.getSource();
plugin.getParameters(); // this returns the object with getters! 
```

Which returns an object with getters for the fields. 

Therefore I need all the capabilities of `CustomDataFetcher`, just slighty different logic for getting the source.

**Comment by bbakerman** [comment]
PropertyDataDetcher makes the eminently sensible idea that the "source" of property is the source in the `DataFetchingEnvironment`

You can create your own custom fetchers by simple creating a wrapper `DataFetchingEnvironment` where the source is the one you want.  Then delegate to (eg compose not inherit) a PropertyDataFetcher with this

```
   class CustomDataFetcher implements DataFetcher {

        PropertyDataFetcher delegate;

        @Override
        public Object get(DataFetchingEnvironment environment) throws Exception {
            Plugin plugin = environment.getSource();
            environment  = wrap(environment, plugin.getParameters());
            return delegate.get(environment);
        }

        private DataFetchingEnvironment wrap(DataFetchingEnvironment delegate, Object newSource) {
            return new DataFetchingEnvironment() {
                @Override
                public <T> T getSource() {
                    return (T) newSource;
                }

                @Override
                public Map<String, Object> getArguments() {
                    return delegate.getArguments();
                }

                @Override
                public boolean containsArgument(String name) {
                    return delegate.containsArgument(name);
                }
```

**Comment by Thisen** [comment]
@bbakerman solved my issue, but I find that solution verbose.

I still suggest making a more extendable DataFetcher, but if that doesn't fit your architecture, then you are free to close the issue.

**Comment by bbakerman** [comment]
The PR mentioned above would allow

```
class CustomDataFetcher implements DataFetcher {

        PropertyDataFetcher delegate;

        @Override
        public Object get(DataFetchingEnvironment environment) throws Exception {
            Plugin plugin = environment.getSource();
            environment  = wrap(environment, plugin.getParameters());
            return delegate.get(environment);
        }

        private DataFetchingEnvironment wrap(DataFetchingEnvironment delegate, Object newSource) {
            return new DelegatingDataFetchingEnvironment(delegate) {
                @Override
                public <T> T getSource() {
                    return (T) newSource;
                }
      };
}


```
