### ISSUE TITLE
Can we make field selection in the output of mutations optional?

### ISSUE THREAD

**Issue by phuongphally** [graphql-java/graphql-java#1673]
Can we make result output optional or required some fields

We do something like

`mutation { UpdateUser ( ... ) }`
Or 
`mutation { UpdateUser ( ... ) { id } }`

**Comment by lqc** [comment]
That would be against the spec https://graphql.github.io/graphql-spec/June2018/#sec-Language.Operations

**Comment by phuongphally** [comment]
@iqc Thanks for the response . 

My use case that , I have `Update User` `Muration` call `UpdateUser( input:  {...} )`  

And all the time I need to  write with full syntax like 

`UpdateUser(input:{.....}){....}`

``` javascript mutation{
  UpdateAppUser(input: {
    firstName:"firstName",
    lastName:"lastName",
  }){
    id,
    firstName,
    lastName
  }
}

```

The question is optional output should be 

```javascript

UpdateUser(input:{.....}){....}

```

Or 

```javascript

UpdateUser(input:{.....})

```

**Comment by bbakerman** [comment]
> Can we make field selection in the output of mutations optional?

No because the graphql spec says the object types MUST always have a selection set (one or more fields) and thats how the spec works.

```
SelectionSet
{Selectionlist}
Selection
Field
FragmentSpread
InlineFragment
```

https://graphql.github.io/graphql-spec/June2018/#SelectionSet
