### ISSUE TITLE
NonNullableFieldWasNullError encountered even when the given field is not null

### ISSUE THREAD

**Issue by ashera96** [graphql-java/graphql-java#1674]
Given below is the java code which was used to calculate the complexity of a given query using the MaxQueryComplexityInstrumentation.
```
private boolean queryComplexityAnalysis(String payload) {
    MaxQueryComplexityInstrumentation maxQueryComplexityInstrumentation = new MaxQueryComplexityInstrumentation(10);

    GraphQL runtime = GraphQL.newGraphQL(schema)
            .instrumentation(maxQueryComplexityInstrumentation)
            .build();
    try {
        ExecutionResult execution = runtime.execute(payload);
        List<GraphQLError> errors = execution.getErrors();
        if (errors.size()>0) {
            for(GraphQLError temp : errors) {
                log.error(temp);
            }
            return false;
        }
        System.out.println("Maximum query complexity was not exceeded");
        return true;
    } catch (Throwable e) {
        log.error(e);
    }
    return false;
}
```

The backend which I'm using is "[https://graphql-pokemon.now.sh/](https://graphql-pokemon.now.sh/)". Conisder the 2 scenarios which are listed below:

 1.   Let the payload be {pokemon(name: "Pikachu"){ evolutions{weight {minimum} attacks{fast{name}}} }}. Once this is passed, I successfully get the response "Maximum query complexity was not exceeded"
  2.  Let the payload be {pokemon(name: "Pikachu"){id evolutions{weight {minimum} attacks{fast{name}}} }}. Once this is passed, I get an error message like given below, "NonNullableFieldWasNullError{message='Cannot return null for non-nullable type: 'ID' within parent 'Pokemon' (/pokemon/id)', path=[pokemon, id]}"

They only difference here is that in the schema the id field is required, but the others aren't. Part of the schema is given below. Once this id is removed from the query the code seems to work fine, otherwise, NonNullableFieldWasNullError is thrown (it is clear that the above-said field is not empty). Any help is appreciated.

![post](https://user-images.githubusercontent.com/30475839/67006388-a7442380-f102-11e9-9703-ea41dac20af0.png)

The full schema file can be found [here](https://github.com/lucasbento/graphql-pokemon/blob/master/schemas/schema.graphql)

**Comment by bbakerman** [comment]
Answered in spectrum chat
