### ISSUE TITLE
Passing down DataFetchingEnvironmentImpl into an @Aspect

### ISSUE THREAD

**Issue by adamelkhayyat** [graphql-java/graphql-java#1675]
<small>* Code is linked at the end of the post.</small>

Hey, I am fairly new to spring-boot and especially new to graphql-java. I have a question regarding authentication, I use mi3o's way of authenticating my graphQL resolves (find the basic code here: https://mi3o.com/spring-graphql-security/). 

I am facing an issue with my class `SecurityGraphQLAspect`. I can not seem to be able to extract the`DataFetchingEnvironmentImpl` object from the `JoinPoint` param in the method `doSecurityCheck(...)`. My intention of getting the`DataFetchingEnvironmentImpl` object is to access the headers and grab the data from there for authentication.

```
@Aspect
@Component
@Order(1)
class SecurityGraphQLAspect {

    @Autowired
    private val jwtTokenUtil: JwtTokenUtil? = null

    /**
     * All graphQLResolver methods can be called only by authenticated user.
     * @Unsecured annotated methods are excluded
     */
    @Before("allGraphQLResolverMethods() && isDefinedInApplication() && !isMethodAnnotatedAsUnsecured()")
    fun doSecurityCheck(jp: JoinPoint) {
        // Every resolve from GraphQL that does not have the @Unsecured annotation gets passed through here first.

        jp.args.forEach { e ->
                if (e is DataFetchingEnvironmentImpl) {   // Currently never gets into there, as DataFetchingEnvironmentImpl obj is never passed down to here.
                    val context = e.getContext() as GraphQLContext
                    val token = context.request.get().getHeader("Authorization");
                    val email = context.request.get().getHeader("UserEmail")
                    if (!(jwtTokenUtil!!.validateToken(token, email)!!)) {
                                    throw AccessDeniedException("User not authenticated")
                    }
            }
         }
    }

    /**
     * Matches all beans that implement [com.coxautodev.graphql.tools.GraphQLResolver]
     * note: `GraphQLMutationResolver`, `GraphQLQueryResolver` etc
     * extend base GraphQLResolver interface
     */
    @Pointcut("target(com.coxautodev.graphql.tools.GraphQLResolver)")
    private fun allGraphQLResolverMethods() {
    }
    /**
     * Matches all beans in com.mi3o.springgraphqlsecurity package
     * resolvers must be in this package (subpackages)
     */
    @Pointcut("within(com.example.assignment4..*)")
    private fun isDefinedInApplication() {
    }

    /**
     * Any method annotated with @Unsecured
     */
    @Pointcut("@annotation(com.example.assignment4.security.Unsecured)")
    private fun isMethodAnnotatedAsUnsecured() {
    }
}

```

For some reference, check out the resolves and how authentication is being done there right now (not ideal at all). I can pass `DataFetchingEnvironment` and access the headers via the `DataFetchingEnvironmentImpl` obj in the resolve to do the authentication but I'd rather do it at one place and in a consistent manner (so, having all the authentication logic in `doSecurityCheck(...)` method above).

Example:
```
@Component
class InterestMutation : GraphQLMutationResolver {

    @Autowired
    private val interestService: InterestService? = null

    fun addInterest(user: Int, tag: Int, env: DataFetchingEnvironment): Interest {
        Security().authenticate(env)     // temp solution, needs changing
        return this.interestService!!.addInterest(user, tag)
    }
}
```

I know that this is possible but I am not sure on how to pass that information (via JoinPoint) down to `SecurityGraphQLAspect`. Any advice or help is serious appreciated, thanks!

Entire code repo: https://github.com/adamelkhayyat/graphql-springboot/tree/master/13-develop%202

**Comment by bbakerman** [comment]
GraphQLMutationResolver comes from graphql-java-tools

https://github.com/graphql-java-kickstart/graphql-java-tools

The use graphql-java under the covers however how they pass in context is in their code and you will need to ask there.

**Comment by adamelkhayyat** [comment]
Thanks for pointing me in the right direction @bbakerman, closing this now.
