### ISSUE TITLE
ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer when using Relay/SimpleListConnection

### ISSUE THREAD

**Issue by mxmlnglt** [graphql-java/graphql-java#1680]
**Describe the bug**
When I try to benefit from the default value set for the argument "first" - as used in the [`SimpleListConnection`](../blob/master/src/main/java/graphql/relay/SimpleListConnection.java#L69) - the execution of my request fails with a `ClassCastException`.

**To Reproduce**
My schema:
```
schema {
  query: Query
}
type Query {
  companies(first: Int = 10, after: String): CompanyConnection @connection(for: "Company")
}
type Company {
  id: ID
  name: String
}
```
My Java classes:
```
public class Company {
	private int id;
	private String name;
}

@Component /* Spring annotation */
public class Query implements GraphQLQueryResolver /* GraphQL Java Tools interface */ {

	public Connection<Company> companies(int first, String after, DataFetchingEnvironment environment) {
		return new SimpleListConnection<Company>(companies(environment)).get(environment);
	}

	private List<Company> companies(DataFetchingEnvironment environment) {
		return Arrays.asList(new Company(1, "first"), new Company(2, "second"), new Company(3, "third"), new Company(4, "fourth")); 
	}

}
```
Note : I'm in a context with Spring Boot (`spring-boot-starter-parent:2.1.8.RELEASE`) and GraphQL Java Tools (`graphql-spring-boot-starter:5.10.0` / `graphql-java-tools:5.6.1` which includes `graphql-java:13.0`).

GraphQL Java Tools auto-generates the schema from my `.graphqls` file, the Relay-related objects (use of the `@connection` directive; see https://www.graphql-java-kickstart.com/tools/relay/ ) + links the GraphQL `Query` to my Java `Query` class through the interface `GraphQLQueryResolver`.

WHAT WORKS: (1st case)
```
{
  companies(first: 2, after: "c2ltcGxlLWN1cnNvcjE=") {
    edges {
      cursor
      node {
        id
        name
      }
    }
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
  }
}
```
returns:
```
{
  "data": {
    "companies": {
      "edges": [
        {
          "cursor": "c2ltcGxlLWN1cnNvcjI=",
          "node": {
            "id": "3",
            "name": "third"
          }
        },
        {
          "cursor": "c2ltcGxlLWN1cnNvcjM=",
          "node": {
            "id": "4",
            "name": "fourth"
          }
        }
      ],
      "pageInfo": {
        "hasPreviousPage": true,
        "hasNextPage": false,
        "startCursor": "c2ltcGxlLWN1cnNvcjI=",
        "endCursor": "c2ltcGxlLWN1cnNvcjM="
      }
    }
  }
}
```
WHILE THIS DOESN'T: (2nd case)
```
{
  companies(after: "c2ltcGxlLWN1cnNvcjE=") {
    edges {
      cursor
      node {
        id
        name
      }
    }
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
  }
}
```
returns:
```
{
  "errors": [
    {
      "message": "Internal Server Error(s) while executing query"
    }
  ],
  "data": {}
}
```
STACKTRACE:
```
[g.e.SimpleDataFetcherExceptionHandler]: Exception while fetching data (/companies) : java.math.BigInteger cannot be cast to java.lang.Integer
java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Integer
	at graphql.relay.SimpleListConnection.get(SimpleListConnection.java:69)
	at com.my.graphql.schema.Query.companies(StructureQuery.java:46)
	at com.my.graphql.schema.QueryMethodAccess.invoke(Unknown Source)
	at com.coxautodev.graphql.tools.MethodFieldResolverDataFetcher.get(MethodFieldResolver.kt:167)
	at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:270)
```

Line 69 of SimpleListConnection.java (graphql-java):
        Integer first = environment.getArgument("first");
retrieves a BigInteger (2nd case), not an Integer (1st case).

Either the default value should be "created" as Integer, or this code should be nicer e.g. using a java.lang.Number instead.
Same applies to variable "last".

I tried to debug:
- in my method `companies()` above, "first" is set in both cases (int 2 or int 10)
but in the DataFetchingEnvironment's arguments, "first" is either Integer(2) or BigInteger(10)
- the DataFetchingEnvironment is constructed line 245 of ExecutionStrategy with argumentsValues containing the "offending" BigInteger
- this Map<String, Object> is extracted from the GraphQLFieldDefinition through the ValuesResolver (line 236)

My field definition is:
`FieldDefinition{name='companies', type=TypeName{name='CompanyConnection'}, inputValueDefinitions=[InputValueDefinition{name='first', type=TypeName{name='Int'}, defaultValue=IntValue{value=10}, directives=[]}, InputValueDefinition{name='after', type=TypeName{name='String'}, defaultValue=null, directives=[]}], directives=[Directive{name='connection', arguments=[Argument{name='for', value=StringValue{value='Company'}}]}]}`

My field argument[0] is:
`GraphQLArgument{name='first', value=null, defaultValue=10, type=GraphQLScalarType{name='Int', description='Built-in Int', coercing=graphql.Scalars$1@1b02dfed}}`
in fact this `defaultValue=10` is a `BigInteger`.

The inputValueDefinitions[0] is:
`InputValueDefinition{name='first', type=TypeName{name='Int'}, defaultValue=IntValue{value=10}, directives=[]}`

**Comment by bbakerman** [comment]
```
at com.my.graphql.schema.Query.companies(StructureQuery.java:46)
	at com.my.graphql.schema.QueryMethodAccess.invoke(Unknown Source)
	at com.coxautodev.graphql.tools.MethodFieldResolverDataFetcher.get(MethodFieldResolver.kt:167)
	at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:270)
```

graphql-tools is a wrapper library over top of graphql-java

https://github.com/graphql-java-kickstart/graphql-java-tools

You will want to ask them.  The underlying graphql-java always passes Integer values of our the `Int` scalar.  So I am not sure what is going on here.
