### ISSUE TITLE
SchemaDirectiveWiring missing onSchema() method

### ISSUE THREAD

**Issue by Tanaht** [graphql-java/graphql-java#1683]
Hello all,

There is a missing feature in my opinion about this graphQL Java implementation.

In GraphQL:
It is possible to insert directive on a Schema on the SDL:

```graphql
directive @MyDirective(name : String!) on SCHEMA
schema
@MyDirective(arg: "arg")
{
    query: Query
}
```

But there is absolutely no way (or I've not seen any) to have access to this directive from GraphQL Java API

One of the solution I could think of is to update the interface SchemaDirectiveWiring to add a method onSchema() 
--> Of course this solution have some impacts on the Internal GraphQL Java source code

**Comment by bbakerman** [comment]
Thanks for reporting. We should have this.  Today as a work around you can do `graphql.schema.GraphQLSchema#transform` and set in directives but as you say this should be able to be done in schema directive wiring

**Comment by andimarek** [comment]
closing this issue now, because we are now added `GraphQLSchema.getSchemaDirectives` which lets you access the directives defined on your `schema ...` element.

**Comment by wenkang-du** [comment]
> 现在关闭这个问题，因为我们现在添加了`GraphQLSchema.getSchemaDirectives`它，它允许您访问`schema ...`元素上定义的指令。

How to write logic code for this directive?

**Comment by wenkang-du** [comment]
> closing this issue now, because we are now added `GraphQLSchema.getSchemaDirectives` which lets you access the directives defined on your `schema ...` element.

How to write logic code for this directive?
