### ISSUE TITLE
Kotlin compiler error: inherited platform declaration clashes

### ISSUE THREAD

**Issue by jmfayard** [graphql-java/graphql-java#1690]
**Describe the bug**

As a Kotlin programmer, I would like to create an Exception that extends both `GraphQLError` and `RuntimeException`

```kotlin
data class KotlinGraphqlException(val msg: String, val e: Throwable? = null) : 
    RuntimeException(msg, e), 
    GraphQLError 
{
    override fun getErrorType() = ErrorType.ValidationError
}
```

This is possible in Java, but not in Kotlin because both GraphQLError and RuntimeException have an inherited `message` property

![image](https://user-images.githubusercontent.com/459464/68121142-4e003080-ff07-11e9-9d37-8b097bb05cde.png)

Work-around: we currently have to define this class in Java. It's the only Java class in our project :/

Request: add a base class for Kotlin users that extends both `GraphQLError` and `RuntimeException`

I could hack my way by extending `graphql.schema.CoercingParseLiteralException` that does it, but it's not semantically correct.

**Comment by bbakerman** [comment]
I don"t see how we can fix this.  We wont fix it specifically for Kotlin per se.

**Comment by jmfayard** [comment]
The fix would be to add to the library a class that implements both:

`public class SomeException extends GraphQLException implements GraphQLError {}`

**Comment by andimarek** [comment]
we merged and released a GraphQLErrorException .. see #1743
