### ISSUE TITLE
NodeVisitorWithTypeTracking#visitArgument broken for directive arguments in master

### ISSUE THREAD

**Issue by kaqqao** [graphql-java/graphql-java#1696]
The current implementation of [`NodeVisitorWithTypeTracking#visitArgument`](https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/analysis/NodeVisitorWithTypeTracking.java#L184) assumes an argument always belongs to a field, which is untrue as arguments can also belong to directives.

Trying to traverse a query with arguments on directives thus leads to an exception. This is a regression, as it behaved correctly in v13.

**Comment by andimarek** [comment]
I don't think this worked correctly in v13: the `visitArgument` method is poorly named: it is actually a `visitFieldArgument`.

@kaqqao is this a feature request for argument visiting for directives or is it good if doesn't produce any NPE:

the NPE is fixed in #1720

**Comment by kaqqao** [comment]
Fixing the NPE is good enough for my use-case. I'm using `QueryTraverser` to collect and deserialize query directives. More or less exactly what #1351 was trying to do. So I don't need the traversal to descent into the directive arguments themselves.
Thanks for fixing this and feel free to close this issue if you don't want to add that feature (yet) or track it separately.
