### ISSUE TITLE
Input Validation performance

### ISSUE THREAD

**Issue by kristofdepypere** [graphql-java/graphql-java#170]
![pasted image at 2016_06_28 14_28](https://cloud.githubusercontent.com/assets/14199192/16455558/0c9b9776-3e15-11e6-8b08-a252c249627f.png)
The above image shows that the actual validation of inputs takes longer than the actual execution of the query.
We are using graphql and queries can become quite extensive. On the UI side we use relay and we are considering disabling validation on production because this is taking too much time. 

Can this performance be improved or the validation made optional ?

**Comment by dminkovsky** [comment]
@kristofdepypere are you available to discuss this issue further? Is it still affecting you?

Regardless, regarding making the validation optional: it is possible we could do this. The [spec states](http://facebook.github.io/graphql/#sec-Validation):

> Typically validation is performed in the context of a request immediately before execution, however a GraphQL service may execute a request without explicitly validating it if that exact same request is known to have been validated before. For example: the request may be validated during development, provided it does not later change, or a service may validate a request once and memoize the result to avoid validating the same request again in the future. Any client‐side or development‐time tool should report validation errors and not allow the formulation or execution of requests known to be invalid at that given point in time.

As an immediate workaround, please see [`GraphQL#execute()`](https://github.com/graphql-java/graphql-java/blob/v2.0.0/src/main/java/graphql/GraphQL.java). You can use that code to execute your own queries, excluding the validation bit

```
Validator validator = new Validator();
List<ValidationError> validationErrors = validator.validateDocument(graphQLSchema, document);
if (validationErrors.size() > 0 {
    return new ExecutionResultImpl(validationErrors);
}
```

**Comment by aschrijver** [comment]
Hi @kristofdepypere !

I just created an initial version of [vertx-dataloader](https://github.com/engagingspaces/vertx-dataloader] (and https://github.com/facebook/dataloader/issues/36), a Java port of Facebook DataLoader that can be used with GraphQL to batch and cache queries.
It is based on `vertx-core`, but only using `Future<V>` and `CompositeFuture` from there. This would make the validation only occur once.

I am intending to use the data loader in another project I am creating, namely [vertx-graphql-service-proxy](https://github.com/engagingspaces/vertx-graphql-service-proxy) which creates a client-side proxy of a GraphQL Schema and then delegates all calls to type resolvers and data fetchers to a back-end microservice in asynchronous fashion, which could speed up query execution.

You are obviously way ahead in applying GraphQL. I am interested in your experiences and the hurdles you are now facing.
BTW the profiling screenshot....did you do it with plain IntelliJ, or some other tool?

**Comment by kristofdepypere** [comment]
Hi, 

Currently we subclassed the graphql class to make the validation optional. We are thinking to disabled it on Production at least as long as our graphql is not publicly exposed. Ideally it is always enabled but with this kind of performance this seems not acceptible. 

We have a full relay-react ui with graphql Java backend en idd we do have some Challenges and some of them need to be solved in the naar future. 

Profiling is done with jprofiler. I'll Read up on your mentions as they look interesting

**Comment by aschrijver** [comment]
Nice to hear you are using it large scale and in production. Such experiences when shared are really useful to boost GraphQL (Java) and bring new people in the community. Something you may consider blogging about.. Thanks!

I will probably also extend the open source projects into React/Relay realms in future, because that's what I am using myself also. The projects I referenced are still quit minimal, but I can see some interesting features on the horizon. Also I have created [vertx-graphql-service-discovery](https://github.com/engagingspaces/vertx-graphql-service-discovery) to further usefulness of GraphQL in a Microservices architecture based on Vert.x.

**Comment by dminkovsky** [comment]
@kristofdepypere Looking at this again now. What a bummer you didn't open that 15.5% section that shows what's taking up all the time in `LanguageTraversal.traverse` :) If, by chance, you do this again in the future, please post. I'll have to get jprofiler or similar rolling soon, so will try to repeat this experiment. Do you, by chance, remember what kind of query you were using (large/small deep/shallow)?

Anyway, thanks again for posting this.

**Comment by kristofdepypere** [comment]
Hi,
Actually I tried to reproduce now but couldn't see this behaviour anymore. Perhaps I chose the wrong way of profiling leading to too much overhead while instrumenting a lot of small validation calls on methods.
I chose sampling now and the profiling results say validation doesn't take much time of the total execution time.

**Comment by dminkovsky** [comment]
Cool. Thanks for the update. Let's leave this open in case anyone else experiences this.

**Comment by andimarek** [comment]
Closing this now because the initial problem was solved and nobody reported something similar so far.
