### ISSUE TITLE
Incorrect InterfaceFieldArgumentRedefinitionError

### ISSUE THREAD

**Issue by morris** [graphql-java/graphql-java#1701]
**Describe the bug**
The SchemaTypeChecker throws InterfaceFieldArgumentRedefinitionError even if only the descriptions are different between interface argument definition and object type argument definition. This line https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/schema/idl/SchemaTypeChecker.java#L523 does a string comparison of AST nodes, which includes the description.

I believe the description shouldn't be taken into account. For example, the following is valid IMO (and is no problem in other GraphQL implementations):

```
interface Customer {
  "The display name of the customer"
  displayName: String!
}

type PersonCustomer implements Customer {
  "The display name of the customer. For persons, this is the first and last name."
  displayName: String!
}

type CompanyCustomer implements Customer {
  "The display name of the customer. For companies, this is the company name and its form."
  displayName: String!
}
```

**Comment by bbakerman** [comment]
Fair call - I agree this is a bug

**Comment by andimarek** [comment]
The actual problem here are comment and not descriptions on field arguments. This is a test case which fails currently:

```graphql
        type Query { hello: String }
        
        interface Customer {
            displayName(
            # interface arg
            arg: String
            ): String!
        }

        type PersonCustomer implements Customer {
            displayName(
            # impl arg 1
            arg: String
            ): String!
        }

        type CompanyCustomer implements Customer {
            displayName(
            arg: String
            ): String!
        }
```

**Comment by andimarek** [comment]
adressed by #1735
