### ISSUE TITLE
Scalars.GraphQLID should serialize ConnectionCursor 

### ISSUE THREAD

**Issue by awilkin87** [graphql-java/graphql-java#1704]
It should be possible, even appropriate, to define a connection cursor as an ID type within a schema. Graphql-java defines a useful API for creating connections, which includes `ConnectionCursor`. However, `ConnectionCursor` cannot be serialized as an ID, resulting in the following error:

> Can't serialize value (/xxxxxx/pageInfo/endCursor) : Expected type 'ID' but was 'DefaultConnectionCursor'.

As currently implemented, developers must write custom connection classes to use ID type for cursors or they must change the cursors in their schema to String type.

**Comment by bbakerman** [comment]
We agree - we have created #1693 which will fix this

**Comment by andimarek** [comment]
this is fixed by merging #1683
