### ISSUE TITLE
Schema Parser Error when schema contains commented lines

### ISSUE THREAD

**Issue by HiranyaKavishani** [graphql-java/graphql-java#1705]
**Describe the bug**
When parsing schema  which contains comments, through graphql parser, it gets error "InvalidSyntaxError"
```
typeRegistry = schemaParser.parse(schema);
```
The parser sends an error as 

> SchemaProblem{errors=[InvalidSyntaxError{ message=Invalid Syntax : There are more tokens in the query that have not been consumed offending token 'represents' at line 45 column 2 ,offendingToken=represents ,locations=[SourceLocation{line=45, column=2}] ,sourcePreview=}

` The "Upload" scalar type
 represents a file upload.
scalar Upload
}]}`

**To Reproduce**
Use the following as schema.graphql file and use  **graphql.schema.idl.SchemaParser** to parse the shema to get **typeRegistry**

```
directive @cacheControl(
  maxAge: Int
  scope: CacheControlScope
) on FIELD_DEFINITION | OBJECT | INTERFACE
enum CacheControlScope {
  PUBLIC
  PRIVATE
}

type Continent {
  code: String
  name: String
  countries: [Country]
}

type Country {
  code: String
  name: String
  native: String
  phone: String
  continent: Continent
  currency: String
  languages: [Language]
  emoji: String
  emojiU: String
}

type Language {
  code: String
  name: String
  native: String
  rtl: Int
}

type Query {
  continents: [Continent]
  continent(code: String): Continent
  countries: [Country]
  country(code: String): Country
  languages: [Language]
  language(code: String): Language
}

# The `Upload` scalar type
 represents a file upload.
scalar Upload**
```

**Comment by bbakerman** [comment]
The syntax is invalid.

```
# The `Upload` scalar type
 represents a file upload.
scalar Upload**
```

This is all kinds of wrong.

The comment works so reads as

```
 represents a file upload.
scalar Upload**
```

the first line in invalid
and so it the second one with the `**` bit

**Comment by andimarek** [comment]
closing this issue now: @HiranyaKavishani please reopen if needed.
