### ISSUE TITLE
Type serialization/coercion not according to the spec

### ISSUE THREAD

**Issue by drkarl** [graphql-java/graphql-java#171]
This commit titled as a bugfix is actually introducing a bug since now is no longer according to the spec:

https://github.com/graphql-java/graphql-java/commit/43d5f57abe49a16349676aa9c144ce1fa9670187

The spec says:

https://facebook.github.io/graphql/#sec-Coercing-Variable-Values

> If the operation has defined any variables, then the values for those variables need to be coerced using the input coercion rules of variable’s declared type. If a query error is encountered during input coercion of variable values, then the operation fails without execution.

Also

https://facebook.github.io/graphql/#sec-Scalars

> A GraphQL server, when preparing a field of a given scalar type, must uphold the contract the scalar type describes, either by coercing the value or producing an error.
> 
> For example, a GraphQL server could be preparing a field with the scalar type Int and encounter a floating‐point number. Since the server must not break the contract by yielding a non‐integer, the server should truncate the fractional value and only yield the integer value. If the server encountered a boolean true value, it should return 1. If the server encountered a string, it may attempt to parse the string for a base‐10 integer value. If the server encounters some value that cannot be reasonably coerced to an Int, then it must raise a field error.

**Comment by andimarek** [comment]
This is fixed with #455
