### ISSUE TITLE
jsonStringify: Error when trying to escap forward slashes

### ISSUE THREAD

**Issue by anhldbk** [graphql-java/graphql-java#1712]
**Describe the bug**
`AstValueHelper.jsonStringify()` is the function to convert a value into a JSON string  according to http://json.org/ rules

I think currently it does NOT correctly handle forward slashes:

**To Reproduce**

```java
String magic = "std:0.1.0/services";
System.out.println(
    AstValueHelper.jsonStringify(magic)
);

// Will print out: 
// std:0.1.0\/services
// The right one should be:
// std:0.1.0/services
```

As far as I try Javascript `JSON.stringify()`, Python `simplejson` output the later one with the magic input.

**Analysis**

The bug found at this line [AstValueHelper.java#L184](https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/language/AstValueHelper.java#L184)

```java
static String jsonStringify(String stringValue) {
    StringBuilder sb = new StringBuilder();
    for (char ch : stringValue.toCharArray()) {
        switch (ch) {
            case '"':
                sb.append("\\\"");
                break;
            case '\\':
                sb.append("\\\\");
                break;
            case '/':
                sb.append("\\/"); // -> THIS ONE
                break;
```

**Question**

Should I make a PR against this issue?

**Comment by bbakerman** [comment]
Thanks for reporting this.  Please make a PR.

**Comment by andimarek** [comment]
fix is merged
