### ISSUE TITLE
make fields protected in ExceptionWhileDataFetching

### ISSUE THREAD

**Issue by Sam-Kruglov** [graphql-java/graphql-java#1717]
I want to extend `ExceptionWhileDataFetching` because I will always have `extensions` field populated with our internal error code but the default behavior leaves it `null` without any setter exposed. I tried extending it, but it's not very nice, tried to use composition but then there is a bunch of places in the kickstart code that says `instanceof ExceptionWhileDataFetching`.

I ended up redeclaring fields in child class

I would also like to not have `Exception while fetching data` prefix in all messages and maybe remove the `classification` field from response

**Comment by andimarek** [comment]
@Sam-Kruglov can you describe a bit more what are you trying to do?

You are subclassing `ExceptionWhileDataFetching`? `ExceptionWhileDataFetching` is not meant to be created by you: it is created internally by graphql java if a exception is thrown by a `DataFetcher`

**Comment by Sam-Kruglov** [comment]
Thanks for the response!
Business logic throws custom exception with extra fields that must appear in extensions in the response.
I guess exposing setter or some way to set it would solve this, so I can set it myself in custom data fetcher handler that i supply to execution strategy.

I also mentioned would be nice to edit message and remove classification field (that is completely useless for the front end).

**Comment by Sam-Kruglov** [comment]
Oops

**Comment by Sam-Kruglov** [comment]
The worst thing for me is this message prefix I want to get rid of `Exception while fetching data (%s)`

**Comment by andimarek** [comment]
I am closing this, because this is not something we will change:

`ExceptionWhileDataFetching` only happens when you throw an Exception inside a DataFetcher. This should not happen normally. If you want to return an Error you can do this via `DataFetcherResult`.

**Comment by andimarek** [comment]
We also have `DataFetcherExceptionHandler` which lets you customize the error if you really want to throw Exceptions.
