### ISSUE TITLE
Allow TypeReference as InputType with checks for non-null circular references

### ISSUE THREAD

**Issue by kaqqao** [graphql-java/graphql-java#172]
As per https://github.com/facebook/graphql/issues/189 nullable circular references are legal in input types, thus `TypeReference` should be allowed as input.
During schema building, when `TypeReference`s are being replaced, a check needs to be put in place to prevent non-null circular references, though.

**Comment by IamCornholio** [comment]
A bit here: https://github.com/graphql-java/graphql-java/pull/34. Needs more work to deal with the circular references validation.

**Comment by kaqqao** [comment]
I implemented `TypeReference `replacement for `InputType`s on my local env, but couldn't figure out a good way to check for circularity...
I guess I should make a proper fork and push what I have so far so that someone else could join/comment.

**Comment by dminkovsky** [comment]
Merged #172
