### ISSUE TITLE
SLF4J is missing, and raises a warning.

### ISSUE THREAD

**Issue by arvind0598** [graphql-java/graphql-java#1729]
**Describe the bug**
While doing the Hello World (with Maven) from the documentation, linked [here](https://www.graphql-java.com/documentation/v13/getting-started/), I got the following warning during execution. It did execute without any errors though.

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
{hello=world}

Process finished with exit code 0
```

Of course, adding slf4j-simple as a dependency fixed the issue, but seeing as its a dependency already in the build.gradle for this project, something must have been wrong somewhere.

**To Reproduce**
Follow the linked tutorial from the documentation, with Maven.

The dependencies in my pom.xml are listed below:
```
<dependencies>
    <dependency>
        <groupId>com.graphql-java</groupId>
        <artifactId>graphql-java</artifactId>
        <version>2019-12-09T21-46-27-74aed1a</version>
    </dependency>
    <dependency>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-simple</artifactId>
        <version>1.7.30</version>
    </dependency>
</dependencies>
```

Adding slf4j fixes the issue. Otherwise, the warning persists.

**Comment by andimarek** [comment]
Hi,
this is not a bug, but normal slf4j behaviour: it is your responsibility to add an appropriate slf4j binding. See the the slf4j docs for details: http://www.slf4j.org/manual.html

Best regards
