### ISSUE TITLE
Future plans for this project?

### ISSUE THREAD

**Issue by aschrijver** [graphql-java/graphql-java#174]
Hi @andimarek ,

First of all: thanks for this project! I released my first open-source project [vertx-graphql-service-discovery](https://github.com/engagingspaces/vertx-graphql-service-discovery) that makes use of it last Friday (see also credits to you in [Acknowledgments](https://github.com/engagingspaces/vertx-graphql-service-discovery#acknowledgments) section).

You mention in the title that this project is in *very* low maintenance mode. This makes me nervous, as I was planning on using it in more projects. With 472 stars, 25 contributors and being the only Java implementation for such an important technology like GraphQL, makes this an important project as well.

Could you tell a bit more on your future plans? Is the low maintenance period temporary, are you considering looking for a different maintainer, or maybe having multiple maintainers that can merge PR's if you do not have the time?

Best wishes,

Arnold Schrijver.

**Comment by Jimexist** [comment]
Really appreciate this repo and everyone's contribution to it. I'm also a bit concerned about the *low maintainance* mode - maybe there is a way to allow people/community to contribute more actively?

**Comment by IamCornholio** [comment]
Adding @yrashk

**Comment by yrashk** [comment]
I am one of the recently added co-maintainers in the project. Even though my current usage of GraphQL has subsided, I am expecting this to change (meaning I am anticipating being able to provide a bit more time to the project at a later point). I am also trying to provide reasonable maintenance for https://github.com/graphql-java/graphql-java-annotations at this time.

---

*Personally*, I think establishing and nurturing an optimistic merging strategy might be a solution for this project. In my projects, I use C4 that was developed in the ZeroMQ project. I wrote a bit about this at https://blog.eventsourcing.com/productive-welcoming-vs-code-of-conduct-656b1571ddd6#.19ww1t2km but @hintjens explained the ideas behind it a lot better in his talk https://www.youtube.com/watch?v=uzxcILudFWM

**Comment by aschrijver** [comment]
Hi @yrashk ,

Thank you for your explanation. I wasn't aware there were more than one maintainer. Github doesn't show this anywhere (or I've missed it), so it might be good to mention in the README.

I fully agree with you on the code of conduct and already remarked on it in PR #143. I think it is more off-putting than inviting, and the unacceptable behaviours described I have seen nowhere on Github yet. Would be more fitting to have on Facebook maybe...

The C4 spec and guidelines look very interesting and could give a good boost to the project, when implemented. If applying it I think a short, comprehensive bullet list with the procedure would be a good idea, and maybe a wiki page that provides some more background.

On the licensing aspect I am not an expert (par. 2.2.1). I know that real active community contributors (to which I see I can count you as well) the correct licensing is very important. I represent the average Github user so to say, and when I research projects for inclusion in my own project having it Apache2-licensed is an additional plus. Also I have worked for several employers that exclusively allowed Apache2 project into the organization.
Not saying this is good, or how it should be, but just like reading privacy statements, finding out the subtle, legal differences of varying licenses is not something that excites me.

BTW Nice choice the name for these specs. You'll probably find the NSA and FBI at your doorstep if you use it overly much these days :wink:

**Comment by andimarek** [comment]
Hi @aschrijver,

because of personal reasons I am currently not really maintaining this project. And I can't say when (or even if) this will change. The second maintainer is @yrashk, but he is also not very active currently. 

The CoC is not up to discussion, but I am open for every process which will improve the current situation. But it is true, that currently it is not clear that we would welcome more maintainers or how to become one.

But I don't intent to be a strong gatekeeper in that sense: If somebody has contributed a PR and is willing to be a maintainer and to follow the CoC I am happy to give that person commit rights.  (That's basically how @yrashk became a maintainer)

Regards,
Andi

**Comment by aschrijver** [comment]
Thanks @andimarek for your clarification. I think the responses in this thread put my mind at rest.
And if not, I could also request to become maintainer myself.

(On the CoC, I don't mind the thing, of course, just found it odd first time I saw it. Haven't seen a troll, nor sexual remark since, so maybe its indeed working :wink:)

**Comment by kaqqao** [comment]
@aschrijver
Hello ex-Backabase colleague (it's Bojan)!
I'm also heavily investing in this project (working on a too-be-open-sourced library that I intend to use in production soon), and am currently working on fixing some of the issues I identified and impact my work, but I'm not able to continually help with maintenance.
For this reason, I'm planning to look into Sangria (Scala GraphQL implementation) as an alternative, as it's very active and still JVM.

**Comment by andimarek** [comment]
@aschrijver I added a note to make clear that we are looking for help.

@kaqqao If Scala is an option I can recommend Sangria. I know the maintainer and he is very active and Sangria has some very interesting advanced features.

**Comment by aschrijver** [comment]
@andimarek Thanks :+1: 

@kaqqao Hee Bojan, nice to meet you! Send you a LinkedIn mesage.

**Comment by dminkovsky** [comment]
Hello everyone! I am Dmitry and I was recently added as a maintainer to this project. I am also invested in this library and look forward to spending time working through issues with you guys.

Since I am new to this project, it would be helpful for me to find out which issues, if any, are most important to everybody, so we can turn our attention to them.

**Comment by kaqqao** [comment]
We're currently using our own forked version of graphql-java where we added the support for circular input types (issue #172). I'm planning to polish that code and make a PR (currently on vacation, so it will be a couple weeks more before I can do it). This is currently our most important one.
Also, schema printer (issue #126) would be a treat.

**Comment by dminkovsky** [comment]
@kaqqao thank you for your feedback!

Please follow up re: #172 when you're back and have some time. It would be nice to see if we can unfork you. It's an interesting issue. I've come across https://github.com/facebook/graphql/issues/189 in other contexts, too. It's an interesting part of the spec. 

I will work on #126. I don't want to add that printer without tests, and will most likely just port the tests from the JS reference. Nothing complicated there. Just a bit tedious. I also am not a huge fan that this printer replicates the type matching found in https://github.com/graphql-java/graphql-java/blob/v2.0.0/src/main/java/graphql/validation/TraversalContext.java#L31. Would be nice to fork this out.

**Comment by dminkovsky** [comment]
Just wanted to leave a note here that I am on vacation this week, so my ability to work on issues here will be reduced until I am back next week.

**Comment by andimarek** [comment]
@aschrijver I am closing this Issue because I think we addressed your initial questions.
