### ISSUE TITLE
Allow a custom Coercing for GraphQLEnumType

### ISSUE THREAD

**Issue by Keisuki** [graphql-java/graphql-java#1755]
GraphQLEnumType currently contains a hardcoded Coercing internally, which cannot be set or modified by developers.

It would be useful if we could provide a custom Coercing for enums in the RuntimeWiring, as it is with Scalars.  This would allow us to represent GraphQL enums internally by our own enums (without matching names) or other classes.

**Comment by andimarek** [comment]
We already support custom values via `EnumValuesProvider`. 

You can provide it in the `RuntimeWiring`:

```java
               RuntimeWiring wiring = RuntimeWiring.newRuntimeWiring()
                    .type(newTypeWiring("EurEnum")
                            .enumValues(yourValuesProvider)
                    ).build()
```
I hope that helps.
Best regards,
Andi
