### ISSUE TITLE
IntrospectionResultToSchema doesn't handle descriptions correctly

### ISSUE THREAD

**Issue by andimarek** [graphql-java/graphql-java#1759]
The current implementation converts description into comments which is a legacy behavior. Descriptions should be converted into descriptions.

Also: Scalar descriptions are ignored completely.

**Comment by Sajan-99** [comment]
Do these descriptions need a source location?

**Comment by andimarek** [comment]
@Sajan-99 no the description is just text which documents a type or field etc.

The implementation should simply take the description from the introspection result and set it to the Ast Nodes

**Comment by dondonz** [comment]
Closed by PR #1774
