### ISSUE TITLE
No long value in graphql.g4

### ISSUE THREAD

**Issue by xuzb** [graphql-java/graphql-java#176]
Why not support long value? It throws exception when input a large long value.

**Comment by dminkovsky** [comment]
@xuzb can you please give a code example that demonstrates the problem? This implementation uses [`BigDecimal`](https://github.com/graphql-java/graphql-java/blob/v2.0.0/src/main/java/graphql/parser/GraphqlAntlrToLanguage.java#L328) when parsing `FloatValue` input strings. 

"Long" is not in the grammar because it is not part of the GraphQL grammar.

**Comment by dminkovsky** [comment]
Closing for now.

**Comment by dminkovsky** [comment]
Closing because there cannot be a Long value in the grammar.

**Comment by dminkovsky** [comment]
Hey sorry about the confusion here. @xuzb can you provide a value or example that lead to the exception?

**Comment by xuzb** [comment]
Sorry for replying so late.
The following example can lead to the exception: 

import graphql.ExecutionResult;
import graphql.GraphQL;
import graphql.GraphQLError;
import graphql.schema.*;

import static graphql.Scalars.GraphQLLong;
import static graphql.schema.GraphQLArgument.newArgument;
import static graphql.schema.GraphQLFieldDefinition.newFieldDefinition;
import static graphql.schema.GraphQLObjectType.newObject;

public class InputTypeTest {
    public static GraphQLArgument newInputArgument(GraphQLInputType inputType) {
        return newArgument().name("input").type(inputType).build();
    }

    public static void main(String[] args) {

        GraphQLInputObjectType inputLongType = GraphQLInputObjectType.newInputObject()
                .name("LongInput")
                .field(GraphQLInputObjectField.newInputObjectField().name("longValue").type(GraphQLLong).build())
                .build();

        GraphQLObjectType mutation = newObject().
                name("mutationType").
                field(newFieldDefinition()
                        .name("testLong")
                        .type(GraphQLLong)
                        .dataFetcher(new DataFetcher() {
                            @Override
                            public Object get(DataFetchingEnvironment environment) {
                                Object input = environment.getArguments().get("input");
                                return 10;
                            }
                        })
                        .argument(newInputArgument(inputLongType))
                        .build())
                .build();

        GraphQLSchema schema = GraphQLSchema.newSchema()
                .query(mutation)
                .mutation(mutation)
                .build();

        ExecutionResult result = new GraphQL(schema).execute("mutation mu { testLong (input: {longValue: " + System.currentTimeMillis() + "}) { longValue} }");
        for (GraphQLError error : result.getErrors()) {
            System.out.println(error);
        }
    }
}

**Comment by dminkovsky** [comment]
The issue here is actually that the query is not valid. 

The schema defines output type of mutation field "testLong" as a scalar `GraphQLLong`, not an object. The query provides a selection set for that field. That is not valid. The error in `ExecutionResult` is a validation error that asserts this problem.

If you remove the selection set, like so:

```
ExecutionResult result = new GraphQL(schema).execute("mutation mu { testLong (input: {longValue: " + System.currentTimeMillis() + "}) }");
```
you get the expected result.

**Comment by xuzb** [comment]
Hi, If you define the output type as a object type, it still throws exception.

**Comment by dminkovsky** [comment]
I don't see anything wrong. Try for yourself please:

```
package graphql

import graphql.schema.*
import spock.lang.Specification

import static graphql.Scalars.GraphQLLong
import static graphql.schema.GraphQLArgument.newArgument
import static graphql.schema.GraphQLFieldDefinition.newFieldDefinition
import static graphql.schema.GraphQLInputObjectField.newInputObjectField
import static graphql.schema.GraphQLInputObjectType.newInputObject
import static graphql.schema.GraphQLObjectType.newObject;

public class LongTest extends Specification {

    def "longtest"() {
        when:

        GraphQLObjectType mutation = newObject()
            .name("mutationType")
            .field(newFieldDefinition()
                .name("testLong")
                .argument(newArgument()
                    .name("input")
                    .type(newInputObject()
                        .name("LongInput")
                        .field(newInputObjectField()
                            .name("longValue")
                            .type(GraphQLLong)
                            .build())
                        .build())
                    .build())
                .dataFetcher(new DataFetcher() {
                    @Override
                    public Object get(DataFetchingEnvironment environment) {
                        return environment.getArguments().get("input").get("longValue");
                    }
                })
                .type(newObject()
                    .name("LongOutput")
                    .field(newFieldDefinition()
                        .name("longValue")
                        .type(GraphQLLong)
                        .dataFetcher(new DataFetcher() {
                            @Override
                            public Object get(DataFetchingEnvironment environment) {
                                return environment.getSource();
                            }
                        })
                        .build())
                    .build())
                .build())
            .build();

        GraphQLSchema schema = GraphQLSchema.newSchema()
                .query(mutation)
                .mutation(mutation)
                .build();

        // Input a large long value
        ExecutionResult result = new GraphQL(schema).execute("mutation mu { testLong (input: {longValue: " + System.currentTimeMillis() + "}) { longValue} }");
        for (GraphQLError error : result.getErrors()) {
            System.out.println(error);
        }

        then:
        null
    }
}

```

**Comment by andimarek** [comment]
closing for now, because inactivity for a long time
