### ISSUE TITLE
Oerview of Schema Printing and Introspection rules for Scalars and Directives

### ISSUE THREAD

**Issue by andimarek** [graphql-java/graphql-java#1760]
# Scalars 
Introspection and Scalars:

> When returning the set of types from the __Schema introspection type, all referenced built‐in scalars must be included. If a built‐in scalar type is not referenced anywhere in a schema (there is no field, argument, or input field of that type) then it must not be included.

Schema Printing and Scalars:

> When representing a GraphQL schema using the type system definition language, all built‐in scalars must be omitted for brevity.

# Directives
Open PR (https://github.com/graphql/graphql-spec/pull/633):

GraphQL Java and GraphQL.js both return skip,include and deprecated in the introspection `{__schema {directives }}` query.

> When representing a GraphQL schema using the type system definition language,
the built-in directives should be omitted for brevity.

>GraphQL implementations that support the type system definition language must
provide the `@deprecated` directive if representing deprecated portions of
the schema, in this case `@deprecated` directive may be included when returning
the set of directives from the `__Schema` introspection type.

>When returning the set of directives from the `__Schema` introspection type, both `@skip` and `@include` directives must be included.

**Comment by simeonleatherland** [comment]
Open PR looking into schema printing and scalars : https://github.com/graphql-java/graphql-java/pull/1769
