### ISSUE TITLE
Allow interfaces to implement other interfaces

### ISSUE THREAD

**Issue by andimarek** [graphql-java/graphql-java#1764]
https://github.com/graphql/graphql-spec/pull/373

**Comment by halkeye** [comment]
Is this being worked on at all? maybe a draft? I was thinking about seeing if i could contribute at all, but its a lot of code to learn :)

**Comment by etienne-sf** [comment]
Hello happy graphql-java devs,

Any news on this subject ?

**Comment by felipe-gdr** [comment]
Hi @etienne-sf , we're working on a PR to add this new feature to the library. It should be up very shortly ;-)
