### ISSUE TITLE
Allow directives on variable definitions 

### ISSUE THREAD

**Issue by andimarek** [graphql-java/graphql-java#1765]
https://github.com/graphql/graphql-spec/pull/510 not sure how we handle this atm.

**Comment by dugenkui03** [comment]
> [graphql/graphql-spec#510](https://github.com/graphql/graphql-spec/pull/510) not sure how we handle this atm.

I have done some work about **variable directive**, the main change as follows:

1. change the code in `GraphqlOperation.g4`、`GraphqlAntlrToLanguage`、`GraphQLDirective` 、`Introspection` to support 'variable directive';

2. add field `directives` in `VariableDefinition`;
3. change some code about **directive** in `KnownDirectives`、`AstPrinter`、`TestUtil.groovy`,；

4. add groovy test in `VariableDirectiveTest.groovy` to certify that:
   - the declared **variable directive** can't be used in wrong position other than variable;
   - program can get variable directive information from parsed Document.

Is that enough to support **variable directive**?

And should I  add method `instrumentVariables` in `Instrumatation`, which will be called before or around [Execution.execute.valuesResolver.coerceVariableValues](https://github.com/graphql-java/graphql-java/blob/c8de10ed221a4291d9c89455cb39dff56dc90720/src/main/java/graphql/execution/Execution.java#L73), to support the ability described in [spec](https://spec.graphql.org/draft/#sec-Language.Directives): Directives provide a way to describe **alternate runtime execution** and type validation behavior in a GraphQL document.

**Comment by andimarek** [comment]
done
