### ISSUE TITLE
SchemaTransformer: Deleting the node in the parent TraverserContext

### ISSUE THREAD

**Issue by dimdimych** [graphql-java/graphql-java#1766]
The code below fails with `NullPointerException` in `FpKit.map` (in certain cases) 
```java
GraphQLSchema newSchema = SchemaTransformer.transformSchema(schema, new GraphQLTypeVisitorStub() {
    @Override
    protected TraversalControl visitGraphQLType(GraphQLSchemaElement node, TraverserContext<GraphQLSchemaElement> context) {
        // defined elsewhere
        if (checkCondition(node)) {
            // delete the _parent_ node
            TreeTransformerUtil.deleteNode(context.getParentContext());
        }
    }
}); 
```
My investigation showed that `TraverserVisitor.enter` implementation in the `SchemaTransformer.transform` method does not update `zipperByOriginalNode` hash map with changes in parent contexts correctly. The following line of the SchemaTransformer source code assumes that changes to the zippers collection are performed on the current context and node only
```java 
143:  zipperByOriginalNode.put(context.originalThisNode(), nodeZipper);
```

**Comment by andimarek** [comment]
@dimdimych this is not really supported: you can't "go back" and delete something. You can only delete the current node you are visiting or you change the current node in a way that you delete some children. 

So in you case you would actually check the condition of the children when you visit the parent node and then call `.changeNode` with the children deleted.

I hop that helps.
