### ISSUE TITLE
Support `@stream` directive extension

### ISSUE THREAD

**Issue by igdianov** [graphql-java/graphql-java#1767]
There is a [proposal](https://robrichard.net/jskongress-2019/#43) spec for `@stream` directive that supposed to address streaming list results:

- Similar to @defer, but for lists
- Will load each element of the list as it is ready
 - Show users the first item in the list without waiting for the whole list

**Request**
```
query {
  talks @stream {
    title
    time
    speaker {
      name
    }
  }
}
```
**Initial Response**
```
{
  "data": {
    "talks": []
  }
}
```

**Patch for first talk**
```
{
  "path": ["talks", 0],
  "data":  {
    "title": "Opening Keynote",
    "time": "10:30-11:00",
    "speaker": {
      "name": "Sean Larkin"
    }
  }
}
```

**Patch for second talk**
```
{
  "path": ["talks", 1],
  "data":  {
    "title": "Knock knock, who’s there?",
    "time": "11:30-12:00",
    "speaker": {
      "name": "Sam Bellen"
    }
  }
}
```

Having native `@stream` directive support in `graphql-java` will be great for streaming large result sets without having to wait for the whole root list or any embedded list to resolve in memory for   https://github.com/introproventures/graphql-jpa-query in order to minimize memory usage while fetching large results from the database.

I tried to use subscriptions for streaming large results via SSE or HTTP streaming, but it is very limited for queries type, i.e. https://github.com/introproventures/graphql-jpa-query/pull/229#issue-353230436

I can collaborate and contribute to `graphql-java`

**Comment by bbakerman** [comment]
Yes the graphl working group is discussing @stream this morning - there is interest in this area

**Comment by andimarek** [comment]
@igdianov please follow the development here: https://github.com/graphql/graphql-spec/blob/master/rfcs/DeferStream.md

GraphQL Java will not implement any stream/defer until the spec for has made some serious progress: we don't have the resources to support an alpha version of it. We already implemented defer once (it is actually still available) but then the community never implemented it more widely.

**Comment by manuelfink** [comment]
May I ask, is there any progress on @stream directive and @defer?  

For data heavy applications @stream and @defer are very interesting as they solve the issue when querying larger amounts of data, which are heavy and slow. 

I guess many users are not using defer yet, as it is in experimental state. Side questions, but maybe not related to this issue: are there any plans to extend defer from experimental to stable? When do you normally declare a feature as stable?

**Comment by dkubicki** [comment]
as @manuelfink asked any plan of implement/support **@stream**, **@defer**  ?
@andimarek i guess they have made a progress :)

**Comment by kamilchm** [comment]
@edvinerikson should know some implementation details https://github.com/graphql-java/graphql-java/issues/2052#issuecomment-710237331

**Comment by rhino88** [comment]
Is anyone working on this currently?

**Comment by dondonz** [comment]
The GraphQL Working Group is still working on the stream and defer spec. I can see an agenda item for it in one of the meetings last month: https://github.com/graphql/graphql-wg/blob/main/agendas/2023/05-May/04-wg-primary.md

As @andimarek said previously, we won't be able to implement stream/defer until the spec is finalised.

**Comment by dondonz** [comment]
Closing this issue for now, we will keep an eye on spec developments as we're keen to have stream & defer too
