### ISSUE TITLE
Move GraphQL Java scalars to extended scalar lib

### ISSUE THREAD

**Issue by andimarek** [graphql-java/graphql-java#1771]
We are planning to move the GraphQL Java scalars from this lib to extended scalars.

**Comment by simeonleatherland** [comment]
Open PR for adding the java scalars to the lib https://github.com/graphql-java/graphql-java-extended-scalars/pull/20

**Comment by simeonleatherland** [comment]
@andimarek this issue can be closed as it has been resolved.
