### ISSUE TITLE
OverlappingFieldsCanBeMerged is slow

### ISSUE THREAD

**Issue by redhead** [graphql-java/graphql-java#1786]
`OverlappingFieldsCanBeMerged` can be very slow when many fragments in the query.
Scala implementation resolved it by optimizing the algorithm.

See https://github.com/sangria-graphql-org/sangria/pull/12.

Can we do something similar in graphql-java?

**Comment by bbakerman** [comment]
> Can we do something similar in graphql-java?

of course we can - its an open source project and you can you submit a PR to get this started.

**Comment by redhead** [comment]
It doesn't follow the spec, so I'm asking if it's the way to go. 

I may do it once I will get some free time.

**Comment by bbakerman** [comment]
Are you saying that way the sangria team solved the performance problem was to not follow spec?

if so can you expand on that and help us understand what they did and how it deviates?

I read that issue but there is a lot of reverse engineering involved and it would be great to get a head start on that

**Comment by redhead** [comment]
I didn't read it very much into details, but they looked at the algorithm defined by the spec regarding overlapping-fields-can-be-merged, and introduced some optimizations to it (some caching, and some function call refactorings so they don't check things more than needed). 

Currently, it is in "experimental" and providing a way how to replace the original validator with the optimized one using their API for validators. Which is not possible in graphql-java if I saw correctly. So the spec algorithm is still the default one, but there is a way to replace it.

See also
(short comment) https://github.com/sangria-graphql-org/sangria/pull/12#issuecomment-553876071
(details in blog post) https://tech.xing.com/graphql-overlapping-fields-can-be-merged-fast-ea6e92e0a01

**Comment by redhead** [comment]
Bump. 

We would like to sort this our for our application, as it's imposing quite a big performance hit for our API.

**Comment by andimarek** [comment]
@redhead can you provide us with some profiling results?

**Comment by redhead** [comment]
I kind of wanted to start a discussion about it first, so I can't give you profiling results of the rewritten algorithm (I can of the current state). 

Also, as it's not following the spec's pseudocode, I wasn't sure you would be ok of merging it at all.

**Comment by redhead** [comment]
This is the state now. As you can see, even constructing quite a big SQL select and running it on the DB server was faster than `OverlappingFieldsCanBeMerged.isAlreadyChecked`

![Screenshot_2](https://user-images.githubusercontent.com/158482/77045618-dc121a80-69c1-11ea-8b5e-71c0b697a231.png)

**Comment by andimarek** [comment]
How big was the query you are running? Can maybe share it? Thanks

**Comment by redhead** [comment]
The query is big (2k lines), it's because we are doing a global search query which can potentially return any type of our app model entity. Because of that, it consists of a lot of inline fragments for "casting" to the right GQL type of the app model entity. Most of the entities don't have a common denominator interface to make it consise.

The gist of it is here, it was edited for clarity and to hide our business domain:

    query GlobalSearch {
      _search(size: 10, filter: "foobar") {
        edges {
          node {
            gid
            type
            publishedVersion {
              ... on FooType {
                name
                _ancestors {
                  gid
                  type
                  ancestorVersion {
                    ... on AType {
                      name
                      _draftType
                    }
                    ... on BType {
                      label
                      _draftType
                    }
                  }
                }
              }
              ... on BarType {
                name
                _ancestors {
                  gid
                  type
                  ancestorVersion {
                    ... on XType {
                      label
                      _draftType
                    }
                    ... on YType {
                      yName
                      _draftType
                    }
                    ... on ZType {
                      zName
                      _draftType
                    }
                  }
                }
              }

              #################
              ## ...
              ## THIS CAN GO ON LIKE THIS HUNDRED OF TIMES
              ## ...
              #################

            }
          }
        }
        pageInfo {
          hasNextPage
          endCursor
        }
        totalCount
      }
    }

**Comment by redhead** [comment]
Please have a look into the sangria bug report (though written in scala, it probably follows the same algorithm):
https://github.com/sangria-graphql/sangria/issues/296

and the query they reported was:
https://gist.github.com/objmagic/3c881449fcdb3a812a371b86bfa5a3c9

**Comment by redhead** [comment]
So, I took a chance at work to start rewriting the Scala implementation to Java. The rewrite was smooth, but I got to the point that Scala implementation is working with different validation assumptions.

For example, in the case of the test 'conflicting scalar return types':

            boxUnion {
                ...on IntBox {
                    scalar
                }
                ...on StringBox {
                    scalar
                }
            }

the Scala impl shows VALID in terms of overlapping-fields-can-be-merged (in Java is invalid). As the field types are **unknown** (these fields are not defined in the schema), they do not consider them invalid to be merged, as they can be actually of the same type (we do not know).

This would potentially bring some non-backwards-compatible behavior.

So, to continue with the rewrite, could this be (as an experimental validation) considered also valid?

**Comment by redhead** [comment]
(I had to delete my previous post from today as it wasn't fully valid.)

I took a chance to try to rewrite the algorithm from Scala (sangria) implementation to graphql-java. As you can see, it went quite well:

![old](https://user-images.githubusercontent.com/158482/78688587-b491dc00-78f5-11ea-8d93-7977f371dc5a.png)
![new](https://user-images.githubusercontent.com/158482/78688592-b5c30900-78f5-11ea-92cf-76181ea3a676.png)

I have a dirty WIP code of the new algorithm rewritten from scala., All the tests from OverlappingFieldsCanBeMergedTest are passing except for these cases:

1) the error messages are not exactly the same (could be more or less of them, as they can be reported case by case)
2) types that cannot be resolved according to the schema (fields' types that are unknown in validator are not considered for the validation - they always pass)

**Comment by davidcurrie** [comment]
+1 for giving this some serious consideration. I'm looking at a Java profile where, of the 3.8s of CPU time spent in the GraphQL endpoint, 3.2s is spent in OverlappingFieldsCanBeMerged.leaveSelectionSet.

**Comment by andimarek** [comment]
hi,

we are planning to address this issue via https://github.com/graphql-java/graphql-java/pull/2495

Special thanks to @redhead: we really appreciate the effort you put in, but ultimately we could not accept a scala version of the algorithm from a longterm maintainability POV. But we implemented the same algorithm based on the xing article.

We are planning to replace the current validation completely with the more performant one. 

Andi

**Comment by redhead** [comment]
Thanks a lot. It looks great.

**Comment by andimarek** [comment]
merged now and will be part of 17.0
