### ISSUE TITLE
How to validate graphql query against the schema without execution?

### ISSUE THREAD

**Issue by gevorgkurghinyan** [graphql-java/graphql-java#1790]
We have 2 layer architecture (internal and external schema), so we need to validate incoming graphql query against the external schema (without actually executing it), map the query to an internal graphql query and then execute it.

I was looking graphql-java code and I see that most of the classes for query validation are internal classes and there is no public API for it.

https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/GraphQL.java

private PreparsedDocumentEntry parseAndValidate(AtomicReference<ExecutionInput> executionInputRef, GraphQLSchema graphQLSchema, InstrumentationState instrumentationState) {...}

**Comment by bbakerman** [comment]
This was answewred in the Spectrum - https://spectrum.chat/graphql-java/general/how-to-validate-graphql-query-against-the-schema-without-execution~5ef618ab-5c50-4ba2-948b-927f480f4f8a?m=MTU4MTkyMTcyMjE1OA==
