### ISSUE TITLE
The validation issue when input type is listvalue  

### ISSUE THREAD

**Issue by tawalisa** [graphql-java/graphql-java#1793]
Hi
I found a bug by validation when type of input is listvalue. 
Below is my SDL file.
```graphql

type Query {
    bookById(id: ID): Book
    authorById(id: ID): Author
}

type Book {
    id: ID
    name: String
    pageCount: Int
    author(filter: AuthorFilterArgs): [Author]
}

type Author {
    id: ID
    firstName: String
    lastName: String
}
input AuthorFilterArgs {
  AND: [AuthorFilterArgs!]
  OR: [AuthorFilterArgs!]
  id: InputString
  firstName: InputString
  lastName: InputString
}
input InputString {
  EQ: String
  GT: String
  GTE: String
  LT: String
  LTE: String
  IN: [String!]
  CONT: String
}
```
The below is my query.
```graphql
{
    bookById(id: "book-1"){
        id
        name
        author(filter: {
            OR : {
                 firstName:{EQ:"1"}, 
                firstName: {GT:"2"}
             }
        }
){
            id
            firstName   
    }
  }
}
```
Here 'OR: [AuthorFilterArgs!]' is listvalue.  From spec , The input list have to use square-brackets [].   https://spec.graphql.org/June2018/#sec-List-Value
That query is illegal because there is not square-brackets in "OR". But grahpql-java does not validate it.   Could you please have a look?
The correct query should be below. 
```graphql
{
    bookById(id: "book-1"){
        id
        name
        author(filter: {OR : [
                       {firstName: {EQ: "1"}}
                      ,{ firstName:{EQ: "2"}
                    }
                  ]
               }){
            id
            firstName
        }
    }
    
}
```
You can get the example from url.
https://github.com/tawalisa/tutorials
Thanks.

**Comment by tawalisa** [comment]
Added a point. I tried to used graphql-java 11, 13 and 14.  Their behavior were same.

**Comment by tawalisa** [comment]
Just added commit to try fix in my branch. Could you please have a look? https://github.com/tawalisa/graphql-java/commit/ac7b7334fb8708733780d9f96765c588d10b4c4f

**Comment by andimarek** [comment]
Your first query has the following arguments:
```graphql
OR :{
    firstName:{EQ:"1"}, 
    firstName:{GT:"2"}
}
````
This is an input object with twice the same key: I am not sure we have a validation for that, but this is different from the "single element treated as list" topic.

**Comment by tawalisa** [comment]
@andimarek  Thanks for your reply. 
Yes, I was aware of it . This is a single value and it follows spec.   So the topic should be not a problem. 
But I think it could be still another issue about duplicate field in an input object. I checked spec as below link.  duplicate field should not pass validation. But the graphql-java does not throw exception in my case. 
https://spec.graphql.org/June2018/#sec-Input-Object-Field-Uniqueness

```
Input Object Field Uniqueness

Formal Specification

    For each input object value inputObject in the document.
    For every inputField in inputObject
        Let name be the Name of inputField.
        Let fields be all Input Object Fields named name in inputObject.
        fields must be the set containing only inputField.

Explanatory Text

Input objects must not contain more than one field of the same name, otherwise an ambiguity would exist which includes an ignored portion of syntax.

For example the following query will not pass validation.
```

**Comment by rakeshdausa** [comment]
Is there any workaround to validate query for multiple fields with same name?

**Comment by omavi** [comment]
These seem to be the same issue: https://github.com/graphql-java/graphql-java/issues/1806
