### ISSUE TITLE
Support returning DataFetcherResult from subscriptions

### ISSUE THREAD

**Issue by smyrick** [graphql-java/graphql-java#1795]
**Describe the bug**
In graphql-java, a subscription must return a `Publisher<T>` from its data fetcher. This is enforced by the `SubscriptionExecutionStrategy` here: https://github.com/graphql-java/graphql-java/blob/101dc6cfc8dbdf598206868a3e15f6afa0b3bd1d/src/main/java/graphql/execution/SubscriptionExecutionStrategy.java#L70-L77

Just before the check for a type of `Publisher`, graphql-java calls the base `ExecutionStrategy.fetchField`. In that method, it checks if the result is of type `DataFetcherResult` and if it is, unboxes it: https://github.com/graphql-java/graphql-java/blob/101dc6cfc8dbdf598206868a3e15f6afa0b3bd1d/src/main/java/graphql/execution/ExecutionStrategy.java#L300-L302

That means however that the object passed to `fetchField` is a `Publisher` so it will never unbox a `DataFetcherResult`. 

To support partial results, a second check in the `SubscriptionExecutionStrategy` after unboxing the Publisher, should be added to check for a `DataFetcherResult` again. With some refactoring of the base `ExecutionStrategy` some of the existing code could be used to do this.

The GraphQL spec does allow subscription to return data and errors in a single message: https://spec.graphql.org/June2018/#sec-Response-Stream

**To Reproduce**
Create a subscription that returns a `Publisher<DataFetcherResult<T>>` and it fails to parse the proper data and errors fields.

**Related Issues**
This was brought to our attention in graphql-kotlin https://github.com/ExpediaGroup/graphql-kotlin/issues/608

**Comment by bbakerman** [comment]
I aggree that DataFetcherResult should be supported an unpacked

However I am a bit confused when you say ".. we check for a type of Publisher"  Who is we - some kotlin library or the graphql-java library.

Also we want should support top level subscription fields returning `Publisher<T>` and `DataFetcherResult<Publisher<T>>` - and yes <T> could itself be `DataFetcherResults`

You said

> To Reproduce
> Create a subscription that returns a `Publisher<DataFetcherResult<T>>` and it fails to parse the proper data and errors fields.


Did you mean

> Create a subscription that returns a `DataFetcherResult<Publisher<T>>` and it fails to parse the proper data and errors fields.

?

**Comment by smyrick** [comment]
Sorry, the "we" in this case just means the graphql-java library. I will edit my above comment to make it more clear. However, when graphql-kotlin is running it's reflection, it also needs to unwrap the types so we can produce the proper schema information.

Here is the helper method in graphql-kotlin that unwraps the return types from functions: https://github.com/ExpediaGroup/graphql-kotlin/blob/b1292443d2cb563ab030cfc3a8d6dc216cdc499f/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/utils/functionReturnTypes.kt#L41

graphql-kotlin assumes that the valid types are: 

* `Valid type T`
* `Publisher<T>`
* `DataFetcherResult<T>`
* `CompletableFuture<T>`
* `CompletableFuture<DataFetcherResult<T>>`

To support subscription partial results should the type supported be `Publisher<DataFetcherResult<T>>` or `DataFetcherResult<Publisher<T>>`? I would assume it is the former, since the `DataFetcherResult` can be thought of as the JSON object that has both `data` and `errors` and subscriptions return a stream of those objects.

**Comment by bbakerman** [comment]
The PR above supports with a DataFetcherResult wrapping the `Publisher` (that is on the top level field) and also each return "stream object" from the `Publisher` can also be a `DataFetcherResult<T>`

Because as you say the initial top level field (which gives of the reactive stream Publisher) can have that and errors and each "streamed" object can have errors

**Comment by smyrick** [comment]
Closed in https://github.com/graphql-java/graphql-java/pull/1804
