### ISSUE TITLE
Unexpected behavior: Type References get replaced in wrapping types

### ISSUE THREAD

**Issue by redhead** [graphql-java/graphql-java#1796]
I spent a few hours debugging a nasty bug with a "duplicate" GQL type in the schema (two types of the same name was found).

In our app, we regenerate the GQL schema every time our app model changes. The first schema was built alright and worked perfectly. But the second (and any other) schema ended up with the error above. Finally, I've found that wrapping types like `GraphQLList` or `GraphQLNonNull` are actually replacing the wrapped `GraphQLTypeReference` instances with the resolved type from the schema. 

However, that resolved type may not even be from the same schema anymore (in our case, after we regenerate the schema to match our new app model, the list points to the previous schema type). It happened because I wanted to reuse the same `GraphQLList` of `GraphQLTypeReferences`, which doesn't change in between the app models, and I put it into a static final constant. Each new schema that we generated to comply the new app model was referencing the List of types from the very first schema (after it got replaced).

This is quite surprising behavior as graphql-java uses an extensive amount of immutable data structures, copying, and builders in other cases. I was very baffled as why TypeReference is actually breaking immutability principles (probably because performance, but still).

The documentation mentions replacing the reference, but as it describes recursion types, I thought it happens in runtime without mutating the state of the instances that I provide to the schema.

It would be nice to mention this in the documentation properly. Although, I would rather see this as a bug and break of immutability.

**Comment by bbakerman** [comment]
When you say you regenerate your schema when thigns changes, what mechanism do you use to to this?  build it again from scratch or schema.transform it?

We replace ALL type references inside a schema at schema.build time.

```
            GraphQLSchema graphQLSchema = new GraphQLSchema(tempSchema, codeRegistry);
            schemaUtil.replaceTypeReferences(graphQLSchema);
```

after that the  built schema and objects are meant to be immutable.  So it sounds like you have stumbled on an edge case, perhaps via the "schema regeneration" you mention above.

> The documentation mentions replacing the reference, but as it describes recursion types, I thought it happens in runtime without mutating the state of the instances that I provide to the schema.

how are you holding onto old instances?  In what manner? Do you  re-use them  in some way?  We had not considered that GraphqlXXXTpes woul be held onto after Schema.build() is called.  Is this what you are doing?

See `graphql.schema.SchemaUtil#replaceTypeReferences`.

I ask all these questions, not to doubt you, but to get a better understanding of whats going on and whether we have a case we didnt consider.

Is it possible to produce a simplified unit test of this happening please.

**Comment by bbakerman** [comment]
Ahh read the description better

>  It happened because I wanted to reuse the same GraphQLList of GraphQLTypeReferences, which doesn't change in between the app models, and I put it into a static final constant. 

Yeah we cant handle that - we intend that a schema and its objects are publically immutable but because of type references we mutate them via non public methods.  Its EXCEEDINGLY difficult to built immutable structures that also allow circular references.

**Comment by redhead** [comment]
I see.

Correct me if I'm wrong but what if the schema would be copying the type and do the replace internally during build on the copy, but not touching the instances I pass to the schema builder. Then they would stay immutable, but as a side effect they would not be part of the schema since it was copied.

**Comment by bbakerman** [comment]
I am not sure what things you are holding OUTSIDE ready to be re-used and hence I cant give you a good answer on the question asked.

In short we don't recommend that you hold onto types across schema builds with the expectation that they are internally immutable.  They are not.

**Comment by redhead** [comment]
Ok, no problem. I will keep it in mind. Thanks.
