### ISSUE TITLE
Separate interface from implementation in API classes

### ISSUE THREAD

**Issue by aschrijver** [graphql-java/graphql-java#180]
I am writing a remote service proxy for a GraphQL Schema where the original schema is first marshalled to json and then reconstructed at the client's end. For this purpose I have created decorators for the API classes in the `graphql.schema` package.

However, since these are concrete classes which my decorators extend I cannot have an abstract decorator base class, and also I have to create dummy `super()` constructors to avoid parameter check exceptions.

GraphQL Java being a library that is integrated in other products should have an API that is extensible, where applicable.

Extracting interfaces from current concrete classes and moving the latter to an `impl` sub-package would be a good improvement in this direction. If you agree I can create a PR.

**Comment by bbakerman** [comment]
I think we can close this issue as is since its hard to see it getting implemented

**Comment by aschrijver** [comment]
no problem. agree :)
