### ISSUE TITLE
Schema validation for query arguments have fields with same name

### ISSUE THREAD

**Issue by rakeshdausa** [graphql-java/graphql-java#1806]
I have an application based on graphql-java. In my case when I try to pass an argument with same name it will not fail and it works by keeping last value. 
But according to graphql specification, duplicate field should not pass validation and throw a validation error. 

https://spec.graphql.org/June2018/#sec-Input-Object-Field-Uniqueness

**Comment by bbakerman** [comment]
Can you tell me how you build the schema?  via SDL or via direct Schema object building

we have this code in input field uniquness in SDL

```
    private void checkInputValues(List<GraphQLError> errors, InputObjectTypeDefinition inputType, List<InputValueDefinition> inputValueDefinitions) {

        // field unique ness
        checkNamedUniqueness(errors, inputValueDefinitions, InputValueDefinition::getName,
                (name, inputValueDefinition) -> {
                    // not sure why this is needed but inlining breaks it
                    @SuppressWarnings("UnnecessaryLocalVariable")
                    InputObjectTypeDefinition as = inputType;
                    return new NonUniqueNameError(as, inputValueDefinition);
                });


        // directive checks
        inputValueDefinitions.forEach(inputValueDef -> checkNamedUniqueness(errors, inputValueDef.getDirectives(), Directive::getName,
                (directiveName, directive) -> new NonUniqueDirectiveError(inputType, inputValueDef, directiveName)));

        inputValueDefinitions.forEach(inputValueDef -> inputValueDef.getDirectives().forEach(directive -> {
            checkDeprecatedDirective(errors, directive,
                    () -> new InvalidDeprecationDirectiveError(inputType, inputValueDef));

            checkNamedUniqueness(errors, directive.getArguments(), Argument::getName,
                    (argumentName, argument) -> new NonUniqueArgumentError(inputType, inputValueDef, argumentName));
        }));
    }
```

**Comment by rakeshdausa** [comment]
I built the schema via direct Schema object building. 
To more clarify my question. Schema generation is fine and it generates schema correctly. But when I am firing some query with some argument like
``` 
{
    follow(followerId: <anyFollowerID> , followerID:<someOtherFollowerID>){
    {
        followed
     }
}
```

Then it must fail because I passed two arguments but this query supports only one argument. Although it picking last one but still its not according to GraphQL-specifications.

**Comment by michael-schmetter** [comment]
Is there any progress here?
There is no validation on those query arguments, which is against the GraphQL spec.

**Comment by michael-schmetter** [comment]
Should be fixed by https://github.com/graphql-java/graphql-java/pull/1857
This issue could be closed from my point of view

**Comment by omavi** [comment]
I don't think #1857 fully addresses the issue because it looks to only validate argument names and not all input object fields. The spec [implies that the validation should be recursive](http://spec.graphql.org/June2018/#sec-Input-Object-Field-Uniqueness).

**Comment by bbakerman** [comment]
@omavi - can you please give us an reproducible example in SDL format where this bug is happening.

We never got one originally on this issue and if we need to fix more things we need good reproduction

**Comment by omavi** [comment]
@bbakerman - I just typed this up, so it may not be perfect, but here's the idea:

```graphql
FooMutation(inputObj: BarInput): Foo

input BarInput {
  FooInputField: FooInput
}

input FooInput {
  fooTitle: String
}

type Foo {
  fooTitle: String
}
```

and 

```
mutation MyMutation {
    FooMutation(
        inputObj: {
                    FooInputField: {
                        fooTitle: "A"
                    },
                    FooInputField: {
                        fooTitle: "B"
                    }
                  }
    ) {
        fooTitle
    }
}
```

graphql-java ends up accepting the last duplicate value and passes it along while ignoring the rest

**Comment by ashatch** [comment]
@bbakerman I think I have a test that can easily be plugged in, using the `dogWithInput` definition that already exists:

```groovy
    def 'when inputs are duplicated, must error'() {
        setup: "Should not allow duplicate field names in input"
        def query = """
           query {
             dogWithInput(leash: {
                id: "foo"
                id: "bar"
             })
           }
        """
        when:
        traverse(query)

        then:
        errorCollector.getErrors().size() == 1
    }
```

**Comment by bbakerman** [comment]
Thanks for the PR - I havent looked into this at all much.  Can you do some more leg work please.

Can you show me in the graphql specification where it forbids this.  It feels wrong but I would love to see it in spec and I would also love for someone to do the leg work here :)

**Comment by ashatch** [comment]
Thanks for the merge - much appreciate the quick response in getting it in the next release.

Can this issue close (@rakeshdausa)?

**Comment by dondonz** [comment]
Closed by pull request https://github.com/graphql-java/graphql-java/pull/3094
