### ISSUE TITLE
Builders that accept Map and List should create a new shallow copy

### ISSUE THREAD

**Issue by ssko1** [graphql-java/graphql-java#1808]
### Explanation
Builders, when passed in a List or Map, assigns and uses the same reference internally to also add additional elements when chaining operations. The original object is mutated which can cause undesirable behavior when the original object is used later.

Below, I have an example that demonstrates this behavior on a [`Document`](https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/language/Document.java#L138).

### Current behavior
```java
FragmentDefinition fragmentDefinition = FragmentDefinition.newFragmentDefinition()
    .name("test_fragment")
    .build();

//initially size == 1
List<Definition> fragmentDefinitions = new ArrayList<>();
fragmentDefinitions.add(fragmentDefinition);

OperationDefinition query = OperationDefinition.newOperationDefinition()
    .operation(Operation.QUERY)
    .build();

Document document = Document.newDocument()
    .definitions(fragmentDefinitions)
    .definition(query)
    .build();

//...do something with document

System.out.println(fragmentDefinitions.size()); // expect 1, but will equal 2
```

I am using `fragmentDefinitions` later in the code; I was a little surprised when I saw the `OperationDefinition` pop up as an extra element in the list.

The above code will throw an exception if you build the document with a collection or map that is unmodifiable in some way: `Collections.singletonList()` or `Collections.singletonMap()` will throw exceptions on `add` and `put`.

### Proposed/Desired behavior

I propose all builders create a shallow copy of all collections and maps so that the example code above works as expected, that is, `fragmentDefinitions.size()` should be equal to 1.

Thoughts?

**Comment by bbakerman** [comment]
Yes we really should shallow copy that list.  

```
     public Builder definitions(List<Definition> definitions) {
            this.definitions = definitions;
            return this;
        }

        public Builder definition(Definition definition) {
            this.definitions.add(definition);
            return this;
        }
```

We default the list but the code that builds out the list of things assumes that you want to set ALL the lists as once.  As you said its fragile.

In the document parse we never use the "list" varation (because we add / add  / add as we encounter AST elements) and hence this short coming has not revealed itself

We would be happy to accept PRs to help make this more robust.

**Comment by ssko1** [comment]
Interesting side note is that every `graphql.language.Node` with a collection builder method is actually not immutable as per the documentation because you can modify collections after the object has been built.

```java
List<Comment> comments = new ArrayList<>();
Argument argument = Argument.newArgument("key", StringValue.newStringValue("value").build())
    .comments(comments)
    .build();

System.out.println(argument.getComments().size()); // 0
comments.add(null);
System.out.println(argument.getComments().size()); // 1
```

So fixing issue this would allow Nodes to conform to the statement "Every node is immutable".

This might be something to look into for other areas where the immutability contract is broken (not just for builders).

**Comment by bbakerman** [comment]
We are now using ImmutableList and its its smart copy members in a lot of place, especisally in the AST nodes

I am going to close this issue.  More specific examples can be raised as new issues
