### ISSUE TITLE
Performance optimization of ExecutionPath.toListImpl()

### ISSUE THREAD

**Issue by rrva** [graphql-java/graphql-java#1809]
ExecutionPath.toListImpl() shows up when profiling, especially the Collections.reverse() part. Is it possible to build the execution path in a cheaper way?

**Comment by bbakerman** [comment]
Can you give us some more profiling information please

I am sure it can be improved however it would be great to see before / after profiling data or some sort of flamegraph on how ExecutionPath is being slower that it should

**Comment by bbakerman** [comment]
Having a look at the code we are quite aggressive in computing the "list" view.  I am guessing because we then use it in .equals and so on.

We may  be able to make it more efficient by using a lazy approach BUT I think we need to see more profiling to see where the construction costs are really being made

**Comment by bbakerman** [comment]
I did some quick micro branch marking.  As with ALL micro benchmarking its just numbers.

but given

```
 public void benchExecutionPathBuilding() {

        ExecutionPath path = ExecutionPath.rootPath();
        for (String segment : sixLenPath) {
            path = path.segment(segment);
        }
    }
````




With no changes we get

Result "benchmark.ExecutionPathBenchMark.benchExecutionPathBuilding":
  783.604 ±(99.9%) 10.125 ops/ms [Average]
  (min, avg, max) = (762.150, 783.604, 799.679), stdev = 9.471
  CI (99.9%): [773.479, 793.729] (assumes normal distribution)


I then took out the `toListImpl()` on construction

  Result "benchmark.ExecutionPathBenchMark.benchExecutionPathBuilding":
  4312.197 ±(99.9%) 57.882 ops/ms [Average]
  (min, avg, max) = (4207.411, 4312.197, 4432.042), stdev = 54.143
  CI (99.9%): [4254.315, 4370.079] (assumes normal distribution)


That's a lot more ops.  773 -> 4312

I am investigating.  But I would love more profiling data that you can get in a real production sense

**Comment by bbakerman** [comment]
For example you gave us flamegraph data on https://github.com/graphql-java/graphql-java/issues/1012 which help a lot

**Comment by bbakerman** [comment]
Some benchmarking from the PR


START

Result "benchmark.ExecutionPathBenchMark.benchExecutionPathBuilding":
  294.826 ±(99.9%) 10.213 ops/ms [Average]
  (min, avg, max) = (279.647, 294.826, 314.893), stdev = 9.553
  CI (99.9%): [284.613, 305.038] (assumes normal distribution)

ATTEMPT 1) Lazy toListImpl() computed each time (with hash codes and .equals)

Result "benchmark.ExecutionPathBenchMark.benchExecutionPathBuilding":
  177.590 ±(99.9%) 11.788 ops/ms [Average]
  (min, avg, max) = (157.543, 177.590, 191.738), stdev = 11.027
  CI (99.9%): [165.802, 189.378] (assumes normal distribution)


ATTEMPT 2) Proper Lazy toListImpl() with once time lazy init

Result "benchmark.ExecutionPathBenchMark.benchExecutionPathBuilding":
  458.210 ±(99.9%) 35.598 ops/ms [Average]
  (min, avg, max) = (419.352, 458.210, 523.477), stdev = 33.298
  CI (99.9%): [422.612, 493.808] (assumes normal distribution)


ATTEMPT 3) Proper Lazy toListImpl() with once time lazy init
 and Custom.equals / hashCode 

Result "benchmark.ExecutionPathBenchMark.benchExecutionPathBuilding":
  968.788 ±(99.9%) 35.214 ops/ms [Average]
  (min, avg, max) = (898.569, 968.788, 1020.979), stdev = 32.939
  CI (99.9%): [933.574, 1004.002] (assumes normal distribution)


What does this mean?

It means for the benchmark code it went from 294 ops/s to 968 op/s

Intuitively it's faster if we are creating the ExecutionPath often (which we do)

I don't yet have Profiler information on this.

**Comment by rrva** [comment]
Sorry for delay, will try to provide flamegraphs soon

**Comment by andimarek** [comment]
we have an improvement at #1891
