### ISSUE TITLE
Rename GraphQLSchema.getDictionary() to getAdditionalTypes()

### ISSUE THREAD

**Issue by aschrijver** [graphql-java/graphql-java#181]
The `GraphQLSchema.getDictionary()` is only ever used in tests to provide types for testing, but what is its intended purpose? If it is intended to e.g. provide additional interface implementations it is better renamed to something like `additionalTypes`.

With the current name of `dictionary` I would expect it to hold a flat set of _all_ the types that are defined throughout the schema (maybe with the exclusion of introspection types).

**Comment by dminkovsky** [comment]
Yes, indeed, the purpose of `dictionary` is to provide types to the schema in the event that you want to define types that are not reachable from the query or mutation roots. 

This set is an [array called `types` in the JS implementation](https://github.com/graphql/graphql-js/blob/v0.6.2/src/type/schema.js#L227). I agree that "dictionary" is an unfortunate name. It would be nice to change this, but not high priority given that this issue exists for reference and that most likely this is not a feature that many people are using.

**Comment by aschrijver** [comment]
Thanks. Well, I a am not using it right now, but I think as GraphQL is maturing and used in larger schema definitions this will be regularly used.

**Comment by andimarek** [comment]
This Is solved by #398
