### ISSUE TITLE
Cpu spike with graphql and vertx

### ISSUE THREAD

**Issue by himanshumps** [graphql-java/graphql-java#1810]
We are seeing issue with graphql and vertx.

I have posted the issue on vertx forum but looks like it might be an issue with graphql java library.

The link to issue is: [Vertx web graphql cpu spike issue](https://github.com/vert-x3/vertx-web/issues/1539) 

There is a sample code that has been shared in the issue.

Looping @tsegismont as well

**Comment by andimarek** [comment]
@himanshumps can you give us more information than that? We are looking specifically for profiling data normally. thanks

**Comment by bbakerman** [comment]
We are going to need more information than

> GraphQL is making CPU spike to maximum during performance test (500tps)

If you have a test application you should be able to profile it in a tool like JProfiler or YourKit and get some insights into what methods are doding what.

We need more evidence so we can start to find a problem.

For example https://github.com/graphql-java/graphql-java/issues/1012 was a bug report that we could action

**Comment by himanshumps** [comment]
I tried to get the flamegraph created as in #1012 

I have no clue if you will be able to find that root cause with it. 

The flamegraph from the main application where we see the CPU going to 1.

I created it using the steps mentioned at https://netflixtechblog.com/java-in-flames-e763b3d32166

Let me know if you need more data.


![flamegraph](https://user-images.githubusercontent.com/22702284/76066782-44213380-5fb4-11ea-921c-21de714c5374.png)

**Comment by himanshumps** [comment]
Also attached is the SVG file

[flamegraph.zip](https://github.com/graphql-java/graphql-java/files/4297336/flamegraph.zip)

**Comment by bbakerman** [comment]
I had a look at the flame graph

I cant see any hot spots in graphql java code terms.

I see some  

```
Ljava/io/FileOutputStream:::writeBytes
[perf-1674.map]
[..
[perf-1674.map]
queue_work_on
JavaCalls::call_virtual
vert.x-eventloo
...
JavaThread::thread_main_inner
```

which is a worry - I read that as some code doing IO inside the vertx event loop - that is a big big no no.

I also see some Jackson deserialisation and so on.

Flame graphs are great but with just one its hard to see any hotspots and there is little graphql-java code in them.

We are interested in performance problems in graphql-java - however we cant be a remote debugger of performance problems effectively.

**Comment by tsegismont** [comment]
Hi @bbakerman , this is Thomas from the Vert.x team. I am the maintainer of the Vert.x Web GraphQL module.

An issue has been opened on the vertx-web project too. I took a look at the benchmarked code and I wanted to let you know it didn't look much relevant to me, see https://github.com/vert-x3/vertx-web/issues/1539#issuecomment-594467888

Cheers

**Comment by andimarek** [comment]
closed bases on the previous comment
