### ISSUE TITLE
Update Documentation for Creating Model/POJO Classes & Explain How the PropertyDataFetcher Resolves Fields Using Reflection

### ISSUE THREAD

**Issue by jmt212** [graphql-java/graphql-java#1812]
In the current implementation of `PropertyDataFetcher` and `PropertyDataFetcherHelper`, a cascading series of method calls is made in an attempt to find the suitable accessor method or field for a given field. The sequence currently is:

1. Use reflection to find a publicly accessible getter method - if successful store result in the method cache to save on future reflection operations
2. If (1) fails reflection is again used to find a non-public getter method - if successful the result of this is stored in the method cache to save on future reflection operations
3. If (2) fails reflection is used to find a publicly accessible field - if successful the result is stored in field cache.
4. Finally, if (1), (2), or (3) fail - the field is stored in a negative cache, and null is returned

In profiling my application recently I found that most of the CPU time was being spent in `PropertyDataFetcherHelper. getPropertyValue()` - this was because several classes in my schema lacked getter methods (only had publicly accessible fields). This caused cases (1) and (2) - from above - to always be called and resulted in two reflection calls being made in an attempt to find a getter method.

Could the documentation for how simple POJOs are resolved via the `PropertyDataFetcher` be updated and clarified to better explain how fields are resolved, and explicitly note the cascading series of reflection calls that are being made. 

Alternatively - would it be possible in `PropertyDataFetcherHelper.getPropertyValue()` - to always check the negative, field, and method caches before moving onto attempting to find an accessor via any of the reflection methods described above.

**Comment by bbakerman** [comment]
Just to explain our code history - originally we had no method caches or negative caches at all.  And hence we were not as efficient as we are today.

You have found our new most in efficient scenario 3) public fields

I don't think documentation is the answer (albeit we could always improve it) but rather as you said a "negative cache" on each of the 1) 2) 3) strategies and fast short cutting to them.

**Comment by bbakerman** [comment]
One question I have is are you using SDL to build your schemas?  

If so you can use WiringFactory to provide a default data fetcher that will be used for simple property fetchers.  You could then write your own public field fetcher as a work around.

**Comment by jmt212** [comment]
We are not using a SDL to build our schema. We maintain the schema (the .graphqls file) by hand (it rarely changes).

For wiring up our DataFetchers - we only explicitly wire types & queries that are complex and in turn let the java-graphql default handle the rest for simple type and fields.

For the time being we have gone through our code base and ensured that there are public getter methods available for java-graphql to use when using the PropertyDataFetcher.

Declaring getters, where they had not previously been defined, works for us - just wanted to raise my findings to see what could be done for the future (looks like you already have a PR out implementing this 👍 ) and hopefully help anyone that stumbles upon this.

**Comment by bbakerman** [comment]
This has been fixed
