### ISSUE TITLE
Common base for instrumentation parameters

### ISSUE THREAD

**Issue by fvilla-amazon** [graphql-java/graphql-java#1816]
Is there a reason why the instrumentation parameters for different instrumentation methods do not have a common base class?  Some do but others do not.  It would seem that all methods should at least have some things in common.  For example, the operation that is or will be executed or perhaps the context that will be used in the execution.  Not having a common base, makes developing code that will be the same across several instrumentation method tedious and boiler-platy.  Another thing is that different instrumentation parameters don't alway use the same method to return the same kind of object.  For example, get the ExecutionStepInfo can be done in different ways, depending on which instrumentation method is being implemented.

Also, why was the method for accessing the data fetcher for a given field removed?  I realize that the code registry was introduced recently and that it can be accessed via the code registry.  However, doing so make it so that developers have to know more about the internals of how GraphQL Java stores types and when certain types should be unwrapped.

**Comment by bbakerman** [comment]
> Is there a reason why the instrumentation parameters for different instrumentation methods do not have a common base class

I think might be that the Instrumentation classes "evolved" over time.  No great reason otherwise.  Once we had a certain shape, we could have fixed it but it would break API.

We accept PRs if you think you have a cleaner way

**Comment by bbakerman** [comment]
Also https://spectrum.chat/graphql-java?tab=posts is a good resource for "questions versus code problems"

**Comment by fvilla-amazon** [comment]
Thanks @bbakerman.  I'll keep the PR in mind
