### ISSUE TITLE
DataFetchingEnvironmentImpl.Builder uses wrong value for localContext

### ISSUE THREAD

**Issue by arlampin** [graphql-java/graphql-java#1818]
On [DataFetchingEnvironmentImpl.Builder#L282](/graphql-java/graphql-java/blob/0886c26d4caa2628938ba1d843085379eb6ce31c/src/main/java/graphql/schema/DataFetchingEnvironmentImpl.java#L282) there is line 

```java
this.localContext = env.locale;
```
This should be
```java
this.locale = env.locale;
```
instead. Currently `locale` is not copied over properly and `localContext` is overwritten by `locale`

**Comment by bbakerman** [comment]
Thanks for report - this should be an easy fix.  Any chance you could make a PR?  You know, open source and all? :)

**Comment by bbakerman** [comment]
Well I had spare time and its a small fix so thanks once again for reporting
