### ISSUE TITLE
Idea of a more efficient data fetcher registry

### ISSUE THREAD

**Issue by bbakerman** [graphql-java/graphql-java#1819]
Today the GraphqlCodeRegistry uses a multi map (system then named) look up plus an instantiation of the PropertyDataFecther on each field lookup (by co-ordinate)

This then looks up the DataFetcherFactory which then creates the data fetcher.  Generally this is pretty fast since most of this is stateless.

So really we have a Coordinates -> DataFetcherFactory cache with possible instatiation.

We could make this more efficient by caching Coordinates -> DataFetcher per code registry.  This would apportion the cost of this look up across ALL request on that registry aka that schema.

I had a go at this locally and all the tests pass - its a simple fix.

The downside of this is that you have a mutable cache (ConccurenHashMap) per code registry and hence a small window if "mutability" and possible problems from unintended object resuse.  However the more I think about this I think in this cases its "theoretical" (eg possible but unlikely)

**Comment by sheepdreamofandroids** [comment]
You could use a Caffeine cache and do away with those problems.
Also, you might not want to hang on to rarely used datafetchers forever.
