### ISSUE TITLE
Create overload of GraphQLSchema.getAllTypesAsList() that filters introspection types

### ISSUE THREAD

**Issue by aschrijver** [graphql-java/graphql-java#182]
I have need to get the list of types defined in a schema, without introspection types. But a call to `GraphQLSchema.getAllTypesAsList()` includes them by default.
Now while this is easy to do, but it requires keeping a known list of type names, or filtering on the double dash before the type name, which is not optimal.

Better would be if there was an overload that does not load the introspection type to the list.
Or maybe this method could be `GraphQLSchema.getDictionary()`. See also #181

**Comment by dminkovsky** [comment]
I don't think this is worth adding to the codebase. Filtering out the introspection types in application code is easy enough that I do not think we need to expand this codebase to support that. 

Further, and quite important in my opinion, is the fact that the introspection types are true, real types in the schema. I can see there might be many times when you are not interested in these types, but generally I don't think this implementation should provide a function that filters out real, legitimate, queryable types.

However, If this becomes a popular request, we can definitely revisit. Closing for now.

**Comment by aschrijver** [comment]
Fair enough, no problem.
