### ISSUE TITLE
Pass the current ExecutionContext to ValueUnboxer.unbox

### ISSUE THREAD

**Issue by roschlau** [graphql-java/graphql-java#1822]
**Use Case**:
I have a special class `Localized<T>`, which can provide different values of the same type for different Locales. This is pretty handy for translations. It would make working with GraphQL much easier, if I could define an Unboxer that receives the current ExecutionContext in addition to the object to be unboxed to automatically unbox localized values based on the current Locale, like this:

    class LocalizedUnboxer implements ValueUnboxer {
      @Override
      Object unbox(Object object, ExecutionContext context) {
        if (object instanceof Localized) {
          return object.forLocale(context.locale);
        }
        return object;
      }
    }

It will also come in handy for other types of context-dependent boxed values, but this is the main one I would really like this functionality for.

Looking at the source code, this shouldn't be much trouble to implement, as the current ExecutionContext is already in scope everywhere the unboxing happens. I could provide an implementation, if this is decided to be worth having.

**Comment by bbakerman** [comment]
I understand your wanty here.  You are after that an "aspect callback" that can take any value T and the executing environment and return a unwrapped value 

`U unwrap( T value, ExecutingEnv env)`

The thing is we kinda have that.  That the data fetcher virtually - the execution has all sorts of interesting things in it

`U fetch(DataFetchingEnvironment env)`

I am sympathetic to such an "aspect" - that is you you don't have to know about each DataFetcher (perhaps they are composed in libs outside your control) 

As a work around right now you can use `graphql.execution.instrumentation.Instrumentation#instrumentDataFetcher` which will be given a data fetcher and you can then tweak any value coming back from it.

@andimarek  - what are your thoughts on ValueUnboxer becoming and "aspect" that has context?

**Comment by roschlau** [comment]
@bbakerman Thanks for that suggestion, didn't think about using an Instrumentation to achieve this result! I'd still be in favor to allow Unboxers access to the execution environment, but this solution works well enough for us for now 👍
