### ISSUE TITLE
Scalar types not reachable through root operation types are omitted by SchemaGenerator

### ISSUE THREAD

**Issue by sachindshinde** [graphql-java/graphql-java#1833]
**Describe the bug**
`SchemaGenerator.buildAdditionalTypes()` doesn't check `typeRegistry.scalars()`, so scalar types that aren't reachable through root operation types aren't included in schemas generated by `SchemaGenerator`.

**To Reproduce**
```java
TypeDefinitionRegistry typeRegistry = new SchemaParser().parse(
        "type Query" +
        "\n" +
        "scalar Foo\n"
);
RuntimeWiring runtimeWiring = RuntimeWiring.newRuntimeWiring()
        .scalar(GraphQLScalarType.newScalar()
                .name("Foo")
                .coercing(Scalars.GraphQLString.getCoercing())
                .build()
        )
        .build();
GraphQLSchema schema = new SchemaGenerator().makeExecutableSchema(typeRegistry, runtimeWiring);
Assertions.assertTrue(schema.getAllTypesAsList().stream().anyMatch(type -> type.getName().equals("Foo")));
```

**Comment by bbakerman** [comment]
@andimarek correct me if I am wrong but the coming graphql spec says that unused scalars should not be included if they are not referenced

I just tried to find that in the future spec PRs but I could not.

**Comment by bbakerman** [comment]
https://github.com/graphql-java/graphql-java/issues/1760 references the work we did for future spec compliance

**Comment by sachindshinde** [comment]
@bbakerman 
As far as I can tell from the relevant section of the coming spec
https://github.com/graphql/graphql-spec/blob/master/spec/Section%203%20--%20Type%20System.md#scalars

There's two parts here:
> When returning the set of types from the __Schema introspection type, all referenced built-in scalars must be included. If a built-in scalar type is not referenced anywhere in a schema (there is no field, argument, or input field of that type) then it must not be included.

for introspection, and
> When representing a GraphQL schema using the type system definition language, all built-in scalars must be omitted for brevity.

for SDL.

Neither of them talks about custom scalars, only built-in scalars.

**Comment by bbakerman** [comment]
thanks for that

I am looking at the current master code and I can see

```
    /**
     * We build the query / mutation / subscription path as a tree of referenced types
     * but then we build the rest of the types specified and put them in as additional types
     *
     * @param buildCtx the context we need to work out what we are doing
     *
     * @return the additional types not referenced from the top level operations
     */
    private Set<GraphQLType> buildAdditionalTypes(BuildContext buildCtx) {
        Set<GraphQLType> additionalTypes = new LinkedHashSet<>();
        TypeDefinitionRegistry typeRegistry = buildCtx.getTypeRegistry();
        typeRegistry.types().values().forEach(typeDefinition -> {
            TypeName typeName = TypeName.newTypeName().name(typeDefinition.getName()).build();
            if (typeDefinition instanceof InputObjectTypeDefinition) {
                if (buildCtx.hasInputType(typeDefinition) == null) {
                    additionalTypes.add(buildInputType(buildCtx, typeName));
                }
            } else {
                if (buildCtx.hasOutputType(typeDefinition) == null) {
                    additionalTypes.add(buildOutputType(buildCtx, typeName));
                }
            }
        });
        typeRegistry.scalars().values().forEach(scalarTypeDefinition -> {
            if (ScalarInfo.isGraphqlSpecifiedScalar(scalarTypeDefinition.getName())) {
                return;
            }
            if (buildCtx.hasInputType(scalarTypeDefinition) == null && buildCtx.hasOutputType(scalarTypeDefinition) == null) {
                additionalTypes.add(buildScalar(buildCtx, scalarTypeDefinition));
            }
        });
        return additionalTypes;
    }
```

I havent written any tests but code inspection seems to lead to unreferecned scalars being included as additonal types

I need to do more tests on master

**Comment by sachindshinde** [comment]
Ah, that's my mistake, sorry for the confusion. I was looking at `14.0`, and not `master`. That does indeed look like the right code on `master`.

I'll close out this issue, since it looks like it's been fixed.
