### ISSUE TITLE
DefaultValueUnboxer.unboxValue for nested Optional

### ISSUE THREAD

**Issue by dugenkui03** [graphql-java/graphql-java#1837]
is it necessary to make 'unboxValue' recursive,in case of nested 'Optional':
```
 def result = Optional.of(Optional.of("a"))
```

the new method just like that:
```
 public static Object unboxValue(Object result) {
        if (result instanceof Optional) {
            Optional optional = (Optional) result;
            if (optional.isPresent()) {
//                return optional.get();
                return unboxValue(optional.get());
            } else {
                return null;
            }
        }
```

**Comment by bbakerman** [comment]
> def result = Optional.of(Optional.of("a"))

That is to say this is an optional value that may or may not contain a optional value that may or may not contain a value?

I have to say this is pretty weird.

`java.util.Optional#flatMap` ?

**Comment by andimarek** [comment]
I am not sure we want to support such a case: you can always register your own ValueUnboxer if needed.

@dugenkui03 can you give us a bit more insight how/why a nested Optional might occur? thanks

**Comment by dugenkui03** [comment]
@bbakerman @andimarek Thanks for your reply. Nested Optional may be weird and shouldn't occur,but it is acceptable for DefaultValueUnboxer.unboxValue,and it will effect the preciseness for the purpose of ValueUnboxer.unbox.

I notice that unboxMethod seem always to be recursive,such as GraphQLTypeUtil.unwrapAll and Wrapper Classes in Java.
