### ISSUE TITLE
Add JavaDoc to Github Pages branch and add link from README

### ISSUE THREAD

**Issue by aschrijver** [graphql-java/graphql-java#184]
This is a follow-up issue for #24 to have TravisCI generate and commit JavaDoc HTML pages on a `gh-pages` branch to expose it as a Github Pages site and then include a link to it from the README for reference.

**Comment by markphilpot** [comment]
Github recently allowed sites to be run out of a `docs` directory on master rather than a `gh-pages` branch which makes the build pipeline much easier.  I'll take this one on.

**Comment by aschrijver** [comment]
Oh, that is cool. Wasn't aware of that feature. Thanks.

**Comment by markphilpot** [comment]
So some options:

the github page contains:
A) The latest javadocs
B) The javadocs for the last release
C) Javadocs for all previous releases including `latest`

For whatever reason I rarely use javadocs so I'm not sure what's most useful for everyone. I'm also making the assumption that the main README.md continues to be the focus for documentation rather than trying to set up a jekyll site.

If we go A) then I'll just use the new convention of the `docs` folder.  For B) or C) I'll use the gh-pages branch (makes it cleaner for on going development)

**Comment by aschrijver** [comment]
One nice thing of JavaDocs is that they often pop up before the code in Google searches. I think they are used by many people in that way, where they take a quick peek when they hear mention of a class, then continue being productive :wink: again.

A) does not seem a good option. Users of JavaDoc are most typically using a stable release
On the other 2: B) is nice and C) even nicer, but probably more work to configure?

**Comment by markphilpot** [comment]
C) Isn't that bad. I wasn't going to try to do a travis auto commit for the latest so it will just be a manual periodic thing (I'll manage that for now).  Let me get a PR together and see what you think.

**Comment by aschrijver** [comment]
:+1: Yeah best be KISS and add it to release procedure.

**Comment by markphilpot** [comment]
Check out the project page and let me know what you think :: http://graphql-java.github.io/graphql-java/

**Comment by aschrijver** [comment]
Looks good! :+1: 
Indeed a bit minimalistic, but that's no problem. Is the link in the footer the only way back to the main project page, or will that be the page header title as well after committing.
Alternatively (or in addition) there can be a 'latest' entry under releases that drops you off at the main project page.

**Comment by markphilpot** [comment]
Try it now and see if that checks all the boxes.

**Comment by aschrijver** [comment]
Bit late. But even though workaholic today was too nice weather in Netherlands :smile:
It looks really nice @markphilpot . Nice job!@

**Comment by markphilpot** [comment]
Sounds good!
