### ISSUE TITLE
Creating FieldCoordinates can have an impact on performance

### ISSUE THREAD

**Issue by fvilla-amazon** [graphql-java/graphql-java#1845]
Currently, FieldCoordinates.coordinate(String type, String fieldName), and similarly FieldCoordinates.systemCoordinates, can be expensive to use at runtime, especially in instrumentation.  This is because they perform validation on the input that checks the string and also applies regular expressions on the string input.  This is definitely needed when loading things from the schema or manually constructing these objects from unknown sources.

However, if the inputs are coming from strings that have already been validated, it would be good to have a boolean option to allow developers to state they trust the source and circumvent the validation.  In our case, we were implementing the field-based instrumentation methods and using FieldCoordinates to look up the field's data fetcher.  This was causing a significant degradation in performance.  We had to implement a workaround which saw our TPS values go up anywhere from 20% to 200% depending on the queries being run.

We plan on contributing a PR that allows passing in a flag to the FieldCoordinate creation methods to disable validation.  We plan on also keeping the original method with the validation enabled to allow the existing code to remain unaffected.

**Comment by andimarek** [comment]
closing this issue at it is addressed by #1846
