### ISSUE TITLE
Consider adding support for GraphQL comments to SDL creation

### ISSUE THREAD

**Issue by tmiddlet2666** [graphql-java/graphql-java#1848]
Currently graphql-java does not appear to support the GraphQL spec around comments.

See http://spec.graphql.org/June2018/#sec-Comments

This would be a useful documentation addition.

**Comment by andimarek** [comment]
we are fully supporting comments. What do you mean exactly?

**Comment by tmiddlet2666** [comment]
@andimarek Sorry i should have been more clear.
I mean in the SDL definition.
E.g. in the following
```  
GraphQLObjectType simpsonCharacter = newObject()
    .name("SimpsonCharacter")
    .description("A Simpson character")
    .field(newFieldDefinition()
            .name("name")
            .description("The name of the character.")
            .type(GraphQLString))
    .field(newFieldDefinition()
            .name("mainCharacter")
            .description("One of the main Simpson characters?")
            .type(GraphQLBoolean))
    .build();
```

I can't do
```
GraphQLObjectType simpsonCharacter = newObject()
    .name("SimpsonCharacter")
    .comment("this is a comment") // <-- HERE
    .description("A Simpson character")
``

**Comment by andimarek** [comment]
I don't think we will add this:

Comments are a pure SDL/Query level construct and I think introducing comments on this level would be a mistake. (If you want to comments something in Java use Java comments. If you want to comments something in a SDL use GraphQL comments).

(Note: Historically comments have been used to document things, but after descriptions were introduced comments are nowadays only useful on the AST level.)

**Comment by kaqqao** [comment]
Maybe add a hook to the `SchemaPrinter` so that custom comments can be added to the print-out? Sounds like it would satisfy the use-case in mind (add comments for programmatically assembled schema).
