### ISSUE TITLE
LocalContext are shared between two parallel queries with alias.

### ISSUE THREAD

**Issue by yuhanz** [graphql-java/graphql-java#1852]
**Describe the bug**
I have a resolver that query for a list of object, filter by the input parameter. The resolver also stores the input parameter in LocalContext (so that the child resolver below the query remember its query context). However, when two queries at the same levels are made, separated by alias names, I found out that the LocalContext is unexpectedly shared in the two sibling queries, instead of being "local" to its own branch.

In my example, I am querying the `positive` topics and the `negative` topics at the same depth of the tree, and my .topics resolver records the polarity POSITIVE in the LocalContext at the query for pros, and this value POSITIVE is passed to the query for cons through LocalContext. This is unexpected as the cons query is not under the local context of the pros query.

```
Query {
  pros: topics(polarity: "POSITIVE") {
    displayName
    polarity
  }
  cons: topics(polarity: "NEGATIVE") {
    displayName
    polarity
  }
}
```

**To Reproduce**
Let the DataFetcher be the following
```
dataFetchingEnvironment -> {
  GraphQLContext localContext = env.getLocalContext();
  String polarity = Optional.<String>ofNullable(localContext.get("polarity"))
        .orElse(PolarityFilter.valueOfOrNull(env.getArgument("polarity")));
  localContext.put("polarity", polarity);
  return Arrays.asList(new Topic("testDisplayName", polarity));
}
```
When making the query above, polarity showed as POSITIVE in both queries for `pros` and `cons`. This is on graphql-java 13.0

**Comment by bbakerman** [comment]
Thanks for reporting - we will look into this

**Comment by andimarek** [comment]
@yuhanz You are using a `GraphQLContext` as `localContext` which is not what it should be used for. A `GraphQLContext` is basically a mutable map and you are sharing it across multiple `DataFetcher` and you mutate `polarity`. 
So the first `DataFetcher` is called and changes "polarity". Then the second is called and overrides the same "polarity" value. 

If you want to mutate your localContext you have to always make a copy of it and return a new localContext which then will be passed down to the children.

I hope that helps.

**Comment by yuhanz** [comment]
@andimarek : My intuition of `localContext` a `Map` is shared between one  `DataFetcher` and its child nodes, as being a context _local_. This context is not shared with its siblings `DataFetcher`s , including alias, nor for `DataFetcher`s on the other branches. Meanwhile a (global) `context` is shared in every `DataFetcher`. With this definition, the behavior of a sibling `DataFetcher` getting the mutated `LocalContext` is unexpected, as the `LocalContext` is no longer _local_

However, I got your work around of explicitly creating a copy of the `LocalContext` when modification is involved. This should work, too.
```
dataFetchingEnvironment -> {
  GraphQLContext localContext = env.getLocalContext();
  GraphQLContext childLocalContext = GraphQLContext.newContext().build();
  childLocalContext.putAll(localContext);

  String polarity = Optional.<String>ofNullable(localContext.get("polarity"))
        .orElse(PolarityFilter.valueOfOrNull(env.getArgument("polarity")));
  localContext.put("polarity", polarity);
  Object data = Arrays.asList(new Topic("testDisplayName", polarity))
  return DataFetcherResult.newResult()
                    .data(vehicleReviewGraphQLService.getReviews(vehicleReviewsQuery))
                    .localContext(childContext)
                    .build(); ;
}
```
