### ISSUE TITLE
DefaultForNonNullArgument validation rule

### ISSUE THREAD

**Issue by xma000** [graphql-java/graphql-java#1853]
graphql-java has this validation rule `DefaultForNonNullArgument` but I didn’t find it in the GraphQL spec. Basically, a client wants to send a query like the following but setting a default value to a non-null type is not allowed.
```
query ($id: ID! = "123") {
 order(id: $id) {
   name
 } 
}
```

Relevant code is at https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/validation/rules/VariableDefaultValuesOfCorrectType.java#L28. BTW, the error message "Missing value for non null type" seems to be incorrect.

**Comment by andimarek** [comment]
closing this issue: we are tracking it in https://github.com/graphql-java/graphql-java/issues/1870
