### ISSUE TITLE
Return POJO instead of LinkedHashMap

### ISSUE THREAD

**Issue by bugy** [graphql-java/graphql-java#1855]
Dear all,
I'm trying to use graphql-java for loading a graph of in-memory java objects and doing some transformations on them (e.g. exporting to CSV). 
When I use `graphql.execute(ExecutionInput)`, it always provides a list of nested `LinkedHashMap`s
However, I would prefer having results as POJOs.

I dig a little bit into the code, and found, that the results are aggregated in `AbstractAsyncExecutionStrategy#handleResults`. So I decided to implement a custom strategy, which would build POJO directly.
However, I don't see any way, how to know, which output class it should be. I could take it from the current `ExecutionPath` (which is available in `ExecutionStrategyParameters`), but `handleResults` doesn't have this parameter.

So, my questions are:
1. Is there any way to get current ExecutionPath in `handlerResults`?
2. Is there any other way to produce POJO instead of LinkedHashMap?

PS thanks a lot for the wonderful library!

**Comment by bbakerman** [comment]
I am not sure that returning POJOs is the right thing to do.

graphql is a system where the consumer indicates what data they want.  They may ask for 6 fields or 2.  They may ask for it down 3 levels or 1.

The map approach we use (where ExecutionResult is a temporary holder and converted into a map as we descend and return up from the query level is very deliberate.

It allows

```
{
     pet {
           name
            tricks {
                  type
            }
    }
}
```

To become a map like

```
{
     "pet" :  {
           "name": "spot",
            "tricks" :  [
                  "type" : "sit"
            ]
    }
}
```

Maybe you ask for tricks in a query or maybe you dont.  The idea of this being POJOs as we execute the engine is not sensible in my opinion.

Let's say you had POJOs hypothetically.  What would you do with them?  Throw them at Jackson ObjectMapper and send them over the wire as JSON?   A Map is just as good for that, in some ways better (no reflection needed).

You say

> However, I would prefer having results as POJOs.

Can you outline your thoughts on why POJOs would help you build better graphql based software?

**Comment by bugy** [comment]
Hi @bbakerman, thanks for the detailed answer!

Let me describe the use case. On server-side, we aggregate multiple entities and build CSV from them.
The server-side code like this
```
List<Booking> bookings = bookingService.loadBookings(bookingIds);

List<Long> apartmentIds = extractApartmentIds(bookings);
List<Apartment> apartments = apartmentService.loadApartments(apartmentIds);

List<Long> apartmentOwnerIds = extractOwnerIds(apartments);
List<Account> accounts = accountService.loadAccounts(apartmentOwnerIds);

// etc.

// here is some mapping logic to transform entities into specific csv columns
List<BookingCsvRow> rows = transformToCsvRows(bookings, apartments, accounts);
writeCsv(rows, "/tmp/some_file.csv");
```

We have this pattern of loading linked entities quite often, and I thought, that GraphQL could help with reducing the boilerplate.

How I would see it:
```
List<BookingGraphql> bookings = customGraphqlGateway.load(
    BookingGraphql.class, "apartment", "apartment.owner");

// etc.

List<BookingCsvRow> rows = transformToCsvRows(bookings); 
writeCsv(rows, "/tmp/some_file.csv");
```

Where BookingGraphql is a class, which has `ApartmentGraphql apartment` field and apartment has the link to the owner
If there is a link to another entity, it will be empty (or even throw some exception on access)

In my opinion, all the primitive fields should be loaded automatically for this case. Since they are loaded from the services anyway. Mapping them will not be a huge overhead.

I think that the approach with POJOs, in this case, is cleaner and safer. You have compile-time check for field access and during development, you always know which fields are there.

I would like to use this POJO approach only in java and only in memory.
For external communication (for front-end), we will not use it, and as you said, Map will work perfectly fine there.

**Comment by bbakerman** [comment]
I am closing this question as answered

**Comment by bugy** [comment]
Hi, @bbakerman thanks for your time, but I don't think that my original question is answered in any way. In my opinion, "you don't need it" is not an answer

I would be glad to work on some PR here and make graphql-java a bit more extensible (I'm not talking about pojo implementation here). Unfortunately at the moment, I don't see any way for me to implement pojo `handleResults` for my project, apart from copypasting the whole `graphql.execution.AsyncExecutionStrategy` class.

My idea would be just to add overloaded AbstractAsyncExecutionStrategy#handleResults method, which would accept one more field: `ExecutionStrategyParameters executionParameters`

**Comment by andimarek** [comment]
@bugy we will not implement a pojo bases execution strategy: mapping data onto Java objects is an area we are deliberately not handling. 

But we want to enable other people to build things on top of graphql java. We would be open to this kind of PR your are suggesting. Please open a PR without investing to much time (you can ignore test to start with for example) and we will give you more detailed feedback.

Thanks!

**Comment by bugy** [comment]
Hi @andimarek thanks for the answer, sounds cool and perfect to me!

> we will not implement a pojo bases execution strategy

completely agree here!

**Comment by bugy** [comment]
Hi, it seems my change was reverted:
https://github.com/graphql-java/graphql-java/commit/1bd60a39e984368fb7c724360e8f072ba2c84c4f

Can we revert it please? 

CC @dugenkui03
