### ISSUE TITLE
UniqueArgumentNamesRule for duplicated arguments in query

### ISSUE THREAD

**Issue by dugenkui03** [graphql-java/graphql-java#1856]
The following should be invalid since the argument value is ambiguous.
```
            query getDogName {
              dog(arg1:"value1",arg1:"value2") {
                  name
              }           
            }
```
```
            query getDogName {
              dog(arg1:"argValue") {
                  name @include(if: true,if: false)
              }           
            }
```
UniqueArgumentNamesRule will be pretty helpful, especially when field/directive hold many arguments, which can prevent write duplicate arguments by mistakes.

The implementation in graphql-js is [UniqueArgumentNamesRule](https://github.com/graphql/graphql-js/blob/master/src/validation/rules/UniqueArgumentNamesRule.js)

**Comment by andimarek** [comment]
the PR is merged
