### ISSUE TITLE
Third party copyright header

### ISSUE THREAD

**Issue by dminkovsky** [graphql-java/graphql-java#186]
Are there any licensing implications given the header on this file?
https://github.com/graphql-java/graphql-java/blob/master/src/test/groovy/graphql/execution/batched/GraphqlExecutionSpec.groovy

**Comment by andimarek** [comment]
I don't think so: The whole project is under MIT license, but some parts are of course contributed by different people.

**Comment by dminkovsky** [comment]
Cool. Sounds good. Closing for now.
