### ISSUE TITLE
Query complexity calculation fails with NPE

### ISSUE THREAD

**Issue by paulbakker** [graphql-java/graphql-java#1865]
Calculating query complexity for the following query fails with a NullPointerException.

query Hello($name:String="Someone") {
    hello(name: $name)
}
The critical bit is the default value for the $name variable. Without a default value the NPE doesn't happen.

I've provided a test that shows the issue in PR #1862.

**Comment by felipe-gdr** [comment]
Thanks for reporting this.

Pull request #1867 tries to fix this issue.

Cheers!
