### ISSUE TITLE
Add support for Intermediate Interfaces & Generic Utility Types

### ISSUE THREAD

**Issue by redhead** [graphql-java/graphql-java#1866]
Add support interfaces extending other interfaces as described in the spec here:
https://github.com/graphql/graphql-js/pull/2084

And already implemented in graphql-js 15:
https://dev.to/mikemarcacci/intermediate-interfaces-generic-utility-types-in-graphql-50e8

**Comment by felipe-gdr** [comment]
This is a duplicate of #1764

**Comment by redhead** [comment]
Damn, I am sure the search didn't show me that yesterday. Sorry.
