### ISSUE TITLE
Use https in docs

### ISSUE THREAD

**Issue by benmccann** [graphql-java/graphql-java#1873]
https://www.graphql-java.com/documentation/v14/getting-started/ should replace `http://dl.bintray.com` with `https://dl.bintray.com`

See https://max.computer/blog/how-to-take-over-the-computer-of-any-java-or-clojure-or-scala-developer/

**Comment by felipe-gdr** [comment]
I've cloned this issue in the `graphql-java-page` repo and got a PR ready:

https://github.com/graphql-java/graphql-java-page/pull/33
