### ISSUE TITLE
High cpu utilization by PropertyDataFetcher#getPropertyValue method when getter functions on objects are not present

### ISSUE THREAD

**Issue by schandrasekhar** [graphql-java/graphql-java#1874]
In our application we are noticing high cpu utilization by PropertyDataFetcher when getter functions are not present in the java objects. Have narrowed it down to this code specifically

https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/schema/PropertyDataFetcherHelper.java#L52

In our case since there are no getter functions it goes through all the fallbacks and then gets the data from `FIELD_CACHE`. 
In the experiments that we have run keeping everything constant if we add getters to java objects the CPU reduces by 100%. Will try to get a simple example to reproduce the issue with profiler data. 
The ask is can `getPropertyValue` method first look into the `METHOD_CACHE` and `FIELD_CACHE` and then try to calculate the method (or) attribute? This will prevent it from going through multiple fallbacks

I can create a pr for this if needed. Will also attach a reproducible example once I have it

**Comment by jmt212** [comment]
I think this may be a duplicate of an issue I raised about a month or so ago.

https://github.com/graphql-java/graphql-java/issues/1812

There's a PR out to address this: https://github.com/graphql-java/graphql-java/pull/1815

**Comment by schandrasekhar** [comment]
i see.. thanks will close this.
