### ISSUE TITLE
Instrumentation for metrics

### ISSUE THREAD

**Issue by xma000** [graphql-java/graphql-java#1875]
Is there a metrics instrumentation available that works with statsd? Like REST metrics, it should include typical metrics like count, error count and response time for each top-level query or mutation field.

**Comment by felipe-gdr** [comment]
GraphQL Java does not implement such instrumentations out-of-the-box. It shouldn't be hard to implement it yourself in your project, though ;-) 

In case you haven't see it, here are the docs about instrumentation in GraphQL Java V14: https://www.graphql-java.com/documentation/v14/instrumentation/

Cheers!

**Comment by bbakerman** [comment]
I am closing this issue as answered
