### ISSUE TITLE
Emoji doesn't survive

### ISSUE THREAD

**Issue by neelkamath** [graphql-java/graphql-java#1877]
**Describe the bug**
When I send an emoji in a GraphQL query, it is replaced with random symbols when I access it via `DataFetchingEnvironment.getArgument()`.

**To Reproduce**
With an HTTP request like:
```http
POST http://localhost:80/graphql HTTP/1.1
Content-Type: application/json

{
  "query": "mutation ($title: String!) { createGroupChat(title: $title) }",
  "variables": {
    "title": "😀 My Group"
  }
}
```
Accessing the **title** like:
```java
System.out.println("title: " + env.getArgument<String>("title"))
```
Gives output like:
```
title: ð My Group
```
This is a simplified version of my actual Kotlin code, so please ignore small grammatical issues.

**Comment by andimarek** [comment]
hi @neelkamath: this is very likely an encoding problem around GraphQL javaPlease make sure that the String passed as Query/Variable into the GraphQL engine is correct: I suspect it its not. 

Depending on what Framework you are using around GraphQL Java you might want to file an Issue with them. This project is the core engine and doesn't deal with JSON serialization and transport layers.

If you are convinced it is an problem with GraphQL Java please try to recreate with a minimal setup: just GraphQL Java engine execution without JSON/HTTP. 

Thanks

**Comment by neelkamath** [comment]
Emoji was working fine until I switched to GraphQL. After making a minimal example, I see that **GraphQL Java** is not the issue. The only other new library I used was **ktor GraphQL**, which despite it doing almost nothing, would appear to be the issue then. Thanks for your time.
