### ISSUE TITLE
Getting an empty objects when queries an interface with inline fragment only upon one of the interface implementation entity types

### ISSUE THREAD

**Issue by itaykl** [graphql-java/graphql-java#1883]
**Describe the bug**
I have an interface entity type called "X", which has 2 entity types which implements this interface called "Y" and "Z". When I execute a query that fetches "X's" and inside the query i use inline fragment only upon "Y" entity with field that only "Y" has and regardless of the "Z" entity at all, I get a result with empty objects(that probably represents the "Z" entities that returned although i don't want any of the "Z" entities to return).

**To Reproduce**
The "X" entity type:
```
interface Character {
episodes: [Episode]
friends: [Character]
id: Long
name: String
}
```

The "Y" entity type:
```
type Human implements Character {
episodes: [Episode]
friends: [Character]
id: Long
name: String
homePlanet: String
}
```

The "Z" entity type:
```
type Droid implements Character {
episodes: [Episode]
friends: [Character]
id: Long
name: String
primaryFunction: String
}
```

The query i use:
`heroes(episode: Episode): [Character]`

So when i query this:
```
  heroes(episode: RETURN_OF_THE_JEDI){
    ...on Human{
      homePlanet
    }
  }
```

I get this:
```
{
  "data": {
    "heroes": [
      {
        "homePlanet": "TATOOINE"
      },
      {
        "homePlanet": "TATOOINE"
      },
      {
        "homePlanet": "TATOOINE"
      },
      {
        "homePlanet": "ALDERAAN"
      },
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {}
    ]
  }
}
```

**Comment by andimarek** [comment]
this is correct GraphQL behavior according to the spec: because your fragment condition doesn't match no field is selected/returned, but that doesn't mean the whole object is removed. Therefore you get an empty object. Hope that helps.
