### ISSUE TITLE
[feature] typesafe arguments

### ISSUE THREAD

**Issue by benmccann** [graphql-java/graphql-java#1887]
Right now to get arguments to the API, it looks something like this:

```
public class UserDataFetcher implements DataFetcher<UserResponse> {

    @Override
    public UserResponse get(DataFetchingEnvironment env) {
        String arg1 = environment.getArgument("arg1");
        Integer arg2 = environment.getArgument("arg2");
        ...
    }

}
```

The danger here is that if you typo `arg1` or `arg2` you don't know it until runtime. Or if you get the type wrong you don't know it until runtime. Both these problems make refactoring and maintaining a large codebase harder.

We could solve this by doing something like:

```
public class UserDataFetcher implements TypedDataFetcher<UserRequest, UserResponse> {

    @Override
    public UserResponse get(UserRequest requestArgs, DataFetchingEnvironment env) {
        String arg1 = requestArgs.getArg1();
        Integer arg2 = requestArgs.getArg2();
        ...
    }

    public static class UserRequest {
        private String arg1;
        private Integer arg2;

        public UserRequest(String arg1, Integer arg2) {
          this.arg1 = arg1;
          this.arg2 = arg2;
        }

        public getArg1() {
          return arg1;
        }

        public getArg2() {
          return arg2;
        }
    }

}
```

Users could use something like @kobylynskyi's [graphql-java-codegen](https://github.com/kobylynskyi/graphql-java-codegen) to generate the request args object from schema if they'd like to cut down on writing boilerplate.

----

Edit: It looks like [graphql-java-tools](https://www.graphql-java-kickstart.com/tools/schema-definition/#input-objects) does this

**Comment by zcourts** [comment]
@benmccann I agree with the argument but it shouldn't result in it being impossible to do         `String arg1 = environment.getArgument("arg1");` - in our usage of graphql-java, we have no idea what the argument names or types are at compile time because our platform let's customers provide their own schemas. Requiring `getArg1()` would prevent us using the lib without a fork or some workaround.

**Comment by benmccann** [comment]
Yeah, that's a good point. It should be optional to use the typed interface and still have the existing untyped interface available in case the schema is only available at runtime and not compile time

**Comment by andimarek** [comment]
We understand that a lot of users want to have a more "Java like arguments". But we decided quite a while ago that is not the scope of this library: main reason is that it is non trivial and we don't think there is one universal solution. 

Other libraries on top of GraphQL Java tackle this problem in different ways. I recommend to ask in our GraphQL Java spectrum chat for recommendations: https://spectrum.chat/graphql-java.
