### ISSUE TITLE
GraphQLTypeUtil.unwrapAll throws ClassCastException if the type is a reference

### ISSUE THREAD

**Issue by zcourts** [graphql-java/graphql-java#1889]
Appears we're using v11 but this code appears to be the same in latest and `GraphQLTypeReference` still doesn't extend `GraphQLUnmodifiedType`.

```
java.lang.ClassCastException: class graphql.schema.GraphQLTypeReference cannot be cast to class graphql.schema.GraphQLUnmodifiedType (graphql.schema.GraphQLTypeReference and graphql.schema.GraphQLUnmodifiedType are in unnamed module of loader 'app')
```
similar to https://github.com/graphql-java/graphql-java/issues/1634

**Comment by bbakerman** [comment]
I had a look at this one.  Yeah the method signature is indeed returning `GraphQLUnmodifiedType`

```
    public static GraphQLUnmodifiedType unwrapAll(GraphQLType type) {
```

and a `GraphQLTypeReference` is not one of those

`public class GraphQLTypeReference implements GraphQLNamedOutputType, GraphQLNamedInputType`

We could change the method return type (say to `GraphQLNamedType`) but this is a breaking change or we could make `GraphQLTypeReference` be a `GraphQLUnmodifiedType` but I am not sure thats quite right.

Fact is you only get `GraphQLTypeReference` in place if you have hand built the type.  Once its be made into a schema the type is modified and all references are replaced.  So in practice the scope of this small in a production sense.

Also the work around is to use

```
    public static <T extends GraphQLType> T unwrapAllAs(GraphQLType type) 
```

It can unwrap as any type.

I think we should close this issue as not worth fixing (eg not worth the breaking change it will involve)
