### ISSUE TITLE
Add code coverage and static analysis to the project

### ISSUE THREAD

**Issue by aschrijver** [graphql-java/graphql-java#189]
Well, the analysis is a bit less important, but would be nice to see the test coverage of the project.

With code coverage integrated the percentage could be displayed in a shield on the README 
I recently started using Codacy for this myself which is free for open-source projects and has a nice dashboard (See [vertx-graphql-service-discovery README](https://github.com/engagingspaces/vertx-graphql-service-discovery/blob/master/README.md) for example). But there are others as well.

(PS Didn't run coverage locally yet, but am curious to what figure the percentage amounts).

**Comment by markphilpot** [comment]
A service I use on my other projects is https://coveralls.io/

**Comment by aschrijver** [comment]
Yes, I think that will do the job just as well.

**Comment by andimarek** [comment]
sorry, this is not planned currently: we just have enough other things to do. I hope you understand.

But if you would create PR, we will of course consider it.

Thanks!
