### ISSUE TITLE
Wiring unions of enums is impossible

### ISSUE THREAD

**Issue by ericvergnaud** [graphql-java/graphql-java#1892]
**Describe the bug**
GraphQL SDL legally supports unions of scalars or enums.
Type resolution in GraphQL Java only supports GraphQLObjectType, which make it impossible to resolve union types of non object types.

**To Reproduce**

`
enum Animal {
    DOG
}

enum Vegetal {
    TREE
}

union Thing = Animal | Vegetal
`
GraphQL java parses the above SDL successfully.
But when wiring it, it is impossible to resolve Thing to Animal or Vegetal because TypeResolver returns a GraphQLObjectType.

This is a hot topic, see https://github.com/graphql/graphql-spec/issues/215

**Comment by andimarek** [comment]
GraphQL doesn't support union of non objects (at least at the moment), there we don't intent to change this behavior. In general we only support what the spec says (or in some cases things that the spec will cover soon)
