### ISSUE TITLE
Feature Request: Graphql Client

### ISSUE THREAD

**Issue by bkuberek** [graphql-java/graphql-java#1894]
Hi,

We started incorporating graphql in our backend systems and it works great for javascript clients, however, we don't have a good solution for server to server communication.

Currently we have to make custom graphql clients that are very domain specific and there is a lot of code and schema duplication everywhere in order to make this work.

It would be great if this project offered a client that can be used to call upstream graphql services. It should handle request creation, request execution, error handling, and response processing.

**Comment by khanactl** [comment]
http is served and you slurp http as a client.  graphql-java’s job is met.

-JP

**Comment by andimarek** [comment]
we understand that our users sometimes want a GraphQL client, but I want to be honest: this is outside of the current scope and current capabilities of this team.

Please have a look at https://spectrum.chat/graphql-java/general/graphql-client-java~dd8c7ce0-e962-46a7-83e1-d18e6fb7ff34 and https://spectrum.chat/graphql-java/general/graphql-java-client~3356e57e-f2ee-4bd5-9522-209a2af7ecd0 for other projects which tries to solve this problem.

thanks!
