### ISSUE TITLE
Suggestion for DataLoaderRegistry API

### ISSUE THREAD

**Issue by benmccann** [graphql-java/graphql-java#1900]
I have a long list of calls that looks like this to register:

```
    dataLoaderRegistry.register(
        PostBatchLoader.class.getSimpleName(), DataLoader.newDataLoader(postBatchLoader));
    dataLoaderRegistry.register(
        UserBatchLoader.class.getSimpleName(), DataLoader.newDataLoader(userBatchLoader));
```

And then when calling:

```
    DataLoader<String, User> userBatchLoader =
        env.getDataLoader(UserBatchLoader.class.getSimpleName());
```

Could we simplify the interface so that it was the following:

```
    // registering
    dataLoaderRegistry.register(DataLoader.newDataLoader(postBatchLoader));
    dataLoaderRegistry.register(DataLoader.newDataLoader(userBatchLoader));

    // calling
    DataLoader<String, User> userBatchLoader = env.getDataLoader(UserBatchLoader.class);
```

I don't quite understand why the current API requires two arguments. Is there ever a time when users would want to register more than one of the same batch loader type?

Is the name used in debug logs / stats? If so, I think a good default would be the simple name, but use the fully qualified name if you have two with the same name in different packages?

**Comment by bbakerman** [comment]
DataLoaderRegistry is a glorified map `private final Map<String, DataLoader<?, ?>> dataLoaders = new ConcurrentHashMap<>();`

So we expose a map like API for that reason.  

You suggestion calls for the schema to be "class based".  This works well in a lot of cases but String is one of the most perfect keys in a general sense.

I dont think there is enough return on investment to make this change

**Comment by mxmlnglt** [comment]
> This works well in a lot of cases but String is one of the most perfect keys in a general sense.

... except when you have so-called duplicates, e.g. Classes which have the same "simple name"...

**Comment by benmccann** [comment]
It doesn't necessarily have to use classes internally. It could just call `getName()` to convert the class to a `String` and use the `String` internally. It would just be a convenience API that allowed accepting either type and would do the conversion for you
