### ISSUE TITLE
DataLoaderRegistry inefficiency

### ISSUE THREAD

**Issue by benmccann** [graphql-java/graphql-java#1902]
The `DataLoaderRegistry` should be request-scoped. That means that users are creating every `DataLoader` for every request even if none or only one or two are used.

Right now we would do something like:
```
    dataLoaderRegistry.register("user", DataLoader.newDataLoader(userBatchLoader));
```

We could probably fix this by making `DataLoaderReigstry` a singleton and instead registering a function that would provide a `DataLoader`:
```
    dataLoaderRegistry.register("user", () -> DataLoader.newDataLoader(userBatchLoaderProvider.get()));
```

**Comment by bbakerman** [comment]
This makes a lot of sense.  DataLoaderRegistry is in the https://github.com/graphql-java/java-dataloader code base.

I have raised this issue there as well

https://github.com/graphql-java/java-dataloader/issues/67

**Comment by bbakerman** [comment]
I looked into this and it's really kinda pointless.

We can make it lazy but as soon as you called `dispatchAll` the it needs to materialise the dataloaders and dispatch them

We would have to write a fancy MemoizingSupplierWithTracking that could decide if its every been asked for and then filter them out from the list. In short I am not sure that its worth it.

I would love to see more evidence now of the costs of creating a DL even if its not needed in a certain graphql request.
