### ISSUE TITLE
DataFetcher isn't called? 

### ISSUE THREAD

**Issue by danielschonfeld** [graphql-java/graphql-java#192]
I have the following schema:

```
query { 
  viewer {
    someInfo(type:X,id:500) {
        name
        address
    }
  }
}
```

I have modelled it so that the arguments `type` and `id` are put on the someInfo `GraphQLObject` and so is the `dataFetcher()`.  I start my java server in debug, breakpoint inside my `DataFetcher` and nothing.  

Is there a reason for that? Am I missing something really obvious or is this a bug?

I am using the `viewer` object to get over the limitation of relay JS allowing only 1 or 0 arguments in root queries.

**Comment by dminkovsky** [comment]
Hi Daniel,

Could you please post your schema definition code? Hard to tell without
seeing that.

Thanks

среда, 24 августа 2016 г. пользователь Daniel Schonfeld написал:

**Comment by danielschonfeld** [comment]
@dminkovsky sure!

```
public class SomeInfoTestSchema {
    public GraphQLSchema getSchema() {
        return schema;
    }

    private GraphQLSchema schema;

    public SomeInfoTestSchema() {
        GraphQLObjectType queryType = newObject()
                .name("Query")
                .description("A query")
                .field(newFieldDefinition()
                        .name("viewer")
                        .type(viewerType())
                        .build()
                )
                .build();

        schema = GraphQLSchema.newSchema()
                .query(queryType)
                .build();
    }

    private GraphQLObjectType viewerType() {
        return newObject()
                .name("Viewer")
                .field(
                    newFieldDefinition()
                    .name("someInfo")
                    .type(someInfoType())
                    .argument(Lists.newArrayList(
                            newArgument()
                                    .name("type")
                                    .type(new GraphQLNonNull(depthType()))
                                    .build(),
                            newArgument()
                                    .name("id")
                                    .type(new GraphQLNonNull(GraphQLInt))
                                    .build()
                    ))
                    .dataFetcher(new SomeInfoFetcher())
                    .build()
                )
                .build();
    }

    private GraphQLObjectType someInfoType() {
        return newObject()
                .description("Some Random Info")
                .name("SomeInfo")
                .field(
                        newFieldDefinition()
                        .name("id")
                        .description("id")
                        .type(GraphQLInt)
                        .build()
                )
                .field(
                        newFieldDefinition()
                        .name("name")
                        .description("Name")
                        .type(GraphQLString)
                        .build()
                )
                .field(
                        newFieldDefinition()
                        .name("type")
                        .description("type of info")
                        .type(depthType())
                        .build()
                )
                .field(
                        newFieldDefinition()
                        .name("address")
                        .description("address")
                        .type(GraphQLString)
                        .build()
                )
                .field(
                        newFieldDefinition()
                        .name("hobby")
                        .type(GraphQLString)
                        .build()
                )
                .build();
    }
    private GraphQLEnumType depthType() {
        return newEnum()
                .name("DepthType")
                .description("depth inspection level")
                .value("BASIC")
                .value("DETAILEDPLUS")
                .build();
    }

}
```

Tested with the following query:
```
query {
  viewer {
    someInfo(type:BASIC,id:500) {
      name
    }
  }
}
```

**Comment by dminkovsky** [comment]
Thanks for the source. How are you executing the query? What is the `source` argument? 

What is the result?

**Comment by danielschonfeld** [comment]
@dminkovsky do you mean you want my DataFetcher class implementation?

where is the `source` argument? if you mean the one in `DataFetchingEnvironment` i don't know since it nevr gets invoked according to my breakpoint in the debugger.

**Comment by dminkovsky** [comment]
@danielkwinsor not interested so much your leaf data fetcher implementation as the ones that lead up to that leaf, and the `source`. By `source` I mean the `context` parameter that you can pass to `GraphQL#execute()`. This is the object against which the query is first executed against. 

Are you getting `null` as the result?

**Comment by danielschonfeld** [comment]
@dminkovsky I am indeed getting `null` as the result.  The source i'm passing to the `GraphQL#execute()` is what I pasted above below my java code.

It's passed via Spring as in your example on the README.MD or the `todomvc-java-graphql`

Here's some logging to the console from running it:
```
2016-08-24 19:58:17.174  INFO 30352 --- [nio-9090-exec-8] graphql.GraphQL                          : Executing request. operation name: null. Request: query {
  viewer {
    someInfo(type:BASIC,id:500) {
      name
    }
  }
} 
2016-08-24 19:58:17.175  INFO 30352 --- [nio-9090-exec-8] c.g.g.controllers.GraphQLController      : RETURNED: {viewer=null}
```

The RETURNED statement is an additional log statement i added.

**Comment by dminkovsky** [comment]
So something is going wrong before your data fetcher is reached. Some debug suggestions:

1. You can examine the result of `GraphQL#execute()` to see if there is an error. I bet you'll get something here.
2. You can implement a data fetcher at each level and debug step through these data fetchers to see which fails. I suspect this won't be necessary as your error will likely crop up in 1.

**Comment by danielschonfeld** [comment]
@dminkovsky just checked (1), the `ExecutionResult` has 0 errors.

how do I go about (2)?

**Comment by dminkovsky** [comment]
@danielschonfeld just as you did above with `.dataFetcher(SomeInfoFetcher())`:

```
.dataFetcher((env) -> {
   // break here 
})
```

at every level, starting from your viewer field. Your result has `viewer==null` so if you have no errors, that data fetcher is returning `null`.

**Comment by danielschonfeld** [comment]
@dminkovsky but what would we be checking doing this? we'll only learn which datafetcher gets invoked (which i'm pretty sure is the first level only... the viewer type). But aside from learning that, what else would we learn or are we looking for?

**Comment by dminkovsky** [comment]
@danielschonfeld that the data fetcher is returning something. If it returns null, that's the end of that tree.

**Comment by danielschonfeld** [comment]
@dminkovsky so anytime null is returned the execution stops trying other datafetchers? and if i dont have any datafetchers as I do, what would be returning that null?

**Comment by danielschonfeld** [comment]
@dminkovsky i just checked, since there's only one place to check and indeed if you add dataFetcher() on the viewer field it breaks in there.  `source` and `arguments` are empty tho.

**Comment by dminkovsky** [comment]
> so anytime null is returned the execution stops trying other datafetchers

Yeah, that's a general GraphQL thing (not specific to this implementation). If you return null, it can't keep going.

> and if i dont have any datafetchers as I do, what would be returning that null?

https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/schema/PropertyDataFetcher.java, which is the [default implementation of `DataFetcher` used when none is provided](https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/schema/GraphQLFieldDefinition.java#L144).

**Comment by danielschonfeld** [comment]
@dminkovsky ok so indeed `PropertyDataFetcher` is broken into and because `source` is null it returns null thus stopping the execution.

What does that teach us/me? Can I do something? is this by design? am I using GraphQL wrong?

**Comment by dminkovsky** [comment]
> ok so indeed PropertyDataFetcher is broken into and because source is null it returns null thus stopping the execution.

Cool, that's what I was thinking.

> What does that teach us/me? Can I do something? 

Implement data fetchers where necessary. If you want to keep going down a tree while returning an empty value for a field's source, return anything but null.

> is this by design?

Yeah, that's how GraphQL is [currently specified](http://facebook.github.io/graphql/#sec-Field-entries). `null` means that sub-tree is over. 

> am I using GraphQL wrong?

Nope, just implement a data fetcher where the default one is not to your liking.

**Comment by danielschonfeld** [comment]
@dminkovsky so you're saying I'd implement something like like DataFetcher for viewer that returns lets say `Maps.newHashMap();` ??

**Comment by dminkovsky** [comment]
@danielschonfeld yeah, basically. It's not pretty, but you're passing `null` to `#execute()`, and then you're using the default data fetcher implementation to read a property off of that ` null`. That won't take you very far in terms of resolving a nested tree of data, which is what GraphQL is all about :)

**Comment by danielschonfeld** [comment]
@dminkovsky you're right it's not pretty, but it makes sense and works! Thank you very much!

**Comment by dminkovsky** [comment]
Great! You're welcome!

среда, 24 августа 2016 г. пользователь Daniel Schonfeld написал:
