### ISSUE TITLE
SDL extended enum values considered invalid for use in directive argument

### ISSUE THREAD

**Issue by jimkyndemeyer** [graphql-java/graphql-java#1937]
**Describe the bug**
15.0 doesn't recognize extended enum values when they're used in directive arguments.

The following schema is valid but produces an SDL validation error in graphql-java 15.0:

```graphql
enum AuthRoles {
    USER
}

extend enum AuthRoles {
    AUTHENTICATED
}

directive @auth(if: AuthRoles) on FIELD_DEFINITION

type Query {
    danger: String @auth(if: AUTHENTICATED) # <-- invalid error for AUTHENTICATED here
}
```

**To Reproduce**
Validate the SDL above and observe that the following error is reported by graphql-java:
`
'danger' [@12:5] uses an illegal value for the argument 'if' on directive 'auth'. Argument value 'AUTHENTICATED' doesn't match any of the allowed enum values ['USER']
`

I have confirmed that the extended enum value validates when used as an argument on a field, so the issue appears to be related to how directive enum arguments are validated:

![image](https://user-images.githubusercontent.com/15837712/83329118-d8cfc080-a287-11ea-9c8c-867b714a8cd4.png)

Directive:

![image](https://user-images.githubusercontent.com/15837712/83329095-af169980-a287-11ea-8508-0f7b501945cf.png)

Originating issue: https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/issues/293

**Comment by bbakerman** [comment]
I had a quick look into this - thanks for the extended example

This code is not happy

```
List<GraphQLError> errors = typeChecker.checkTypeRegistry(typeRegistryCopy, wiring);
```

It seems the type pre-checker is not smart enough.  This is where we need to look for a fix
