### ISSUE TITLE
Raise a different exception if no types are defined in the schema

### ISSUE THREAD

**Issue by zcourts** [graphql-java/graphql-java#1939]
Currently `InvalidSyntaxError` is thrown if now types are defined `parser.parse("#Empty schema with comment")`

It is useful to be able to distinguish this case so that we can respond differently.

In our case we are accepting schemas from customers - if they don't provide a schema we want to continue/saving everything else with the blank schema but if the schema is legitimately invalid i.e. has types but with incorrect syntax then we don't want to save. Right now there is no way to tell the difference between these two cases.

**Comment by bbakerman** [comment]
Please feel free to raise a PR that might be able to address this. 

This might be tricker thna you think - the ANTLR parse looks for valid things (ignoring all comments from the input stream).  So ZERO things is end of stream - hard to tell from a invalid end of stream.

You might want to consider some other "Srtring.contains" check if you need to find empty schema files
