### ISSUE TITLE
Add test for PR #123

### ISSUE THREAD

**Issue by markphilpot** [graphql-java/graphql-java#194]
@yrashk @danielkwinsor 

https://github.com/graphql-java/graphql-java/pull/123

Decided to merge the PR ahead of tests.  This issue is to track the need to add a test case for the change above.

**Comment by dminkovsky** [comment]
I believe this is the test case https://github.com/graphql-java/graphql-java/issues/118#issuecomment-212156330

**Comment by markphilpot** [comment]
I'll work to incorporate that this week.

**Comment by dminkovsky** [comment]
Cool thanks. I'm working on #204 right now which is also related to
TypeReferences. I'll probably get to this as part of that process. But in
case I don't, please feel free if you feel like it.

**Comment by bbakerman** [comment]
I am goig to close this one.  UNsure if its status
