### ISSUE TITLE
GraphQLInputObjectField does not distinguish between a null default value and no default value

### ISSUE THREAD

**Issue by kaqqao** [graphql-java/graphql-java#1958]
**Describe the bug**
Unlike `GraphQLArgument`, `GraphQLInputObjectField` does not distinguish between a `null` default value and no default value. I.e. `GraphQLArgument#hasSetDefaultValue` exists but `GraphQLInputObjectField#hasSetDefaultValue` doesn't.

This is a surprisingly inconsistent behavior, so probably unintentional.

**Comment by andimarek** [comment]
This is solved in master and will be releases in 17
