### ISSUE TITLE
Fails to parse valid Apollo subscription messages which contain extensions field

### ISSUE THREAD

**Issue by DominicTobias-b1** [graphql-java/graphql-java#1971]
**Describe the bug**

Apollo sends an `extensions: {}` field with subscription queries like so:

```gql
{
  "id": "1",
  "type": "start",
  "payload": {
    "variables": {
      "_v0_symbol": "btcusd"
    },
    "extensions": {},
    "operationName": null,
    "query": "subscription ($_v0_symbol: String) {  ticker(symbol: $_v0_symbol) {    average    createdAtTimestamp  }}"
  }
}
```

Unless `extensions` is removed or changed to `undefined` then the java graphql server refuses to parse the valid message and throws a parse error.

**To Reproduce**

Create an apollo stitched server which fetches remote java schemas to use and pass subscriptions to. I can provide some code if you need to but essentially this library should not throw when it encounters an extensions field for subscriptions.

**Comment by andimarek** [comment]
@DominicTobias-b1 this project is just for the GraphQL engine itself. GraphQL Java never parses any json response. Please open an issue with the project you are using on top of GraphQL Java. Thanks!

**Comment by DominicTobias-b1** [comment]
Ah ok thanks, I also noticed the problem went away when upgrading to micronaught 2.0 so issue must have been there
