### ISSUE TITLE
Execution can hang when using both the dataloader/batchloader paradigm and a custom exception handler that sometimes throws.

### ISSUE THREAD

**Issue by alacoste** [graphql-java/graphql-java#1973]
**Describe the bug**

Symptom: execution hangs forever.

Triggering conditions:
- One of the items in a list fails to fetch one of its fields.
- The execution uses a custom exception handler, which throws itself upon handling the datafetcher exception (seems like a reasonable behavior if some errors are meant to be handled by components above graphQL in the software stack, like the HTTP server itself).
- For another elements in the list, one nested sub-field uses the dataloader/batchloader paradigm.

Example query, from the failing test below:
```
query {
  products {
    suppliedBy {
      company { 
        id 
      } 
    }
  }
}
```

My understanding of the execution timeline:
- products returns two items.
- product[0].suppliedBy throws an exception, which is handled the custom exception handler, which rethrows.
- As a result, in product[0]'s call to `AsyncExecutionStrategy.execute(...)`, the `overallResult` completes exceptionally. However, **the line `executionStrategyCtx.onFieldValuesInfo(completeValueInfos);` is never executed.**
- The resolution of product[1] continues: product[1].suppliedBy is correctly fetched, and the datafetcher for product[1].suppliedBy.company is called. However, since this datafetcher is using the dataloader/batchloader paradigm, **the returned future will never complete until the dataloaders are dispatched.**
- Now inside product[1]'s call to `AsyncExecutionStrategy.execute(...)`, with all of product[1]'s fields correctly fetched, we get to `executionStrategyCtx.onFieldValuesInfo(completeValueInfos);`.
- This is where we would normally decide that we are ready to dispatch the dataloaders, but we don't because the "strategy call" for product[0] never had a corresponding "onFieldValuesInfo call". (See `FieldLevelTrackingApproach.levelReady(...)`, the failing condition is: `callStack.allOnFieldCallsHappened(level - 1)`)

**To Reproduce**

I was unable to write a simple fix to the problem, so I feel the best I can contribute is this unit test example that I used for debugging the issue and which exhibits the hanging problem:

```groovy
package graphql.execution.instrumentation.dataloader

import com.github.javafaker.Faker
import graphql.ExecutionInput
import graphql.GraphQL
import graphql.TestUtil
import graphql.execution.AsyncExecutionStrategy
import graphql.execution.DataFetcherExceptionHandler
import graphql.execution.DataFetcherExceptionHandlerParameters
import graphql.execution.DataFetcherExceptionHandlerResult
import graphql.execution.instrumentation.dataloader.models.Company
import graphql.execution.instrumentation.dataloader.models.Person
import graphql.execution.instrumentation.dataloader.models.Product
import graphql.schema.DataFetcher
import graphql.schema.DataFetchingEnvironment
import graphql.schema.idl.RuntimeWiring
import org.dataloader.BatchLoader
import org.dataloader.DataLoader
import org.dataloader.DataLoaderRegistry
import spock.lang.Specification

import java.util.concurrent.CompletableFuture
import java.util.concurrent.CompletionStage
import java.util.stream.Collectors

import static graphql.schema.idl.RuntimeWiring.newRuntimeWiring

class ExecutionHangingTest extends Specification {

    Faker faker = new Faker()
    String schema = """
        type Company { 
           id: Int!
        } 
        type Person {
          company: Company! 
        } 
        type Product { 
          suppliedBy: Person!
        } 
        type QueryType { 
          products: [Product!]! 
        } 
        schema { 
          query: QueryType 
        }
        """

    DataFetcherExceptionHandler customExceptionHandlerThatThrows = new DataFetcherExceptionHandler() {
        @Override
        DataFetcherExceptionHandlerResult onException(DataFetcherExceptionHandlerParameters handlerParameters) {
            throw handlerParameters.exception
        }
    }

    BatchLoader<Integer, Person> personBatchLoader = new BatchLoader<Integer, Person>() {
        @Override
        CompletionStage<List<Person>> load(List<Integer> keys) {
            CompletableFuture.supplyAsync({
                keys.stream()
                        .map({ id -> new Person(id, faker.name().fullName(), id + 200) })
                        .collect(Collectors.toList())
            })
        }
    }

    BatchLoader<Integer, Company> companyBatchLoader = new BatchLoader<Integer, Company>() {
        @Override
        CompletionStage<List<Company>> load(List<Integer> keys) {
            CompletableFuture.supplyAsync({
                return keys.stream()
                        .map({ id -> new Company(id, faker.company().name()) })
                        .collect(Collectors.toList())
            })
        }
    }

    // Always returns exactly 2 products, one supplied by person with ID #0 and one supplied by person with ID #1.
    DataFetcher productsDF = new DataFetcher() {
        @Override
        Object get(DataFetchingEnvironment environment) {
            List<Product> products = new ArrayList<>()
            for (int id = 0; id < 2; id++) {
                products.add(new Product(faker.idNumber().toString(), faker.commerce().productName(), id, []))
            }
            return products
        }
    }

    // Loads the person pointed to via Product.getSuppliedById.
    // Then return it, unless the person has ID 0 in which case it fails.
    DataFetcher suppliedByDF = new DataFetcher() {
        @Override
        Object get(DataFetchingEnvironment environment) {
            Product source = environment.getSource()
            DataLoaderRegistry dlRegistry = environment.getContext()
            DataLoader<Integer, Person> personDL = dlRegistry.getDataLoader("person")
            return personDL.load(source.getSuppliedById()).thenApply({ person ->
                if (person.id == 0) throw new Exception("Failure in suppliedByDF for person with ID == 0.")
                else person
            })
        }
    }

    DataFetcher companyDF = new DataFetcher() {
        @Override
        Object get(DataFetchingEnvironment environment) {
            Person source = environment.getSource()
            DataLoaderRegistry dlRegistry = environment.getContext()
            DataLoader<Integer, Company> companyDL = dlRegistry.getDataLoader("company")
            return companyDL.load(source.getCompanyId())
        }
    }

    RuntimeWiring runtimeWiring = newRuntimeWiring()
            .type("QueryType", { builder -> builder.dataFetcher("products", productsDF) })
            .type("Product", { builder -> builder.dataFetcher("suppliedBy", suppliedByDF) })
            .type("Person", { builder -> builder.dataFetcher("company", companyDF) })
            .build()


    def graphQLSchema = TestUtil.schema(schema, runtimeWiring)

    def query = """
        query Products { 
            products {
                suppliedBy {
                    company { 
                        id 
                    } 
                }
            } 
        }
        """

    private DataLoaderRegistry buildRegistry() {
        DataLoader<Integer, Person> personDataLoader = new DataLoader<>(personBatchLoader)
        DataLoader<Integer, Company> companyDataLoader = new DataLoader<>(companyBatchLoader)

        DataLoaderRegistry registry = new DataLoaderRegistry()
        registry.register("person", personDataLoader)
        registry.register("company", companyDataLoader)
        return registry
    }

    def "execution should never hang even if the datafetcher of one object in a list fails"() {

        DataLoaderRegistry registry = buildRegistry()

        GraphQL graphQL = GraphQL
                .newGraphQL(graphQLSchema)
                .queryExecutionStrategy(new AsyncExecutionStrategy(customExceptionHandlerThatThrows))
                .instrumentation(new DataLoaderDispatcherInstrumentation())
                .build()

        when:

        ExecutionInput executionInput = ExecutionInput.newExecutionInput()
                .query(query)
                .context(registry)
                .dataLoaderRegistry(registry)
                .build()

        def executionResult = graphQL.execute(executionInput)


        then:

        (executionResult.errors.size() > 0)
    }
}
```

**Comment by epowell** [comment]
I believe I am experiencing this issue as well, it has blocked release of a component for a few weeks.

Our use case is a graphql-java based server (via graphql-kotlin) behind a Kong proxy. We see approximately 2.5% of requests fail with a timeout at the proxy's backend, and never see logs or traces appear in the GraphQL server component. Usually it is the first request for a particular user that does this; subsequent requests from the same client seem to go through as normal.

I am attempting to confirm this by testing an alternate strategy that does not use a DataLoader at all, and doesn't cache results. So far I have seen no timeout errors with the alternate approach, which indicates I am seeing an issue in the DataLoader configuration or code.

Our DataLoader is configured to use a Caffeine AsyncCache (wrapped in a simple proxy that implements CacheMap. One complication is that we load values using a Kotlin coroutine function, and have to convert that to a CompletableFuture.

`
    @Bean
    fun attrDataLoader(attrCrossRequestCacheMap: AttrCrossRequestCacheMap): DataLoader<String, Attr> =
            DataLoader<String, Attr>(
                    { CoroutineScope(Dispatchers.Default).future { client.getByIds(it) } },
                    DataLoaderOptions.newOptions()
                            .setCachingExceptionsEnabled(false)
                            .setCacheMap(attrCrossRequestCacheMap)
            )
`

**Comment by alacoste** [comment]
> I believe I am experiencing this issue as well, it has blocked release of a component for a few weeks.

One quick way to verify if this is the exact same issue or not is to try running without any custom exception handler. I was unable to get the resolution to hang in my reproduction unit test without an error handler that itself throws exceptions.

**Comment by bbakerman** [comment]
Thanks you for the excellent investigation and reproduction.

As @alacoste says the work around is to ensure you don't throw exceptions in your exception handlers 

The longer term fix is to ensure that fields that complete exceptionally have their DataLoader promise completed exceptionally.

**Comment by bbakerman** [comment]
I have made a PR for this.

In the mean time the workaround is to harden your own exception handlers with try catches so they dont throw exceptions while handling exceptions
