### ISSUE TITLE
extend GraphQL directive can support multiple fields as input parameters?

### ISSUE THREAD

**Issue by ThinkCoding** [graphql-java/graphql-java#1976]
for example the shema is like this:
```
type cpuType {
  name: String
  cache: String
  price: Double
}

type memoryType {
  name: String
  size: String
  price: Double
}
```

the query is like this:
```
query computer {
  computerQuery {
    cpuType {
      name
      price
    }
    memoryType {
     name
     price
   }
   totalPrice :@add($cpuType.price ,$memoryType.price)
  }
}
```
the diretive add to calculate the sum of two numbers.
how  can i do with GraphQL-java ?

I know a way is to extend antlr make grapql support jsonPath, hava some people hava the same demand and how resolved?

**Comment by bbakerman** [comment]
You have just invented a field `totalPrice` that is not in the schema.

graphql is a closed type system - we will not deviate from spec and allow "synthetic" made up fields.

Sorry we cant and wont do this type if change
