### ISSUE TITLE
Please don make all constructors private

### ISSUE THREAD

**Issue by juergen-albert** [graphql-java/graphql-java#1978]
I've seen that a lot of constructors are marked deprecated in order to promote the usage of the builders. It comes with the warning, that they will be made private in future versions. I support this in general, but would like to ask you to mark them as protected instead of private. At least for the types, because I have a couple of Types that extend yours, in order to store some additional attributes I need for (de-)serialization. 

I know that I can implement a type fully because you always work with the Interfaces, but it would be a complete duplication of all of your code.

**Comment by bbakerman** [comment]
Can you tell us more about what classes you are extending and how you implement serialisation using them?

Typically the ExecutionResult is serlialised after the execution - how are you doing it via runtime graphql types?

**Comment by bbakerman** [comment]
No follow up provided - closing....
