### ISSUE TITLE
GraphQL Java and Spring Boot Example don't work for graphql-java 15.0, error: java.lang.NoSuchMethodError: graphql.Assert.assertNotNull

### ISSUE THREAD

**Issue by sxpujs** [graphql-java/graphql-java#1979]
I followed [Getting started with GraphQL Java and Spring Boot](https://www.graphql-java.com/tutorials/getting-started-with-spring-boot/), while I used the latest version of graph-java, and the example doesn't work. The error message is as below.
```
2020-07-11 19:15:19.314 ERROR 12030 --- [nio-8080-exec-6] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: 'java.lang.Object graphql.Assert.assertNotNull(java.lang.Object, java.lang.String, java.lang.Object[])'] with root cause

java.lang.NoSuchMethodError: 'java.lang.Object graphql.Assert.assertNotNull(java.lang.Object, java.lang.String, java.lang.Object[])'
	at graphql.spring.web.servlet.GraphQLInvocationData.<init>(GraphQLInvocationData.java:17) ~[graphql-java-spring-webmvc-1.0.jar:na]
```

The graphql playground response: 
```
{
  "error": {
    "timestamp": "2020-07-11T11:15:19.315+0000",
    "status": 500,
    "error": "Internal Server Error",
    "message": "'java.lang.Object graphql.Assert.assertNotNull(java.lang.Object, java.lang.String, java.lang.Object[])'",
    "path": "/graphql"
  }
}
```

the pom.xml is as below:
```
<dependency>
    <groupId>com.graphql-java</groupId>
    <artifactId>graphql-java</artifactId>
    <version>15.0</version>
</dependency>

<dependency>
    <groupId>com.graphql-java</groupId>
    <artifactId>graphql-java-spring-boot-starter-webmvc</artifactId>
    <version>1.0</version>
</dependency>

<dependency>
    <groupId>com.google.guava</groupId>
    <artifactId>guava</artifactId>
    <version>29.0-jre</version>
</dependency>

<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-web</artifactId>
    <version>2.2.5.RELEASE</version>
</dependency>

<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-test</artifactId>
    <scope>test</scope>
</dependency>
```

**Comment by dzhg** [comment]
It looks like `graphql-java-spring-webmvc:1.0` is not compatible with `graphql-java:15.0`.

`Assert.assertNotNull(java.lang.Object, java.lang.String, java.lang.Object[])` was removed in `v15.0` in favor of using `Supplier<String>` for laziness.

You can try with `graphql-java:14.1`:
```
<dependency>
    <groupId>com.graphql-java</groupId>
    <artifactId>graphql-java</artifactId>
    <version>14.1</version>
</dependency>
```

Also, you should use Spring Boot `2.1.0.RELEASE` as per https://github.com/graphql-java/graphql-java-spring/blob/v1.0/build.gradle

**Comment by dzhg** [comment]
https://github.com/graphql-java/graphql-java-spring/issues/31

**Comment by sxpujs** [comment]
> It looks like `graphql-java-spring-webmvc:1.0` is not compatible with `graphql-java:15.0`.
> 
> `Assert.assertNotNull(java.lang.Object, java.lang.String, java.lang.Object[])` was removed in `v15.0` in favor of using `Supplier<String>` for laziness.
> 
> You can try with `graphql-java:14.1`:
> 
> ```
> <dependency>
>     <groupId>com.graphql-java</groupId>
>     <artifactId>graphql-java</artifactId>
>     <version>14.1</version>
> </dependency>
> ```
> 
> Also, you should use Spring Boot `2.1.0.RELEASE` as per https://github.com/graphql-java/graphql-java-spring/blob/v1.0/build.gradle

Thanks, I have changed the version to ```graphql-java:14.1```, and it works well.
