### ISSUE TITLE
Programatically adding filter to query

### ISSUE THREAD

**Issue by stefanofara** [graphql-java/graphql-java#1982]
Hi,
I'm using graph-ql v12 in order to validate some qraphql query.
I need to add some property and related value into the filter using the parsed query.
NOTE: I don't need to use query parameters. I need to change the query programatically

I see inside the parsed query there are only get methods and not the set ones.
I see also there is the method withNewChildren(newChildren). May i use this one? If so, where can i find an example?

In order to understand my needs, here is the query submitted by the user
 {
  product(    uuid: "1" ) {
    uuid
    name
    description
  }
}

and here is the query after programatically changed are applied
 {
  product(    uuid: "1", extraProperty: extraVlue ) {
    uuid
    name
    description
  }
}

Thanks,
Stefano

**Comment by bbakerman** [comment]
In V12 we dont have advanced query rewriting.  

this was improved in v14 but again its a tricky business.  Remember that graphql queries can have fragments (which are really query pointers / macros) which make rewriting a really advanced pasttime.

See `graphql.analysis.QueryTransformer` and `graphql.analysis.QueryTransformerTest` for the gory details
