### ISSUE TITLE
Need to include class loader in caching keys

### ISSUE THREAD

**Issue by jmartisk** [graphql-java/graphql-java#1983]
`PropertyDataFetcherHelper` performs caching for properties, but the caching key only consists of class name and property name: https://github.com/graphql-java/graphql-java/blob/v15.0/src/main/java/graphql/schema/PropertyDataFetcherHelper.java#L269 . This becomes a problem in application servers, where multiple GraphQL applications might run within one JVM, in case that they share some model classes - if these application classes are then loaded by different class loaders, their caching keys will clash, and when one application retrieves a property that was cached for another application, it will run into `java.lang.IllegalArgumentException: object is not an instance of declaring class` when executing queries.
A possible solution is to include the hashCode of the owning class loader for caching keys.

**Comment by andimarek** [comment]
Hi @jmartisk: this sounds very specific, so I am assuming that this happened in a real project.

Can you please share a bit more about your setup/project where this. happened? thanks

**Comment by jmartisk** [comment]
Yes, I found this while developing a GraphQL subsystem for WildFly. Setting up an isolated reproducer is not very easy, but I'll at least come up with a test that demonstrates it. Give me a few minutes :)

**Comment by jmartisk** [comment]
If you check out https://github.com/jmartisk/wildfly-graphql-feature-pack/tree/caching-issue-reproducer (the branch `caching-issue-reproducer`) and do `mvn clean install`, it should fail on `OverlappingMultipleDeploymentsTestCase`, demonstrating this problem.

After updating the `version.com.graphql-java` property in pom.xml to something where my PR (https://github.com/graphql-java/graphql-java/pull/1984) is applied,  the build should start passing. However, the fix needs to be applied (cherry-picked) on top of graphql-java 15.0 for the time being - if you try applying it on master directly, it will fail due to some unrelated API changes that we will need to integrate before updating to 16.0.

I hope this is enough to demonstrate the problem. Sorry I don't know how to demonstrate it more easily :)

**Comment by bbakerman** [comment]
When we put this code in place we knew we ran the risk that the caching would be problematic for people who do dynamic class reloading or in your case multiple class loaders.

However the performance gains on offer for the clear majority of use cases made it worth it.

I suggest you check out **graphql.schema.GraphQLCodeRegistry.Builder#defaultDataFetcher** and use your own PropertyDataFetcher like implementation that can copy with multiple class loaders.  

I am loath to put in more specific caching into this fundamental class.
