### ISSUE TITLE
Unget or release methods for the DataFetcherFactory

### ISSUE THREAD

**Issue by juergen-albert** [graphql-java/graphql-java#1985]
The  DataFetcherFactory documentation already points out, that this is made for frameworks like Spring or Guice. In order to make it usefull to other Frameworks like OSGi, a unget or release would be handy, in order to achieve a proper cleanup after a Datafetcher is used.

The same applies for the DataLoaderRegistry. #1902 already suggests, having a supplier to provide a DataLoader. In the context given, an additional (optional) Consumer could be added to the method signature to hava a release as well:

dataLoaderRegistry.register("user", () -> DataLoader.newDataLoader(userBatchLoaderProvider.get()), userLoader -> userBatchLoaderProvider.release(userLoader));

**Comment by bbakerman** [comment]
Sorry we dont really have a great lifecyle event to attach this to?  

Are you suggesting that on every field, we get and release the DataFetcher?

**Comment by juergen-albert** [comment]
The usage of a Supplier in the DataLoaderRegistry suggests that a new instance may be created on every call. In some cases such prototype instances are really useful and one someone needs to take care of the lifecycle. When I provide a DataFetcher, I have no clue what the Framework does with my fetcher and when it is done using it. Thus I need the Framework to tell me when it is done with it, so I can do my cleanup operations.

**Comment by bbakerman** [comment]
Implementation notes:

Today the GraphqlCodeRegistry is the holder of DF factories and hence DataFetchers

```
    public DataFetcher<?> getDataFetcher(GraphQLFieldsContainer parentType, GraphQLFieldDefinition fieldDefinition) {
        return getDataFetcherImpl(FieldCoordinates.coordinates(parentType, fieldDefinition), fieldDefinition, dataFetcherMap, systemDataFetcherMap, defaultDataFetcherFactory);
    }


    private static DataFetcher<?> getDataFetcherImpl(FieldCoordinates coordinates, GraphQLFieldDefinition fieldDefinition, Map<FieldCoordinates, DataFetcherFactory<?>> dataFetcherMap, Map<String, DataFetcherFactory<?>> systemDataFetcherMap, DataFetcherFactory<?> defaultDataFetcherFactory) {
        DataFetcherFactory<?> dataFetcherFactory = systemDataFetcherMap.get(fieldDefinition.getName());
        if (dataFetcherFactory == null) {
            dataFetcherFactory = dataFetcherMap.get(coordinates);
            if (dataFetcherFactory == null) {
                dataFetcherFactory = defaultDataFetcherFactory;
            }
        }
        return dataFetcherFactory.get(newDataFetchingFactoryEnvironment()
                .fieldDefinition(fieldDefinition)
                .build());
    }

```

The execution code then does this on a field fetch

```
      DataFetcher<?> dataFetcher = codeRegistry.getDataFetcher(parentType, fieldDef);
      CompletableFuture<Object> fetchedValue;
      try {
            Object fetchedValueRaw = dataFetcher.get(environment);
```

So we would have to release the DataFetcher here in a finally block.  

I think the best way would be to have a signature perhaps on DataFetcherFactory itself that passes the DF back into to release it - eg

```
  interface DataFetcherFactory {
      ....
      public void release(DataFetcher df);
```

The challenge on todays code is that the DataFetcherFactory is tied up inside the CodeRegistry and hence the DFF that was used to create a DF is not known to the calling code.  This would have to change significantly if we did this work.

Also some data fetchers in the system (such as hard coded Instrospection data fetchers) would never need this because they are not injectable in any way

**Comment by juergen-albert** [comment]
As I said, the release would help a long way. I could try to provide a PR for this, but I'm not sure if this makes much sense, if this has a deeper impact, as you mentioned.

**Comment by bbakerman** [comment]
I had a brief look at this.  The challenge is that the DataFetcherFactory
is attached to the CodeRegistry which lives with the schema.

Hence they cross requests.  The lifecycle you are asking for is per request?

Also technically the same Data Fetcher could be used on a number of
different fields.  But they may not all be invoked.

So knowing when to "release" it is tricky.

By all means try to write a PR to demonstrate this.  I suspect there is not
a one size fits all approach here.

**Comment by bbakerman** [comment]
We really can't do this give the current design.
