### ISSUE TITLE
Why does DataFetchingEnvironment.getArgument return T?

### ISSUE THREAD

**Issue by peacememories** [graphql-java/graphql-java#1988]
The current API of [`DataFetchingEnvironment`](https://javadoc.io/doc/com.graphql-java/graphql-java/latest/graphql/schema/DataFetchingEnvironment.html) contains a function [`getArgument`](https://javadoc.io/doc/com.graphql-java/graphql-java/latest/graphql/schema/DataFetchingEnvironment.html#getArgument-java.lang.String-) that returns a T, with the additional note

> T - You decide what type it is

This led me to believe that `getArgument` contains some conversion logic, maybe via Jackson, to retrieve POJOs from the arguments, which would make ergonomic sense in this library.
After hitting a wall with `ClassCastException`s and digging for a while, I found #777, the resolution of which is that `getArgument` does *not* convert anything, and always returns `LinkedHashMap`s.
Considering this, I don't see why `getArgument` does not just return `Map<String, Object>` or something similar, since the type argument does not seem to have any practical use anymore. This would, in my opinion, greatly clarify what the API is capable of.

**Comment by bbakerman** [comment]
getArguments returns a map.  getArgument returns T

`<T> T getArgument(String name);`

The reason we have it returning T is that an argument may be a string, boolean, int, float, list or map.  This is to make it easier to use in that regard

I can kinda understand your confusion that some magic mapping was happening, Java devs are conditioned to expecting that magic will happen for them.  The reason we don't have say Jackson auto mapping is to reduce dependencies - we want to stay a pure engine.

https://www.graphql-java.com/documentation/v15/concerns/

**Comment by bbakerman** [comment]
I am going to close this issue as a suggestion - we are happy with the current shape and dont intend to change it
