### ISSUE TITLE
> > If we deprecate ExecutorServiceExecutionStrategy, how could we handle two API queries parallel?

### ISSUE THREAD

**Issue by perkins4j2** [graphql-java/graphql-java#1989]
> > If we deprecate ExecutorServiceExecutionStrategy, how could we handle two API queries parallel?
> 
> The new versions of Graphql use CompletableFuture results and they combine them.
> 
> So imagine we have two data fetchers (psudeo code in lambda syntax)
> 
> ```
> DataFetcher firstCall = env -> CompleteableFuture.supplyAsync(() -> serviceLayer.makeCall1(env));
> 
> DataFetcher secondCall = env -> CompletableFuture.supplyAsync(() -> serviceLayer.makeCall2(env));
> ```
> 
> Each of these fetches is now and async call and CompletableFuture will delegate them to a standard ForkJoin scheduler in Java. You can use your own scheduler if you want. They WILL happen in parallel and be combined by graphql java
> 
> In essence we no longer need the old ExecutorServiceExecutionStrategy which did the same thing but was invented in Java before CompletableFuture

hi，But I still want to use parallel and my ExecutorService。

reason：
1，ExecutorService has monitor online。
2，ForkJoin‘s performance maybe not very well。

So， If I use AsyncExecutionStrategy,how can use my ExecutorService?

THS

_Originally posted by @perkins4j2 in https://github.com/graphql-java/graphql-java/issues/1173#issuecomment-666278120_

**Comment by bbakerman** [comment]
you can provide your own executor service on your CF async calls

`CompletableFuture.supplyAsync(() -> someCode(), yourExecutorService)`

This code would go in the DataFetchers that want to be async
