### ISSUE TITLE
Please add a release in Github page?

### ISSUE THREAD

**Issue by Jimexist** [graphql-java/graphql-java#199]

**Comment by dminkovsky** [comment]
Thank you. Yes we will do this soon.

суббота, 3 сентября 2016 г. пользователь Jiayu Liu написал:

**Comment by dminkovsky** [comment]
Hi @Jimexist, we published a release: https://github.com/graphql-java/graphql-java/releases/tag/v2.1.0.

Thank you for noticing this issue.

**Comment by Jimexist** [comment]
thanks!
