### ISSUE TITLE
graphql extend scalars register

### ISSUE THREAD

**Issue by perkins4j2** [graphql-java/graphql-java#1990]
private RuntimeWiring buildWiring() {
        //extend scalars
        return RuntimeWiring.newRuntimeWiring()
                .scalar(JavaPrimitives.GraphQLByte)
                .scalar(JavaPrimitives.GraphQLShort)
                .scalar(JavaPrimitives.GraphQLLong)
                .type(newTypeWiring("Query").dataFetcher("jobFeature", redisDataFetchers.findJobFeature()))
                .build();
    }

scalar Short
scalar Byte
type Info{
    id: Int
    userShowType: Short 
}

exception:
Invocation of init method failed; nested exception is SchemaProblem{errors=[There is no scalar implementation for the named  'Short' scalar type, There is no scalar implementation for the named  'Byte' scalar type]}

why? and how i should do

THS

**Comment by andimarek** [comment]
Closes as duplicate to spectrum question: https://spectrum.chat/graphql-java/general/javaprimitives-not-works~0f4759d0-a925-424d-aed9-0818f2129c3b

**Comment by UglyHobbitFeet** [comment]
I have the same issue with GraphQLLong. What is the fix? The link to the spectrum question is empty. 

I have a ticket for this here (not sure if it belongs in that repo):
https://github.com/graphql-java/graphql-java-extended-scalars/issues/34
