### ISSUE TITLE
Incorrect handling of directive argument of list type when non-list value is provided in schema  

### ISSUE THREAD

**Issue by dimdimych** [graphql-java/graphql-java#2001]
According to the [Graphql language Spec](https://spec.graphql.org/draft/#sec-Type-System.List) it is allowed to provide a non-list as a value for the list type inputs. According to the spec, if the value's type matches the list item type, the value is interpreted as a singleton list.

While it works in queries, it does not work in schemas, in particular in schema directives with the arguments of List Type. 
For example the following fragment of a schema produces the error below: 
```
directive @test( value: [String] ) on FIELD_DEFINITION
type TestType {
testField: Int @test(value: "some value")
}
```  
`Error: 'testField' [@47:5] uses an illegal value for the argument 'value' on directive 'test'. Argument value is 'StringValue', expected a list value`

**Comment by bbakerman** [comment]
Yup we have missed this completely.  I did not know this

> If the value passed as an input to a list type is not a list and not the null value, then the result of input coercion is a list of size one, where the single item value is the result of input coercion for the list’s item type on the provided value (note this may apply recursively for nested lists).

We should fix this and follow spec.

The 2018 official spec has this defined

https://spec.graphql.org/June2018/#sec-Input-Object-Extensions
