### ISSUE TITLE
Merging of two data sources

### ISSUE THREAD

**Issue by perkins4j2** [graphql-java/graphql-java#2005]
type Query{
    find(id:ID):Student
}
type Student{
    info: Info
    score: Score
}

type Info{
    name: String
}

type Score{
    level: Int
}

how do it by dataFetcher????

like this? I have no idea.....
```
.type(newTypeWiring("Query").dataFetcher("find", dataFetchers.find()))
.type(newTypeWiring("Student")
                        .dataFetcher("info", dataFetchers.findInfo())
                        .dataFetcher("score", dataFetchers.findScore()))
```
ths

**Comment by andimarek** [comment]
Please don't ask the same question here and in spectrum and in general spectrum is the right place. See https://spectrum.chat/graphql-java/general/merging-of-two-data-sources~80b25682-e0a7-4fff-bff9-875dc7b0447c
