### ISSUE TITLE
Provide Automatic-Module-Name

### ISSUE THREAD

**Issue by aholstenson** [graphql-java/graphql-java#2006]
An Automatic-Module-Name in the manifest of the published JAR-files would improve Java 9+ compatibility when using modules. Currently you will receive warnings about using an unstable name derived from the module's file name.

Targeting Java 9+ is becoming more common and being able to use graphql-java while also using Java modules would be beneficial to those projects.

**Comment by andimarek** [comment]
@aholstenson can you describe a bit more what we have todo for it? Maybe you also want to create a PR for it? That would be great. 

In general we are happy to support Java 9 better, especially if the effort is low.

**Comment by aholstenson** [comment]
My experience with configuring Gradle is limited, but how to modify the manifest to include `Automatic-Module-Name` seems to be well documented here: https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_modular_auto

**Comment by bbakerman** [comment]
See linked PR - I tested locally and it creates a MANIFEST with `Automatic-Module-Name ` set

**Comment by revdels** [comment]
The module name contains an dash, which is not allowed. It should consyst of valid java identfiers separated by dots.
