### ISSUE TITLE
the implementation of isEqualTo in FieldDefinition

### ISSUE THREAD

**Issue by dugenkui03** [graphql-java/graphql-java#2031]
It is pretty odd for determing whether two `FieldDefinition` are equal by comparing name, but not considering whether they are in same type. Same for `Field`.

**Comment by dugenkui03** [comment]
I think the more appropriate way is to compare the `FieldCoordinates` of `FieldDefenition`.

For `Field`, I think the more approprate way is compare the absolutely path in query.

**Comment by bbakerman** [comment]
Your right that it should be field name AND field type name 

`FieldCoordinates` here do not apply.  A `FieldDefinition` is the AST element that defines a field.  `graphql.schema.GraphQLFieldDefinition` is the runtime type that uses `FieldCoordinates`
