### ISSUE TITLE
Validation about Hint.path in CacheControl

### ISSUE THREAD

**Issue by dugenkui03** [graphql-java/graphql-java#2051]
https://github.com/graphql-java/graphql-java/blob/c194f88cc7e50c1b1a03f195c26ec62100e503d8/src/main/java/graphql/cachecontrol/CacheControl.java#L49

Is it more appropriate to replace `assertNotNull()` with `assertNotEmpty`?

> This field should be a list of **path** segments starting at the root of the response.

**Comment by bbakerman** [comment]
Yeah probably.
