### ISSUE TITLE
ArrayIndexOutOfBoundsException for SchemaPrinter#print

### ISSUE THREAD

**Issue by omavi** [graphql-java/graphql-java#2053]
The schema printer is unable to safely process an "empty" Javadoc that contains only descriptive tags and no description.

For example:

```    
    /**
     * @deprecated use {@link #otherField} instead.
     */
    @Deprecated
    private String field;
```

The bug is around here: https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/schema/idl/SchemaPrinter.java#L952

The `isNullOrEmpty(descriptionText)` check fails because a newline character (`\n`) is picked up and not counted as "empty" in the `SchemaPrinter#isNullOrEmpty` method. However, the `lines` list is empty because it's created by splitting on the `\n` delimiter.  Since there isn't a `lines#isEmpty` check, this results in an `ArrayIndexOutOfBoundsException` at the line above.

I was able to work around this issue by enabling legacy functionality as I encountered it while upgrading to v15:

```
SchemaPrinter.Options.defaultOptions()
            .descriptionsAsHashComments(true)
```

**Comment by omavi** [comment]
I was able to work around this issue by enabling legacy functionality as I encountered it while upgrading to v15:

```
SchemaPrinter.Options.defaultOptions()
            .descriptionsAsHashComments(true)
```

**Comment by omavi** [comment]
Closing this issue as I realized that I could fix the problem during our Javadoc to GraphQL description conversion. It would still be nice if there was a `lines#isEmpty` check before calling `lines.get(0)` but it's not a serious issue.

**Comment by bbakerman** [comment]
Since you described this bug right down to individual lines, a PR would have gotten this fixed

**Comment by omavi** [comment]
Good point
