### ISSUE TITLE
Accessing query context in GraphQLFieldVisibility

### ISSUE THREAD

**Issue by rrva** [graphql-java/graphql-java#2057]
Looking at `graphql.schema.visibility.GraphqlFieldVisibility` I see no way in the implementation to access query-specific context, like originating request details. Right now I have to put that kind of information in a threadlocal, which seems unsafe (MDC). Is there a way to access the data fetching environment in a GraphQLFieldVisibility implementation?

**Comment by bbakerman** [comment]
Question answered on Spectrum

https://spectrum.chat/graphql-java/general/blocking-introspection-conditionally~1cb1be0f-1080-4ebf-a3dd-29dd02f3758f
