### ISSUE TITLE
Enum not converted to Enum type when fetched from DataFetchingEvironment arguments when Query Default Value is used

### ISSUE THREAD

**Issue by jcromp** [graphql-java/graphql-java#2061]
I'd like to preface this by saying I am new to GraphQL and this could easily be an issue in my Query. 

I have re created the issue with unit tests here: https://github.com/jcromp/graphql-enum-error-example
`mvn test` should do the trick.

The query should take a list of Enum's and if no values are provided it should default to a list of ALL the possible enum values:
```
type Query {
     foos(fooStatus: [StatusEnum!] = [GOOD, BAD, UGLY]): [Foo]
}

enum StatusEnum {
    GOOD,
    BAD,
    UGLY
}
```

This works perfectly fine if I am providing the values to the query. However, when I don't provide a value(s) and the default value is used, when the resolver gets the arguments from the DataFetchingEnvironment they come out as Strings and not their Enum type, this causes a `ClassCastException: class java.lang.String cannot be cast to class com.example.enumerrorexample.StatusEnum`

If this is me not understanding something could someone please let me know what I am doing wrong.

Thanks.

**Comment by dugenkui03** [comment]
I think that the releation between graphql EnumType `StatusEnum` and  java enumType [StatusEnum](https://github.com/jcromp/graphql-enum-error-example/blob/master/src/main/java/com/example/enumerrorexample/StatusEnum.java) is not built successfully. And the tool you use is [graphql-java-tools](https://github.com/graphql-java-kickstart/graphql-java-tools). 

In `graphql-java`, you could maps the GraphQL Enum name to the Java Enum instance by [`NaturalEnumValuesProvider`](https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/schema/idl/NaturalEnumValuesProvider.java). the sample is as follows:
https://github.com/graphql-java/graphql-java/blob/53999d6c30bd286efa514fb5c5e0296e1509d4bf/src/test/groovy/graphql/schema/idl/SchemaGeneratorTest.groovy#L859

**Comment by jcromp** [comment]
Thank you for the response. I've opened an issue with the correct project. Sorry.
