### ISSUE TITLE
deprecated functions

### ISSUE THREAD

**Issue by lunicon** [graphql-java/graphql-java#2075]
Where are many public core function without alternatives, which used internaly!

GraphQLFieldDefinition can't be created without dataFetcherFactory (v15.0)
```   
// @deprecated use {@link graphql.schema.GraphQLCodeRegistry} instead
public Builder dataFetcherFactory(DataFetcherFactory dataFetcherFactory)
// @deprecated use {@link graphql.schema.GraphQLCodeRegistry} instead
public Builder dataFetcher(DataFetcher<?> dataFetcher) {
```
by default `new PropertyDataFetcher<>(name)` no way to set dataFetcherFactory without deprecated function

If you mark function as `@deprecated` don't use is your self and make sure it's not used anywhere else.
I suggest to use `-Xlint:deprecation -Werror` compile flags.

I faced it when try to update my appliction to the latest version.

**Comment by bbakerman** [comment]
We dont intend anyone to create a `GraphQLFieldDefinition` with the data fetcher attached.

Hence the deprecation.  We have one internal usage (in Relay code) and thats on oversight.

We have tests that use it but then again they are testing this deprecated BUT astill callable behaviour.  This is a major breaking change and hence we have left it in place for a long time to help not breaking the world.

> If you mark function as @deprecated don't use is your self and make sure it's not used anywhere else.

Except for one place, this is the case.
