### ISSUE TITLE
Cannot use custom execution strategies on mutations

### ISSUE THREAD

**Issue by pcarrier** [graphql-java/graphql-java#208]
From Execution.java:

```
        if (operationDefinition.getOperation() == OperationDefinition.Operation.MUTATION) {
            return new SimpleExecutionStrategy().execute(executionContext, operationRootType, root, fields);
        } else {
            return strategy.execute(executionContext, operationRootType, root, fields);
        }
```

There are mutation-safe strategies one might want to use unconditionally.

**Comment by dminkovsky** [comment]
If there is a PR for this, please note [these lines](https://github.com/graphql-java/graphql-java/blob/v2.1.0/src/main/java/graphql/execution/ExecutionStrategy.java#L85-L88).
