### ISSUE TITLE
How merge or combine result by query

### ISSUE THREAD

**Issue by perkins4j2** [graphql-java/graphql-java#2081]
**Example**
Schema

```
type A{
   aId: String
   aName: String
}

type B{
   bId: String
   bName: String
}
```

A and B are different db source and schema。

QL：

```
query combine1($aId: ID,$bId: Int){
    a(aId:$aId){
      aId
      aName
   }
    b(bId:$bId){
      bId
      bName
   }
}
```

Now ,the result like:

```
{
   a:{aid aName}
   b:{bid bName}
}
```

**But I expect result is:**

```
{
  aid
  aName
  bId
  bName
}
```

How should I do?

I try the `interface` or `fragment` and so on ....,But never successful.

Any Idea is welcomed, thank you.

**Comment by bbakerman** [comment]
Sorry but this is how graphql  works - each field (a and b in your query) has an entry and then the sub fields under them below to that entry.  This is working as expected.

if you want to discuss this more, then the Spectrum forums are a better place

https://spectrum.chat/graphql-java?tab=posts
