### ISSUE TITLE
warnings about ANTLR version mismatch on stderr

### ISSUE THREAD

**Issue by dfa1** [graphql-java/graphql-java#2097]
**Describe the bug**
During the build and run of a graphql-java app I see a lot of:

`ANTLR Tool version 4.8 used for code generation does not match the current runtime version 4.7.2ANTLR Runtime version 4.8 used for parser compilation does not match the current runtime version 4.7.2ANTLR Tool version 4.8 used for code generation does not match the current runtime version 4.7.2ANTLR Runtime version 4.8 used for parser compilation does not match the current runtime version 4.7.2[`

Version used: 2020-10-21T10-06-46-49bbbeb

**To Reproduce**
Run a query with graphql-java

**Comment by andimarek** [comment]
We upgraded to antlr 4.8 recently. Please make sure you rebuild your project completely. ./gradlew clean build should do the trick.

**Comment by dfa1** [comment]
Thank you :)

According to maven dependency:tree there is a dependency to antlr-runtime 4.7.2
```

INFO] |  \- com.graphql-java:graphql-java:jar:2020-10-21T10-06-46-49bbbeb:compile
[INFO] |     +- com.graphql-java:java-dataloader:jar:2.2.3:compile
[INFO] |     +- org.reactivestreams:reactive-streams:jar:1.0.3:compile
[INFO] |     \- org.antlr:antlr4-runtime:jar:4.7.2:runtime
```
but does not make sense because in the pom I can see antlr-runtime 4.8 as expected. 
Let me dig further...

**Comment by dfa1** [comment]
found the root cause: we have quarkus-universe-bom declaring version 4.7.2 and that takes precedence over the direct library dependency
