### ISSUE TITLE
Tracing instrumentation includeTrivialDataFetchers not work

### ISSUE THREAD

**Issue by aoudiamoncef** [graphql-java/graphql-java#2098]
Hi @bbakerman 
I had this code below: 
```java
    final TracingInstrumentation.Options tracingOptions = TracingInstrumentation.Options.newOptions()
                .includeTrivialDataFetchers(false);
```
It works as expected in GraphQL Java 14, I think after upgrading to v15 includeTrivialDataFetchers(false) doesn't work. May be I'm wrong, I don't know.

Thank you :)

**Comment by bbakerman** [comment]
I dont see why this would not be working

```
InstrumentationFieldFetchParameters instrumentationFieldFetchParams = new InstrumentationFieldFetchParameters(executionContext, fieldDef, environment, parameters, dataFetcher instanceof TrivialDataFetcher);
```

if the dataFetcher is an instance of `TrivialDataFetcher` then this parameter will be true and later code will do

```
    public TracingContext beginField(DataFetchingEnvironment dataFetchingEnvironment, boolean trivialDataFetcher) {
        if (!includeTrivialDataFetchers && trivialDataFetcher) {
            return () -> {
                // nothing to do
            };
        }
```

Can you please investigate more and find concrete evidence of a bug please.  If its a bug we will fix it but a quick examination seems to suggest no problem
