### ISSUE TITLE
Aggregate production users

### ISSUE THREAD

**Issue by dminkovsky** [graphql-java/graphql-java#210]
A primary goal of this library is to enable production use. To further project this aim to prospective users, let's aggregate known production users and list them in the README or in a file in the root directory. 

Please post on this issue if you are aware of any users in public production.

@andimarek @bpatters

**Comment by bpatters** [comment]
Spredfast, Inc - We use it in production in conjunction with schemagen-graphql.

**Comment by andimarek** [comment]
closing it for now: I like the general idea, but we will not add such a info for now. Hopefully later.
