### ISSUE TITLE
Is there any way to extend validation rule?

### ISSUE THREAD

**Issue by tawalisa** [graphql-java/graphql-java#2102]
Hi,

I have a question if we can extend a custom validation rule? 

Thanks

**Comment by dugenkui03** [comment]
> [graphql-java-extended-validation](https://github.com/graphql-java/graphql-java-extended-validation) provides extended validation of fields and field arguments for graphql-java

you also can get the validation rule defined by directive,  check whether the element is legal. That is my way.

**Comment by tawalisa** [comment]
Many thanks @dugenkui03 
 The graphql-java-extended-validation need dive to datafetcher, But my new validation rule need be invoked before datafetcher. My case need check a graphql query which included multiple queries(top level datafetcher).   I just checked source code, it looks graphql-java is being hard code validation rule. I think I could not find way to extend on validation rule. Maybe we need some workaround like instrumentaion. Do you have any suggestion? 

Cheers

**Comment by bbakerman** [comment]
Validation in graphql-java is "query level validation"   eg does this field exist, does it takes the args supplied, are there fragments not referenced.

It is not a place to do business level validation.  if you are determined to write come custom multi field validation (outside of each data fetcher for a field) then check out

`graphql.execution.instrumentation.Instrumentation#beginExecuteOperation` which is called JUST before execution begins.

If you want to prevent execution then you can throw `graphql.execution.AbortExecutionException`

**Comment by dugenkui03** [comment]
Yes, Instrumentation + directive  is a power tool to alter the execution behavior. from spec:
> Directives provide a way to describe alternate runtime execution and type validation behavior in a GraphQL document.

This is a very simple example to extend the @ skip instruction, [@skipByExp(exp: String!) on FIELD](https://github.com/dugenkui03/graphql-java/blob/master-zh/src/test/groovy/readme/directive/SimpleDemo.java).

**Comment by tawalisa** [comment]
Many thanks @dugenkui03 @bbakerman . What a useful help for me!!! I have found a workaround for it. Thank for your help.
