### ISSUE TITLE
Scalar fails using direct value, works with variables

### ISSUE THREAD

**Issue by skfcz** [graphql-java/graphql-java#2105]
**Describe the bug**

I defined a scalar in my schema which used in an input type. 
```graphql
scalar NoLoveInput
input EnumsAndLoVsInput {
  id: OkId
  itimestampVar: Time
  lovAttr: NoLoveInput
  notYet: Decision
}

type Mutation {
  CreateEnumsAndLoVs(input: EnumsAndLoVsInput!): EnumsAndLoVs
}
```

When I call this using Postman with the input given as direct value, the lovAttr is detected as string:

```graphql
mutation  {
    CreateEnumsAndLoVs( input: { notYet: OK, itimestampVar:"11:39:00+01:00",
    lovAttr: "spaces suck"
     }  ) 
       {id, lovAttr {value}, notYet, itimestampVar}
```

"message": "Validation error of type WrongType: argument 'input.lovAttr' with value 'StringValue{value='spaces suck'}' is not a valid 'NoLoveInput' @ 'CreateEnumsAndLoVs'",

When I call this using Postman with the input given as separate variable, this works as expected

```graphql
mutation ($var1: NoLoveInput) {
    CreateEnumsAndLoVs( input: { notYet: OK, itimestampVar:"11:39:00+01:00",
    lovAttr: $var1
     }  ) 
       {id, lovAttr {value}, notYet, itimestampVar}
}
```

**To Reproduce**
Please provide a code example or even better a test to reproduce the bug.

**Comment by bbakerman** [comment]
You have not listed your code for your custom scalar.  This is the area that controls valid values.

See `graphql.schema.Coercing`

`graphql.schema.Coercing#parseValue` is called to parse an actual value (from variables) and decide whether its acceptable

`graphql.schema.Coercing#parseLiteral(java.lang.Object)` is used to parse an AST literal value (the one that worked) as a valid scalar value

I suspect you have different code here.

**Comment by skfcz** [comment]
Hello, 

I register the scalar types like this 
`` .scalar(new com.prostep.ct.oktest.model.NoLoveScalarType( this.noLoveRepository ))
``

the code for the scalar type is trying to find an object in the database (something like a runtime defined enum)
``
public class NoLoveScalarType extends GraphQLScalarType {

    public NoLoveScalarType( com.prostep.ct.oktest.repository.NoLoveRepository repo) {
        super(  "NoLoveInput",
                "Imported from schema 'oktestinclude'",
                new NoLoveSTCoercing( repo ));
    }

    private static class NoLoveSTCoercing implements Coercing<NoLove, String> {
        private NoLoveRepository repo;

        private NoLoveSTCoercing(  NoLoveRepository r) {
             repo = r;
        }

        @Override
        public String serialize(Object o) throws CoercingSerializeException {
            ...
        @Override
        public NoLove parseValue(Object o) throws CoercingParseValueException {
            ...
        @Override
        public NoLove parseLiteral(Object o) throws CoercingParseLiteralException {
            ...
```

This works, but only if the scalar is send with a separate variable definition, not as inline value

**Comment by bbakerman** [comment]
> This works, but only if the scalar is send with a separate variable definition, not as inline value

I suspect very strongly that your `parseLiteral` method has not been written properly.  Have a look at the other scalars and how they work

You will get values like StringValue and IntValue in parseLiteral

**Comment by skfcz** [comment]
Hello All, 

this was an error on my side and not in graphql-java.

The error on our side was, that we returned null where should have used the passed in StringValue.
In this case we got this error message from above.

Our current implementation looks like this
```
 @Override
        public AttributeType parseValue(Object o) throws CoercingParseValueException {
            if (o instanceof String) {
...
            } else {
                throw new IllegalStateException("Could not parse " + o + ". Needs to be a String." );
            }
        }

        @Override
        public AttributeType parseLiteral(Object o) throws CoercingParseLiteralException {
            if (o instanceof graphql.language.StringValue) {
                String value = ((graphql.language.StringValue) o).getValue();
          ...
            } else {
                throw new IllegalStateException("Could not parse " + o + ". Needs to be a StringValue." );
            }
        }
````
