### ISSUE TITLE
Context argument to GraphQL#execute() should be explicit in next breaking version

### ISSUE THREAD

**Issue by dminkovsky** [graphql-java/graphql-java#211]
The reference implementation now has an [explicit context value](https://github.com/graphql/graphql-js/commit/d7cc6f9aed462588291bc821238650c98ad53580) that is separate from the root value. So in that implementation, [`GraphQL#execute()`](https://github.com/graphql/graphql-js/blob/v0.7.0/src/execution/execute.js#L116-L117) now looks like:

```
export function execute(
  schema: GraphQLSchema,
  documentAST: Document,
  rootValue?: mixed,
  contextValue?: mixed,
  variableValues?: ?{[key: string]: mixed},
  operationName?: ?string
): Promise<ExecutionResult> {
```

We should probably follow in our next breaking version.

**Comment by bbakerman** [comment]
@dminkovsky - how keen are you to break this?

I think we should use a Parameter pattern so we can 1) reduce the number of arguments and 2) add new parameters without method overloading and breaking API

**Comment by andimarek** [comment]
Currently our `context` argument is presented as `root` to `DataFetchers`. This is confusing and would be happy to clear it up.

**Comment by andimarek** [comment]
This will not come in 3.0.0, added to 4.0.0.

**Comment by andimarek** [comment]
This is the proposal:

* We will add a `root` object: This will be presented as `root` to `DataFetchers`
* `root` will be the `source` object for the first query

This is a breaking change.

**Comment by andimarek** [comment]
PR: #456

**Comment by andimarek** [comment]
the PR is merged and will be in the next release
