### ISSUE TITLE
DataFetchingEnvironment.getSelectionSet().getFields() is broken from Mutations after upgrade to graphql-java 16

### ISSUE THREAD

**Issue by artem-ag** [graphql-java/graphql-java#2117]
**Describe the bug**
Trying to invoke `dataFetchingEnvironment.getSelectionSet().getFields()` from a Mutation results in `graphql.AssertException: no field with name mutationFieldName found in object Query` exception being thrown out.

This seems be caused by https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/normalized/NormalizedQueryTreeFactory.java#L55 that assume that root is always a Query.

This worked fine in graphql-java 15, and is broken after upgrade to graphql-java 16.

**To Reproduce**
From a DataFetcher that's registered to resolve a Mutation field invoke something like below:

```
DataFetchingFieldSelectionSet selectionSet = environment.getSelectionSet();
if (selectionSet.getFields().stream().allMatch(field -> SUPPORTED_FIELDS.contains(field.getName()))) { return "xyz"; }
```

**Comment by andimarek** [comment]
This will be fixed by #2126

**Comment by fbreivald** [comment]
Hi, any Idea when the fix will be released? My project is stalled on this issue.

**Comment by Me1kaa** [comment]
Hello! Can you release 16.2. Cause besides that issue - there are some important bugs fixed.

**Comment by austinarbor** [comment]
Have opened parallel fix with suggested assertion changes https://github.com/graphql-java/graphql-java/pull/2173 can we get one of these PRs merged in? This is a blocking issue for us
