### ISSUE TITLE
new hotspot in FieldCollector

### ISSUE THREAD

**Issue by dfa1** [graphql-java/graphql-java#2119]
**Describe the bug**
16.1 improved a lot memory consumption and performance in our setup (thank you very much!). 
However, this morning I spotted a completely new hotspot:

![image](https://user-images.githubusercontent.com/5798698/100840161-c6705280-3475-11eb-92d8-b1a5c5f9c2e7.png)

**To Reproduce**
Running a large number of queries inside yourkit with object allocation recording enabled.

**Comment by dfa1** [comment]
NB: queries don't have directives

**Comment by dugenkui03** [comment]
The` java.util.stream` operation in `FpKit.groupingBy` cost too much.

Filter by `Predicate` maybe faster.

**Comment by dfa1** [comment]
maybe also directly:

    private boolean getDirectiveResult(Map<String, Object> variables, List<Directive> directives, String directiveName, boolean defaultValue) {
        Optional<Directive> foundDirectives = directives.stream().filter(directive -> Objects.equals(directiveName, directive.getName())).findFirst();
        if (foundDirectives.isPresent()) {
            Directive directive = foundDirectives.get();

But since this is going to be very hot path, I would propose to remove completely `stream()` and `Optional` allocations:

    // nullable return value
    private Directive findDirectiveByName(List<Directive> directives, String name) {
        for (Directive directive : directives) {
            if (Objects.equals(directive.getName(), name)) {
                return directive;
            }
        }
        return null;
    }

**Comment by dfa1** [comment]
@dugenkui03  I actually tried the second approach (I had to scratch the itch!). What do you think?

**Comment by dugenkui03** [comment]
> @dugenkui03 I actually tried the second approach (I had to scratch the itch!). What do you think?

Move the logic of `findDirectiveByName` to `NodeUtil`, and replace all `getXXByName` with `getNodeByName(List<NamedNode> list, String name)` will be better.

@bbakerman is that a appropriate way.

**Comment by dfa1** [comment]
@dugenkui03  thank you for the suggestion: looks better now :-)

**Comment by dfa1** [comment]
see https://github.com/graphql-java/graphql-java/pull/2123

**Comment by dfa1** [comment]
fixed, I don't see anymore this method in the profiler:

![image](https://user-images.githubusercontent.com/5798698/101740439-1af47d00-3ac9-11eb-8f3d-4930031e663f.png)
