### ISSUE TITLE
`'query'` and `'mutation'` cannot be used as field names

### ISSUE THREAD

**Issue by pcarrier** [graphql-java/graphql-java#213]
The following query fails to parse:

```
query queryDetailQuery($serviceId: ID!, $queryId: ID!, $client: String, $timeFrom: Timestamp!, $timeTo: Timestamp!) {
  service(id: $serviceId) {
    report(from: $timeFrom, to: $timeTo) {
      usageStats(clientName: $client) {
        query(id: $queryId) {
[...]
}
```

It triggers an `org.antlr.v4.runtime.NoViableAltException`.

To the best of my knowledge this should be valid GraphQL.

**Comment by dminkovsky** [comment]
Hey, thanks for the report. I confirmed the problem. This query does appear to be valid and does get parsed by the reference impl. I opened a PR #214 with a test that demonstrates this failure.

**Comment by dminkovsky** [comment]
I can also confirm that this **does not** fail if you rename the innermost field `query` to something else.

**Comment by hepin1989** [comment]
The spec does not say not allow `query` as an fieldName.
http://facebook.github.io/graphql/#sec-Names

**Comment by dminkovsky** [comment]
@pcarrier Just pushed a commit to the PR that fixes the issue. Will merge/release pending review.

Thank you.

**Comment by dminkovsky** [comment]
PS. The test added in this PR is in currently in a temporary location for easy visibility and needs to be moved to a better spot before merge.
