### ISSUE TITLE
Small performance optimization: SimpleInstrumentation should use SimpleInstrumentationContext.noOp()

### ISSUE THREAD

**Issue by belks** [graphql-java/graphql-java#2131]
Hi,
The SimpleInstrumentation is creating a lot of useless SimpleInstrumentationContext objects. I suggest using the already existing SimpleInstrumentationContext.noOp() instead to save some memory allocations and GC overhead.

**Comment by dfa1** [comment]
@andimarek I can confirm it:

![image](https://user-images.githubusercontent.com/5798698/104182531-e568e980-5410-11eb-8f7f-c26979ac698e.png)

**Comment by dfa1** [comment]
well, SimpleInstrumentationContext.noOp() is really creating a new instance at every invocation.

 Maybe the original intent is to allocate it just once (i.e. a static final field)? @bbakerman
