### ISSUE TITLE
There is no scalar implementation for the named 'GraphQLLong' scalar type

### ISSUE THREAD

**Issue by UglyHobbitFeet** [graphql-java/graphql-java#2134]
I read the docs and did the following:

Gradle:
```
implementation 'com.graphql-java:graphql-java:15.0' // Also tried v16.1
implementation 'com.graphql-java:graphql-java-extended-scalars:15.0.0'
```

Java:
```
import graphql.scalars.ExtendedScalars;
...
newRuntimeWiring()
  .scalar(ExtendedScalars.GraphQLLong)
  .type(...).build();
```

GraphQL:
```
scalar GraphQLLong
type Mutation {
  myTest(someValue:GraphQLLong): String
}
```

And I get the error:
```
SchemaProblem{errors=[There is no scalar implementation for the named  'GraphQLLong' scalar type]}
graphql.schema.idl.SchemaGenerator.makeExecutableSchema(SchemaGenerator.java:74)
graphql.schema.idl.SchemaGenerator.makeExecutableSchema(SchemaGenerator.java:52)
```
I notice if I comment out the java lines, it gives me the same error.  I verified that the scalar is there via printout of the RuntimeWiring objects getScalars() method.

```
GraphQLScalarType{name='Long', description='Long type', coercing=graphql.scalars.java.JavaPrimitives$1@5e08b120}
```
What am I doing wrong?

**Comment by dfa1** [comment]
```
scalar GraphQLLong
type Mutation {
  myTest(someValue:GraphQLLong): String
}

```
IMHO here you should use *long*

**Comment by UglyHobbitFeet** [comment]
That's what I originally had but it's no longer a valid type

**Comment by dfa1** [comment]
so if you have:
```
newRuntimeWiring()
  .scalar(ExtendedScalars.GraphQLLong)
  .type(...).build();
```

and:

```
scalar Long
type Mutation {
  myTest(someValue: Long): String
}
```

you still see the problem?

**Comment by UglyHobbitFeet** [comment]
That works perfectly, thanks!  I wasn't aware you could do that as the docs
I was looking at (
https://github.com/graphql-java/graphql-java-extended-scalars) had the
scalar types identically match in the graphqls and .java side.

**Comment by dfa1** [comment]
you're welcome! 😉

**Comment by dfa1** [comment]
@UglyHobbitFeet  I would close this bug as there is no bug to fix here :)

**Comment by sureshkumar2004** [comment]
> so if you have:
> 
> ```
> newRuntimeWiring()
>   .scalar(ExtendedScalars.GraphQLLong)
>   .type(...).build();
> ```
> 
> and:
> 
> ```
> scalar Long
> type Mutation {
>   myTest(someValue: Long): String
> }
> ```
> 
> you still see the problem?

what is the the .type(...)   for Long Java type

**Comment by bbakerman** [comment]
You only really need to make the scalar available via that 

```
newRuntimeWiring()
  .scalar(ExtendedScalars.GraphQLLong)
```

The SDL code generation code will handle the fact that the `someValue` argument is a Long and match it to the provided `ExtendedScalars.GraphQLLong` instance

`.type(...)` here is a `graphql.schema.idl.TypeRuntimeWiring` which is about fields and data fetchers and type resolvers

**Comment by Manoj-t** [comment]
@sureshkumar2004 have you been able to figure out what is the .type in for Long Java type ? If so, can you please help me
