### ISSUE TITLE
SchemaPrinter creates schema with syntax error when optional arguments for directives are not provided

### ISSUE THREAD

**Issue by lksvenoy-r7** [graphql-java/graphql-java#2141]
**Describe the bug**
When using the SchemaPrinter I noticed that it would create invalid schemas if trying to parse a schema containing custom directives that do not have arguments provided to its optional directives.

For example, if you have a directive that looks like this:
`directive @auth(roles: [String!]) on FIELD_DEFINITION`

And you use it on a type like this
`doAThing(id: ID!) @auth`

The SchemaPrinter will print that line like this
`doAThing(id: ID!) @auth()`

which is an invalid schema

**To Reproduce**
See above. Create a directive with an optional argument and try to use it in a schema without adding arguments. The SchemaPrinter will output it with empty argument brackets.

Example test:
```
var schemaString = "directive @auth(roles: [String!]) on FIELD_DEFINITION\ntype Query { hello: String! @auth }";
var schema = new SchemaPrinter().print(UnExecutableSchemaGenerator.makeUnExecutableSchema(new SchemaParser().parse(schemaString)));
assertFalse(schema.contains("()"));

// Actual output is 
type Query {
  hello: String! @auth()
}
```

**Comment by dugenkui03** [comment]
This bug is fixed in #2142

**Comment by lksvenoy-r7** [comment]
Great stuff @dugenkui03 👍

**Comment by andimarek** [comment]
contained in 16.2
