### ISSUE TITLE
When a NonNull input field is not provided, should it be coerced to default value if present?

### ISSUE THREAD

**Issue by bbakerman** [graphql-java/graphql-java#2177]
When a NonNull input field is not provided, should it be coerced to default value if present?

However, with the following (simplified) situation, I got a NonNullableValueCoercedAsNullException
```
input ListSnacksInput { 
  kitchen: [Kitchen!]! = [] 
  startPageToken: String 
} 
type Query {
  listSnacks(input: ListSnacksInput!) : [Snacks!]!
}


query ($input: ListSnacksInput!){
  listSnacks(input: $input) {
     ...
  }
}
variables:
{
  input: {startPageToken: "dummyToken"}
}
```

Here's the source [code](https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/execution/ValuesResolver.java#L199) that checks if the value is null and resolve the value to default value if possible. But it is called after [#coerceValue](https://github.com/graphql-java/graphql-java/blob/59cd870263031113a5ef3477ea862b24a0d1b8f5/src/main/java/graphql/execution/ValuesResolver.java#L142), which will throw exception first if the value is null.

_Originally posted by @mingh2 in https://github.com/graphql-java/graphql-java/discussions/2172_

**Comment by liautaud** [comment]
I've ran into the same problem recently, thanks for the fix!

**Comment by pelletier197** [comment]
We encountered the same issue here! It's an important issue for us, because when adding a new field with a default value for backward-compatibility,  it breaks our client. Thanks a lot for the fix!
