### ISSUE TITLE
DataFetcher

### ISSUE THREAD

**Issue by mmjd** [graphql-java/graphql-java#22]
Hi,
Suppose that I have defined the following schema hierarchy:

{ person { department { office (rate: 10) { rate } } }

this will be translated to a JPA join to fetch data from a SQL database. I could not find a simple way to get the office argument in person data fetcher. getting office argument in its own data fetcher is simple but where's the place to use all this arguments to create and execute a query? I thought I can use context to pass data around but it does not seem very clean. would you please suggest a pattern?

Regards,

**Comment by andimarek** [comment]
I'm not sure I understand you completely, but you want to have access to the office argument, when fetching the person?

I think you should model it in another way then, because depending on the something deeper in the graph is against the idea of graphql. If the office argument influences the person, it should be a person argument.

I hope this helps. 

Regards,
Andi

**Comment by mmjd** [comment]
thanks Andi, but we have the following example in graphql specification draft:

```
{
  user(id: 4) {
    id
    name
    profilePic(width: 100, height: 50)
  }
}
```

suppose that profilePic part is defined as fragment inside a relay container and has merged into the above query for fetching. how can I find user and its profile picture from database in user datafetcher while I have only access to profilePic arguments in its own dataFetcher? do I have to move profile picture arguments to user?

Regards,

**Comment by andimarek** [comment]
You have access to the user object via the `source` attribute of the [DataFetchingEnvironment](https://github.com/andimarek/graphql-java/blob/master/src/main/java/graphql/schema/DataFetchingEnvironment.java#L10) .

The user is resolved before the `DataFetcher` for the profilePic is called, so you can access the User in there.

Or you could also fetch the User AND all possible profilePics in all supported sizes at once, but still you would need a simple DataFetcher to return only the desired size.

And yes: If you really need or want only one `DataFetcher` with the User AND the one specific profilePic, you would need to move the argument for the size to the User. But then of course you loose the ability to select different sizes without knowing the User.

**Comment by yrashk** [comment]
@mmjd was your original issue resolved (i.e. can this ticket be closed)?
