### ISSUE TITLE
SchemaPrinter outputs empty argument list when all argument values are empty or null

### ISSUE THREAD

**Issue by briankrug** [graphql-java/graphql-java#2206]
SchemaPrinter violates the spec in that it will print empty arguments for directives if all the argument values are null. graphql.schema.idl.SchemaPrinter lines 808-826 need to be altered to not append the begin parenthesis until argValue is not null or empty (and obviously the end parenthesis must only be appended at the end when the begin parenthesis is appended).

And example of a SDL fragment that when parsed and then printed would cause this issue:
`directive @resolve(exception: String) on FIELD_DEFINITION
type A {
    id: ID!
}
type B {
     id: ID!
     b: B @ resolve
}
`

**Comment by bbakerman** [comment]
Since you have done an excellent job in identifying the problem all that is left is to make a PR and help this open source project get better :)

**Comment by briankrug** [comment]
Looks like https://github.com/graphql-java/graphql-java/issues/2141 resolved this
