### ISSUE TITLE
Rethink memory overhead of SourceLocation 

### ISSUE THREAD

**Issue by andimarek** [graphql-java/graphql-java#2208]
Every single Ast Element has `SourceLocation` which is probably too much. It is only needed for errors and consumes a lot of memory unused otherwise.

We should think of ways optimizing it.

**Comment by deepakguruu** [comment]
We have faced a similar issue where source location object utilised additional memory(about 150KB, 15% of schema object).
Any updates on the fix for this issue @andimarek

**Comment by bbakerman** [comment]
Fixed in #2394

**Comment by balasubramaniam-p** [comment]
Hi

We are facing the same issue where out of 16 MB [Total size of GraphQL], nearly 2 MB is occupied by this `SourceLocation objects.` 

<img width="677" alt="Screenshot 2023-11-21 at 2 37 43 PM" src="https://github.com/graphql-java/graphql-java/assets/151619887/4ff74d1d-446e-41e0-885f-50965fd39ae9">

**Comment by bbakerman** [comment]
`graphql.parser.ParserOptions#isCaptureSourceLocation` can be set to false to stop the parser from creating `SourceLocation` objects.  It's on by default but it can be turned off

**Comment by balasubramaniam-p** [comment]
Thanks @bbakerman
