### ISSUE TITLE
Field Collector as possible optimization

### ISSUE THREAD

**Issue by andimarek** [graphql-java/graphql-java#2209]
Looking at some Microbenchmarks it seems that `FieldCollector` could be optimized. Especially `ConditionalNodes` which is called by `FieldCollector` is worth looking at.

**Comment by andimarek** [comment]
One idea: is to not use MergedField at all inside the collector.

**Comment by dfa1** [comment]
@andimarek  please have a look #2216

**Comment by bhabegger** [comment]
@dfa1 @andimarek @bbakerman  Anything to be done here ?

**Comment by dondonz** [comment]
Hello I'm closing this ticket as it's quite an old one, there is nothing to do right now.
