### ISSUE TITLE
SchemaPrinter does not preserve the declaration order of Definitions and Fields

### ISSUE THREAD

**Issue by briankrug** [graphql-java/graphql-java#2213]
SchemaPrinter imposes its own sorting to Definitions and Fields. It prints Interfaces first, then Unions, Objects, Enums, Scalars and lastly Inputs. Within each of these it sorts the types by name. And within each Type it sorts the fields by their name. It would be very helpful to producing a logically ordered schema (instead of alphabetically ordered) to add an option to SchemaPrinter that would not do such sorting but would retain the order in which these definitions and fields were added to the schema.

**Comment by bbakerman** [comment]
This is REALLY hard - really hard to garuntee and order that can survive a parse and schema generation and all the HashMaps that might involve.

SchemaPrinter has `graphql.schema.GraphqlTypeComparatorRegistry` which is a set of comparators to use

It has a graphql.schema.GraphqlTypeComparatorRegistry#AS_IS_REGISTRY which is defined as `return (o1, o2) -> 0;`

I think you want to use that - BUT we cant garuntee its in the parser text order   - its the order they come out of a schema 

We never aimed for SDL round trips eg SDL text -> schema -> SDL text (being the same)

**Comment by bbakerman** [comment]
We are not going to aim to every do this I think
