### ISSUE TITLE
Custom scalars cannot be used as directive argument

### ISSUE THREAD

**Issue by Andy2003** [graphql-java/graphql-java#2239]
**Describe the bug**
Using a custom scalar as argument of a directive will fail on schema compilation with the following error:

```
SchemaProblem{errors=['Test' [@4:13] uses an illegal value for the argument 'arg' on directive 'test'. Argument value is of type 'ObjectValue', expected a scalar.]}
	at graphql.schema.idl.SchemaGenerator.makeExecutableSchema(SchemaGenerator.java:91)
```

**To Reproduce**
```graphql
directive @test(arg: MyType) on OBJECT
scalar MyType
type Test @test(arg: { some: "data" }){
    field: String 
}
type Query {
    field: Test
}
```

with the custom scalar registartion:

```java
def runtimeWiring = RuntimeWiring.newRuntimeWiring()
                .scalar(new GraphQLScalarType("MyType", "", new Coercing() {
                    @Override
                    Object serialize(Object input) throws CoercingSerializeException {
                        return input
                    }

                    @Override
                    Object parseValue(Object input) throws CoercingParseValueException {
                        return input
                    }

                    @Override
                    Object parseLiteral(Object input) throws CoercingParseLiteralException {
                        return input
                    }
                }))
                .build()
```

This issue can be solved by removing the type check in [graphql.schema.idl.ArgValueOfAllowedTypeChecker#checkArgValueMatchesAllowedScalar](https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/schema/idl/ArgValueOfAllowedTypeChecker.java#L215-L221)

**Comment by enriquedacostacambio** [comment]
@Andy2003 you may want to clarify that the problem happens specifically when using custom scalars that serialize to an object.

**Comment by bbakerman** [comment]
We had this wrong.  We cant restruct what AST literals are allowed into a scalar.  It is up to the scalar to decide.

So the scalar can throw an exception but our prechecking code cant decide for it.

This has been fixed


See https://github.com/graphql-java/graphql-java/pull/2429
