### ISSUE TITLE
Why give @fetch by default?

### ISSUE THREAD

**Issue by qzchenwl** [graphql-java/graphql-java#2254]
It's not specified by the standard Spec. I defined @fetch for some other usage (not by SchemaDirectiveWiring) and ran into problems.

**Comment by bbakerman** [comment]
We chose to make this extension ourselves - it allows a field to be fetched from another property other than its name but in SDL only

While we try to follow spec, this does not mean we cant have extensions to it.  This is one extension that graphql-java chose to do.  We have had others.

**Comment by bbakerman** [comment]
We reconsidered our position on `@fetch`

https://github.com/graphql-java/graphql-java/pull/2455
