### ISSUE TITLE
Duplicate fields in SelectionSet

### ISSUE THREAD

**Issue by jmartisk** [graphql-java/graphql-java#2275]
**Describe the bug**
Calling `dataFetchingEnvironment.getSelectionSet().getFields()` returns each selected field twice.

For example:
```
type Query{jim: Person}
type Person {firstName: String, surname: String}
```

data fetcher:
```
public Object get(DataFetchingEnvironment environment) {
   for (SelectedField field : environment.getSelectionSet().getFields()) {
      System.out.println("field name: " + field.getName());
   }
   // return the result
}
```
 
When querying `{jim {firstName}}`, the data fetcher will print the `firstName` field twice.

**To Reproduce**
Standalone reproducer: https://github.com/jmartisk/reproducers/tree/main/graphql-duplicate-fields

**Comment by josephlbarnett** [comment]
Confirmed seeing this as well, is `getImmediateFields()` in graphql-java 16 the intended replacement for `getFields()` usages in graphql-java 15?

**Comment by knotenpunkt** [comment]
maybe a related issue/feature we could have in the future: https://github.com/graphql-java/graphql-java/discussions/2280

a getSelectionSet directly on the parent

and yes the dupclicate fields i can confirm

**Comment by fforw** [comment]
I want all fields including the object fields on all levels below rows. This way I'm also getting them relative to "rows" which convenient for me.

**Comment by bbakerman** [comment]
Ahh I see what's happening here

We have entries in out internal structures that allows for two types of glob matching

```
normalisedSelectionSetFields = {LinkedHashMap@2214}  size = 2
 "Person.firstName" -> {ArrayList@2296}  size = 1
  key = "Person.firstName"
  value = {ArrayList@2296}  size = 1
 "firstName" -> {ArrayList@2297}  size = 1
  key = "firstName"
  value = {ArrayList@2297}  size = 1
  ```
  
  So we would allow glob matching on `firstName` and also on `Person.firstName`.

but when we call `getFields` we are sending back what is essentially the same field.

I need to look into this more when we have `Pet` interfaces with `Dog.name / Cat.name` cases

Thanks for the reproduction code

**Comment by bbakerman** [comment]
Fixed
