### ISSUE TITLE
Default data fetcher on Code Registry not being invoked

### ISSUE THREAD

**Issue by silospen** [graphql-java/graphql-java#2282]
**Describe the bug**
When setting a defaultDataFetcher on a GraphQLCodeRegistry, I expect that data fetcher to be selected for every field that doesn't have an explicit data fetcher set. Instead, it ignores the defaultDataFetcher and falls back to a PropertyDataFetcher.

I *think* the bug is in this code interaction: 
 - SchemaGeneratorHelper queries the GraphQLCodeRegistry to ask if there's a dataFetcher for these coordinates: https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/schema/idl/SchemaGeneratorHelper.java#L971
 -  If there isn't one, it falls back to the default provided by the wiring factory, then falls back to the PropertyDataFetcher
 - GraphQLCodeRegistry.hasDataFetcherImpl only looks at the systemDataFetcherMap and dataFetcherMap, it never interacts with the defaultDataFetcherFactory even if one is custom set https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/schema/GraphQLCodeRegistry.java#L89
 - The net effect is that the correct data fetcher would be used if this method returned true, but it never returns true when only the defaultDataFetcherFactory is set.

**To Reproduce**
I forked your tutorial here, this is where the wiring up of the default is done: https://github.com/silospen/tutorials/blob/master/book-details/src/main/java/com/graphqljava/tutorial/bookdetails/GraphQLProvider.java#L51

You can see the diff against your tutorial code here: https://github.com/silospen/tutorials/commit/72b8e8aad8ea94bfa9acd2f3ce22a5f0b426b4d8

I would expect this code to horribly break the response, because all of the properties would now be trying to use the author data fetcher instead of property data fetchers, but it works fine. Your example request is:

```
{
  bookById(id: "book-1"){
    id
    name
    pageCount
    author {
      firstName
      lastName
    }
  }
}
```

and the unexpected response is:

```
{
  "data": {
    "bookById": {
      "id": "book-1",
      "name": "Harry Potter and the Philosopher's Stone",
      "pageCount": 223,
      "author": {
        "firstName": "Joanne",
        "lastName": "Rowling"
      }
    }
  }
}
```

Let me know if i've misunderstood something here, thanks for taking a look!

**Comment by dugenkui03** [comment]
You could define default DataFetcher by implementing WiringFactory and overriding `getDefaultDataFetcher`.

detail in: https://github.com/graphql-java/graphql-java/blob/22314931ecd2c0631b289a48f099b4a7ed12c74f/src/test/groovy/graphql/schema/idl/WiringFactoryTest.groovy#L296

**Comment by silospen** [comment]
Thanks for the workaround, that works fine but it's a shame to have to inject another object rather than have all my logic in the GraphQLCodeRegistry.
