### ISSUE TITLE
HelloWorld.java --There is a small mistake

### ISSUE THREAD

**Issue by liaofangcai** [graphql-java/graphql-java#229]
Object.staticValue("world").build()

**Comment by dminkovsky** [comment]
Thank you for posting.

It's correct actually. The master branch right now lets you provide Builder
objects in schema definition. Check out this commit
https://github.com/graphql-java/graphql-java/commit/be0e7f3ae90a4c53fd4c5dfe43b4d9cff94f59dd

Were you looking for something?

среда, 19 октября 2016 г. пользователь 廖芳才 написал:

**Comment by IamCornholio** [comment]
I think people are using the released version to try this out and the released version doesn't have that commit. Perhaps the readme should also point to a released version?

**Comment by liaofangcai** [comment]
I found it. thanks
