### ISSUE TITLE
Change loglevels from info to warn or debug..

### ISSUE THREAD

**Issue by aschrijver** [graphql-java/graphql-java#230]
At various places there is logging taking place at `info` level. IMO this level is incorrect.
Messages are either clogging the log (should be debug-level) or indicate a query failure (should be warn).

Log.info that should be warn:
https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/execution/ExecutionStrategy.java#L42

Log.info that should be debug:
https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/GraphQL.java#L60

**Comment by GrigoryPtashko** [comment]
+1

I also think that "Executing operation ..." should be at the debug level.

**Comment by dminkovsky** [comment]
Yes! Do you feel like PRing this?

**Comment by aschrijver** [comment]
Sure.

**Comment by dminkovsky** [comment]
Thanks!
