### ISSUE TITLE
Duplicating string values from schema

### ISSUE THREAD

**Issue by deepakguruu** [graphql-java/graphql-java#2314]
<img width="1175" alt="Screen Shot 2021-05-03 at 6 38 41 PM" src="https://user-images.githubusercontent.com/29925661/116879895-e54e5d00-ac3e-11eb-8a4e-bf2e195e2ad8.png">

As seen in the attached memory dump, simple strings like \n and \t are being duplicated.
Can't this be solved using intern while building a schema?

**Comment by deepakguruu** [comment]
Upon further analysis, we found the source of most of these strings to be at IgnoredChar(graphql.parser.GraphqlAntlrToLanguage.createIgnoredChar()).
A simple intern of the text returned from the token saved significant memory.
`token.getText().intern()`
Size before intern:
![image](https://user-images.githubusercontent.com/29925661/117129224-0b4d3c00-adbc-11eb-9ae0-34c09bf80e65.png)
Size post intern:
![image](https://user-images.githubusercontent.com/29925661/117129258-186a2b00-adbc-11eb-8ea3-f355e28d4b6a.png)
A reduction of ~250KB was observered.

PS: May I know what the purpose of this ignored char object is? Can it be opt-out?

**Comment by sonallux** [comment]
> Can it be opt-out?

There is already issue #2207 for making `IgnoredChars` opt-out.

**Comment by bbakerman** [comment]
Thanks for reporting this in detail.

We will use the early issue as the ticket 

Duplicate
