### ISSUE TITLE
Query Complexity throws NPE for list input as a variable with default value.

### ISSUE THREAD

**Issue by srinivasankavitha** [graphql-java/graphql-java#2330]
**Describe the bug**
When MaxQueryComplexityInstrumentation is enabled for queries that take a list as input variable with default values, we get an NPE.

**To Reproduce**
Set up a test case to demonstrate the scenario here: https://github.com/graphql-java/graphql-java/pull/2329
```
type Query{
    hello(names: [String]): String
 }            
      
       
query Hello(\$names:[String] = ["Someone"]) {
    hello(name: \$names)
} 
```

**Comment by bbakerman** [comment]
See https://github.com/graphql-java/graphql-java/pull/2337
