### ISSUE TITLE
Issue w/ building zip and gzip downloads

### ISSUE THREAD

**Issue by dr-a-patton** [graphql-java/graphql-java#2350]
The build.gradle file automatically assumes the code has been fetched via git, and requires git hash to return a non-error result; however, the code is also offered via zip and gzip tarball.  This is inconsistent.  If the code is offered via zip or tarball, it should be fully buildable w/o a git requirement.

**Comment by dr-a-patton** [comment]
Simply adding a build switch or even manual build instructions to alter/override the git requirement would probably be sufficient... at least it would provide lip service to zip and tarball support.

**Comment by andimarek** [comment]
@dr-a-patton you are right, this could be improved. 

We are happy to accept a PR which would allow that. If you are able to submit one, that would be awesome!

**Comment by dr-a-patton** [comment]
Ah!  Dr., heal thyself!  ;-)  Unfortunately, I'm still a neophyte in gradle and groovy, but assuming I get a spare moment, I may take a swing at it... unless somebody w/ more time and skillz beats me to the punch (here's hoping! ;-) )

**Comment by andimarek** [comment]
@dr-a-patton it is fixed now on master.
