### ISSUE TITLE
Support for an async DataFetcherExceptionHandler

### ISSUE THREAD

**Issue by rstoyanchev** [graphql-java/graphql-java#2356]
The need for async exception handling is perhaps less obvious than for async data fetching but fundamentally no reason why it can't arise in either. For example an exception handler might need to retrieve security context from a remote source, write a record of the exception to a data store, and so on. 

In addition, with async data fetchers, there is likely to be some strategy for context passing in which case there is a need for consistency in how this is done across data fetchers and exception handlers.

**Comment by bbakerman** [comment]
See #2371
