### ISSUE TITLE
Excessive lock contention in ExecutionContext.getErrors() 

### ISSUE THREAD

**Issue by dfa1** [graphql-java/graphql-java#2369]
**Describe the bug**
According to yourkit [1] we have a lot of blocking happening in this line (almost all red blocks are related to this line):

`overallResult.complete(new ExecutionResultImpl(builder.build(), executionContext.getErrors()));`

as `ExecutionContext` defines it as `synchronizedList`:

```
    private final List<GraphQLError> errors = Collections.synchronizedList(new ArrayList<>());

    /**
     * @return the total list of errors for this execution context
     */
    public List<GraphQLError> getErrors() {
        return ImmutableList.copyOf(errors);
    }
```

[1] ![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/5798698/120625020-8ceac500-c461-11eb-9fa6-634dfa8bc3fb.png)

**To Reproduce**
I don't have reproducer but, right now we have a workaround to get the "errors" via reflection, that delivers a massive improvement.

@andimarek @bbakerman IIRC we already discussed this once

**Comment by dfa1** [comment]
@andimarek  @bbakerman please let me elaborate a bit: right now errors are copied for every intermediate result in `AbstractAsyncExecutionStrategy`:

      protected BiConsumer<List<ExecutionResult>, Throwable> handleResults(ExecutionContext executionContext, List<String> fieldNames, CompletableFuture<ExecutionResult> overallResult) {

maybe it is possible to copy the errors only in the very last result (top-level)? In this way, errors are collected in the `ExecutionContext` and copied once at the very end (i.e. no contention for all error-free queries).

**Comment by bbakerman** [comment]
Yeah this is not great.  I think we will have to improve this.

In order to refactor to allow errors to be aggregated once and copy once is a big refactor.

however I think if we get rid of this lock contention via a ConcurrentWriteArrayList then we should be able improve this

**Comment by bbakerman** [comment]
#2371 contains a fix for the above.  We move away from synchronized list to a CopyOnWriteArrayList

In the cases where there are zero errors it will have much less contention

**Comment by dfa1** [comment]
@bbakerman it looks very promising, thank you!

(should I close this issue?)

**Comment by dfa1** [comment]
and basically this is reverting the work done here: https://github.com/graphql-java/graphql-java/pull/2008

**Comment by andimarek** [comment]
@dfa1 can we write a JMH test to see what is faster?

**Comment by bbakerman** [comment]
Actually now that you bring that up you have jogged a memory.  I must look into it again.

Off hand we want the happy path to be fast because most graphql queries result in zero errors

**Comment by bbakerman** [comment]
> can we write a JMH test to see what is faster?

We already had one - as expected Collections.synchronisedList() is much faster because of the array copying in the ConcurrentWriteArrayList.

However it's not that simple.

@dfa1 has identified that we have significant read contention on the blessed path of no errors.  So we are paying a penalty when there is ZERO errors - which is the worse case.

So if an implementation generates an error on every request then they will have more work to do on write - 

Whereas I expect that the most common case is ZERO errors and hence this is more efficient for this case - because read copy of the list is a simple array copy.

**Comment by dfa1** [comment]
@bbakerman yes, CopyOnWriteArrayList should help a lot in case of no errors (99.99% of the queries in our applications). I tried (and failed) to attach the errors only for final, top-level `ExecutionResult`.

 I did the changed inside `GraphQL`  but there are some tests failures (3) for individual unit tests for execution strategies. @bbakerman should I create a PR? as you said the clean refactoring is a lot of work

**Comment by andimarek** [comment]
@dfa1 yes please: open a PR, even if there a still failing tests, so we can talk about it better.

**Comment by andimarek** [comment]
What about this? https://github.com/graphql-java/graphql-java/pull/2377

This basically removes any locking for the happy path, but it uses an AtomicReference to access the list of errors (which is immutable).

**Comment by bbakerman** [comment]
I have changed my PR to use Andi's AtomicRef + ImmutableList

Benchmarking shows its in the same order of magnitude of speed as CopyOnWriteArray - so while not better its not worse

I will leave it like that for consistency with other code - we want to embrace ImmutableLists where we can for "copying efficiencies" elsewhere

**Comment by dfa1** [comment]
nice design and implementation... thank you guys! <3

**Comment by dfa1** [comment]
@andimarek @bbakerman testing the latest snapshot from maven central with this fix:

![image](https://user-images.githubusercontent.com/5798698/124778462-49dcaf80-df41-11eb-9281-bfe4ba56959b.png)

basically I don't see anymore any lock contentions[1]. Thank you very much for the fix!

[1] for the happy path without errors
