### ISSUE TITLE
Please add ExecutionContext back into DataFetchingEnvironment

### ISSUE THREAD

**Issue by briankrug** [graphql-java/graphql-java#2373]
We use ExecutionContext in our Resolvers to add Errors as we validate or execute operations. However, this property was removed from DataFetchingEnvironment in commit https://github.com/graphql-java/graphql-java/commit/30769d1e39ff7f616ffe4adc1ef03712c64343d7#diff-dcd57114fc947cae6b8a05505cfc2aee70237d1dbab27e35743f9826eecd1dfd. Please, put it back! We rely on this!

**Comment by bbakerman** [comment]
The replacement mechanism is `graphql.execution.DataFetcherResult`

if a data fetcher returns this object it is able to return data, errors and local context.

```
return DataFetcherResult.newResult().error(myerror).build()
```

**Comment by briankrug** [comment]
We are using GraphQL Java Kickstart. It is just uglier to have to refactor all our resolvers to return DataFetcherResult instead of the main type. Is there a reason this was replaced and can't be left there for more flexibility?

**Comment by bbakerman** [comment]
>  Is there a reason this was replaced and can't be left there for more
flexibility?

Yup - we should never had made ExecutionContext public API in retrospect.
It's there for the query engines and not really for DataFecthers

So we removed it.  This gives us the ability to improve the engines,
potentially using different representations of execution context within
them.

**Comment by briankrug** [comment]
So could `addError` and `hasError` methods be added to DataFetchingEnvironment?

**Comment by bbakerman** [comment]
> So could addError and hasError methods be added to
DataFetchingEnvironment?

All things are possible but if you need to refactor a Datafecther to called
`dfe.addError` then you can refactor it to called `return
DataFetcherResult.newResult(data).errors().build()`
