### ISSUE TITLE
Throw more granular exceptions for better error handling

### ISSUE THREAD

**Issue by okorz001** [graphql-java/graphql-java#239]
Currently graphql-java mostly only throws GraphQLException. (AssertException is thrown during graph creation for duplicate enums or fields.) This is hard to work with because it is unclear if the error is with the GraphQL query (input/client) or the data fetcher (output/server).

Most services would like to behave differently depending on client or server failure. For example, a web service would like to return 4xx or 5xx statuses respectively. I am currently inspecting the stack trace to do so which is slow and brittle.

Example client error -- invalid integer literal in query
```
src/main/java/graphql/Scalars.java:47:                throw new GraphQLException("Int literal is too big or too small");
```

Example server error -- data fetcher returned null for non-nullable type
```
src/main/java/graphql/execution/ExecutionStrategy.java:54:                throw new GraphQLException("Cannot return null for non-nullable type: " + fields);
```

**Comment by bbakerman** [comment]
I think this can be closed since it changed significantly since 2016
