### ISSUE TITLE
ValuesResolver.argumentMap should return only arguments which got values in query/mutation definition

### ISSUE THREAD

**Issue by arkadyz1** [graphql-java/graphql-java#2391]
Hi,

Suppose we have mutation "updateUser" with 2 arguments: "name", and "newName". We don't have variable definition for "newName", like bellow

```
{"operationName":"updateUser","variables":{"userName": 23},"query":"
mutation updateUser($userName: String!, $newName: String) {
    updateUser(userName: $userName,  newName:$newName) {
.......
    }
}
"}
```

In datafetcher object in DataFetchingEnvironment.getArguments() we get both arguments: "name" and "newName", and value of newName is null. The existence of "newName" in arguments map misleads the business logic, because we don't know if the user put null intentionally or this field should just be ignored.

I think, arguments maps should contain only arguments that user sent in the variables object. 

We are working in version 14.1, was this behavior changed in another version ?

**Comment by bbakerman** [comment]
This has been a source of confusion for us over the years.  Early graphql did not clearly specify the expected behavior AND we get a few things wrong.

I am pretty sure this has been fixed in the latest version of graphql-java

**Comment by bbakerman** [comment]
I wrote this quick unit test to prove to myself that we have covered this case

```
    def "integration test on arg values"() {
        def sdl = """ 
        type Query { 
            f(arg1 : String, arg2 : String) : String
        } 
        """

        DataFetcher df = { DataFetchingEnvironment env ->
            showArgVal(env, "arg1") + "|" + showArgVal(env, "arg2")
        }
        def schema = TestUtil.schema(sdl, ["Query": ["f": df]])
        def graphQL = GraphQL.newGraphQL(schema).build()

        when:
        def er = graphQL.execute(ExecutionInput.newExecutionInput().query('''
                query foo($arg1 : String, $arg2 : String) {
                    f(arg1 : $arg1, arg2 : $arg2)
                }  
            ''').variables(["arg1": "val1"]))
        then:
        er.errors.isEmpty()
        er.data["f"] == "arg1:true,val1|arg2:false,null"
    }

    private String showArgVal(DataFetchingEnvironment env, argName) {
        "$argName:" + env.containsArgument(argName) + "," + env.getArgument(argName)
    }
```

and it works - `arg1` in this case (the only 1 with a variable value) comes across with a value meanwhile `arg2` is NOT in the argument map (via the `containsArgument` call) and it will of course map to null if you ask for it direct via `getArgument`
