### ISSUE TITLE
SDL scalar descriptions are not available for introspection

### ISSUE THREAD

**Issue by WMendelsohn** [graphql-java/graphql-java#2410]
**Describe the bug**

Scalar descriptions are not correctly included into a `GraphQLSchema` from a `TypeDefinitionRegistry` parsed from an SDL string. 

`GraphQLScalarType`'s definition field remains as `null`, while strangely, the description on `GraphQLScalarType.definition` includes the correct value.

This is important, as for users who load their schema from graphql SDL files, rather than building it with the builders, the descriptions never make it through to introspection.

**To Reproduce**

Using GraphQL-Java version 16.2

```java
 final String schemaSDL = ""
    + "\"\"\"\n"
    + "2-digit integer e.g. January is 01\n"
    + "\"\"\"\n"
    + "scalar Month\n"
    + "\n"
    + "type Query {\n"
    + "  currentMonth: Month\n"
    + "}\n";

final TypeDefinitionRegistry tdr = new SchemaParser().parse(schemaSDL);
final GraphQLSchema schema = new SchemaGenerator().makeExecutableSchema(tdr, RuntimeWiring.newRuntimeWiring().scalar(
    GraphQLScalarType.newScalar().name("Month").coercing(new GraphqlStringCoercing()).build()).build());
final GraphQLScalarType scalar = (GraphQLScalarType) schema.getType("Month");

assertEquals("2-digit integer e.g. January is 01", scalar.getDefinition().getDescription().getContent()); // Passes
assertEquals("2-digit integer e.g. January is 01", scalar.getDescription()); // Fails
```

**Comment by bbakerman** [comment]
When you wired in the implementation here

```

    GraphQLScalarType.newScalar().name("Month").coercing(new GraphqlStringCoercing()).build()
```

this created a  scalar with no description.

This is tricky in some regards because a Scalar needs to have a specific instance (unlike types that we can create purely from SDL) because of the code in the coercing

**Comment by WMendelsohn** [comment]
Thanks for your reply.

I can see that the description is coming in to `graphQLScalarType.getDefinition().getDescription()`.  It's not using the `GraphQLScalarType` I created with `newScalar()`, that one didn't have a definition set when I built it.  

It seems to me that it's creating a new `GraphQLScalarType` with some stuff from the SDL and some stuff from the scalar definition from the `RuntimeWiring`, in which case, couldn't we include the description from the SDL into the new scalar definition as part of that transformation, much like we include the definition?

**Comment by bbakerman** [comment]
Your right - we could do something - we transform it today.  we could transfer the description if not empty

```
        GraphQLScalarType scalar;
        if (wiringFactory.providesScalar(environment)) {
            scalar = wiringFactory.getScalar(environment);
        } else {
            scalar = buildCtx.getWiring().getScalars().get(typeDefinition.getName());
        }

        if (!ScalarInfo.isGraphqlSpecifiedScalar(scalar)) {
            scalar = scalar.transform(builder -> builder
                    .definition(typeDefinition)
                    .comparatorRegistry(buildCtx.getComparatorRegistry())
                    .specifiedByUrl(getSpecifiedByUrl(typeDefinition, extensions))
                    .withDirectives(buildAppliedDirectives(
                            buildCtx,
                            typeDefinition.getDirectives(),
                            directivesOf(extensions),
                            SCALAR,
                            buildCtx.getDirectives(),
                            buildCtx.getComparatorRegistry())
                    ));
        }
```

**Comment by bbakerman** [comment]
fixed

**Comment by WMendelsohn** [comment]
Thank you! 😄
