### ISSUE TITLE
weird version 0.0.0-$timestamp is deployed on maven central

### ISSUE THREAD

**Issue by dfa1** [graphql-java/graphql-java#2427]
**Describe the bug**
Since few weeks there are weird version number in maven central:
https://mvnrepository.com/artifact/com.graphql-java/graphql-java

![image](https://user-images.githubusercontent.com/5798698/124468865-f2500f80-dd99-11eb-8f52-24401a9fe656.png)

is that expected?

**To Reproduce**
N/A

**Comment by dfa1** [comment]
a bit of context: I would like to test these two changes before the 17.0 release:
https://github.com/graphql-java/graphql-java/issues/2369
https://github.com/graphql-java/graphql-java/pull/2394

**Comment by bbakerman** [comment]
@andimarek can explain more but the 0.0.0 for snapshots was chosen so that it did not interfere with auto build updating tools like Renovate that saw certain versions is being later than released versions.

**Comment by dfa1** [comment]
perfect, then we don't need this issue... let me close it :)
