### ISSUE TITLE
Variables are coerced twice during an execution when a field validation instrumentation is active

### ISSUE THREAD

**Issue by jenssuhr** [graphql-java/graphql-java#2458]
**Describe the bug**
It looks like variables are coerced twice during an execution using graphql-java 16.2, once in `execute` and once in `validateFieldsAndArguments`. This breaks e.g. enums with non-default names.

Variables are first coerced [here](https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/execution/Execution.java#L69), then [added to the execution context](https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/execution/Execution.java#L90).
In `FieldValidationSupport`, the `QueryTraverser` is [initialized with those variables from the execution context](https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/execution/instrumentation/fieldvalidation/FieldValidationSupport.java#L36) and coerces them again [here](https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/analysis/QueryTraverser.java#L60).

**To Reproduce**
If you have an enum value defined like this
```kotlin
GraphQLEnumType.newEnum()
    .name("MyEnum")
    .description("My enum with all lowercase names.")
    .values(
        MyEnum.values().map {
            GraphQLEnumValueDefinition.newEnumValueDefinition()
                .name(it.getLowerCaseName())
                .value(it)
                .build()
        }
    ).build()
```
the first coercion works correctly, but the second one fails.

**Comment by dondonz** [comment]
Hi @jenssuhr,

I'm trying to investigate the issue but I can't reproduce the error. Could you please help me by expanding on your example?

Could you please paste here:
1. an example query,
2. the field validation instrumentation(s) used, and
3. the name of the error when the second coercion failed

**Comment by jenssuhr** [comment]
Hi, thanks for investigating! I'll try to add an example as soon as possible.

**Comment by jenssuhr** [comment]
I just noticed that we're not using the field validation correctly. Instead of using `SimpleFieldValidation` and adding rules, we were using a separate `FieldValidationInstrumentation` for each rule and chaining them together using `ChainedInstrumentation`. Fixing that will probably also fix this issue.
Thank you for your help!
