### ISSUE TITLE
Access to upstreamPublisher/upstreamSubscriber in subscriptions

### ISSUE THREAD

**Issue by richardbizik** [graphql-java/graphql-java#2469]
### Discussed in https://github.com/graphql-java/graphql-java/discussions/2466

<div type='discussions-op-text'>

<sup>Originally posted by **richardbizik** July 15, 2021</sup>
Hi, would it be possible to add getter for upstreamPublisher into CompletionStageMappingPublisher 
https://github.com/graphql-java/graphql-java/blob/d783ec7ee30369ca2fdecdfd0b74e8bf6d96baa8/src/main/java/graphql/execution/reactive/CompletionStageMappingPublisher.java#L25
as well as use non anonymous class for Subscriber with getter for  https://github.com/graphql-java/graphql-java/blob/d783ec7ee30369ca2fdecdfd0b74e8bf6d96baa8/src/main/java/graphql/execution/reactive/CompletionStageMappingPublisher.java#L41
and another getter for DelegatingSubscription
https://github.com/graphql-java/graphql-java/blob/d783ec7ee30369ca2fdecdfd0b74e8bf6d96baa8/src/main/java/graphql/execution/reactive/DelegatingSubscription.java#L13
so we could have access to our underlying implementation. I have some info stored in these classes and executing 
``` java
GraphQL graphQL = GraphQL
        .newGraphQL(graphQLSchema)
        .instrumentation(instrumentation)
        .build();
ExecutionResult executionResult = graphQL.execute(executionInput);
executionResult.getData();
```
returns instance of CompletionStageMappingPublisher It would be useful to have access to my data stored in upstream. Or is there something I am missing and the access is already possible?</div>

**Comment by bbakerman** [comment]
done
