### ISSUE TITLE
GraphQLTypeReference for GraphQLInputType

### ISSUE THREAD

**Issue by brimworks** [graphql-java/graphql-java#247]
Currently, you can not define a GraphQLTypeReference in places that require a GraphQLInputType. This is problematic for recursively defined input types. It appears that we simply need to modify SchemaUtil so it also resolves GraphQLInputObjectType and add in a few replaceTypeReferences() implementations to handle replacing input types.

**Comment by dminkovsky** [comment]
Hey sorry I can look this up right now but there is a PR for this issue.
You'll find it if you take a look.

ср, 23 нояб. 2016 г. в 18:30, Brian Maher <notifications@github.com>:

**Comment by dminkovsky** [comment]
Ah found it https://github.com/graphql-java/graphql-java/pull/204

ср, 23 нояб. 2016 г. в 18:32, Dmitry Minkovsky <dminkovsky@gmail.com>:

**Comment by brimworks** [comment]
Thanks! I'll close my PR and this request.
