### ISSUE TITLE
Non slf4j version of graphql-java?

### ISSUE THREAD

**Issue by jleskovar** [graphql-java/graphql-java#250]
Hi there,

Bit of a long shot, but I may as well ask. Would it be possible to make available on maven central a version of graphql-java that does not rely upon or use slf4j - say via a "-no-slf4j" version suffix, or something similar? I am building a java agent that needs to bundle its own dependencies, and slf4j potentially interferes with the host application.

I would much rather not have to fork / embed source in my own code base, but I guess that can be my fallback.

Regards,
James

**Comment by dminkovsky** [comment]
Hi @jleskovar,

Thanks for opening this issue. So, in such an artifact, what will happen to all the `org.slf4j.Logger.{log,info,warn,error}` calls we have right now?

**Comment by jleskovar** [comment]
@dminkovsky my thinking is that they would just not even be called. I realise my use case is probably quite rare, as I can't have _any_ logging at all, neither at runtime or compile time. I have uploaded a fork (https://github.com/jleskovar/graphql-java) of graphql-java 2.2.0 at coordinates com.github.jleskovar:graphql-java:2.2.0-no-slf4j that completely removes slf4j from the classpath, just for my own usage.

**Comment by jleskovar** [comment]
Closing, as I have a workaround for now.

**Comment by dminkovsky** [comment]
Cool, good to hear. Sorry we couldn't help here.
