### ISSUE TITLE
 Support alter the behavior about  FieldCollector by custom directive

### ISSUE THREAD

**Issue by dugenkui03** [graphql-java/graphql-java#2525]
## issue

It seems that there is no convenient way to **support the custom operation about fragment which define in custom directive**. Things like that:

- The definitioin of directive:
```graphql
directive @skipBy(predicate: String!, dependencySources: [String!]) on FIELD| INLINE_FRAGMENT | FRAGMENT_SPREAD
```

- skip the InlineFragment fetch when `age<18` is true.
```graphql
query inlineFragmentNoType($age: Int) {
  user(handle: "zuck") {
    id
    name
    ... @skipBy(predicate:"age<18") {
      firstName
      lastName
      birthday
    }
  }
}
```

I think it is important to allow user to define directive which can skip the collection of fields. Maybe it can be supported by `Instrumentation` or `FieldCollector`.

**Comment by bbakerman** [comment]
One of the challenges of custom query directives is that often call for the "engine algorithm" to be changed by them.

In your case your `@skipBy` means something and I am guess it means skip executing certain fields if the directive expression is true.

The challenge is - how do you design an engine algorithm that is relaiable and predicatable AND can change.

Honestly I dont think you can - even inastrumentation only have certain callbacks - it does not influence how the execution engine runs.

The real way you achieve custom query directives is via a custom engine - and that is no easy bit of egineering.

**Comment by dugenkui03** [comment]
That is my way: update the document,operationDefinition and fragmentsByName in ExecutionContext when Instrumentation.instrumentExecutionContext, details in the implementation of @skipBy. 

It would be a more flexible way if field-collect behavior can be changed by directive. Will you accept #2529?

**Comment by dugenkui03** [comment]
That‘s my way: update the document,operationDefinition and fragmentsByName in ExecutionContext when Instrumentation.instrumentExecutionContext, details in [the implementation of @skipBy](https://github.com/graphql-calculator/graphql-calculator/pull/55/files#diff-132f45837bd3021a593d3635a4406fe90b4691cda98d547c9427f867980eea9c). 

It would be a more flexible way if field-collect behavior can be changed by directive, and I believe that is a common common scenario. Releated PR #2529

**Comment by dugenkui03** [comment]
Hi, @bbakerman  @andimarek , would you like to accept this change #2529 ?
