### ISSUE TITLE
What is best way to do equal check on 2 TypeDefinitionRegistry objects or 2 ObjectTypeDefinition objects?

### ISSUE THREAD

**Issue by arjunballa** [graphql-java/graphql-java#2536]
I have a requirement to compare 2 graphql api schema definitions for equality. 
I looked at `objectTypeDefinition.isEqualTo(Node)` method but it is just doing name comparison but not checking for `fieldDefinitions`

What s the best way to do?

**Comment by bbakerman** [comment]
The first thing to recognise is that the `XXXDefinition` objects are parsed AST nodes - they are not types.  They are parsed bits of text.

And yes the equality operations on them (including the `.equalTo` methods) have not been implemented.  We do not recommend using them for equality checks.  

But again they are NOT graphql types - they are parsed elements from SDL text
