### ISSUE TITLE
Android gradle gives dependency issue

### ISSUE THREAD

**Issue by smarques84** [graphql-java/graphql-java#254]
I am trying to using this library on my project but i kept having this error:
Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: org/antlr/v4/runtime/ANTLRErrorListener.class

I noticed that this project seems to use Guava which i am already using for other parts on my project but commenting my guava dependency does't fix it for me because i rely on other guava dependencies,  how can i fix this issue?

**Comment by dminkovsky** [comment]
Hey maybe this is related to #225. That issue is fixed but not-yet-released. Try this workaround:

  compile('com.graphql-java:graphql-java:2.2.0') {
        exclude module: 'antlr4'
    }

This project doesn't use Guava, though. Its only runtime dependency is Slf4j.

**Comment by smarques84** [comment]
Thank you @dminkovsky , this fixed my issue!
