### ISSUE TITLE
SchemaTypeChecker does not check interface extension field types

### ISSUE THREAD

**Issue by ctrlcwho** [graphql-java/graphql-java#2542]
https://github.com/graphql-java/graphql-java/blob/d2ca93c19e952968ae0b5bdeefc7f951b3b2f344/src/main/java/graphql/schema/idl/SchemaTypeChecker.java#L380

The SchemaTypeChecker class only checks type extension field types, not interface extension fields, this seems like inconsistent behavior. 
To reproduce, simply run the following type registry through graphql.schema.idl.SchemaTypeChecker#checkTypeRegistry:
```
interface BaseType {
  id: String
}
extend interface BaseType {
  reference: OtherType
}
```
No error related to `OtherType` not existing within the type registry will be thrown, but when you make the interface into a type, the type registry checker will return a validation error.

**Comment by bbakerman** [comment]
When we first put the TypeDefinitionRegistry code in place, we put in a series of checks to make sure we had a consistent and correct schema - aka these rules.

Later we learnt that there are cases that can be really checked until you have a full schema so we started to check schema invariants the GraphqlSchema `.build()` code.

I guess my point of this story is - if this referenced `OtherType` can exist in `GraphqlSchema` form then its a bug.  

However if after calling `SchemaParser + SchemaGenerator` there is an SchemaProblem throw by some part of the code then its not a bug, just not implemented all in SchemaTypeChecker

**Comment by dondonz** [comment]
Hello as this issue is quite old and hasn't received any extra comments lately, I'll close this issue out.

If you'd like to make a new comment please do open a new issue, thanks!
