### ISSUE TITLE
GraphQL Java + GSON - Handling of ID types

### ISSUE THREAD

**Issue by treverj** [graphql-java/graphql-java#2544]
**Describe the bug**
Even though it has been discussed [here](https://github.com/graphql-java/graphql-java/pull/105) and [here](https://github.com/graphql-java/graphql-java/issues/259) about the use of GSON and the way it converts integers to double by treating them as numbers, and the work arounds to use LenientNumericalScalars, we have come across potentially 2 issues with how GraphQL Java handles them. 

According to the [GraphQL spec](http://spec.graphql.org/June2018/#sec-ID) for id fields, 

> any string (such as "4") or integer (such as 4) input value should be coerced to ID as appropriate for the ID formats a given GraphQL server expects. Any other input value, including float input values (such as 4.0), must raise a query error indicating an incorrect type.

The 2 potential issues I see are:

1. When a Double reaches GraphqlIDCoercing.parseValue, it is converted to a string and accepted rather than being rejected with CoercingParseValueException (whether this is because of GSON or not, it doesn't seem to get stopped before reaching here and will enter the execution as a String ending .0) - This may be me taking the above line from the spec too literally.
2. With how GSON treats integers as Numbers, should the GraphqlIDCoercing class be able to handle integers that have come in as Double due to following how JS and Numbers work. Obviously for custom scalars this can be avoided, but is this something that should be natively handled for IDs. If not, should the docs be updated to include a recommended solution of overriding the default behaviour. 

**To Reproduce**
Pass a value in with a .0 on the end for an ID field as a variable and you will receive a string version of that value but with .0 at the end. If you do the same with an actual double e.g. 3.5, you will get that as a string in the execution.

**Comment by dondonz** [comment]
Hello as this issue is quite old and hasn't received any extra comments lately, I'll close this issue out.

If you'd like to make a new comment please do open a new issue, thanks!
