### ISSUE TITLE
DataFetcherExceptionHandler. onException is both required and deprecated

### ISSUE THREAD

**Issue by softprops** [graphql-java/graphql-java#2545]
In the latest release, at this time 17.2, [DataFetcherExceptionHandler](https://javadoc.io/doc/com.graphql-java/graphql-java/17.2/graphql/execution/DataFetcherExceptionHandler.html)'s method `onException` is deprecated in favor of its async replacement `handleException`. 

It seems you can't implement its replacement still needing to implement onException which leaves new code following the suggestion with a deprecation warning. What's the recommended path to migrating without deprecation warnings?

**Comment by bbakerman** [comment]
> It seems you can't implement its replacement still needing to implement onException which leaves new code following the suggestion with a deprecation warning.

We had 2 choices - make a breaking change without deprecation - 

PRO - its cleaner
CON - its breaks every one

or we could introduce a new method with a default implementation, deprecate the old

PRO - its less clean
CON - its breaks no one

Good Java library evolution does the latter choice.

SPIs (interfaces that so users have to implement) are the hardest to evolve btw

So yes you get an deprecation policy - but not broken.  You should use the new method.  At some future version where do DO remove the old method, less people will be affected

**Comment by rstoyanchev** [comment]
I think there is one more option, for `DataFetcherExceptionHandler` to add a default implementation of `onException`. This would not disrupt existing implementations and would allow migrating to `handleException` and dropping `onException` completely. Otherwise when `onException` is finally removed, it would trigger a wave of changes that can also cause issues.
