### ISSUE TITLE
graphql-java.com /latest redirection minor bug

### ISSUE THREAD

**Issue by sp00m** [graphql-java/graphql-java#2557]
I just noticed https://www.graphql-java.com/documentation/latest/ redirects to https://www.graphql-java.com/documentation/v16/ instead of https://www.graphql-java.com/documentation/v17/.

Pretty minor but worth fixing I guess.

**Comment by dondonz** [comment]
Thanks for reporting!

We've published a new version of the website which fixes the `latest` link.
