### ISSUE TITLE
Co-ercion on Longs does not handle Double / Float inputs

### ISSUE THREAD

**Issue by bbakerman** [graphql-java/graphql-java#259]
public static GraphQLScalarType GraphQLLong = new GraphQLScalarType("Long", "Long type", new Coercing() {
        @Override
        public Object serialize(Object input) {
            if (input instanceof String) {
                return Long.parseLong((String) input);
            } else if (input instanceof Long) {
                return input;
            } else if (input instanceof Integer) {
                return ((Integer) input).longValue();
            } else {
                return null;
            }
        }

If the input to this is a double then it wil nbot try andget the longValue() of it and rather it will set it to null

The reason this is a problem is that JSON input systems like GSON will take String input like

    {
      "serviceDeskId" : 1
    }

and create a Map object like

    "serviceDeskId" -> "1.0"

because numbers in JSON can be doubles.

I think its very unexpected that an input for variables for "x" : 1 actually ends up as null and having to do "x" : "1" is also unexpected

**Comment by dminkovsky** [comment]
Hi @bbakerman, thank you for posting. I see what you're saying. Do you know why GSON does that that conversion? Because of the whole JS `Number` type thing?

I don't think this built-in scalar class should be changed to accommodate this though... I like how the built-ins are simple and do not attempt to perform any lossy conversions. I'll leave this open to see if other people want this feature, but otherwise I think it makes sense to write your own scalar type. It's a small class and then you can control exactly the behavior you desire.

**Comment by bbakerman** [comment]
@dminkovsky - I take your point about it the coercion being lossless as a design goal however I would say that GraphQL seems (to me at least) very much an "approximation" framework that to tend towards "just working " rather than being very precise.  It strikes me as a framework that follows Postels Law : 

    (...) implementations should follow a general principle of robustness: be conservative in what you do, be liberal in what you accept from others.

https://en.wikipedia.org/wiki/Robustness_principle

This StackOverflow question outlines why GSON does what it does

http://stackoverflow.com/questions/15507997/how-to-prevent-gson-from-expressing-integers-as-floats

A specific case could use a type adapter an make all Long looking Doubles into Longs and so on

However the challenge for GrapQL Java is that this approache requires all consumers to strongly know the shape of their internal Schemas.  Some consumers might, but a generic system will not.

Since the "variables" will come in over the wire as JSON then with the current GraphQL API we need to get it to Map<String,Object> some way.  People will trip up on this depending on what framework they use to JSON --> Map.

Anyway thanks for taking the time to consider this issue.  I agree it can go either way.

**Comment by dminkovsky** [comment]
By the way it looks like this is related to #105

**Comment by andimarek** [comment]
Is this still relevant @bbakerman?

**Comment by bbakerman** [comment]
No longer a problem
