### ISSUE TITLE
GraphQLScalarType does not have the constructor the documentation says it does.

### ISSUE THREAD

**Issue by robertkuhar** [graphql-java/graphql-java#2592]
**Describe the bug**

The https://www.graphql-java.com/documentation/v17/scalars/ documentation calls out a constructor that the GraphQLScalarType at 17.3 does not have. Consequently you cannot use the documentation to figure out how to write a custom Scalar in Java.

**To Reproduce**

Lift the code from 2021-10-18's copy of https://www.graphql-java.com/documentation/v17/scalars/, "Writing your Own Custom Scalars".

```
        public static final GraphQLScalarType EMAIL = new GraphQLScalarType("email", "A custom scalar that handles emails", new Coercing() {
            @Override
            public Object serialize(Object dataFetcherResult) {
                return serializeEmail(dataFetcherResult);
            }

            @Override
            public Object parseValue(Object input) {
                return parseEmailFromVariable(input);
            }

            @Override
            public Object parseLiteral(Object input) {
                return parseEmailFromAstLiteral(input);
            }
        });
```

Expected: The code to compile.

Actual: `'GraphQLScalarType(java.lang.String, java.lang.String, graphql.schema.Coercing, java.util.List<graphql.schema.GraphQLDirective>, graphql.language.ScalarTypeDefinition, java.util.List<graphql.language.ScalarTypeExtensionDefinition>, java.lang.String)' has private access in 'graphql.schema.GraphQLScalarType'`

**Comment by sonallux** [comment]
@bbakerman I have created PR graphql-java/graphql-java-page#63 to fix this issue.

**Comment by andimarek** [comment]
the documentation is now fixed.
