### ISSUE TITLE
Hide & handle schema errors (currently inconsistent logging)

### ISSUE THREAD

**Issue by piotrblasiak** [graphql-java/graphql-java#2601]
Currently graphql-java returns schema errors to the client.

1) Is it possible to catch them somehow in order to log them and return something more user friendly/anonymous?

2) Even if it's not possible to hide these errors from the user, it should be possible to log them in order to be able to react to them. I set my log reporting threshold to WARN and that worked for some errors like missing fields, but then I got this error which was not logged:

`The field at path '/setGuestEntries/userDetails[1]/version' was declared as a non null type, but the code involved in retrieving data has wrongly returned a null value. The graphql specification requires that the parent field be set to null, or if that is non nullable that it bubble up null to its parent and so on. The non-nullable type is 'Int' within parent type 'UserDetail'`

**Comment by jbellenger** [comment]
You can do some amount of logging/transformation using an Instrumentation, here's a test case that demonstrates how to do that: 
https://github.com/graphql-java/graphql-java/pull/2520/files#diff-712673c8ad60dc594a5cc619fd4cd1905470cecb8f340a0240e839237532e47bR631

**Comment by kvfedorov** [comment]
> Is it possible to catch them somehow in order to log them and return something more user friendly/anonymous?

If server failed to construct the answer, client won't be able to use it in intended way. So no matter what server will do instead of correct answer, it is responsibility of the client to compensate wrong answer. Besides, it will have to handle connectivity issues even if server will be perfect.

Specifically problem you face is development time problem: you as developer need to provide server implementation which respects schema you declared. Just check resolver code which produce 'version' field and make sure it never returns null and message will do away forever.

**Comment by piotrblasiak** [comment]
> > Is it possible to catch them somehow in order to log them and return something more user friendly/anonymous?
> 
> If server failed to construct the answer, client won't be able to use it in intended way. So no matter what server will do instead of correct answer, it is responsibility of the client to compensate wrong answer. Besides, it will have to handle connectivity issues even if server will be perfect.
> 
> Specifically problem you face is development time problem: you as developer need to provide server implementation which respects schema you declared. Just check resolver code which produce 'version' field and make sure it never returns null and message will do away forever.

It's a good point that the code should not be able to produce an invalid result, but in case it does because of a bug I think I'd prefer just logging it on the server rather than sending it to the client.

**Comment by kvfedorov** [comment]
Are we still talking about missing field? If field is missing and server did not return any error (just logged) how would client know that response is invalid? There could be multiple missing fields, right?

@jbellenger had provided a way to mitigate that. But I would not try to do that in practice and keep resolving such schema forced issues ASAP at development time to respect protocol between client and server. 

Note that runtime problems would still happen and there is exception handler you may want to tune for these.

**Comment by piotrblasiak** [comment]
I think it would be nice to be able to hide all schema errors - but to be honest I've now realised most people don't agree with me that it's needed :)

But I still think that the logging of schema/validation errors should be consistent - either they are WARN:ed or not. So either you have to do instrumentation to log those errors or you don't.

**Comment by bbakerman** [comment]
> I think it would be nice to be able to hide all schema errors

This is not a schema error - this is a case where th API designers declared "this field will ALWAYS have a value" and they then lied - it had no value.  So a client can't make an assumption on the data

> I think it would be nice to be able to hide all schema errors

Can you tell me more on what you would expect the see on the client side for this invariant problem?

Is it because internal details on fields are being listed or is it that there is an error at all?

If it's the latter you could post process the result and remove errors you don't like.  I am not sure that's a good idea in client terms but as an API provider you could make that choice.

**Comment by piotrblasiak** [comment]
In my case I have been only returning error messages are user friendly and can be presented to the end user, something Ive realised may be a bit too strict so I am now handling that in a different way (using the extension "userFriendlyMessage").
But I would still say that an error where a non-null field is null is nothing the client developer can do anything about, and in a way it is leaking information about a bug. The error message could be something a bit less detailed like "Internal server error".

**Comment by piotrblasiak** [comment]
@bbakerman By post-processing, do you mean using instrumentation? I already have a DataFetcherExceptionHandler but that one doesn't catch these errors.

**Comment by bbakerman** [comment]
`graphql.execution.instrumentation.Instrumentation#instrumentExecutionResult` would allow you to change the result before passing it back out of graphql-java OR at the layer above graphql java you could always just change the `graphql.ExecutionResult` itself

**Comment by bbakerman** [comment]
> By post-processing, do you mean using instrumentation
Yes or outside the graphql-java layer - take the ExecutionResult and post
process it
