### ISSUE TITLE
GraphQL Java should use generics where possible

### ISSUE THREAD

**Issue by bbakerman** [graphql-java/graphql-java#261]
DataFetchers today do no use generics.  So you get code like

        public DataFetcher exampleFetcher() {
        return environment -> {
            GraphContext context = (GraphContext) environment.getContext();
            return supplierMethodCall(context);
        };
    }

The ACTUAL return type is Object so its hard to maintain.  But the shape of fetched objects are really important in GraphQL.

Where as

    public DataFetcher<FooObject> exampleFetcher() {
        return environment -> {
            GraphContext context = environment.getContext();
            return supplierMethodCall(context);
        };
    }

Tells a maintainer what they need to know.  It must return a FooObject and hence so must the method call etc..

In fact this could be applied to a number of places in GraphQL Java.   DataFetchingEnvironment is another place where we should do this.  Its neater looking and tells people what they are getting. 

             // where it would be defined as  <T> T getContext();
            GraphContext context = environment.getContext();
            return supplierMethodCall(context);

There are a number of places in GraphQL where one is casting into specific types.  Where that occurs the API should be <T> T defined.

You already do it on DataFetchingEnvironment.getArg

        public <T> T getArgument(String name) {
            return (T) arguments.get(name);
        }

I suggest it is done on the source and context attributes as well.

**Comment by dminkovsky** [comment]
How about this as a start? https://github.com/graphql-java/graphql-java/pull/262

**Comment by dminkovsky** [comment]
Also c.f. https://github.com/graphql-java/graphql-java/pull/91

**Comment by bbakerman** [comment]
fixed
