### ISSUE TITLE
ANTLR grammar doesn't match GraphQL spec for directive locations

### ISSUE THREAD

**Issue by sachindshinde** [graphql-java/graphql-java#2649]
**Describe the bug**

Looking at the [2018 GraphQL spec](https://spec.graphql.org/June2018/#sec-Type-System.Directives), it has for a while allowed for an optional leading `|` in directive locations. E.g., the following is valid GraphQL:
```graphql
directive @foo on
    | OBJECT
    | INTERFACE
```

However, trying to parse this with `graphql-java` throws, because the [ANTLR grammar](https://github.com/graphql-java/graphql-java/blob/master/src/main/antlr/GraphqlSDL.g4#L128) doesn't allow the optional leading `|`.

**To Reproduce**

This code snippet throws:
```java
new SchemaParser().parse("directive @foo on | OBJECT");
```

**Comment by jord1e** [comment]
`graphql-js` does not seem to have test cases describing this. It does have them for unions, weird
