### ISSUE TITLE
Consider making GraphQL-type constructors non-protected, so that languages like Scala/Kotlin can use direct, idiomatic syntax

### ISSUE THREAD

**Issue by GavinRay97** [graphql-java/graphql-java#2677]
I initially tried to write something like this in Kotlin and Scala, but I found that it wasn't possible since the GQL type constructors are `private`:

```kotlin
val queryType = GraphQLObjectType(
  name = "Query",
  fields = listOf(
    GraphQLField(
      name = "sayHello",
      arguments = // ...
    )
  )
)
```

What I've done is manually wrapped every base type to make an easier/more idiomatic API, but it would be nice not to do this since it requires staying in sync with the latest `graphql-java` constructor parameters:

```kt
inline fun objectType(block: GraphQLObjectTypeBuilder.() -> Unit): GraphQLObjectType {
    return GraphQLObjectTypeBuilder().apply(block).build()
}

class GraphQLObjectTypeBuilder {
    var name: String? = null
    var description: String? = null
    var fields: List<GraphQLFieldDefinition>? = null

    fun build(): GraphQLObjectType {
        return GraphQLObjectType
            .newObject()
            .apply {
                if (name != null) name(name)
                if (description != null) description(description)
                if (fields != null) fields(fields)
            }
            .build()
    }
}
```

The reason I am wanting to do this is because I am programmatically building GraphQL schemas from dynamic data sources:
```kt
val queryType = objectType {
    name = "Query"
    fields = schema.tableNames.map { tableName: String ->
        field {
            name = tableName
            type = objectType {
                name = tableName
                fields = table.rowType.fieldList?.map { field: RelDataTypeField ->
                    field {
                        name = field.name
                        type = field.type.toGraphQLType() as GraphQLOutputType
                    }
                }
                arguments = listOf(
                    argument {
                        name = "limit"
                        type = graphql.Scalars.GraphQLInt
                    },
                    argument {
                        name = "offset"
                        type = graphql.Scalars.GraphQLInt
                    },
                    argument {
                        name = "order_by"
                        type = graphql.Scalars.GraphQLString
                    },
                    argument {
                        name = "where"
                        type = inputObjectType {
                            name = tableName + "_bool_exp"
                            fields = table.rowType.fieldList?.map { field: RelDataTypeField ->
                                inputObjectField {
                                    name = field.name
                                    type = field.type.toGraphQLComparisonExprType() as GraphQLInputType
                                }
                            }?.plus(
                                listOf(
                                    inputObjectField {
                                        name = "_and"
                                        type = list(
                                            nonNull(
                                                typeRef(tableName + "_bool_exp")
                                            )
                                        )
                                    },
                                    inputObjectField {
                                        name = "_or"
                                        type = list(nonNull(typeRef(tableName + "_bool_exp")))
                                    },
                                    inputObjectField {
                                        name = "_not"
                                        type = typeRef(tableName + "_bool_exp")
                                    },
                                )
                            )
                        }
                    },
                )
            }
        }
    }
}
```

**Comment by jord1e** [comment]
Why not just use the factory methods? They work fine for your use case and are tested by GraphQL Java. Opening up constructors allows modification of logic by subclassing, which may affect thread-safety or introduce undebuggable errors.

Not everything has to be a DSL.

You can build a proper DSL yourself though, if you *really* want to for this one place in your code: https://www.baeldung.com/kotlin/dsl

**Comment by GavinRay97** [comment]
Because the builder methods are unnecessarily verbose

Yes, they work, but I don't see a reason why someone should be disallowed from using constructors directly in their code if they desire to.

The only thing lack of direct constructor access does is require the user to write a wrapper over the builder methods.

> You can build a proper DSL yourself though, if you really want to for this one place in your code

If you would read my comment, you'll see I've done what you describe -- nearly verbatim

```kt
inline fun objectType(block: GraphQLObjectTypeBuilder.() -> Unit): GraphQLObjectType {
    return GraphQLObjectTypeBuilder().apply(block).build()
}

class GraphQLObjectTypeBuilder {
    var name: String? = null
    var description: String? = null
    var fields: List<GraphQLFieldDefinition>? = null

    fun build(): GraphQLObjectType {
        return GraphQLObjectType
            .newObject()
            .apply {
                if (name != null) name(name)
                if (description != null) description(description)
                if (fields != null) fields(fields)
            }
            .build()
    }
}
```

This is pointless though, the only reason it has to exist is because the constructors are `private`/`protected`

**Comment by jord1e** [comment]
> Yes, they work, but I don't see a reason why someone should be disallowed from using constructors directly in their code if they desire to.
> [...]
> This is pointless though, the only reason it has to exist is because the constructors are private/protected

If I am correct: this is done to protect the implementation details from modification, potentially affecting thread-safety and execution behaviour.

---

Opening up these classes to subclassing may also inhibit adoption of Valhalla value types in the distant (or hopefully, near) future:
https://cr.openjdk.java.net/~jrose/values/values-0.html

> Can a value class be abstract or non-final? No. (Abstract value classes do not presently seem worthwhile.)

> The decision to limit or prohibit subclassing and subtyping of value types is necessary to avoid pointer polymorphism. Abstract super types (like the interface Comparable) are only considered because they cannot be instantiated.

And a more recent preview JEP:
https://openjdk.java.net/jeps/8277163
> A value class declaration is subject to the following restrictions:
>
>    The class is implicitly final, so cannot be extended. The class may not be declared abstract.

**Comment by bbakerman** [comment]
> but I don't see a reason why someone should be disallowed from using constructors directly in their code if they desire to.

Just to give insight on why the constructors are private and the builders are used.

A main reason is to prevent subclassing - we dont want public constructors which allows sub classes.  This locks us in as the constructors being SPI - their shape if fixed forever.   `final` would have been a way to do this but there is more reasons why final classes aren't right/

Another main reason is to allow us to evolve the set of properties a class has.  If the GraphqlObjectType has say 5 properties and later we invent a 6th then with private constructors and builders we can extend the property set without changing the constructor signature.  With this we need to overload YET another constructor method.  This is a Java thing, and I know more modern languages have named parameters and default method parameters.  But its a Java library by design and we work within the bounds of the language.

We won't be opening up the constructors.  As mentioned above if you want Kotlin bindings to make better DSL syntax then you would be better to build your own factory methods.

**Comment by GavinRay97** [comment]
Fair enough, I appreciate the thoughtful reply

Closing =)
