### ISSUE TITLE
Multiple operation error: graphql.execution.UnknownOperationException: Must provide operation name if query contains multiple operations.

### ISSUE THREAD

**Issue by aritgithub** [graphql-java/graphql-java#2701]
Strange error on multiple operation query/mutation:
```
mutation TEST1 {
    TEST1: myResolver(param1: {
        xml: "TEST1"
    }) {
        xml
    }
}

mutation TEST2 {
    TEST2: myResolver(param1: {
        xml: "TEST2"
    }) {
        xml
    }
}
```
Throw this exception:

`
graphql.execution.UnknownOperationException: Must provide operation name if query contains multiple operations.
`

Are the mutation operations not named correctly?

**Comment by jord1e** [comment]
When your operation string (or 'query' as GraphQL Java calls it) contains more then one operation, you must specify the name of the operation which you want to execute.
In fact 'queries' are [Document](https://spec.graphql.org/October2021/#sec-Document)s as defined by the spec.

You can do this by providing the `operationName` whilst constructing your `ExecutionInput`:
https://github.com/graphql-java/graphql-java/blob/f824c01dc8ec6cdcd183bd79b14a6d8652fb5ce1/src/main/java/graphql/ExecutionInput.java#L228

Some documentation over at the [Execution page](https://www.graphql-java.com/documentation/execution) may not be misplaced, I will look into this.

**Comment by aritgithub** [comment]
Reading Documents specs

> _When submitting a Document with multiple operations to a GraphQL service, the name of the desired operation to be executed must also be provided._

this all makes sense.
Thanks for the clarification.
