### ISSUE TITLE
GraphQLEnumType __DirectiveLocation has wrong definition for VARIABLE_DEFINITION value

### ISSUE THREAD

**Issue by arlampin** [graphql-java/graphql-java#2702]
**Describe the bug**
/src/main/java/graphql/introspection/Introspection.java has definition for `__DirectiveLocation` GraphQL enum on [Introspection.java#L424](https://github.com/graphql-java/graphql-java/blob/f824c01dc8ec6cdcd183bd79b14a6d8652fb5ce1/src/main/java/graphql/introspection/Introspection.java#L424). There seems to be a mistake on line 434, where `VARIABLE_DEFINITION` GraphQL enum value is linked to internal `DirectiveLocation.INPUT_FIELD_DEFINITION` Java enum value.

**To Reproduce**
Not sure, I noticed the issue when investigating the code

**Comment by bbakerman** [comment]
Thanks for the bug report and fix
