### ISSUE TITLE
`MultiSourceReader` has breaking behavioural changes when running on Java 16+

### ISSUE THREAD

**Issue by jord1e** [graphql-java/graphql-java#2709]
**Describe the bug**
Because of [`JDK-8241020` "LineNumberReader.getLineNumber() behavior is inconsistent with respect to EOF"](https://bugs.openjdk.java.net/browse/JDK-8241020), the `MultiSourceReader` class behaves incorrectly when running on Java 16+ VMs, even when compiling with Java 8. This causes breaking changes.

The following test cases are failing:
![afbeelding](https://user-images.githubusercontent.com/30464310/151972502-9eb01957-cbdf-4ff7-8c80-14294bbdbb9b.png)

**To Reproduce**

Run the tests on JDK 16, or higher
Same issue occurs when you compile on JDK 8 and run tests on JDK 16+ (see results below)

For ease of testing you may temporarily clone https://github.com/jord1e/graphql-java/tree/ci-improvements and change the versions in `gradle.properties` (or checkout https://github.com/jord1e/graphql-java/commit/a1f4f8455c21a1beb60d38d2baff6dabf93be719)

Results can be downloaded here:
https://github.com/jord1e/graphql-java/actions/runs/1778419182

Found whilst working on #2676 

Can't figure this one out on myself quickly...

**Comment by jord1e** [comment]
.

**Comment by dondonz** [comment]
Fixed by #3670
