### ISSUE TITLE
guava 30 dependency is removed from pom, but not from gradle metadata

### ISSUE THREAD

**Issue by mmorrisontx** [graphql-java/graphql-java#2728]
**Describe the bug**
From what I understand, guava 30 is purposefully being shadowed and relocated into graphql-java. This seems to be reflected properly in the graphql-java pom, which properly does not have a guava dependency. Unfortunately, it is not reflected in the gradle library metadata, where the guava dependency is still present: https://repo1.maven.org/maven2/com/graphql-java/graphql-java/17.3/graphql-java-17.3.module

This means that maven consumers properly do not receive guava 30 through graphql-java, but gradle consumers improperly do receive the gradle 30 dependency.

**Comment by dondonz** [comment]
Hello! Yes that's spot on.

This PR resolved the issue, which was merged into master. It will be included in the next release. https://github.com/graphql-java/graphql-java/pull/2586

**Comment by mmorrisontx** [comment]
If you are interested in restoring gradle metadata in the future, I believe if you use [these instructions](https://imperceptiblethoughts.com/shadow/publishing) (moving 'exposed' dependencies to the `shadow` configuration, the shadowjar plugin will properly manage both the pom and the gradle metadata for you.

**Comment by andimarek** [comment]
This fix is released in 18.0. If you want to have gradle metata please open a new issue. thanks
