### ISSUE TITLE
GraphQL object should use Builder pattern like the schema objects

### ISSUE THREAD

**Issue by bbakerman** [graphql-java/graphql-java#273]
Currently the GraphQL top level object is instantiated via newGraphQL(x,y)

However PRs are already trying to add new capabilities wired into this top level object.  And hence the constructor signature keeps expanding.

A Builder pattern should be used.  eg:  

      GraphQL.newObject(StarWarsSchema.starWarsSchema)
                .executionStrategy(new ExecutorServiceExecutionStrategy(threadPoolExecutor))
                .build()

This would also be consistent with the way schema objects are built etc...which helps consumers avoid "cognitive dissonance" in the API

**Comment by JeffQuandt** [comment]
When is this PR going to be merged into a release? Specifically, the Generics capability included in this change set. For example, the readme shows creating a DataFetcher using a generic. However, the 2.3.0 release has the non-Generic version.

**Comment by aamura** [comment]
I had the same problem than Jeff, README made me happy because I thought that Generic was included in the version but 2.3.0 release doesn't include it.
