### ISSUE TITLE
Deprecation of Apollo Cache Control Specification

### ISSUE THREAD

**Issue by setchy** [graphql-java/graphql-java#2759]
Hi team

Recently, Apollo updated their original [Apollo Cache Control](https://github.com/apollographql/apollo-cache-control) specification with a disclaimer that is has been deprecated/removed from their platforms for some time.

Their alternate approach is in the form of a schema directive `@cacheControl`, with support recently added to federation-jvm v0.8.0 ([release notes](https://github.com/apollographql/federation-jvm/blob/master/RELEASE_NOTES.md#v080))

This issue is to help track either the
- Deprecate the CacheControl implementation within `graphql-java`, or
- Refactor to follow their recommended alternate approach

**Comment by jord1e** [comment]
Wouldn't "Refactor to follow their recommended alternate approach" require graphql-java to include federation-jvm, effectively creating a circular dependency?

**Comment by setchy** [comment]
Sorry should have been clearer.  I didn't mean introduce a cyclic dependency, I more meant moving the schema directive logic from federation-jvm into the base graphql-java package, since its really not federation-centric AND graphql-java had previously implemented their caching specification a few years back

**Comment by andimarek** [comment]
We are planning to deprecate the current one and remote it at one point in the future.
