### ISSUE TITLE
antlr4 v4.10.x is out - any plans to use / adopt to it?

### ISSUE THREAD

**Issue by aamotharald** [graphql-java/graphql-java#2809]
Are there any pland to move to antlr 4.10.x ?
This implies re-generating the scanners, lexers and parsers based on a grammar. 4.9.x (compile-time) and 4.10.x (runtime) does not work.
It's just a technicality to upgrade, but it has to be done in one step.

**Comment by andimarek** [comment]
We don't have specific plans, but we are open for a pull request if you would like to contribute.

Is there a specific reason that you ask? 

Thanks!

**Comment by aamotharald** [comment]
Hi @andimarek ,
there is no specific reason. My project uses the renovate bot that informed us about the new antlr4 version with a PR.
We noticed that we can only move to this version when all other (reuse)libraries that use antlr4 are also on that version. So graphql-java is one of these. It's a bigger coordination effort for us to move to antlr4 v 4.9.x and would have rather expected this to be version 5.x.x . In other words: if I start a contribution for graphql-java a major version bump should be considered to not cause runtime issues by your consumers. I am still not sure how I should deal with this, but I am happy to make a contribution there if the question about the semantiv versioning for graphql-java would be discussed out..

**Comment by dondonz** [comment]
Thanks for raising the issue! We're now shading `antlr-runtime`, which will resolve this version clash problem.
