### ISSUE TITLE
The spec allows for an "extensions" map in the result but graphql-java does not

### ISSUE THREAD

**Issue by bbakerman** [graphql-java/graphql-java#281]
According to spec : http://facebook.github.io/graphql/#sec-Response-Format there can be an extensions field (as a map) in the response

    The response map _may_ also contain an entry with key `extensions`. This entry, if set, must have a   
    map as its value. This entry is reserved for implementors to extend the protocol however they see 
    fit, and hence there are no additional restrictions on its contents.

However the `graphql.ExecutionResult` has only "data" and "errors"

This should be extended so it has "extensions" as a null map.  This means that current clients wont be surprised and ExecutionStrategies would be free to add extension values if they see fit

**Comment by dminkovsky** [comment]
Fixed with #287. Thank you @sean-brandt.
