### ISSUE TITLE
Not consistent Directive lookup

### ISSUE THREAD

**Issue by andimarek** [graphql-java/graphql-java#2810]
In `QueryDirectives` everything returns a list of directives (because repeatable). 
But in `GraphQLDirectiveContainer` we have `getAppliedDirective` which returns just one.

We should make them consistent.

**Comment by andimarek** [comment]
Possible option:
deprecate the current one and introduce a `getUniqueAppliedDirective` for query and schema directives.

**Comment by federicorispo** [comment]
@andimarek I checked and the `GraphQLDirectiveContainer#getAppliedDirective((String directiveName)` method has not yet been deprecated in favor of `GraphQLDirectiveContainer#getUniqueAppliedDirective((String directiveName)`. If you want I can work on it and open a PR

**Comment by dondonz** [comment]
A PR would be very welcome!
