### ISSUE TITLE
Update dependency to java-dataloader

### ISSUE THREAD

**Issue by Lana11s** [graphql-java/graphql-java#2817]
First of all: thanks for the great library!

Are there any plans to release graphql-java with a new version of java-dataloader which contains this fix https://github.com/graphql-java/java-dataloader/pull/113 
That would solve our OSGi issue.

Thanks in advance!

**Comment by bbakerman** [comment]
2 things need to happen - a new release of DataLoader would need to be released and a new version of graphql-java would need to depend on it.

The first is somewhat easy

The second is not likely to happen for quite a few weeks.
