### ISSUE TITLE
Abort execution for transaction handling

### ISSUE THREAD

**Issue by dllx** [graphql-java/graphql-java#282]
I'd like to put the whole GraphQL mutation operation in a database transaction. To that end, I wrap the whole GraphQL.execute method in a transaction.

When a mutation of a toplevel field causes an error, that should roll back the whole transaction. Resolving the rest of the toplevel fields is not desirable in this case, because the transaction may be in an inconsistent/unusable state. Further, as in the case of when using Hibernate, a ConstraintViolationException on the first toplevel field will be reported for the following toplevel fields again.

Mutations are executed by the SimpleExecutionStrategy which inherits from ExecutionStrategy, where the resolveFields method puts an ExceptionWhileDataFetching into the errors list and continues with the next field. The situation is not easily resolvable by using a different ExecutionStrategy because for mutations, SimpleExcecutionStrategy is always used.

Further, other exceptions that don't come from the DataFetcher might also be collected in the error list and execution continues with the next field.

I suggest a configuration possibility to enable aborting the execution when an error occurs, returning an empty (null) data in the ExecutionResult together with the error in the errors list.

**Comment by dminkovsky** [comment]
I am not sure that this would be to spec. I think, and I definitely might
be wrong, but the way execution is specified, mutation fields that error
are null and then execution continues?

**Comment by dllx** [comment]
Yes, I was wondering about the same. I posed a question on stackoverflow to find out more on it, please see http://stackoverflow.com/questions/41238205/graphql-mutation-operation-in-single-transaction.
As the spec says nothing about the side-effects of resolving a top level mutation field, the server could implement the execution/modification of such a field as some sort of no-op if a previous executed top level field had an error.

**Comment by dllx** [comment]
Which leads to the fact that with the current state of graphql-java, this could be implemented by the data fetchers keeping track of the success state in the context Object and react on that accordingly.

That would be a bit awkward as many occurences would have to be adapted, so I still think it would be cleaner when implemented at a more central spot, i.e., the graphql-java library.

**Comment by bbakerman** [comment]
If you really want this then you could provide your own specialisation of "execution strategy" and start your transactions etc.. as you require.

**Comment by corydolphin** [comment]
@bbakerman would it be OK to expose a way for an ExecutionStrategy to simply deal with the exception handling?

**Comment by bbakerman** [comment]
Yeah I think your PR is sensible (not for this issue probably in DB TXN terms) but in a general sense

**Comment by andimarek** [comment]
@bbakerman @corydolphin @dllx Is this issue solved with #387 merged?

**Comment by andimarek** [comment]
solved by #387

**Comment by hank-cp** [comment]
hi @dllx, could you please provide some examples about how to solve this issue with your PR?
