### ISSUE TITLE
The project should better demarcate what is API and what is not

### ISSUE THREAD

**Issue by bbakerman** [graphql-java/graphql-java#284]
Currently it is not crystal clear what is API and what is not.

Clearly top level classes such as GraphQL and ExecutionStrategy are API

But what about `graphql.execution.Execution` or `graphql.execution.ValuesResolver`.  Are they API or implementation detail?

If we had to add new aspects to these classes and changed constructors etc are we breaking consumers?

I suggest that the API be made more clear.  

Annotations are a great way to do this.  The project could have 3 new annotations

@PublicAPI (things you can call and wont change)
@PublicSPI  (things you are meant to implement)
@Internal  (public things that are not API and may change)

This will allow the project to better keep `semver` sematics while evolving as necessary.

**Comment by Jimexist** [comment]
regarding `@Internal` i think putting `internal` in package name is a good practice

**Comment by bbakerman** [comment]
I agree on .internal in the package name as well as .api in the packages however that would be a major breaking change.

Ideally it would be

     graphql.api.AnApiClass

and

    graphql.internal.InternalImplementationClass

the use of annotations are a way to not break current API while better documenting what is API

**Comment by andimarek** [comment]
Because we are planning for a breaking change release I suggest that we use that to try to make it more clear what api vs internal is.

But I think moving everything is not acceptable imho. Breaking stuff should be limited to what we think is really necessary. Annotating seems fine.

**Comment by andimarek** [comment]
I like to idea to add two annotations `@PublicApi` and `@InternalApi` for example.

**Comment by andimarek** [comment]
First shot: #411

**Comment by andimarek** [comment]
we added annotations in #411 ...closing it therefore now: we will add the annotations as we go.
