### ISSUE TITLE
Add both errors and document in PreparsedDocumentEntry 

### ISSUE THREAD

**Issue by zsmoore** [graphql-java/graphql-java#2843]
Hello all,

We are currently trying to patch queries at runtime in our GraphQLEngine.  We do this to make backwards incompatible schema changes compatible by modifying old queries the server receives at runtime.

When looking at implementing this solution we ran into a couple issues.
1 - executing a query internally calls [`ParseAndValidate`](https://github.com/graphql-java/graphql-java/blob/36905f3a9e66c29aa1e6cf8211d9fd173aca5282/src/main/java/graphql/ParseAndValidate.java) so if we want to inspect the errors we would need to have the engine `ParseAndValidate` the raw query in [`ExecutionInput`](https://github.com/graphql-java/graphql-java/blob/36905f3a9e66c29aa1e6cf8211d9fd173aca5282/src/main/java/graphql/ExecutionInput.java) twice
2 - Swapping to leveraging [`PreparsedDocumentProvider`](https://github.com/graphql-java/graphql-java/blob/36905f3a9e66c29aa1e6cf8211d9fd173aca5282/src/main/java/graphql/execution/preparsed/PreparsedDocumentProvider.java) we can intercept the [`PreparsedDocumentEntry`](https://github.com/graphql-java/graphql-java/blob/d783ec7ee30369ca2fdecdfd0b74e8bf6d96baa8/src/main/java/graphql/execution/preparsed/PreparsedDocumentEntry.java) to avoid validation twice however, in cases that have errors `PreparsedDocumentProvider` does not expose the underlying query or document.  This means we need to Parse the execution input using Parse.parse even in this optimized case.

It seems there is no reason the system is not able to handle exposing the `Document` and `ValidationErrors` produced from [`ParseAndValidate`](https://github.com/graphql-java/graphql-java/blob/36905f3a9e66c29aa1e6cf8211d9fd173aca5282/src/main/java/graphql/ParseAndValidate.java) to consumers of [`PreparsedDocumentEntry`](https://github.com/graphql-java/graphql-java/blob/d783ec7ee30369ca2fdecdfd0b74e8bf6d96baa8/src/main/java/graphql/execution/preparsed/PreparsedDocumentEntry.java)

Is there any reason we hide these or would it be possible to change the implementation to expose both?

Thanks!

**Comment by bbakerman** [comment]
Nominally there is no reason why we could not change this.  We have used it as a kinds of `Either` class either you have errors or a valid document.

So for the `parse` step we could ONLY ever have errors or a document but not both.  But for the validation step - it would be possible to get back the document and errors in theory.

**Comment by zsmoore** [comment]
Would you be open to me putting this change up or should we discuss more if its warranted?

**Comment by zsmoore** [comment]
Created https://github.com/graphql-java/graphql-java/pull/2858 for review
