### ISSUE TITLE
Introspection query can't work when object mapper serialization inclusion is set to ignore nulls

### ISSUE THREAD

**Issue by Warestone** [graphql-java/graphql-java#2847]
### Discussed in https://github.com/graphql-java/graphql-java/discussions/2844

<div type='discussions-op-text'>

<sup>Originally posted by **Warestone** June  3, 2022</sup>
Hi everyone!

I set my own object mapper with setSerializationInclusion(JsonInclude.Include.**NON_EMPTY**) for GraphQL, but when im trying to call **IntrospectionQuery** for **GraphiQL** docs Im getting error "Introspection result missing interfaces", because my object mapper ignore nulls. Of course, if I set JsonInclude.Include.**USE_DEFAULTS** it will be ok but I need non_empty globally

So, how can I add exclusion for this? Im trying add mixin to object mapper with graphql.introspection.**Introspection** and my mixIn class which extends last one and set JsonInlude.USE_DEFAULTS but it isn't work

I need to leave Include.NON_EMPTY for global and somehow add exclusion for query IntrospectionQuery graphiql call</div>

**Comment by bbakerman** [comment]
GraphQl will represent ask for fields as `null` by design.

if you ask for 

```
query x {
   foo  {
       bar
   }
}
```

And `bar` was null then you get back

```
{
"data:" { "foo: : { "bar":  null  } } 
}
```

I dont think you can and SHOULD use your Jackson serialization to remove nulls.  Its not the graphql way as you have discovered
