### ISSUE TITLE
ResultPath getParent().getSegmentName() throw cast exception

### ISSUE THREAD

**Issue by xxlv** [graphql-java/graphql-java#2862]
**Describe the bug**
ResultPath  -> getParent().getSegmentName()
may throw Cast class Execption
because segement maybe `int` ,but getSegmentName use `(String)segment` 

**To Reproduce**

See `ResultPath.getSegmentName()` method

**Comment by bbakerman** [comment]
We this bug in an existing code path or something you hand crafted.  I can see a potential problem but I am trying to better understand how you came to this problem

**Comment by xxlv** [comment]
> We this bug in an existing code path or something you hand crafted. I can see a potential problem but I am trying to better understand how you came to this problem

aha, just a potential problem.


Background :

I need to get segment name as key for my business logic. so i use `getSegmentName()`.

Now  i use `isNamedSegment()` before invoke `getSegmentName()` and works fine .
