### ISSUE TITLE
Version 2.3.0 not on maven.

### ISSUE THREAD

**Issue by oexza** [graphql-java/graphql-java#288]
The title says it. 2.3.0 is not on maven https://mvnrepository.com/artifact/com.graphql-java/graphql-java

**Comment by dminkovsky** [comment]
Will be released soon.

пт, 23 дек. 2016 г. в 14:25, Peace Michaels <notifications@github.com>:

**Comment by dminkovsky** [comment]
(thanks for opening the issue)

пт, 23 дек. 2016 г. в 16:14, Dmitry Minkovsky <dminkovsky@gmail.com>:

**Comment by dminkovsky** [comment]
Looks like the artifact is up on central now. Thanks again.
