### ISSUE TITLE
Spring Boot support of GraphQL in java

### ISSUE THREAD

**Issue by shishuwu** [graphql-java/graphql-java#289]
Actually, this is not a issue but a request.

There is a [graphql boot project](https://github.com/oembedler/graphql-spring-boot) in github, but seems it is not maintained/documented for a long time, it also integrates graphiql and relay. 

So could you **take over** it into this project, if so that would be great. thanks

**Comment by timtebeek** [comment]
Spring Boot support should not be too difficult to add I suppose; I've done so for `graphql-jpa` here: https://github.com/timtebeek/graphql-jpa-spring-boot-starter/tree/master/src/main/java/com/github/timtebeek/graphql/jpa
That's a different project that uses graphql-java to deduce a schema from jpa, but that just means `graphql-java` would need even less to setup.

**Comment by dminkovsky** [comment]
Thank you @timtebeek and @shishuwu for reporting.

**Comment by dminkovsky** [comment]
Also https://github.com/Distelli/graphql-apigen

**Comment by andimarek** [comment]
As suggested we brought the mentioned project into the org: https://github.com/graphql-java/graphql-spring-boot
