### ISSUE TITLE
What's the suggested way to do authorization per field?

### ISSUE THREAD

**Issue by lulzmachine** [graphql-java/graphql-java#290]
Hello!

I've started using this library recently and am trying to do some kind of authorization on field-level. Basically what we want to do is to say that some users can see "book.author.id" and some users can't. We would also like to have this be as flexible, generalized and decoupled as possible. We want to have this as a framework-component, so it shouldn't matter what underlying data storage is used. To get started with something, we'll just have a simple blacklist to check from. I've been searching around quite a lot, but haven't found any nice, clean solutions. From what I've gathered there are basically three points where this could be done:

1. By altering the incoming queries to not query for the blacklisted fields
2. By checking inside each DataFetcher
3. By altering the output data

Solution number 3 is suboptimal, since that would change the data after it's already been queried from the database. Also it might be possible to circumvent with aliases or subqueries or something (?)

Solution number 2 might be suitable. But so far the datafetchers seem quite complex, and it seems hard to do a catch-all solution. However, the graphql project does suggest something quite similar: http://graphql.org/learn/authorization/

I've tried to put something like this in a DataFetcher, and it seems to do the trick:
```java
            // find what fields the user tried to select
            Field field1 = environment.getFields().get(0);
            List<Selection> selections = field1.getSelectionSet().getSelections();

            // convert into LinkedHashMap, field-by-field (while checking permissions)
            for (Selection selection : selections) {
                Field selectionField = (Field) selection;
                // only works for fields 1 deep. todo: some kind of search? or is there a way to find parent

                String fieldName = parentType.getName() + "." + environment.getFieldType().getName() + "." + selectionField.getName();
                boolean isBlacklisted = blacklist.getOrDefault(fieldName, false);
                if (isBlacklisted) {
                    continue;
                }

                try {
                    // invoke the getter for this property
                    Object value = new PropertyDescriptor(selectionField.getName(), StarWarsData.AuthorDb.class).getReadMethod().invoke(myAuthor);
                    obj.put(selectionField.getName(), value);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
            return obj
```

However, if we want this as a general framework component, it's a bit unclear how we can combine this with whatever DataFetcher the user wants to have. Probably we'd have to wrap all our DataFetchers in a wrapper class.

For solution 1, the goal is to alter the incoming queries to remove certain fields from the selections. I noticed that there aren't any comfortable hooks to do this with the GraphQL object, so we had to pretty much copy the whole GraphQL.execute() method:
```java
    public static ExecutionResult ourExecution(String requestString, Object context, GraphQLSchema schema) {
        // this is basically copied from GraphQL.java
        Parser p = new Parser();
        Document document = p.parseDocument(requestString);
        CleanDocument(document, context);

        Validator validator = new Validator();
        List<ValidationError> validationErrors = validator.validateDocument(schema, document);
        ExecutionResult exresult = null;
        if (validationErrors.size() > 0) {
            exresult = new ExecutionResultImpl(validationErrors);
        }
        Execution execution = new Execution(null, null);
        String operationName = null;
        Map<String, Object> arguments = Collections.<String, Object>emptyMap();
        exresult = execution.execute(schema, context, document, operationName, arguments);
        return exresult;
    }
```
Where our cleaning method "CleanDocument" would go through and clean the incoming queries. We could also put a "CleanResult" after the execution, just to make sure (and maybe do some assertions to make sure users really care about the incoming SelectionSets).

Right now it seems best to have a combination of solution 1 and 3. However, we are quite unsure if this solution will be sustainable. And whether the classes we use here are considered public api or internals.

So do you as library authors have any suggestions? Anything we've overlooked/misunderstood/etc?

**Comment by dminkovsky** [comment]
> Probably we'd have to wrap all our DataFetchers in a wrapper class.

That's what I do. Whether you wrap or extend, I've not had problems with this approach. Check whether the field is allowed execution, and then execute or not. 

```
abstract class AuthorizedDataFetcher extends DataFetcher {

  @Override
  public Object get(DataFetchingEnvironment env) {
    if (isAllowed(env)) {
      return fetch(env);
    }
    // otherwise throw or return null;
  }

  // perform actual data resolution
  public abstract fetch(DataFetchingEnvironment);

}
```

You can clean the document too, but then you don't get `null` fields and errors for unauthorized fields, just the execution results you want allowed. 

With regard to hooks, we are considering changing the API to facilitate this (#269) (@bbakerman)

**Comment by oexza** [comment]
in our case, field result filtering/authorization is done at the
service layer(which is the single source of truth) such that if we
were to build a rest api atop it, it would still work seamlessly.
DataFetchers should be kept as slim as possible.

**Comment by bbakerman** [comment]
I would have to agree with @oexza here.  The authorisation is best done in your "service layer" so that given a user it comes back with "null fields" if they are not allowed to see it or not.

Then your data fetchers can be as thin as possible.

This will also allow better "testing" since the service layer can be unit tested outside the GraphQL "fetch" code

**Comment by dminkovsky** [comment]
Indeed, @oexza and @bbakerman's responses represent what the GraphQL authors suggest, too: http://graphql.org/learn/authorization/

**Comment by lulzmachine** [comment]
Okay. Thanks for the input! It's been very helpful! Closing the issue now, I hope that's okay

**Comment by dminkovsky** [comment]
@oexza  @bbakerman I added a service layer to my application (gRPC), and indeed: having a service layer and thin fetchers is quite nice!
