### ISSUE TITLE
allow Coercing.parseLiteral to return null (remove @NonNull annotation)

### ISSUE THREAD

**Issue by sgerke-1L** [graphql-java/graphql-java#2904]
[Coercing.parseLiteral](https://github.com/graphql-java/graphql-java/blob/3139ccbb8a2313704518f39150223bda550d0500/src/main/java/graphql/schema/Coercing.java#L77) is declared to return a `@NonNull` value.

However, a coercing may want to return `null` for the NullValue. See for example the [ObjectScalar](https://github.com/graphql-java/graphql-java-extended-scalars/blob/313b22114516b203342b7c7d5b7a0e1879cc2ad4/src/main/java/graphql/scalars/object/ObjectScalar.java#L69) implementation in https://github.com/graphql-java/graphql-java-extended-scalars

**Comment by bbakerman** [comment]
Hmm this is an intersting one - on the one hand the code is like that to say

* always return a value
* Most of the time there should be a value
* throw  `CoercingParseLiteralException` if there is a problem in the conversion

I guess that the AST `NullValue` is mostly like going to result in a scalr saying its raw value for that is null

**Comment by sgerke-1L** [comment]
I found this previous discussion: https://github.com/graphql-java/graphql-java/issues/1362
Somehow the @NonNull was removed from serialize but not from parseLiteral.

**Comment by bbakerman** [comment]
This has been fixed

**Comment by sgerke-1L** [comment]
Thanks for addressing this with #2912

**Comment by andimarek** [comment]
sorry to open

**Comment by andimarek** [comment]
@sgerke-1L can you explain why you would want to return `null` for not null literal value? thanks

**Comment by sgerke-1L** [comment]
Motivation was the handling of `NullValue` in ObjectScalar. The null return was causing problems with spotbugs validation.

**Comment by sgerke-1L** [comment]
Is it easy to see that NullValue is never passed?

**Comment by andimarek** [comment]
Not sure what you mean with easy: if you look into the GraphQL Java source code you can find it.

It should be clearly documented I would say.

**Comment by dondonz** [comment]
On the follow up discussion - the `NullValue` case in `ObjectScalar`'s `parseLiteral` implementation has been removed, as a `NullValue` literal input will coerced as null & returned before the scalar's `parseLiteral` method is called. Added more documentation to make this clearer inside `Coercing`.

**Comment by sgerke-1L** [comment]
Thanks, this solves our problem: The inconsistency now resolved.
