### ISSUE TITLE
documentation on field visibility describes a deprecated path

### ISSUE THREAD

**Issue by softprops** [graphql-java/graphql-java#2914]
the documentation on [field visibility ](https://www.graphql-java.com/documentation/field-visibility) suggests users use

```java
GraphQLSchema schema = GraphQLSchema.newSchema()
        .query(StarWarsSchema.queryType)
        .fieldVisibility(blockedFields)
        .build();
```

which is deprecated

<img width="1113" alt="Screen Shot 2022-08-05 at 6 26 30 PM" src="https://user-images.githubusercontent.com/2242/183219442-ae37f63b-7336-43bf-a31d-a72395ed251f.png">

I was able to get this working the the replacement with something that looked this

```java
var schema = GraphQLSchema.newSchema()
        .query(StarWarsSchema.queryType)
        .build();
 var limitedSchema = schema
      .transform(schemaBuilder ->
         schemaBuilder.codeRegistry(
           schema.getCodeRegistry()
               .transform(codeRegistryBuilder -> codeRegistryBuilder.fieldVisibility(blockedFields)));
```

**Comment by dondonz** [comment]
Thanks @softprops , good catch! This has been fixed
