### ISSUE TITLE
Renamed scalar still present in the schema if used as directive argument

### ISSUE THREAD

**Issue by dariuszkuc** [graphql-java/graphql-java#2933]
**Describe the bug**
When custom scalar is used as a directive argument, old scalar name is still present in the schema after rename.

In the example below both `Query.field` return type and `myDirective` argument are updated to the `Bar` type but the schema contains entries for both original `Foo` and renamed `Bar`.

**To Reproduce**
Modify current scalar rename test to include directive (https://github.com/graphql-java/graphql-java/pull/2928)

```graphql
scalar Foo
directive @myDirective(foo: Foo) on FIELD_DEFINITION
type Query {
  field: Foo @myDirective
}
```

See: https://github.com/dariuszkuc/graphql-java/commit/6005e8e632fcc5c032203fbb0a54d86e399d2fce

It looks like the original `Foo` is only added if the directive is applied, i.e. if we update `field: Foo @myDirective` to `field: Foo` we won't have the old type in the schema. Might be an issue with applied directives.

**Comment by bbakerman** [comment]
Thanks for reporting.  I have created a reproduction test and can confirm it does not remove the old type if it used in applied schemas

**Comment by bbakerman** [comment]
I can confirm that the old directive mechanism works (the type gets replaced) however the applied directive does not

**Comment by andimarek** [comment]
We found the bug and fixed it ... see #2934
