### ISSUE TITLE
Slack Org?

### ISSUE THREAD

**Issue by kreed-rmn** [graphql-java/graphql-java#294]
Heya, 

I'm part of a team at RetailMeNot that is building a service using this library. We'd love to contribute back to it both in PRs and design direction. In order to speed that process up, is there an existing [Slack](https://slack.com/) organization we could use to communicate? If not, can we create one and reference it as a part of documentation?

Thanks,
Kasey

**Comment by dminkovsky** [comment]
Hi @kreed-rmn. What about Gitter: https://gitter.im/graphql-java/graphql-java ?

**Comment by kreed-rmn** [comment]
@dminkovsky That'll work! Thanks!
