### ISSUE TITLE
Cannot resolve method GraphQL.newObject(GraphQLSchema)  in 2.3.0

### ISSUE THREAD

**Issue by darrinps** [graphql-java/graphql-java#295]
Trying the same Hello World after latest update and Android Studio is complaining about not finding the newObject().

Code is as follows:

import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;

import java.util.Map;

import graphql.GraphQL;
import graphql.schema.GraphQLObjectType;
import graphql.schema.GraphQLSchema;

import static graphql.Scalars.GraphQLString;
import static graphql.schema.GraphQLFieldDefinition.newFieldDefinition;
import static graphql.schema.GraphQLObjectType.newObject;

public class MainActivity extends AppCompatActivity
{

    @Override
    protected void onCreate(Bundle savedInstanceState)
    {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        example();
    }

    private void example()
    {
        GraphQLObjectType queryType = newObject()
                .name("helloWorldQuery")
                .field(newFieldDefinition()
                        .type(GraphQLString)
                        .name("hello")
                        .staticValue("world"))
                .build();

        GraphQLSchema schema = GraphQLSchema.newSchema()
                .query(queryType)
                .build();

        GraphQL graphQL = GraphQL.newObject(schema).build();

        Map<String, Object> result = (Map<String, Object>) graphQL.execute("{hello}").getData();

        System.out.println(result);
        // Prints: {hello=world}
    }
}

**Comment by dminkovsky** [comment]
Sorry that's a typo in the readme. Try GraphQL.newGraphQL().
ср, 11 янв. 2017 г. в 21:16, Darrin <notifications@github.com>:

**Comment by darrinps** [comment]
Didn't help. Looks like it can't find anything other than class for GraphQL. No methods at all associated with it from what I am seeing.

**Comment by dminkovsky** [comment]
Oh sorry you're on the 2.3.0 released artifact.

The readme is for master, which isn't released yet.

Have a look at the readme on a tagged release.

ср, 11 янв. 2017 г. в 21:26, Darrin <notifications@github.com>:

**Comment by darrinps** [comment]
Thanks.

Will it be long before that is released? I may wait if it's just a few days or so.

Also, do you know if there is an example of how to hit an endpoint? I see it set up for Star Wars for example, but don't see how to set the execute of the Graph object to hit a specific endpoint. So, if I am running that Star Wars instance at localhost://8080 is there an example somewhere of how to configure the execute to hit that point?

**Comment by darrinps** [comment]
That works fine by the way. Changes it to:

 GraphQLSchema schema = GraphQLSchema.newSchema()
                .query(queryType)
                .build();

**Comment by dminkovsky** [comment]
> Will it be long before that is released? I may wait if it's just a few days or so.

Not sure when the next release will be. Probably within the next month? 2.3.0 is fine for now, I think.

> Also, do you know if there is an example of how to hit an endpoint? 

I'm not sure what you mean by hitting an endpoint. Those examples predate me and I didn't grok all of them. But it sounds like you got query execution going.

**Comment by dminkovsky** [comment]
Whoops didn't meant to close.

**Comment by dminkovsky** [comment]
But actually I think it makes sense to close this. Please post if you have another question or check out the [Gitter channel](https://gitter.im/graphql-java/graphql-java) or [mailing list](https://groups.google.com/forum/#!forum/graphql-java).
