### ISSUE TITLE
antlr4 upgrade >= 4.10.x - plans

### ISSUE THREAD

**Issue by aamotharald** [graphql-java/graphql-java#2965]
Hi colleagues,

I noticed that this project uses antlr4 in version 4.9.3. See https://github.com/graphql-java/graphql-java/blob/master/build.gradle#L54 .
I would like to move up to4.11.x, but I noticed that antlr4 has runtime issues with regards to downwards-compatibility check https://github.com/antlr/antlr4/releases/tag/4.10 .

So if you upgrade, I would advise to make a minor version release. I am happy to make a contribution to an upgrade, but wanted to know what your project thinks about this circumstance.

**Comment by dondonz** [comment]
Hi @aamotharald, is there a particular reason for upgrading to 4.11? Is there a new feature you're interested in or something else?

**Comment by andimarek** [comment]
FYI: antlr is purely internally used. A user of GraphQL Java should never come in contact with it directly.

**Comment by aamotharald** [comment]
My use case is:
I have a project that uses antlr4 (some grammar for somne use case) in version 4.11.x .
This project also wants to use graphql-java (with antlr4 version 4.9.3).
As only one version of the lib can be consumed, the dependency management (maven/gradle,..) will use 4.11.x .
This will lead to a runtime issue in graphql-java.
So for now the only solution is to downgrade the project to antlr 4.9.x to be able to consume graphql-java without runtime issues. 
This is fine until a security vulnerability gets detected in 4.9.x that has been stuffed in 4.11.x or later (theoretical use case). Then the option will be to stop using graohql-java or wait for the upgrade adoption.
But I see the hassle with this antlr4 >= 4.10.x adoption which I am also not too happy about.

**Comment by dondonz** [comment]
In that case, we actually shade in `antlr4-runtime`, so there won't actually be a dependency clash.

We started shading in the dependency after receiving feedback that it was a blocker.

**Comment by andimarek** [comment]
Starting with 19.0 antlr is no longer a direct dependency as it is sharded. This should solve your dependency conflict. Cc @dondonz

**Comment by aamotharald** [comment]
Hi @andimarek @dondonz ,
I was not aware of the shading solution approach. That sounds like a good solution to me.
Thanks for the update here!
I'll ry that out.
