### ISSUE TITLE
Base64 padding compatibility with NodeJS toGlobalId

### ISSUE THREAD

**Issue by deweyjose** [graphql-java/graphql-java#2966]
Hi all,

We're currently migrating away from some of our NodeJS based infrastructure that produces Relay Global IDs to Java based. The NodeJS [graphql-relay library](https://github.com/graphql/graphql-relay-js/blob/main/src/utils/base64.ts) produces padded IDs while the Relay.java code explicitly calls for a nonPadded encoder. For now we're going to write our own to/from GlobalId methods because we need compatibility for this effort but would rather use the Relay class instead.

Any thoughts on making this configurable? 

https://github.com/graphql-java/graphql-java/blob/113db6b09097f64383bfc9a9d5c745b011774e81/src/main/java/graphql/relay/Relay.java#L241

**Comment by dondonz** [comment]
Hello, I asked the team. This Relay class hasn't received much attention, with the last update 7+ years ago. Originally it was more of a demonstration and we may deprecate this class in the future.

We'd recommend you create your own Relay class and then you can adjust the ID methods as you like.
