### ISSUE TITLE
[Feature Request] Add support for Java record types to PropertyDataFetcher

### ISSUE THREAD

**Issue by jvdsandt** [graphql-java/graphql-java#2991]
Java record types have private fields and public getter methods for these fields. But these getter methods don't have a "get" prefix. Currently the implementation of PropertyFetchingImpl.getPropertyViaGetterMethod does not find these getter methods so Java record types cannot be used as a source.

Can support for Java record type getters be added to PropertyFetchingImpl.getPropertyViaGetterMethod ?

**Comment by bbakerman** [comment]
I concur - we should have this.  The trick will be

* how do we know its a record?
* we run on Java 8 - how can code on Java 8 know its a record
* is it just naming?

But in general, problems aside, we should have this!

**Comment by jord1e** [comment]
I already implemented this, it was closed

https://github.com/graphql-java/graphql-java/pull/2793

The PR to add testing support for this has been open for a while:

https://github.com/graphql-java/graphql-java/pull/2789

**Comment by bbakerman** [comment]
Yeah we havent invested time in your multi JVM approach.

As for your fix - I kinda like it better than mine but mine allows for non Record based naming as well

```
public class Batman {
   public String name() {
     return "batman";
  }
}
```
as well as records

```
public record Batman(String name) {}
```
