### ISSUE TITLE
[Feature request] parameters for introspection queries

### ISSUE THREAD

**Issue by MayCXC** [graphql-java/graphql-java#2995]
I have a fork https://github.com/graphql-java/graphql-java/pull/2993 that adds a method to IntrospectionQuery.java to generate introspection queries that include deprecated input fields and other options, as well as adjusting the `specifiedByURL` field capitalization to match the graphql spec. This is useful for graphql clients that use graphql-java to do schema introspection, as well as graphql servers who wish to support `specifiedByURL`.

**Comment by dondonz** [comment]
Thanks! Merged in #2993
