### ISSUE TITLE
Update SLF4J

### ISSUE THREAD

**Issue by ersimont** [graphql-java/graphql-java#300]
I recommend updating the SLF4J dependency. It is currently at `1.7.12` (from March 2015).  The most recent is `1.7.22`.  I bring this up because I ran into an error running GraphQL-Java on Google App Engine, and found the solution [here](http://stackoverflow.com/a/33637960/1836506).

I added `slf4j-api` in my own dependencies at the most recent version, which resolved the issue, but it would be nice for future users not to have to hunt down this bug themselves (nor any other bugs that have been fixed in more recent releases)!

**Comment by andimarek** [comment]
@ersimont Could you create a PR for that? That would be great ... thanks!

**Comment by ersimont** [comment]
I'm hesitant because I don't have a build setup for this project, and I also don't use Gradle. I assume it's just bumping the version number in `build.gradle`, and that's it?  If so, I could make the PR, but it would probably be faster for a project member to do it themselves than to verify that I did it correctly...

**Comment by dminkovsky** [comment]
Makes sense. I'll bump the version. Thanks for reporting!


вс, 15 янв. 2017 г. в 0:06, ersimont <notifications@github.com>:

**Comment by bbakerman** [comment]
This should be able to be closed soon
