### ISSUE TITLE
Minor optimization for `ValidationError#toString()`

### ISSUE THREAD

**Issue by dugenkui03** [graphql-java/graphql-java#3005]
https://github.com/graphql-java/graphql-java/blob/13ab0009bd42b591bb4a542cd9c780a53515321d/src/main/java/graphql/validation/ValidationError.java#L24

In `ValidationError`, It seems that `extensions` should be print in `toString()`.

**Comment by federicorispo** [comment]
Hi,
I made a [quick commit](https://github.com/federicorispo/graphql-java/commit/daa68847b9b0f28d0a48b5619a5a7d3d5d785324) to add this optimization. However, if the value of an extension is an object which does not have the `toString()` method overridden then `org.example.ClassName@4ea5b703` will be printed.

If you like the solution I can open PR asap.

There are a couple of things I notice in the `ValidationError` class:
1. The `message` field is always initialized with the `description`. A solution could be to delete the `message` fields and the `getMessage()` method could return the description field
2. The `location` field is initialized inline but the `extensions` and the `queryPath` are not. Could we uniformized the three fields? Initialize them will avoid NullPointerException and they would allow to remove the nullability check I made [here](https://github.com/federicorispo/graphql-java/commit/daa68847b9b0f28d0a48b5619a5a7d3d5d785324#diff-ed80e58cf538f2b65aff944e7e6e8d7c32369e5a73e83d11265005393a959a58R120)

I can fix one or both these two points in the same branch if you like

**Comment by bbakerman** [comment]
By all means submit  it - however

```
Optional.ofNullable(extensions).isPresent()
```

just use `extensions != null` - there is no need for an object instantiation (Optional) in order to work if its null or not

**Comment by federicorispo** [comment]
> By all means submit it - however

Perfect! Next time I will open the PR without asking (some project maintainer can be very picky about the flow to follow :rofl: 

> there is no need for an object instantiation

You are right!

About the other two points? Do I create a new issue and a new PR or do I always use this one?

**Comment by dondonz** [comment]
@federicorispo feel free to open a PR and reference this issue. No need to create a new issue
