### ISSUE TITLE
TypeDefinitionRegistry.types is One hundred thousand.

### ISSUE THREAD

**Issue by Scorpiord** [graphql-java/graphql-java#3007]
When the size of the TypeDefinitionRegistry.types is One hundred thousand, The graphql.schema.idl.SchemaTypeChecker#checkTypeRegistry will run 10 minutes.
The checkTypeRegistry method will be optimized?

**Comment by bbakerman** [comment]
What's you use case for having a graphql schema with 100,000 types in it.  

* One type per customer?
* Auto generated in some way?

Even if we could make checkTypeRegistry 50% faster but 5 minutes is too long right

**Comment by bbakerman** [comment]
No follow up - closing this issue
