### ISSUE TITLE
Kotlin isX properties access

### ISSUE THREAD

**Issue by turboezh** [graphql-java/graphql-java#3010]
Related: #130, #2991, #2994.

**Describe the bug**

If some boolean GraphQL field named `isX` and backed by DTO isX() getter, `PropertyFetchingImpl` fails to find such a getter.
Instead it tries `isIsX()`.

**Why (boolean) getter named so?**

The problem is related to Kotlin properties:

> If the name of the property starts with `is`, a different name mapping rule is used: the name of the getter will be the same as the property name... This rule applies for properties of any type, not just `Boolean`.

https://kotlinlang.org/docs/java-to-kotlin-interop.html#properties

**How to fix**

Property fetcher should not add `is` prefix if a field already prefixed with it.
Or more general way: it should try getter without a prefix at all (getter name == field name) as a last resort.

**To Reproduce**

Schema:
```graphql
type TheType {
    isAwesome: Boolean
}
```

Kotlin:
```kotlin
/**
 * DTO
 */
class TheType(
    val isAwesome: Boolean?
)
```

Java:
```java
/**
 * DTO
 */
public class TheType {
    private Boolean isAwesome;

    public TheType(Boolean isAwesome) {
        this.isAwesome = isAwesome;
    }

    public Boolean isAwesome() {
        return isAwesome;
    }
}
```

**Comment by bbakerman** [comment]
This might be fixed by the `record` like property fetching that went in recently.  Nominally it was for Java records but it might work here.

https://github.com/graphql-java/graphql-java/pull/2994

It allows first uses the direct name of a property of its present.  I think this will work for Kotlin


```
public record JavaRecord(Boolean isAwsome()
```

creates `isAwesome()` as a getter

Can you try and confirm this?

**Comment by turboezh** [comment]
Hi, @bbakerman.

I've made some tests: https://github.com/turboezh/graphql-java/pull/1/files.

At `PropertyDataFetcher` level it seems to work correctly. But.

I also add tests to the `LambdaFetchingSupport` and it fails with `get`/`is`-prefixed names.
I think there is some conflict with "record properties" algorithm and `get`/`is` prefixes.
Look at this test please: https://github.com/turboezh/graphql-java/pull/1/files#diff-335d1791aad84b00e8762546a158726200525fa06a55b73d8284ff0fea4ac7deR54

For example, `issues` is an eligible property name, but it will fail.

Here
https://github.com/graphql-java/graphql-java/pull/2994/files#diff-551e16520d229eecfb4b850a0112704fb00e52c27c207efb5d567d9372113d79R112
in `nameMatches` method, `mkPropertyName` will strip `is` so `sues` method will not be found in a class.

**Comment by bbakerman** [comment]
Thanks you - we will take a look
