### ISSUE TITLE
getPropertyViaFieldAccess ignoring superclass fields

### ISSUE THREAD

**Issue by AlexanderPraegla** [graphql-java/graphql-java#3019]
**Describe the bug**
When an abstract class with Lomboks fluent accesssors is defined, `graphql.schema.PropertyFetchingImpl#getPropertyViaFieldAccess` will not find the field because it does not check the superclass like e.g. `graphql.schema.PropertyFetchingImpl#findPubliclyAccessibleMethod`. This results in a null value in the query response for data that is acutally available.

**To Reproduce**
Use this schema:

```
type Query {
    movies: [Movie]
}

interface Movie {
    title: String
}

type ScaryMovie implements Movie {
    title: String
    gory: Boolean
    scareFactor: Int
}

type ActionMovie implements Movie {
    title: String
    nrOfExplosions: Int
}
```
Implement the classes like this:

```
@Data
@NoArgsConstructor
@AllArgsConstructor
@Accessors(fluent = true)
public abstract class Movie {
    private String title;

}

@Data
@Accessors(fluent = true)
public class ActionMovie extends Movie {
    private int nrOfExplosions;

    public ActionMovie(final String title, int nrOfExplosions) {
        super(title);
        this.nrOfExplosions = nrOfExplosions;
    }
}

@Data
@Accessors(fluent = true)
public class ScaryMovie extends Movie {
    private boolean gory;
    private int scareFactor;

    public ScaryMovie(final String title, final boolean gory, final int scareFactor) {
        super(title);
        this.gory = gory;
        this.scareFactor = scareFactor;
    }

}
```
I created a simple project to demonstrate this: https://github.com/AlexanderPraegla/graphql-java-lombok-fluent-accessor

**Comment by bbakerman** [comment]
we have a PR that will go out in graphql-java 20

https://github.com/graphql-java/graphql-java/pull/2994

This will find methods that are "record like"

I ran up you example code locally and your classes become

input :

```
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;
import lombok.experimental.SuperBuilder;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Accessors(fluent = true)
@SuperBuilder
public abstract class Movie {
    private String title;

}
```

generated code

```
public abstract class Movie {
    private String title;

    protected Movie(MovieBuilder<?, ?> b) {
        this.title = b.title;
    }

    public String title() {
        return this.title;
    }

    public Movie title(String title) {
        this.title = title;
        return this;
    }
    
```

That is Lombok generated accessors with the annotations as provided is making a `title()` method

The PR I mentioned now has "record like" access such that a graphql field named `title` will look for a `title()` method to get access.

So in a sense your problem will fix itself without needing to do super class java field access.

Does this makes sense to you

**Comment by bbakerman** [comment]
I ran you Lombok code (copied) and this bit of snippet code with the proposed code from the future PR

```

        PropertyDataFetcher<Object> titleDF = PropertyDataFetcher.fetching("title");

        Object source = new ScaryMovie("titleVal",true,100);
        DataFetchingEnvironment dfe = DataFetchingEnvironmentImpl.newDataFetchingEnvironment().fieldType(Scalars.GraphQLString)
                .source(source).build();

        Object titleValue = titleDF.get(dfe);
        Assert.assertTrue( titleValue.equals("titleVal"));
        
```

And it worked as expected because of the record like accessors

**Comment by AlexanderPraegla** [comment]
That's great news. Thank you for the quick replay. When do you think graphql-java 20 will be released?

**Comment by bbakerman** [comment]
before Xmas

**Comment by dondonz** [comment]
Closing issue as record-like accessors were included in v20 release
