### ISSUE TITLE
Parse queryString with the document, which is the AST.

### ISSUE THREAD

**Issue by derek2009** [graphql-java/graphql-java#302]
Since we can do parseDocument() with the queryString, can we do parseQueryString() with the document, which is the AST?

I tried it but turned out that it didn't work. However, parseQueryString() is extremely important when it comes to the two-way parse. I hope you can help me. Thanks.

**Comment by dminkovsky** [comment]
parseDocument() parses GraphQL documents, which may include queries,
fragments and schema definitions.

What are you trying to parse? What errors are you receiving?

**Comment by derek2009** [comment]
Sorry for my misdescribing. For parseDocument(), consider this infomation flow: String input -> Document document. So can we do a parseQueryString() for the information flow that is from Document document -> String input?  

In this case, we can do some operations between queries & fragments, such as appending a fragment into a query in runtime. Apperantly we can do this appending operation with a Document instance which is parsed from the String query. However, how can we get the updated String query from its updated Document instance? This is my problem.

**Comment by dminkovsky** [comment]
> for the information flow that is from Document document -> String input?

Oh do you mean like: https://github.com/graphql-java/graphql-java/issues/126
?


вт, 17 янв. 2017 г. в 0:05, Huixiao Huang <notifications@github.com>:

**Comment by derek2009** [comment]
Yes! Gorgeous! Thank you.
