### ISSUE TITLE
Can GraphQLArgument.Builder#defaultValue be undeprecated?

### ISSUE THREAD

**Issue by kaqqao** [graphql-java/graphql-java#3032]
[`GraphQLArgument.Builder#defaultValue`](https://github.com/graphql-java/graphql-java/blob/e7409ac5263d451417f5651ad5b1dd891440ca29/src/main/java/graphql/schema/GraphQLArgument.java#L377) is deprecated, but I think I have points in its defense. 

1. Value passed to `GraphQLArgument.Builder#defaultValueProgrammatic` has to be raw input (as the GraphQL engine would receive it). If inside the `DataFetcher` this value is immediately deserialized into a domain instance (which is an extremely common scenario), this deserialization (of arbitrary depth) will needlessly run on every single field resolution. Using `defaultValue` instead, an already deserialized domain object can be provided avoiding the extra cost.

2. While `defaultValue` bypasses the usual validation, it can only be invoked when programmatically constructing the schema, which is _power-user mode_, so it can be seen as an advanced optimization where some extra leeway can be expected.

3. It honestly doesn't seem like a feature that would mess with anything else or require much work to support

A similar alternative to un-deprecation would be replacing `defaultValue(Object)` with `defaultValueWithState(InputValueWithState)` for the sake of clarity.

I hope these points convince you to leave this nice little escape-hatch intact, pretty please 🙏

**Comment by andimarek** [comment]
The main reason to remove it is that it is wrong: a already coerced default value can't be correctly printed back to a literal value in the general case, therefore we can't print it as SDL or return it for Introspection.

**Comment by kaqqao** [comment]
I see...
Maybe at least some memoization could be introduced to avoid repeated deserialization?
Also, sounds like [`GraphQLAppliedDirectiveArgument.Builder#inputValueWithState`](https://github.com/graphql-java/graphql-java/blob/557ad5dc35338f94fdb973521295be2b6b057625/src/main/java/graphql/schema/GraphQLAppliedDirectiveArgument.java#L236) should be deprecated.
