### ISSUE TITLE
Graphql Remove duplicates from the Response

### ISSUE THREAD

**Issue by miriyalajanardhan** [graphql-java/graphql-java#3064]
How to remove the duplicates from the response of Graphql automatically

Lets see the below graphql request I have.

```
query {
  test1(request:{
			userId: "test1@test.com"
  }) {
       id
       name
       product
  }
}
```

And the Response is below:

```
{
    "data": {
        "test1": [{
                "id": 1,
                "name": "Test",
                "product": "ABCD"
            }, {
                "id": 1,
                "name": "Test",
                "product": "ABCD-2"
            },
        ]
    }
}
```

Now if I remove the "product" in the query response field, the reponse looks like below. That is where the duplicates come.

```
{
    "data": {
        "test1": [{
                "id": 1,
                "name": "Test"
            }, {
                "id": 1,
                "name": "Test"
            },
        ]
    }
}
```

Let me know if we have any library available to do this. We are using Spring Boot with below dependency.

```
<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-graphql</artifactId>
</dependency>
```

**Comment by bbakerman** [comment]
This is not how graphql works.  You have returned a list in the `test1` field and that list is being reflected.  You would need to de-dupe in the `test` field data fetcher.

You can look ahead into the sub selected fields via `DataFetchingFieldSelectionSet`

https://www.graphql-java.com/documentation/field-selection
