### ISSUE TITLE
Validator does not catch missing value parameters

### ISSUE THREAD

**Issue by scf37** [graphql-java/graphql-java#308]
if declared `hello` with `(a: string, b: string)` following will pass execution successfully:
`{hello(a: "4")}`
`{hello(b: "4")}`
`{hello}`

code (sorry for Scala):
```
val queryType = newObject()
        .name("helloWorldQuery")
        .field {
          newFieldDefinition()
            .`type`(GraphQLString)
            .name("hello")
            .argument {
              GraphQLArgument.newArgument()
                    .name("a")
                  .description("description")
                  .`type`(GraphQLString)
                  .build()
            }
            .argument {
              GraphQLArgument.newArgument()
                  .name("b")
                  .description("description")
                  .`type`(GraphQLString)
                  .build()
            }
            .dataFetcher(env => "world")
        }
    .build()

    val schema = GraphQLSchema.newSchema()
        .query(queryType)
        .build()

    val graphQL = new GraphQL(schema)

    val result = graphQL.execute("{hello(a: \"4\")}")
    System.out.println(result.getData)
    System.out.println(result.getErrors)
```

**Comment by bbakerman** [comment]
Can you expand more on what your expectations are here?

I think your are right in that the spec says 👍 

http://facebook.github.io/graphql/#sec-Validation.Arguments

that arguments with a non null "type" should not allowed to be non null at runtime.

**Comment by scf37** [comment]
I expected error about missing arguments. 
Does nullable type of field argument imply default value of null?

**Comment by bbakerman** [comment]
I think I have it wrong.  The library requires you to wrap the type in a GraphQLNonNull type first

so 

     new GraphQLNonNull(GraphQLString)

Thats the equivalent of the JS implementation where you use !

    rollDice(numDice: Int!, numSides: Int): [Int]

So by default the Java API assumes its not required

**Comment by bbakerman** [comment]
GraphQLNonNull should have a factory for static import so you could do

     GraphQLNonNull.nonNull(GraphQLString)

and hence

     .name("a")
     .type(nonNull(GraphQLString))

**Comment by okorz001** [comment]
It seems this issue could be closed?
