### ISSUE TITLE
Align names for GraphQLContext

### ISSUE THREAD

**Issue by dfa1** [graphql-java/graphql-java#3080]
**Describe the bug**
I'm trying to get rid of deprecated method in my code base running with **graphql-java 19.0**.
The global find/replace approach is not working because there is a small typo in how GraphQLContext is spelled.

In `DataFetchingEnvironment `
        `GraphQLContext getGraphQlContext();` `Ql` instead of `QL`

In `ExecutionInput`

```
        public Builder graphQLContext(Consumer<GraphQLContext.Builder> builderFunction) {  ...
        public Builder graphQLContext(Map<?, Object> mapOfContext) {  ...
```

In `InstrumentationExecutionParameters`

```
public GraphQLContext getGraphQLContext() {
```

So far the only exception I see is in `DataFetchingEnvironment `. Maybe it is worth to deprecate the wrong name and provide the correct one? 

**To Reproduce**
N/A

**Comment by bbakerman** [comment]
Part of me says yes but more if me says that the cost ( a new deprecated method + a new corrected one) is not worth the effort for the sake of a `l`.

Others might disagree

**Comment by dondonz** [comment]
Although the inconsistency is annoying I agree that it's quite a cost to deprecate a method and move onto a new method.

**Comment by dfa1** [comment]
yes, I agree: that's why I created a bug instead of a PR ☺️

But what about people moving from older versions? they will use directly the non-deprecated method.

**Comment by dondonz** [comment]
In my team at work, I'm definitely one of the most triggered by inconsistent naming, so I do feel your pain 😭 I know you mentioned only inconsistencies with `GraphQLContext`. At the risk of being triggering, there are many more other naming inconsistencies, I spotted `GraphqlErrorBuilder` earlier today. To be clear, this is not to blame anyone, I've definitely been guilty of the same.

We had a chat about your suggestion. We only have a certain deprecation "budget" we have to spend (in terms of work we ask users to do when upgrading), and we'd rather spend it on methods where the logic has changed. Sorry.
