### ISSUE TITLE
Replace outdated links to GraphQL spec in Javadoc

### ISSUE THREAD

**Issue by rstoyanchev** [graphql-java/graphql-java#3082]
I noticed the link to `http://facebook.github.io/graphql/#sec-Errors-and-Non-Nullability` on `NonNullableFieldWasNullException` is no longer valid, and could be updated. There are 20+ places with links that start with `http://facebook.github.io/graphql`.

**Comment by bbakerman** [comment]
PR up to change this and fix a few other things
