### ISSUE TITLE
The ErrorType enum should be removed

### ISSUE THREAD

**Issue by dminkovsky** [graphql-java/graphql-java#310]
I think the `graphql.ErrorType` enum can be removed, and along with it `GraphQLError#gerErrorType()`. I think these add needless complexity and are not part of the spec. 

The only [specified error properties are](http://facebook.github.io/graphql/#sec-Errors) are

> Every error must contain an entry with the key message with a string description of the error intended for the developer as a guide to understand and correct the error.

> If an error can be associated to a particular point in the requested GraphQL document, it should contain an entry with the key locations with a list of locations, where each location is a map with the keys line and column, both positive numbers starting from 1 which describe the beginning of an associated syntax element.

**Comment by dminkovsky** [comment]
Also it's not actually used anywhere in the code base.

**Comment by bbakerman** [comment]
This is a breaking change however.  Anyone consuming this in their error handling  be broken.

Semver says this must be a 3.x change

**Comment by okorz001** [comment]
I am using this property currently.

How do you propose determining if the query failed because of user input or server failure? I currently do something like this:

```
        switch (error.getErrorType()) {
            case InvalidSyntax:
                // fall through
            case ValidationError:
                return 404;

            default:
                // fall through
            case DataFetchingException:
                // some exception inspection omitted here...
                return 500;
        }
```

Related: #239

**Comment by tklovett** [comment]
The spec _does_ explicitly allow for additional user- or implementation-specific fields:

> GraphQL servers may provide additional entries to error as they choose to produce more helpful or machine‐readable errors, however future versions of the spec may describe additional entries to errors.

**Comment by andimarek** [comment]
we wil not remove the ErrorType: I think it is quite useful and as @tklovett pointed out it is spec conform.
