### ISSUE TITLE
Introspection support for deprecated input fields

### ISSUE THREAD

**Issue by tomgasson** [graphql-java/graphql-java#3104]
The GraphQL spec supports introspection of args

```diff
 type __Field {
-   args: [__InputValue!]!
+  args(includeDeprecated: Boolean = false): [__InputValue!]!
 }
 
  type __InputValue {
+   isDeprecated: Boolean!
 }
```

This allows clients to continue to see `deprecated` input args so that things are deprecated but not broken. 
Additionally, this can be used by clients to ratchet out usages of the deprecated fields - ensuring no new usages of them

Context:
 - https://github.com/graphql/graphql-spec/pull/805

**Comment by andimarek** [comment]
Hey @tomgasson ... would you be willing to contribute a PR to implement it? That would be awesome.

**Comment by bbakerman** [comment]
This has already been reported - by you @andimarek 

#1770 

and implemented in 

#2186 

I have double checked it and its working as expected, on fields and arguments and input fields and enums
