### ISSUE TITLE
`NonNullableFieldWasNullException` not returned in execution result but still captured by New Relic

### ISSUE THREAD

**Issue by koenpunt** [graphql-java/graphql-java#3107]
Not sure if it's a bug report or a feature request, but here it goes;

We're using Spring GraphQL, and thus indirectly graphql-java. Additionally we use NewRelic for error reporting (among other things).

When returning `null` from a resolver that is defined as non-nullable, we correctly get an error in the response for the field, and the error is reported to NewRelic. 
However, when an exception is thrown from a non-nullable resolver, this exception is shown in the response correctly, but the `NonNullableFieldWasNullException` is still reported to NewRelic.

Spring GraphQL provides a way to intercept the graphql response, using a `WebGraphQlInterceptor`, but here is only one of the two exceptions available on the graphql response (which is technically correct, per https://github.com/graphql-java/graphql-java/issues/522).

It's unclear to me how or where the `NonNullableFieldWasNullException` is captured by NewRelic (I've also opened a [related issue at the agent repo](https://github.com/newrelic/newrelic-java-agent/issues/1127)).

A workaround I tried was ignoring all `NonNullableFieldWasNullException`s in NewRelic, and manually notify NewRelic of the exception, but this doesn't work either, because `NonNullableFieldWasNullException`s aren't passing through a "DataFetcherExceptionHandler".

Is there another way to intercept the `NonNullableFieldWasNullException`?

Related issue on the Spring GraphQL repository: https://github.com/spring-projects/spring-graphql/issues/600

**Comment by bbakerman** [comment]
> Is there another way to intercept the NonNullableFieldWasNullException?

The challenge will be that `NonNullableFieldWasNullException` is key to following the graphql spec.

If a field returns null (for a non null field) then an exception is throw - however if the parent field is also non nullable then it needs to be cleared and so on

https://spec.graphql.org/June2018/#sec-Errors-and-Non-Nullability

So we need to exception to flow into the code in order to follow spec.

See `graphql.execution.ExecutionStrategy#handleNonNullException` for example

**Comment by koenpunt** [comment]
That I understand, but even when the exception is not visible in the application, it still is logged to NewRelic. Is there an explanation for that?

**Comment by bbakerman** [comment]
Now you are asking a New Relic question...I have no idea
