### ISSUE TITLE
Handle breaking changes and deprecations through OpenRewrite

### ISSUE THREAD

**Issue by yeikel** [graphql-java/graphql-java#3108]
The [v20.0 release notes](https://github.com/graphql-java/graphql-java/releases/tag/v20.0) contains several breaking changes, that users will have to adapt as well as subtle deprecations [like this one](https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/execution/instrumentation/SimpleInstrumentation.java#L14-L17) that is currently not listed in the release notes

While the changes are welcome and understandably necessary, keeping track of them and applying them can be a hurdle for users to adopt.

To help users adopt these and future changes to the framework, I propose we add a module containing [OpenRewrite migration recipes](https://docs.openrewrite.org/). For those unfamiliar: OpenRewrite allows you to define migration steps either through Yaml or with Java visitors, and compose these steps to achieve larger migrations. 

As a recent example, migration recipes have been [added to Axon Framework](https://developer.axoniq.io/w/upgrading-to-axon-framework-4.7-automated). In practice that comes down to the following code changes, which also include instructions on their use: https://github.com/AxonFramework/AxonFramework/pull/2597/files

**Comment by bbakerman** [comment]
This is an interesting idea.

However it would appear to be a lot of work building / testing and then maintaining these migrations scripts.

I am not sure we have the people power to do that.

**Comment by bbakerman** [comment]
Closing this as something we just are not going to do.  Thank you for the suggestion however
