### ISSUE TITLE
Non-extensibility restrictions of GraphQL Java project

### ISSUE THREAD

**Issue by ideas-into-software** [graphql-java/graphql-java#3109]
I was recently tasked with upgrading our open source project, Gecko GraphQL, from version 11 of GraphQL Java to most recent compatible version. 

We utilize EMF heavily throughout our open source and commercial projects and Gecko GraphQL, with version of GraphQL 11 used so far, allowed to use GraphQL with EMF.

Unfortunately, as I discovered during upgrade, you’ve made a lot of design changes which result in inability to extend GraphQL Java for such purpose as ours; specifically: 

1. private (instead of protected) constructors in classes which need to be extended, e.g.: 
 - `graphql.schema.GraphQLFieldDefinition`
 - `graphql.schema.GraphQLInputObjectField`
 - `graphql.schema.GraphQLInputObjectType`

2. methods written to concrete types instead of interfaces, e.g. 
 - `graphql.schema.GraphQLInputFieldsContainer`
 - `graphql.schema.visibility.GraphqlFieldVisibility`
 - `graphql.schema.GraphQLTypeVisitor`
 - etc.

3. `graphql.execution.ValuesResolver` methods changed to static and called in 20 different places throughout codebase, making it impossible to extend EMF-related values’ resolution like so far

Therefore, I wanted to ask are there any specific reasons you do not program to interfaces and closed the GraphQL Java library this way? Are you aware of this problem and do you intend to address it ? It should be addressed holistically, i.e. for entire GraphQL Java project, so it can be extended like so far. Related issues I found are: https://github.com/graphql-java/graphql-java/issues/1978 , https://github.com/graphql-java/graphql-java/issues/1811

**Comment by bbakerman** [comment]
> Therefore, I wanted to ask are there any specific reasons you do not program to interfaces and closed the GraphQL Java library this way?

Yes - we did most of what you have listed on purpose.  We don't intend for consumers to extend the major classes directly.  A `GraphQLFieldDefinition` has a certain behavior and shape say and they are constructor via builders.   This allows us to evolve them over time and reduces the chance of breaking consumers over time.

In other languages this might be considered "sealed" classes.


>  Are you aware of this problem and do you intend to address it ? 

We made these choices consciously, we don't consider it a problem (on balance) and we don't intend to change the code.


> graphql.execution.ValuesResolver methods changed to static and called in 20 different places throughout codebase,

```
@Internal
public class ValuesResolver {
```

classes marked as `@Internal` are just that - they are not considered part of the public API.  We try to use `@PublicApi` to indicate classes that are truly public

**Comment by ideas-into-software** [comment]
Hi,

Apologies I have not had the time to reply earlier.

Apparently there are use cases (like ours, i.e. extending GraphQL to support EMF) which require a certain level of extensibility. This is an open source project and it would be enough to use interfaces in method signatures, instead of concrete types, possibly abstract classes which implement those interfaces, but can be extended, and have concrete types you already define (eg. `graphql.schema.GraphQLFieldDefinition`, `graphql.schema.GraphQLInputObjectField`, `graphql.schema.GraphQLInputObjectType`) extending those abstract classes. You could seal those concrete types, but still allow room for extensibility. So IMHO this would be ideal.

Unfortunately, due to these restrictions, we had to use a different approach, but this requires using another set of abstractions. In the just released, latest version of our GraphQL EMF library (https://github.com/geckoprojects-org/org.gecko.graphql) we had to utilize such approach.

On a related note, as part of work on that GraphQL EMF library, I had to introduce a small change in `GraphQL Java Servlet` to allow for using Jakarta Servlet API version 5.x, and shared  that pull request: https://github.com/graphql-java-kickstart/graphql-java-servlet/pull/524 – please see that PR for more info if interested. 

Regards
