### ISSUE TITLE
DataFetcherResult with extensions

### ISSUE THREAD

**Issue by dfa1** [graphql-java/graphql-java#3118]
**Describe the bug**
In one of our `DataFetcher`s, we need to return data + extensions. Right now this is not possible and we are forced to either use a workaround or to add yet another `Instrumentation` (in order to access the `ExecutionResult`).

Would you consider adding `extensions` to `DataFetchingResult` a good design? 

**To Reproduce**
No code so far...

**Comment by bbakerman** [comment]
Yes...I have a PR up to do this...I am on mobile and don't have way
access...but search and tell me what you think..

It's not DataFetcherResult based... But maybe it could be

**Comment by bbakerman** [comment]
See 

https://github.com/graphql-java/graphql-java/pull/3049

https://github.com/graphql-java/graphql-java/pull/3085

The `ExtensionsBuilder` will be available as a GraphqlContext value under the class key.

Now there is another design argument that could make it do this

* A DataFetcherResult is extended to include extensions to add
* Execution Strategy code would be changed to see them
* It would call the ExtentionsBuilder itself say

One thing I don't like is 2 ways to do the same thing

But one thing I do like is that DataFetcherResult is a "rich functional object" - ef return things like errors or local context or extensions and they get acted on.

I am leaning towards having this in place

**Comment by dfa1** [comment]
it looks nice! looking forward to test the pre-release!
