### ISSUE TITLE
Ability to pass authentication/authorization data transparently to DataFetcher

### ISSUE THREAD

**Issue by mindas** [graphql-java/graphql-java#314]
I am planning to use GraphQL by exposing the ability to send queries from the frontend, but adding the authentication/authorization layer in the backend. From what I have read, the recommended approach is to implement this in `DataFetcher`. This seems fairly good idea, `DataFetcher` returning `null` / terminating object graph in case if loaded object is not viewable for the current user.

However, I have struggled with passing authentication data from `graphQL.execute(...)` so it ends up in `DataFetchingEnvironment`. Perhaps I have missed something, but here's my evaluation of all possible options I have tried:

- Passing auth data via `Object context`. From what I understand, `context` (also referenced as `root` or `source`) is used to refer to parent JSON and therefore should not be used to carry auth information.

- Passing auth data via `Map<String, Object> arguments`. This seemed like an ideal option, however only arguments matching variable values are allowed in and others are filtered out by `ValuesResolver`. I could not find any way of supplying own `ValuesResolver` except reflection. I would rather not declare this as a public GraphQL variable as authentication/authorization is purely server-side business.

- extending default `ExecutionContext`. This again would be a possible option, however there are no hooks for that; object is instantiated in `ExecutionContextBuilder`, and `ExecutionContextBuilder` is again instantiated explicitly in `Execution`.

Is there any other option that would be possible in this scenario? Thank you.

**Comment by dllx** [comment]
We are also using the context (Object) to store some information that we need in several data fetchers all around the response hierarchy. That works fine, I don't see how you could not put info about the executing user (authentication info) there.

If you use some authentication/authorization framework like Shiro, you can use that to get the Subject, but (in the case of Shiro), the Subject is bound to the thread local storage. Parallel execution strategies won't work, then.

**Comment by bbakerman** [comment]
The main graphql page gives some great examples on how to approach AuthN / AuthZ

http://graphql.org/learn/authorization/

In general the "context" object you pass into the original graphql.execute() method is of your choosing and is "not used to carry the source".

`graphql.schema.DataFetchingEnvironment#getContext` gives you a context object you passed in and its not changed by the framework

`graphql.schema.DataFetchingEnvironment#getSource` gives you the current "source object" in the graph as it executes and resolves field values.

One thing I would add (as outlined on that graphql link) is that authN belongs in the business layer code that your graphql code calls.  Dont put it in the DataFetchers or you will make your system more brittle.
