### ISSUE TITLE
Maven Artifact 2.3.0 is not the current version 2.3.0

### ISSUE THREAD

**Issue by mattesja** [graphql-java/graphql-java#316]
The maven artifact I've got from maven central (https://search.maven.org/remotecontent?filepath=com/graphql-java/graphql-java/2.3.0/graphql-java-2.3.0.jar) seems to have the wrong version (shasum = eb290bb0ebc1bd9e9b9762fba3d3008306029a94).

Especially the HelloWorld example did not compile, because the method  GraphQL.newGraphQL() is missing. After building an own jar from the sources everything works.

**Comment by dminkovsky** [comment]
Hi @mattesja. The version you see by default at https://github.com/graphql-java/graphql-java/ is the latest master. Please select a tagged release or commit to browse other versions of this codebase.

**Comment by mattesja** [comment]
Ok, using the doc from https://github.com/graphql-java/graphql-java/tree/v2.3.0 helped.
Thanks!
