### ISSUE TITLE
GraphQL API : `variables` in a POST body should be provided as an object, not a recursively JSON-encoded string

### ISSUE THREAD

**Issue by bachhavdipak** [graphql-java/graphql-java#3161]
**Describe the bug**
A clear and concise descriI am trying to use graphql api but while triggering api I am getting below error message. 

    {
        "errors": [
            {
                "message": "`variables` in a POST body should be provided as an object, not a recursively JSON-encoded string.",
                "extensions": {
                    "code": "BAD_REQUEST"
                }
            }
        ]
    }

Input Request :

     Response response = given()
                    .contentType(ContentType.JSON)
                    .header("authorization", "xxxxx.yyyyy.zzzz")
                    .body(query)
                    .when()
                    .post("https://adoveq.stepzen.net/api/graphql");
    
            response.then().log().all();

Query : 

    mutation login($email: String!, $password: String!) {
    
      signIn(email: $email, password: $password)
    
    }

When I am passing raw body with credential then I am getting response but when I am passing them as variable to below MyInput class its throwing error.

    public class MyInput{
    
        private String query;
        private String Parameters;
    
        public String getQuery() {
            return query;
        }
    
        public void setQuery(String query) {
            this.query = query;
        }
    
        public String getParameters() {
            return Parameters;
        }
    
        public void setParameters(String Parameters) {
            this.Parameters = Parameters;
        }
    
    }
    
**Passing variable value using below code:**

            JSONObject variables = new JSONObject();
            variables.put("username", "James smith");
            JSONObject variables1 = new JSONObject();
            variables1.put("password", "Q1dsfsdfsdfet");

            final String query="mutation login($email: String!, $password: String!) {  signIn(email: $email, password: $password)  }";
            final MyInput= new MyInput();
            query.setQuery(query);
            query.setVariables(variables.toString());
            query.setVariables(variables1.toString());

**Comment by dondonz** [comment]
Hello @bachhavdipak,  

This issue appears to be related to how your HTTP request is formed. I'm not sure which libraries you are using so it is hard for me to debug. In case you haven't seen it, have a look at the [serving over HTTP GraphQL documentation](https://graphql.org/learn/serving-over-http/#post-request) and you could also ask the provider of the API you are trying to contact for more information.

I am closing this issue as this error was not generated by the GraphQL Java library. This library doesn't include transport concerns such as HTTP.
