### ISSUE TITLE
This code base help me to resolve graphql-java version 7 CVE also ?

### ISSUE THREAD

**Issue by Gowtham21** [graphql-java/graphql-java#3197]
I just want to know, in our code base we are using graphql-java version 7 for different purpose, to avoid the vulnerability attack, this code base can really help to resolve this issue ? I also heard lower version of graphql has good in performance compare to the latest version, so we are sticking in graphql version 7 only.

**Comment by dondonz** [comment]
We haven't backported the latest CVE to version 7. See [this discussion](https://github.com/graphql-java/graphql-java/discussions/3181) for the list of patched versions.

We are a small team of volunteers so we only have a limited bandwidth to support old versions. Generally speaking we backport security fixes for a given version for roughly 18 months, see the [release policy](https://www.graphql-java.com/blog/release-policy) for more.

I understand it's a considerable jump from version 7 to one of the patched versions, but there have been immense performance improvements in the most recent few versions. We've had performance improvements contributed by Twitter and others, and we've worked to reduce object allocations and speed up PropertyDataFetchers. See the release notes for more, for example [the release notes for v20](https://github.com/graphql-java/graphql-java/releases/tag/v20.0).

**Comment by Gowtham21** [comment]
Thanks for the update, Final thing for this CVE 2022-37734, is there any other way that we can stop the threads without uplifting to any newer version ?

**Comment by bbakerman** [comment]
v7.0 came out on Jan 12, 2018 - that's more than 5 years ago - that's forever ago in software terms

> is there any other way that we can stop the threads

I am not sure what that means

**Comment by bbakerman** [comment]
Closing as answered
