### ISSUE TITLE
AstPrinter produces invalid GraphQL

### ISSUE THREAD

**Issue by pcarrier** [graphql-java/graphql-java#3229]
**Describe the bug**
When a non-BlockString string contains escaped characters like newlines or quotes, AstPrinter does not escape them and the resulting document is not valid GraphQL.

**To Reproduce**
https://github.com/pcarrier/graphed/blob/main/src/jvmTest/kotlin/com/pcarrier/graphed/graphql/Repro1.kt

```
=== Original ===
"\"" scalar A
=== Parsed and printed ===
"""
scalar A

Exception in thread "main" graphql.parser.InvalidSyntaxException: Invalid syntax with ANTLR error 'token recognition error at: '"""\nscalar A\n'' at line 1 column 1
	at graphql.parser.Parser$1.syntaxError(Parser.java:368)
…
```

**Comment by dondonz** [comment]
Hello from the future! I wanted to say, thanks for reporting the bug! I'm working on a fix

**Comment by dondonz** [comment]
Trialing our new bot

This is still on my todo list
