### ISSUE TITLE
Expand GraphQL schema ANTLR parser to capture comments as descriptions

### ISSUE THREAD

**Issue by apottere** [graphql-java/graphql-java#325]
The reference implementation was updated to allow comments in a GraphQL schema to be available on the objects/fields they immediately precede as descriptions (https://github.com/graphql/graphql-js/pull/464).  I would be awesome if the java implementation could do the same!  Right now in my project we're using decorators to achieve a similar effect, but it's less intuitive and less readable.

I don't know enough about ANTLR to do it myself, or else I would submit a PR instead of an issue 😞

**Comment by bbakerman** [comment]
I have submitted a PR for capturing comments

**Comment by bbakerman** [comment]
This is now on master
