### ISSUE TITLE
graphql.GraphQL::executeAsync should catch clause of AbortExecutionException call instrumentation.instrumentExecutionResult?

### ISSUE THREAD

**Issue by dimdimych** [graphql-java/graphql-java#3255]
It is not a bug report but a question. 

I have a `instrumentation.beginExecution` implementation that checks the security context of the request and throws an `AbortExecutionException` if it is not found in the request or expired. That works fine for me except for the fact that I have the other instrumentation with `instrumentExecutionResult` that adds some generic request and environment metadata to the "extensions" node of the response. When `AbortExecutionException` is thrown it doesn't get called because currently, the `AbortExectionException` catch clause creates an `ExecutionResult` from the exception and just returns it. 

My question is, shouldn't `instrumentation.instrumentExecutionResult` be called on the result in the case of caught `AbortExecutionException`?  

See graphql/GraphQL.java:440-450

**Comment by bbakerman** [comment]
On my phone right now... And will look into this... But off hand I would
say yes .. instrumentResult() sorry be called

**Comment by bbakerman** [comment]
I can see the problem

```
         //
            // allow instrumentation to tweak the result
            executionResult = executionResult.thenCompose(result -> instrumentation.instrumentExecutionResult(result, instrumentationParameters, instrumentationState));
            return executionResult;
        } catch (AbortExecutionException abortException) {
            return CompletableFuture.completedFuture(abortException.toExecutionResult());
        }
```

It only calls the instrumentation during the happy  path - this should be fixed

**Comment by bbakerman** [comment]
I looked into this more - it seems if the `AbortExecutionException` happens during the execute phase - the intrumentation will be caught but if its during "parse / validate" phase - it will not - I list this here to say it sometimes works but not for all edge cases
