### ISSUE TITLE
GraphQL doesn't preserve order of input object fields

### ISSUE THREAD

**Issue by lukashornych** [graphql-java/graphql-java#3256]
We are building a GraphQL API for our specialized e-commerce database, where we use input objects on GraphQL queries to define complex internal database queries (filter, order, requirements, ...). Recently, we have discovered that the GraphQL Java lib doesn't preserve the order of fields nested in input objects defined by the API consumer. Consider this simplified example of our query:

```graphql
listProducts(
  orderBy: {
    attributeNameNatural: ASC,
    attributeCodeNatural: DESC
  }
) {
  primaryKey
}
```

This query tells us that the API consumer wants to get a list of all products sorted primarily by `name` attribute in ascending order and secondarily by a `code` attribute in descending order. Therefore, we expect to get the following Java map in a data fetcher for the `orderBy` argument:

```json
{
  "attributeNameNatural": "ASC",
  "attributeCodeNatural": "DESC"
}
```

Instead, we get the following map, which has keys sorted by field definitions (sorted by field name):

```json
{
  "attributeCodeNatural": "DESC",
  "attributeNameNatural": "ASC"
}
```

To correctly determine which condition is primary and which one is secondary, we need GraphQL to parse this object into a Java map in the same order as it arrived at the API endpoint. However, this is not currently happening. I dug into the library and found out that fields are parsed by iterating over all field definitions of an input object definition in the `graphql.execution.ValuesResolverConversion#literalToInternalValueForInputObject` method.
This approach sorts the fields of input objects according to the API schema, not what an API consumer has defined, which is the main issue for us. 

As a side note, especially in our case, this approach of parsing doesn't seem to be very performance-optimized, considering the fact that e.g. in our case, filter conditions can have object definitions with easily 200+ fields, of which the API consumer usually sends only a few (usually not more than 10 fields per an input object). Maybe some kind of field indexing using HashMaps could speed this up? Compared to our REST API with the same features, our GraphQL API is significantly slower, most likely due to the input parsing and validation.

Is the consumer-oriented field order preservation something that makes sense to implement in the GraphQL Java library core, or are there some known complications? I'd be happy to help with the implementation if that's possible, the problem seems to be mainly in the `graphql.execution.ValuesResolverConversion` class.

**Comment by bbakerman** [comment]
Thanks for the detailed report.  I am surprised we don't because we have lots of code in other places that tries to preserve field order etc..

The graphql spec says they do not have to be ordered

https://spec.graphql.org/June2018/#sec-Input-Object-Values

>  Input object fields may be provided in any syntactic order and maintain identical semantic meaning.
> These two queries are semantically identical:

```
{
  nearestThing(location: { lon: 12.43, lat: -53.211 })
}
{
  nearestThing(location: { lat: -53.211, lon: 12.43 })
}
```

So the specification is working against what you are trying to achieve.  I know personally I would have intuitively thought they would be ordered but the spec is quite adamant here.

For arguments themselves  they are also unordered

https://spec.graphql.org/June2018/#sec-Language.Arguments

> Arguments may be provided in any syntactic order and maintain identical semantic meaning.

**Comment by bbakerman** [comment]
> As a side note, especially in our case, this approach of parsing doesn't seem to be very performance-optimized, considering the fact that e.g. in our case, filter conditions can have object definitions with easily 200+ fields, of which the API consumer usually sends only a few (usually not more than 10 fields per an input object).

I had a quick look into this and went as far as trying to create a PR with a map of input fields.  The challenge is that fields can have defaults.

```
input Foo {
    a : String
    b: String  = "B"
    c: String = "C"
    d : String
}
```

and `f(arg : {a : "A"})` would result in a argument map of

```
{
  a: "A",
  b : "B",
  c: "C"
}
```
  
 

So for a input object type it might have 200 fields (of which the consumer only provides say 10) but the engine can't know that the other 190 are or are not defaulted - so it has to iterate the list of possible input fields anyway to find the default values.

One possible way to do this would be to have `InputFieldsContainer` have a `Map<String,Object> getDefaultValues()` say so that we could iterate by provided AST field name and then some how slip in the default values for fields not present.  

The challenge is that default values are not particularly cacheable across requests

```
                Object coercedDefaultValue = defaultValueToInternalValue(
                        inputInterceptor,
                        fieldVisibility,
                        inputFieldDefinition.getInputFieldDefaultValue(),
                        fieldType,
                        graphqlContext,
                        locale);
```

The current request attrs ( fieldVisibility, graphqlContext, locale) can all be specific to the current request and hence the default values per request can change

We need to think on this more.

**Comment by lukashornych** [comment]
Thank you for the detailed analysis! There is a lot of valuable information for us.

You are right about the order of the input fields. To be honest, I didn't know that the GraphQL spec define this. Thanks for the valuable info! We'll probably have to find another solution on our end so that we don't confuse users of our API with the field order.

As for the performance, I didn't know that an input field could have a default value, that's my bad. The official [GraphQL docs](https://graphql.org/learn/) don't say much about it, so I must have missed it even in the code I've mentioned. The suggested `Map<String,Object> getDefaultValues()` seems fine to me, at least better than iterating over every single input field. That way, if there are no or a small number of default values, the map would be empty, and we would save resources by not iterating over a potentially large collection of field definitions. 

> The current request attrs ( fieldVisibility, graphqlContext, locale) can all be specific to the current request and hence the default values per request can change

I've looked into this more and it seems to me (please, correct me if I'm missing something) that only the actual parsing/serialization part of the default value resolution can be parametrized with these attributes (i.e. value coercings). The original default value in a GraphQL schema is represented by the `InputValueWithState` object, which doesn't seem to depend on the request attributes. 
My thinking would then be to cache these raw default values in the previously mentioned map `Map<String,InputValueWithState> getDefaultValues()`, and the parsing/serialization could be performed in real time when we have all of the default values collected.

What do you think about this?

**Comment by bbakerman** [comment]
We are always keen to get performance improvements

In this case I think we will need a way to 

* get all arguments of a output field that have defaults
* get all fields of a input type that have defaults

It was the defaulting of values that stop my attempt earlier to fix this.  but we want that computation of "args / fields with defaults" to be done once - and the best time to do that is at field / input object creation time not per request

**Comment by lukashornych** [comment]
After some testing and profiling on our end in our application, it seems that the discussed problem with default values strangly doesn't occur after all. At least in our case. If it turns out to be a problem in the future, we will try to find a solution and create another issue. 

For now, thank you for your patience, we will close this issue as the main topic was resolved.
Thanks again.
