### ISSUE TITLE
documentation on custom scalars is out of date

### ISSUE THREAD

**Issue by softprops** [graphql-java/graphql-java#3277]
I just resolved some deprecation warnings in my build related to coercing implementation and then noticed the current user docs for creating custom scalars will lead users towards deprecated versions of coercing methods. 

Current user docs https://www.graphql-java.com/documentation/scalars#writing-your-own-custom-scalars
Current java docs https://javadoc.io/static/com.graphql-java/graphql-java/21.0/graphql/schema/Coercing.html

This is not technically a bug so I'm filing under "other issue" as documentation debt

**Comment by dondonz** [comment]
Thanks, yes our documentation needs updating, especially to remove deprecated examples.

In case anyone reading would like to help us out, the repo with the documentation is https://github.com/graphql-java/graphql-java-page

**Comment by dondonz** [comment]
Trialing our new bot! This is on my to do list as part of a documentation overhaul coming soon

**Comment by dondonz** [comment]
Closed as it was fixed by https://github.com/graphql-java/graphql-java-page/pull/146 thanks!
