### ISSUE TITLE
DataFetchingEnvironment generic methods should accept Class<T> as an argument

### ISSUE THREAD

**Issue by guy120494** [graphql-java/graphql-java#328]
For my opinion, it will be safer for programmers that way, because casting errors will be caught at compile time rather than run time (and you wont get CastException)

**Comment by dminkovsky** [comment]
Thanks yes this seems like a good thing to me. So the cast would happen
through Class#cast()?


чт, 16 февр. 2017 г. в 11:59, Guy Smorodinsky <notifications@github.com>:

**Comment by guy120494** [comment]
yes, through clazz.cast(env.getSource());

**Comment by guy120494** [comment]
yes

**Comment by bbakerman** [comment]
As discussed on the PR, the benefits for this change do not outweigh the costs.
