### ISSUE TITLE
Critical: Missing Guava in graphql-java 19.7 Causing Service Failures

### ISSUE THREAD

**Issue by samjcombs** [graphql-java/graphql-java#3318]
**Describe the bug**
There appears to be an issue with `graphql-java` version `19.7` related to the way it handles the `guava` dependency. 

In version 19.6, guava was bundled within the JAR. However, in 19.7, it's absent.  _Is this intentional?_
![image](https://github.com/graphql-java/graphql-java/assets/104232548/dedbd530-0d05-4253-9e2e-bc3677f616c5)

Additioanlly, both the POMs for 19.6 and 19.7 are identical (apart from the library version), suggesting a reliance on the packaged version of the dependency in the META-INF of the library. 
<img width="1305" alt="image" src="https://github.com/graphql-java/graphql-java/assets/104232548/228947c3-1329-4e6e-b869-0d97b5a7ff9b">

Adding the guava dependency directly leads to a type mismatch errors all over the place even when the [exact version indicated for guava in graphql-java's build.gradle](https://github.com/graphql-java/graphql-java/blob/master/build.gradle#L92C55-L92C55) is provided.

![image](https://github.com/graphql-java/graphql-java/assets/104232548/bb1c0dc6-82fd-4d29-82db-d6a1b4596c24)

This surfaced in our org in a rather nasty way yesterday, as a number of services automatically upgraded to the next minor version bump, but are now in a broken state because graphql-java complains that guava is non existent.  

The solution is to pin graphql-java to 19.6, but because other libraries, e.g. DGS, Apollo jvm, rely on graphql-java, pinning can result in other unintended side-effects.  We will do it in the meantime to unblock services, but can anyone comment as to why guava was removed from the 19.7 JAR file? 

** To Reproduce **

Observe that the 19.6 JAR has guava bundled within.
In contrast, the 19.7 JAR does not.

**Comment by samjcombs** [comment]
Thanks @sullrich84 for the additional context.  Upon deeper investigation, we are going to pin to `19.2` instead of `19.6` to ensure maximum compatibility with our DGS and Apollo deps.

**Comment by andimarek** [comment]
thanks for the quick response everybody ... we will look into it as soon as possible. In the meantime just use the previous bugfix release as already suggested. 

Thanks!

**Comment by bbakerman** [comment]
Notes for the graphql-java team but also in the spirit of open source.

I didn't think we bundled Guava at all in its original form.  I thought we shaded it into our own package for the classes we use, namely the Immutable collection classes (and support code)

If I recall right , then nominally we shouldn't have any com.google.* in our code base at all.  Did we upgrade gradle at some point and start to "unshade" good into the code base and then consumers started to depend on it

We will want to look through versions and see when we started to provide guava classes in `com.google` form...

**Comment by bbakerman** [comment]
Affected versions

| version | has `graphql.com.google.common`
| 17.0       |  ✅❌


| Version       | has `graphql.com.google.common` |
| ----------- | ----------- |
| 17.0             | ✅                |
| 17.6             | ✅                |
|                    |                     |
| 18.0             | ✅                |
| 18.7             | ✅                |
|                    |                     |
| 19.0             | ✅                |
| 19.4             | ✅                |
| 19.5             | ✅                |
| 19.6             | ✅                |
| 19.7             | ❌                |
|                     |                    |
| 20.0            | ✅                |
| 20.4            | ✅                |
| 20.5            | ❌                |
|                     |                    |
| 21.0             | ✅                |

**Comment by bclozel** [comment]
master builds look fine to me

```shell
$ wget https://repo1.maven.org/maven2/com/graphql-java/graphql-java/0.0.0-2023-09-01T02-27-18-c14a72f/graphql-java-0.0.0-2023-09-01T02-27-18-c14a72f.jar
$ tar -tvf "graphql-java-0.0.0-2023-09-01T02-27-18-c14a72f.jar" | grep "graphql/com/google" | wc -l
   901
```

To me it looks like the guava versions are out of sync between [the dependency declaration](https://github.com/graphql-java/graphql-java/blob/20.x/build.gradle#L92) (`com.google.guava:guava:32.0.0-jre`) and the [shadow configuration](https://github.com/graphql-java/graphql-java/blob/20.x/build.gradle#L126) (`com.google.guava:guava:32.1.1-jre`). This is the case on both 20.x and 19.x branches. Aligning the versions and building the jar locally fixes things for me.

It's really easy to make such a typo, so maybe turning that version into a variable or refactoring all of those into [a version catalog](https://docs.gradle.org/current/userguide/platforms.html#sec:sharing-catalogs).

**Comment by dondonz** [comment]
Thanks everyone for reporting the issue and helping us to debug. I have started the release process for v20.6 and v19.8 which will fix the problem. It will land in Maven shortly.

**Comment by dondonz** [comment]
Confirming both v19.8 and v20.6 have landed in Maven and we triple checked the JARs to verify that Guava is shaded.

https://repo1.maven.org/maven2/com/graphql-java/graphql-java/19.8/
https://repo1.maven.org/maven2/com/graphql-java/graphql-java/20.6/
