### ISSUE TITLE
Cannot resolve method GraphQL.newGraphQL?

### ISSUE THREAD

**Issue by Nickersoft** [graphql-java/graphql-java#332]
I'm trying to get the Hello World code running on my server, and have installed version 2.3.0 using Gradle:

`compile 'com.graphql-java:graphql-java:2.3.0'`

However, attempting to call 
`GraphQL graphQL = GraphQL.newGraphQL(schema).build();` 
throws an errors saying that `newGraphQL` cannot be resolved. I checked the decompiled class file and for some reason all of the static methods are gone and it just contains a bunch of `execute()` public methods. Any idea as to why?

**Comment by dminkovsky** [comment]
Hi Tyler,

The readme is current with master. Please see the tree at the v2.3.0 tag to
see that version's readme.

Thanks,
Dmitry

сб, 18 февр. 2017 г. в 11:57, Tyler Nickerson <notifications@github.com>:

**Comment by Nickersoft** [comment]
Thanks @dminkovsky! Didn't realize there'd be such a difference.

**Comment by dminkovsky** [comment]
It's mostly cosmetic with regard to the scheme definition API. You'll find
it's pretty similar.

сб, 18 февр. 2017 г. в 12:58, Tyler Nickerson <notifications@github.com>:
