### ISSUE TITLE
How about using Immutable to define the model

### ISSUE THREAD

**Issue by hepin1989** [graphql-java/graphql-java#333]
Currently the builder is written by hand,how about this ?
I you guys think that's OK,I could do it.

**Comment by dminkovsky** [comment]
@hepin1989 could you do it in Immutable? would those classes handle validation, or would there be another layer on top of the immutables that did schema validation?

**Comment by bbakerman** [comment]
As much as Immutables is cool...I am not sure there is a big benefit here.  The builders are already written and we dont write many of them like you would in a more CRUD project.

So its diminishing returns on for this new dependency.

I like Immutables but in this case I am not sure its warranted

**Comment by andimarek** [comment]
Thanks @hepin1989 for offering your help.
But I agree with @bbakerman: They are already written and we will not reimplement them. Therefore I am closing the issue.
