### ISSUE TITLE
Interest in generating schemas through reflection?

### ISSUE THREAD

**Issue by pkriens** [graphql-java/graphql-java#3333]
For my own work I developed a GraphQLSchema generator that makes it very lightweight to create a GraphQL endpoint. I could donate this in improved form if this is interesting.

To define a GrapQL endpoint, it is necessary to define an interface that represents the schema. Any defined classes are treated as Schema types. Methods are by default treated as Schema Fields but an annotation can make it a Mutation. All data types are properly mapped, including generic types for Lists.
```java
	interface MyDomain extends GraphQLDomain {

		class Foo {
			int bar;
		}

		List<Foo> foo();

		Foo foo1(int x);

		@Mutation
		@Nullable Foo foom(int x);

	}
```
This delivers the following schema:
```graphql
"Marks the field, argument, input field or enum value as deprecated"
directive @deprecated(
    "The reason for the deprecation"
    reason: String = "No longer supported"
  ) on FIELD_DEFINITION | ARGUMENT_DEFINITION | ENUM_VALUE | INPUT_FIELD_DEFINITION

"Directs the executor to include this field or fragment only when the `if` argument is true"
directive @include(
    "Included when true."
    if: Boolean!
  ) on FIELD | FRAGMENT_SPREAD | INLINE_FRAGMENT

"Directs the executor to skip this field or fragment when the `if` argument is true."
directive @skip(
    "Skipped when true."
    if: Boolean!
  ) on FIELD | FRAGMENT_SPREAD | INLINE_FRAGMENT

"Exposes a URL that specifies the behaviour of this scalar."
directive @specifiedBy(
    "The URL that specifies the behaviour of this scalar."
    url: String!
  ) on SCALAR

type Foo {
  bar: Int!
}

type Mutation {
  foom(x: Int!): Foo!
}

type Query {
  foo: [Foo]
  foo1(x: Int!): Foo
}
```
To provide an implementation, it is only necessary to provide an implementation of the Domain class.
```java
	@Test
	public void testMyDomain() {
		GraphQLSchema schema = ReflectiveSchemaGenerator.schema(MyDomain.class, new MyDomain() {

			@Override
			public List<Foo> foo() {
				Foo foo = new Foo();
				foo.bar = 3;
				return Collections.singletonList(foo);
			}

			@Override
			public Foo foo1(int x) {
				Foo foo = new Foo();
				foo.bar = x;
				return foo;
			}

			@Override
			public Foo foom(int x) {
				return null;
			}
		});
		System.out.println(new SchemaPrinter().print(schema));
		GraphQL engine = GraphQL.newGraphQL(schema)
			.build();
		ExecutionResult executionResult = engine.execute("mutation mname { foom(x:10) { bar } }");

		Map<?, ?> data = executionResult.getData();
		System.out.println(executionResult);

	}

```

If this is not of any interest, feel free to close this issue. If I get positive feedback I can provide a PR.

**Comment by bbakerman** [comment]
The graphql-java code base concentrates on being the underlying engine for others to build up.

Spring GraphQL And Netflix DGS have done that as have other libraries such as [GraphQL SPQR](https://github.com/leangen/graphql-spqr)

So while I am not saying you work is not interesting - we would not be interested in including it into the base graphql-java engine code base.

**Comment by pkriens** [comment]
Ok, I understand the reasoning. I always hate extra dependencies myself :-)

Just one closing comment. This model to declare the schema and operations declaratively in an interface can _massively_ reduce the API surface. And it is only one 424 line class with no external dependencies :-)

**Comment by bbakerman** [comment]
> And it is only one 424 line class with no external dependencies :-)

Now that sounds really interesting - why not throw it up into your github repo and see what others think of it
