### ISSUE TITLE
Upgrade to SLF4J 2.0.x - Is that needed

### ISSUE THREAD

**Issue by schaefa** [graphql-java/graphql-java#3339]
With Sling GraphQL Core I am running into an issue when upgrading to 21.x that the project upgraded to SLF4J 2.0.7 but that breaks our integration.

When I downgrade graphql-java to SLF4J to 1.7.25 and build it with the latest code (aka fixing the android.os issue) it compiles and works just fine.

If GraphQL-Java works with SLF4J 1.7.25 why did you upgrade as I am pretty sure not the only one that might have dependency issues.

**Comment by schaefa** [comment]
I don't mind the upgrade but maybe the release could ask for a range in MANIFEST.MF that includes 1.7 as lower end (or even lower) instead of 2.0.

**Comment by dondonz** [comment]
Hello, thanks for reporting the issue!

As more background, we automatically update dependencies with Dependabot. There wasn't any particular reason for upgrading from that version of SLF4J.

I'll have a closer look and think about what we can do, there are a few options.

**Comment by dondonz** [comment]
From the next release, we'll be removing SLF4J as a dependency entirely https://github.com/graphql-java/graphql-java/pull/3403

Thanks for reporting the issue!
