### ISSUE TITLE
GraphQL Response Missing `data` Entry

### ISSUE THREAD

**Issue by aschober** [graphql-java/graphql-java#334]
According to the [GraphQL spec](https://facebook.github.io/graphql/#sec-Response-Format), the Response format should include the `data` entry for holding the result of the query and `error` entry for holding any errors. 

It appears `ExecutionResult.getData()` returns a map of the object without this top-level `data` entry.

Using library v2.3.0.

**Comment by aschober** [comment]
Thinking on this more, it appears that the expected path is to JSON serialize the entire `ExecutionResultImpl` object which includes `data` and `error` objects as opposed to accessing the fields independently.

**Comment by bbakerman** [comment]
Yup - the graphql-java implementation does perform JSON serialisation, since this is best done by your other library code such as Jackson / Jersey / GSON etc..

But it gives you a object that will serialise out as 

    { "data" : { .... } }
