### ISSUE TITLE
SchemaDiff EnforceDirectives Option Does Not Identify Removal of Directive From Type or Field

### ISSUE THREAD

**Issue by ndejaco2** [graphql-java/graphql-java#3343]
**Describe the bug**
The enforceDirectives option for SchemaDiff does not properly detect if a directive was removed from a field or type. This is because it relies on an introspection result as input. The introspection query does not return directives on fields or types so they are not present when the diff of the document is ran. 

**To Reproduce**

Schema 1:

```
directive @someDirective on FIELD_DEFINITION

type test {
  version: String! @someDirective
}

type Query {
  getTests: [test]!
}
```

Schema 2:

```
directive @someDirective on FIELD_DEFINITION

type test {
  version: String!
}

type Query {
  getTests: [test]!
}
```
When schema diff is run on these two schemas it will detect no changes even though removal of a directive could be a breaking change especially for composite schemas. 

Potential solution would be providing the ability for DiffSet to provide the SchemaDefinition directly so that it can be overridden to use an approach that does not require introspection:

```
public interface DiffSet {
     Document getOldSchemaDefinition();
     Document getNewSchemaDefinition();
}


public class IntrospectionDiffSet implements DiffSet  {
   ....
   @Override
   public Document getOldSchemaDefinition() {
        return new IntrospectionResultToSchema().createSchemaDefinition(this.introspectionOld);   
    }
    
    @Override
     public Document getNewSchemaDefinition() {
        return new IntrospectionResultToSchema().createSchemaDefinition(this.introspectionNew);   
    }
}
```
The SchemaDiff class can then use this hook rather than requiring the introspection result method. 

```
public class SchemaDiff {
 ...
     private void diffSchemaImpl(DiffSet diffSet, DifferenceReporter reporter) {
            Document oldDoc = diffSet.getOldSchemaDefinition();
            Document newDoc = diffSet.getNewSchemaDefinition();
            ...
     }
}
```

We would then be able to override this implementation with something like this:
```
 public class SDLDiffSet implements DiffSet {
   ....
   
   @Override
   public Document getOldSchemaDefinition() {
        return Parser.parse(this.oldSchemaSdl);
   }
    
    @Override
    public Document getNewSchemaDefinition() {
        return Parser.parse(this.newSchemaSdl);
    }
}
```

I am willing to help with a PR if there is some agreement on direction here.

**Comment by ndejaco2** [comment]
Here is a failing test:

```
def "directives are removed should be breaking when enforceDirectives is enabled"() {
        def oldSchema = TestUtil.schema('''
        directive @someDirective on FIELD_DEFINITION

        type test {
          version: String! @someDirective
        }
        
        type Query {
          getTests: [test]!
        }
       ''')
        def newSchema = TestUtil.schema('''
        type test {
          version: String!
        }
        
        type Query {
          getTests: [test]!
        }
       ''')
        def reporter = new CapturingReporter()
        DiffSet diffSet = DiffSet.diffSet(oldSchema, newSchema)
        def diff = new SchemaDiff(SchemaDiff.Options.defaultOptions().enforceDirectives())
        when:
        diff.diffSchema(diffSet, reporter)

        then:
        reporter.dangerCount == 0
        reporter.breakageCount == 1
        reporter.breakages.every {
            it.getCategory() == DiffCategory.MISSING
        }
    }
```

**Comment by dondonz** [comment]
Thanks for the detailed report and test, we'll have a look. Could you let me know which version of GraphQL Java you're using?

**Comment by ndejaco2** [comment]
This repros on any version since SchemaDiff was introduced, but for the sake of investigation lets just work off the latest

**Comment by ndejaco2** [comment]
I went ahead and added a PR to fix this. Let me know what you think :)

**Comment by ndejaco2** [comment]
Change is merged, any idea when the next release might be?

**Comment by dondonz** [comment]
We're planning a non-breaking change release later this month (October).

In general we release quarterly, alternating between breaking change releases and non-breaking change releases. More details here: https://www.graphql-java.com/blog/release-policy/

**Comment by dondonz** [comment]
Alternatively we do publish build versions for every merged in change, so if you'd like to use it immediately that's an option as well.

**Comment by ndejaco2** [comment]
Great thanks!
