### ISSUE TITLE
Scalars example implementaion is outdated (interface Coercing)

### ISSUE THREAD

**Issue by jodeleit-es** [graphql-java/graphql-java#3347]
**Describe the bug**
The code example at https://www.graphql-java.com/documentation/scalars/#example-implementation is outdated. It overrides now deprecated methods and if you follow the example stuff breaks. Further analysis is pending, but it seams that introspection queries throw a 400 with an error message like exception text "The non deprecated version of valueToLiteral has not been implemented by this scalar : class org.restheart.graphql.scalars.bsonCoercing.GraphQLBsonBooleanCoercing" or similar, when the Schema has default values defined.

**To Reproduce**
Use the code from the example, it should fail in a similar way.

**Comment by jodeleit-es** [comment]
See https://github.com/SoftInstigate/restheart/issues/483

**Comment by dondonz** [comment]
Hello, thanks for reporting. Yes our documentation needs an overhaul!!

To anyone reading, we always welcome documentation improvements in our documentation repo https://github.com/graphql-java/graphql-java-page. But I don't meant to put the responsibility only on reporters :)

After this next release it's my mission to review all of our documentation and give it the love it deserves. Thanks for letting me know that the scalar page needs work.
