### ISSUE TITLE
Test using other JDK versions?

### ISSUE THREAD

**Issue by yeikel** [graphql-java/graphql-java#3367]
Hi all, 

I noticed that the project is configured to test [using Java 11](https://github.com/graphql-java/graphql-java/blob/master/.github/workflows/master.yml#L20-L22)

Would you support building and testing (no need to release) using other versions? 

In particular, it would be ideal to check that the project works as expected with at least the newer LTS versions (17,21 at the time of this writing), and possibly with the latest Java version if possible (22)

I am open to send a PR with the same if accepted

Thanks!

**Comment by dondonz** [comment]
We do have a PR up from @jord1e with something along the same lines - would their PR meet your requirements?

https://github.com/graphql-java/graphql-java/pull/2789

It is on me to review that PR

**Comment by yeikel** [comment]
> We do have a PR up from @jord1e with something along the same lines - would their PR meet your requirements?
> 
> #2789
> 
> It is on me to review that PR

That one is much more advanced than what I am asking (no wonder is still in review) but if that's planned to be reviewed at some point then that's great. I'll comment on it instead

**Comment by jord1e** [comment]
I updated #2789 and I think we can close this as a duplicate of #2676 (?), please comment on the PR if you have more suggestions

**Comment by yeikel** [comment]
That's fair. Thanks!
