### ISSUE TITLE
GraphQL Query builder support 

### ISSUE THREAD

**Issue by srinivasanraghavan** [graphql-java/graphql-java#337]
Is there a support for bulding a graph query in the client side in graphql-java ..

I wrote a sample builder function some thing like this

	GraphQlObject friends = new GraphQlObject.Builder("friends").addField("id", ScalarTypes.STRING).build();
		GraphQlObject character = new GraphQlObject.Builder("character").addField("id", ScalarTypes.STRING).addField("friends", friends).build();
character.genrateQueryString()) should generate like 

character{id friends{id } }

The above is simple query but the api I wrote an api which  support most of the graphql spec 

I just want to understand does graphql-java supports query generation which would useful in the client side

**Comment by bbakerman** [comment]
No not really.  The problem of client side query generation is not currently handled by this library.  Its concerned with server side schema definition and execution.

**Comment by andimarek** [comment]
I am closing this issue, because we don't have a todo here right now: Like @bbakerman said it is currently out of scope.
