### ISSUE TITLE
Guava Dependency Issue with 21.3

### ISSUE THREAD

**Issue by marchpane** [graphql-java/graphql-java#3374]
Hello everyone,

I'm having difficulties with the latest release (**21.3**) where in file `GraphQLSchema` some dependencies seem to be missing. 

This is how it looks in my Intellij: 
<img width="479" alt="image" src="https://github.com/graphql-java/graphql-java/assets/89104892/73b01f8c-9c25-443c-866a-4909448e79e0">

This could maybe be similar to this older issue: https://github.com/graphql-java/graphql-java/issues/3318

I even set up a completely new Spring / Maven project and only added the dependency below and there is still a mismatch between the files.

```
<dependency>
	<groupId>com.graphql-java</groupId>
	<artifactId>graphql-java</artifactId>
	<version>21.3</version>
</dependency>
```
Is anyone else also experiencing this behavior? If yes, how did you solve it?

The strange thing is that when I downgrade from `21.3` to `21.2` the bytecode and source match and Intellij doesn't complain any more.

**Comment by dondonz** [comment]
The problem in issue #3318 was resolved with https://github.com/graphql-java/graphql-java/pull/3322 and backported to other versions. However the issue wasn't present in v21.x so I am curious to understand what's happening for you. Can you provide an example repo with code that reproduces this error? Then I can have a closer look

**Comment by dondonz** [comment]
Ok good to hear!
