### ISSUE TITLE
String De-Duplication Support

### ISSUE THREAD

**Issue by thalapura-alapurom** [graphql-java/graphql-java#3378]
Hi 

During ExecutableGraphQL generation, it would be better to **deduplicate string,** since it occupied a considerable amount of memory due to duplication of string objects.  

You could see that String alone took **4 MB.**
<img width="663" alt="Screenshot 2023-11-21 at 2 43 21 PM" src="https://github.com/graphql-java/graphql-java/assets/151619887/23fd0b95-d0be-41bc-bf84-74701ad4f684">

Within that due to duplication, the size of single string is around **674KB.**  Took only took 2 object for reference.
<img width="643" alt="Screenshot 2023-11-21 at 2 53 00 PM" src="https://github.com/graphql-java/graphql-java/assets/151619887/49f055eb-22e7-4660-b802-0791abb0fd35">

So we would recommend to optimise this object with string deduplication concept. Also it will be great if the GraphQL object is **serialisable (For compression purpose)**.

**Comment by bbakerman** [comment]
Do you have any more insight on how we are duplicating strings.  I don't undertand what you are showing in that second screen shot.

In general I would assume we mostly just point to string objects created initially from the SDL parse.

eg

```
        builder.name(typeDefinition.getName());

==

    public B name(String name) {
        this.name = name;
        return (B) this;
    }
```

The above is mostly what we do - that is set a pointer to the original string.

So I would love to get insight in where we might be doing `String sCopy = new String(sOriginal.getChars())` say


> Also it will be great if the GraphQL object is serialisable (For compression purpose).

A GraphQL object contains data and code.  So how would the custom code like a registry of DataFetchers be serialized?   Also how does serialisaton related to compression in a memory runtime sense ?

**Comment by balasubramaniam-p** [comment]
Regarding serialisation, if an object is serialisable, I can convert the object into a sequence of characters and store it in a file system. Later we can retrieve the same and deserialise into original object

**Comment by stefanstrat27** [comment]
> Regarding serialisation, if an object is serialisable, I can convert the object into a sequence of characters and store it in a file system. Later we can retrieve the same and deserialise into original object

I'm not 100% sure, but you might be able to store it as a binary file (the Java object itself) rather than a text file (serialized into JSON or something)

**Comment by bbakerman** [comment]
for the record this PR from our friends at Netflix (originally) will help in this regard

https://github.com/graphql-java/graphql-java/pull/3504

**Comment by bbakerman** [comment]
Closing this issue as addressed (somewhat) in the linked PR via v22
