### ISSUE TITLE
Support Object values in NodeBuilder.additionalData

### ISSUE THREAD

**Issue by ooraini** [graphql-java/graphql-java#3379]
I'm using additionalData in `InputValueDefintion` to communicate metadata between code that is generating the schema, and code that implements data fetchers. Initially I used directives which was cumbersome, and since the metadata was not relevant to users of the API it felt like a hack.

I saw the additionalData method from `NodeBuilder`:
```
@PublicApi
public interface NodeBuilder {

    NodeBuilder sourceLocation(SourceLocation sourceLocation);

    NodeBuilder comments(List<Comment> comments);

    NodeBuilder ignoredChars(IgnoredChars ignoredChars);

    NodeBuilder additionalData(Map<String, String> additionalData);

    NodeBuilder additionalData(String key, String value);

}
```

and I started using it, but, it's restricted to String values. I'm not sure why..., Can the signature be relaxed to `Object` values?

**Comment by bbakerman** [comment]
>  it's restricted to String values. 

This was done on purpose - the AST tree once built is meant to be an immutable structure.

If we allow `Map<String,Object>` then additional data will then nominally be a mutable structure.

The work around is to create a parallel data structure that you fill out as you go and key it by the built object say or put a key into the node that points to that parallel data structure.
