### ISSUE TITLE
v21 is released, but documentation is at v20

### ISSUE THREAD

**Issue by eeverman** [graphql-java/graphql-java#3382]
If you go to the documentation page:
https://www.graphql-java.com/documentation/v21/getting-started
there is this warning at the top of the page:

> This is unreleased documentation for GraphQL Java v21 version.
> For up-to-date documentation, see the [latest version](https://www.graphql-java.com/documentation/getting-started) (v20).

Also, this url: https://www.graphql-java.com/documentation/getting-started
redirects to v20 instead of v21.

It [looks like v21 is released](https://www.graphql-java.com/blog/v21-released), so the doc warning and links must be out of date.

**Comment by dondonz** [comment]
Hello, thanks for reporting. I had a look and I'm seeing the same problem that you are

I'll have a look at our documentation config.

Yes v21 is out and is our current version.

**Comment by dondonz** [comment]
Thanks - fixed in our documentation repo https://github.com/graphql-java/graphql-java-page/pull/142
