### ISSUE TITLE
Multiple operations in a single document

### ISSUE THREAD

**Issue by vijethpatil** [graphql-java/graphql-java#339]
When trying to execute multiple operations in a single document, only the first operation is executed as ExecutionContextBuilder here https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/execution/ExecutionContextBuilder.java#L56
picks up the first operation. 
```
{
              query q1 {
                company {
                  listAccounts {
                    edges {
                      node {
                        name
                      }
                    }
                  }
                }
              }
              query q2 {
                company {
                  listAccounts {
                    edges {
                      node {
                        name
                      }
                    }
                  }
                }
              }
      }
```

is my understanding correct?

**Comment by apottere** [comment]
I think this line is really the problem: https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/execution/ExecutionContextBuilder.java#L50

If you have more than one operation in your query, it forces you to pick one to run.  Isn't that a huge breach of the spec?

**Comment by dminkovsky** [comment]
From the current version of the spec:

"When submitting a query document with multiple operations to a GraphQL
service, the name of the desired operation to be executed must also be
provided."

http://facebook.github.io/graphql/#sec-Executing-Operations

I take this to mean that a single operation is executed.

**Comment by dminkovsky** [comment]
There is more in 6.1:

"To execute a request, the executor must have a parsed Document (as defined
in the “Query Language” part of this spec) and a selected operation name to
run if the document defines multiple operations, otherwise the document is
expected to only contain a single operation. " —
http://facebook.github.io/graphql/#sec-Executing-Requests

**Comment by apottere** [comment]
Sorry, my mistake - it looks like that is the correct behavior.  The query in the original comment isn't actually valid.

@vijethpatil if you want to get multiple query results in the same request, you can use something like this instead:
```
{
  q1: company {
    ...
  }
  q2: company {
    ...
  }
}
```

**Comment by dminkovsky** [comment]
No problem! Good to review spec and confirm understanding. Thanks for
posting.

пн, 20 марта 2017 г. в 17:10, Andrew Potter <notifications@github.com>:

**Comment by vijethpatil** [comment]
Thanks @apottere @dminkovsky for clarification. Makes sense to pick the first one if the query(operation) to run isn't specified based on the spec.
