### ISSUE TITLE
Examples of graphql with jersey

### ISSUE THREAD

**Issue by kobbikobb** [graphql-java/graphql-java#340]
Can you provide examples of how you would use this library with jersey?

For example: 
```
@Path("/")
public class GraphQLResource {

    @GET
    @Path("/")
    public Response get() {

        GraphQLObjectType queryType = newObject()
                .name("helloWorldQuery")
                .field(newFieldDefinition()
                        .type(GraphQLString)
                        .name("result")
                        .staticValue("Hello World"))
                .build();

        GraphQLSchema schema = GraphQLSchema.newSchema()
                .query(queryType)
                .build();


        GraphQL graphQL = new GraphQL(schema);

        Object data = graphQL.execute("{result}").getData();
        return Response.ok(data.toString()).build();
    }
}
```

**Comment by bbakerman** [comment]
You can and should return the ExecutionResult object back via Jersey

    ExecutionResult er = graphQL.execute("{result}")
    return Response.ok(er)

The spec says that the reply should have either a "data" attribute
    {
     data : {....}
     }

or an errors attribute

    {
      errors : ....
   }

The ExecutionResult will do that for you

**Comment by bbakerman** [comment]
the spec says nothing about HTTP status code etc.. Its up to you to decide what you want to send back

see: http://facebook.github.io/graphql/#sec-Response

**Comment by dllx** [comment]
There's a little bit more in the "best practices" at http://graphql.org/learn/serving-over-http/, but as you say, not about HTTP status code.

**Comment by bmsantos** [comment]
You should be able to also use GraphQLAsync in something like (not tested):

```
public class Resource {

        @Inject
        private GraphQLAsync graphQL;
       
        @GET
        public void asyncGet(@Suspended final AsyncResponse asyncResponse) {
            graphQL.executeAsync("write query here")
                   .thenApply((result) -> asyncResponse.resume(result));
        }
    }
```

You can see a fully working example in Vert.x [here](https://github.com/bmsantos/vertx-graphql-example/blob/master/graphql-service/src/main/java/com/github/bmsantos/graphql/rest/GraphQLHandler.java#L53).

**Comment by kobbikobb** [comment]
Thank you!

**Comment by jordanglassman** [comment]
If using graphql-java in this way, is it still possible to get access to the underlying servlet classes to, say, do low-level error handling as described here:  https://www.howtographql.com/graphql-java/7-error-handling/, for example, to override `GraphQLServlet#filterGraphQLErrors`?
