### ISSUE TITLE
SimplePerformantInstrumentation tags all Union'd result types instead of concrete resolved type

### ISSUE THREAD

**Issue by alexanderbaumann-toast** [graphql-java/graphql-java#3417]
**Describe the bug**

(This may be an issue with our implementation, but I'm having issues finding where this is happening or solutions in the documentation)

We have implemented `SimplePerformantInstrumentation.instrumentExecutionResult` to tag all resolved types, and then we post the tags to Datadog. This is helpful for us to know which results are being returned from our graph.

But if we have a union of types, then all union'd types are tagged instead of the concrete resolved type.

**To Reproduce**
* Create a union of different types and a query (`union UnionBarBaz = Bar | Baz`)
* Query the union'd type
* See all union'd types are tagged 

<img width="1611" alt="image" src="https://github.com/graphql-java/graphql-java/assets/103513196/e0bab87b-ee65-41c5-bb7f-441e6c769827">

**Comment by bbakerman** [comment]
Yeah so you challenge is this

You are coming in at the end of the processing to tag data and a field has  a union type but fact that the `graphql.schema.TypeResolver` has resolved non concrete types to concrete types has been lost

the only way I see forward for you would be this

* use `graphql.schema.idl.WiringFactory#getTypeResolver(graphql.schema.idl.InterfaceWiringEnvironment)` to provide a type resolve that can record somewhere that the resolved types are - 
* probably put that into `GraphQLContext` - probably under file type + field name say in a map
* Then in your in instrumentResult - look in the `GraphQLContext` for the values you recorded earlier

**Comment by dondonz** [comment]
Hello, hopefully @bbakerman's comment helped resolve your problem. As there wasn't any additional comment I'm closing this issue.
