### ISSUE TITLE
Files not found

### ISSUE THREAD

**Issue by satishrajgure** [graphql-java/graphql-java#342]
I think below files are missing..
graphql.parser.antlr.GraphqlBaseVisitor;
graphql.parser.antlr.GraphqlParser;
graphql.parser.antlr.GraphqlLexer;
graphql.parser.antlr.GraphqlParser;

**Comment by exbe** [comment]
These classes are generated by ANTLR and appear under build/generated-src/antlr/main/graphql/parser/antlr/...
Run `gradle clean build` to get them.

**Comment by andimarek** [comment]
Closing, because nothing to do here. 

@satishrajgure Please reopen or create a new Issue if you still have problems. Thanks!
