### ISSUE TITLE
Copying of extensionDefinitions when generating a new builder

### ISSUE THREAD

**Issue by RoKKim** [graphql-java/graphql-java#3427]
**Describe the bug**
The `graphql.schema.GraphQLSchema#newSchema(graphql.schema.GraphQLSchema)` method does not copy the `graphql.schema.GraphQLSchema.Builder#extensionDefinitions` when generating a new builder from the existing `GraphQLSchema`. Is there a reason for this? Do I need to redefine the extensions when generating a new builder?

An easy fix would probably be:
```java
return new Builder()
        ...
        .extensionDefinitions(existingSchema.getExtensionDefinitions())
        ...
```

**Comment by bbakerman** [comment]
sounds like a bug due to an oversight

**Comment by dondonz** [comment]
Reserving this one!
