### ISSUE TITLE
SchemaPrinter not outputting "extend schema" for extensionDefinitions

### ISSUE THREAD

**Issue by RoKKim** [graphql-java/graphql-java#3428]
**Describe the bug**
When calling `graphql.schema.idl.SchemaPrinter#schemaPrinter` with a schema that has `graphql.schema.GraphQLSchema#extensionDefinitions` defined, I would expect it to print out the "extend schema" string. I would expect the `graphql.schema.idl.SchemaPrinter#schemaPrinter` to:

1. Check if `options.isUseAstDefinitions()` returns `true`.
2. Print "extend schema" for each `out.print(AstPrinter.printAst(extension));`.

Alternatively, is there another method to enable printing of the extensions?

**Comment by dondonz** [comment]
Hello, thanks for reporting, I think this was forgotten about. It should be added to the Schema Printer
