### ISSUE TITLE
Avoid UUID in default ExecutionId implementation

### ISSUE THREAD

**Issue by DanielThomas** [graphql-java/graphql-java#3435]
**Describe the bug**

`UUID` is backed by `SecureRandom` and because of the security sensitive nature of this randomness source, is backed by the blocking `/dev/random`. The default `sun.security.provider.NativePRNG` is also not thread safe, so the call to `engineNextBytes` occurs in a `synchronized` block.

That means in the cases where query concurrency exhausts the available entropy, queries will block on the randomness source, and each other due to the monitor.

**To Reproduce**

Seen in the real world, unclear on the conditions that lead to this being a problem on this host, but it runs upwards of 1k queries per second:

<img width="1175" alt="Screenshot 2024-02-05 at 5 19 01 pm" src="https://github.com/graphql-java/graphql-java/assets/1479220/b0a002cb-f276-45e5-a0b5-a5c7bd0c7439">

A counter, a timestamp mixed with some other source (such as the identityHashCode of the GraphQL instance), etc. may be a better choice to avoid `SecureRandom`.

**Comment by andimarek** [comment]
Thanks a lot for reporting @DanielThomas ... we will look into what we can we do to make the default experience better.

Just to document it for everybody reading this: this is just the default value. You can always set another `ExecutionId` per `ExecutionInput`

**Comment by kilink** [comment]
Note that [spring-graphql](https://github.com/spring-projects/spring-graphql/blob/b727854fa50490eda8c0e19637e93fce222cc5ca/spring-graphql/src/main/java/org/springframework/graphql/ExecutionGraphQlRequest.java#L47-L51) already registers a custom `ExecutionIdProvider` to avoid this issue.

**Comment by bbakerman** [comment]
This has been fixed in the latest version
