### ISSUE TITLE
the Javadoc link cannot be visited

### ISSUE THREAD

**Issue by xiaoCong2014** [graphql-java/graphql-java#348]
in README.md file, the Javadoc link--"http://graphql-java.github.io/graphql-java/"  cannot be visited .

The result page shows "There isn't a GitHub Pages site here. If you're trying to publish one, read the full documentation to learn how to set up GitHub Pages for your repository, organization, or user account.".

**Comment by andimarek** [comment]
reference to the javadoc page is removed now ... we ill provide another form of documentation
