### ISSUE TITLE
Extra curly braces at the end of a query are ignored

### ISSUE THREAD

**Issue by vojtechmasa** [graphql-java/graphql-java#352]
**Current behavior**
If you submit the following query:
`{profile(id:117) {firstNames, lastNames, frontDegree}}}` or `{profile(id:117) {firstNames, lastNames, frontDegree}}}}}}}}}`, the queries are processed as they are syntactically correct.

**Expected behavior**
If you submit the following query:
`{profile(id:117) {firstNames, lastNames, frontDegree}}}` or `{profile(id:117) {firstNames, lastNames, frontDegree}}}}}}}}}`, the queries are rejected - invalid syntax.

**Comment by bbakerman** [comment]
fixed on master
