### ISSUE TITLE
I'm currently working with GraphQL and encountered an issue with the InputMapDefinesTooManyFieldsException. This exception occurs when an undefined field is included in the input variable of a GraphQL mutation.

### ISSUE THREAD

**Issue by shijie-world** [graphql-java/graphql-java#3549]
plaintext
Hello,

I'm currently working with GraphQL and encountered an issue with the InputMapDefinesTooManyFieldsException. This exception occurs when an undefined field is included in the input variable of a GraphQL mutation.

Here's an instance of the problem:

If our input type is defined as:

input BookInput {
  title: String
  author: String
}
And we includes an undefined field like this:
graphql
mutation {
  createBook(input: { title: "My Book", author: "Me", publicationDate: "2022" }) {
    id
  }
}
The InputMapDefinesTooManyFieldsException is thrown as the publicationDate field is not defined for BookInput.
I understand this is designed to help catch errors and avoid issues. However, due to my specific needs, I would like to know if there is a way to cancel, or bypass, this field validation functionality?
I've tried looking through the available configuration settings, documentation, and source code, but I couldn't find anything related to this feature.
Any guidance or suggestions on this would be greatly appreciated.
Thank you.

**Comment by bbakerman** [comment]
There is no way to cancel this exception.  Basically you have provided a literal (which gets translated into a map) that has more fields than the input type defines.

graphql as an API style leans heavily on the type system to ensure enough data is present and correct data is present.

The same thing would happen if you did

```
mutation($variable : BookInput!) {
   createBook(input: $variable) {
      id
}
```

and the variable object had to many attributes.

> However, due to my specific needs

What are you specific needs?  What is you want to achieve ?

**Comment by bbakerman** [comment]
@shijie-world - any chance you could expand on your use case for sending in more fields that specified.   You might well have a valid use (eg migration from old shapes to new shapes)
