### ISSUE TITLE
GraphQLType should allow vendor extensions

### ISSUE THREAD

**Issue by bbakerman** [graphql-java/graphql-java#357]
The base GraphQLType should have a vendor extensions mechanism so consuming tools can add "extra information" to nodes in the graph

I imagine something like

    public interface GraphQLType {

       String getName();

       Map<String,Object> getExtensions()

       <T> T getExtension(String key)

       void putExtension(String key, Object obj);
}

This will allow users to "decorate" the types with extra information BEYOND what the info the graphql execution engine needs to operate

**Comment by bbakerman** [comment]
My inspiration is (amongst other things) Swagger extensions

http://swagger.io/specification/

**Comment by bbakerman** [comment]
Also potentially the directives (in the graphql language) could also be available.  In fact one could argue that directives might be the extra "attributes" to put in place

   query myQuery() {
     field @directive(arg1: "value")
 }

could result in that field having "extensions" with the directive values.

**Comment by andimarek** [comment]
@bbakerman I think it would be interesting how other implementations handle that. Do you have any info about that?

**Comment by bbakerman** [comment]
talking with @andimarek he suggested we optionally link back to the XXDefinition file and hence we will gain the directives inherently via that

With objects that dont come from IDL - then it would be null

**Comment by bbakerman** [comment]
The use of directives and comments and IDL mean this is basicallty redundant
