### ISSUE TITLE
Documentation includes deprecated/dead code

### ISSUE THREAD

**Issue by ataylormays-duetto** [graphql-java/graphql-java#3576]
## Description

https://www.graphql-java.com/documentation/sdl-directives includes the following code:

```
class AuthorisationDirective implements SchemaDirectiveWiring {

    @Override
    public GraphQLFieldDefinition onField(SchemaDirectiveWiringEnvironment<GraphQLFieldDefinition> environment) {
        String targetAuthRole = (String) environment.getDirective().getArgument("role").getValue();

        GraphQLFieldDefinition field = environment.getElement();
        GraphQLFieldsContainer parentType = environment.getFieldsContainer();
        //
        // build a data fetcher that first checks authorisation roles before then calling the original data fetcher
        //
        DataFetcher originalDataFetcher = environment.getCodeRegistry().getDataFetcher(parentType, field);
        DataFetcher authDataFetcher = new DataFetcher() {
            @Override
            public Object get(DataFetchingEnvironment dataFetchingEnvironment) throws Exception {
                Map<String, Object> contextMap = dataFetchingEnvironment.getContext();
                AuthorisationCtx authContext = (AuthorisationCtx) contextMap.get("authContext");

                if (authContext.hasRole(targetAuthRole)) {
                    return originalDataFetcher.get(dataFetchingEnvironment);
                } else {
                    return null;
                }
            }
        };
        //
        // now change the field definition to have the new authorising data fetcher
        environment.getCodeRegistry().dataFetcher(parentType, field, authDataFetcher);
        return field;
    }
}
```

However, `DataFetcher originalDataFetcher = environment.getCodeRegistry().getDataFetcher(parentType, field);` is a deprecated method, which has now been removed in the latest v22 of graphql-java: https://github.com/graphql-java/graphql-java/pull/3514/files.

**Comment by ajkerr** [comment]
I opened a PR at https://github.com/graphql-java/graphql-java-page/pull/160 to address another case of this.

**Comment by dondonz** [comment]
Thanks for reporting!

**Comment by ataylormays-duetto** [comment]
@dondonz are there any code samples out there of how to implement a directive like this (i.e. one that wraps the original data fetcher) that use the latest `GraphQLCodeRegistry` methods, e.g. `public DataFetcher<?> getDataFetcher(GraphQLObjectType parentType, GraphQLFieldDefinition fieldDefinition)`?

**Comment by dondonz** [comment]
Hello thanks for asking. That page of the documentation needs more love, thanks for the suggestion for more code samples.

If you (or someone else reading this) would like to help us write examples feel free to open a PR on the documentation repo https://github.com/graphql-java/graphql-java-page. No pressure of course :)

**Comment by dondonz** [comment]
@ataylormays-duetto thanks for your message, I updated the example to use the newer `GraphQLCodeRegistry` methods. Documentation is deploying now. Here's the PR: https://github.com/graphql-java/graphql-java-page/pull/166
