### ISSUE TITLE
Schema Parser Error when schema contains Federation-specific GraphQL directives (APOLLO)

### ISSUE THREAD

**Issue by shamin2021** [graphql-java/graphql-java#3588]
**Describe the bug**
When parsing schema which contains Federation-specific GraphQL directive '@key' defined by Apollo, through graphql parser, it gets error "DirectiveUndeclaredError"

`typeRegistry = schemaParser.parse(schema);`

The parser sends an error as

`SchemaProblem{errors=['Review' [@17:1] tried to use an undeclared directive 'key']}`

**To Reproduce**
Use the following as schema.graphql file and use graphql.schema.idl.SchemaParser to parse the shema to get typeRegistry

```
type Product {
  inStock: Boolean
  name: String
  price: Int
  reviews: [Review]
  shippingEstimate: Int
  upc: String!
  weight: Int
}

type Query {
  me: User
  productB(upc: String!): Product
  topProducts(first: Int = 5): [Product]
}

type Review @key(fields : "id") {
  body: String
  id: ID!
  product: Product 
}

type User {
  id: ID!
  name: String
  reviews: [Review]
  username: String
}
```

**Comment by dondonz** [comment]
Hello, this error is occurring because the `@key` directive is not a built-in directive. You'll have to define the directive in the schema yourself (or perhaps Apollo can insert it for you).

This is not a bug with graphql-java, this is the intended behaviour.

**Comment by shamin2021** [comment]
Can you please let me know any example on how to get this sorted if possible. TIA

**Comment by bbakerman** [comment]
2 minutes of googling led me to 

https://www.apollographql.com/docs/federation/federated-types/federated-directives/#key

```
directive @key(fields: FieldSet!, resolvable: Boolean = true) repeatable on OBJECT | INTERFACE
```

along with all the other Appollo directives.  You need to declare them in the SDL to use them on types

```
