### ISSUE TITLE
PersistedQuerySupport in graphql-java always returns PersistedQueryNotFound, even for queries that have been executed before

### ISSUE THREAD

**Issue by jellenelis** [graphql-java/graphql-java#3611]
**Describe the bug**
Our backend uses graphql-java and quite recently introduced Apollo Persisted Queries by using ApolloPersistedQuerySupport with an InMemoryPersistedQueryCache. The clients we used did not support this functionality yet, so it was very hard to test.
Today our frontend team implemented this functionality and we see that we get a PersistedQueryNotFound error for every query no matter how many times that specific query was ever executed. When I look into the code, I see that [PersistedQuerySupport](https://github.com/graphql-java/graphql-java/blob/1ebf1a9997e53155a128b7b18c49d80dd401ad6e/src/main/java/graphql/execution/preparsed/persisted/PersistedQuerySupport.java#L50) throws a PersistedQueryNotFound whenever the queryText that is returned by PersistedQueryCache is null or blank. I do not see a code path in which the provided query text ever is persisted, but I obviously might be mistaken.

**To Reproduce**
The ApolloPersistedQuerySupport class is created as found below and is provided when creating the GraphQL object using the preparsedDocumentProvider method.
```
final PreparsedDocumentProvider persistedQuerySupport = new ApolloPersistedQuerySupport(
          InMemoryPersistedQueryCache.newInMemoryPersistedQueryCache().build());
```

If you need any extra information, I am happy to provide that, but currently I do not have a test that tests this except for a manual test. The error we get back is
```
{
    "errors": [
        {
            "message": "PersistedQueryNotFound",
            "locations": [],
            "extensions": {
                "persistedQueryId": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                "generatedBy": "graphql-java",
                "classification": "PersistedQueryNotFound"
            }
        }
    ]
}
```

**Comment by jellenelis** [comment]
Upon further testing, it seems like it eventually is resolved. It seems to take more than one try, though, until the query is persisted, which seems strange in my opinion. 

We had multiple (2) identical instances running, so I could understand a particular query not being persisted for at most two times. However, it took on average five times before the query actually succeeded when only the hash was sent. 

If you have any idea what might cause this, I would be interested to hear. It is not that much of a problem as such, but still seems weird.

**Comment by bbakerman** [comment]
InMemoryPersistedQueryCache only works with a fixed set of PQ ids at build time

your code example said

```
InMemoryPersistedQueryCache.newInMemoryPersistedQueryCache().build()
```

and hence you are building a cache with zero PQs in it.  So it should never load ANY.  This is not a cache that builds up over time.  You said later "it seems like it eventually is resolved. It seems to take more than one try," but that also makes not sense because if you truly built an empty `InMemoryPersistedQueryCache` - then it should NEVER supply any values

**Comment by bbakerman** [comment]
```
        def inMemoryPersistedQueryCache = InMemoryPersistedQueryCache.newInMemoryPersistedQueryCache()
                .addQuery("hash123", "query { oneTwoThree }")
                .addQuery("hash456", "query { fourFiveSix }")
                .build()
```

is how one might make one with entries say

**Comment by jellenelis** [comment]
Hi Brad,

thanks for your answer. I do think it saves actual queries to be honest, [this line](https://github.com/graphql-java/graphql-java/blob/391bccb5f0835125df15a60b24ef4c22dbc548bb/src/main/java/graphql/execution/preparsed/persisted/InMemoryPersistedQueryCache.java#L47) creates a PreparsedDocumentEntry that is then saved in the Map because it is returned as the result of the remapping function given to compute The query is either a query that is present in the ExecutionInput (which would be the case after a cache miss) or a known query.

I see that the InMemoryPersistedQueryCache is not the best option anyway because it will leak memory, so I will rll my own anyway.

Jelle
