### ISSUE TITLE
Add option to toggle token information in ANTLR parser error messages

### ISSUE THREAD

**Issue by dondonz** [graphql-java/graphql-java#3617]
Thanks @ee-usgs for this suggestion.

Let's add a parser option that can toggle on/off ANTLR detailed parser errors, in case somebody prefers to not include offending token information in error messages. 

However, the default behaviour will remain the same as before, as parser error messages with offending token information are very helpful for debugging.

There are 3 parsing messages that can contain token information
* `InvalidSyntax.full`
* `InvalidSyntaxBail.full`
* `InvalidSyntaxMoreTokens.full`

**Comment by ee-usgs** [comment]
Thank you!  This looks great to me - I'd be happy to test a version of it as soon as it is available.
Also, is there any central collection of the configuration options?  I feel like configuration switches like this would be hard to find.

**Comment by dondonz** [comment]
We keep parser config inside the `ParserOptions`, I've got this pull request to address this ticket: https://github.com/graphql-java/graphql-java/pull/3618

We do master build releases so there will be a testable version after this pull request is merged into master

**Comment by dondonz** [comment]
Implemented in #3618

**Comment by ee-usgs** [comment]
Should I be able to configure that with something like this in my application file?
If so, it is not working.

```
graphql:
  path: "/graphql"
  parser:
    ParserOptions:
      redactTokenParserErrorMessages: true
```

**Comment by dondonz** [comment]
Hello may I ask are you using something like Spring for GraphQL with an application.yml configuration file? Or are you using DGS or something else?

If you're using a framework the yml configuration you presented will only work if the framework supports it. Your framework might have a different way to configure `ParserOptions`.

In terms of raw GraphQL Java, the way to set ParserOptions is via the setters in `ParserOptions.java`. https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/parser/ParserOptions.java

**Comment by ee-usgs** [comment]
My apologies - I had forgotten graphql-java was running under an added layer:  I'm using [Micronaut GraphQL Integration](https://micronaut-projects.github.io/micronaut-graphql/latest/guide/).  Their documentation is a bit lacking around some of their configuration points, but incase anyone is looking for it, I ended up creating an implementation of their `GraphQLExecutionInputCustomizer` interface.  The code looks like this:

```java
import graphql.ExecutionInput;
import graphql.parser.ParserOptions;
import io.micronaut.configuration.graphql.GraphQLExecutionInputCustomizer;
import io.micronaut.core.annotation.Nullable;
import io.micronaut.http.HttpRequest;
import io.micronaut.http.MutableHttpResponse;
import jakarta.inject.Singleton;
import org.reactivestreams.Publisher;
import reactor.core.publisher.Mono;

@Singleton
public class DataMeshGraphQLExecutionInputCustomizer implements GraphQLExecutionInputCustomizer {

	@Override
	public Publisher<ExecutionInput> customize(
			ExecutionInput executionInput,
			HttpRequest httpRequest,
			@Nullable MutableHttpResponse<String> httpResponse) {


		// New parser options to specify that tokens that cannot be parsed are not included in parser error messages
		ParserOptions parserOptions = ParserOptions.newParserOptions().redactTokenParserErrorMessages(true).build();
		executionInput.getGraphQLContext().put(ParserOptions.class, parserOptions);

		return Mono.just(executionInput);
	}
}
```
