### ISSUE TITLE
Empty errors array contradicts graphql specification

### ISSUE THREAD

**Issue by kirill-astapov** [graphql-java/graphql-java#3627]
### Discussed in https://github.com/graphql-java/graphql-java/discussions/3626

<div type='discussions-op-text'>

<sup>Originally posted by **kirill-astapov** June 11, 2024</sup>
ExecutionResultImpl returns empty list of errors, but it  contradicts current specification https://spec.graphql.org/October2021/#sec-Errors

The errors entry in the response is a **non-empty list** of errors, where each error is a map</div>

**Comment by dondonz** [comment]
Hello @kirill-astapov can you provide a sample test to demonstrate the problem?

I'd like to understand a situation where we have contradicted the specification. There is a subtle difference between what the Java representation (ExecutionResultImpl) contains and what is ultimately produced in the response as you point to in the specification.

As a related note, it's better to refer to the draft version of the specification, as it's most up to date. Regarding your question the wording for this section is largely the same: https://spec.graphql.org/draft/#sec-Errors

**Comment by bbakerman** [comment]
This is why `graphql.ExecutionResult#toSpecification` exist.

```java
    /**
     * The graphql specification says that result of a call should be a map that follows certain rules on what items
     * should be present.  Certain JSON serializers may or may interpret {@link ExecutionResult} to spec, so this method
     * is provided to produce a map that strictly follows the specification.
     *
     * See : <a href="https://spec.graphql.org/October2021/#sec-Response-Format">https://spec.graphql.org/October2021/#sec-Response-Format</a>
     *
     * @return a map of the result that strictly follows the spec
     */
    Map<String, Object> toSpecification();
```

The ExecutionResultImpl is a Java oriented result value that decided to default the errors to empty list

However the JSON on the wire is what counts.  So a JSON serializer can be written to produce a standards compliant value OR you can to `toSpecfication` and serialize that map which follows the specification.

**Comment by kirill-astapov** [comment]
Got it, thanks for the clarification, we'll use toSpecification() method, since our front library gives an error with an empty array
