### ISSUE TITLE
Improve usefulness of `toString()` method for debug logging an `ExecutionInput`

### ISSUE THREAD

**Issue by oliverlockwood** [graphql-java/graphql-java#3628]
### Describe the bug
The `toString()` implementation in `ExecutionInput` could be a lot more useful for debugging.

### To Reproduce
1. Create an `ExecutionInput`, e.g. one of the two following ways:
   ```java
    ExecutionInput executionInput = ExecutionInput.newExecutionInput(rawQuery).build()
    // or
    ExecutionInput executionInput = ExecutionInput.newExecutionInput()
        .query(query)
        .operationName(operationName)
        .variables(variables)
        .build();
   ```

2. Log it
   ```java
    log.debug("Processing GraphQL query: {}", executionInput);
   ```

3. Look at what you get back
    ```
    Processing GraphQL query: ExecutionInput{query='\n    query(\n        $q: String!,\n        $userId: Int!,\n        $resourceTypes: [String],\n        $tenantId: Int!,\n        $fqlFilter: String\n        ) {\n        suggestions(\n          q: $q\n          userId: $userId\n          resourceTypes: $resourceTypes\n          tenantId: $tenantId,\n          fqlFilter: $fqlFilter\n        ) \n{\n    id,\n    name,\n    created,\n    fileAssetType,\n    placeholder,\n    live,\n    objectType {\n        name,\n        displayName\n    },\n    userDefinedObjectTypeId,\n    assetContext {\n        formatContext {\n            duration,\n            format\n        },\n        videoStreamContexts{frameRate},\n        height,\n        width,\n        imageFormat\n    },\n    fileInformation{\n        mimeType\n    }\n}\n    }', operationName='null', context={}, graphQLContext={}, root=null, rawVariables=graphql.execution.RawVariables@5a43def0, dataLoaderRegistry=graphql.execution.instrumentation.dataloader.DataLoaderDispatcherInstrumentationState$1@1819fea9, executionId= null, locale= en_US}
    ```

The problem I have is that `rawVariables` is logged as `graphql.execution.RawVariables@5a43def0`, which doesn't help much!

### Proposal
I am happy to raise a PR to solve this.  I can see two possible approaches:
1. Update the `ExecutionInput.toString()` method in https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/ExecutionInput.java#L169-L182 so that it logs `rawVariables` as `rawVariables.toMap()`, instead.
2. Implement a new `RawVariables.toString()` method which provides its information by returning `toMap().toString()` or similar.

I lean towards option (2) but I am happy to be guided by your preference.
Many thanks.

**Comment by dondonz** [comment]
Hello, thanks for opening the issue. That's an oversight 😄 we should have a `toString()` method in `RawVariables`, and for its counterpart, `CoercedVariables` as well.

If you'd like to open a PR you are very welcome to! As you say it's better to have the method inside the class itself rather than something which uses it like `ExecutionInput`. Inside both `RawVariables` and `CoercedVariables` is an `ImmutableMapWithNullValues`, and this does have a `toString` method, which you can make use of.

**Comment by oliverlockwood** [comment]
Thanks @dondonz.  PR #3629 now raised and ready for review.

**Comment by dondonz** [comment]
Thanks so much for reporting and the quick PR!
