### ISSUE TITLE
Newly introduced GraphQL stream feature doesn't work

### ISSUE THREAD

**Issue by Yevhenii-Kozlovskyi1** [graphql-java/graphql-java#3645]
**Describe the bug**
I tried the newly introduced `defer` and `stream` features in the 22.0 release and it seems that the `stream` feature has not been implemented yet meanwhile it is mentioned in the release description. Could you please accept that the feature is still in the development stage or advise how this feature could be used?

**To Reproduce**

Add `@stream` directive to your schema and append this directive to any collection field.

**Comment by dondonz** [comment]
Hello, we have not implemented `@stream` yet. 

In the [22.0 release notes](https://github.com/graphql-java/graphql-java/releases/tag/v22.0) we have specifically called this out:
> At this stage we have not yet supported @stream but this is likely to be included in a future release.

We would like to implement it but there's no concrete timeline for it yet, we are still polishing the `@defer` implementation at the moment.

**Comment by Yevhenii-Kozlovskyi1** [comment]
I see, thanks for the explanation.
