### ISSUE TITLE
Use lambda when possible?

### ISSUE THREAD

**Issue by Jimexist** [graphql-java/graphql-java#366]
I can tell that my IntelliJ (gently) warns me of places where anonymous class could be replaced by lambdas, and it can convert all of them in one pass.

I would help to do it but I don't think it's a clear cut that lambdas are better in terms of code readability (works for me, but it depends on many other cases).

So what do you think?

**Comment by andimarek** [comment]
I am not sure about such a brute force method: Using the diamond operator for example was straight forward, but as you said: it is not always clear that you should use a lambda, even if it is possible.

**Comment by bbakerman** [comment]
I used to think that explicit inner classes was a good thing but as I worked more on Java8 code bases it became obvious that it wasn't needed very often and Lambdas tended to be quite clear.

So I would tend to prefer Lambdas unless it introduces exceptionally bad clarity (which is a judgment call I appreciate)

**Comment by Jimexist** [comment]
i could create a PR and let's see what's changed? @andimarek @bbakerman

**Comment by Jimexist** [comment]
https://github.com/graphql-java/graphql-java/pull/383
