### ISSUE TITLE
Invalid location is used inside GraphQL error

### ISSUE THREAD

**Issue by IvanGoncharov** [graphql-java/graphql-java#3661]
**Describe the bug**
Per GraphQL spec, the error location should only be specified IF it can point to a valid location (i.e., starting with a positive column/row).
https://spec.graphql.org/draft/#sel-GAPHRPFCCaCGX5zM

This value was returned:
https://github.com/graphql-java/graphql-java/blob/ee32161909b10a80659aa5d8e7495f07519026d1/src/main/java/graphql/language/SourceLocation.java#L17
It is assigned here:
https://github.com/graphql-java/graphql-java/blob/ee32161909b10a80659aa5d8e7495f07519026d1/src/main/java/graphql/parser/ExtendedBailStrategy.java#L72

**To Reproduce**
I don't have a Java environment on my machine, so I can't test it myself :(

**Comment by dondonz** [comment]
Hello, thanks for opening the issue!

To help me understand, was there a particular situation that triggered an empty source location for you? For example did you send a regular query and it came back with a negative source location?

**Comment by IvanGoncharov** [comment]
@dondonz Sadly, I don't have reproduction.
This issue was reported as part of: https://github.com/apollographql/router
Customer reported they used `graphql-java` and got `{ line: -1, column: -1 }` returned inside subgraph error.
I implemented workaround inside router: https://github.com/apollographql/router/pull/5633
But I don't have any other details so sadly I can't explain how it was triggered.

**Comment by dondonz** [comment]
In case you saw it, was the problem with the JSON response containing an error with negative numbers, or if it was the Java object directly? (or both?)

Thinking out loud, if the issue is only about the JSON response there's an option to change the serialization method

**Comment by bbakerman** [comment]
Yeah as you say in above we return a non null "EMPTY" object when the parser has an error and it can find the token that offended (maybe end of stream say or some other parsing problem without a location).

**Comment by bbakerman** [comment]
The spec says


> If an error can be associated to a particular point in the requested GraphQL document, it should contain an entry with the key locations with a list of locations, where each location is a map with the keys line and column, both positive numbers starting from 1 which describe the beginning of an associated syntax element.

So one could infer that we should NOT put in an entry for this situation.  Mind you it does not state we MUST not that but that we SHOULD if we can.

We could perhaps fix this as `toSpecification` time and remove error locations that are EMPTY.
