### ISSUE TITLE
Query caching example in documentation version 22 is incorrect - has getDocument implemenation but v22 has getDocumentAsync in getDocumentAsync

### ISSUE THREAD

**Issue by manishtulsiani** [graphql-java/graphql-java#3663]
**Describe the bug**
Hi, graphql-java team. Firstly, thanks for the great library that we are using via spring-graphql. We recently updated from spring-boot 3.1.x to 3.3.1 which upgraded the graphql-java from 21 to 22.

The query caching example in the documentation is still showing an implementation of [getDocument](https://www.graphql-java.com/documentation/execution#query-caching) but v22 of graph-java does not have this method in the interface. It has [getDocumentAsync](https://github.com/graphql-java/graphql-java/blob/v22.0/src/main/java/graphql/execution/preparsed/PreparsedDocumentProvider.java#L27)

The documentation needs to be updated.

Thank you.

**To Reproduce**
NA

**Comment by manishtulsiani** [comment]
Closing as there is already an open [pr](https://github.com/graphql-java/graphql-java-page/pull/160) to address this.

**Comment by dondonz** [comment]
Thanks for reporting.
