### ISSUE TITLE
`GraphqlIDCoercing` should implement `Coercing<String, String>`.

### ISSUE THREAD

**Issue by Plygon** [graphql-java/graphql-java#3682]
Currently, `GraphqlIDCoercing` implements `Coercing<Object, Object>`. However, every method is guaranteed to return a `String`. If we need to use the results of its methods, we need to cast them back to `String`.

Can this class be updated so that
- `parseValue`, `serialize`, and `parseLiteral` return `String` instead of `Object`?
- `valueToLiteral` returns `StringValue` instead of `Value<?>`?

**Comment by bbakerman** [comment]
https://spec.graphql.org/October2021/#sec-ID

Technically it should be `Coercing<Object, String>` - the spec says graphql is "agnostic to ID format, and serializes to string to ensure consistency across many formats"

So it must serialise to String but it can be any input object.

The real challenge here is this `Coercing` has been in place for so long that its hard to say its worth the risk of breaking someone to be a little nicer.  I agree it would be "nicer" but what would we break?

I am not sure the juice is worth the squeeze
