### ISSUE TITLE
Any recommended linter for the scheme checks?

### ISSUE THREAD

**Issue by chenrui333** [graphql-java/graphql-java#3694]
Ran into some MisplacedDirective issue today, but underlying it is because we have mixed graphql implementations (graphql-js call graphql-java, it is a long story), I am just curious if there is linter tool that I can use to prevent it from happening again?

Also I saw this project, https://github.com/graphql-java/graphql-linalyzer, but the last commit was 6 years ago, I guess it is dead? 

Many thanks!

**Comment by dondonz** [comment]
Hello, could you provide a small sample of what you meant by MisplacedDirective? For example if you can provide a short schema example, that would help me understand better. Perhaps there's a missing validation that we can add here

The library you linked to isn't actively maintained anymore, but perhaps there's something to add to this repo.
