### ISSUE TITLE
A schema MUST have a query operation defined.

### ISSUE THREAD

**Issue by esfomeado** [graphql-java/graphql-java#3698]
**Describe the bug**
I´m using Spring GraphQL and I have a schema with two files.

One file contains a simple type and the other contains a subscription. I don´t have any queries or mutations so not sure why it requires me to have a query defined.

**To Reproduce**
Create a Spring GraphQL application with two schemas. One containing one type and another containing a subscription.

**Comment by esfomeado** [comment]
Thanks, but I don´t see why is required at all.

I will have to create a random query to make it work.

Thanks

**Comment by bbakerman** [comment]
> Thanks, but I don´t see why is required at all.

It is like this because the graphql specification requires it - so yeah a dummy query field is required.

I am sympathetic but this is how its specified so this is how we run our engine
