### ISSUE TITLE
Asynchronous DataFetcher?

### ISSUE THREAD

**Issue by ybayk** [graphql-java/graphql-java#37]
~~Please consider adding support of Future return type for DataFetcher API.~~
Actually scratched that. We just noticed it is possible to provide a custom executor service per fetcher. But it will still block for each fetcher.
Is it actually possible to go async all the way?  
1) Across all fetchers
2) Make top level graphql execute() async as well.

**Comment by tberman** [comment]
I have an implementation of an ExecutionStrategy that uses rxjava that I will be publishing as open source soon.

**Comment by yurgis2** [comment]
That would be exactly what we are looking for. Any hint on how soon? :)

**Comment by tberman** [comment]
https://github.com/nfl/graphql-rxjava is available now, readme coming soon, and trying to get it put into central ASAP

**Comment by akhahaha** [comment]
I would also like to second @ybayk's request to go async all the way (via fetchers and execute()). @tberman's work-around still leaves something to be desired.

I'm new to GraphQL and have only looked at this Java implementation thus far, but it seems to me that this would more closely follow the Javascript specification, which states that [ExecutionResults should be returned via a promise](http://graphql.org/docs/api-reference-execution/).

If others agree with this sentiment, I'd be happy to start working or collaborate on a pull request to make this happen.

**Comment by akhahaha** [comment]
@dminkovsky I'd integrate some sort of callback interface as the primary method of returning data from execute() and fetchers.

Query executions would probably end up looking something like this:
```
new GraphQL(schema).execute("{hello}", new GraphQLCallback() {
            @Override
            public void onComplete(ExecutionResult result) {
                // Handle result
            }
        });
```

and the DataFetcher interface would need to change to:
```
public interface DataFetcher {
    Object get(DataFetchingEnvironment var1, DataFetchCallback callback);
}

// Sample async DataFetcher
new DataFetcher() {
    @Override
    public Object get(DataFetchingEnvironment environment, DataFetchCallback callback) {
        // Start async operation with callback, such as web or DB lookup
       async(new AsyncCallback() {
           @Override
           public void onComplete(Object result) {
               // Return value to ExecutionStrategy via callback to be collated
               callback.onComplete(value);
           }
       });
    }
};
```

This implementation seems simple enough, although it does have the slight problem of requiring the callback to be manually called, and I'm not sure how to enforce that at the moment.

As for the callback interfaces themselves, I imagine a few simple classes would suffice, although I'm sure we can also use a more established callback library such as JDeferred (actual Promise functionality).

**Comment by IamCornholio** [comment]
That would mean the original get() method would have to be deprecated. Why not add the callback reference to the environment? That way one can add a separate handling mechanism for the when the callback has been set in the environment.

**Comment by akhahaha** [comment]
You have a good point: we shouldn't be deprecating methods lightly.

It seems to me that in order to avoid deprecating the get() method, the ExecutionStrategy must decide to either wait for the DataFetchCallback or process the serial return value of get(). One workaround for this ambiguous situation would be to create a separate AsyncExecutionStrategy and perhaps an executeAsync() function to handle the callback methods. The drawbacks to this would be some likely code duplication, at the very least.

My point also remains that per GraphQL-JS specification, the library should be async capable by default, and callbacks of some sort are the way to go about this. Perhaps the best solution for something this drastic would be to break backwards compatibility and push it out as v3.0.0?

**Comment by hepin1989** [comment]
Go with CompletableFuture ,Task,Source or something else that compose,no callback.
eg:

AsyncDataFeture{
  Source<T> get(..);
}

**Comment by akhahaha** [comment]
@hepin1989 I was looking at CompletableFutures as well, although I haven't personally used it before. It does seem to have the potential of being more elegant than simple callbacks. Does it address @IamCornholio's concern about backwards compatibility though?

**Comment by IamCornholio** [comment]
The file ExecutorServiceExecutionStrategy seems to be doing a bit already..

**Comment by akhahaha** [comment]
@IamCornholio what do you mean?

**Comment by IamCornholio** [comment]
I mean that this code seems to be using futures already and I wondered if that essentially represents the AyncExecutionStrategy that you were talking about:

```
Map<String, Future<ExecutionResult>> futures = new LinkedHashMap<String, Future<ExecutionResult>>();
for (String fieldName : fields.keySet()) {
	final List<Field> fieldList = fields.get(fieldName);
	Callable<ExecutionResult> resolveField = new Callable<ExecutionResult>() {
		@Override
		public ExecutionResult call() throws Exception {
			return resolveField(executionContext, parentType, source, fieldList);

		}
	};
	futures.put(fieldName, executorService.submit(resolveField));
}
try {
	Map<String, Object> results = new LinkedHashMap<String, Object>();
	for (String fieldName : futures.keySet()) {
		ExecutionResult executionResult = futures.get(fieldName).get();

		results.put(fieldName, executionResult != null ? executionResult.getData() : null);
	}
```

This code is in that file ExecutorServiceExecutionStrategy.

**Comment by akhahaha** [comment]
@IamCornholio Ah gotcha. From what I can tell, that particular ExecutionStrategy is used to [parallelize field resolution](https://github.com/graphql-java/graphql-java#execution-strategies) to speed up execution and is not related to the asynchronous functionality I'm looking to enable here.

**Comment by hepin1989** [comment]
I fact I am doing the parallelism thing currently ,I am going to be with https://github.com/monixio/monix and https://github.com/akka/akka/.
We should use something that monadic as the return type.just as what sangria choose scala's Future.

**Comment by hepin1989** [comment]
Another option is go with reactor project,then we could using https://github.com/reactor/reactor-core/blob/master/src/main/java/reactor/core/publisher/Mono.java.

**Comment by akhahaha** [comment]
@hepin1989 Yes I think I agree with you after studying up on CompletableFutures.

I've completed a working conversion on [my fork](https://github.com/akhahaha/graphql-java). execute() and fetchers now return CompletableFuture promises. I haven't edited the Groovy tests yet, but it seems to be playing nice with Firebase callbacks as well as static information.

This will deprecate almost everything, so I'd like more input before making the pull request.

**Comment by hepin1989** [comment]
@akhahaha 
1. scatter and gather pattern,java.util.concurrent.CompletableFuture#allOf
2. id depends,for field read,no needed,for method invoking yes,maybe another executor too.
3. it's monad,it compose,don't worry.

but I think I will try another way,make use of akka,to do further batching.

**Comment by dminkovsky** [comment]
Hey everyone,

I'm away for a few days and looking forward to catching up on this. Thanks for the PR.

**Comment by dminkovsky** [comment]
Just took a look over this PR. Thank you again for it!

I don't fundamentally understand why this library itself behave asynchronously. For example, if the library is taken as is, and user wants to make `#execute()` return a `CompletableFuture`, instead of changing this implementation, why not just wrap `#execute()` in something that creates and returns the future? That "something" can then complete the future whenever the query is resolved?

**Comment by dminkovsky** [comment]
Perhaps such a wrapper could be called `GraphQL#executeAsync()`, in the spirit of Bluebird promisification? That way we'll have APIs that are both sync and async.

**Comment by akhahaha** [comment]
How would the future be resolved from asynchronous operations within custom DataFetchers in this case?

**Comment by akhahaha** [comment]
Also, I could be wrong in my understanding of the implementation, but aren't DataFetchers at the moment required to return the various pre-defined GraphQL types?

**Comment by dminkovsky** [comment]
The data fetchers would work the same. All that changes is the addition of this top-level wrapper and its other overloads:

```
public CompletableFuture<ExecutionResult> executeAsync(String query) {
  return CompletableFuture.supplyAsync(() -> {
      return GraphQL.execute(query)
  })
}
```

If you want to parallelize field resolution, you [use the executor service](https://github.com/graphql-java/graphql-java/issues/37#issuecomment-245160142).

Then again, this wrapper is so simple, and it forces JDK 6 to JDK 8, that I'm not sure it's necessary.

**Comment by dminkovsky** [comment]
> Also, I could be wrong in my understanding of the implementation, but aren't DataFetchers at the moment required to return the various built-in GraphQL Scalars types (or GraphQL objects/maps/models built from said types)?

Yeah, they need return values that can be coerced or the resolution fails.

**Comment by akhahaha** [comment]
I think we may have our interpretations of what async entails. For my requirements, I wish to implement a DataFetcher that needs to perform a database lookup (Firebase, in this case). This database call is made asynchronously and is returned via callback, like follow:

```
DataFetcher userFetcher = new DataFetcher() {
        @Override
        public Object get(DataFetchingEnvironment environment) {
            CompletableFuture<Object> promise = new CompletableFuture<>();
            users.orderByChild("id").equalTo("10154006247769055").addListenerForSingleValueEvent(new ValueEventListener() {
                @Override
                public void onDataChange(DataSnapshot dataSnapshot) {
                    User result = dataSnapshot.child("10154006247769055").getValue(User.class);
                    promise.complete(result);
                }

                @Override
                public void onCancelled(DatabaseError databaseError) {

                }
            });

            return promise;
        }
    };
```

If I block for the result and return the User result directly, it succeeds. However, I would like to receive the ExecutionResult only when this (and all other) asynchronous DataFetchers resolve without blocking.

And after writing all this, I realize that I can use blocking DataFetchers and simply run the execute() in another thread, so I finally see how wrapping the entire thing would work.

I still wonder if async behavior shouldn't be default, again pointing back to the JS implementation.

**Comment by dminkovsky** [comment]
> If I block for the result and return the User result directly, it succeeds. I would like to receive the ExecutionResult only when this (and all other) asynchronous DataFetchers resolve without blocking.

I came to Java from JS and I think that trajectory causes me to think this way as well. But I'm not sure there's any reason not to block here, especially with the executor service-based strategy. Each data fetcher might as well just block and resolve synchronously.

I mean the beautiful thing about Java is that you can block! And there are so many beautiful, clean, synchronous blocking APIs out there (Kafka an [Kafka Streams](http://docs.confluent.io/3.0.0/streams/), for example), it makes me dread the whole ["What Color is Your Function?"](http://journal.stuffwithstuff.com/2015/02/01/what-color-is-your-function/) JS experience. 

> I still wonder if async behavior shouldn't be default, again pointing back to the JS implementation.

I'm a huge proponent of having this implementation look and feel as much like the reference JS implementation as possible. But here we have a great JVM feature (first-class threads; the ability to write clean simple functions), that I think it makes sense to deviate and use this JVM feature.

**Comment by hepin1989** [comment]
I am currently using monix and akka,to do the same thing too,but I think you could wrap around the original datafetcher too.in case that for the `FieldDataFetcher` or `MethodDataFetcher` which do things simple we should not enforce a async boundary but evaluate it now ,and we should think about the blocking datafetcher too,which we may need a dedicated thread pool.

the real parallelism used in production need more than this.What I am doing now is:
1. totally asynchronous  from the ground up.
2. auto batching and grouping
3. auto parallelism
4. duplicate

you could read the paper of facebook's haxl,it's really helpful.

a wrapping at the `GraphQL.execute()` will have no help for the RT.

**Comment by hepin1989** [comment]
@akhahaha how about a new `AsyncExecutionStrategy` with a new method `executeAsync`,eg:
```java
    public Task<ExecutionResult> executeAsync(final ExecutionContext executionContext,
                                              final GraphQLObjectType parentType,
                                              final Object source,
                                              final Map<String, List<Field>> fields,
                                              final OperationDefinition operationDefinition){...}
```

**Comment by akhahaha** [comment]
> But I'm not sure there's any reason not to block here, especially with the executor service-based strategy. Each data fetcher might as well just block and resolve synchronously.

@dminkovsky I think I'm seeing the light now. It took a while to see how the ExecutorService parallelism, blocking DataFetchers, and an async wrapper can be combined to achieve the equivalent result for async operations. Perhaps a short tutorial about this in the README might be in order?

Feel free to reject the pull request. It was a fun exercise, if nothing else.

> how about a new AsyncExecutionStrategy with a new method executeAsync,eg:
@hepin1989 It seems to be superfluous now, all things considered.

**Comment by hepin1989** [comment]
@akhahaha Asynchronous operation which lazy evaluate will reduce the unnecessary asynchronous boundary,and enable future auto optimization,even `CompletableFuture` which is an eager one,may not fit for the unlimited optimization,for simple usage,the ExecutorService should be enough.

**Comment by oexza** [comment]
re-echoing @hepin1989 's [comment](https://github.com/graphql-java/graphql-java/issues/37#issuecomment-245836615) the real benefit of asynchronous data fetchers is the ability to use custom thread pools/executionContext. Lets say we have a simplistic data fetcher that uploads a file to some file service,

`DataFetcher fileUploadFetcher = new DataFetcher() {
		
		@Override
		public CompletionStage<Object> get(DataFetchingEnvironment env) {
			
			final GraphQLContext context = (GraphQLContext) env.getSource();

			CompletionStage<String>  uploadedFileUrlPromise = CompletableFuture.supplyAsync(() -> {
                 final Optional<String> urlOption = Optional.ofNullable(fileUploadService.upload(context.getRequest().getFile("file")));
                 if(urlOption.isPresent())
                       return urlOption.get();
                 else{
                       return null;
                  }
                 }, MyExecutorProvider.fileUploadPool);
	         return uploadedFileUrlPromise;
		}
	};`
the upload routine which is a long running operation, will run in  MyExecutorProvider.fileUploadPool which is configured and tuned specifically for this purpose. This kind of execution isolation is for me the biggest benefit of non blocking fetchers.

**Comment by dminkovsky** [comment]
@akhahaha I am sorry about my delayed responses. I am glad to hear it and am glad that my suggestion makes sense. I wasn't sure whether I was addressing your question, but I think we are on the same page. Yes—we definitely want to improve the docs wherever possible. Where in the README do you think adding this would have greatest impact?

@hepin1989 @oexza I am not sure I understand why the [executor service strategy](https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/execution/ExecutorServiceExecutionStrategy.java) doesn't provided the flexibility you are looking for. Can't you still use your own thread pool / executor service in the data fetchers as they currently are?

I should also emphasize that Java 6 compatibility is an important goal for this project that we are seeking to maintain for as long as possible. We have Java 6 users running this in production, and that is pretty cool in my opinion!

**Comment by dminkovsky** [comment]
@hepin1989 by the way, if you are using Akka/Scala, have you checked out [Sangria](https://github.com/sangria-graphql)?

**Comment by hepin1989** [comment]
@dminkovsky Yes,thanks,but I implement it my self:)you know ,close source project,have much adoption.GraphQL is used at `taobao.com` for all the content service.

**Comment by aschrijver** [comment]
Maybe this project should get an official branch with Java 8 and async-all-the-way targeted for a future 3.0.0 release. And an additional roadmap document.

**Comment by dminkovsky** [comment]
So I've spent the past few weeks attempting to enlighten myself on this issue. Here's what I've found:

At this time, there are too many disparate async libraries/mechanisms in the Java world for this library to adopt one particular approach. The JS implementation is simple: there are no types, and @leeb just tests results for `.then()` to determine if the result is a Promise. Very simple! 

But no such thing in Java. Before Java 8 you had RxJava `Observable` and Netty's `ChannelPromise`. Now Java 8 adds another mechanism: `CompletionStage/CompletableFuture`. There are all different, and to me it doesn't make sense to bake any of them into this library as the canonical way to be async. 

Can we just have execution strategies for each of these? @pcarrier has one for RxJava; @akhahaha showed how one could be written for `CompletionStage/CompletableFuture`.

**Comment by aschrijver** [comment]
Yes, that's an issue. I am working with Vert.x, yet another way to go asynchronously. In Vert.x the fetchers should be async as well. I am looking into using the above async branch, but with a Vert.x implementation of CompletableFuture.

Maybe the project could be improved to facilitate various extensions more easily (have a more defined SPI). Maybe support the most basic callback handler overloads (similar to described above).
Then extension projects can build on top of it.

(Talking about extension: IMO the Relay code should be pushed out to an extension as well. It's just one client library. I intend to switch to Apollo Client, and no special node/edge server schema needed)

**Comment by dminkovsky** [comment]
> Maybe the project could be improved to facilitate various extensions more easily

So my conclusion has been that extending ExecutionStrategy is simple enough. You have to implement `execute()` and you'll probably have to override `resolveField`, but between those two methods I think you can make anything happen. That's my opinion anyway.

**Comment by benhead** [comment]
Perhaps someone should add "Coming soon" to the "Asynchronous resolvers" section of [this page](http://graphql.org/learn/execution/) on the official docs? It seems to be saying that this capability is baked into GraphQL. Especially that last line...

> During execution, GraphQL will wait for Promises, Futures, and Tasks to complete before continuing and will do so with optimal concurrency.

**Comment by dminkovsky** [comment]
@benhead thanks for your post. [That page](http://graphql.org/learn/execution/) is about the reference, JS implementation. The asynchronous execution strategy I am working on uses Java 8's `CompletableFuture` interface...

...which I just [PR-ed](https://github.com/graphql-java/graphql-java/pull/242). If anyone is interested in this, please comment there.

**Comment by marcelalburg** [comment]
I found https://github.com/karthicks/graphql-java-async and it offers an non blocking (for vertx) possibility to fetch data from remote/slow systems in a async way. Maybe you can take a look and it fullfill all your needs. It wraps graphql-java and based on it.

**Comment by andimarek** [comment]
We will finally try to tackle this issue in the next release. See #283

**Comment by hepin1989** [comment]
Yes, Go For Async, and we could rebuild the sync from the Async again.

**Comment by andimarek** [comment]
I am closing this issue: the issue will be handled in #324
