### ISSUE TITLE
Explicitly setting field with a default value to null sets it to default value instead of null

### ISSUE THREAD

**Issue by piotrblasiak** [graphql-java/graphql-java#3708]
If you explicitly set a variable to null, and that variable has a default value like this query:

`myQuery(deleted: Boolean = false)`

and you call

`myQuery(deleted: null)`

environmeng.getArgument("deleted") still returns false, instead of null.

1) Is this a bug, or have I misunderstood the graphql spec?
2) Is there any way to make it return null instead?

**Comment by bbakerman** [comment]
Thanks for reporting - this is an area where historically there was a lot of confusion both in implementation and in specification.

I don't have an immediate answer but I will talk to @andimarek and @dondonz on this to get a confirmed answer

**Comment by bbakerman** [comment]
Can I asked you to confirm the example above.

is "myQuery" here actually a field as in

```
type Query {
    myQuery(deleted: Boolean = false) : String
}
```

or is it an query operation as in

```
query myQuery(deleted: Boolean = false) {
   someField($deleted)
}
```

This is important just to make sure we are replicating the same problem

**Comment by piotrblasiak** [comment]
@bbakerman first one

**Comment by bbakerman** [comment]
I made this PR with extra test cases for what I think you are reporting as a bug.  But its working as expected

https://github.com/graphql-java/graphql-java/pull/3709

please have a look at the cases and makes sure we are talking about the same conditions.

If you can can you make a reproduction case showing this happening.  Please show the graphql-java version, the SDL schema used and the query operation and variable values.

**Comment by piotrblasiak** [comment]
Looks like we´re talking about the same thing, and this is not what I experience so I will create a reproduction case.

**Comment by piotrblasiak** [comment]
Massive apologies. The bug was not in graphql-java, but in react relay compiler that simply removes arguments that are set to null(!). I should have created a reproduction case to start with. Sorry for wasting your time. Please let me know if I can donate in some way.

**Comment by bbakerman** [comment]
No problems - thanks for getting back to us
