### ISSUE TITLE
Add totalCount field in Connection

### ISSUE THREAD

**Issue by yinan-liu** [graphql-java/graphql-java#372]
It would be nice to have a totalCount field in Connection to explicitly tell the totalCount number of result returned by the query, this information is very useful for UI. This field is also asked in graphql spec along with pageinfo and edges.

It seems we can add custom fields in the connection in Relay.java (release 2.2.0)

`public GraphQLObjectType connectionType(String name, GraphQLObjectType edgeType, List<GraphQLFieldDefinition> connectionFields) {`

Does it mean that I can extends the Connection.java to have this totalCount field, and add accordingly a new field definition the above method ?

please advise

**Comment by yinan-liu** [comment]
found a way to do the same.

**Comment by heruan** [comment]
@yinan-liu Can you please show how you added `totalCount`? I'm also interested on this and I can't find a way.

**Comment by greenled** [comment]
@yinan-liu please could you talk about the way you found?

**Comment by zhleonix** [comment]
If you are using SPQR, an example can be found at https://github.com/leangen/graphql-spqr/blob/master/src/test/java/io/leangen/graphql/RelayTest.java

**Comment by pongpanot-t** [comment]
I resolve by creating the MyConnection interface and extend Relay's Connection.
