### ISSUE TITLE
 File ExecuteObjectInstrumentationContextAdapter is empty

### ISSUE THREAD

**Issue by fedinskiy** [graphql-java/graphql-java#3730]
The sources (https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/execution/instrumentation/adapters/ExecuteObjectInstrumentationContextAdapter.java) were removed in https://github.com/graphql-java/graphql-java/pull/3460, but the file remained (probably due to conflict resolution).

**Comment by bbakerman** [comment]
Thanks for reporting this

https://github.com/graphql-java/graphql-java/pull/3732
