### ISSUE TITLE
Missing import in Hello World

### ISSUE THREAD

**Issue by ronaldborman** [graphql-java/graphql-java#374]
I've just started with graphql-java. The first thing I did was trying to execute the Hello World example on README.md.  However, I noticed that the following import is missing:

`import graphql.GraphQL;`

**Comment by andimarek** [comment]
@ronaldborman Thanks for reporting it.

Would you mind creating a PR? That would be great.. thanks!

**Comment by ronaldborman** [comment]
Sure, no problem. See pull request 375.

**Comment by andimarek** [comment]
merged PR
