### ISSUE TITLE
To achieve graphql mutation

### ISSUE THREAD

**Issue by Noyalcitrus** [graphql-java/graphql-java#379]
How to achieve graphql mutation using spring boot. I have already implemented the query type schema with postgres database(jpa) and its working fine. I want to know how to create mutation type schema postgres database(jpa)
Plz help me in this

**Comment by bbakerman** [comment]
In essence you need to have a type that takes arguments and a data fetcher that causes an mutation to you data store via jpa.

I am not going to go into how to make a JPA update.  How you wire your mutating data fetchers together is up to you.

I realised the data readme is sparse in terms of mutation examples and hence I have expanded it

https://github.com/graphql-java/graphql-java/pull/394

    new DataFetcher() {
            @Override
            public Review get(DataFetchingEnvironment environment) {
                Episode episode = environment.getArgument("episode");
                ReviewInput review = environment.getArgument("review");

                // make a call to your store to mutate your database
                Review updatedReview = reviewStore().update(episode, review);

                // this returns a new view of the data
                return updatedReview;
            }
        }

In the example above you need to get your JPA store and make updates based in input arguments
