### ISSUE TITLE
Allow a graphql schema file to be turned into a runnable schema

### ISSUE THREAD

**Issue by bbakerman** [graphql-java/graphql-java#381]
The base graphql library should be able to read graphql schema files.

It has the ability to parse them already but it cant turn "definitions" into actual runtime object types.

I propose we have the ability to compile a graphql schema file and generate it into runnable schema with data fetchers and type resolvers.

**Comment by stevehu** [comment]
@bbakerman @andimarek When do you think 3.0.0 will be released? As this is an added on feature, it is possible to release it with 2.5.0? Thanks.

**Comment by andimarek** [comment]
@stevehu There will be no 2.5.0: We are already using Java 8 and did other breaking changes on `master`, so there can't be a 2.5.0. You have to wait for 3.0.0, sorry.

Cheers,
Andi

**Comment by andimarek** [comment]
This is solved by #386 and will be included in 3.0.0
