### ISSUE TITLE
can't use typereference as possibleType in uniontype

### ISSUE THREAD

**Issue by jauco** [graphql-java/graphql-java#382]
A uniontype accepts only ObjectTypes as argument for possibleType. Not a TypeReference.

```java
        newUnionType()
          .possibleType(newObject().build()) //Works
          .possibleType(new GraphQLTypeReference("SomeOtherType")) //doesn't work!
          .build();
```

Is this on purpose? Is there a workaround to allow two objects to reference each other in fields with a union type? i.e. How can I make the code below work?

```java

GraphQLObjectType extraObject = newObject()
  .name("extraObject")
  .field(newFieldDefinition()
    .name("some field")
    .type(Scalars.GraphQLString)
  ).build();

GraphQLObjectType objA = newObject()
  .name("objA")
  .field(newFieldDefinition()
    .name("some field")
    .type(newUnionType()
      .possibleType(extraObject)
      .possibleType(new GraphQLTypeReference("objB")) //doesn't work
    )
  ).build();
GraphQLObjectType objB = newObject()
  .name("objB")
  .field(newFieldDefinition()
    .name("some field")
    .type(newUnionType()
      .possibleType(extraObject)
      .possibleType(objA)
    )
  ).build();
```

**Comment by jauco** [comment]
I'm now fairly sure this is a bug:

 1. [GraphQLUnionType line 39](https://github.com/graphql-java/graphql-java/blob/f203c6e04546074438f890623adaf4f27fa338fe/src/main/java/graphql/schema/GraphQLUnionType.java#L39) contains a method for resolving type references that is never called.
 1. In the method a check is performed if the type is a type reference, this check will always fail because the type is an object type

**Comment by jauco** [comment]
I made a fix in jauco/graphql-java@85453f8483b74238bc303f0112776acca8be82e5 I'm not sure if this is the best solution, and I don't know how to run gradle unittests so I'm not submitting a PR right now.

But if you think this is a good approach I will.

**Comment by bbakerman** [comment]
to run tests in gradle just do

   ./gradlew clean build

This will build and run all the tests.

I personally use IDEA and run the tests from inside the project.

**Comment by bbakerman** [comment]
Ok I looked into this issue.  There is a way to do what you want but the method is perhaps hidden from you

I created https://github.com/graphql-java/graphql-java/pull/393 to improve the documentation

You need to use this format

    newUnionType()
        .name("Pet")
        .possibleType(GraphQLObjectType.reference("Cat"))
        .possibleType(DogType)

This creates a reference that IS a GraphQLObjectType and also a TypeReference

**Comment by jauco** [comment]
thanks!
