### ISSUE TITLE
Fix dup code warning by IntelliJ code inspector

### ISSUE THREAD

**Issue by Jimexist** [graphql-java/graphql-java#384]
<img width="451" alt="screenshot 2017-04-19 21 33 41" src="https://cloud.githubusercontent.com/assets/622789/25182784/4d1fc5ea-2548-11e7-9815-fc00fd6a17eb.png">

**Comment by Jimexist** [comment]
@bbakerman do you think it's worth the effort to address the dup code and extract them into a utility function?

**Comment by andimarek** [comment]
@Jimexist I don't think we should make it dry, just because dry is often a good thing. We should tackle specific issues, when we encounter them.

**Comment by Jimexist** [comment]
ok that's a fair point. i'll close this issue.
