### ISSUE TITLE
README.md should only reflect the released version

### ISSUE THREAD

**Issue by bbakerman** [graphql-java/graphql-java#402]
The master branch contains new code that is not released.

However people come to the "home" README to find out how to use the released library

And with 3.x, its breaking changes.

We need a way to stage future READMEs text while not breaking current examples

I propose we keep a README.next.md so we can stage future work progressively yet retain the old released examples

**Comment by andimarek** [comment]
As an alternative we could create a specific PR, which will get merged after the new version is released. That might be better, because with an open PR we can just merge it without having to deal   with conflicts manually.

**Comment by bbakerman** [comment]
My problems with the specific branch is that if some one works on "branch A" to add Foo support they really should document it as they go.  But now they need to go to another branch to make the documentation.

Also the ability to have "compileable" readme examples is low with this approach since they need to be maintained across 2 branches

**Comment by cliedeman** [comment]
[React router](https://github.com/ReactTraining/react-router) solves this problem nicely by having links to docs of the previous versions right at the top of the readme.

**Comment by bbakerman** [comment]
Yeah maybe having a "how to use graphql" .md file would be more easy to manage from a version point of view.  The current system would always stay stable.

**Comment by andimarek** [comment]
switched to readthedocs.io and they support different versions.
