### ISSUE TITLE
Provide development builds for faster feedback and downstream adoption

### ISSUE THREAD

**Issue by ieugen** [graphql-java/graphql-java#405]
Hello, 

I believe it is in the benefit of the community to provide nightly builds based on master (or the development branch that holds the next version of the library).

The idea is that projects that depend on the bleading edge version of graphql-java can depend on those nightly builds and adopt changes much faster. This will allow them to test the code changes and come back with feedback, but also be able to release immediatly after a new graphql-java release. 

I believe this is easy to automate with travis and bintray or similar services, since both of them support open source projects. 

I'm willing to contribute this functionality if it is of value to the community. I know it would be usefull for me working on `graphql-apigen` and an internal project. 

Wdyt?

**Comment by andimarek** [comment]
@ieugen we already to that: every commit is built and available on bintray: https://github.com/graphql-java/graphql-java#development-build
