### ISSUE TITLE
Support type extensions (e.g. "extends type Query", etc.)

### ISSUE THREAD

**Issue by kaseyreed** [graphql-java/graphql-java#406]
## Use Case

For large schemas, being able to extend top level types like Query and Mutation would be nice to have so as to modularize schemas for large projects. 

## Current State

It is currently possible to extend a type once like so: 
```
type Query {
   aField: AType
}

# potentially in another file
extend type Query {
   bField(someArg: SomeType): SomeDomainSpecificType
}
```

Attempting to add one more `extend type` results in an error. 

## Desired State
It would be preferable if the library supported any number of type extensions. This will enable applications with medium / large schemas to separate their types by domain and use-case.

**Comment by bbakerman** [comment]
This is now in master and will be released in 3.0
