### ISSUE TITLE
update grammars-v4

### ISSUE THREAD

**Issue by tamer-hino** [graphql-java/graphql-java#423]
graphql should allow hyphen in model names,
in graphql-js [grammar](https://github.com/graphql/graphql-js/pull/213) it's already updated;

**Comment by dh94** [comment]
hyphen are not allowed in graphql, see [GraphQL naming rules](https://facebook.github.io/graphql/#sec-Names).
the pull request you referred to wasn't merged to graphql-js and is closed - so graphql-js doesn't support it.

i would recommend you look at [How to handle Hyphens in GraphQL](http://stackoverflow.com/questions/41427320/how-to-handle-hyphens-in-graphql-schema-definitions)
