### ISSUE TITLE
RuntimeWiring: registered DataFetcher for a field that does not exist should cause an error

### ISSUE THREAD

**Issue by andimarek** [graphql-java/graphql-java#426]
When a `DataFetcher` is registered for a `RuntimeWiring`, but is is never used, it should cause an Exception.

**Comment by bbakerman** [comment]
I am not sure about this one.

Imagine a larger team, you put together a "framework" of runtime fetchers etc..

Then you also create a series of graphql end points with different schemas.

You combine them at runtime.  So sometimes for a given schema endpoint you MAY not have a field for a fetcher.  

Its not precise but no harm is done.

If we enforce all fetchers are used, then loosely coupled schema def -> runtime wiring is no longer possible

**Comment by ieugen** [comment]
@bbakerman : You have a good point. Come to think of it, we might end up in the situation with multiple enpoints. 

How about logging the unused data fetchers for starters?

**Comment by andimarek** [comment]
maybe I was not clear: not used should not mean "is not called".

I meant: If I register a `DataFetcher` for a field which doesn't exist, it should cause an Exception.

**Comment by bbakerman** [comment]
I think we should close this issue.  I dont think we should make this change.

My reasoning is again to allow a loose coupling between runtime wiring and schema.  I should be able to join together a IDL type specification to a RuntimeWiring that is larger in data fetchers than there is fields.

I agree it can allow things to slip under the covers (eg I though I was using DF X but I have no field for it) BUT it benefits are that you can mix together more complicated schemas -> wirings where sometimes not all data fetchers get used.

I advocate strongly that we dont do this.  Its overly precise and its costs very little in effect (eg a DF that is not used) but prevents a mix and match strategy when building your schemas + runtime wiring

**Comment by andimarek** [comment]
I agree with @bbakerman and there closing it
