### ISSUE TITLE
Null literal is unsupported

### ISSUE THREAD

**Issue by dh94** [graphql-java/graphql-java#427]
currently in graphql-java we can't distinguish between provided nulls and unprovided values,
even worse - the query just fails
see the official graphql pr here
https://github.com/facebook/graphql/pull/83

**Comment by andimarek** [comment]
comment by @bbakerman:

We could extend the grammar to allow a NullValue to be captured in syntax eg:

field (arg : null)
The trick then would be how best to tell DataFetchers that the value is null literal versus not present

**Comment by ieugen** [comment]
@andimarek : java.util.Optional could do that ?

**Comment by bbakerman** [comment]
java.util.Optional would indeed do it

but we would have to change the current behaviour from 

    T argValue = environment.getArgument("arg")

to

   Optional<T> argValue = environment.getArgument("arg")

This would break all existing code.  Its a tricky one

**Comment by ieugen** [comment]
As they say: If you wish to make an omelet... release version 4 :).

**Comment by andimarek** [comment]
see #434

**Comment by bbakerman** [comment]
Implemented via PR #452
