### ISSUE TITLE
mutation to add data into multiple tables in a single query. 

### ISSUE THREAD

**Issue by ajmalsha** [graphql-java/graphql-java#443]
Hi ,

Please explain how to add data into two different tables having one to many mapping.

For example -

I have two tables like author and post . author table having one to many mapping to the post table . I want to insert post details (to Post table) while inserting the Author details(to Author table) in single mutation.Then I need to update the author table with author details and post table with post details.

**Comment by andimarek** [comment]
Hi,

I am sorry, but `graphql-java` doesn't deal with tables or any persistence technology.

You will have to write a mutation which updates your tables. For more about Mutations have a look here: https://github.com/graphql-java/graphql-java#causing-mutation-during-execution

**Comment by ajmalsha** [comment]
I need mutation query like this .

mutation{
  Author(id:2,name:"ajmal",posts:[{id:1,title:"hello"}]){
    id
  }
}

can you help me?

**Comment by andimarek** [comment]
@ajmalsha I am sorry, but we can't help you with implementing the mutation: as I said graphql-java has nothing to do with how you save or update your data.

Feel free to open a new issue if you have a specific question.

Thank you.

**Comment by bbakerman** [comment]
I will link you to our documentation on mutations

http://graphql-java.readthedocs.io/en/latest/execution.html#mutations

In short you need to write a DataFetcher that implements your desired mutation
