### ISSUE TITLE
Description in IDL

### ISSUE THREAD

**Issue by vojtechmasa** [graphql-java/graphql-java#447]
Firstly, thank you very much for great improvements in version 3, especially IDL support, I really appreciate that!

I would like to migrate my project from programmatic definition to IDL. I spent quite long time with creating documentation via `description()` in schema definitions, but I don't see a way (I searched the docs) how to define it via IDL. Is there any possibility to define it (maybe I overlooked something) or it's not possible?
Thanks a lot!

**Comment by andimarek** [comment]
@vojtechmasa Thanks for your kind words.

Unfortunately you are right: IDL doesn't support descriptions currently.  You can have a look for the current discussion: https://github.com/facebook/graphql/pull/90

**Comment by andimarek** [comment]
@vojtechmasa I must correct myself: @bbakerman did an awesome job and already added descriptions based on the current discussion in the PR.

you can add descriptions via comments preceding the type:

``` graphql
# this is a description
type Foo {
  # description for bar
  bar: String
} ```

But be aware that this is not really final and might change in the future. You should also avoid empty lines in the comment, they will probably used to distinguish between a comment and a description:

``` graphql
# this is just a comment and will be ignored in the future but is currently added to the description
#
# this is a description
type Foo {
...
}```

This is probably something we will change soon.

Does this help you?

**Comment by vojtechmasa** [comment]
Wow! That's great news! Thanks a lot guys!

**Comment by andimarek** [comment]
See #449

**Comment by andimarek** [comment]
@vojtechmasa PR #449 is merged. this means after the next release we will honor empty lines as separation between comments and descriptions.

and yes: we will also document it.

I'm closing this now, because we answered your initial question. :-)
