### ISSUE TITLE
ParseCancellationException obscured by NullPointerException

### ISSUE THREAD

**Issue by kaqqao** [graphql-java/graphql-java#448]
If a query contains extra characters at the end, e.g. `{something}}`, document parsing will throw a `ParseCancellationException` that doesn't have `RecognitionException` as the cause. Yet, [graphql.GraphQL#203](https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/GraphQL.java#L203) always expects `RecognitionException`, which causes a `NullPointerException` obscuring the real error.

**Comment by andimarek** [comment]
done with #465
