### ISSUE TITLE
Values of enum in IDL

### ISSUE THREAD

**Issue by vojtechmasa** [graphql-java/graphql-java#450]
I don't know how I could bind enum in IDL with specific Java enum values. Is there an alternative in IDL for the following definition?
```
GraphQLEnumType colorEnum = newEnum()
    .name("Color")
    .value(Color.RED.name(), Color.RED)
    .value(Color.GREEN.name(), Color.GREEN)
    .value(Color.BLUE.name(), Color.BLUE)
    .build();
```
I would say the enum
```
enum Color {
    RED
    GREEN
    BLUE
}
```
would have `String` as value types.

**Comment by bbakerman** [comment]
Currently there is no way to inspect a Java enum as an input to an IDL
values.

The current code simple takes the IDL enum and makes the anme and value the
same thing.

We could have a EnumFactory construct that would give make a call to get
values for a named enum and it would return object values

**Comment by andimarek** [comment]
I think providing values should not be part of the IDL, but it is on the same level as `TypeResolver` and `DataFetcher`. We should extend the `RuntimeWiring` to support such a mapping from Enum Name -> Enum Value.

Is this similar to your `EnumFactory` @bbakerman ?

**Comment by bbakerman** [comment]
Yes I meant an EnumFactory at the RuntimeWiring sense.

**Comment by andimarek** [comment]
@vojtechmasa Please have a look at #458 ... this should solve this Issue.

**Comment by vojtechmasa** [comment]
Looks great. Thank you!

**Comment by andimarek** [comment]
closing it ... will be in the next release
