### ISSUE TITLE
GraphQL Schema Definition support in graphql-java

### ISSUE THREAD

**Issue by ajmalsha** [graphql-java/graphql-java#451]
Can we implement GraphQL Schema Definition support in graphql-java ? if yes then how?

**Comment by andimarek** [comment]
@ajmalsha creating a schema with the Schema defintions language (also called IDL) is supported. Please have a look at the documentation for details: http://graphql-java.readthedocs.io/en/latest/schema.html

**Comment by ajmalsha** [comment]
```
SchemaParser schemaParser = new SchemaParser();
SchemaGenerator schemaGenerator = new SchemaGenerator();

this part is not sporting for me. can you please help me?

```

**Comment by andimarek** [comment]
@ajmalsha this is not a fully working program: it is just a snippet to illustrate how to use it. For example the Imports are missing and the error message tells you that you need to import SchemaGenerator.

**Comment by ajmalsha** [comment]
@andimarek  i know that i'm asking about if i need to add any discrepancies to do this?
