### ISSUE TITLE
File missing in maven repository 

### ISSUE THREAD

**Issue by ajmalsha** [graphql-java/graphql-java#453]
I think your maven repository is not updated . and i found some missing file in that. that why i'm facing Some issue .

`graphql-java/src/main/java/graphql/schema/idl/`  is not in your maven repository provided jar file .

please check the issue .If the issue occurred then i requested  you to solve this as soon an possible .

**Comment by andimarek** [comment]
https://repo1.maven.org/maven2/com/graphql-java/graphql-java/3.0.0/graphql-java-3.0.0-sources.jar containts all sources for the latest release.
