### ISSUE TITLE
Default Root Types for IDL

### ISSUE THREAD

**Issue by andimarek** [graphql-java/graphql-java#457]
It is allowed to omit

```graphql
schema {
...
}
```
if the Root Types are called `Query` and `Mutation`

See https://github.com/facebook/graphql/pull/90/files#diff-fe406b08746616e2f5f00909488cce66R1000 

This is currently not supported.

**Comment by andimarek** [comment]
Your thoughts @b

**Comment by andimarek** [comment]
Your thoughts @bbakerman?

**Comment by bbakerman** [comment]
Fair enough lets do it.  Its easy enough.  Have to do it on schema gen and de compile

**Comment by andimarek** [comment]
@bbakerman we must also do it on the `SchemaPrinter`: only emit `schema ...` if the root types are not named `Query` etc
