### ISSUE TITLE
Why doesn't GraphQLTypeReference implement GraphQLInputType

### ISSUE THREAD

**Issue by petervelosy** [graphql-java/graphql-java#46]
I.e. why isn't it possible to use TypeReferences when creating input objects? If this is intended like this, what is the proper way to create a GraphQLInputObject hierarchy (used for dynamic generation of mutations) out of a Java entity hierarchy which includes bidirectional relationships?

Thank you!

**Comment by andimarek** [comment]
Hi,

currently Type-references are only resolved on Objects or Interfaces. This means that even when  we merge #34 you don't get the behaviour you want.

Also: When you look at the graphql spec about http://facebook.github.io/graphql/#sec-Input-Objects they say they created Input Objects to not allow circular references. So I'm currently not sure it's even possible what you want.

Could you give an example of your schema? I think this would really help.

Thanks

**Comment by petervelosy** [comment]
Dear Andi,

Here are two examples from my schema:

1: recursivity: a User can have a referrer, who is also a User. 
2: bidirectionality: a User can have multiple Subscriptions, but a Subscription may be transferred and shared. Thus, it is a bidirectional relationship which I would like to be editable from both ends.

Currently I have done a workaround in which my argument is a JSON string with the object hierarchy. It would be great if this could be solved via a standard GraphQL way! Currently I have the impression that the mutation framework is rather only for RPCs than hierarchical data updates...

Thanks,
Peter

**Comment by petervelosy** [comment]
Dear Andi,

Here are two examples from my schema:

1: recursivity: a User can have a referrer, who is also a User. 
2: bidirectionality: a User can have multiple Subscriptions, but a Subscription may be transferred and shared. Thus, it is a bidirectional relationship which I would like to be editable from both ends.

Currently I have done a workaround in which my argument is a JSON string with the object hierarchy. It would be great if this could be solved via a standard GraphQL way! Currently I have the impression that the mutation framework is rather only for RPCs than hierarchical data updates...

Thanks,
Peter

**Comment by petervelosy** [comment]
Sorry, closed the issue just accidentally. The buttons were too close on my phone.

**Comment by andimarek** [comment]
I think InputObject was not meant to be used in this way. 
For your first example: User referencing another User. This could be cyclic, but you can't express that in a literal. I think that's exactly the type of case they wanted to avoid.

**Comment by andimarek** [comment]
Also: Yes, it's kind of RPC style.

**Comment by eugenpp** [comment]
Mentioned in #172

**Comment by dminkovsky** [comment]
Closing this in favor if #172 which has PR #204.
