### ISSUE TITLE
Provide a way to retrieve the partial result if instrumentation throws an exception

### ISSUE THREAD

**Issue by kaqqao** [graphql-java/graphql-java#460]
Currently, if a `DataFetcher` throws, a `GraphQLError` is added but the execution still results in an `ExecutionResult`. On the other hand, if instrumentation throws, the whole execution throws, and the partial result can not be retrieved.
I'd argue this warrants an improvement, as it would make instrumentation more useful.

The concrete example I have in mind here is dynamic analysis of query complexity. I've built an instrumentation that collects complexity scores as the fields are being resolved, and once a threshold is broken it throws an exception. Without the ability to still return the partial result, it is no more useful than static analysis would be. I can come up with more use-cases, but this is an organic one I have.

**Comment by bbakerman** [comment]
If we do this I think we should use exception class hierarchy as instructions.

If you accidentally throw NullPointerException then I doubt you meant it.

If you throw a well known `StopQueryExecutionException` there is no doubt say on what do in the framework

**Comment by kaqqao** [comment]
I was thinking along the same lines: have a known exception type that is handled in a special way, allowing instant interruption of further resolution, with the result built so far still reachable.
@andimarek mentioned he already had something in mind, so maybe he has a different perspective.

The current implementation allows for instant interruption, but at the expense of the partial result. Conversely, an exception in a fetcher, retains the partial result but doesn't interrupt further resolution (beyond its own branch).

Btw, I added an example to the issue, to better clarify the intent.

**Comment by andimarek** [comment]
I will tacke this together with #459

**Comment by bbakerman** [comment]
Hey this is done yeah... via the `graphql.execution.AbortExecutionException` no?

**Comment by andimarek** [comment]
unfortunately not: you can abort the execution before the execution, but the exception is not handled correctly while executing. Should not be too complicated, but needs to be done.

**Comment by andimarek** [comment]
Lets plan that for 5.0

**Comment by bbakerman** [comment]
I had  a quick look into this.  With the use of CompletableFuture its kinda tricky.

The AsyncES code tends to fire of N futures (per field) and wait for them all the complete but handle any exception from that in aggregate.

While this "independent" execution, you can have 1 field / code path stop execution via say an AbortExecutionException but you can easily stop all the other futures that are nominally running at the same time.

@kaqqao - do you want the other fields in your partial result?  Perhaps is it enough to ask whether any one (or more) future has been completed and grab their results but otherwise skip anything that is still running??

**Comment by andimarek** [comment]
@bbakerman I like the idea to grab the results which are already finished and then return what we have. 👍

**Comment by kaqqao** [comment]
Originally, my scenario was like that: all the current and future fields get cancelled when an instrumentation throws, but the current result is still returned. But, I no longer have a concrete case for it... so I'm certainly on board with whatever you guys think makes sense here.

**Comment by david-tamjidi** [comment]
Any idea if this will make it into 7.0? :)
