### ISSUE TITLE
ExecutionResult does not follow spec

### ISSUE THREAD

**Issue by bbakerman** [graphql-java/graphql-java#473]
The spec says

https://facebook.github.io/graphql/#sec-Response-Format

> Response Format
> 
> A response to a GraphQL operation must be a map.
> 
> If the operation included execution, the response map must contain a first entry with key data. The value of this entry is described in the “Data” section. If the operation failed before execution, due to a syntax error, missing information, or validation error, this entry must not be present.
> 
> If the operation encountered any errors, the response map must contain a next entry with key  errors. The value of this entry is described in the “Errors” section. If the operation completed without encountering any errors, this entry must not be present.

So ExecutionResult is a map like thing that should NOT have an error field if there are no errors and vice versa.

So for example this in invalid

```json
{
  "errors": [],
  "data": {
    "hero": {
      "name": "R2-D2"
    }
  }
}
```
since it has data in it but no errors

But JSON serialisation libraries such as GSON and others WILL include these fields.

        private void returnAsJson(HttpServletResponse response, ExecutionResult executionResult) {
        response.setContentType("application/json");
        GSON.toJson(executionResult, response.getWriter());
    }

I propose that we have a toMap() method on execution result that means its easy for HTTP service layers to implement the spec properly.

        private void returnAsJson(HttpServletResponse response, ExecutionResult executionResult) {
        response.setContentType("application/json");
        GSON.toJson(executionResult.toMap(), response.getWriter());
    }

**Comment by guy120494** [comment]
What would happened if execustionResult returns null when error is empty?
Is there any convention in JSON libraries what happens? I know that in GSON it ignores the null values (unless specific asked not to)

**Comment by bbakerman** [comment]
So the spec says that if null is present and there are no errors then that is the result of the query

So graphql JSON encoder code is responsible for setting it up to encode nulls if it wants to follow spec

**Comment by andimarek** [comment]
See PR #480 for further discussion

**Comment by tkvw** [comment]
Why didn't you implement a custom serialization 
type for this? @see: https://github.com/google/gson/blob/master/UserGuide.md#TOC-Custom-Serialization-and-Deserialization

**Comment by bbakerman** [comment]
Because the graphql-java library BY design does not want to get into the game of build JSON serialisation strategies

Would we would need one for Jackson / GSON / JSONP / Java 9 / SimpleJson ....
