### ISSUE TITLE
DataFetcher doesn't have a reference to the parent type

### ISSUE THREAD

**Issue by bsideup** [graphql-java/graphql-java#476]
Hi!

If I use WiringFactory I can't access the parent type of a field. 

It means that if I provide a DataFetcher for a field with id "name" then the only way to resolve it is to resolve EVERY field with id "name", for EVERY type.

However, I would like to say that my WiringFactory provides DataFetcher only for type "SomeUserType" and field id "name".

Thanks!

**Comment by andimarek** [comment]
Hi,

do you really need a `WiringFactory`? You could use the normal `.type` of `RuntimeWiring` to define the `DataFetcher` for `SomeUserType`.

And you can additionally use a `WiringFactory` if needed. But this is only intended for some dynamic uses cases which can't be solved otherwise.

**Comment by bsideup** [comment]
Hi,

Yes, my case IS dynamic discovery :) 
I have a pluggable system with many extensions to the single GraphQL endpoint

**Comment by andimarek** [comment]
Ok ... then answering your original question: We only provide the `FieldDefinition` currently. But you could use the `TypeDefinitionRegistry` to access the possible parent and check if the `FieldDefinition` is part of it:
something like that:
```java
if( ((ObjectTypeDefinition)typeDefinitionRegistry.getType("SomeUserType")).getFieldDefinitions.contains(fieldDefinition) ) {

.... 
}
```

**Comment by bsideup** [comment]
Thanks! Do you plan to simplify this API somehow?

**Comment by andimarek** [comment]
well .... I can see it that it would make sense to provide the parent. 
We would be happy to accept a PR to change that. :-)

**Comment by bsideup** [comment]
ok :) Will do

**Comment by andimarek** [comment]
thanks

**Comment by ieugen** [comment]
I also have a use case where it would be great to have the name of the type when resolving Data fetchers. 

I have added a gist to help explain the issue [1]. 

In the schema,  I declare a data fetcher like this:
type MutateQuestionnaire {
````
start(id: Long!, token: String!): Questionnaire @dataFetcher(name: "mutateQuestionnaireStart")
````
And I'm using a Spring based wiring factory to lookup a bean with the name `mutateQuestionnaireStart` and bind it to the field. 

Having the name of the type `MutateQuestionnaire` will allow me to implement a sort of auto resolution process where I can declare something like:
````
start(id: Long!, token: String!): Questionnaire @dataFetcher(strategy: "autowired")
````

And then I can lookup for beans with the name computed from the type name and field name: `mutateQuestionnaire_start` .

Is this similar to your usage case @bsideup? 

[1] https://gist.github.com/ieugen/12e2ccf078c6d07032cc4a26d6dc53ac

**Comment by bsideup** [comment]
Hey @ieugen,

Yes, you case sounds valid for the change as well :)

I sent a PR with proposed change, could you please take a look at it and say if it works for you?
https://github.com/graphql-java/graphql-java/pull/478

You can even try it yourself thanks to JitPack:
https://jitpack.io/#bsideup/graphql-java/476-parent_type_ref_in_datafetcher-SNAPSHOT
