### ISSUE TITLE
JDK7 support

### ISSUE THREAD

**Issue by bowenliang123** [graphql-java/graphql-java#482]
Any possibility to lower minimum required JDK to 7?
I am interested in using Graphql with Java (better with IDL support) in production while for some restrictions the only available JDK in our team is JDK7.

**Comment by andimarek** [comment]
I am sorry to hear that you can't use Java 8, but we just recently switched to Java 8 and we are already using the new features all over the place and we don't have the resources and the time to support something else.

I'am afraid the answer is no.

Please have a look at this Issue where we discussed it: https://github.com/graphql-java/graphql-java/issues/359 

Thanks!

**Comment by bowenliang123** [comment]
@andimarek All right. I am considering staying version 2.4.0 for further use. Thanks for your detailed reply.
