### ISSUE TITLE
Example for dataFetcher directive

### ISSUE THREAD

**Issue by vtahlani** [graphql-java/graphql-java#497]
Do you have example for using dataFetcher directive. Below is my IDL schema

```
schema {
    query: QueryType
}

type QueryType {
    getUser: User@dataFetcher(dataFetcher : "new com.test.data.User()")
}

interface User {
	userId: ID
	, UserName: String
	, Friends: [User]
	
}

```
Schema get loaded successfully but looks like dataFetch not working.

Can we write custom function as part of dataResolver, the way we can do it with [graphql-js](https://github.com/graphql/graphql-js)? Can we call javaScript functions?

**Comment by bbakerman** [comment]
resolvers are called DateFetchers in graphl-java

See http://graphql-java.readthedocs.io/en/latest/schema.html for examples

 @dataFetcher is not inherently supported by the base graphql-java engine.

You can however write a WiringFactory that would interpret that and create data fetchers based directive.  The WiringFactory is passed the "field definition" which includes directives.

Again see that example for a custom WiringFactory

**Comment by vtahlani** [comment]
I have aleady gone through this link, here runtime wiring function is
missing definition for getDirective and createTypeResolver functions, do
you have complete example with run time wiring?

What would you recommend graphql-js or graphql-java?

On 14 Jun 2017 04:27, "bbakerman" <notifications@github.com> wrote:

resolvers are called DateFetchers in graphl-java

See http://graphql-java.readthedocs.io/en/latest/schema.html for examples

@datafetcher is not inherently supported by the base graphql-java engine.

You can however write a WiringFactory that would interpret that and create
data fetchers based directive. The WiringFactory is passed the "field
definition" which includes directives.

Again see that example for a custom WiringFactory

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/graphql-java/graphql-java/issues/497#issuecomment-308272169>,
or mute the thread

**Comment by bbakerman** [comment]
```
WiringFactory dynamicWiringFactory = new WiringFactory() {
            @Override
            public boolean providesTypeResolver(TypeDefinitionRegistry registry, InterfaceTypeDefinition definition) {
                return getDirective(definition,"specialMarker") != null;
            }

            @Override
            public boolean providesTypeResolver(TypeDefinitionRegistry registry, UnionTypeDefinition definition) {
                return getDirective(definition, "specialMarker") != null;
            }

            @Override
            public TypeResolver getTypeResolver(TypeDefinitionRegistry registry, InterfaceTypeDefinition definition) {
                Directive directive = getDirective(definition, "specialMarker");
                return createTypeResolver(definition, directive);
            }

            @Override
            public TypeResolver getTypeResolver(TypeDefinitionRegistry registry, UnionTypeDefinition definition) {
                Directive directive  = getDirective(definition,"specialMarker");
                return createTypeResolver(definition,directive);
            }

            @Override
            public boolean providesDataFetcher(TypeDefinitionRegistry registry, FieldDefinition definition) {
                return getDirective(definition,"dataFetcher") != null;
            }

            @Override
            public DataFetcher getDataFetcher(TypeDefinitionRegistry registry, FieldDefinition definition) {
                Directive directive = getDirective(definition, "dataFetcher");
                return createDataFetcher(definition,directive);
            }
        };
        return RuntimeWiring.newRuntimeWiring()
                .wiringFactory(dynamicWiringFactory).build();
```

This is a sample example wiring factory.  It looks for a special directive say and adjusts behaviour on that

You can then do this say (this is an example)

         private Directive getDirective(FieldDefinition fieldDefintion, String type) {
        return fieldDefintion.getDirectives().stream().filter(d -> d.getName().equals(type)).findFirst().get();
    }

and then

         private DataFetcher createDataFetcher(FieldDefinition definition, Directive directive) throws ClassNotFoundException, IllegalAccessException, InstantiationException {
        Optional<String> dataFetcherClass = directive.getArguments().stream().filter(argument -> argument.getName().equals("dataFetcherClass")).map(arg -> ((StringValue) arg.getValue()).getValue()).findFirst();
        if (dataFetcherClass.isPresent()) {
            Class<DataFetcher> dfClass = (Class<DataFetcher>) Class.forName(dataFetcherClass.get());
            return dfClass.newInstance();
        }
        return new PropertyDataFetcher(definition.getName());
    }


This of course is just example code
