### ISSUE TITLE
ExecutionInput should comply with GraphQL Spec

### ISSUE THREAD

**Issue by jdorleans** [graphql-java/graphql-java#503]
POJO ExecutionInput should have the following attributes to complain with the GraphQL Spec.
- **query** - String - a GraphQL query as a string
- **variables** - Map<String, Object> - defines variables for your query (optional)
- **operationName** - String - a name of an operation, in case you defined several of them in the query (optional)

http://graphql.org/learn/serving-over-http/#post-request

**Comment by bbakerman** [comment]
The class is not really designed to be JSON instantiated.

It has a builder and is designed to be called more "deliberately".  The "context" and "root" object can never be set via a JSON object say

This would be nicer

        ExecutionInput executionInput = ExecutionInput.newExecutionInput()
                .query(requestString)
                .operationName(operationName)
                .context(context)
                .root(context)
                .variables(arguments)
                .build();


I will agree that the names of the methods should follow spec naming.

        ExecutionInput executionInput = ExecutionInput.newExecutionInput()
                .requestString(requestString)
                .operationName(operationName)
                .context(context)
                .root(context) // This we are doing do be backwards compatible
                .arguments(arguments)
                .build();

I would suggest you create a JSON oriented class that can be instantiated automatically that then feeds into actual builder

**Comment by bbakerman** [comment]
The naming has been changed to align with spec.  Its still not designed to be JSON instatiated directly
