### ISSUE TITLE
Introspection query marks LIST fields as null

### ISSUE THREAD

**Issue by blevandowski-lv** [graphql-java/graphql-java#520]
When running an introspection query as follows:
`query IntrospectionQuery {
  __schema {
    types {
      fields {
        name
        type {
          name
          kind
          fields {
            name
          }
        }
      }
    }
  }
}`

objects return properly as:
`{
  "name": "NAME",
  "type": {
    "name": "OBJECT_NAME",
    "kind": "OBJECT",
    "fields": [ ... ]
  }
}`

but when run on a list, I get back:
`{
  "name": "NAME",
  "type": {
    "name": null,
    "kind": "LIST",
    "fields": null
  }
}`

I would expect "name" to be the objects that make up the list, and "fields" to be the fields of those objects - much like if it was a single object, only that "kind" is marked as "LIST" instead of "OBJECT".

**Comment by bbakerman** [comment]
To help with this issue can you run the same same query on the reference js served graphql to check its return values

**Comment by bbakerman** [comment]
http://facebook.github.io/graphql/#sec-List

The spec says about Lists

> List
> 
> Lists represent sequences of values in GraphQL. A List type is a type modifier: it wraps another type instance in the ofType field, which defines the type of each item in the list.
> 
> Fields
> 
> kind must return __TypeKind.LIST.
> ofType: Any type.
> All other fields must return null.

It might be missing the ofType field (perhaps although others do too) but the other fields are following sec I think
