### ISSUE TITLE
BatchedExecutionStrategy logs two warnings on each data fetching exception

### ISSUE THREAD

**Issue by tklovett** [graphql-java/graphql-java#528]
If I'm reading it correctly, `BatchedExecutionStrategy` logs two warnings when `Exception`s occur during `DataFetcher#get(DataFetchingEnvironment)`

1. https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/execution/batched/BatchedExecutionStrategy.java#L318-L319
2. https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/execution/ExecutionStrategy.java#L75

**Comment by bbakerman** [comment]
This has been rewritten in 4.x and is not longer the case that I can see
