### ISSUE TITLE
Generate schema from .class object

### ISSUE THREAD

**Issue by Volodymyr128** [graphql-java/graphql-java#53]
I'm programming on both: JavaScript and Java. I'm very excited about idea of GraphQL on a client side. But the Groovy (moreover I suppose Java) implementation seems not readable for me Let's look at the next examples:
1. Data definition - https://github.com/andimarek/graphql-java/blob/master/src/test/groovy/graphql/StarWarsData.groovy
2. Schema definition - https://github.com/andimarek/graphql-java/blob/master/src/test/groovy/graphql/StarWarsSchema.java
3. Query tests - https://github.com/andimarek/graphql-java/blob/master/src/test/groovy/graphql/StarWarsQueryTest.groovy

For me the less readable part is schemas and data fetchers. _Why you can't generate them from .class objects?_ Example:

```
class StarWarsEnum {
    NEWHOPE,
    EMPIRE,
    JEDI
}
GraphQLEnumType episodeEnum = GraphQL.from(StarWarsEnum.class)
```

No much benefit for enum, but that will significantly simplify `characterInterface` and `humanType`  objects. Also your DAO layer may already have that POJO classes and GraphQL will just resure them.

**Comment by andimarek** [comment]
Hi,

of course the schema could be build in another way. But generating from classes seems not perfect. For example where to do you specify such things as the documentation. Also it's not always the case that you have a class for every GraphQLObject or GraphQLInterface.

In general I don't plan to add another schema definition soon, but I'm open for any idea/contributions.

Andi

**Comment by buma** [comment]
I have some kind of code generator for java classes and enums. It also adds documentation (description) nullability and defaultValue in operations. it reads those info from javadoc. For release I need to clean it if somebody is interested.

**Comment by sanju-sfo** [comment]
I was really glad to find the Java based server for GraphQL, though the client side became simpler with GraphQL but the complexity is pushed to the server side.
Being said that, it feels like it's a different flavor of xsd/xml combination, However the I also do feel that the Creating Schema directly as GraphQL object is not intiutive and readable. 

I went thru the spec to find, if there is any text based language independent way of defining the schema (similar to xsd) which can be later use to create both Pojo's as well as GraphQL object using some code generator. or just Dynamically create the the GraphQL objects in runtime thru reflection. 

Very disappinted not to see the text based defintion thru the GraphQL spec though, or may be I have missed it please let me know if I am wrong here.

**Comment by danielkwinsor** [comment]
I am interested in generating schema from .classes too.  I might even have bandwidth to help with contributing or helping clean up buma's reflection code for release.

**Comment by buma** [comment]
Finally I have uploaded [code](https://github.com/buma/GraphQlGenerator) to the Github.

**Comment by danielkwinsor** [comment]
Hi guys,
I have uploaded [graphql-java-type-generator](https://github.com/danielkwinsor/graphql-java-type-generator) which currents operates on a .class basis, but the structure is such that I'll be designing a config based approach, and can fit in a .java approach as well.
I appreciate your feedback.

**Comment by dminkovsky** [comment]
Hi, thanks for posting. This is beyond the scope of this project, but check out some related things:

https://github.com/graphql-java/graphql-java-annotations
https://github.com/graphql-java/graphql-java-type-generator
https://github.com/bpatters/schemagen-graphql
