### ISSUE TITLE
Variables logging on Execution

### ISSUE THREAD

**Issue by fchiarelli** [graphql-java/graphql-java#534]
**Variables** logging is actually missing: [GraphQL.java#execute](https://github.com/graphql-java/graphql-java/blob/e284b7e8cafb4313766bafbde2a5aa59bc3b3dd5/src/main/java/graphql/GraphQL.java#L253)

**Comment by andimarek** [comment]
Could you open a PR for that? Thanks a lot

**Comment by bbakerman** [comment]
Me
