### ISSUE TITLE
Runtime wiring needs the ability to inject as last resort DataFetcher

### ISSUE THREAD

**Issue by bbakerman** [graphql-java/graphql-java#536]
Today it uses PropertyFetcher but you should be able to wire in a DataFetcher that is used as a last resort

**Comment by A1m7331** [comment]
funny, I came here one hour after you to request the exact same thing!

Actually, I thought I found a way to achieve this with a custom wiring factory that contains the RunTimeWiring and checks whether one exists. Like this:
`
public class CustomWiringFactory implements WiringFactory{
    private RuntimeWiring wiring;
    public AnnotationAwareWiringFactory(RuntimeWiring wiring) {
        this.wiring = wiring;
    }
    @Override
    public boolean providesDataFetcher(TypeDefinitionRegistry registry, FieldDefinition definition)
    {
        return true;
    }

    @Override
    public DataFetcher getDataFetcher(TypeDefinitionRegistry registry, FieldDefinition definition) {
        DataFetcher existingFetcher = wiring.getDataFetcherForType(parentType.getName()).get(definition.getName());
        if (existingFetcher != null) {
            return existingFetcher;
        }
        return new CustomDataFetcher();
    }
`

But the problem is, that getDataFetcher is only passed the FieldDefinition and as far as I can see there is no possibility here to know which type it does belong to.

Isn't this a general Problem here? The power of a custom WiringFactory is not very impactful if you get fields without any information to which type it does actually belong to.

**Comment by bbakerman** [comment]
Yes we know about this issue -  There current master branch has a new set of parameters passed in

```
    /**
     * This is called to ask if this factory can provide a data fetcher for the definition
     *
     * @param environment the wiring environment
     *
     * @return true if the factory can give out a data fetcher
     */
    default boolean providesDataFetcher(FieldWiringEnvironment environment) {
        return false;
    }
```

and

```
    public class FieldWiringEnvironment extends WiringEnvironment {

    private final FieldDefinition fieldDefinition;
    private final TypeDefinition parentType;

    FieldWiringEnvironment(TypeDefinitionRegistry registry, TypeDefinition parentType, FieldDefinition fieldDefinition) {
        super(registry);
        this.fieldDefinition = fieldDefinition;
        this.parentType = parentType;
    }

    public FieldDefinition getFieldDefinition() {
        return fieldDefinition;
    }

    public TypeDefinition getParentType() {
        return parentType;
    }
}
```

This gives you the parent type to allow for better decisions

**Comment by A1m7331** [comment]
I solved the first issue on the current version, by adding a custom DataFetcher whenever none is present. Not perfect, but works for now.

    ```
private RuntimeWiring.Builder makeDefaultWirings(RuntimeWiring.Builder wiring,
                                                     TypeDefinitionRegistry compiledSchema)
    {
        for (String typeName : compiledSchema.types().keySet()) {
            Map<String, DataFetcher> dataFetchers = wiring.build().getDataFetcherForType(typeName);
            TypeDefinition type = compiledSchema.types().get(typeName);
            if (type instanceof ObjectTypeDefinition) {
                for (FieldDefinition fieldDefinition : ((ObjectTypeDefinition) type)
                        .getFieldDefinitions()) {
                    dataFetchers.computeIfAbsent(fieldDefinition.getName(),
                                                 AnnotationAwarePropertyDataFetcher::new);
                }
            }
        }
        return wiring;
    }

```
