### ISSUE TITLE
graphql 3.0.0 schema generator does not put additional types in the schema

### ISSUE THREAD

**Issue by bbakerman** [graphql-java/graphql-java#538]
Given the following

```
schema {
    query : Query
}

type Query {
    being(id : ID, type : String) : Being
    beings(type : String) : [Being]
}

interface Being {
    id : ID
    name : String
    nameInQuenyan : String
    invitedBy : ID
}


type Ainur implements Being {
    id : ID
    name : String
    nameInQuenyan : String
    invitedBy : ID
    loves : String
}


type Istari implements Being {
    id : ID
    name : String
    nameInQuenyan : String
    invitedBy : ID
    colour : String
}

type Deity implements Being {
    id : ID
    name : String
    nameInQuenyan : String
    invitedBy : ID
    outlook : String
}
```

The types Istari and Ainur will not being included in the generated schema since they are not referenced at all.  I think this fix is on master but for 3.0.0 is still a problem

It means you cannot write a interface driven schema

**Comment by filipncs** [comment]
Any plans to do a minor 3.0.x release with this fix? The commit that fixed this (https://github.com/graphql-java/graphql-java/commit/9addb0219831a39c9ffc3cc96ab445c4e15b700f) applies cleanly to v3.0.0 with only a couple of adjustments.

I'd gladly supply a PR with a clean modification to v3.0.0 that fixes the issue and includes a test.

In general it would be nice to have an idea of what the current roadmap looks like, e.g. if it would make more sense to hold out for 4.0.0

**Comment by bbakerman** [comment]
This is fixed in 4.x which is due end of Aug
