### ISSUE TITLE
Introspection data fetchers

### ISSUE THREAD

**Issue by emrul** [graphql-java/graphql-java#556]
I have a number of types and fields that should only be returned in the schema if a user has particular access rights.

My own data fetchers enforce access rights but I specifically don't want certain fields to be returned by an introspection query made by certain users.

I've been trying to find various ways to customise the behaviour.  Unfortunately, it seems a LOT of what I'd need to change is hidden behind private methods or classes that cannot easily be replaced by subclassing.

Is there a sane way to do this short of forking the code base?

**Comment by bbakerman** [comment]
Ok I accept your use case.  Not sure how many people would ever do it but perhaps banks and financial type companies might

I ran up a PR here : https://github.com/graphql-java/graphql-java/pull/562

Let me know if you think you can implement your code in terms of that.

**Comment by emrul** [comment]
Hi, I just tried your PR and unless I've made a mistake I think its failing.  
I believe it is because SchemaUtil() has a reference to Introspection.__Schema in the method collectTypes()

If I use the default it is fine but if I wire my own in and issue an Introspection query I get 

`Validation error of type InvalidFragmentType: Fragment FullType cannot be spread here as objects of type GraphQLObjectType{name='__Type', description='null', fieldDefinitionsByName={kind=graphql.schema.GraphQLFieldDefinition@386cac77, name=graphql.schema.GraphQLFieldDefinition@7f61d90a, description=graphql.schema.GraphQLFieldDefinition@50e0e4d8, fields=graphql.schema.GraphQLFieldDefinition@2f04c3d1, interfaces=graphql.schema.GraphQLFieldDefinition@72d6cd52, possibleTypes=graphql.schema.GraphQLFieldDefinition@30ee38b, enumValues=graphql.schema.GraphQLFieldDefinition@549f0116, inputFields=graphql.schema.GraphQLFieldDefinition@5d0c5a1f, ofType=graphql.schema.GraphQLFieldDefinition@1974a0b1}, interfaces=[]} can never be of type GraphQLObjectType{name='__Type', description='null', fieldDefinitionsByName={kind=graphql.schema.GraphQLFieldDefinition@6d120aaf, name=graphql.schema.GraphQLFieldDefinition@412921aa, description=graphql.schema.GraphQLFieldDefinition@7e4a4732, fields=graphql.schema.GraphQLFieldDefinition@42871162, interfaces=graphql.schema.GraphQLFieldDefinition@3f3d3cef, possibleTypes=graphql.schema.GraphQLFieldDefinition@37916ed3, enumValues=graphql.schema.GraphQLFieldDefinition@1bcedcc4, inputFields=graphql.schema.GraphQLFieldDefinition@6138c2de, ofType=graphql.schema.GraphQLFieldDefinition@37345052}, interfaces=[]}`

**Comment by emrul** [comment]
I made a PR along your original suggestion of having an IntrospectionTypeProvider - the only real differences are:

1. SchemaUtil.allTypes() references the schema provided by the TypeProvider
2. Instead of configuring the GraphQL instance I configure the GraphQLSchema.  I write Kotlin but I've made a Java example:

`
        GraphQLSchema schema = GraphQLSchema
                .newSchema()
                .query(...)
                .mutation(...)
                .introspectionTypeProvider(MyIntrospectionProvider.INSTANCE)
                .build(...);
`

This works, I suspect because of the change to SchemaUtil()

I'll be very happy to use the naming conventions in your PR, I also have no issue with configuring the introspection provider at the GraphQL level but I suspect we'll need to find a way to still push this down into the GraphQLSchema instance so that it can pass it on to SchemaUtil()

Thoughts and pointers much appreciated!

**Comment by emrul** [comment]
@bbakerman this has been quiet for a couple of weeks - do you have any idea on whether you'll be able to correct your PR or accept mine?

**Comment by bbakerman** [comment]
@emrul - there is some opposition in accepting this PR into the system.  That is building a more complex library for the sake of a small user case.

That said I personally have recently come across a user case.  Public and Private APIs.

Imagine a graphql gateway that has more and less fields on it depending on whether the caller is a private in company caller versus a public out of company API user?

That said I am not sure its Introspection but rather a separate schema in general.

**Comment by emrul** [comment]
@bbakerman I'm a little confused - who and where is this opposition coming from? I received no comments on my PR or in this issue other than from yourself.

I'm also not sure I understand the complexity argument.  The current code base has a static class (SchemaUtil) that makes a direct reference to a static singleton inside one of its methods.  It could be argued that unless the developer were intentionally trying to make it impossible for this code to be extended there are more flexible code constructs that would otherwise be more appropriate.  Even if you had 2 separate GraphQL instances in a JVM they would currently share the same reference to IntrospectionSchema.

My proposed patch (I would guess) changes less than 100 lines and refactors the code I mentioned above so it becomes extensible and we no longer have a totally inflexible reference to a static singleton.  Now library users can extend and override behaviour if they need to.

I'm not sure how, given some of the other PRs and library features there are in GraphQL-Java and the intent of this particular PR to do a small bit of clean up, that this one should get picked up as contributing to a 'more complex library for the sake of a small user case'.  I'm also slightly taken aback that this has seemingly happened in the shadows somewhere while this issue has been left dormant and I've had no clue - that questions the level of transparency that this project is striving for.

I appreciate the use case you reference.  Its not the same as ours and maybe when you have a finite number of possibilities it is simpler to have separate schema.  However, I would point out that if my suggested approach was taken then you could meet the public / private company API requirement without much effort other than writing a filter at Introspection schema level - far easier to manage than a separate API.

I have a meeting with the rest of the team on our current project this afternoon.  We'll discuss the project feedback there and decide on how to proceed.

**Comment by andimarek** [comment]
@emrul Im sorry, that you feel disappointed, but we are a small team of currently 3 maintainers (working on this project in our free time) and we have carefully to consider if we add a new feature. 

@bbakerman and I talked about it and I wasn't sure if we should really support it, because it makes it slightly more complex and I am not convinced this is a problem/use case enough of our users have. That's all: there was no big decision or shadow process.  

And this issue was not left dormant: sometimes we need a few weeks or even months to get back to an issue. We try of course that doesn't take too long, but we can't promise anything.

**Comment by emrul** [comment]
Thanks for the explanation @andimarek.  I understand your situation.  We're of course open to the idea that not all our patches are things that other people would want.  I would still ask you to consider whether such tight coupling in this instance is a good idea in what should be a library for other developers to be able to use and extend.

We will most likely maintain our work in a separate fork and we'll try to track this projects releases as closely as possible.

Please feel free to close this issue & associated PR.

**Comment by andimarek** [comment]
@emrul thanks for understanding. I will talk with @bbakerman about this issue again and we will get back to you soon.

**Comment by bbakerman** [comment]
This is what I think we should do 👍 

1) have a switch to turn off Introspection (not replace it nor allow it to lie - just be on and off)
2) expect people to build separate schemas for their class of users
3) don't build replaceable introspection

I have been thinking about what it would take to have a Schema A and transform it into Schema B with some differences (added fields and types / removed fields and types)
its like you need a SchemaTransformer
that “walks” the schema and calls back to code to add / remove fields and types
that way you can have a “open” schema and then “transform” it into the more closed one say
and keep 2 copies in memory
that way the Introspection will work for each

if you “lie” in Introspection you still have to enforce field access at query time via data fetchers
because Introspection says there is no “secretFoo” field but the runtime will validate it and accept it
now you need to make the dataFetcher blow up some how

thats kinda security by obscurity - not be design

**Comment by emrul** [comment]
Guys, I think we're set with maintaining our fork as the approach forward so your choices here really won't impact us.  We are discussing whether we can spend time to publicly release our work (mainly about providing more enterprise-y features) after project has launched.

That said, I don't know who's usecase @bbakerman is targeting but it certainly would not be something we could use.  I also would point out that DataFetchers would need to do security checking even if you kept _n_ schemas in memory (unless you had separate DataFetchers for each schema..  at which point the question is what benefit are you getting?)

Providing a switch to switch introspection off is something that might be useful for some, but it sounds like it will create a LOT more headache to actually make that a useable approach.  It also sounds like it will involve more complexity than what I suggested.  And you will still need to refactor that tightly coupled relationship between SchemaUtil and Introspection classes.

It is also not 'security by obscurity' to design a system that hides inaccessible fields as long as it also prevents access to those fields - you as library designers can't make sure users do the right thing.

Overall I would suggest against this - unless I'm mis understanding some use case I'm not sure how the alternative proposal provides any useable benefit.

**Comment by andimarek** [comment]
@emrul I am bit surprised, but maybe we didn't communicate it clearly: Option 2 was specifically designed for your use case:

You would define n different schemas for n different roles and select the appropriate one for the introspection per request.

@bbakerman also just wanted to point out that we don't plan to actually enforce the security in `graphql-java`, meaning that you would have to ensure yourself that the user doesn't access a forbidden field.

I am interested in your feedback, even if you decide to maintain a fork with your own solution: Wouldn't that solve your problem?

Thanks!

**Comment by emrul** [comment]
@andimarek I think you might have not read my related comment on the PR I provided: https://github.com/graphql-java/graphql-java/pull/557#issuecomment-313707486 "We initially thought about building multiple GraphQL schemas but the project anticipates that access should be controlled at group level and having a large number of instances of GraphQL schemas for each permutation just isn't feasible."

Essentially it was one of our early thoughts/plans but it just wasn't viable.  I fully agree, if we had a well-defined split between, say, public and private users, we could work with your suggestion.  But instead we have a group hierarchy and certain groups are permitted access to certain fields (and sub-fields).

In our current setup, with the patch we have applied it works very well: the DataFetchers are calling out to an ACL check to make sure users are authorised to request the particular fields they're asking for.  If a user tries to query something that they don't have access to we return an error that looks like the field just doesn't exist.  Now, returning a 'field doesn't exist' error while the Introspection schema says it does wouldn't make any sense - so we applied the same ACL checks on introspection queries.

Upon reflection, this probably isn't something most users of this framework would have to do - we just needed it because our customers are rather particular about this sort of thing.

**Comment by andimarek** [comment]
@emrul thanks for your (repeated) explanation: I understand it better now. We will have to think about it again.

**Comment by bbakerman** [comment]
@emrul - can you have a look at https://github.com/graphql-java/graphql-java/pull/641 and see if it satisfies your use case.

It prevents both introspection, query validation and data execution (should you some how get past validation)

I think this will do what you want.

You would implement a GraphqlFieldVisibility implementation that controlled what fields are visible during the request based on your users

**Comment by bbakerman** [comment]
I am going to close this issue as the capability to change field visibility including to Introspection is now in master and will come with 4.0
