### ISSUE TITLE
Is there any way to populate string representation of GraphQLSchema object?

### ISSUE THREAD

**Issue by opshubdata** [graphql-java/graphql-java#559]
We are thinking to generate Schema documentation from GraphQLSchema Object. Is there any existing implemented method which will help us to build schema documentation?

I tried to generate json from object using Jackson but it throw StackOverflowError exception,

Infinite recursion (StackOverflowError) (through reference chain: graphql.schema.GraphQLFieldDefinition["type"]->graphql.schema.GraphQLObjectType["fieldDefinitions"]->java.util.ArrayList[3]->graphql.schema.GraphQLFieldDefinition["type"]->graphql.schema.GraphQLObjectType["fieldDefinitions"]->java.util.ArrayList[3]->graphql.schema.GraphQLFieldDefinition["type"]->graphql.schema.GraphQLObjectType["fieldDefinitions"]->java.util.ArrayList[3]->graphql.schema.GraphQLFieldDefinition["type"]->graphql.schema.GraphQLObjectType.......

**Comment by bbakerman** [comment]
the graphql schema and type system is self referential eg a cyclic graph.  

graphql by its very specification has a "introspection" system that allows the schema to be ..well instropected and documented

This is how tools like graphiql work.  They fire off introspection queries to the schema and it reports what it looks like

http://graphql.org/learn/introspection/
https://github.com/graphql/graphiql

There are also static tools for generating documentation from a schema as well.  I think you might want to check those out

**Comment by bbakerman** [comment]
for example : https://www.npmjs.com/package/graphql-docs

https://github.com/2fd/graphdoc

**Comment by opshubdata** [comment]
Great!!.

Thanks a lot for saving our time and suggesting best solution.
