### ISSUE TITLE
GraphQL Date and Time scalars

### ISSUE THREAD

**Issue by donbeave** [graphql-java/graphql-java#564]
Hello, guys!

I just published `graphql-java-datetime`, which can serialize Date and Time in GraphQL:
https://github.com/donbeave/graphql-java-datetime

I think it's one of the commons scalars what people need to use when they start to migrate to GraphQL, what about transfer this project to https://github.com/graphql-java?

Best regards,
  Alexey Zhokhov.

**Comment by andimarek** [comment]
Hi @donbeave,

thanks for the hint and thanks for the projects, but currently we don't add new projects to the organisation: We are a small team and just maintaining the current projects is challenging. 

Our way of promoting of related projects is the awesome-list: https://github.com/graphql-java/awesome-graphql-java 

I am happy to accept a PR there.

Cheers,
Andi

**Comment by donbeave** [comment]
Hi @andimarek 

Thank you, understand.

I just created PR: https://github.com/graphql-java/awesome-graphql-java/pull/6

Best regards,
Alexey Zhokhov.

**Comment by jdorleans** [comment]
@donbeave It'd be nice to have your lib not depending on spring, but rather a raw date/time support. Have you consider doing this?
