### ISSUE TITLE
new release date for graphql-java 4.x

### ISSUE THREAD

**Issue by guy120494** [graphql-java/graphql-java#568]
I would like to know when a new version  is expected to be released .
There are fixes in the master (for example null issue), that are not included in the current release.

**Comment by bbakerman** [comment]
We are aiming for an end of August release.

We may create a 4.x-alphaN in the meantime if the release runs over

**Comment by imrikoch1212** [comment]
Do you know if it will contain any breaking changes from the current release?

**Comment by andimarek** [comment]
@imrikoch1212 yes, it contains some breaking changes, but as always we aim for "simple" changes meaning you get a clear upgrade path.

you can get a preview of the breaking changes here: https://github.com/graphql-java/graphql-java/pulls?q=is%3Apr+is%3Aclosed+milestone%3A4.0.0+label%3A%22breaking+change%22

**Comment by soudmaijer** [comment]
Hi, really looking forward to the 4.0 release. Would love to start using the AsyncExecutionStrategy.

Would be nice if you could publish some milestones to a maven repository that last a bit longer than a day (bintray) ;-)

Thanks for the great work so far!!!

**Comment by andimarek** [comment]
@soudmaijer I am sorry, but we don't have the time or resources to publish milestones to maven. Please use the development build if you wanna test it before release. Thanks and I hope you understand!

**Comment by raderio** [comment]
@andimarek can I help with publishing milestones to maven? What I need to do?

**Comment by andimarek** [comment]
@raderio thanks for the offer, but there is nothing you can do: you can build it yourself or use use a development build via bintray. If you can't do both you will have to wait until we release the new version..

**Comment by raderio** [comment]
https://github.com/graphql-java/graphql-java/releases/tag/v4.0

**Comment by andimarek** [comment]
closing this now, because 4.0 is released
