### ISSUE TITLE
DataFetchingEnvironment creation

### ISSUE THREAD

**Issue by FernsPaanakker** [graphql-java/graphql-java#57]
The DataFetchingEnvironment which is created in the ExecutionStrategy.java uses executionContext.getRoot() (line 37) but in the DataFetchingEnvironment itself, the parameter is named context. Shouldn't the executionContext.getRoot() be replaced with executionContext? That way, the whole executionContext is available within the DataFetcher.

I changed this in my fork to be able to add errors from within the DataFetcher (I use this for server-side input validation in mutations).

**Comment by andimarek** [comment]
`ExecutionStrategy` is a non "public" class, so I don't think it should become a part of the API.

But yes: The naming might be a bit confusing. 

I'm also interested: You changed it in you fork. What part of the `ExecutionStrategy` are you using. Maybe we can add this to the instead the `DataFetchingEnvironment` instead the whole object to support your use case.

**Comment by FernsPaanakker** [comment]
I didn't mean that I think that ExecutionStrategy should become part of the API. I propose that in the file ExecutionStrategy.java, in the function resolveField we change this:        DataFetchingEnvironment environment = new DataFetchingEnvironment(                source,                argumentValues,                executionContext.getRoot(),                fields,                fieldDef.getType(),                parentType,                executionContext.getGraphQLSchema()        );
to this:        DataFetchingEnvironment environment = new DataFetchingEnvironment(                source,                argumentValues,                executionContext,                fields,                fieldDef.getType(),                parentType,                executionContext.getGraphQLSchema()        );
That way I can access the context from the DataFetchingEnvironment in a DataFetcher and add errors. Some sample code inside a DataFetcher:
<snip>    			.dataFetcher(new DataFetcher() {    					@Override    					public Object get(DataFetchingEnvironment environment) {    						if (environment.getContext() instanceof ExecutionContext) {    							ExecutionContext context = (ExecutionContext)environment.getContext();    							if (!"justATest".equalsIgnoreCase(vehicle.getNumberPlate())) {    								DataValidationError error = new DataValidationError("numberPlate","Invalid number plate");    								context.getErrors().add(error);    							}    						}<snip>
I apologize for the whacky code inserts, but I hope the proposed change and the usage example does make things more clear.
Date: Sat, 2 Jan 2016 00:57:10 -0800

**Comment by andimarek** [comment]
@FernsPaanakker I'm sorry and don't want to be rude, but could you please edit your last comment and format the code properly? It's really not readable. Thanks.

**Comment by FernsPaanakker** [comment]
@andimarek No problem, the github 'reply using email' made a mess of formatting the code. I should be better now.

**Comment by dminkovsky** [comment]
Hi, thank you for posting. I believe this issue is related to a misunderstanding of how GraphQL execution works and confusion around the root (passed to `GraphQL#execute()`) and "source" from `DataFetchingEnvironment#source()` in the DataFetcher, and even the "execution context" which is an API. We should improve documentation, but I am closing this as this is not a big/not something we'll change. Thanks.
