### ISSUE TITLE
Coercing class Javadoc

### ISSUE THREAD

**Issue by jameskleeh** [graphql-java/graphql-java#572]
The javadoc for the Coercing class has very little detail and I don't understand how the different methods will be used. I'm creating this issue to get a better understanding of the class and to recommend a more thorough javadoc to help others in the future.

In addition, it would be great if the provided scalars were actual classes so they can be extended more easily

**Comment by bbakerman** [comment]
By all means we could improve the javadoc.

However the standard Scalar types are meant to be singleton instances and are not designed to be extended at all.

Scalars.GraphQLString is the one and only instance of the String scalar say.  Same for all the others

**Comment by jameskleeh** [comment]
@bbakerman Thanks for the response. Given the scalars are not used by this library itself and instead are for usage by users, it doesn't make much sense to me why they would be designed in a way that isn't extensible. That was just a side note however and I didn't intend to distract from the main reason for creating this issue.

**Comment by bbakerman** [comment]
Scalars are meant to be the "end" of the logical tree in graphql queries

So the built in String / Int / ID / Long and so on are meant to defined as primitive values that are accepted in a standard format and output in a standard way.

This is the role of the Coercing code to decide how that standard way is implemented

From

http://graphql.org/learn/schema/#scalar-types

>  In most GraphQL service implementations, there is also a way to specify custom scalar types. For example, we could define a Date type:

> scalar Date

> Then it's up to our implementation to define how that type should be serialized, deserialized, and validated. For example, you could specify that the Date type should always be serialized into an integer timestamp, and your client should know to expect that format for any date fields.

So if there were designed to be re-useable it would suggest they are flexible in their accepted formats... which they are not. (not really)

The spec prescribes behaviours for the standard scalars

http://facebook.github.io/graphql/#sec-Scalars

Using singletons is way for the library to ensure that the behaviour stays according to spec.

but as you say we could improve the documentation for those writing their own custom scalars

**Comment by jameskleeh** [comment]
@bbakerman Thanks for the javadoc update.

Re: https://github.com/graphql-java/graphql-java/pull/585/files#diff-dc68e8d611d1400df42325428aee3043R44

Will the input to `parseValue` be an instance of `graphql.language.Value`?

**Comment by jameskleeh** [comment]
Also in regards to the specification for Scalars, currently (2.4.0) they throw an exception, and do not raise a query error per what the spec says. 

"If the integer input value represents a value less than -231 or greater than or equal to 231, a query error should be raised."

Is there any way to raise a query error with a custom scalar type in version 2.4 ?

**Comment by bbakerman** [comment]
The Scalar code was revisited in 3.0 because it was incorrect according to spec

You will need to upgrade to get that fix

parseValue will be Java objects as passed in via the variables mpa on the query

**Comment by jameskleeh** [comment]
@bbakerman Can you explain how the Scalars raise query errors in 3.0 ? As far as I can see, exceptions are still thrown instead of a query error being raised.

https://github.com/graphql-java/graphql-java/blob/v3.0.0/src/main/java/graphql/Scalars.java#L79

Thanks!
