### ISSUE TITLE
GraphQLFieldDefinition is not being created with the FieldDefinition.

### ISSUE THREAD

**Issue by mikeparisstuff** [graphql-java/graphql-java#574]
GraphQLFieldDefinitions are not being provided the FieldDefinition during instantiation. I believe this method (https://github.com/graphql-java/graphql-java/blob/58f22a6535eff9c884d4bccec97377ab6359e610/src/main/java/graphql/schema/idl/SchemaGenerator.java#L448) should be passing the FieldDefinition `fieldDef` to the builder so it can be retrieved later.

**Comment by bbakerman** [comment]
This is missing on more than fields.  All of the graphql runtime types have "definitions" that needs to be transferred.

If I recall that "definitions" were missing so I made another PR to add that and then forgot to circle  back and make SchemaGen put them in place

**Comment by mikeparisstuff** [comment]
Thanks for the fix :)
