### ISSUE TITLE
Can't set null using mutation - graphql treats null as EnumValue

### ISSUE THREAD

**Issue by Don4ik** [graphql-java/graphql-java#578]
I'm using graphql-java 2.3.0.
I'm trying to set null to some fields and each time i receive:

**Query:**
```
  mutation {
    UPDATE_User(

      id:3,
      type: null
    ) {id}
  }
```

**Response:**
```
{
  "errors": [
    {
      "validationErrorType": "WrongType",
      "message": "Validation error of type WrongType: argument value EnumValue{name='null'} has wrong type",
      "errorType": "ValidationError",
      "locations": [
        {
          "line": 5,
          "column": 7
        }
      ]
    }
  ],
  "data": null
}
```

It treats null as EnumValue. Why?

**Comment by kaqqao** [comment]
Neither the version you-re using (2.3.0) nor the current stable (3.0) support the `null` keyword, and unquoted stings are normally enum values in GraphQL, so this why you're getting the error.
The current master does support `null`, so apart from waiting for the next stable release (aimed for end of August, I believe), you could use a nightly build from https://bintray.com/andimarek/graphql-java/graphql-java or build master yourself.

Do note that `null` itself is rather recent addition to the GraphQL specification.
