### ISSUE TITLE
NonNullableFieldWasNullException not properly handled in the SimpleExecutionStrategy

### ISSUE THREAD

**Issue by joostlammers** [graphql-java/graphql-java#581]
The SimpleExecutionStrategy will check, in case of an error, whether the parentTypeInfo is nonNull and if so, rethrow the NonNullableFieldWasNullException on to the next level.

``` 
 ExecutionTypeInfo typeInfo = e.getTypeInfo();
 if (typeInfo.hasParentType() && typeInfo.getParentTypeInfo().isNonNullType()) {
      throw e;
 }
```

However, since the exception does not change, the next level will again rethrow.
This assert logic does not check the typeInfo of the current 'level' of the GraphQL tree, but only the typeInfo within the exception which never changes.
So, whenever a hierarchy of more than 2 levels is involved, this logic fails.
The unit tests also only test 2 levels deep.

Correct handling for 2 levels:
```
parent  nullable 
   child - nonNullable but still null
```
Returned: data: `{parent : null}`

Invalid scenario
``` 
top - nullable
    parent - nonNullable
        child - nonNullable but still null
```
Excepted result: `data: {top : null}`
Returned: `data: null`

To fix, change:
```  
TypeInfo typeInfo = e.getTypeInfo();
 if (typeInfo.hasParentType() && typeInfo.parentTypeInfo().typeIsNonNull()) {
```
into this:
``` 
TypeInfo typeInfo = parameters.typeInfo();
if (typeInfo.typeIsNonNull()) {
```

**Comment by bbakerman** [comment]
Nice catch.  Working on a PR now
