### ISSUE TITLE
Differentiating between provided null values in input argument

### ISSUE THREAD

**Issue by yarinvak** [graphql-java/graphql-java#584]
I have looked into a closed issue discussing a problem in the current release- the impossibility to differentiate between a field that is set to null in the input object, and a field that is not set at all. They both are initialized as nulls in the created hashmap. 
You have agreed to deal with this issue and said that it will get into the 4.x release, but I wanted to ask and be sure that the next release is going to contain a solution for this.

**Comment by yarinvak** [comment]
https://github.com/graphql-java/graphql-java/pull/434 the closed pull request discussing this issue

**Comment by bbakerman** [comment]
Definitely fixed in the too be released 4.x branch

**Comment by bbakerman** [comment]
Since we closed previous issue I am going to close this one as well (to keep things neat)
