### ISSUE TITLE
DataFetchingEnvironment.getSelectionSet() works for object type only (i.e. not for lists).

### ISSUE THREAD

**Issue by mikeparisstuff** [graphql-java/graphql-java#595]
A field `user(id: ID!): User` will returns the correct selection set from `dataFetchingEnv.getSelectionSet().get()` but a field `users: [User]` returns and empty set for `dataFetchingEnv.getSelectionSet().get()`.

I haven't dug in enough to find out where the issue materializes yet.

**Comment by bbakerman** [comment]
Can you please send in a reproduction query and schema so we can more easily fix this

**Comment by bbakerman** [comment]
I have the offending code

```
    public static DataFetchingFieldSelectionSet newCollector(ExecutionContext executionContext, GraphQLType fieldType, List<Field> fields) {
        if (fieldType instanceof GraphQLObjectType) {
            return new DataFetchingFieldSelectionSetImpl(executionContext, (GraphQLObjectType) fieldType, fields);
        } else {
            // we can only collect fields on object types.  Scalars, Interfaces, Unions etc... cant be done.
            // we will be called back once they are resolved however
            return NOOP;
        }
    }

```

The problem is we are only handle ObjectTypes but we are not unwrapping List / Non null ness from the type

**Comment by mikeparisstuff** [comment]
Awesome this looks exactly like the issue.
