### ISSUE TITLE
Is there a Contributor License Agreement for this project?

### ISSUE THREAD

**Issue by fmoloney** [graphql-java/graphql-java#61]
Some companies using this project can't contribute back without one.

**Comment by andimarek** [comment]
No there is none yet. 
Do you personally (or your company) need one?

**Comment by trackzer0** [comment]
Yeah we've been using it lately and I was told we can't contribute bugfixes or anything without a CLA.

**Comment by trackzer0** [comment]
It's a company btw, if it was up to me I'd just start contributing.

**Comment by andimarek** [comment]
@trackzer0 I understand and appreciate any help. I will look into that and try to find a solution.

**Comment by drkarl** [comment]
Any updates on this? I saw you added a [Code of Conduct](https://github.com/andimarek/graphql-java/blob/master/CODE_OF_CONDUCT.md) but unfortunately that doesn't serve as CLA, the lawyers wouldn't let us contribute without that :cry:

**Comment by okorz001** [comment]
I am also curious when a CLA will be available.

**Comment by mduarte** [comment]
I would also need a CLA to be able to contribute.

**Comment by andimarek** [comment]
Thanks everybody for your interest to contribute ... I really would like to make it possible.
To help moving forward could you please post/reference an acceptable CLA? I don't want to maintain multiple CLAs.
Also: The CLA would be signed with me personally. This is a private project with no organization/company behind it. Is this ok for you all? 
@trackzer0 @mduarte @okorz001 @drkarl

**Comment by andimarek** [comment]
closing it for now: we don't currently plan to add a cla to this project. If we get more feedback that it is needed, we will reconsider.
