### ISSUE TITLE
Apollodata Optics client

### ISSUE THREAD

**Issue by BattleBeaver** [graphql-java/graphql-java#617]
Can anybody advise regarding possibility of creating java client for Apollodata Optics client? Or similar tool for monitoring GraphQL APIs?
https://optics.apollodata.com/

**Comment by bbakerman** [comment]
I have been in discussion with Apollo regarding instrumentation and have also looked into whats involved.

They are proposing a new standard where the engine gives back standardized tracing information

https://github.com/apollographql/apollo-tracing

The new graphql 4.x (master) has support for this.  

See `graphql.execution.instrumentation.tracing.TracingInstrumentation`

There is no current Optics agent for java that I know that reports in the older protobuf msg format.

**Comment by BattleBeaver** [comment]
cool, thank you, @bbakerman!

**Comment by bbakerman** [comment]
Answered
