### ISSUE TITLE
HelloWorld example will not running successfully

### ISSUE THREAD

**Issue by tylerhjones** [graphql-java/graphql-java#627]
```
Exception in thread "main" SchemaProblem{errors=[There is no top level schema object defined]}
	at graphql.schema.idl.SchemaGenerator.makeExecutableSchema(SchemaGenerator.java:151)
	at com.jive.api.graphs.service.HelloWorld.main(HelloWorld.java:27)
```

line 27 for me is https://github.com/graphql-java/graphql-java/blob/master/src/test/java/HelloWorld.java#L25

java version "1.8.0_77"
graphql-java version "3.0.0"

The hello world is a copy paste with package line added, yet it will not execute without an error

**Comment by andimarek** [comment]
Hi @tylerhjones,

the hello world you are referring to requires the latest not released version of graphql-java.

Please have a look here for the documentation for 3.0.0: http://graphql-java.readthedocs.io/en/stable/getting_started.html

Thanks!

**Comment by tylerhjones** [comment]
ah ok, thank you

**Comment by Tanmay1192** [comment]
@andimarek  I'm getting same exception when try to run project via CLI whereas its working fine when run via IDE (Eclipse).
Details :
https://stackoverflow.com/q/65168270/4644974
