### ISSUE TITLE
How to avoid recursive queries?

### ISSUE THREAD

**Issue by cliren** [graphql-java/graphql-java#633]
GraphQL spec says https://facebook.github.io/graphql/#sec-Fragment-spreads-must-not-form-cycles, has this been implemented in graphql-java and if so how is is this enforced?

**Comment by andimarek** [comment]
We have this validation rule: https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/validation/rules/NoFragmentCycles.java

**Comment by andimarek** [comment]
I am closing this issue, because there is nothing to do for us now 

@cliren I hope this answered your question.
