### ISSUE TITLE
Implemented IDL type of a interface not detected

### ISSUE THREAD

**Issue by cjwchonjac** [graphql-java/graphql-java#638]
In IDL, if implemented type of a interface not used in AST, GraphQL schema does not contains definition of the type. something like this:
Query {
  queryA: A
}
interface A {
  id: ID
}

type B implements A {
  id: ID
  data: String
}
for above case, only interface type A detected in makeExecutableSchema.

**Comment by bbakerman** [comment]
This has been fixed in 4.x aka master.  It now adds the "additional types" into the schema
