### ISSUE TITLE
ExecutionResultImpl ctor bug?

### ISSUE THREAD

**Issue by undernorthernsky** [graphql-java/graphql-java#639]
Just browsing, but comparing L27 and L31 of https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/ExecutionResultImpl.java#L27 shouldn't both ctors check data != null?

**Comment by andimarek** [comment]
@undernorthernsky thanks for reporting. Yes I think this should be fixed.

Would you like to make a PR for that? That would be awesome. Thanks a  lot.

**Comment by bbakerman** [comment]
turns out its the other way around - if you take a data object (null or not) then the data is considered present

**Comment by andimarek** [comment]
this is fixed by #643 ...
