### ISSUE TITLE
Example using server + database

### ISSUE THREAD

**Issue by raderio** [graphql-java/graphql-java#644]
Please add an example using a server + fetching data from database, it will be very useful.
Thanks.

**Comment by andimarek** [comment]
I am sorry, but we will not provide a example for getting data from a database: `graphql-java` lets you implement the `DataFetchter` Interface, but is not concerned with where the data comes from. 
For a starting point see our documentation about it: http://graphql-java.readthedocs.io/en/stable/schema.html#datafetcher-and-typeresolver

Thanks

**Comment by raderio** [comment]
At least you can provide a full application about DataFetcher and TypeResolver.

For example it is not clear to me 
```
DataFetcher<Foo> fooDataFetcher = environment -> {
        // environment.getSource() is the value of the surrounding
        // object. In this case described by objectType
        Foo value = perhapsFromDatabase(); // Perhaps getting from a DB or whatever
        return value;
}

GraphQLObjectType objectType = newObject()
        .name("ObjectType")
        .field(newFieldDefinition()
                .name("foo")
                .type(GraphQLString)
                .dataFetcher(fooDataFetcher))
        .build();
```

why type is GraphQLString, it should be Foo?

**Comment by andimarek** [comment]
yes, you are right: of course we could improve our documentation and provide are more complex example. But every full application example needs to be maintained and is time consuming to create in the first place and we didn't have time and the resources to do it so far.

I can recommend asking questions in our gitter channel: https://gitter.im/graphql-java/graphql-java and I can recommend this introduction: https://www.howtographql.com/graphql-java/0-introduction/
