### ISSUE TITLE
GraphQL pre-approved queries

### ISSUE THREAD

**Issue by raderio** [graphql-java/graphql-java#646]
Dows graphql-java support pre-approved queries?

https://www.reddit.com/r/reactjs/comments/5aemkc/if_graphql_servers_are_only_going_to_accept/

**Comment by andimarek** [comment]
No, graphql-java doesn't support pre-approved queries currently.

**Comment by raderio** [comment]
But is it planned?

**Comment by andimarek** [comment]
No ... currently it is not planned. I am also not sure this is something `graphql-java` should implement at all: As far as I understand it it could easily be added on top of `graphql-java`.

**Comment by raderio** [comment]
https://github.com/graphql-java/graphql-java/issues/335
