### ISSUE TITLE
Upload file(image)

### ISSUE THREAD

**Issue by raderio** [graphql-java/graphql-java#652]
Please add an example of how to upload a file(image).

**Comment by andimarek** [comment]
I am sorry, but this will not happen: uploading a file is out of scope for `graphql-java`.

I recommend asking in our gitter channel and or at SO for help.

**Comment by raderio** [comment]
> When executing an operation, you can optionally provide a context. If you put the uploaded binary (or entire HttpRequest object) there, you can get a hold of it from DataFetcher

**Comment by raderio** [comment]
https://github.com/facebook/graphql/issues/349#issuecomment-326064720

**Comment by loganvolkers** [comment]
If someone is looking to implement this, here is a proposed spec that uses multipart upload: https://github.com/jaydenseric/graphql-multipart-request-spec
