### ISSUE TITLE
Error > Encoding a \ or new line character inside the JSON

### ISSUE THREAD

**Issue by MartinX3** [graphql-java/graphql-java#662]
The Character '\' for new line is not allowed in the curl statement, if it is put inside the json.

curl --request POST   --url http://localhost:8080/v1/graphql \    **_<- Allowed._**
    --header 'content-type: application/json' \    **_<- Allowed._**
    --data '{"query":"query {categories(filter: { name: \"Dried\" })  \    **_<- This one is not allowed._**
        {id name}}","variables":"{}"}';

Same with an invisible new line character.

Here is the error:
`{"timestamp":1503920520738,"status":400,"error":"Bad Request","exception":"org.springframework.http.converter.HttpMessageNotReadableException","message":"JSON parse error: Illegal unquoted character ((CTRL-CHAR, code 10)): has to be escaped using backslash to be included in string value; nested exception is com.fasterxml.jackson.core.JsonParseException: Illegal unquoted character ((CTRL-CHAR, code 10)): has to be escaped using backslash to be included in string value\n at [Source: java.io.PushbackInputStream@1b1e7e6; line: 1, column: 29]","path":"/v1/graphql"}`

In [GraphiQl](https://github.com/skevy/graphiql-app) I can write
`{categories(filter: { name: "Dried" }) \`
`{id name}}`
and there it works.

Is there a parsing error inside GraphQL or CURL?

**Comment by martin-g** [comment]
The GraphiQL example is not the same as the failing one.
In the failing one you have a backslash followed by a new line character. In the GraphiQL there is no new line. The error message comes from Jackson and says that there is a problem with code=10, i.e. LF, not the backslash.

**Comment by MartinX3** [comment]
Thanks for your fast response.
There is a new linke character. Github killed the new line after the \
I look, if I can reformat this issue code block.

**Comment by bbakerman** [comment]
I dont tihnk this is a problem in the graphql-java library.  It does NO JSON interpretation on input and output.

What framework and graphql wrapper library are you using?

**Comment by MartinX3** [comment]
I'm using this one for spring boot:
[graphql-spring-boot-starter](https://github.com/merapar/graphql-spring-boot-starter)

**Comment by bbakerman** [comment]
Can you please report that problem again that project then.  This is not a graphql-java problem.

if it turns out to be a graphql-java problem can you re-raised a new ticket with more detail on exactly what graphql-java (the base library) is doing wrong.
