### ISSUE TITLE
`MaxQueryDepthInstrumentation` and `MaxQueryComplexityInstrumentation` fail with mutations

### ISSUE THREAD

**Issue by drewolson** [graphql-java/graphql-java#665]
Both of these implementations fail with a null pointer exception when the request is a mutation. I'm suspicious it is related to [this line](https://github.com/graphql-java/graphql-java/blob/eafa3a31e6081b36e075273c77cb1c4c4f3f3fca/src/main/java/graphql/analysis/QueryTraversal.java#L54) which seems to assume the request is a query.

**Comment by andimarek** [comment]
@drewolson thank you for reporting. This PR #666 should fix that. Can you confirm that? Thanks!

**Comment by drewolson** [comment]
This looks like the right fix. I'm unsure of how to test these in-progress fixes via maven.

Also, I agree that this should be released as `4.0.1` if you're willing to do it.

**Comment by andimarek** [comment]
@drewolson We just released version 4.1. Please try it out ... thanks!
