### ISSUE TITLE
Remove unnecessary limitation regarding BatchedExecutionStrategy and GraphQLList types

### ISSUE THREAD

**Issue by arlampin** [graphql-java/graphql-java#667]
On [BatchedExecutionStrategy.java#L204](https://github.com/graphql-java/graphql-java/blob/02f34e6f870395332bb3c1819b0f3914f76e0a3a/src/main/java/graphql/execution/batched/BatchedExecutionStrategy.java#L204) DataFetcher return value is cast to Java `List<Object>`, which I feel is an unnecessary restriction, as it is merely iterated over. Instead, value should be cast to `Collection<?>` (or even `Iterable<?>`?).

I haven't checked if other build-in execution strategies have the same restriction, but if they do, the above also applied to them.

Thoughts?

**Comment by andimarek** [comment]
yes I think we can loosen that restriction ... I don't see a reason why not.

**Comment by bbakerman** [comment]
PR up
