### ISSUE TITLE
Possible incorrect MaxQueryComplexityInstrumentation calculation

### ISSUE THREAD

**Issue by drewolson** [graphql-java/graphql-java#671]
I created [this test](https://github.com/drewolson/graphql_npe_example/blob/da40969b8196a55fadd8f1a5f9995ffb337ab193/src/test/java/MaxComplexityTest.java) which I expect to pass, but it fails.

Right now, the `MaxQueryComplexityInstrumentation` thinks the total complexity of the provided query is `1`, but I would have expected it to be `3` (there are 3 fields requested and my complexity calculator returns a constant value of `1` per field).

This may be a bug or it may be a misunderstanding on my part of how the complexity calculation is supposed to happen.

**Comment by andimarek** [comment]
the calculation is correct: if you always return 1 the overall complexity of your example query is 1.

The Calculator calculates the complexity based on the sum of of complexity values of its childs. So if you wanna have every field count as one, the Calculator should look like this ` (env, childComplexity) -> childComplexity + 1`. This is also the default one.
