### ISSUE TITLE
Optional support in BatchedExecutionStrategy

### ISSUE THREAD

**Issue by joesankey** [graphql-java/graphql-java#673]
Looks like Optional unboxing has not been added to BatchedExecutionStrategy yet.

Should BatchedExecutionStrategy delegate more of the resolution to the parent class so it picks up changes like Optional unboxing?

**Comment by bbakerman** [comment]
> Should BatchedExecutionStrategy delegate more of the resolution to the parent class so it picks up changes like Optional unboxing?

yes it should.  Thanks for reporting... PRs are also welcome ;)
