### ISSUE TITLE
Question regarding filtering on query

### ISSUE THREAD

**Issue by zacyang** [graphql-java/graphql-java#688]
I am working on a spike on adopting graphql on one of our APIs. 

For filtering, I've manged to achieve the functionality by introduce query parameters as suggested on 
[Passing Arguments](http://graphql.org/graphql-js/passing-arguments/)

After that, I found a handy out-of-box solution from graphcool which provides a filter on type functionality.
[Filtering by field](https://www.graph.cool/docs/reference/simple-api/filtering-by-field-xookaexai0/)

Does graphql-java support something similar? 

Thanks

**Comment by andimarek** [comment]
I am sorry, but graphql-java doesn't provide any special support for filtering the response (as graphcool does)

And I don't think it will, because it is out of scope: defining arguments to fields and decide what they mean is extremely domain specific.

**Comment by andimarek** [comment]
closing this issue because there is nothing to do currently
