### ISSUE TITLE
Trying to implement date as custom scalar

### ISSUE THREAD

**Issue by rsmkrishna** [graphql-java/graphql-java#691]
I am trying to get hands-on on creating custom scalar. so took existing implementation of graphqldate example and trying to replicating same . getting failed. Graphql version is 3.0.0

`public class GraphQLDate extends GraphQLScalarType {

    public GraphQLDate() {
        super("Date", "Date type", new Coercing<Date, String>() {
            private Date convertImpl(Object input) {
                if (input instanceof String) {
                    LocalDateTime localDateTime = DateTimeHelper.parseDate((String) input);

                    if (localDateTime != null) {
                        return DateTimeHelper.toDate(localDateTime);
                    }
                }
                return null;
            }

            @Override
            public String serialize(Object input) {
                if (input instanceof Date) {
                    return DateTimeHelper.toISOString((Date) input);
                } else {
                    Date result = convertImpl(input);
                    if (result == null) {
                        try {
							throw new Exception("Invalid value '" + input + "' for Date");
						} catch (Exception e) {
							// TODO Auto-generated catch block
							e.printStackTrace();
						}
                    }
                    return DateTimeHelper.toISOString(result);
                }
            }

            @Override
            public Date parseValue(Object input) {
                Date result = convertImpl(input);
                if (result == null) {
                    try {
						throw new Exception("Invalid value '" + input + "' for Date");
					} catch (Exception e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
                }
                return result;
            }

            @Override
            public Date parseLiteral(Object input) {
                if (!(input instanceof StringValue)) return null;
                String value = ((StringValue) input).getValue();
                Date result = convertImpl(value);
                return result;
            }
        });
    }

}`

`@Bean
    @ConditionalOnMissingBean
    public GraphQLDate graphQLDate() {
        return new GraphQLDate();
    }`

`SchemaParser schemaFile = SchemaParser.newParser()
											.file("getMessageDetails.graphql")
											.scalars(graphQLDate())
											.resolvers(
													queryRootResolver,
													messageDetailResolver,
													messageAttachmentResolver,
													linkDetailResolver,
													messageDetailRqstResolver)
											.dictionary(
													ServiceContext.class,
													MessageDetailRqst.class,
													MessageDetail.class,
													MessageAttachment.class,
													LinkDetail.class,
													NameValuePair.class,
													CustomMap.class)
											.build();
				
				gSchema = schemaFile.makeExecutableSchema();`

In Graphql schema file

'
scalar Date

type Query{
	getMessageDetails(serviceContext : ServiceContext, messageDetailRqst : MessageDetailRqst) : GetMessageDetailsResp
}

.
.
.
.
.

input ServiceContext {
	addnContext: Date
}
'

Getting below exception on start of my application.

Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [graphql.schema.GraphQLSchema]: Factory method 'getGraphqlSchemaByType' threw exception; nested exception is graphql.GraphQLException: type Date not found in schema
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
	... 54 common frames omitted
Caused by: graphql.GraphQLException: type Date not found in schema
	at graphql.schema.SchemaUtil.resolveTypeReference(SchemaUtil.java:217)
	at graphql.schema.GraphQLInputObjectField.replaceTypeReferences(GraphQLInputObjectField.java:44)
	at graphql.schema.SchemaUtil.resolveTypeReferencesForInputFieldsContainer(SchemaUtil.java:209)
	at graphql.schema.SchemaUtil.replaceTypeReferences(SchemaUtil.java:187)
	at graphql.schema.GraphQLSchema$Builder.build(GraphQLSchema.java:131)
	'
'

Do I need to add furthur more configuration. Please guide me correct way to create a customscalar. I have posted here after trying possible ways. lack of this topic too.

**Comment by bbakerman** [comment]
It looks like you are using one of the graphql-java based frameworks for your code?

Can you outline which one.  ?

I think your problem is more how you tell that framework about our custom scalar (which looks ok at a glance)

I think you will want to raise an issue with the framework project and not graphql-java itself since this project is about the base engine

**Comment by rsmkrishna** [comment]
Hi 

Thanks, for the quick reply. Can you help me with any proper documentation on "How to implement Customscalar type". As you said above one i refered to Graphql-datetime example from git.

Thanks in advance.

**Comment by andimarek** [comment]
@rsmkrishna maybe this will help you: https://github.com/donbeave/graphql-java-datetime

**Comment by rsmkrishna** [comment]
@andimarek , Thanks for your reply. 

yes I am refering above said link. I am trying to add one of the java scalar type file(GraphQLDate.java) in my local project. and i am getting below error 
'Caused by: graphql.GraphQLException: type Date not found in schema'

The only document i found greatful is "graphql-java.pdf". I am referring that. where i found one line 
".scalar(CustomScalar)" at page 11. But i don't find any class related to instance "CustomScalar".

Please guide to create and register a custom scalar type in graphql-java.

**Comment by rsmkrishna** [comment]
Here is the detail Error footpath.

Error starting Tomcat context. _Exception: org.springframework.beans.factory.UnsatisfiedDependencyException. Message: Error creating bean with name 'graphQLServletRegistrationBean' defined in class path resource [com/oembedler/moon/graphql/boot/GraphQLWebAutoConfiguration.class]: Unsatisfied dependency expressed through method 'graphQLServletRegistrationBean' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'graphQLServlet' defined in class path resource [com/oembedler/moon/graphql/boot/GraphQLWebAutoConfiguration.class]: Unsatisfied dependency expressed through method 'graphQLServlet' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'graphQLSchemaProvider' defined in class path resource [com/oembedler/moon/graphql/boot/GraphQLWebAutoConfiguration.class]: Unsatisfied dependency expressed through method 'graphQLSchemaProvider' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'getGraphqlSchemaByType' defined in class path resource [com/scb/s2b/journey/configuration/JourneyQueryParser.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [graphql.schema.GraphQLSchema]: Factory method 'getGraphqlSchemaByType' threw exception; nested exception is graphql.GraphQLException: type Date not found in schema_

**Comment by andimarek** [comment]
@rsmkrishna I am sorry: this is not a graphql-java problem. Please open an issue at https://github.com/graphql-java/graphql-spring-boot if it is not solved yet. Thanks

**Comment by bobdi98** [comment]
Why is this issue closed? I have the exact same problem as this. Is there a solution for this already?

**Comment by bbakerman** [comment]
@bobdi98 - the schema parser you are using is likely NOT the one in the graphql-java base library but rather one in another library - say the graphql-java-spring-boot one

Hence this issue is closed because we cant reproduce it using native graphql-java.

If you can write a iunit test demonstrating this then all the better
