### ISSUE TITLE
Issues when creating a new schema from an existing schema that has interfaces

### ISSUE THREAD

**Issue by drewolson** [graphql-java/graphql-java#698]
It seems that something related to interfaces is not copied over when creating a new schema from an existing schema. I've created a test to demonstrate the problem [here](https://github.com/drewolson/graphql_npe_example/blob/c8dd15128d22addc3f14aa0efc7a04941c83aed4/src/test/java/NewSchemaFromExistingTest.java).

[Here](https://github.com/drewolson/graphql_npe_example/blob/c8dd15128d22addc3f14aa0efc7a04941c83aed4/src/test/resources/test.idl) is the IDL used for the test.

**Comment by bbakerman** [comment]
This is now on master.  Thanks for reporting this bug
