### ISSUE TITLE
MaxQueryDepthInstrumentation is not traversing for GraphQLList

### ISSUE THREAD

**Issue by zjchen82** [graphql-java/graphql-java#705]
In QueryTraversal.visitField, this method do not cater for GraphQLList type which results in its depth is not been calculated.

**Comment by bbakerman** [comment]
a list if not a descent in field terms surely?

     type MyQuery
          list : [String]
          deep : [MyQuery]
    }

when we encounter the field list its depth 1 - its not how many items are in the list say.  Its how many fields deep the query is

if we had a query like

     query {
        deep {
            deep {
                list
            }
       }
     }

In that case the field tree is 4 levels deep

**Comment by andimarek** [comment]
@zjchen82  we can't use the length of the list, because query complexity is calculated before the query is actually executed. 

You can however provide a custom calculator and increase the complexity for the specific field

**Comment by zjchen82** [comment]
@bbakerman Understood that the depth is not related to the number of items in the list. 

The example with depth 4 is actually 2 by using graphql-java 4.1. The depth is 4 if the type in the example change to 
```
type MyQuery
      list : [String]
      deep : MyQuery
}
```

@andimarek Noted with thanks.
