### ISSUE TITLE
Support for Guava Optional

### ISSUE THREAD

**Issue by rj254** [graphql-java/graphql-java#723]
Would it be possible to support Guava Optionals as well as Java Optionals?

**Comment by andimarek** [comment]
I am sorry, but this is not so easy:

- We could add Guava as a dependency and check for Guava Optionals as well as for Java Optionals: The code itself is trivial, but we don't want to add Guava (or any other lib) as a dependency. So this is not an option.

- We could check with reflections if the returned values is of type guava optional and then handle it without having a compile dependency. We would need to make sure that it does not have an negative overall impact and in general such reflection code is rather not nice. So I am not sure about this ... if you are really interested in having Guava Optional support it would be great if you could a PR for that. But I can't promise if it gets merged.

Thanks!

**Comment by bbakerman** [comment]
I also echo the idea of that we NOT add Guava as a dependency.  Its very heavy weight dependency and we want to be as light as possible.

The code that does this is protected.  You can override it an a custom ExecutionStrategy say

```
    protected Object unboxPossibleOptional(Object result) {
        if (result instanceof Optional) {
            Optional optional = (Optional) result;
            if (optional.isPresent()) {
                result = optional.get();
            } else {
                result = null;
            }
        }
        return result;
    }
```

That is the current code. You could use

```
    class GuavaExecutionStrategy extends AsyncExecutionStrategy {
        @Override
        protected Object unboxPossibleOptional(Object result) {
            if (result instanceof Option) {
                return ((Option) result).get();
            }
            return super.unboxPossibleOptional(result);
        }
    }
```

**Comment by andimarek** [comment]
@bbakerman nice solution, didn't thought of that 👍

**Comment by rj254** [comment]
Thanks!
