### ISSUE TITLE
Add variableName to the NonNullableValueCoercedAsNullException

### ISSUE THREAD

**Issue by kirpi4ik** [graphql-java/graphql-java#730]
For a query with more `GraphQLNonNull` arguments, throwing exception only with generic message without argument name  `Null value for NonNull type 'String!` is not useful because we don't understand from message which exactly argument was null . I don't see any mechanism to return the argument name or other details from exception.
The only options is to extend `ValueResolver` and replace `coerceArgumentValues` with custom implementation which does not look as good option.
Since `variableDefinition.name` is already there, is it possible to pass also the variable definition  `name` to the `NonNullableValueCoercedAsNullException` ?

**Comment by bbakerman** [comment]
Great idea!
