### ISSUE TITLE
Have the ability to diff 2 schemas for breaking changes

### ISSUE THREAD

**Issue by bbakerman** [graphql-java/graphql-java#733]
Like the graphql-js reference lib we should have the ability to diff 2 schemas

https://github.com/graphql/graphql-js/blob/26023b30ff8dd083bdf60f2415909f18ebdda502/src/utilities/findBreakingChanges.js

Whether its based on 2 GraphQLSchema objects  or the result of an Introspection query or a mix of both is interesting.

I suspect for "contract" testing, you will like have new code in GraphQLSchema form and an existing target system (via HTTP Introspection say) and want to diff the two.

**Comment by andimarek** [comment]
see #744
