### ISSUE TITLE
GraphQL execution hooks

### ISSUE THREAD

**Issue by chrisregnier** [graphql-java/graphql-java#734]
I've been looking into creating a unique dependency injection scope for certain levels through the execution process. ie a type resolver scope similar to a singleton, request, or session scope so my data fetchers can inject things with the right lifecycle. 

So I'm wondering if there's any good ways to hook into the execution process to define clear scoping bubbles around each resolver?

**Comment by bbakerman** [comment]
You can use `graphql.execution.instrumentation.Instrumentation#instrumentDataFetcher` to instrument every DataFetcher in the system.

You can replace at runtime the DataFetcher that gets used.

How are you building your schema?  Per request or singleton?  Building the schema per request is quasi expensive but the schema is immutable at a build time.

Instrumentation allows you to substitute in a new DF given the current one defined on the schema.

Perhaps we need a "DataFetcherFactory" that can be put on a schema type and hence allow an indirection into the typically "static" schema.

**Comment by chrisregnier** [comment]
Definitely only creating the schema once. 

For more clarity into what I'm doing, I've setup my system to look for any methods annotated with GQLResolver and match the methods to the schema field requests. This is really nice for pulling in Query and Mutation resolvers into the same location, along with supporting fields that might not be directly on the models, as you can see in the example below. The declaring class can then also be used for storing a bunch of cache related objects as well. 

schema: 
```
type User {
  lname: String
  fname: String
  fullname(reverse: Boolean): String
}
type Query {
  currentUser: User
  users(filter: String): [User]
}
```
```java
public class User {
  public String fname;
  public String lname;
}

@QueryScope
public class UserResolver {
  @Inject private UserDAO userDAO;
  private LRUCache<String, User> userCache;

  @GQLResolver(type="Query", field="currentUser")
  public User currentUser(@GQLContext DataFetchingEnvironment env) {
      return ((ReqContext)env.context).currentUser;
  }

  @GQLResolver(type="Query", field="users")
  public Set<User> findUsers(@GQLParam("filter") String filter) {
      // also do stuff with cache here
      return userDAO.findUsersWhere(filter);
  }

  @GQLResolver(type="User", field="fullname")
  public String getFullName(@GQLParam("reverse") boolean reverse, @GQLSource User user) {
    return (reverse)? String.join(", ", user.lname, user.fname) : String.join(" ", user.fname, user.lname);
  }
}
```

In the example above I've got I've added a `@QueryScope`, which means the UserResolver class will be instantiated once for each query. This is easy to do cause this can be done outside of the query. But I was looking into creating some other scopes that would instantiate the declaring class for every time it's requested (ie each User would get a new scope).  

So I'll take a look a deeper look at Instrumentation cause I think that might be enough to do what I want. No need for a DataFetcherFactory for now, but thanks!
