### ISSUE TITLE
Have the ability to turn a Introspection query into a printed schema

### ISSUE THREAD

**Issue by bbakerman** [graphql-java/graphql-java#740]
Today you can make an introspection query and it gives you back Map<String,Object> of the result.

But you cant turn that into IDL say, or a schema even.  We should have this capability.

I envisage the ability to fire of a introspection HTTP request to a service and recreate the schema for testing purposes say or to document it via IDL

**Comment by andimarek** [comment]
we already have the ability to construct a schema from a introspection query: https://github.com/graphql-java/graphql-java/blob/0ea9d3cae254512b30966ac88b36effc200309d0/src/test/groovy/graphql/introspection/IntrospectionResultToSchemaTest.groovy#L545

**Comment by bbakerman** [comment]
Yeah I realise we can also parse a Document into a TypeRegistry and hence a schema proper.

So I will make this a tweak to SchemaPrinter to accept both Map<String, Object> introspectionResult and Document and hence allow you to print introspections that much easier
