### ISSUE TITLE
Throw RuntimeException when catch NoSuchFieldException in FieldDataFetcher

### ISSUE THREAD

**Issue by buptliuhs** [graphql-java/graphql-java#742]
```FieldDataFetcher.getFieldValue``` swallows ```NoSuchFieldException``` and return null.
It's very hard to detect a code defect (not having a getter for a GraphQL field) and the GraphQL always returns ```null``` value for that field. From my perspective, it's better to have an immediate failure at runtime in case the required getters are not defined/implemented.

**Comment by bbakerman** [comment]
The code in question is

     private Object getFieldValue(Object object) {
        try {
            return object.getClass().getField(fieldName).get(object);
        } catch (NoSuchFieldException e) {
            return null;
        } catch (IllegalAccessException e) {
            throw new RuntimeException(e);
        }
   }

I am torn as to whether to fix this or not.  I take your point that if you wire in a FieldDataFetcher("expectedField") then its hard to debug if you make spelling mistakes say

Conversely there are valid cases where you have a diverse range of objects being presented to the data fetcher and "expectedField" is not there.  graphql says that when you ask for field X and its not present then you should return null.

That is just like a map lookup.  If you do `map.get("expectedField")` then it wont blow up but return null.  Very much javascript semantics (where graphql originated)

You could create your own data fetcher to give you the strict semantics you want.  There is not a lot of code here.  Or we could make it  have 2 modes a "strict mode" and a normal mode.
I am leaning towards leaving it as it and recommending you create your own strict field fetcher.

Thoughts @andimarek ?

**Comment by buptliuhs** [comment]
I agree with you on your point by the example of map lookup. However, just imagine a database query using SQL, it will throw an error when some unknown fields in the query, and that's why I think having a ```strict mode``` of FieldDataFetcher by default is better. I'm using graphql-annotation btw (which means I did not spell the wrong words). I feel that it might be more suitable to implement the ```strict mode``` FieldDataFetcher in that according to your recommendation.
Thanks!
