### ISSUE TITLE
QueryTraversal doesn't work with Union types and __typename

### ISSUE THREAD

**Issue by david-tamjidi** [graphql-java/graphql-java#763]
Hi Guys,

I think i might have found a bug, it seems like the QueryTraversal class doesn't work with union types:

`java.lang.ClassCastException: graphql.schema.GraphQLUnionType cannot be cast to graphql.schema.GraphQLFieldsContainer
	at graphql.analysis.QueryTraversal.visitImpl(QueryTraversal.java:98)
	at graphql.analysis.QueryTraversal.visitField(QueryTraversal.java:165)
	at graphql.analysis.QueryTraversal.visitImpl(QueryTraversal.java:100)
	at graphql.analysis.QueryTraversal.visitField(QueryTraversal.java:165)
	at graphql.analysis.QueryTraversal.visitImpl(QueryTraversal.java:100)
	at graphql.analysis.QueryTraversal.visitField(QueryTraversal.java:165)
	at graphql.analysis.QueryTraversal.visitImpl(QueryTraversal.java:100)
	at graphql.analysis.QueryTraversal.visitPreOrder(QueryTraversal.java:64)
	at graphql.analysis.QueryTraversal.reducePreOrder(QueryTraversal.java:89)
	at graphql.analysis.MaxQueryDepthInstrumentation.lambda$beginValidation$1(MaxQueryDepthInstrumentation.java:31)`

This is with the 4.2 release but it looks like the QueryTraversal class hasn't changed in 5.0 yet. Will take a look and see if i can work out a patch.

-David

**Comment by david-tamjidi** [comment]
Here is a sample query which is triggering the error:

query {
    someObject {
       someUnionType {
          ___typename
          ... on TypeX {
           field1
         }
          ... on TypeY {
           field2
         }
     }
  }
}

**Comment by david-tamjidi** [comment]
Here is a hacky but simple fix to highlight the error:

`private void visitImpl(QueryVisitor visitor, SelectionSet selectionSet, GraphQLCompositeType type, QueryVisitorEnvironment parent, boolean preOrder) {

        for (Selection selection : selectionSet.getSelections()) {
            if (selection instanceof Field) {
            	 	GraphQLFieldDefinition fieldDefinition;
            		if(((Field) selection).getName().equals(TypeNameMetaFieldDef.getName())) {
            			fieldDefinition = TypeNameMetaFieldDef;
            		} else {
            			GraphQLFieldsContainer fieldsContainer = (GraphQLFieldsContainer) type;
            			fieldDefinition = getFieldDef(fieldsContainer, (Field) selection);
            		}
                visitField(visitor, (Field) selection, fieldDefinition, type, parent, preOrder);
            } else if (selection instanceof InlineFragment) {
                visitInlineFragment(visitor, (InlineFragment) selection, type, parent, preOrder);
            } else if (selection instanceof FragmentSpread) {
                visitFragmentSpread(visitor, (FragmentSpread) selection, parent, preOrder);
            }
        }
    }`

**Comment by bbakerman** [comment]
I can reproduce this bug via

```
    def "#763 handles union types"() {
        given:
        def schema = TestUtil.schema("""
            type Query{
                someObject: SomeObject
            }
            type SomeObject {
                someUnionType: SomeUnionType  
            }
            
            union SomeUnionType = TypeX | TypeY
            
            type TypeX {
                field1 : String
            }

            type TypeY {
                field2 : String
            }
        """)
        def visitor = Mock(QueryVisitor)
        def query = createQuery("""
            {
            someObject {
                someUnionType {
                    __typename
                    ... on TypeX {
                        field1
                    }
                    ... on TypeY {
                        field2
                    }
                }
            }
        }
            """)
        QueryTraversal queryTraversal = createQueryTraversal(query, schema)
        when:
        queryTraversal."$visitFn"(visitor)

        then:
        1 * visitor.visitField({ QueryVisitorEnvironment it -> it.field.name == "someObject" && it.fieldDefinition.type.name == "SomeObject" && it.parentType.name == "Query" })
        1 * visitor.visitField({ QueryVisitorEnvironment it -> it.field.name == "someUnionType" && it.fieldDefinition.type.name == "SomeUnionType" && it.parentType.name == "SomeObject" })
        1 * visitor.visitField({ QueryVisitorEnvironment it -> it.field.name == "__typename" && it.fieldDefinition.type.wrappedType.name == "GraphQLString"})

        where:
        order       | visitFn
        'postOrder' | 'visitPostOrder'
        'preOrder'  | 'visitPreOrder'

    }

```

as a Test inside QueryTraversalTest

I made this PR which currently fails

https://github.com/graphql-java/graphql-java/pull/765
