### ISSUE TITLE
Allow programmatic detection of error type

### ISSUE THREAD

**Issue by ind1go** [graphql-java/graphql-java#769]
Before `toSpecification` was introduced, a simple bean serialiser such as with Jackson would output all `get`table values, which on `GraphQLError` included the `ErrorType`. This came in handy for programmatic detection of error types by the client, in order to take different action.

`toSpecification` is very useful in that we can be more sure that the result will match the spec. However, I'd like to be able to see the `ErrorType`. I can't see a way to interject and override to add the `ErrorType` to the on-spec map.

**Comment by bbakerman** [comment]
@ind1go - If we allowed ErrorType into Map  toSpec() then ipso facto it would not meet spec.

We introduced it for those who want to follow spec strongly on execution result and errors.  For example stack traces may come with certain errors but some people dont want that (and others do)

Since you are in charge of JSON serialisation, simply pull apart the list of errors yourself, create what ever map of them suits you with what ever data you want and then serialize that.

**Comment by ind1go** [comment]
Well... to be exact it would still meet spec! 😄  [At the bottom of section 7.2.2](http://facebook.github.io/graphql/draft/#sec-Errors):
>  GraphQL servers may provide additional entries to error as they choose to produce more helpful or machine‐readable errors, however future versions of the spec may describe additional entries to errors.

I agree that there is a need to follow spec strongly and `toSpecification()` has definitely been an excellent improvement. I guess there are two parts that you want to meet in the spec - one is that the permitted elements are in the right order (if necessary - the top-level elements must meet a precise ordering, for example) and also have the right names. `toSpecification()` does a great job of these, and if I were adding my own fields I wouldn't want to have to re-write this logic, rather defer to the framework.

My suggestion is that it might be possible to delegate to the provided `toSpecification()` and then build on top of it for this type of customisation, perhaps with some kind of handler for the `ExecutionResult`. It would mean that all the specced fields are exactly right, but then there would be freedom for those machine-readable fields. At the moment, `ExecutionResultImpl.toSpecification()` defers straight to `GraphQLError.toSpecification()` and then on to `GraphqlErrorHelper.toSpecification()`, with no opportunity to intervene.

**Comment by andimarek** [comment]
I agree with @bbakerman that you are in control and add/modify the response as you wish. Adding more hooks/flexibility comes always with a cost and I don't see the value for this here at the moment.

You can always add your own GraphQLError to the response and implement `getExtension()` which is then placed inside the `extension`.

Additionally we now put `classification` into the error `extension` which I think is exactly what you were asking for. ( See `GraphqlErrorHelper`)
