### ISSUE TITLE
ConnectionCursor/Edge needs no argument constructor so Jackson can deserialize

### ISSUE THREAD

**Issue by bpatters** [graphql-java/graphql-java#77]
The ConnectionCursor.java and Edge.java class needs a nor argument constructor so that it can deserialize it.

**Comment by andimarek** [comment]
Hi,

what do you mean with deserialize it? 

Thanks

**Comment by bpatters** [comment]
When you send a ConnectionCursor to the server it needs to turn the JSON into a ConnectionCursor object in order to process it. The way Jackson handles this, without annotations which would't be appropriate here, is that it uses the no argument constructor to create the object and then set's the fields based on the properties received. Without this constructor Jackson can't turn JSON into a ConnectionCursor object without a @JsonCreator annotation on the constructor.

An easy test is to:
1. update build.gradle
testCompile("com.fasterxml.jackson.core:jackson-core:${jacksonVersion}");
    testCompile("com.fasterxml.jackson.core:jackson-databind:${jacksonVersion}");
2. Create a Simple test that:
ObjectMapper objectMapper = new ObjectMapper()
ConnectionCursor cursor = new ConnectionCursor("cursorValue");
cursor = objectMapper.readValue(objectMapper.writeValueAsString(cursor), ConnectionCursor.class);

The last line will blow up because it can't construct a ConnectionCursor object.

**Comment by andimarek** [comment]
closing it.
I don't think it is wise to make it work for Jackson: Jackson is flexible enough to handle it with additional config.
