### ISSUE TITLE
JSON Scalar best practice?

### ISSUE THREAD

**Issue by loganvolkers** [graphql-java/graphql-java#771]
We're using GraphQL to implement a custom `JSON` scalar that maps internally to a Jackson JsonNode.

What is the best practice for doing this? The challenge we're facing is the best way to turn an `ObjectValue` into a `Map<String,Object>` or a `JsonNode` for parsing inputs to mutations.

**Comment by loganvolkers** [comment]
I found this reference for GraphQL js for inspiration: https://github.com/taion/graphql-type-json/blob/master/src/index.js

**Comment by loganvolkers** [comment]
So we copied the approach from GraphQL.js.

 - Hopefully this helps other people implement custom scalars
 - Or the GraphQL.java maintainers tell us this is the wrong approach.

```java
    static JsonNode valueToJson(Value v) {
        if (v instanceof BooleanValue) {
            return JsonNodeFactory.instance.booleanNode(BooleanValue.class.cast(v).isValue());
        } else if (v instanceof EnumValue) {
            return JsonNodeFactory.instance.textNode(EnumValue.class.cast(v).getName());
        } else if (v instanceof FloatValue) {
            return JsonNodeFactory.instance.numberNode(FloatValue.class.cast(v).getValue());
        } else if (v instanceof IntValue) {
            return JsonNodeFactory.instance.numberNode(IntValue.class.cast(v).getValue());
        } else if (v instanceof NullValue) {
            return JsonNodeFactory.instance.nullNode();
        } else if (v instanceof StringValue) {
            return JsonNodeFactory.instance.textNode(StringValue.class.cast(v).getValue());
        } else if (v instanceof ArrayValue) {
            final ArrayNode result = JsonNodeFactory.instance.arrayNode();
            for (final Value v2 : ArrayValue.class.cast(v).getValues()) {
                result.add(valueToJson(v2));
            }
            return result;
        } else if (v instanceof ObjectValue) {
            final ObjectNode result = JsonNodeFactory.instance.objectNode();
            for (final ObjectField f : ObjectValue.class.cast(v).getObjectFields()) {
                result.set(f.getName(), valueToJson(f.getValue()));
            }
            return result;
        } else {
            throw new IllegalStateException(String.format("Unsupported value type: %s", v.getClass()));
        }
    }
```

**Comment by bbakerman** [comment]
If you want a JSON Scalar then this looks pretty good for the "literals" that might come into the system.

JSON is essentially a Map like scalar.  One thing to consider with Map like Scalars is that the breaking the symmetry of graphql query --> results.

For example a query

    {
       hero {
            name
            power
       }
    }

will produce a response like

     {
        "hero" : {
              "name" : r2d2",
               "power" : "beeping, whistling,  saving"
         }
     }

Note the symmetry - the response has the same shape as the response.  The leaf nodes (aka Scalars" have 1 value which map the leaf nodes of the query.

With a Map like Scalar you have a leaf node query field but NOT a leaf value in the response.  Imagine power is a Map like scalar as you have imlemented.

     {
        "hero" : {
              "name" : r2d2",
               "power" : {
                          "key1" : "beeping",
                          "key2" : "whistling",
                          "key3" : "saving"
                }
         }
     }

This is not to say that this is against spec but it does break the symmetry.  If you are happy with that then great.  

I think the reason graphql does not define a Map like scalar is that it wants you to "describe" all the addressable fields.  In the above you have no way of knowing (as a consumer) what the keys of the Map like scalar might be.  Again this might be ok but the query itself is not specifying them.

One thing I dont know is how well upstream graphql client libraries can handle your Map like scalar.  Will something like Relay or Appollo JS clients be able to intrinsically understand your map like Scalar?  I am not sure.  I guess its not worse than any other scalar but most scalars have a single value say and this one does not.

**Comment by loganvolkers** [comment]
Great concerns @bbakerman. The following is a list of tools that I have used that support a JSON Scalar over the past year (note that Graphql java and graphql-java-tools compatibility was confirmed today with the above code)

 - Apollo Client
 - [graphql-tools](http://dev.apollodata.com/tools/graphql-tools/scalars.html)
 - [graphql-js](https://github.com/taion/graphql-type-json/)
 - graphql-java
 - graphql-java-tools
 - graphiql
 - graph.cool

**Comment by bbakerman** [comment]
I am going to close this as an issue in the code BTW

**Comment by lorines** [comment]
@loganvolkers how did you implement the serializer in Java? I am trying to implement JSON scalar, but my query is returning an empty object instead of a JSON object.

**Comment by ryber** [comment]
@loganvolkers or @lorines also wondering how the Coercing works in this case for the serializer

If you return the JSON from Jackson as a string then, indeed you get JSON but it's jammed inside of a string
```
   {"data":{"body":"[]"}}
```

However if you try and return a Map version of the json then you get a parsing error. I'd really prefer to return the JSON as JSON and not as a string

**Comment by ryber** [comment]
For anyone who finds this. Returning a Jackson JsonNode works:

```
         private ObjectMapper om = new ObjectMapper();

        @Override
        public Object serialize(Object dataFetcherResult) throws CoercingSerializeException {
            try {
                return om.valueToTree(dataFetcherResult);
            } catch (Exception e) {
                throw new CoercingSerializeException(e);
            }
        }
```

**Comment by bbakerman** [comment]
See https://github.com/graphql-java/graphql-java-extended-scalars for a JSON scalar.
