### ISSUE TITLE
PropertyDataFetcher should more aggressively get values

### ISSUE THREAD

**Issue by bbakerman** [graphql-java/graphql-java#772]
If I have a Java type like

```
    static class Human implements Character {
        final String id;
        final String name;
        final List<String> friends;
        final List<Integer> appearsIn;
        final String homePlanet;

        public Human(String id, String name, List<String> friends, List<Integer> appearsIn, String homePlanet) {
            this.id = id;
            this.name = name;
            this.friends = friends;
            this.appearsIn = appearsIn;
            this.homePlanet = homePlanet;
        }

        public String getId() {
            return id;
        }

        public String getName() {
            return name;
        }

        public List<String> getFriends() {
            return friends;
        }

        public List<Integer> getAppearsIn() {
            return appearsIn;
        }

        public String getHomePlanet() {
            return homePlanet;
        }

        @Override
        public String toString() {
            return "Human{" +
                    "id='" + id + '\'' +
                    ", name='" + name + '\'' +
                    '}';
        }
    }
```

then PropertyDataFetcher will return null for `getName()` because this is not a public class.

HOwever this is very 1997 Java thinking.  Virtually every one expects it to work as getting into the getters defined.

GSON / Jackson / you name it work with this and use `setAcessible()` and so on to just work out of the box.

The error is very hidden and would put most people off

```
"message": "Cannot return null for non-nullable type: 'String' within parent 'Droid' (/hero/name)",
      "path": [
        "hero",
        "name"
      ]
```

I think graphql-java should be more aggressive in getting values from POJOs

**Comment by corydolphin** [comment]
Out of curiosity, why would you want to use the PropertyDataFetcher instead of a Method Reference?

**Comment by bbakerman** [comment]
@corydolphin - what is a Method Reference?  (also out of curiosity?)

**Comment by corydolphin** [comment]
It allows a nice shorthand for referring to a method to e.g fulfill a functional interface. 

My suggestion is that rather than have an implicit, reflection-based getter (which is slow, and would fail at runtime if it could not be found), to instead use a method reference to the getter for the property. 
https://docs.oracle.com/javase/tutorial/java/javaOO/methodreferences.html

**Comment by bbakerman** [comment]
Yeah the trick with graphql is that you are mapping an opaque object to a
named "field" at runtime not at code time

So there is no way to do a method reference that I know of since you dont
know the target object until the data fetcher runs.

So PropertyFetcher uses a reflective approach which by default is "field
name" --> POJO getter name.

So a field "name" maps to a JavaBean getName() and so on.

A method reference wont be possible to "hold" and apply to any opaque
object in java (that I know of - love to be shown how say)

**Comment by corydolphin** [comment]
What I'm suggesting is that instead of having it be "automagic", developers are simply required to set the data fetcher as a method reference, and the api could be made easier to use. I.E. in our usage, we have a wrapper, and thus our datafetchers for property-getters are just e.g. `ObjectName::getThing`

**Comment by bbakerman** [comment]
Yeah I think you are right

I have raised

https://github.com/graphql-java/graphql-java/pull/797
