### ISSUE TITLE
Unable to change DataFetcherExceptionHandler

### ISSUE THREAD

**Issue by ejdzipi** [graphql-java/graphql-java#776]
Hello, would it be possible to publish getter for dataFetcherExceptionHandler in ExecutionStrategy class? I need to replace SimpleDataFetcherExceptionHandler with my custom handler, but i don't want to mess with execution strategies. Thanks

**Comment by bbakerman** [comment]
Nope its not possible.  You're in charge of your own code.  

You wire together the execution strategies yourself and hence you need to wire in your custom handler at construction time.

What is preventing you from using the following?

     newGraphql(schema).queryExecutionStrategy(
            new AsyncExecutionStrategy(new MyCustomExceptionHandler())
    ).build();

**Comment by bbakerman** [comment]
We wont be making a fix here unless a better reason can be articulated

**Comment by ejdzipi** [comment]
As i am using graphql-java-servlet and graphql-java-tools, i need to provide my own ExecutionStrategyProvider and so on, which produce a lot of classes which are identical to default graphql-java classes just to change one exception handler.

**Comment by bbakerman** [comment]
I would take it up with the graphql-java-servlet and graphql-java-tools projects to be honest.

A final immutable design is what we are after
