### ISSUE TITLE
Handling of variable type errors does not conform to spec and appears inconsistent with graphql-js

### ISSUE THREAD

**Issue by filipncs** [graphql-java/graphql-java#786]
Currently, if a given variable does not conform to its declared type, a RuntimeException will be thrown when executing a query.

This does not conform to the spec, nor to any other graphql implementations I've been able to test against, including graphql-js.

Going through the relevant sections of the spec:

Section 6.1.2 specifies what happens when variable types mismatch: http://facebook.github.io/graphql/October2016/#sec-Coercing-Variable-Values

> If a **query error** is encountered during input coercion of variable values, **then the operation fails without execution**.
> ...
> ...
>       f. Otherwise, if value cannot be coerced according to the input coercion rules of variableType, **throw a query error**.

Section 7 describes how the response should look: http://facebook.github.io/graphql/October2016/#sec-Response

>  When a GraphQL server receives a request, *it must return a well‐formed response*. The server’s response describes the result of executing the requested operation if successful, and describes any errors encountered during the request.

There is no exception here for operations that fail without execution, and in fact section 7.2.1 explicitly describes how the response should look in this case: http://facebook.github.io/graphql/October2016/#sec-Response-Format

>  If the operation included execution, the response map must contain a first entry with key data. The value of this entry is described in the “Data” section. **If the operation failed before execution**, due to a syntax error, missing information, or validation error, this entry must not be present.

I guess this might be the biggest point of contention, as `query error` is not explicitly listed as one of the types of errors occurring before execution. However, as the spec does not give unambiguous descriptions of the different types of errors and their meanings, I think the most reasonable reading is that this specific type of query error is a validation error.

In any case, I think it would be helpful if the spec was made clearer on the error types.

**Comment by bbakerman** [comment]
My reading of the graphql-js has this

```
      const errors = isValidJSValue(value, varType);
      if (errors.length) {
        const message = errors ? '\n' + errors.join('\n') : '';
        throw new GraphQLError(
          `Variable "$${varName}" got invalid value ` +
          `${JSON.stringify(value)}.${message}`,
          [ varDefNode ]
        );
      }
```

that is it throws during execution if the type is invalid.

That said I am reading the code - not running it (yet).

I am sympathetic to it being a validation error or just an "graphql error" however.  

So you offer of a PR is welcome.   

But its still not 100% clear that we should or should NOT throw during invalid InputObjectType values.

**Comment by filipncs** [comment]
And the `GraphQLError` is turned into an actual compliant response here: https://github.com/graphql/graphql-js/blob/4f5e351c2afb28e4ae3a44eae76d45d895ff3aa2/src/error/formatError.js#L15


```
/**
 * Given a GraphQLError, format it according to the rules described by the
 * Response Format, Errors section of the GraphQL Specification.
 */
export function formatError(error: GraphQLError): GraphQLFormattedError {
  invariant(error, 'Received null or undefined error.');
  return {
    message: error.message,
    locations: error.locations,
    path: error.path
  };
}
```

**Comment by filipncs** [comment]
And here is a near-minimal node example, using graphql-js, that exercises the behaviour of the reference implementation:

```
var GQL = require('graphql');

var schema = new GQL.GraphQLSchema({
    query: new GQL.GraphQLObjectType({
        name: 'RootQueryType',
        fields: {
            hello: {
                type: GQL.GraphQLString,
                args: {number: {type: GQL.GraphQLInt}},
                resolve() {
                    return 'world';
                }
            }
        }
    })
});

var query = 'query namedQuery($var: Int!) { hello(number: $var) }';
var variables = {"var": "not-a-number"};

GQL.graphql(schema, query, null, null, variables).then(result => {
    console.log(result);
});
```

Printed result:
```
{ errors:
   [ { GraphQLError: Variable "$var" got invalid value "not-a-number".
Expected type "Int", found "not-a-number": Int cannot represent non 32-bit signed integer value: not-a-number
    at getVariableValues (/private/tmp/example/node_modules/graphql/execution/values.js:97:15)
    at buildExecutionContext (/private/tmp/example/node_modules/graphql/execution/execute.js:207:54)
    at executeImpl (/private/tmp/example/node_modules/graphql/execution/execute.js:121:15)
    at execute (/private/tmp/example/node_modules/graphql/execution/execute.js:110:229)
    at /private/tmp/example/node_modules/graphql/graphql.js:75:34
    at Promise (<anonymous>)
    at graphqlImpl (/private/tmp/example/node_modules/graphql/graphql.js:59:10)
    at Object.graphql (/private/tmp/example/node_modules/graphql/graphql.js:48:227)
    at Object.<anonymous> (/private/tmp/example/index.js:21:5)
    at Module._compile (module.js:624:30)
       message: 'Variable "$var" got invalid value "not-a-number".\nExpected type "Int", found "not-a-number": Int cannot represent non 32-bit signed integer value: not-a-number',
       locations: [Array],
       path: undefined } ] }
```

I.e. the `GraphQLError` is caught long before it reaches the calling code, and is added to the errors array (that can then be formatted for a serialized response with the above mentioned `formatError` method).

To sum up: The reference implementation does not let GraphQLErrors bubble out to calling code. It includes them in the errors array.

**Comment by bbakerman** [comment]
OK I concur - it catches a thrown exception and maps it to an error in the list

I rewrote that test to ensure its about InputObjects

```
var GQL = require('graphql');

const InputArgsType = new GQL.GraphQLInputObjectType({
    name: "InputType",
    fields: {
        field1: {
            type: GQL.GraphQLString,
        },
        field2: {
            type: GQL.GraphQLString,
        }
    }
});

var schema = new GQL.GraphQLSchema({


    query: new GQL.GraphQLObjectType({
        name: 'RootQueryType',
        fields: {
            hello: {
                type: GQL.GraphQLString,
                args: {inputObj: {type: InputArgsType}},
                resolve() {
                    return 'world';
                }
            }
        }
    })
});

var query = 'query namedQuery($var: InputType!) { hello(inputObj: $var) }';
var variables = {"var": "not-a-number"};

GQL.graphql(schema, query, null, null, variables).then(result => {
    console.log(result);
});
```

and it gets

```
{ errors: 
   [ { GraphQLError: Variable "$var" got invalid value "not-a-number".
     Expected "InputType", found not an object.
         at getVariableValues (/Users/bbaker/src/personal/node_gql/node_modules/graphql/execution/values.js:97:15)
         at buildExecutionContext (/Users/bbaker/src/personal/node_gql/node_modules/graphql/execution/execute.js:207:54)
         at executeImpl (/Users/bbaker/src/personal/node_gql/node_modules/graphql/execution/execute.js:121:15)
         at execute (/Users/bbaker/src/personal/node_gql/node_modules/graphql/execution/execute.js:110:229)
         at /Users/bbaker/src/personal/node_gql/node_modules/graphql/graphql.js:75:34
         at graphqlImpl (/Users/bbaker/src/personal/node_gql/node_modules/graphql/graphql.js:59:10)
         at Object.graphql (/Users/bbaker/src/personal/node_gql/node_modules/graphql/graphql.js:48:227)
         at Object.<anonymous> (/Users/bbaker/src/personal/node_gql/test.js:35:5)
         at Module._compile (module.js:570:32)
         at Object.Module._extensions..js (module.js:579:10)
       message: 'Variable "$var" got invalid value "not-a-number".\nExpected "InputType", found not an object.',
       locations: [Object],
       path: undefined } ] }

```

**Comment by bbakerman** [comment]
We will reconsider this in light of this

**Comment by bbakerman** [comment]
Now present on master.
