### ISSUE TITLE
Using a Set Collection causes a Validation Error on mutation input

### ISSUE THREAD

**Issue by andrewe123** [graphql-java/graphql-java#79]
graphql.validation.Validator is producing the following error when the mutation argument is mapped to an object that contains a Set

```
private Set<String> ids;
```

Request Query
mutation a {
  createThing (info: {ids: ["abc"]}) {
     title
     id
  }
}

Response
{
  "errors": [
    {
      "errorType": "QueryValidationError",
      "msg": "Validation error of type WrongType: argument value ObjectValue{objectFields=[ObjectField{name='ids', value=ArrayValue{values=[StringValue{value='abc'}]}}]} has wrong type [SourceLocation{line=2, column=19}]"
    }
  ]
}

It works if the argument mapped in the object contains a List instead, but that is not ideal since we'll have to perform a further conversion to remove duplicates. The GraphQL server should be able to accept any Collection type for a json list? 

Probably more of a question than an issue. Since Set isn't ordered that might be the reason it's not possible?

**Comment by bpatters** [comment]
Checkout https://github.com/bpatters/schemagen-graphql . It handles this by allowing you to define your own type converter for these method invocations (See JacksonTypeMapper in the examples for a simple default implementation). It can also will generate schema for you.

Still under heavy development, but aiming for production use in 3-4 weeks for a large production application.

**Comment by danielkwinsor** [comment]
Remember that in GraphQL arguments are unordered, but Lists are ordered.

In the query, your type `{ids: ["abc"]}` is an input object with 1 field named ids, and ids has type List of Strings.  Therefore it's both ordered and can contain duplicates.  Now, I can't see what GraphQLType your schema declares this GraphQLInputObjectField as, but it must be a GraphQLList(GraphQLString) to work with the given query.  Is this the schema type and it still fails to convert?  But if your schema is something else, converting a GraphQL List to a Java Set is not something graphql-java does.

**Comment by bbakerman** [comment]
Going to close this as its now a year and no response on question asked
