### ISSUE TITLE
OpenTracing Support?

### ISSUE THREAD

**Issue by loganvolkers** [graphql-java/graphql-java#792]
It seems like OpenTracing is becoming a good standard alternative to custom APM systems.

They have a guide for how frameworks can include tracing (http://opentracing.io/documentation/pages/instrumentation/instrumenting-frameworks)

 - Is this something that the core maintainers agree about adding to the core libary? Or should it be a separate package?
 - Would the core team consider building and supporting this?

**Comment by bbakerman** [comment]
We would consider it but would need more detail on how this would be placed inside graphql-java

That library as is has NO edges - eg no HTTP / JSON just the core engine.  So for example HTTP headers and URLs and so on meaning nothing to the core graphql-java library.

So how do you see the support being implemented?

We have tracing support for the Apollo proposed tracing spec via graphql.execution.instrumentation.tracing.TracingSupport as an example already.  Its uses
the spec "extensions" map to place tracing data of the "fields" and fetchers

**Comment by loganvolkers** [comment]
Hey Brad thanks for taking a look and getting back to me quickly.

The document that I linked you in hindsight isn't necessarily the best because it focuses more on the web frameworks of the world. In reality though, OpenTracing has instrumentation for many types of IO operations: JDBC, Mongo, RPC, 

The way that I see this implemented is like this:
 1. The instrumentation would need some way of accessing a parent `Span`.  In order to create an `OpenTracingInstrumentation` instance you'd likely need to provide a `Supplier<Span>` or something to access the parent `Span` from the upstream web framework or whatnot.
 2. [Create a child `Span`](http://opentracing.io/documentation/pages/instrumentation/instrumenting-frameworks#start-the-span) for the entire GraphQL request.
 3. Create a child `Span` for each resolver

I'm definitely not an expert on OpenTracing, but I do know that it seems to have some excellent open source momentum as a replacement to Zipkin.

For inspiration here are a couple things that may be of use:
 - [Jaxrs implementation](https://github.com/opentracing-contrib/java-jaxrs/blob/master/opentracing-jaxrs2/src/main/java/io/opentracing/contrib/jaxrs2/client/ClientTracingFilter.java)
 - https://github.com/opentracing-contrib
 - https://github.com/openzipkin/brave
 - http://zipkin.io/pages/existing_instrumentations.html

**Comment by bbakerman** [comment]
Closing for now as we are not likely to do this.  It can be done via a custom instrumentation

**Comment by koenpunt** [comment]
> Closing for now as we are not likely to do this. It can be done via a custom instrumentation

Is there by any chance someone that already wrote a custom instrumentation for graphql-java with tracing in zipkin/opentracing format?
