### ISSUE TITLE
EnumValue with SchemaGenerator

### ISSUE THREAD

**Issue by vincentDAO** [graphql-java/graphql-java#793]
Hi,

I'm using schema first with GraphQL V5. I got an issue relate to Enum and Field parameter
The class SchemaGenerator always return "String" for default enum in field parameter.

Here is my schema:
`type Query {
    queryUsers(userType: UserType = EXTERNAL)
}`
I also wired the enum values
`builder.type("UserType", typeWiring -> typeWiring.enumValues(new NaturalEnumValuesProvider<UserStatus>(UserType.class)));`

with default query:
`query {
    queryUsers() # I expect userType will be binded to enum value EXTERNAL
}`
But always get String value "EXTERNAL"
Here is my datafetcher
`public DataFetcher<List<User>> querySchedulingRespondents() {
	return env -> {
		//UserType type = env.getArgument("userType"); // not working
		String type = env.getArgument("userType"); //working
		// query stuff
	}
}`

And after check source code; I think the issue maybe relate to method graphql.schema.idl.SchemaGenerator.buildValue(Value, GraphQLType)
![shema_generator_enum_value](https://user-images.githubusercontent.com/22828550/31874447-7a46a384-b7f3-11e7-9544-85945e62df88.png)

**Comment by bbakerman** [comment]
OK got it - up that seems a bit wrong.  The other parts of the code use a  graphql.schema.idl.EnumValuesProvider as an indirection.

This part does not.

That said the spec has been pretty specific about what values can be defaulted in what way and hence we need to double check that.

**Comment by glasser** [comment]
I'm still seeing this today on master... Was this fixed? Will try to make a test.

**Comment by glasser** [comment]
See https://github.com/graphql-java/graphql-java/pull/2150
