### ISSUE TITLE
Context in Type Resolver

### ISSUE THREAD

**Issue by gregryork** [graphql-java/graphql-java#796]
HI,
For a project we are working on it is useful to have the type resolvers have access to the context. As an example think of our data being a numerical ID that represents a person (interface type). That person can be an employee type or a customer type, and that needs to have access to the context to resolve which it is.

I've added a PR for this at https://github.com/graphql-java/graphql-java/pull/795

It would be really helpful if you could take a look. Many thanks for a great library!

**Comment by bbakerman** [comment]
Done
