### ISSUE TITLE
Allow @export on fields to allow query chaining

### ISSUE THREAD

**Issue by bbakerman** [graphql-java/graphql-java#807]
Inspired by http://sangria-graphql.org/learn/#batch-executor we should have the ability to export variables from one operation / query into another.

            query A {
                hero 
                {
                    id @export(as:"droidId")
                    name 
                    friends  @export(as:"r2d2Friends") 
                    {
                        name @export(as:"friendNames")
                    }
                }
            }

            query B($droidId : String!) {
                droid (id : $droidId ) {
                    name
                }
            }

This is related to #806 . Technically its not truly needed but its more powerful if #806 is in place.

This allows for even more performant queries since you can send 2 operations / queries in one request and have the output of the first feed into the input of the second and so on.

This is also not spec but its is experimental based off what Facebook are already doing

See:

https://www.youtube.com/watch?time_continue=626&v=ViXL0YQnioU

http://sangria-graphql.org/learn/#batch-executor

**Comment by andimarek** [comment]
closing now: we are not adding this at the moment as it is outside of the spec and the details are unclear.
