### ISSUE TITLE
Rename IDL to SDL

### ISSUE THREAD

**Issue by bbakerman** [graphql-java/graphql-java#809]
The graphql working group came down with a recommendation that the IDL be known as SDL

We should rename is where we can, especially in the docs (probably not in the package names...too late for that.  A breaking API change like that is not worth it)

**Comment by guidorota** [comment]
The changes to rename IDL in SDL in the documentation were made in [this commit](https://github.com/graphql-java/graphql-java/pull/821/commits/7262ebced3f78ebb8476bed2eef67c1d4e0b1f13).

Should we close this issue or do you think there's more that we can rename without introducing a breaking change?
