### ISSUE TITLE
Add context to GraphqlFieldVisibility calls

### ISSUE THREAD

**Issue by MMaas3** [graphql-java/graphql-java#814]
Hi,

My colleague @jauco and I have question about the `GraphqlFieldVisibility`. We need to hide the existence of certain parts of the graph for certain users, and it would seem to fit the bill perfectly for that usecase.

Your [documentation](http://graphql-java.readthedocs.io/en/v5/execution.html#limiting-field-visibility) describes that it can be used for limiting the fields that user sees. It suggests to inject a userAccessService in the constructor. It is not clear how the userAccessService knows who the current user is during query execution. In our application we do not have a straightforward way of retrieving the user from some global state (The GraphQL object is shared by mutliple threads each executing a request for a different user)

We now set the user as the context object in the execution (as suggested by the graphql guide). It would be nice to have access to that context object inside the GraphqlFieldVisibility calls. 

This would mean a slight change to the interface of the `GraphqlFieldVisibility`.

for example:

```
public interface GraphqlFieldVisibility {

    /**
     * Called to get the list of fields from an object type or interface
     *
     * @param fieldsContainer the type in play
     *
     * @return a non null list of {@link graphql.schema.GraphQLFieldDefinition}s
     */
    List<GraphQLFieldDefinition> getFieldDefinitions(GraphQLFieldsContainer fieldsContainer, ExecutionContext executorContext);

    /**
     * Called to get a named field from an object type or interface
     *
     * @param fieldsContainer the type in play
     * @param fieldName       the name of the desired field
     *
     * @return a {@link graphql.schema.GraphQLFieldDefinition} or null if its not visible
     */
    GraphQLFieldDefinition getFieldDefinition(GraphQLFieldsContainer fieldsContainer, String fieldName, , ExecutionContext executorContext);
```

If you agree with our suggestion we are very happy to provide a pull request. Is this something you would be willing to accept?

**Comment by bbakerman** [comment]
We would be happy to accept these changes.  What I would do is invent a GraphqlFieldVisibilityEnvironment class (with builder) that contains the variables and change the API to include these.

This would be a breaking change but we can role it out in 7.0 say

**Comment by bbakerman** [comment]
See the PR for the reasons for closing this issue and also the workaround to do what you want
