### ISSUE TITLE
getName() of GraphQLList/GraphQLNonNull etc

### ISSUE THREAD

**Issue by david-tamjidi** [graphql-java/graphql-java#819]
Hi guys,

I was just wondering if the getName() of these Types (GraphQLList/GraphQLNonNull) should be null as is currently or perhaps something like:

"ListOf_" + wrappedType.getName()

this is similar to how the toString() function in these classes are written. Thoughts? I can submit a patch if this is desirable.

**Comment by bbakerman** [comment]
Its not a crazy idea.  The reference JS implementation has no names but then it doesnt have interfaces in JS to inherit from.

**Comment by bbakerman** [comment]
Looking into this (and quickly implemented it) - it breaks Introspection

> List

> Lists represent sequences of values in GraphQL. A List type is a type modifier: it wraps another type instance in the ofType field, which defines the type of each item in the list.

> Fields

> kind must return __TypeKind.LIST.
> ofType: Any type.
> All other fields must return null.

> Non-Null

> GraphQL types are nullable. The value null is a valid response for field type.

> A Non‐null type is a type modifier: it wraps another type instance in the ofType field. Non‐null types do not allow null as a response, and indicate required inputs for arguments and input object fields.

> kind must return __TypeKind.NON_NULL.
> ofType: Any type except Non‐null.
> All other fields must return null.

This will cause the name to be listof_foo which is wrong (and the test catch).

We could fix that up...but the more I think of it - the more I like to keep it as it is
