### ISSUE TITLE
Ability to contribute errors in a DataFetcher

### ISSUE THREAD

**Issue by mrdon2** [graphql-java/graphql-java#820]
Currently, it seems you can, in a DataFetcher, either return data or throw an exception that will result in exactly one error.  However, if your DataFetcher is retrieving a tree of data where nested fields may have their own errors (such as the case of weaving two GraphQL requests), there is no way to currently to return data _and_ contribute one or more errors for nested data fields.

One possible solution would be to allow the DataFetcher return a special object that contains data and errors that can be matched to nested data fields.  Either the library could match the errors list to their fields or the data fetcher could.

**Comment by bbakerman** [comment]
Another option would be to make the error collection available vis the data fetcher environment and have the DF contribute to the list perhaps?

We also have to think about the "path" of the errors.  The spec says there should be ONLY one error per path.  Will this break spec?

**Comment by mrdon2** [comment]
PR at  #824

**Comment by mrdon2** [comment]
The way the PR works, the spec should be ok as it uses the same spec-checking code path as normal errors

**Comment by mrdon2** [comment]
PR has been merged
