### ISSUE TITLE
Support for aliases?

### ISSUE THREAD

**Issue by tsoares-atypon** [graphql-java/graphql-java#826]
It isn't clear how a query that uses aliases like the following would be supported:

    { 
       foo 
       { 
           b1: bar (x: "1") { boo },
           b2: bar (x: "2") { boo }
       }
    }

It would obviously cause problems if the source object ("foo") isn't a Map.  But in cases where "foo" is a Map, it should be possible to support this query.  

It looks like currently PropertyDataFetcher#get(DataFetchingEnvironment) always tries to get the value from Maps using the property name ("bar" in this case), and ignoring any alias that might be defined.  The alias seems to be available in the DataFetchingEnvironment by looking at the Field, so perhaps it would be possible to support this case.

**Comment by bbakerman** [comment]
Aliases are a syntatic sugar that allows you to rename a field in the results.

So you will get a map result with `b1` and 'b2` in the result.

How a field name (+aliases) gets applied to a source object is the job of the data fetcher.

Out of the box you get a Java data fetcher that takes the field name and "JavaBean" style tries to find data for that field or its the source is a map does a map read.

However you can write your own DataFetcher that decides on an  object access strategy that respects aliases say.

You need to decide a strategy that makes sense for you. 

There are challenges with using aliases, namely in fallback. If you try to read the "b1" value should it be null of its not found or should it fall back to the underlying field name "bar"??

That question cant be easily answered I think in a generic sense.  So having a specific "AliasRespectingDataFetcher" might make sense but its local to how you want to run your code and not generic for all.

**Comment by bbakerman** [comment]
Closing this as its more a question than a bug

**Comment by Type1J** [comment]
This might case an efficiency problem, but not supporting aliasing means that this implementation does not conform to even the earliest GraphQL spec: http://facebook.github.io/graphql/July2015/#sec-Field-Alias

**Comment by bbakerman** [comment]
After reading the spec link it does NOT say that aliases are to be used to look up underlying values.

It says that aliases are to be used as the outgoing property names on results (which is to be the field name by default and the alias to allow unique views on the field).

Looking into the graphql-js reference implementation it has the following default resolver

```
/**
 * If a resolve function is not given, then a default resolve behavior is used
 * which takes the property of the source object of the same name as the field
 * and returns it as the result, or if it's a function, returns the result
 * of calling that function while passing along args and context value.
 */
export const defaultFieldResolver: GraphQLFieldResolver<any, *> = function(
  source,
  args,
  contextValue,
  info,
) {
  // ensure source is a value for which property access is acceptable.
  if (typeof source === 'object' || typeof source === 'function') {
    const property = source[info.fieldName];
    if (typeof property === 'function') {
      return source[info.fieldName](args, contextValue, info);
    }
    return property;
  }
};
```

It ONLY looks up by field name - never by alias

I am going to close this issue again.  We do have a PR open at the moment on this but I am also inclined not to support it as its not specified behaviour

cc: @swaters-atlassian

**Comment by davidcurrie** [comment]
Adding another thumbs down. As per the example given above where `b1` and `b2` have different arguments, different aliases of the same field may have different values. The current implementation makes it impossible for the data fetcher on a parent object to distinguish between them.

**Comment by cdrolet** [comment]
Using alias come usually with different arguments... this is ridiculous.
You need to take this in consideration. 
Adding another thumbs down

**Comment by Type1J** [comment]
I think that what I said was misunderstood. I was saying that aliasing didn't work unless you were using a Map object. That may not be true, now, but I don't know because I used ApolloServer in Node.js for the other projects that year. Now, Juniper in Rust.

**Comment by unrealprox** [comment]
There is example #14 in the [spec](https://spec.graphql.org/draft/#sec-Overview):
```
{
  user(id: 4) {
    id
    name
    smallPic: profilePic(size: 64)
    bigPic: profilePic(size: 1024)
  }
}
```
with result (example #15):
```
{
  "user": {
    "id": 4,
    "name": "Mark Zuckerberg",
    "smallPic": "https://cdn.site.io/pic-4-64.jpg",
    "bigPic": "https://cdn.site.io/pic-4-1024.jpg"
  }
}
```

So, I think it should be considered a bug

**Comment by bbakerman** [comment]
@unrealprox 

What are you saying is a bug?

The example above works in graphql java (and has for a long time)

The key is that the code behind `profilePic` in your example uses the different argument values to "distinguish" the values returned.

The alias is used to msake the output as having a different key.

The original questioner above asked that PropertyDataFetcher some how use the alias on input to look into an object for values.

This is not a good idea at all.  First off the reference implementation does not do this.  It can be done but its not generic behavior

Secondly now The client is now causing the causing the server to run code not if its choose.  So you might have a backing object with a `name` attribute and a client can alias it as `password` and all of a sudden it starts to read the attribute `password` not because the server meant to but because the client used that alias.

We wont be changing this - there is no bug

**Comment by andimarek** [comment]
I am locking this issue now: as @bbakerman explained above GraphQL Java will not change the default property data fetcher to consider aliases automatically.
