### ISSUE TITLE
A way to send an 401 - Unauthorized HTTP response

### ISSUE THREAD

**Issue by DavidFlorin** [graphql-java/graphql-java#833]
I want to use the GraphQL for authentication mechanism also, using mutations

I was following the [How to GraphQL - Backend Java tutorial](https://www.howtographql.com/graphql-java/5-authentication/) and in the `createContext` method:

```java
@Override
protected GraphQLContext createContext(Optional<HttpServletRequest> request, Optional<HttpServletResponse> response) {
// ...
}
```
* I need to be able to check the token (it may be expired or a wrong token provided) and return a custom status code, like `401 - Unauthorized` so we can redirect the user in the web to a login page eventually. At the moment, if I throw an Exception in that method, I will get a `500 - Server Error` and this is not explicit enough. Is there any way to do that?

* How can I check the mutation name in order to exclude `signin` calls or some public mutations (mutations calls that does not require an `Authorization` header)

**Comment by bbakerman** [comment]
The base graphql-java library does not deal with HTTP or error codes and so on.  Its purely the engine of executing graphql queries.

That example uses graphql-java-servlet which is another library.

Perhaps @kaqqao might be able to help here as he was the author of that tutorial.

**Comment by DavidFlorin** [comment]
Ok, thank you. I will put this issue on [graphql-java-servlet](https://github.com/graphql-java/graphql-java-servlet)
