### ISSUE TITLE
SchemaDiff is not reporting field additions

### ISSUE THREAD

**Issue by gpan** [graphql-java/graphql-java#837]
Comparing the following two schemata does not report any diffs. 
It seems that current implementation does not report any additions like this in any of the three diff levels *(INFO, BREAKING, DANGEROUS)*

I believe that any changes should be reported, maybe in a new diff level (?)

**Old Schema**
```graphql
type Query {
    entity: Entity
}

type Entity {
    id: ID!
    field1: String!
}
```

**New Schema**
```graphql
type Query {
    entity: Entity
}

type Entity {
    id: ID!
    field1: String!
    field2: String!
}
```

**Comment by bbakerman** [comment]
Thanks for reporting - yes to be useful beyond just breaking changes, we should consider additions.  

Off hand I thought it reported them as INFO but if not it could be another category

**Comment by guidorota** [comment]
We can start reporting them at INFO level for now, and change it later if we find that it's not suitable.
