### ISSUE TITLE
Multiple fieldVisibilities

### ISSUE THREAD

**Issue by guy120494** [graphql-java/graphql-java#843]
Hi,
Is there an option to have more the one `GraphqlFieldVisibility`? 
If I want for example to have multiple criteria, like permissions and configuration-specific visibility (maybe set "graphql.introspection = false" in my .properties file and then make a `NoIntrospectionGraphqlFieldVisibility`).

Can I have a list of `GraphqlFieldVisibility` and make the GraphQL engine to check all of them?

**Comment by bbakerman** [comment]
@guy120494 - We dont offer composed GraphqlFieldVisibility today nor plan to.

I think you need to compose on the "inside" of the GraphqlFieldVisibility interface.  Its your conditions that decide what should or should not be included.  I would invent a composed set of conditions of your own choice and merge them together to provide a unified GraphqlFieldVisibility collection of allowed fields

**Comment by guy120494** [comment]
Sounds fair, but what is the difference between that and an instrumentation? you could say the exact same thing on instrumentation, but yet there is `ChainedInstrumentation`.

**Comment by bbakerman** [comment]
Instrumentation does not return a list of fields that need merging

Imagine 2 field visibilities A and B on the fields

    name,age, secretIdentity

A call to A returns [name,secretyIdentity]
A call to B returns [age]

So thats the field list then?  union  of the list / intersection 

Its simpler if you decide that set of rules.

As for instrumentation, we provide multiple implementations that dont need to be conflict resolved
