### ISSUE TITLE
Can't throw a custom error

### ISSUE THREAD

**Issue by fnovoa10** [graphql-java/graphql-java#849]
This is the error response for every error.

```
"errors": [
		{
			"message": "Internal Server Error(s) while executing query",
			"path": null,
			"extensions": null
		}
	]
```

**Comment by JangChulwoon** [comment]
First, Sorry I am not good Eng  :(  

I used `GraphQLException`  when I handle Exception.   

For example ...  

```
        try {
            throw new Exception("Exception !! ");
        }catch (Exception e){
            throw new GraphQLException(e.getMessage());
        }
```
> request  

```
{
   a  { 
     ...  there is not problem query ..
   }
   b  { 
     ...  there is problem query ..
   }
}

```



> result 

```
 "data": {
    "a":  data bla bla  ~~ ,
    "b": null
  },
 "errors": [
    {
      "message": "Exception while fetching data (/b) : Exception ??",
      "path": [
        "b"
      ],
      "exception": {
        "cause": null,
        "stackTrace": [
          {  // .....
```  

Most can be processed by GraphQLException.
But , If validate and parse step operate exception, I couldn't handle Exception. 

> Such as case

```
{
  "data": null,
  "errors": [
    {
      "message": "Validation error of type FieldUndefined: Field 'WrongQuery' in type 'QueryName' is undefined",
      "locations": [
        {
          "line": 8,
          "column": 3
        }
    ....

```

Because GraphQL-java works in the following order.

`Parse and validate` -> `run` -> `return`  

> It may be a little different ... 

if parse and validate step  operate exception, It is immediately returned. 
So, We can't handle Exception of parse or validate step.

**Comment by bbakerman** [comment]
Please read http://graphql-java.readthedocs.io/en/v6/execution.html and the section `Exceptions while fetching data`

It outlines how you can change the errors you see namely via     `DataFetcherExceptionHandler`

You seem to be getting errors from https://github.com/graphql-java/graphql-java-servlet which is not this library.  I suspect that library is masking your errors not the base graphql-java library

You can extend the servlet and override the method that filters exceptions to allow more to be shown to the client.

**Comment by hfye** [comment]
I encountered the same problem and have spent whole day on it.

please share if you have any solution!

**Comment by fnovoa10** [comment]
Hey @hfye, I solved my problem using the following post, i hope it works for you.

https://picodotdev.github.io/blog-bitix/2017/11/devolver-mensajes-de-error-descriptivos-en-graphql/

Regads.
