### ISSUE TITLE
Can field visibility be set on input fields?  If so how?

### ISSUE THREAD

**Issue by Mark-K** [graphql-java/graphql-java#852]
I am trying to use BlockedFields to specify fields that the client can't request or input based on the current user's authenticated role.

The graphql-java 6.0 release is being used.

## sample schema
```
schema {
    query : Query
}
type Query {
    search ( input : SearchInput ! ) : [ SearchResult ! ]
}
input SearchInput {
    startId : Int !
    endId : Int !
    userNames : [ String ! ]
}
type SearchResult {
    id : Int !
    userName : String !
    title : String !
    content : String !
}
```
## java code fragment
```
    boolean isAdmin = (null != account) && account.hasRole("admin");
    if ( ! isAdmin) {
        BlockedFields fieldBlocker = BlockedFields.newBlock()
            .addPattern("SearchResult\\.userName")
            .addPattern("SearchInput\\.userNames")
            .build();
        schema = schema.transform(builder -> builder.fieldVisibility(fieldBlocker));
    }
```
If for example the current user has the "admin" role, "userNames" can be specified as a search parameter and requested in the result because an admin is permitted to search for arbitrary users.  When the user hasn't been assigned the "admin" role, I desire to make the "userNames" input field not-visible because such users can only search for their own entries.  The userNames criteria will be supplied internally by the business logic.

Using the BlockedFields class, I have been able to adjust the visibility of the "userName" output field as required.  When the user is admin, the userName output field appears in the introspected schema and does not appear when the user is not admin.

However, the "userNames" input field appears regardless of the field visibility configuration when the schema is introspected.  The field is also passed through to the data fetcher.  I tried a field validation instrumentation to catch the case where userNames is specified when it is not allowed.  It works; but, that doesn't feel like the right way of doing things.

The other obvious option is having separate admin and non-admin schema files.  If possible I'd prefer to avoid that route since the number of roles is expected to increase and having to create a schema file for every possible combination the roles doesn't scale well. 

If it is already possible, could someone tell me the proper way to make an input field non-visible?
If not possible, could the ability to make input fields non-visible be added to a future release?

**Comment by Mark-K** [comment]
Part 2

I tried separating the "admin" user fields into a separate IDL

## Normal User Schema
```
schema {
    query : Query
}
type Query {
    search ( input : SearchInput ! ) : [ SearchResult ! ]
}
input SearchInput {
    startId : Int !
    endId : Int !
}
type SearchResult {
    id : Int !
    title : String !
    content : String !
}
```
## Admin User extended schema
```
extend input SearchInput {
    userNames : [ String ! ]
}
extend type SearchResult {
    userName : String !
}
```
## Java code fragment
```
        TypeDefinitionRegistry registry = new TypeDefinitionRegistry();
        SchemaParser parser = new SchemaParser();
        String resource = "user.graphql";
        URL schemaUrl = this.getClass().getClassLoader().getResource(resource);
        try (Reader in = new InputStreamReader(schemaUrl.openStream(), StandardCharsets.UTF_8)) {
            registry.merge(parser.parse(in));
        } catch (IOException | RuntimeException ex) {
            LOG.catching(ex);
            return null;
        }
        boolean isAdmin = (null != account) && account.hasRole("admin");
        if (isAdmin) {
            String adminResource = "admin.graphql";
            schemaUrl = this.getClass().getClassLoader().getResource(adminResource);
            try (Reader in = new InputStreamReader(schemaUrl.openStream(), StandardCharsets.UTF_8)) {
                registry.merge(parser.parse(in));
            } catch (IOException | RuntimeException ex) {
                LOG.catching(ex); // stops here
                return null;
            }
        }
```
When the admin.graphql schema is parsed the following error occurs:
```
graphql.schema.idl.errors.SchemaProblem: errors=[InvalidSyntaxError{ message=Invalid Syntax ,locations=[SourceLocation{line=1, column=7}]}]
```
Still looking for a solution...

**Comment by bbakerman** [comment]
Regarding the second comment, the "extend" keyword is only applicable to object types.

There is no "extend" for input type

    typeExtensionDefinition : EXTEND objectTypeDefinition;

    objectTypeDefinition : TYPE name implementsInterfaces? directives? '{' fieldDefinition+ '}';

Regarding the first comment let me have more of a think about how one might handle "reduced" input types.   It strikes me as a little weird because you are restricting something that the client might have already INPUT and not something that they are restricted from seeing.

Can you explain more about why a non admin can not submit a "userNames" field.  Is it because the code that acts on "usersNames" is unaware of the "application roles"?

**Comment by Mark-K** [comment]
Good Morning BBakerman,

Thank you for your response!

In answer to your question, the application code is aware of the user's roles and for a non-admin user arbitrarily replaces the userNames list (ignores the input value) with a list containing only the logged in user's userName.
Having the userNames field in the input schema for a non-admin user implies that the non-Admin user is permitted to search for any other user's data which is not the case.  Being able to remove the field from the non-admin's view of the schema removes that "ambiguity" and seeming security hole.

For me it's actually more of a how to deal with QA Team/Documentation Team/Customer issue than a programming issue.  The question is "why is it there if I can't use it?"  I can document it to death; but, the question will remain and will keep coming back like an unwelcome zombie.

If you should decide to include the functionality of making the visibility of input fields controllable by the application, my personal preference on how hidden input fields are handled would be for an InputMapDefinesTooManyFieldsException to be thrown.  This exception is already thrown when a field that does not exist in the schema (an undefined field) is found in the input variables.  The idea is that if the field is hidden, it does not exist as far as the client is concerned.  When validating the variables map, passing the request for an input type's fields through the schema's getFieldVisibilty().getFieldDefinition() mechanism may work assuming that the schema instance can be obtained at that point and a method accepting a GraphQLInputFieldsContainer can also be implemented.  Looking at the code, it wasn't apparent that the schema was obtainable where the decision to throw InputMapDefinesTooManyFieldsException is made.

However, that said and being new to GraphQL, I'm not sure what the accepted approach is when dealing with what a user is permitted to do and how that should be presented in the schema.  The application should obviously not allow a user to make unauthorized requests or include unauthorized fields in input data.

But shouldn't that information be reflected in the schema that the user can see?
So, if you were to say:

- the accepted practice is to add a validation rule and reject requests containing unwanted fields
- the application should silently ignore such things.

either would be perfectly acceptable and doable.

My background in web development has been to only show users what they are allowed to operate on.  Even though the web app may have many functions available, the current user may only see in the interface the subset of functions they have been granted permission to use.  That may or may not be how GraphQL interprets the idea of user permissions and visible schema.

I am in the process of separating the business logic from the web interface of several web apps by collecting the BL out of the web apps and facing it with GraphQL.  The initial version due to multiple user authentication sources was too complex, too many URL endpoints (one for each unique user type), schema files and redundancy.  The user authentication requirement was changed to a single source so the complex "mess" is being merged and reduced which is leading to situations where merging the schema makes api visible to users that don't have permission to actually use it.

**Comment by bbakerman** [comment]
Thanks for the detailed reply.  It does help inform how we make fixes to the library.

I can "buy" your argument about consistency between Introspection and calls and in fact that is why we added "field visibility" to the library in the first place.
