### ISSUE TITLE
Introspection to Schema processing handles default values incorrectly

### ISSUE THREAD

**Issue by mrdon2** [graphql-java/graphql-java#863]
Default values in a introspection query result are usually a JavaScript string that represents a JSON value.  For example, "defaultValue": "\\"foo\\"".  However, the library currently treats that as a literal, making the default value "foo" instead of just foo.  If the schema is then turned into another introspection query result, the default value will become \\\\\\\\"foo\\\\\\\\"

**Comment by bbakerman** [comment]
@mrdon2 - I am confused here about exactly how to repduce this problem.

I can see the `graphql.introspection.IntrospectionResultToSchema` given back a graphql language element, name a list of  List<InputValueDefinition> that have default values.

And I can see the AST printer correctly printing them as

    type QueryType {
  hero(
  #comment about episode
  episode: Episode
  foo: String = "bar"
  ): Character @deprecated(reason: "killed off character")
}

Is it some where else that defaults are not encoded correctly?

**Comment by bbakerman** [comment]
Is it compound graphql values perhaps?

**Comment by mrdon2** [comment]
No, this happens with basic strings.  If the default value is a string, it is included in the introspection query result as defaultValue="\\"foo\\"".  However, the IntrospectionResultToSchema class doesn't evaluate the \\"foo\\" value as a JSON value (and therefore set it to foo), but keeps the quotes.  Then, when the schema is turned into an introspection query response, the backslashes are encoded, so what you get is defaultValue="\\\\"foo\\\\""

**Comment by bbakerman** [comment]
I have found the source of the problem.  It was because the default value printing in a couple of places assumed `string` and not the AST type proper

There is now a PR for this.
