### ISSUE TITLE
Fetch data from Janus-Cassandra using GraphQL

### ISSUE THREAD

**Issue by ShiniIn** [graphql-java/graphql-java#873]
Hi 

I am new to graphql-java. I am trying to fire query to the Janus Graph+cassandra by using Graph QL. I have dynamic schema like all the classes may have dynamic properties. I want to write a typeresolver in such a way that It can handle dynamic schema.

My data model is like this. I have two type of parent classes.
1. Entity (It has many classes like student, schools , teacher etc. and have dynamic structure and new classes can be created dynamically i.e. they act as vertex)
2. Relation (It has many classes like teaches, studentof etc. and can have dynamic structure and can be created dynamically i.e. they act as relationships)

Now I want to write a schema and their type resolver so that I can execute my query on the database using the Graph QL such that It returns the type of entity we want on particulcar filters.

Regards,
Shrikant

**Comment by bbakerman** [comment]
One thing to remember about graphql is that the total set of possible objects MUST be able to be expressed in schema (even with type resolvers)

That is for an interface / union of type IFoo you need to be able to have concrete types for all possible variables.  So exactly how dynamic do you need yuor types.

I dont think its possible to write a response to your question in a simple issue.  You are asking...how do I build a graphql thing"  Its too broad

I think you should start with http://graphql-java.readthedocs.io/en/v6/ and https://www.howtographql.com/graphql-java/0-introduction/ and get a handle on building the app in general.

**Comment by bbakerman** [comment]
I am closing this issue as its not a problem with the software - rather its a general call for help
