### ISSUE TITLE
Differentiate between a mutation GraphQLFieldDefinition and it's query.

### ISSUE THREAD

**Issue by B-hamza** [graphql-java/graphql-java#874]
Imagining a case where a schema change dynamically, for that reason we do not have any way to set new queries and mutation in a schema.
Reading the source code, there is just one way to do it, by creating each time a new schema. 
But we do not have any difference between the mutations and queries when getting getFieldDefinitions from a root type for example.

Is there any way to set Definitions in a schema dynamically, and even differentiate between the mutations definition and query definition?

**Comment by bbakerman** [comment]
Schemas in graphql (by spec) are static.  if you contact a graphql server (say on /graphql) then it should report the same schema and the complete schema.  The point is that you can discover what's on offer.

You can offer and UBER schema (all possibilities) and then restrict what types some one can see via FieldVisibility.

I think you might be on the wrong track in thinking that a schema is completely dynamic.  Imagine a relational database schema that was different every time you asked?  How can you write a program based on that?

It would help if you expanded aspects you want to make dynamic

**Comment by bbakerman** [comment]
I am closing this issue because it not clear what is being asked or that there is a software issue
