### ISSUE TITLE
Remove CompletableFuture from ExecutionStrategy.java

### ISSUE THREAD

**Issue by siderakis** [graphql-java/graphql-java#877]
Can we remove the references to CompletableFuture from the ExecutionStrategy base class? 

This is preventing us from upgrading to newer versions of GraphQL-Java. I know this probably isn't an issue for anyone besides us, sorry for asking. For now I'm just seeing if you guys would be open to a PR (or design doc) so we can consider this option.

Here is some more context:

 - We have a ExecutionStrategy based on `ListenableFuture`s written for an older version of GraphQL-Java (before the introduction of CompletableFuture). It was non-blocking, and didn't require CompletableFuture/ListenableFuture in ExecutionStrategy. It works by implementing ExecutionResult with AsyncExecutionResult which implemented a method to return the actual ExecutionResult asynchronously. A ListenableFutureAsyncExecutionStrategy would then extend ExecutionStrategy in a few places checking if `ExecutionResult instanceof AsyncExecutionResult` and did the appropriate async transformations, etc.

`public class AsyncExecutionResult implements ExecutionResult {

  private ListenableFuture<ExecutionResult> executionResultFuture;

  public AsyncExecutionResult(
      ListenableFuture<ExecutionResult> executionResultFuture) {
    this.executionResultFuture = executionResultFuture;
  }

  public ListenableFuture<ExecutionResult> getExecutionResultFuture() {
    return executionResultFuture;
  }

  @Override
  public Object getData() {
    throw new UnsupportedOperationException("called getData on AsyncExecutionResult");
  }
  //...
`

 - One deployment environment we are targeting blacklists CompletableFuture, in favor of ListenableFuture. In this case we can not deploy code that contains CompletableFutures. This means that converting ListenableFutures to CompletableFutures isn't an option. We might need to create a jar that doesn't contain any references to CompletableFuture.

 - https://github.com/google/rejoiner was recently open sourced and started taking advantage of the capabilities of the newer versions of GraphQL-Java. I'd like to deprecate our internal version to use the open source version, but can't because until I can upgrade GraphQL-Java.

**Comment by bbakerman** [comment]
Sorry but its not going to happen.  The whole point of async support we put into graphql 4 was to have a JDK 8 compliant system without extra dependencies (including Guava).

I am sorry that you have a environment blacklist on CompletableFuture (that seems crazy to me on a JDK 8 based system) but we have embraced CompletableFuture to represent our "promises".

CF is viral in most places in graphql-java and cannot be easily replaced
