### ISSUE TITLE
Same Type name Issue

### ISSUE THREAD

**Issue by ShiniIn** [graphql-java/graphql-java#879]
Hi

Suppose I have to implement the Search and  Query operations in GraphQl. I have an entity with name SampleEntity. Now I have two fields say FieldA and FieldB. Now that I have two fields in the GraphQL say SearchByFieldA and SearchByFieldB which both returns list of SampleEntity.

    objectType.field(GraphQLFieldDefinition.newFieldDefinition()
                    .name("SerachByFieldA")
                    .argument(GraphQLArgument.newArgument()
                            .name("FieldA")
                            .type(Scalars.GraphQLString))
                    **.type(list(SampleEntity.build()))**
                    .dataFetcher(deleteFetcher));
            objectType.field(GraphQLFieldDefinition.newFieldDefinition()
                    .name("SearchByFieldB")
                    .argument(GraphQLArgument.newArgument()
                            .name("FieldB")
                            .type(Scalars.GraphQLString))
                    **.type(list(SampleEntity.build()))**
                    .dataFetcher(UpdateFetcher));

I get the following error
"All types within a GraphQL schema must have unique names. No two provided types may have the same name."
  
** type which I am referring to
Is there any resolution for the above error

**Comment by tinnou** [comment]
It's not really the place to ask questions but rather to surface potential bugs with the library. Gitter might be what you're looking for and you will also likely get faster answers. https://gitter.im/graphql-java/graphql-java

That said, looking at your code snippet, it seems like you are attempting to register two instances of the same class `SampleEntity`. If your `build()` method is doing what most build methods do, it will give you a difference instance every time you call it. Hence graphql-java "detecting" two different types with the same name.

What you want to do is reuse the same `SampleEntity` instance, probably like:
```java
SampleEntity sampleEntity = SampleEntity.build();
objectType.field(GraphQLFieldDefinition.newFieldDefinition()
                .name("SerachByFieldA")
                .argument(GraphQLArgument.newArgument()
                        .name("FieldA")
                        .type(Scalars.GraphQLString))
                .type(list(sampleEntity))
                .dataFetcher(deleteFetcher));
objectType.field(GraphQLFieldDefinition.newFieldDefinition()
                .name("SearchByFieldB")
                .argument(GraphQLArgument.newArgument()
                        .name("FieldB")
                        .type(Scalars.GraphQLString))
                .type(list(sampleEntity))
                .dataFetcher(UpdateFetcher));
```
