### ISSUE TITLE
Mutations is not working: "Mutations are not supported on this schema"

### ISSUE THREAD

**Issue by thangbqvng** [graphql-java/graphql-java#880]
Hello, I am new in GraphQL, I am trying to create a demo project but I stuck at Mutation because graphQL always return error with this message:

`{"data":null,"errors":[{"errorType":"MutationNotSupported","locations":null,"message":"Mutations are not supported on this schema","path":null,"extensions":null}]}`

This is my query: 

> http://localhost:9000/graph?query=mutation{%20createUser(name:%20%22Ng%20Thi%20thanh%20thao%22,%20age:%2021){%20id%20name%20age%20}%20}

Here is my current Project: https://github.com/thangbqvng/graphql-demo

Thanks for your support.

**Comment by bbakerman** [comment]
You need to define a mutation type at the top of your schema.

https://github.com/thangbqvng/graphql-demo/blob/master/resource/schema.graphqls

Looks ok

However this is not pure graphql-java code re: `import graphql.schema.GraphQLSchema;`   This is some other library.

**Comment by thangbqvng** [comment]
Thanks for your help, I will try to fix it.
