### ISSUE TITLE
Accessing argument object in typeresolver.

### ISSUE THREAD

**Issue by rsmkrishna** [graphql-java/graphql-java#881]
# Try to fetch/access argument in root query from GraphqlResolver.
### Sorry for poor english.

```
query myQuery($groupid : String!, $userId : String!){
	  getContext(serviceContext:{
		groupId:$groupid
		userId:$userId
	  }){
		 userDetail
		 allowedJourney{
		  name
			value
		}
	  }
	}
```

I have a GraphQLQueryResolver as below, which triggers succesfully and userDetail got fetched.

	public class CommonServiceQResolver implements GraphQLQueryResolver
	{
		CommonServiceFetcher commonServiceFetcher;

		public GetContextResp getContext(ServiceContext serviceContext, 
					DataFetchingEnvironment env)
		{
			return commonServiceFetcher.getContext(serviceContext, env);
		}
	}		

I have a GraphQLResolver<GetContextResp> as below, in which i am trying to access arguments passed in getContext query from below getAllowedJourney resolver method. Please help with correct approach.

```
public class GetInitialContextRespResolver implements GraphQLResolver<GetContextResp >{
	public List<NameValuePair> getAllowedJourney(GetContextResp ggetContextResp , 
			DataFetchingEnvironment env){
		
		Object obj = env.getArgument("serviceContext"); // null.
	serviceContext = (ServiceContext) obj;
```

**Comment by rsmkrishna** [comment]
Please guide with the correct approach for above scenario.

**Comment by bbakerman** [comment]
`GraphQLQueryResolver` is not a part of graphql-java per se-- but some other library built on top of graphql-java.

Do you know what library this comes from??  Ask them for help I think
