### ISSUE TITLE
No way to get requested fields of an object

### ISSUE THREAD

**Issue by gfsilva92** [graphql-java/graphql-java#884]
I have a POJO called Concept, which has several fields:

- id
- type
- term
- definition
- example
- source
- lastUpdate

And I have a Query called "concepts" which retrieves a concept by term. If someone executes the following request:

query {
   concepts(term : "myTerm"){
       term
       definition
   }
}

In this case, the user is searching for the concept with term "myTerm" and is only requesting "term" and "definition" fields. I'm getting the data from a database. So, how can I know in the Java side that I don't need to retrieve all the fields but only those 2 ones? Is that possible?

Thank you.

**Comment by tinnou** [comment]
Yes, it is possible, the `DataFetcher` interface exposes the `DataFetchingEnvironment` via this method https://github.com/graphql-java/graphql-java/blob/276dfc89875db8d030402e01d9ab3aae64ccc158/src/main/java/graphql/schema/DataFetcher.java#L27

Every time the data fetcher linked to the `concepts` field gets executed, you are provided with an instance of the `DataFetchingEnvironment`. It contains context information about the query that is being executed and other request context information. The `DataFetchingEnvironment` exposes the current field selection set via the method https://github.com/graphql-java/graphql-java/blob/276dfc89875db8d030402e01d9ab3aae64ccc158/src/main/java/graphql/schema/DataFetchingEnvironment.java#L121

The fields on the selection set from your snippet are `term` and `definition` and you can access them with this method: https://github.com/graphql-java/graphql-java/blob/fe8a5d404dc39d01334dae70c8089e0a1466781a/src/main/java/graphql/schema/DataFetchingFieldSelectionSet.java#L42

**Comment by gfsilva92** [comment]
Ok, I'm clarified! Thanks.

**Comment by sryara** [comment]
@gfsilva92 @tinnou Can you guys please provide an example for the above use case? I am also struggling to achieve query only fields from database that are specified in request ? Any small example will be a big help. Thanks.
