### ISSUE TITLE
Give access to dispatch method in DataLoaderDispatcherInstrumentation  and provide the current Context.

### ISSUE THREAD

**Issue by mogaleaf** [graphql-java/graphql-java#885]
I'm using Dataloader , DataLoaderRegistry and DataLoaderDispatcherInstrumentation but I need to dispatch only for the current query.   
    
In my code each query creates a bundle of DataLoaders that are registered in the DataLoaderRegistry for the current session so that the query fills only its own Dataloaders (I'm using the context and a sessionId to retrieve DataLoaders that should be used for the session).
So I don't want to dispatch on all the Registered Dataloader in the DataLoaderRegistry but only ones concerned by my session.

In order to use the DataLoaderDispatcherInstrumentation, I'd like to have access to the current Context and I'd like to override the default behavior of _dispatch_ method.

Could we have the current Context in dispatch, and could dispatch be protected or public so it could be override ?

```
	protected void dispatch(Object context) {
		log.debug("Dispatching data loaders ({})", dataLoaderRegistry.getKeys());
		dataLoaderRegistry.dispatchAll();
	}
```

**Comment by bbakerman** [comment]
Since DataLoader instances typically "cache" values, you should only use them in a per request basis generally.

Are you sure you want to share data loader instances across requests.  Its seems fraught.

If you are intent on this approach, I would derive a new DataLoaderRegistry class that knows how to get the per session DL for itself.

**Comment by mogaleaf** [comment]
Having one DataLoaderRegistry and Dataloader per request is exactly what I was trying to do.

My problem comes in fact from the spring boot graphql plugin that I'm using and by default it comes with one singleton Instrumentation/DataloaderRegistry and doesn't create a new Instrumentation/DataLoaderRegistry for each request.

After customizing this behaviour I can now create one DataloaderRegistry and Dataloader per request and it works fine.

I'm closing this issue.

Thanks for your help.

**Comment by szantogab** [comment]
@mogaleaf Can you tell me please, how you have managed to create a DataLoaderRegistry per request with spring-boot-graphql plugin?

Thanks!

**Comment by mogaleaf** [comment]
@szantogab I have extended the SimpleGraphQLServlet and override the `protected Instrumentation getInstrumentation()` method.
This method is called at each request so you can create a new Instrumentation at each request.

In GraphQlServlet you have 
`
private GraphQL newGraphQL(GraphQLSchema schema) {
        ExecutionStrategyProvider executionStrategyProvider = getExecutionStrategyProvider();
        return GraphQL.newGraphQL(schema)
            .queryExecutionStrategy(executionStrategyProvider.getQueryExecutionStrategy())
            .mutationExecutionStrategy(executionStrategyProvider.getMutationExecutionStrategy())
            .subscriptionExecutionStrategy(executionStrategyProvider.getSubscriptionExecutionStrategy())
            .instrumentation(getInstrumentation())
            .preparsedDocumentProvider(getPreparsedDocumentProvider())
            .build();
    }
`
