### ISSUE TITLE
SchemaUtil.findImplementations causes significant degradation of execution performance

### ISSUE THREAD

**Issue by gkesler** [graphql-java/graphql-java#896]
`SchemaUtil.findImplementations` has O(N^2) complexity and this causes significant degradation of query execution performance.
This is a redundant task that is performed twice per query:
1. during validation
2. during execution

Proposal:
Create an index of GraphQLObjectTypes by GraphQLInterface they implement and cache that in a map in a GraphQLSchema member variable. This way complexity of `SchemaUtil.findImplementations` gets reduced from O(N^2) to O(1) and our tests demonstrate up 10x performance boost.

**Comment by bbakerman** [comment]
Fixed via https://github.com/graphql-java/graphql-java/pull/898

**Comment by bbakerman** [comment]
PR accepted (and tweaked)
