### ISSUE TITLE
Apache Commons 

### ISSUE THREAD

**Issue by exbe** [graphql-java/graphql-java#902]
Hello!
I wanna check the community and authors thought on bringing dependencies like `commons-collections4` or `commons-lang3`.

These implementations are mature enough and trustworthy, also they help to reduce code duplicates (such as Fluent traversable and bunch of utils methods), some of it can be re-used today.

Is that a good idea or making graphql lib thin as possible has higher priority over code/algorithms  duplication?

**Comment by bbakerman** [comment]
We have as a project goal of keeping the library as dependency free as possible

So yes we will choose to duplicate code at the expense of adding new dependencies.

That is what things like commons-xxx or guava say are not a dependency.

So far it has served us really well.
