### ISSUE TITLE
Allow defining empty types

### ISSUE THREAD

**Issue by sammyhk** [graphql-java/graphql-java#903]
According to graphql/graphql-js#937 now support defined empty type like:
```graphql
type MyType
```
but currently graphql-java not supported. This is a useful feature, please consider to support.

Similar issue link to here: graphql-java/graphql-java-tools#70

**Comment by bbakerman** [comment]
Investigations reveal that empty types are allowed

https://github.com/graphql/graphql-js/blob/master/src/language/__tests__/schema-kitchen-sink.graphql#L15-L29

and the RFC for the type spec updates is here

https://github.com/facebook/graphql/pull/90/files

namely

     ObjectTypeDefinition : Description? type Name ImplementsInterfaces? Directives[Const]? FieldsDefinition?

that is fields are optional
