### ISSUE TITLE
Enum List as input

### ISSUE THREAD

**Issue by alexcibotari** [graphql-java/graphql-java#911]
Hello,

I have next GraphQL definition:
```
Query {
countries(regions: [Region!]): [Country!]
}

enum Region {
  EUROPE
  ASIA
}

type Country {
  code: String!
  name: String!
  regions: [Region!]
}
```
and Java
`
public Set<Country> getCountries(Set<RoamingRegion> regions)
`
or
`
public Set<Country> getCountries(Optional<Set<RoamingRegion>> regions)
`

when I do a request to GraphQL-Java i receive an error 

```
{
  "data": null,
  "errors": [
    {
      "message": "Validation error of type VariableTypeMismatch: Variable type doesn't match",
      "locations": [
        {
          "line": 2,
          "column": 43
        }
      ],
      "description": "Variable type doesn't match",
      "validationErrorType": "VariableTypeMismatch",
      "errorType": "ValidationError",
      "path": null,
      "extensions": null
    }
  ]
}
```

**UPDATE :**

```
query getCountries($regions: [Region]!) {
  countries(regions: $regions){
    code
    name
    regions
  }
}
```
as variables I send list of Regions as String because TypeScript automatically convert Array of Enums in to Array of Strings
```
['EUROPE','ASIA']
```

if I try the same but instead of List of Regions I use Single enum as input, everything works :(
This why I think problem is in List of Enums

**Comment by bbakerman** [comment]
I cant see your graphql query not can I see your variables you pass in.

So I am sorry without that I cant help you

**Comment by alexcibotari** [comment]
Hello @bbakerman , I have updated description with variables

**Comment by bbakerman** [comment]
Can you please write a unit test that shows this bug in action.  A rough guess says it should work

I unit test would help me debug this a lot

**Comment by alexcibotari** [comment]
I'm not familiar with your code, but if you help me I can write several Unit Tests.
I would like to create schema exactly as in description and execute a query in order to check what I will receive in Java.

**Comment by bbakerman** [comment]
Ahh I found your problem by writing this unit test

```
    def "test enum list as args"() {
        def spec = '''
            type Query {
                countries(regions: [Region!]): [Country!]
            }

            enum Region {
              EUROPE
              ASIA
            }
            
            type Country {
              code: String!
              name: String!
              regions: [Region!]
            }
        '''

        def countriesFetcher = new DataFetcher() {
            @Override
            Object get(DataFetchingEnvironment env) {
                assert env.getArgument('regions') != null
                return null
            }
        }
        def schema = TestUtil.schema(spec, [Query: [countries: countriesFetcher]])
        def graphQL = GraphQL.newGraphQL(schema).build()

        when:
        def query = '''
                query getCountries($regions: [Region!]) {
                    countries(regions: $regions) {
                      code
                      name
                      regions
                    }
                }
            '''
        def result = graphQL.execute(ExecutionInput.newExecutionInput()
                .query(query)
                .variables([regions: ['EUROPE', 'ASIA']])
        )

        then:

        result.errors.isEmpty()

    }
```

Which works.  Your problem is that your have specified the Regions argument and Regions variable definition differently originally

     countries(regions: [Region!])
     ....
    query getCountries($regions: [Region]!) {

that is `[Region!]`   does not equal `[Region]!`

the first is a list of non null enums and the second is a non null list of (possibly null) enums

Thats the problem here.

I will look to see what we can do in the error message to make it more apparent
