### ISSUE TITLE
Should the value returned from parseLiteral persist through to the DataFetcher?

### ISSUE THREAD

**Issue by joshstrange** [graphql-java/graphql-java#912]
I have a custom data fetcher that I have written as well as GraphQLScalarType. 

    GraphQLScalarType GraphQLTimestamp = new GraphQLScalarType("Timestamp", "Timestamp", new Coercing() { ... }

I have set my custom type on my annotation:

    arguments.add(GraphQLArgument.newArgument().name("lessThan").type(GraphQLTimestamp).build()); 

When I pass data into GraphQL it does run through the parseLiteral() function and with breakpoints I can see it is creating a GregorianCalendar as expected (from a integer timestamp). However once I get to my DataFetcher my argument is still just an IntValue.

Using breakpoints this makes sense as my parseLiteral is only called during validation. Am I understanding correctly that parseLiteral is ONLY used for validation and not used to manipulate data as it comes into the system?

Thank you!

**Comment by bbakerman** [comment]
Hmm I need to look deeper

Also do you know about : https://github.com/donbeave/graphql-java-datetime

**Comment by bbakerman** [comment]
Also I would need a copy of your ScalarCode to judge

**Comment by joshstrange** [comment]
@bbakerman I have seen that but we use unix timestamps everywhere and I don't see support for that in that library.

Here is my code

````
public static GraphQLScalarType GraphQLTimestamp = new GraphQLScalarType("Timestamp", "Timestamp", new Coercing() {
	@Override
	public Object serialize(Object input) {
		return input;
	}

	@Override
	public Object parseValue(Object input) {
		GregorianCalendar calendar = new GregorianCalendar();
		calendar.setTimeInMillis(((IntValue)input).getValue().multiply(new BigInteger("1000")).longValue());
		return calendar;
	}

	@Override
	public Object parseLiteral(Object input) {
		GregorianCalendar calendar = new GregorianCalendar();
		calendar.setTimeInMillis(((IntValue)input).getValue().multiply(new BigInteger("1000")).longValue());

		return calendar;
	}
});
````

**Comment by bbakerman** [comment]
The parseLiteral is used during execution to create the variables map and to tur Argument values (which are AST) into argument values

```
    protected CompletableFuture<Object> fetchField(ExecutionContext executionContext, ExecutionStrategyParameters parameters) {
   ...
        Map<String, Object> argumentValues = valuesResolver.getArgumentValues(fieldVisibility,
    ....
```

See `graphql.execution.ValuesResolver#getArgumentValues(graphql.schema.visibility.GraphqlFieldVisibility, java.util.List<graphql.schema.GraphQLArgument>, java.util.List<graphql.language.Argument>, java.util.Map<java.lang.String,java.lang.Object>)`

**Comment by bbakerman** [comment]
Ok so I took your code and wrote a unit test for it (in Groovy which is what we use to test graphql-java)

```
    def "test912"() {
        GraphQLScalarType GraphQLTimestamp = new GraphQLScalarType("Timestamp", "Timestamp", new Coercing() {
            @Override
            public Object serialize(Object input) {
                return input;
            }

            @Override
            public Object parseValue(Object input) {
                GregorianCalendar calendar = new GregorianCalendar();
                BigInteger value = new BigInteger(String.valueOf(input))
                calendar.setTimeInMillis(value.multiply(new BigInteger("1000")).longValue());
                return calendar;
            }

            @Override
            public Object parseLiteral(Object input) {
                if (input == null) {
                    return null
                }
                GregorianCalendar calendar = new GregorianCalendar();
                calendar.setTimeInMillis(((IntValue) input).getValue().multiply(new BigInteger("1000")).longValue());

                return calendar;
            }
        })

        def spec = """
                type Query {
                    field1 (arg : Timestamp) : Timestamp
                    field2 (arg : Timestamp) : Timestamp
                }
                
                scalar Timestamp
                    
        """
        def argEchoDataFetcher = new DataFetcher() {
            @Override
            Object get(DataFetchingEnvironment environment) {
                return environment.getArgument("arg")
            }
        }
        def schema = TestUtil
                .schema(spec, RuntimeWiring.newRuntimeWiring()
                .scalar(GraphQLTimestamp)
                .type(
                newTypeWiring("Query")
                        .dataFetcher("field1", argEchoDataFetcher)
                        .dataFetcher("field2", argEchoDataFetcher)
        ).build())

        def graphQL = GraphQL.newGraphQL(schema).build()

        def bDay = 666

        when:
        def query = '''
            query OpName( $var1 : Timestamp) {
                field1(arg : $var1)
                field2(arg : 1) 
            }
        '''
        def result = graphQL.execute(newExecutionInput().query(query).variables(var1: bDay))

        then:
        result != null
        (result.data['field1'] as GregorianCalendar).toInstant().toEpochMilli() == 666000
        (result.data['field2'] as GregorianCalendar).toInstant().toEpochMilli() == 1000
```

It works as expected.  However I did need to tweak your Corecing function a little

Basically you used IntValue.getValue in the `parseValue` method.  This is not right.  The objects that come into `parseValue` are from the variables map and are not AST literals.

That is what `parseLiteral` handles

Notice in the query

     query OpName( $var1 : Timestamp) {
                field1(arg : $var1)
                field2(arg : 1) 
            }

We have 1 field whose argument from from the variable map (field1) and one that is an AST literal (field2)

Both get to the data fetcher as expected

**Comment by bbakerman** [comment]
I am going to close this issue because the system is working as expeceted if the Coercing is written correctly.

I did  find a bug while doding this : https://github.com/graphql-java/graphql-java/issues/916

which explains if null workaround in the parseLiteral above (when used with Schema generation).
