### ISSUE TITLE
SchemaPrinter does not print directives

### ISSUE THREAD

**Issue by kclaes** [graphql-java/graphql-java#920]
As title.

I'm using the TypeDefinitionRegistry to programmatically add types to a schema, but upon printing this schema, the (existing and new) directives are not printed.

Code used (in case I'm going about this the wrong way):
`
        String schema = new SchemaPrinter(SchemaPrinter.Options.defaultOptions().includeScalarTypes(true).includeExtendedScalarTypes(true)).print(UnExecutableSchemaGenerator.makeUnExecutableSchema(registry));
`

**Comment by bbakerman** [comment]
Yes - we dont currently hold SDL directives into the runtime system - but we are adding support for it and hence can add support to print directives

Thanks for reporting...we will get onto it

**Comment by bbakerman** [comment]
Work breakdown 

* we start with printing directives from GraphqlObjectType / GraphqlFieldDefinition
* we add the other types once we have directives on them
