### ISSUE TITLE
Can't modularise the Schema SDL with graphql-java 7.0

### ISSUE THREAD

**Issue by sp00m** [graphql-java/graphql-java#928]
The provided snippet in the docs does not compile: http://graphql-java.readthedocs.io/en/v7/schema.html#modularising-the-schema-sdl

My code so far:

```java
        SchemaParserOptions options = newOptions()
                .useDefaultGenericWrappers(true)
                .build();
        SchemaParser parser = newParser()
                .file("schema.graphqls")
                .options(options)
                .scalars(toArray(scalars, GraphQLScalarType.class))
                .resolvers(resolvers)
                .build();
        GraphQLSchema schema = parser
                .makeExecutableSchema();
        return newGraphQL(schema)
                .queryExecutionStrategy(new BatchedExecutionStrategy())
                .build();
```

I plan to merge multiple .graphqls files to improve scalability, but `SchemaParser schemaParser = new SchemaParser();` does not compile, plus `SchemaParser#parse(...)` does not exist.

**Comment by bbakerman** [comment]
Are you sure you are using pure graphql-java and not some other graphql-java based library that wraps graphql-java?  

Because none of the code above even exists in graphql-java as described, eg the `.file("schema.graphqls"))` and so on are not from our code base

**Comment by sp00m** [comment]
@bbakerman Oops good catch, I'm indeed using graphql-java-tools, I did not notice it has another way of initializing all this, my bad!
