### ISSUE TITLE
WiringFactory should provide Scalars

### ISSUE THREAD

**Issue by ceronman** [graphql-java/graphql-java#930]
Using `WiringFactory` with a `RuntimeWiring` allows for fine control of what data fetchers and type resolvers are used. However, the `WiringFactory` interface doesn't allow to specify custom scalars.

I propose to add two new methods to `WiringFactory`:

```java
boolean providesScalar(ScalarWiringEnvironment environment)
```
and
```java
GraphQLScalarType getScalar(ScalarWiringEnvironment environment)
```
If this makes sense I'm willing to provide a pull request.

**Comment by bbakerman** [comment]
yes this makes sense -  we have it on RuntimeWiring via a getScalars() method but yes the WiringFactory should allow it.  

Please make a PR if you can
