### ISSUE TITLE
Tutorial is out of date

### ISSUE THREAD

**Issue by rmcloughlin** [graphql-java/graphql-java#934]
In README.md there is this line:

_There is also an excellent tutorial here : https://www.howtographql.com/graphql-java/0-introduction/_

I started following the tutorial and then noticed that it was a bit out of date.  Then I saw this comment https://github.com/howtographql/howtographql/issues/100#issuecomment-365698574 in which the author of the tutorial says

_And now I think I must rewrite the tutorial as the landscape changed too much in the meantime._

So maybe README.md should be changed to say that it's a "slightly out-of-date" tutorial, or something like that.

**Comment by bbakerman** [comment]
cc: @kaqqao  - thoughts

**Comment by kaqqao** [comment]
Ah, yes. Please do put a note for the time being, and I'll start rewriting it as soon as I can. It is true that it is outdated and must be substantially changed.
