### ISSUE TITLE
Unable to get raw variables/not parsed into arguments

### ISSUE THREAD

**Issue by joshstrange** [graphql-java/graphql-java#938]
I have the following query:

````
query calendarItemQuery($title: String!) {
	CalendarItem(title: $title) {
		title
		start(orderBy: DESC)
	}
}
````

variables:

````
{
    "title": "My title"
}
````

Which works just fine, I can find the "title" -> "My title" mapping in `environment.getArgument("title")`. However if I try this query instead:

````
query calendarItemQuery($gt: Timestamp!) {
	CalendarItem {
		title
		start(orderBy: DESC, greaterThan: $gt)
	}
}
````

with variables:

````
{
    "gt": 1519448400
}
````

Then `environment.getArguments()` is empty. I can see the variables on `environment.getSelectionSet().variables` but it is private and there is no way to get it. I have tracked my variable all the way though the codebase to when it disappears and it is [here](https://github.com/graphql-java/graphql-java/blob/688d15769e627c6fb3e55e2efd1ad2fe41b86626/src/main/java/graphql/execution/ExecutionStrategy.java#L199) when my variable is passed into `valuesResolver.getArgumentValues()`. My "title" makes it through but "gt" does not. Am I missing something about how I should be passing variables?

**Comment by bbakerman** [comment]
How are you resolving the Timestamp scalar type?

**Comment by bbakerman** [comment]
I suspect you are getting parse errors under the covers

**Comment by joshstrange** [comment]
@bbakerman Thank you for your input! Where can I look for said parse errors (or where can I put my breakpoint to check)?

Timestamp is a Scalar type that I defined:

````
public static GraphQLScalarType GraphQLTimestamp = new GraphQLScalarType("Timestamp", "Timestamp", new Coercing() {
		@Override
		public Object serialize(Object input) {
			return input;
		}

		@Override
		public Object parseValue(Object input) {
			GregorianCalendar calendar = new GregorianCalendar();
			BigInteger value = new BigInteger(String.valueOf(input));
			calendar.setTimeInMillis(value.multiply(new BigInteger("1000")).longValue());
			return calendar;
		}

		@Override
		public Object parseLiteral(Object input) {
			if (input == null) {
				return null;
			}
			GregorianCalendar calendar = new GregorianCalendar();
			calendar.setTimeInMillis(((IntValue) input).getValue().multiply(new BigInteger("1000")).longValue());

			return calendar;
		}
	});
````

 Also I can see it getting correctly set in the coercedValues HashMap and it's in the executionContext.getVariables() it just never makes it into the DataFetchingEnvironment, or more importantly it's lost after this line:

````
        Map<String, Object> argumentValues = valuesResolver.getArgumentValues(fieldVisibility, fieldDef.getArguments(), field.getArguments(), executionContext.getVariables());

````

in ExecutionStrategy.fetchField()

**Comment by bbakerman** [comment]
Check out the values in `executionContext.getVariables()` before its passed into the resolver code.

That contains the variables as defined by the outside query.  Check you have the input you expect.

`graphql.execution.ValuesResolver#coerceValueForScalar` is really the only place where it calls parseValue()

**Comment by joshstrange** [comment]
@bbakerman Interesting, I'm finding that variables never work for me unless they share the exact same name as the field for which they are a variable for. I think this is my actual issue as I can get variables working for a timestamp (my custom scalar) if I name it "created" and use graphql to search for a record created at a specific time (useless in practice but proves my point they work). Same with for example searching for a user by username. If I name the variable "username" it all works, if I name it "user1" or "myUser" then it stops working. 

I could almost accept this as a limitation but it breaks down if I have a query like the following:

````
query myTwoBestFriends($friendOne: String!, $friendTwo: String!) {
    friendOne: User(username: $friendOne) {
         id
         username
         email
    }
    friendTwo: User(username: $friendTwo) {
         id
         username
         email
    }
}
````

Passing up variables:

````
{
    "friendOne": "joeyt",
    "friendTwo": "rossg"
}
````

I believe the source of my problems is coming from the ValuesResolver.getArgumentValues() function which receives my valid variables but since they don't match field names it throws them away.

**Comment by bbakerman** [comment]
Ahh I got it now - yes you can just invent argument names in graphql.

From your example query above the argument to the user field is called "username".  It cannot be called 'user' or 'myUser' because the schema is a well defined thing.  fields and arguments MUST be called by the name

I wrote a quick unit test to show this

```
class Issue938 extends Specification {

    public static GraphQLScalarType GraphQLTimestamp = new GraphQLScalarType("Timestamp", "Timestamp", new Coercing() {
        @Override
        Object serialize(Object input) {
            return input
        }

        @Override
        Object parseValue(Object input) {
            GregorianCalendar calendar = new GregorianCalendar()
            BigInteger value = new BigInteger(String.valueOf(input))
            calendar.setTimeInMillis(value.multiply(new BigInteger("1000")).longValue())
            return calendar
        }

        @Override
        Object parseLiteral(Object input) {
            if (input == null) {
                return null
            }
            GregorianCalendar calendar = new GregorianCalendar()
            calendar.setTimeInMillis(((IntValue) input).getValue().multiply(new BigInteger("1000")).longValue())

            return calendar
        }
    })

    class UserImpl {
        int id
        String username
        String email
    }


    def "938 custom scalar and variables"() {

        def schemaSDL = '''
            
            type User {
                id : Int
                username : String 
                email : String
            }
            
            type Query {
                User(username : String!) : User
            } 
        '''
        def userDataFetcher = new DataFetcher() {
            @Override
            Object get(DataFetchingEnvironment env) {
                def username = env.getArgument("username")
                return new UserImpl(id: 1, username: username, email: username + '@gmail.com')
            }
        }
        def runtimeWiring = RuntimeWiring.newRuntimeWiring()
                .scalar(GraphQLTimestamp)
                .type(
                TypeRuntimeWiring.newTypeWiring("Query")
                        .dataFetcher("User", userDataFetcher)
                        .build())
                .build()
        def schema = TestUtil.schema(schemaSDL, runtimeWiring)
        def graphql = GraphQL.newGraphQL(schema).build();

        when:
        def input = ExecutionInput.newExecutionInput()
                .query('''
                        query myTwoBestFriends($friendOne: String!, $friendTwo: String!) {
                            friendOne: User(username: $friendOne) {
                                 id
                                 username
                                 email
                            }
                            friendTwo: User(username: $friendTwo) {
                                 id
                                 username
                                 email
                            }
                        }
                        ''')
                .variables(["friendOne": "joeyt", "friendTwo": "rossg"])
                .build()
        def executionResult = graphql.execute(input)

        then:
        executionResult.errors.isEmpty()
        executionResult.data == [friendOne:
                                         [id: 1, username: 'joeyt', email: 'joeyt@gmail.com'],
                                 friendTwo:
                                         [id: 1, username: 'rossg', email: 'rossg@gmail.com']
        ]


    }
```

All works as expected.  But the query arguments MUST be called 'username'.  

In fact working on this I found a NullPointerException bug in the new error reporting which I will fix.

Hence the PR associated with this issue.  However over all the system is working as expected regarding variables and so on as mentioned above

**Comment by bbakerman** [comment]
See https://github.com/graphql-java/graphql-java/pull/954 for the bug I found
