### ISSUE TITLE
Remove Java exceptions from graphql errors

### ISSUE THREAD

**Issue by bbakerman** [graphql-java/graphql-java#939]
Mostly clients dont care about getting the Java exception in a graphql error.  A browser JS or Mobile client cant do anything useful with it.

Its mildly useful in "dev mode" when exceptions happen as code is immature but once its production the value drops greatly.

A large number of people have asked for this over time.

We should revisit the errors that capture an exception and rather focus on logging say

**Comment by bbakerman** [comment]
Ok looking into this perhaps the biggest surface error will be `graphql.ExceptionWhileDataFetching`

It is declared as

    public class ExceptionWhileDataFetching implements GraphQLError {
      private final String message;
      private final List<Object> path;
      private final Throwable exception;
      private final List<SourceLocation> locations;
     private final Map<String, Object> extensions;

That is is explicitly has a an exception member and Jackson / GSon will reflect that if you call toJson() in it

But there a number of other errors that are in fact exceptions

Things like `public class MissingRootTypeException extends GraphQLException implements GraphQLError {` and so on

They extend `GraphQLException` (runtime type) and implement `GraphQLError` so they can be placed as is inside the error collection.

This is typical where we throw an exception on an exceptional path and just add it to the error collection higher up.

If we took the exceptions out, we would have to translate them to errors at catch point into a more generic `GraphQLError`

The more I look into this the more I think the `.toSpecification()` is they way to go at the end of the run.  

A twist on that is that perhaps we put "instructions" into the graphql setup that says to "convert to spec" errors on the way out autmatically (instead of requring them to do it before they serialise)

eg

    newExecutionInput().query("{ foo }").convertErrorsToSpecification().build();

Which means the ExecutionResult would inherently be spec compliant and no exceptions

Thoughts @andimarek / @kaqqao ?

**Comment by bbakerman** [comment]
The more I looked into this (and build some generic code solutions which turn GrapqlErrorsWithExeptions -> NoExceptionGrapqlErrors) the less I think we have anything to do

The "make errors to spec" already exists.  Such that you can just call .toSpecification() on the result and your done.

How in an calling library like graphql-java-servlet they will need to do some work to expose that switch but really it's there responsibility not the main library.

**Comment by kaqqao** [comment]
Sorry I never replied! Somehow missed it :(
Either way, I totally agree. I think it's both important and useful to keep the exception available in the result, and to give an easy serialization option. And graph-java already does both...

The only mildly confusing thing is that some `GraphQLError`s _contain_ an exception while some _are_ an exception, and would maybe prefer if there was a single approach (e.g. if all `GraphQLError`s wrapped an exception and exposed it via `getCause` or something), but that's a different topic probably.
