### ISSUE TITLE
NonNullableFieldWasNullError renders null locations field

### ISSUE THREAD

**Issue by martin-walsh** [graphql-java/graphql-java#940]
According to GraphQL spec for errprs, location field if included cannot be null, it should instead be ommitted if empty.

> If an error can be associated to a particular point in the requested GraphQL document, it should contain an entry with the key locations with a list of locations, where each location is a map with the keys line and column, both positive numbers starting from 1 which describe the beginning of an associated syntax element.
http://facebook.github.io/graphql/October2016/#sec-Errors

It looks like the offending code withing `NonNullableFieldWasNullError` is
```
    @Override
    public List<SourceLocation> getLocations() {
        return null;
    }
```

This getter should be annotated with `@JsonInclude.NON_NULL` or `@JsonIgnore`

See https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/execution/NonNullableFieldWasNullError.java

**Comment by martin-walsh** [comment]
I should also state that my issues are arising through usage of graphql-java-servlet project & that my assumed use case is rendering errors to json with Jackson.  If you feel the fix is more appropriate in that project given the lack of dependency upon jackson, please close this issue and I will open an issue within graphql-java-servlet instead

**Comment by andimarek** [comment]
Hi,
we don't deal with jackson or other serialization specific issues in this topic. So we can't add any annotations as you mentioned.
We provide this method https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/ExecutionResult.java#L31 
to help with such cases, but I am not sure out of my head if the location case is properly handled.

**Comment by martin-walsh** [comment]
Ok, thanks, I'll dig further & see what can be done downstream
