### ISSUE TITLE
Add "posibleTypes" to "GraphQLInterfaceType"

### ISSUE THREAD

**Issue by guy120494** [graphql-java/graphql-java#950]
Is it possible to add a function `posibleTypes` to `GraphQLInterfaceType`, like `GraphQLUnionType` has? It will help me to have a nice annotation of `@GraphQLInterface(possibleTypes={..})` like `@GraphQLUnion` has. As for my understanding, interface and unions have the same functionality expect interface has common fields, so it seems fair to add this function

**Comment by andimarek** [comment]
the problem here is that each Interface can be implemented from a number objects. This means we can't just add add a field to it without having the full schema resolved. There is a method  which does i want I think: `SchemaUtil.findImplementations`

**Comment by guy120494** [comment]
It is not quite what I want, because I want to know the implementations of the interface when building the schema (that are specified by `@GraphQLInterface(possibleTypes={..})`)
I guess that's the difference between programmatically building the schema and building the schema with SDL. Well, I just to stay with what I have now

**Comment by andimarek** [comment]
I don't think I understood u correctly: what do u mean with "specified by `@GraphQLInterface(possibleTypes={..})`"?

**Comment by guy120494** [comment]
I'm one of the maintainers of the annotations project. I want to add support for interfaces (What we have now is not enough in my opinion). For that I want to add a new annotation `@GraphQLInterface` that can be put on interfaces. The problem is: how do I know which classes implement the interface?
I was thinking that we could have an option to specify which classes implement the interface(`@GraphQLInterface(possibleTypes={A.class, B.class}`), but on second thought I don't think it is a good idea, because that way we cannot have other classes implement this interface(like if we import the interface from external jar, we cannot implement it). Do you have any idea how can we do that? 

P.s, I noticed that if we have the interface in the schema, then the schema doesnt recognize the implementations of it, unless they are explicitly specified in the schema

Exmaple:
Lets say that under `Query` I have only the interface `Animal`. The interface has 2 implementation: `Dog` and `Cat`. When I build the schema it doesn't recognize the `Dog` and `Cat` classes, but if under `Query` I have `Animal`, `Cat`,`Dog` then the schema recognizes that `Cat` and `Dog` implement `Animal`

**Comment by bbakerman** [comment]
Interfaces in the type system are "implemented" by object types.

So I would imagine it looks like this

@GraphQLInterface
class SomeInterface {
     ....
}


@GraphQLObject(implements = { SomeInterface.class }
class SomeObjectType {
   ..


or something like that

This is annotation equivalent of SDL like

```
interface SomeInterface {
 ...
}

type SomeObjecType implements SomeInterface {

}


```

notice how its the object type that says what is implemented.  This is the only way that makes sense to me...  an interface cant dictate who implements it - only an object type can choose to have that shape.

**Comment by guy120494** [comment]
You are right, it does make more sense, I will try that.
About my other question: If the only field of a query is an interface, does the schema suppose know what objects implement it (even though they are not explicitly specified as fields in any place of the schema)?

**Comment by bbakerman** [comment]
> If the only field of a query is an interface, does the schema suppose know 

Um I am not sure of the question.  Can you please be more precise, perhaps in SDL shorthand to illustrate your point

**Comment by guy120494** [comment]
Lets say I have this schema:
```
interface SomeInterface {
 age:Int
}

type SomeObjecType implements SomeInterface {
name:String
}

type Query {
field:SomeInterface
}
```
So the only field in my schema (under Query) is the interface.
When I try to query my server I can't do
```
query {
        field{
               ... on SomeObjectType{name}
              }
}
```
because the schema doesnt know `SomeObjectType`.
But if I have:
```
type Query {
field:SomeInterface
object:SomeObjectType
}
```
I can run the query above, because the schema knows `SomeObjectType` and it knows it implements `SomeInterface`

Is that suppose to be like that? or is a bug in the annotations? if so, I have no idea how to fix that

**Comment by bbakerman** [comment]
I think this is a bug in your annotations library.

In native graphql-java SDL, we add the additional types (not referenced from the operations but defined in the schema)

```
        Set<GraphQLType> additionalTypes = buildAdditionalTypes(buildCtx);

        return schemaBuilder.build(additionalTypes);
  ...
         /**
     * We build the query / mutation / subscription path as a tree of referenced types
     * but then we build the rest of the types specified and put them in as additional types
     *
     * @param buildCtx the context we need to work out what we are doing
     *
     * @return the additional types not referenced from the top level operations
     */
    private Set<GraphQLType> buildAdditionalTypes(BuildContext buildCtx) {
        Set<GraphQLType> additionalTypes = new HashSet<>();
        TypeDefinitionRegistry typeRegistry = buildCtx.getTypeRegistry();
        typeRegistry.types().values().forEach(typeDefinition -> {
            TypeName typeName = new TypeName(typeDefinition.getName());
            if (typeDefinition instanceof InputObjectTypeDefinition) {
                if (buildCtx.hasInputType(typeDefinition) == null) {
                    additionalTypes.add(buildInputType(buildCtx, typeName));
                }
            } else {
                if (buildCtx.hasOutputType(typeDefinition) == null) {
                    additionalTypes.add(buildOutputType(buildCtx, typeName));
                }
            }
        });
        return additionalTypes;
    }

```

I am guessing that the annotations library forms a tree from "root types" down wards say.  I dont think you can safely do this.
