### ISSUE TITLE
PreparsedDocumentProvider computeFunction not executed as documented

### ISSUE THREAD

**Issue by ric2016** [graphql-java/graphql-java#951]
PreparsedDocumentProvider.get has an argument 
`Function<String, PreparsedDocumentEntry> computeFunction`
documented as "If the query has not be pre-parsed, this function can be called to parse it"

However, the function input ('query') isn't used when this function is called in GraphQL.java:
`PreparsedDocumentEntry preparsedDoc = preparsedDocumentProvider.get(executionInput.getQuery(), query -> parseAndValidate(executionInput, graphQLSchema, instrumentationState));`

This should be changed to
`PreparsedDocumentEntry preparsedDoc = preparsedDocumentProvider.get(executionInput.getQuery(), query -> parseAndValidate(executionInput.transform(b -> b.query(query)), graphQLSchema, instrumentationState));`

As long as actual query strings are used, the effect is the same. However, the proposed fix allows referencing queries by aliases (e.g. ids), and using the PreparsedDocumentProvider as the resolver. 

(If this isn't the intended use case, at least the argument in PreparsedDocumentProvider.get should be changed to `Supplier<PreparsedDocumentEntry>` to avoid giving the impression that PreparsedDocumentProvider could be used as a resolver)

**Comment by bbakerman** [comment]
Ahh your right - this seems to have been lost in a refactor.

It is intended as a way to allow say "reference queries" to be turned into say full queries but it seems to have gotten lost in the wash.

I will make this change...

**Comment by bbakerman** [comment]
Now in place
