### ISSUE TITLE
Support of @defer 

### ISSUE THREAD

**Issue by bbakerman** [graphql-java/graphql-java#956]
There is power in allowing two classes of data to flow out a graphql query.  The data I need right now and the data I could do with a bit later.

https://dev-blog.apollodata.com/new-features-in-graphql-batch-defer-stream-live-and-subscribe-7585d0c28b07

There are experimental implementations out there that allow you to specify that a portion of the query can be delivered later

     query {
            hero {
                 id
                 name
                 friends @defer {
                        id
                        name
                }
           }
     }

So in the example above we have hero data coming down first, followed by friends data later.

# How to reflect this as a return type?

The first challenge I see is how to reflect this as a return type.  In some ways its like our current subscription support in that its a stream of results that comes back.  One now and some later.  Thats really a reactive stream, which we kind a of have.

Today subscriptions come back as a `Publisher` first data object in the execution result

    ExecutionResult executionResult = graphql.execute('subscription { ...}');
    Publisher<ExecutionResult> stockPriceStream = executionResult.getData();

We could model it like that, that is if any @defer is present then we give you a similar construct.  This would not break API.

However its not intuitive an a Java sense.  You have to KNOW you have @defer directives in the query to KNOW you have to expect this return type shape.

Perhaps we should require people to "buy into" this shape via an api call like

   CompletableFuture<Publisher<ExecutionResult> streamCF = graphql.asyncStream('subscription { ...}');

Its crystal clear (albeit a bit long winded) what you get back here.  Same with subscription where we make you call it via the cleaner API.  This is a *breaking change* on API shape.

# How to execute this in an execution strategy?

There are two challenges I see.  One is to shortcut out when you encounter a @defer ed field in the query and then  how to execute on that promise to deliver the rest of the data.

Does it imply multi threading?  That is who caused the later @defer fields to be executed?

In subscription we rely on that fact that the inner "Publisher" is in control of sending data.  We set it up and then some other actor will cause the data to flow.

But @defer means we are the actor on the later data.  And so far graphql-java has studiously avoided multi threading or having a hard implementation on a reactive stream implementation (say RxJava) to actually call on.

So I can see that supporting @defer would involve us have a dep on Rxjava or at least have an SPI where some one has to provide a `PublisherFactory` that will be given a callback to wrap

    interface PublisherFactory {
         Publisher<ExecutitionResult> getDeferPublisher()
    }

And then we need a way to "act" again once we give this back out.  That is we return to the caller early but continue processing (via another thread??)

# How deep do you allow it

Design question is - how many levels deep can you specify @defer.  One makes a lot of sense but why not more?

     query {
            hero {
                 id
                 name
                 friends @defer {
                        id
                        name
                        friends @defer {
                           name
                        }
                }
           }
     }

It gets complicated in some sense with more than one but perhap each @defer is simply a return shotcut with a promise to deliver the rest later

**Comment by bbakerman** [comment]
@kaqqao / @apottere / @andimarek  - thoughts?

**Comment by andimarek** [comment]
I think it is a real life requirement we should support at some point.
But I agree: the implementation is not really obvious.

I think one of the most successful design decisions of graphql-java is not to deal with json parsing/http connection/mutlithreading (except very few occasions) and also only include very few dependencies.

Without knowing how it would look in detail I would strongly prefer to keep `graphql-java` this way. But I also think that we should provide some easy to use implementation (based on RxJava or whatever). So I think extracting the heart of the defer implementation  in a extra artifact like `graphql-java-defer` or so makes sense. We could achieve this without adding too much overhead by converting this repo into a gradle multiproject build. So far my thoughts on the meta level regarding dependenies/artifacts.

I think I need so see some kind of spike to get a real feeling how an implementation could look like in detail. But again: I am totally for at least trying to implement it.👍

**Comment by andimarek** [comment]
a first version of this is now shipped in 8.0: https://github.com/graphql-java/graphql-java/pull/967
