### ISSUE TITLE
GraphqlErrorHelper.toSpecification should write the errorType

### ISSUE THREAD

**Issue by patteblanche** [graphql-java/graphql-java#961]
Error type is not added to the error map by toSpecification().  

```
@SuppressWarnings("SimplifiableIfStatement")
public class GraphqlErrorHelper {

    public static Map<String, Object> toSpecification(GraphQLError error) {
        Map<String, Object> errorMap = new LinkedHashMap<>();
        errorMap.put("message", error.getMessage());
        if (error.getLocations() != null) {
            errorMap.put("locations", locations(error.getLocations()));
        }
        if (error.getPath() != null) {
            errorMap.put("path", error.getPath());
        }
        if (error.getExtensions() != null) {
            errorMap.put("extensions", error.getExtensions());
        }
        return errorMap;
    }
```

**Comment by patteblanche** [comment]
I am seeing that the errorType is not part of the specification: http://facebook.github.io/graphql/October2016/#sec-Errors

Then, maybe the errorType could be added to extensions?  It is confusing to have a field in GraphQLError that is ignored when serialized to json.

**Comment by bbakerman** [comment]
Thats the point of toSpecification() - it only sends the attributes that are "to specification" and not the others.

The errorType is a graphql-java attribute that was invented by the library.  I can see that it would be useful to have even in a specification world

**Comment by patteblanche** [comment]
Ok, got it.

I would add that it is confusing to have members of GraphQLError interface that do not get serialized in the response.

Thanks for your fast response.
