### ISSUE TITLE
Deprecate BatchedExecutionStrategey in 8.0

### ISSUE THREAD

**Issue by andimarek** [graphql-java/graphql-java#963]
We want to deprecate BatchedExecutionStrategy and make it clear it should not be used anymore, but instead batched DataLoader is preferred. 

The reason for deprecating is that it isn't spec conform. (For example null field handling is not correct)

We will remove it once we are sure the alternative is as good as the BatchedExecutionStrategy.
But for now it will stay available.

**Comment by sp00m** [comment]
@andimarek, `BatchedExecutionStrategy` has been deprecated, but the `@Batched` annotation hasn't, and its JavaDoc still reads:

> This annotation must be used in conjunction with `BatchedExecutionStrategy`.

I've been using `@Batched` quite heavily, as it allows avoiding the _select n+1_ issue. Do you have any documentation on how to replace `BatchedExecutionStrategy`? The deprecation notice states:

> BatchedExecutionStrategy has been deprecated in favour of `AsyncExecutionStrategy` and `DataLoaderDispatcherInstrumentation`.

Can one of these understand the `@Batched` annotation kind of the same way `BatchedExecutionStrategy` could? Or should the `@Batched` annotation have been deprecated as well? If so, how to avoid the _select n+1_ issue?

**Comment by bbakerman** [comment]
@sp00m - the @Batched annotation should also be deprecated.  They all serve the purposes of the BatchedExecutionStrategy which should be removed at some stage

**Comment by bbakerman** [comment]
See #1243
