### ISSUE TITLE
Why one root rule for schema AND query parsing?

### ISSUE THREAD

**Issue by escitalopram** [graphql-java/graphql-java#969]
Hi,
I noticed that the antlr parser parses both schemas and queries with the same root rule (document). As a result, it is possible to have type definitions in queries, as well as operations and fragment definitions in schema files, neither of which seems to do anything. Is this intended behavior? Maybe for some kind of planned feature?

**Comment by bbakerman** [comment]
The graphql specification mandates this in a way

https://github.com/facebook/graphql/blob/master/spec/Section%203%20--%20Type%20System.md

That is there is one document defined and it handles queries and schema defintiion

**Comment by escitalopram** [comment]
Thank you. There's no further problem; I'm just trying to understand the codebase better.
