### ISSUE TITLE
Mutations execution strategy

### ISSUE THREAD

**Issue by drkarl** [graphql-java/graphql-java#97]
Is there any technical reason why mutation execution strategy is hardcoded to SimpleExecutionStrategy? Couldn't it use the same strategy used for datafetchers or another one, also specified when building the schema?

**Comment by kirpi4ik** [comment]
Good question, it is definitely something wrong. We had to debug graphQL code to realize that our custom execution strategy was not used for mutations(no exceptions, no log).
Creating hardcoded new instance of SimpleExecutionStrategy inside Execution is weird, more than that our custom execution strategy is already extending SimpleExecutionStrategy.
So if mutation really need to use different strategy at least it must be passed as parameter to GraphQL and not being hardcoded in the Execution.

**Comment by oembedler** [comment]
`SimpleExecutionStrategy` only used to execute actual mutation (it can not be calculated concurrently for instance) - however all other nested fields are resolved using provided custom strategy.
[see this](https://github.com/andimarek/graphql-java/blob/master/src/main/java/graphql/execution/ExecutionStrategy.java#L89)

**Comment by andimarek** [comment]
@oembedler is right: See http://facebook.github.io/graphql/#sec-Evaluating-operations

> If the operation is a mutation, the result of the operation is the result of evaluating the mutation’s top level selection set on the “Mutation Root” object. This selection set should be evaluated serially.

**Comment by danielkwinsor** [comment]
As everyone has said, top level mutations must be serial.  Are you observing that second level mutations are *not* using your custom execution strategy?  If your custom execution strategy is being used, we should close this.

**Comment by dminkovsky** [comment]
Following up on #208. Closing this. Thank you.
