### ISSUE TITLE
Cannot get inline fragment fields from selectionSet

### ISSUE THREAD

**Issue by domarmstrong** [graphql-java/graphql-java#973]
Hi. I am not seeing a way to retrieve the fields of an inline fragment from the DataFetchingEnvironment.
The following query yields `id,type,status` but not `other`. GetFragmentsByName returns nothing. So not sure how i am supposed to access this field?

```graphql
{
    things {
      id
      type
      status
      ...on ChildType {
        other
      }
    }
```

**Comment by bbakerman** [comment]
Care to leave a more complete code example, perhaps a unit test of sorts to explain the code more

**Comment by domarmstrong** [comment]
Yes I'll put something together, havn't had time today

**Comment by domarmstrong** [comment]
I'm resolving the paths now using DataFetchingEnvironment.getFields() to get the Fields/SelectionSets directly. So closing as no issue for me now.
