### ISSUE TITLE
Comprehensible Documentation

### ISSUE THREAD

**Issue by WolfgangFahl** [graphql-java/graphql-java#978]
I tried to use the documentation:
http://graphql-java.readthedocs.io/en/v7/schema.html
in trying to solve https://stackoverflow.com/questions/49324611/github-v4-graphql-api-with-java-using-graphql-java

and got stuck at the need for a 

buildRuntimeWiring function.

For me the example is fully incomprehensible since it seems to use code from https://github.com/graphql-java/graphql-java/blob/master/src/test/groovy/graphql/StarWarsData.groovy#L84

since I have no knowledge of groovy whatsoever i am fully lost.

It would be great to have a groovy-free example and better even a much simpler one.

**Comment by andimarek** [comment]
I see that @kaqqao answered your question.

About the documentation: it is of course not perfect. Please open a new Issue or even a PR if you found a specific problem. If you have general usage questions I can also recommend the gitter channel where u can ask for help https://gitter.im/graphql-java/graphql-java

**Comment by WolfgangFahl** [comment]
Please do not close this issue - my request was specifically for a groovy free and simpler example.

**Comment by bbakerman** [comment]
Sorry but the example is actually in Java 8.  Its meant to be indicative of how you would wire a data fetcher into the runtime wiring.

Its not a tutorial per se.  There are other sections in the documentation that talk about how to write a data fetcher.  

Once you combine a data fetchers together you have your runtime wiring.

Have a look at the next section

http://graphql-java.readthedocs.io/en/v7/execution.html

It hows how to write a DataFetcher.
