### ISSUE TITLE
Improving the performance of DataLoader even further

### ISSUE THREAD

**Issue by bbakerman** [graphql-java/graphql-java#979]
The use of DataLoader has been improved in 7.0 but there are still reports its not as efficient as it could be.

This is a place holder issue to discuss the challenges and ideas on how to fix it.

related issues : 
* https://github.com/graphql-java/graphql-java/issues/831
* https://github.com/graphql-java/graphql-java/issues/760

**Comment by bbakerman** [comment]
The challenges seem to be around the returning of [listTypes] that then recursively call the ExecutionStrategy again once per list.

The expectation from some people is that query be executed in a breath first away and to hold any DataLoads until all fields in the level are dispatched.

To be continued....

**Comment by bbakerman** [comment]
Code attack notes:

The existing `graphql.execution.instrumentation.dataloader.DataLoaderPerformanceTest` should be used for this.

It already has a schema of lists of lists

``` graphql
schema {
    query: Query
}

type Query {
    shops: [Shop]!
}

type Shop {
    id: ID!
    name: String!
    departments: [Department]!
}

type Department {
    id: ID!
    name: String!
    products: [Product]!
}

type Product {
    id: ID!
    name: String!
}
```

We should be able to use this code base and tests to see what more efficient strategies we can come up with

**Comment by ebenoist** [comment]
Is this issue the reason why I'm seeing N+1 calls on a secondary batch join?

I have two batch loaders, one for listings and one for releases. 

```JAVA

  public static <T> CompletableFuture<T> asFuture(Callable<? extends T> callable,
      Executor executor) {
    CompletableFuture<T> future = new CompletableFuture<>();
    executor.execute(() -> {
      try {
        future.complete(callable.call());
      } catch (Throwable t) {
        future.completeExceptionally(t);
      }
    });

    return future;
  }

  BatchLoader<String, Listing> batchListingsLoader = ids -> asFuture(
      ServletScopes.transferRequest(() -> core.getListings(ids).getListingsList()),
      MoreExecutors.directExecutor());

  BatchLoader<String, Release> batchReleasesLoader = ids -> asFuture(
      ServletScopes.transferRequest(() -> lp.getReleases(ids).getReleasesList()),
      MoreExecutors.directExecutor());

  public DataLoaderRegistry get() {
    DataLoaderRegistry registry = new DataLoaderRegistry();

    registry.register("listings", new DataLoader<>(batchListingsLoader));
    registry.register("releases", new DataLoader<>(batchReleasesLoader));

    return registry;
  }
```

And when given my query:
```
{
  user(input: { token: "token"}) {
    feed {
      listing {
        title
        release {
          title
        }
      }
    }
  }
}
```

This results in listings being loaded in bulk correctly, but releases are loaded one at a time, but the load count and batch load count increase on every call.

```
// LISTING CALLS
Statistics{loadCount=24, loadErrorCount=0, batchLoadCount=0, batchLoadExceptionCount=0, cacheHitCount=0}
Mar 20, 2018 12:21:37 PM com.reverb.rql.clients.APIClient lambda$requestURL$0
INFO: REQUEST - url: https://api.reverb.com/api/listings?ids=10958215,10958031,10958027,10958028,10957866,10957526,10957501,10957368,10957323,10957301,10957187,10957125,10957086,10957054,10956732,10956707,10956675,10956629,10956555,10956515,10956496,10956465,10956449,10956437 code: HTTP/1.1 200 OK duration: 94

// RELEASE CALLS
Statistics{loadCount=0, loadErrorCount=0, batchLoadCount=0, batchLoadExceptionCount=0, cacheHitCount=0}
Mar 20, 2018 12:21:37 PM com.reverb.rql.clients.APIClient lambda$requestURL$0
INFO: REQUEST - url: https://lp-api.reverb.com/releases/?ids=c9cce85e-a98d-470d-bad6-a2eb3204cc4d code: HTTP/1.1 200 OK duration: 238
Statistics{loadCount=1, loadErrorCount=0, batchLoadCount=1, batchLoadExceptionCount=0, cacheHitCount=0}
Mar 20, 2018 12:21:38 PM com.reverb.rql.clients.APIClient lambda$requestURL$0
INFO: REQUEST - url: https://lp-api.reverb.com/releases/?ids=b9e4f1bf-3269-41e2-a4e0-f5f442b5378d code: HTTP/1.1 200 OK duration: 127
Statistics{loadCount=2, loadErrorCount=0, batchLoadCount=2, batchLoadExceptionCount=0, cacheHitCount=0}
Mar 20, 2018 12:21:38 PM com.reverb.rql.clients.APIClient lambda$requestURL$0
INFO: REQUEST - url: https://lp-api.reverb.com/releases/?ids=9d6df3b9-880d-4659-8fcf-f5a6cf615249 code: HTTP/1.1 200 OK duration: 43
Statistics{loadCount=3, loadErrorCount=0, batchLoadCount=3, batchLoadExceptionCount=0, cacheHitCount=0}
```

**Comment by andimarek** [comment]
this is our current approach: https://github.com/graphql-java/graphql-java/pull/990

**Comment by siderakis** [comment]
What about passing an object in the Context, so that each node that uses a DataLoader (and any async node, since it's children may use a DataLoader) can signal (in a thread-safe way) that it and all of it's children nodes are done queuing up DataLoader requests. When the root gets the signal that all nodes ready then it dispatches. This cycle repeats until no async requests are pending. 

I know the idea is pretty hand-wavey at this point, I need to look closer at the current implementation to get more specific. Just looking for early feedback.

**Comment by andimarek** [comment]
@bbakerman can this be closed?

**Comment by bbakerman** [comment]
Yup
