### ISSUE TITLE
Make SubscriptionExecutionStrategy extensible

### ISSUE THREAD

**Issue by piotrblasiak** [graphql-java/graphql-java#981]
Would it be possible to change

`private CompletableFuture<ExecutionResult> executeSubscriptionEvent(ExecutionContext executionContext, ExecutionStrategyParameters parameters, Object eventPayload)`

in `SubscriptionExecutionStrategy` to protected instead of private? I need to have that whole method run in a transaction and it is hard to do/incorrect to do that in the reactive chain.

**Comment by piotrblasiak** [comment]
Actually I see now that this does not solve my problem, which is that I need to be able to return a managed JPA entity and have it materialise in graphql-java since it has lazy loaded fields, but since the materialisation/mapping does not happen in a transaction this fails. Any ideas on how to solve this?

**Comment by bbakerman** [comment]
So the subscription model says the first field of the initial request is result Publisher<Object>

Then each time that Publisher emits an event it is mapped over the rest of the original query and turned into ExecutionResults.

So you challenge regarding transactions is not in the graphql-java code but rather in your code that provides the original publisher.

note also that applying 1 transactions across a reactive stream is not really idiomatic.  It is meant to be one or more "events" that happen later.

If you truly need 1 transaction, then I suggest you don't use subscriptions

**Comment by piotrblasiak** [comment]
Thanks for the reply.

You are right that reactive streams and transactions are not compatible so I would either have to do the transaction in the initial publisher or in the last consumer.
So why do I even need a transaction? It is because let´s say I subscribe to changes to a User. The User has lazy-initialized JPA fields like friends() that only gets fetched when the field is called. So then I have a few choices to make this work with graphql:

1) Fetch all available data on all entities I subscribe to every time there is a change (not possible, as there can be friends of friends etc and the graphql subscription query should not have to be limited to n levels).
2) Fetching all the needed fields in the first publisher, but this would require me to pass down graphql logic or something to the first publisher so that it knows what to fetch. Not really intuitive.
3) Emit the ID of the user and fetch & resolve it in the graphql execution strategy where all the fields are being accessed and we can do it within a transaction which is all that is needed for the lazy loading to work.

I did make it work with option 3 by doing the following:

`private CompletableFuture<ExecutionResult> executeSubscriptionEvent(final ExecutionContext executionContext, final ExecutionStrategyParameters parameters, final Object eventPayload) {

        if (eventPayload instanceof Callable) {

                return new Callable<CompletableFuture<ExecutionResult>>(){

                    @Transactional(readOnly = true)
                    @Override
                    public CompletableFuture<ExecutionResult> call() throws Exception {

                        return executeSubscriptionEventImpl(executionContext, parameters, ((Callable) eventPayload).call());
                    }
                }.call(); 
        }
        
        return executeSubscriptionEventImpl(executionContext, parameters, eventPayload);
    }`

And instead of returning the User entity in the datafetcher publisher I return a Callable that has the JPA fetching included:

`.type("Subscriptions", typeWiring -> typeWiring
						.dataFetcher(
								"userChanged",
								environment -> {

									final String id = environment.getArgument("id");

									return Flux.from(publishers.getUserChangedPublisher(id))
											.map(entityUpdatedNotification -> (Callable)() -> userService.getUser(id));
								}
						)
				)`

Does this make sense to you?

**Comment by bbakerman** [comment]
I think you may be leaking your JPA implementation concerns in the graphql arena.

Have you read http://graphql-java.readthedocs.io/en/v7/subscriptions.html

The 1st field gives back a publisher of Foo objects.

``` graphql
      stockQuotes(stockCode:\"IBM') {\n" +
        "            dateTime\n" +
        "            stockCode\n" +
        "            stockPrice\n" +
        "            stockPriceChange\n" +
        "        }\n" +
```

So the publisher that comes from the example `stockQuotes` field will have the rest of the fields applied over it.

So each time you publish an object it will have the query inner body applied

So in your code that that is backed by the Publisher<User> put all your JPA concerns and have that object then be mapped over like any other object.

if you have lazy objects that feed the Pubisher, then put the code that tranforms them into graphql ready objects BEFORE you publish the actual event.  

    Flux.from(publishers.getUserChangedPublisher(id).map(lazyUser -> makeFulluserHereBeforePublishing(lazyUser))

**Comment by piotrblasiak** [comment]
Your suggestion is my option (2) - but that would instead require me to leak graphql into the component that does the publishing :) I am actually quite happy leaking JPA etc into graphql instead as that is much closer to "the surface". And now that I am getting more into this I realise even more that I must have my own SubscriptionExecutionStrategy because I also want to ack notifications etc after they have been written to the websocket etc. Not sure if this is also something you could take into consideration for graphql-java, but worth noting that there might be more people that want to do this so might warrant a change down the line.

**Comment by bbakerman** [comment]
Again I feel that "acks for messages sent" should be in a wrapping publisher + subscriber outside the graphql query layer and in the sending layer of your code.

I am still not convinced that we need to have the ability to extend the execution strategy here

**Comment by haizz** [comment]
@bbakerman I'm having similar problem with subscriptions & transactions except that I'm not using JPA but direct transactional data store API where all the queries are executed against Transaction context object. But the problem is that dataloaders and datafetchers share the same context for the whole subscription session, and there is no way to provide new context for each new subscription Publisher event.

> if you have lazy objects that feed the Pubisher, then put the code that tranforms them into graphql ready objects BEFORE you publish the actual event

GraphQL allows arbitrarily complex queries put into Subscriptions, so there is no way we can predict what data should we load lazily before publishing the event. Could be the whole DB! Kind of diminishes the whole point of GraphQL: to execute only those datafetchers which are sufficient to fulfill whatever query the client requests. 

So what we need is to have some transactional context in datafetchers & dataloaders (implicitly or explicitly) which should be local for each subscription event — and that seems impossible right now.
