### ISSUE TITLE
Relay - SimpleListConnection throws error when empty

### ISSUE THREAD

**Issue by Togrias** [graphql-java/graphql-java#982]
i.e. new SimpleListConnection(emptyList)

**Comment by bbakerman** [comment]
I checked the code and I cant see how this can be the case

I then wrote a small unit test and proved it.

What version are you running etc..and do you have a stack trace

```
    def "empty list"() {
        def testList = []
        def listConnection = new SimpleListConnection(testList)

        expect:
        listConnection != null

    }
```

**Comment by bbakerman** [comment]
Unless we can see evidence otherwise I am going to close this issue
