### ISSUE TITLE
add execution strategy compatibility testkit

### ISSUE THREAD

**Issue by hepin1989** [graphql-java/graphql-java#983]
Make we could easily bench and test its rightness.

**Comment by bbakerman** [comment]
Sounds like a good idea but a lot of work.  TCKs are notoriously hard to write and maintain.

We would of course accept PRs that helped get this in place.

**Comment by exbe** [comment]
@bbakerman if someone decide to tackle this, which approach you would recommend to take?

**Comment by hepin1989** [comment]
@exbe I think the Reactive-Stream TCK is a nice reference.

**Comment by bbakerman** [comment]
@exbe - We are looking at integrating the graphql-cats into graphql-java

This is not yet a proven way to get CTK ability however it might prove out and hence we can wire in other ExecutionStragtergies.

I have  avery early PR almost ready.  Its not finished - its just parsing not execution

**Comment by andimarek** [comment]
closing this issue and tracking it via #988. Cats is our (and the communities) best shot at the moment for this topic.
