### ISSUE TITLE
Add a driver for the graphql-cats TCK

### ISSUE THREAD

**Issue by bbakerman** [graphql-java/graphql-java#988]
https://github.com/graphql-cats/graphql-cats

A recently graphql working group video discussion talked about the power of having a common set of capabilities tested in multiple implementations

The graphql-cats compatibility project is one such effort.

We should try to implement  a driver for the cats tests and see what value it adds.  

It will also allow it to evolve more easily since one more implementation has become involved and hence can feed back and improve the TCK

**Comment by hepin1989** [comment]
refs https://github.com/graphql-java/graphql-java/issues/983 .

**Comment by andimarek** [comment]
closing this issue now as being out of date. the cats project is not active at the moment.
