### ISSUE TITLE
Add built-in Scalars for representing date/datetime in ISO format

### ISSUE THREAD

**Issue by wakeboarder3780** [graphql-java/graphql-java#991]
There are enough people asking for this functionality it's time support for Date and DateTime are added. Other javascript graphQL packages are adding this functionality also, it would be nice if the java variant did also. I would imagine both a Date and a DateTime would suffice to support ISO format.

**Comment by bbakerman** [comment]
@wakeboarder3780 - do you have a reference where other graphql servers are adding this?

**Comment by arcuri82** [comment]
as I had to spend some time to understand how to write my own custom `GraphQLScalarType` for `java.time.ZonedDateTime`, it would have been great if such scalar was already available. Anyway, currently using (adapted from [here](https://github.com/howtographql/graphql-java/blob/master/src/main/java/com/howtographql/hackernews/Scalars.java) and [here](https://github.com/donbeave/graphql-java-datetime/blob/master/graphql-java-datetime/src/main/java/com/zhokhov/graphql/datetime/GraphQLLocalDateTime.java)):

```
class MyDateTimeScalar : GraphQLScalarType("MyDateTime", "DataTime scalar", MyDateTimeScalarCoercing())

private class MyDateTimeScalarCoercing : Coercing<ZonedDateTime, String> {


    override fun serialize(input: Any): String {
        if (input is ZonedDateTime) {
            return input.format(DateTimeFormatter.ISO_ZONED_DATE_TIME)
        }

        val result = convertString(input)
                ?: throw CoercingSerializeException("Invalid value '$input' for ZonedDateTime")

        return result.format(DateTimeFormatter.ISO_ZONED_DATE_TIME)
    }

    override fun parseValue(input: Any): ZonedDateTime {

        return convertString(input)
                ?: throw CoercingParseValueException("Invalid value '$input' for ZonedDateTime")
    }

    override fun parseLiteral(input: Any): ZonedDateTime? {

        if (input !is StringValue){
            return null
        }

        return convertString(input.value)
    }

    private fun convertString(input: Any): ZonedDateTime? {

        if (input is String) {
            return try {
                ZonedDateTime.parse(input)
            } catch (e: DateTimeParseException) {
                null
            }
        }

        return null
    }
}
```

**Comment by andimarek** [comment]
closing as out of date: we are offering a date time scalar via https://github.com/graphql-java/graphql-java-extended-scalars. Please also follow https://github.com/graphql/graphql-spec/issues/579 for a spec solution. thanks
