### ISSUE TITLE
Current Async.eachSequentiallyImpl throws lots of exceptions during non-async execution

### ISSUE THREAD

**Issue by david-tamjidi** [graphql-java/graphql-java#992]
Hey guys,

The current Async.eachSequentiallyImpl has a bug which causes an exception to be thrown pretty much every time it is called when running with the AsyncSerialExecutionStrategy. The exception thrown is NoSuchElementException. Thanks.

Basically the fix is the following:
---------------------------------
private static <T, U> void eachSequentiallyImpl(Iterator<T> iterator, CFFactory<T, U> cfFactory, int index, List<U> tmpResult, CompletableFuture<List<U>> overallResult) {
        if (!iterator.hasNext()) {
            overallResult.complete(tmpResult);
            return;  <------------- NEED TO ADD THIS RETURN HERE!
        }
        CompletableFuture<U> cf;
        try {
            cf = cfFactory.apply(iterator.next(), index, tmpResult);
            Assert.assertNotNull(cf, "cfFactory must return a non null value");
        } catch (Exception e) {
            cf = new CompletableFuture<>();
            cf.completeExceptionally(new CompletionException(e));
        }
        cf.whenComplete((cfResult, exception) -> {
            if (exception != null) {
                overallResult.completeExceptionally(exception);
                return;
            }
            tmpResult.add(cfResult);
            eachSequentiallyImpl(iterator, cfFactory, index + 1, tmpResult, overallResult);
        });
    }

**Comment by bbakerman** [comment]
Can you please outline the bug further.  As in how to reproduce it. 

You have given us the fix but not the exact problem and how to reproduce it.

**Comment by david-tamjidi** [comment]
Please see the attached unit test case as it will help highlight the problem

<------------------------->

import java.util.Map;

import org.junit.Before;
import org.junit.Test;

import graphql.ExecutionInput;
import graphql.ExecutionResult;
import graphql.GraphQL;
import graphql.execution.AsyncSerialExecutionStrategy;
import graphql.schema.GraphQLObjectType;
import graphql.schema.GraphQLSchema;

import static org.junit.Assert.assertEquals;

import static graphql.Scalars.GraphQLInt;
import static graphql.Scalars.GraphQLString;
import static graphql.schema.GraphQLFieldDefinition.newFieldDefinition;
import static graphql.schema.GraphQLObjectType.newObject;

public class TestExceptions {

	private GraphQL fGraphQL;

	@Before
	public void setup() {
		GraphQLObjectType queryType = newObject().name("QueryType")
				.field(newFieldDefinition().name("FIELDS").dataFetcher((env) -> env).type(newObject().name("FieldsType")
						.field(newFieldDefinition().name("FIELD_STRING").type(GraphQLString)
								.dataFetcher((env) -> "TEST"))
						.field(newFieldDefinition().name("FIELD_INT").type(GraphQLInt).dataFetcher((env) -> 1))))
				.build();

		GraphQLSchema schema = new GraphQLSchema(queryType);
		fGraphQL = GraphQL.newGraphQL(schema).queryExecutionStrategy(new AsyncSerialExecutionStrategy()).build();
	}

	@SuppressWarnings("unchecked")
	@Test
	public void simpleQuery() {
		// The idea here is to put a breakpoint on line 75 inside the catch block of eachSequentiallyImpl() of
		// Async.java
		// to see that the exception gets thrown each time or add a print statement temporarily inside the catch block
		// to print out each time the exception gets thrown
		ExecutionResult result = fGraphQL
				.execute(ExecutionInput.newExecutionInput().query("query { FIELDS { FIELD_STRING, FIELD_INT } }"));
		assertEquals("Errors wasnt null: " + result.getErrors(), result.getErrors().size());
		Map<String, Object> data = result.getData();
		assertEquals("TEST", ((Map<String, Object>) data.get("FIELDS")).get("FIELD_STRING"));
		assertEquals(1, ((Map<String, Object>) data.get("FIELDS")).get("FIELD_INT"));
	}
}
<------------------------->

**Comment by david-tamjidi** [comment]
Applying the simple fix from the first comment will stop the exception from being thrown improving performance greatly for the non-async case

**Comment by bbakerman** [comment]
Thanks for the reproductive test...we will look into it
